### ISSUE TITLE
sub SIGNALduino_CheckccConfResponse - make it more robust

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#1015]
## Expected Behavior
- make it more robust so as not to receive a warning

## Actual Behavior
`2021.07.08 12:21:08.516 1: PERL WARNING: Illegal hexadecimal digit '%' ignored at ./FHEM/00_SIGNALduino.pm line 1180.`

https://github.com/RFD-FHEM/RFFHEM/blob/a07524aaeaa41a897af5d952a00927cbd1050cf4/FHEM/00_SIGNALduino.pm#L1174-L1181
## Steps to Reproduce the Problem

  1. feed the sub with an invalid value (example: `216%E857C43023B900070018146C040091`) // value can arise due to an incorrect transmission from serial
  2. look at logfile
  3.

## Specifications

  - Microcontroller:
independent
  - Version (Firmware):
independent

  - Versionmodul (FHEM Module):
3.5.2+20210813

**Comment by HomeAutoUser** [comment]
Wie denkt Ihr über diesen Fall?
Es gibt ja 2 Möglichkeiten vom Handeln.
1) einfach nichts zurück geben, via return und Ende der  Abfrage
oder
2) die Abfrage wiederholen (birgt aber Gefahr, das man bis hin zu einer Schleife kommen könnte, wenn immer falsche Daten kommen)

**Comment by sidey79** [comment]
Spontan würde ich zur Verifizierung der Daten tendieren und ein Return zurück geben.

**Comment by HomeAutoUser** [comment]
@sidey79 ich wollte einen neuen Branch erstellen hier um die Testergebnisse zu sehen. Wurden die Berechtigungen geändert?
Ich würde hierauf https://github.com/HomeAutoUser/RFFHEM/commit/98eeb76cd18f9642caec24e87bee5501fd684b6d aufbauen.

**Comment by sidey79** [comment]
Ich habe nichts geändert. Du kannst in diesem Repo also keinen neuen Branch erstellen?

**Comment by HomeAutoUser** [comment]
Nun klappte es. Ich habe es diesmal so https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository gemacht und nur via GitDesktop ging es nicht. Wer weiss ...

**Comment by HomeAutoUser** [comment]
Dieser Issues wurde erledigt mit https://github.com/RFD-FHEM/RFFHEM/pull/1031
