### ISSUE TITLE
Wrong Autodetected Temp and  Hum Sensor 433 MHZ

### ISSUE THREAD

**Issue by rpsVerni** [RFD-FHEM/RFFHEM#1024]
Hello ,
i have one Sensor it fit not to the  CUL_TCM97001 or is missing in the defintion.

if i want change to sd_WS07 it is not possible.
Not Working.

IT is Label with Mebu 
Modell Number HQ7312-2
art Nr 40283TX

As Auriol i can get the Temp but i miss still the Hum.

i added the definition of the sensor from RTL_433 her it is  a Nexus Sensor.

Model: Auriol
The Temp off Auriol fit to the NExus Temp so it is not complete wrong only the hum is not included.

Model:  NC_WS

It habe correct Hum but wrong temp.

If i Compare Definition Auriol to Nexus and Definition NC_WS to NEXUS.
The Last 2 nibbles of the 9  nibbles are hum and fit to the defenition of NC_WS

And nibble 3 +4 +5 are the temp.

The data is grouped in 9 nibbles:

    [id0] [id1] [flags] [temp0] [temp1] [temp2] [const] [humi0] [humi1]

Please add the Sensor as maybe Mebus 2 in the List model.

THX ahead.

#  Specifications for new sensor / switch / or other device ... 

  - manufacturer:
  - model name:
  - pictures of the device / the board (very helpful)

  
## Specifications 
Manual
https://cdn-reichelt.de/documents/datenblatt/X100/40283FU-WETT.pdf

Protocol definition
https://github.com/merbanan/rtl_433/blob/master/src/devices/nexus.c
###################################
The data is grouped in 9 nibbles:

    [id0] [id1] [flags] [temp0] [temp1] [temp2] [const] [humi0] [humi1]

- The 8-bit id changes when the battery is changed in the sensor.
- flags are 4 bits B 0 C C, where B is the battery status: 1=OK, 0=LOW
- and CC is the channel: 0=CH1, 1=CH2, 2=CH3
- temp is 12 bit signed scaled by 10
- const is always 1111 (0x0F)
- humidity is 8 bits
The sensors can be bought at Clas Ohlsen (Nexus) and Pearl (infactory/FreeTec).
*/
##################################################
Autocreate result#############

AURIOL_77 | T: 24.5

CODE | CUL_TCM97001_77
DEF | CUL_TCM97001_77
 
FUUID | 615d80da-f33f-5fa0-ffa9-b88881df0b9af4d6
LASTInputDev | sdESP
MSGCNT | 40
NAME | AURIOL_77
NR | 706
STATE | T: 24.5
TYPE | CUL_TCM97001
lastH | 0
lastT | 1633520867
sdESP_DMSG | s4DA0F5F0A000
sdESP_MSGCNT | 40
sdESP_Protocol_ID | 0
sdESP_RAWMSG | MS;P0=-2128;P1=320;P5=-1159;P6=-4084;D=16151015151010151010151015151515151010101015101510101010101515151510151015;CP=1;SP=6;R=66;O;m2;
sdESP_RSSI | -41
sdESP_TIME | 2021-10-06 13:47:47

Autocreate result#############

Defintion auriol######
		  # Implementation from Femduino
		  # AURIOL (Lidl Version: 09/2013)
		  #                /--------------------------------- Channel, changes after every battery change      
		  #               /           / ------------------------ Battery state 1 == Ok      
		  #              /           / /------------------------ Battery changed, Sync startet      
		  #             /           / /  ----------------------- Unknown      
		  #            /           / / /    /--------------------- neg Temp: if 1 then temp = temp - 4096
		  #           /           / / /    /---------------------- 12 Bit Temperature
		  #          /           / / /    /               /---------- ??? CRC 
		  #         /           / / /    /               /       /---- Trend 10 == rising, 01 == falling
		  #         0101 0101  1 0 00   0001 0000 1011  1100  01 00
		  # Bit   

Defintion auriol######

Definition######## NC_WS
   # Implementation from Femduino
      # Protocol prologue start everytime with 0101
      # PEARL NC7159, LogiLink WS0002
      #                 /--------------------------------- Sensdortype      
      #                /     / ---------------------------- ID, changes after every battery change      
      #               /     /          /--------------------- Battery state 0 == Ok
      #              /     /          /  / ------------------ forced send      
      #             /     /          /  /  / ---------------- Channel (0..2)      
      #            /     /          /  /  /   / -------------- neg Temp: if 1 then temp = temp - 2048
      #           /     /          /  /  /   /   / ----------- Temp
      #          /     /          /  /  /   /   /             /-- unknown
      #         /     /          /  /  /   /   /             /  / Humidity
      #         0101  0010 1001  0 0 00   0 010 0011 0000   1 101 1101
      # Bit     0     4         12 13 14  16 17            28 29    36
      #$def = $modules{CUL_TCM97001}{defptr}{$idType3};

Definition######## NC_WS

  - Microcontroller:
  - Version (Firmware):
  

  - Versionmodul (FHEM Module):
  
<!--( can be found here: devicename -> Internals -> versionmodul ) --
[rtl_433.0.Nexus-TH-77.txt](https://github.com/RFD-FHEM/RFFHEM/files/7293511/rtl_433.0.Nexus-TH-77.txt)
>

**Comment by sidey79** [comment]
I dont think that this ist a issue of Signalduino.

Can you confirm that the RF Signal is processed by the Signalduino module and send to CUL_TCM97001 module correctly?

**Comment by rpsVerni** [comment]
> Ich denke, diese Nachricht:
> 
> ```
> MS;P0=-2128;P1=320;P5=-1159;P6=-4084;D=16151015151010151010151015151515151010101015101510101010101515151510151015;CP=1;SP=6;R=66;O;m2;
> ```
> 
> passt zum Protokoll 7 (14_SD_WS07.pm). Allerdings passen die Timings nicht 100%ig. Wenn ich P1 ändere in P1=495 wird die Nachricht folgendermaßen dekodiert:
> 
> ```
> DEF        SD_WS07_TH_3
> READINGS:
>      2021-10-06 18:07:06   batteryState    ok
>      2021-10-06 18:07:06   channel         3
>      2021-10-06 18:07:06   humidity        10
>      2021-10-06 18:07:06   state           T: 24.5 H: 10
>      2021-10-06 18:07:06   temperature     24.5
> ```
> 
> Wir haben folgende Typen bei Protokoll 7 kommentiert:
> 
> `'EAS800z, FreeTec NC-7344, HAMA TS34A, Auriol AFW 2 A1'`
> 
> und diese Notizen im Modul 14_SD_WS07.pm:
> 
> ```
>   # 0   4    8     12            24    28       36
>   # 00110110 1010  000100000010  1111  00111000 0000  eas8007
>   # 01110010 1010  000010111100  1111  00000000 0000  other device from anfichtn
>   # 11010010 0000  000000010001  1111  00101000       other device from elektron-bbs
>   # 01100011 1000  000011101010  1111  00001010       other device from HomeAuto_User SD_WS07_TH_631
>   # 11101011 1000  000010111000  1111  00000000       other device from HomeAuto_User SD_WS07_T_EB1
>   # 11000100 1000  000100100010  1111  00000000       other device from HomeAuto_User SD_WS07_T_C41
>   # 01100100 0000  000100001110  1111  00101010       hama TS36E from HomeAuto_User - Bat bit identified
>   # Long-ID  BCCC  TEMPERATURE    ??   HUMIDITY       B=Battery, C=Channel
> ```




MS;P2=-2110;P3=349;P4=-1113;P5=-4069;D=35343234343232343232343434343434343232323432323432323232323434343432343232;CP=3;SP=5;R=61;O;m2;




Müsste das Ergeben laut RTL_433.
Temp 23,7 °C  Hum 11% Kanal 1 Bat okay .

Be

Heute Mittag war es aber aber wie du geschrieben hast Kanal 3.



Jetzt Meine Frage wie bekomme ich jetzt meinen Sensor zu deinem Modul "SD_WS07_TH_3" ?


Habe ich heute schon probiert hat leider nicht funktioniert.
Er erstellt ihn immer wieder als CUL_90007.


Anbei habe ich schon einen  Sensor mit  SD_WS07_TH3
Und  SD_WS07_TH1.....

Bei Wunsch kann ich dir auch mal ein paar Sequenzen mitschneiden.



########################
defmod SD_WS07_TH_3 SD_WS07 SD_WS07_TH_3
attr SD_WS07_TH_3 userattr max-deviation-hum:1,2,3,4,5,6,7,8,9,10,15,20,25,30,35,40,45,50 offset-hum
attr SD_WS07_TH_3 event-min-interval .*:300
attr SD_WS07_TH_3 event-on-change-reading .*
attr SD_WS07_TH_3 room SD_WS07

setstate SD_WS07_TH_3 Defined
setstate SD_WS07_TH_3 2021-10-06 08:48:54 batteryState ok
setstate SD_WS07_TH_3 2021-10-06 08:48:54 channel 3
setstate SD_WS07_TH_3 2021-10-06 08:48:54 humidity 8
setstate SD_WS07_TH_3 2021-10-06 08:48:54 state T: 21.9 H: 8
setstate SD_WS07_TH_3 2021-10-06 08:48:54 temperature 21.9

###############################################

**Comment by elektron-bbs** [comment]
Probiere mal bitte mit dieser SD_ProtocolData.pm (umbenennen!):

[SD_ProtocolData.pm.txt](https://github.com/RFD-FHEM/RFFHEM/files/7303263/SD_ProtocolData.pm.txt)

Nach Neustart von FHEM und Aktivierung von Protokoll 7.1 müsste der Sensor SD_WS07_TH_3 eigentlich besser empfangen werden.

Ich bräuchte dann aber noch einige RAWMSG um evtl. die Timings noch genauer anzupassen.

**Comment by rpsVerni** [comment]
> Probiere mal bitte mit dieser SD_ProtocolData.pm (umbenennen!):
> 
> [SD_ProtocolData.pm.txt](https://github.com/RFD-FHEM/RFFHEM/files/7303263/SD_ProtocolData.pm.txt)
> 
> Nach Neustart von FHEM und Aktivierung von Protokoll 7.1 müsste der Sensor SD_WS07_TH_3 eigentlich besser empfangen werden.
> 
> Ich bräuchte dann aber noch einige RAWMSG um evtl. die Timings noch genauer anzupassen.


Anbei ein paar Logs von dem Sensor.... alt....

[MEBUS_77-2021-10-06.log](https://github.com/RFD-FHEM/RFFHEM/files/7303521/MEBUS_77-2021-10-06.log)
[PFR_130_77-2021-10-06.log](https://github.com/RFD-FHEM/RFFHEM/files/7303522/PFR_130_77-2021-10-06.log)
[AURIOL_77-2021-10-06.log](https://github.com/RFD-FHEM/RFFHEM/files/7303523/AURIOL_77-2021-10-06.log)
[AURIOL_77-2021-10-07.log](https://github.com/RFD-FHEM/RFFHEM/files/7303524/AURIOL_77-2021-10-07.log)

**Comment by sidey79** [comment]
@elektron-bbs 

Danke, jetzt kann ich nicht mehr ruhig schlafen mit dem Wissen, was so alle getrieben wird mit der MatchList und dem Clients von $hash.

So grundsätzlich klingelt da aber was, dass Daten (Eurochron) an SD_WS übergeben werden sollten, weil es dazu mehrere Signalmodulationen gibt.

Wenn der Maintainer des CUL_TCM97001 nicht mehr tätig wird, dann gibt es dafür ja Lösungen. :)

**Comment by rpsVerni** [comment]
> P7#


sind nur 23 Einträge von heute morgen drin
die Mehrheit ist ohne #7

[neu 2txt.txt](https://github.com/RFD-FHEM/RFFHEM/files/7305573/neu.2txt.txt)

**Comment by elektron-bbs** [comment]
> Dann muss ich mir wohl selbst das ein model im cul_tcm97001 schreiben damit der alle Werte liefert.

Mehr Werte als die bei dem von mir eingerichtetem Protokoll (SD_WS07_TH_3) wirst du auch mit dem Modul CUL_TCM97001 nicht bekommen.
Der Sensor sendet nur Temperatur, Feuchte, Batteriebit und evtl. ein Bit für Sendmode (auto/manuell). Letzteres gibt es nicht bei allen Sensoren die dieses Protokoll verwenden. Deshalb wiederhole ich meine Frage nochmal:
Hat der Sensor einen Taster, beschriftet mit TX oder ähnlich?

**Comment by elektron-bbs** [comment]
Leider seit über einem Monat keine Antwort von @rpsVerni :-(

Wollen wir die Definition für diesen Sensor "Mebus Modell Number HQ7312-2" trotzdem übernehmen?

**Comment by sidey79** [comment]
> Leider seit über einem Monat keine Antwort von @rpsVerni :-(
> 
> Wollen wir die Definition für diesen Sensor "Mebus Modell Number HQ7312-2" trotzdem übernehmen?

Ja sollten wir machen

**Comment by rpsVerni** [comment]
> Leider seit über einem Monat keine Antwort von @rpsVerni :-(
> 
> Wollen wir die Definition für diesen Sensor "Mebus Modell Number HQ7312-2" trotzdem übernehmen?

Hallo Zusammen,

ich habe mir jetzt ein paar Gedanken gemacht.

Ich konnte leider nicht ganz nachvollziehen was genau definiert wurde.
Daher kann ich kein Antwort geben ob es Sinn macht die Definition beizubehalten.


Ich war immer der Meinung den Sensor den ich euch zur Verfügung stellen wollte ist mit dem Protokoll CUL_TCM97001 .
Definiert.

Falls ihr natürlich was sinnvolles aus den Protokollen die ich euch zur Verfügung gestellt habe auslesen konntet bin ich natürlich dafür.

Gruß 
Verni

**Comment by elektron-bbs** [comment]
Ich habe einen neuen Branch für diesen Sensor erstellt: master_SD_WS07_HQ7312

Führe bitte folgenden Update-Befehl aus:

`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/master_SD_WS07_HQ7312/controls_signalduino.txt`

Nach einem Neustart von FHEM und Aktivierung des Protokolls 7.1 sollte es dir einen Sensor "SD_WS07_TH_3" anlegen, sofern er noch nicht angelegt war.
Dann bitte beobachten und meine Frage hier https://github.com/RFD-FHEM/RFFHEM/issues/1024#issuecomment-938700726 beantworten.

**Comment by elektron-bbs** [comment]
Kann es sein, das @rpsVerni meine Posts nicht empfängt und deshalb nicht reagiert?

**Comment by rpsVerni** [comment]
Gruß zusammen
###########
update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/master_SD_WS07_HQ7312/controls_signalduino.txt
ausgeführt.

Werde in ein paar tagen Rückmelden ob  es Probleme gab.

Command lief aber soweit durch ohne Problem.

###############
War bereits angelegt.

Gerade bekommt man wieder extrem viel Müll per Mail.
Daher erst jetzt mitbekommen das ihr weiter gemacht habt.
###################################
2021-10-06_08:47:35 SD_WS07_TH_3 T: 21.7 H: 8
2021-10-06_08:47:35 SD_WS07_TH_3 temperature: 21.7
2021-10-06_08:47:35 SD_WS07_TH_3 humidity: 8
2021-10-06_08:47:35 SD_WS07_TH_3 batteryState: ok
2021-10-06_08:47:35 SD_WS07_TH_3 channel: 3
2021-10-06_08:47:35 SD_WS07_TH_3 DMSG: P7#4DA0D9F080
2021-10-06_08:47:35 SD_WS07_TH_3 RAWMSG: 200
2021-10-06_08:48:54 SD_WS07_TH_3 T: 21.9 H: 8
2021-10-06_08:48:54 SD_WS07_TH_3 temperature: 21.9
2021-10-06_08:48:54 SD_WS07_TH_3 RAWMSG: 200
2021-10-06_08:48:54 SD_WS07_TH_3 DMSG: P7#4DA0DBF080

**Comment by elektron-bbs** [comment]
Hallo @rpsVerni 
ich denke, 3 Wochen sollten für die Beobachtungen reichen. Können wir die Definition übernehmen, oder gab es noch Probleme?

**Comment by rpsVerni** [comment]
> Hallo @rpsVerni ich denke, 3 Wochen sollten für die Beobachtungen reichen. Können wir die Definition übernehmen, oder gab es noch Probleme?

Hallo Stand heute nein , du hast gute Arbeit geleistet.
