### ISSUE TITLE
Support for Lightvision Standard 6er LED Spot (EAN 4251512601018)

### ISSUE THREAD

**Issue by hekokkong** [RFD-FHEM/RFFHEM#1046]
Support/Implementation requested for Lightvision Standard 6er LED Spots.  The product comes  with a 433MHz remote controllable LED Driver. Using the remote causes my 433Mhz Signalduino to autocreate certain IT devices, but resending these commands shows no effects. Here's a loglevel 5 log on what happens when the device is turned on and off via the remote. I am happy to support whereever I can. English and German spoken.

Pressing ON:

2021.10.25 18:00:16 5: sduino: Read, RAW rmsg: Ms;��;�ͬ;�Ȅ;���;�̈́;d�#AQQQSCCASASCAQSCCCCCCASA;C1;S2;R1A;O;s1;m0;
2021.10.25 18:00:16 4: sduino: Read, msg READredu: MS;P1=359;P2=-11341;P3=1096;P4=-373;P5=-1101;D=12341515151534343415341534341515343434343434341534;CP=1;SP=2;R=26;O;s=1;m0;
2021.10.25 18:00:16 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:00:16 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:00:16 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1
2021.10.25 18:00:16 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759FD length 24  RSSI = -61
2021.10.25 18:00:16 5: sduino: Dispatch, i8759FD, test ungleich: disabled
2021.10.25 18:00:16 5: sduino: Dispatch, i8759FD, -61 dB, dispatch
2021.10.25 18:00:16 5: sduino: dispatch i8759FD
2021.10.25 18:00:17 4: sduino IT: message "i8759FD" (7)
2021.10.25 18:00:17 4: sduino IT: msgcode "" (0) bin = 100001110101100111111101
2021.10.25 18:00:17 5: sduino IT: EV1527 housecode = 1527x8759f  onoffcode = 1101
2021.10.25 18:00:17 4: sduino IT: 1527x8759f not defined (Switch code: 1101)
2021.10.25 18:00:17 5: sduino: Read, RAW rmsg: Ms;�܁;�Ь;���;���;�ф;D444444444444444;C1;S2;R1A;O;m1;
2021.10.25 18:00:17 4: sduino: Read, msg READredu: MS;P1=348;P2=-11344;P3=1086;P4=-381;P5=-1105;D=12341515151534343415341534341515343434343434341534;CP=1;SP=2;R=26;O;m1;
2021.10.25 18:00:17 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:00:17 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:00:17 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1
2021.10.25 18:00:17 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759FD length 24  RSSI = -61
2021.10.25 18:00:17 5: sduino: Dispatch, i8759FD, test gleich
2021.10.25 18:00:17 4: sduino: Dispatch, i8759FD, Dropped due to short time or equal msg
2021.10.25 18:00:17 5: sduino: Read, RAW rmsg: Ms;��;�Ь;���;��;�؄;D444444444444444;C1;S2;R1A;e;m2;
2021.10.25 18:00:17 4: sduino: Read, msg READredu: MS;P1=363;P2=-11344;P3=1086;P4=-372;P5=-1112;D=12341515151534343415341534341515343434343434341534;CP=1;SP=2;R=26;e;m2;
2021.10.25 18:00:17 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:00:17 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:00:17 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1
2021.10.25 18:00:17 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759FD length 24  RSSI = -61
2021.10.25 18:00:17 5: sduino: Dispatch, i8759FD, test gleich
2021.10.25 18:00:17 4: sduino: Dispatch, i8759FD, Dropped due to short time or equal msg
2021.10.25 18:00:17 5: sduino: Read, RAW rmsg: Ms;��;�Ь;���;��;�؄;D444444444444444;C1;S2;R1A;e;m3;
2021.10.25 18:00:17 4: sduino: Read, msg READredu: MS;P1=363;P2=-11344;P3=1086;P4=-372;P5=-1112;D=12341515151534343415341534341515343434343434341534;CP=1;SP=2;R=26;e;m3;
2021.10.25 18:00:17 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:00:17 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:00:17 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1
2021.10.25 18:00:17 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759FD length 24  RSSI = -61
2021.10.25 18:00:17 5: sduino: Dispatch, i8759FD, test gleich
2021.10.25 18:00:17 4: sduino: Dispatch, i8759FD, Dropped due to short time or equal msg

Pressing Off a while later:

2021.10.25 18:32:13 5: sduino: Read, RAW rmsg: Ms;���;�ށ;�ل;���;�׬;D%A####AAA#A#AA##AAAAA#AAA;C2;S5;RF3;e;b10;m0;
2021.10.25 18:32:13 4: sduino: Read, msg READredu: MS;P1=-389;P2=350;P3=-1113;P4=1075;P5=-11351;D=25412323232341414123412341412323414141414123414141;CP=2;SP=5;R=243;e;b=16;m0;
2021.10.25 18:32:13 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:32:13 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:32:13 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1
2021.10.25 18:32:13 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759F7 length 24  RSSI = -80.5
2021.10.25 18:32:13 5: sduino: Dispatch, i8759F7, test ungleich: disabled
2021.10.25 18:32:13 5: sduino: Dispatch, i8759F7, -80.5 dB, dispatch
2021.10.25 18:32:13 5: sduino: dispatch i8759F7
2021.10.25 18:32:13 4: sduino IT: message "i8759F7" (7)
2021.10.25 18:32:13 4: sduino IT: msgcode "" (0) bin = 100001110101100111110111
2021.10.25 18:32:13 5: sduino IT: EV1527 housecode = 1527x8759f  onoffcode = 0111
2021.10.25 18:32:13 4: sduino IT: 1527x8759f not defined (Switch code: 0111)
2021.10.25 18:32:13 5: sduino: Read, RAW rmsg: Ms;���;�ށ;�ل;���;�׬;D%A####AAA#A#AA##AAAAA#AAA;C2;S5;RF3;e;m1;
2021.10.25 18:32:13 4: sduino: Read, msg READredu: MS;P1=-389;P2=350;P3=-1113;P4=1075;P5=-11351;D=25412323232341414123412341412323414141414123414141;CP=2;SP=5;R=243;e;m1;
2021.10.25 18:32:13 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:32:13 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:32:13 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1
2021.10.25 18:32:13 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759F7 length 24  RSSI = -80.5
2021.10.25 18:32:13 5: sduino: Dispatch, i8759F7, test gleich
2021.10.25 18:32:13 4: sduino: Dispatch, i8759F7, Dropped due to short time or equal msg
2021.10.25 18:32:13 5: sduino: Read, RAW rmsg: Ms;���;�ށ;�ل;���;�׬;D%A####AAA#A#AA##AAAAA#AAA;C2;S5;RF3;e;m2;
2021.10.25 18:32:13 4: sduino: Read, msg READredu: MS;P1=-389;P2=350;P3=-1113;P4=1075;P5=-11351;D=25412323232341414123412341412323414141414123414141;CP=2;SP=5;R=243;e;m2;
2021.10.25 18:32:13 4: sduino: Parse_MS, Matched MS protocol id 3 -> chip xx2260 / xx2262
2021.10.25 18:32:13 5: sduino: Parse_MS, Starting demodulation at Position 2
2021.10.25 18:32:13 5: sduino: Parse_MS, dispatching bits: 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 0 1 1 1
2021.10.25 18:32:13 4: sduino: Parse_MS, Decoded matched MS protocol id 3 dmsg i8759F7 length 24  RSSI = -80.5
2021.10.25 18:32:13 5: sduino: Dispatch, i8759F7, test gleich
2021.10.25 18:32:13 4: sduino: Dispatch, i8759F7, Dropped due to short time or equal msg
2021.10.25 18:32:13 5: sduino: Read, RAW rmsg: Ms;���;�ށ;�ل;���;�׬;d%A####AAA#A#AA##AAAAA#AA@;C2;S5;RF3;e;m3;
2021.10.25 18:32:13 4: sduino: Read, msg READredu: MS;P1=-389;P2=350;P3=-1113;P4=1075;P5=-11351;D=2541232323234141412341234141232341414141412341414;CP=2;SP=5;R=243;e;m3;

After a while, the following IT devices have been auto added:

IT_1527x8759f |   | on | off
IT_1527xf3ff2 |   | on | off
IT_1527xfdce5 |   | on | off

Here's the product links:
https://lightvision.gmbh/standard-system/standard-komplettsets/17/standard-komplettset-6er-9er
https://www.amazon.de/warmweiss-Terrassenbeleuchtung-Wintergarten-Komplettset-Minispots/dp/B07C3PTP1R

**Comment by elektron-bbs** [comment]
Ich schätze, das liegt an der nicht passenden Pulslänge. Diese ist normalerweise 250. Du benötigst wahrscheinlich einen Wert im Bereich von 350 bis etwa 380. Probiere bitte mal mit dem Attribut "ITclock".

Device specific help:
```
ITclock
ITclock ist die kleinste Basispulslänge beim Senden des Intertechno V1 Protokolls.
Ein Signal beim IT-Protokoll besteht immer aus einer Sequenz von HIGH und LOW, die mit einer bestimmten Pulslänge gesendet werden. Typischerweise stehen die Pulslängen dabei im Verhältnis 1:3 (also z.B. LOW=Basispulslänge und HIGH=3*Basispulslänge).
Voreingestellt ist 250 für Original-IT-Geräte. Andere Hersteller verwenden manchmal andere Werte, dennoch sollte ITclock nur dann verändert werden, wenn es Probleme beim Schalten mit Fhem gibt. Achten Sie in dem Fall auch darauf, ob nicht vielleicht das Signal zu schwach ist oder gestört wird, um regelmässig empfangen zu werden.
- Hier ist eine Beschreibung für die Ermittlung des ITclock beim Signalduino: Nach Drücken einer Taste an der Fernbedienung steht die empfangene raw Nachricht im log und in der device-Ansicht des IT-device, also etwa
MS;P0=357;P2=-1128;P3=1155;P4=-428;P5=-11420;D=05023402020202020202020202020202020202023402340234;CP=0;SP=5;
Die Ziffer hinter "CP=" gibt die Pattern-Nr des clock an, also z.B. folgt aus CP=0 --> P0, das am Anfang der Nachricht definiert ist, hier ist also die clock 357.
```

**Comment by hekokkong** [comment]
Das hat funktioniert.

Steuercode ist das letzte Hexbyte, Gerätecode die 5 Hexbytes vor dem Steuercode.

Definition geht wie folgt: 

define <name> IT 1527x<gerätecode> 1101 0111 1110 0110
attr <name> ITClock 350
attr <name>  userV1setCodes dimMin:1100 dimMax:1011 dim20:0010 dim40:1001 dim60:1000 dim80:1010 s1:0100 s2:0001

Steuerung funktioniert damit zuverlässig. Was nicht zuverlässig funktioniert ist die Erkennung der Fernbedienungscodes durch den Signalduino, was die Steuerung durch Signalduino und Fernbedienung aber nicht beeinträchtigt.

Ist mein erster Beitrag in Github. Kann diese Erkenntnis irgendwie in FHEM einfließen so dass das Gerät u.U. mal automatisch erkannt werden kann?

**Comment by elektron-bbs** [comment]
Wir betreuen das dafür zuständige Modul 10_IT.pm nicht.
Du müsstest deine Erkenntnisse im FHEM-Forum https://forum.fhem.de/index.php/board,24.0.html veröffentlichen.

**Comment by sidey79** [comment]
@hekokkong 
Können wir hier noch etwas für dich tun?

**Comment by hekokkong** [comment]
passt alles, den Rest mache ich im Forum. DAnke
