### ISSUE TITLE
Module in SVN aktualisieren

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#1056]
1. 

- [x] FHEM/00_SIGNALduino.pm
- [x] FHEM/lib/SD_ProtocolData.pm
- [x] FHEM/lib/SD_Protocols.pm

2.

- [x] FHEM/10_FS10.pm

- [x] FHEM/14_SD_WS.pm

- [x] FHEM/14_SD_WS07.pm

- [x] FHEM/14_SD_WS09.pm

- [x] FHEM/90_SIGNALduino_un.pm

- [x] FHEM/14_SD_UT.pm

- [x] FHEM/14_SD_BELL.pm

--
not changed
- [x] FHEM/10_SD_GT.PM
- [x] FHEM/14_Hideki.pm
- [x] FHEM/14_FLAMINGO.pm

**Comment by elektron-bbs** [comment]
An folgenden Modulen wurde nichts verändert:
10_SD_GT.pm
14_Hideki.pm
14_FLAMINGO.pm

**Comment by sidey79** [comment]
@HomeAutoUser 
@elektron-bbs 

So ich habe das SIGNALduino Modul aktualisiert. Siehe Revision 25482
https://svn.fhem.de/trac/changeset/25482/

**Comment by HomeAutoUser** [comment]
Die Module  FHEM/14_SD_UT.pm / FHEM/14_SD_BELL.pm werden aktualisiert wenn wir das mit dem https://github.com/RFD-FHEM/RFFHEM/pull/1060 durch haben.

**Comment by sidey79** [comment]
@HomeAutoUser 

Die könnte man ja dann erneut aktualisieren oder?

**Comment by HomeAutoUser** [comment]
;-) Ich kann sie jederzeit aktualisieren *grins*
Ich möchte nur verhindern, das wir im SVN etwas neueres haben als hier im Github Branch um keine Verwirrung zu stiften.

**Comment by sidey79** [comment]
Dazu einfach aus dem tag die Module aktualisieren

https://github.com/RFD-FHEM/RFFHEM/tree/3.5.2


Oh, ich muss da was korrigieren.. mist..

**Comment by HomeAutoUser** [comment]
Modul 14_SD_BELL habe ich abgehakt. Dieses ist identisch und schon im SVN.

**Comment by sidey79** [comment]
Supi, ich bin auch fertig, sobald 14_SD_UT erledigt ist, können wir das issue schließen

**Comment by HomeAutoUser** [comment]
:-D Modul 14_SD_UT.pm ist auch identisch im SVN ohne unsere Änderung welche in Github noch folgt.
Das kann ich dann nach Übernahme ja einzeln aktualisieren im SVN.
Da hatte ich schon mal das SVN angeglichen von beiden Modulen.
