### ISSUE TITLE
FLAMINGO fehlt beim Attribut room die Auswahlmöglichkeit

### ISSUE THREAD

**Issue by Burny4600** [RFD-FHEM/RFFHEM#1079]
https://forum.fhem.de/index.php/topic,123213.0.html

Im Modul fehlt die Auswahlmöglichkeit der Räume und das Atributt ignore.

**Comment by HomeAutoUser** [comment]
@Burny4600 
> https://forum.fhem.de/index.php/topic,123213.0.html
> 
> Im Modul fehlt die Auswahlmöglichkeit der Räume und das Atributt ignore.

Du schreibst, das das Attribut ignore fehlt? Hast du dich dort verschaut? Das Attribut ist einstellbar mit dem Wert 0 oder 1.
