### ISSUE TITLE
14_Hideki.pm: Beim Hideki Windsensor DV928 passt die Zuordnung der Windrichtung nicht

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#1087]
## Expected Behavior
https://forum.fhem.de/index.php/topic,126712.msg1213585.html#msg1213585

## Actual Behavior
https://forum.fhem.de/index.php/topic,126712.msg1213102.html#msg1213102
```
  0  22.5  45   67.5  90  112.5 135  157.5 180 202.5 225  247.5 270 292.5 315  337.5
"N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW"
 0    1     2    3    4    5     6    7    8    9    10   11   12    13   14   15   soll
 0    8     9   11   10   14    15   13   12    4     5    7    6     2    3    1   ist
```

## Specifications

  - Microcontroller:
  - Version (Firmware):

  - Versionmodul (FHEM Module):

**Comment by Ralf9** [comment]
Ich hab dafür einen commit in einen neuen branch gemacht
https://github.com/RFD-FHEM/RFFHEM/commit/6f7f3df58821ebd5595b5712472c596348cfb6af

**Comment by HomeAutoUser** [comment]
Sollte hiermit https://github.com/RFD-FHEM/RFFHEM/pull/1099 eingearbeitet sein.
Wenn noch etwas auffällt oder gewünscht ist, bitte melden @Ralf9
