### ISSUE TITLE
IT Unitcode 0001 funktioniert nur zu 50%

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#109]
Das schalten von Steckdosen mit Unitcode 0000 funktioniert nicht stabil 

https://forum.fhem.de/index.php?topic=58468.new;topicseen#new

**Comment by Ralf9** [comment]
Uns holt gerade ein altes Problem wieder ein. Hast Du eine Idee an was es liegen könnte.
Kannst Du es bei Dir nachvollziehen?
https://forum.fhem.de/index.php/topic,79019.msg710073.html

**Comment by sidey79** [comment]
Ich habe es nie analysiert.
Ist zwar unschön, aber kann man nicht einfach einen anderen unitcode verwenden?

**Comment by Ralf9** [comment]
Kann man bei der Fernbedienung den unitcode einstellen?

**Comment by sidey79** [comment]
Ich weiss nicht, wie ich den Code an der FB verändern kann..
