### ISSUE TITLE
Implement Protocol #7 

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#11]
2015.06.28 07:54:01.913 1: DEBUG>SDuino: incomming message: (MU;P0=484;P1=-4020;P2=-1964;P3=-992;D=01020203030203030302030203030303030202020303020303020202020303030303030303010202030302030303020302030303030302020203030203030202020203030303030303030103;CP=0;)

DEBUG>SDuino: processing unsynced message

DEBUG>SDuino: extracted  pattern 0 484 

DEBUG>SDuino: extracted  pattern 1 -4020 

DEBUG>SDuino: extracted  pattern 2 -1964 

DEBUG>SDuino: extracted  pattern 3 -992

**Comment by sidey79** [comment]
Sync fact 8,3 is not detected

**Comment by sidey79** [comment]
Decoding:

 Clock: 492, 969, -1948, -4004

Bit 0:  492, -969     (factor: 1,-2)
Bit 1:  492, -1948   (factor: 1,-4)
Sync: 492,-4020    (factor 1,8)
   
Pulslength: 74
      id = bintodec   bit 0 to 9;
      channel = bit 10,11   + 1;
      temperature = bir 12 to  23 / 10;

**Comment by sidey79** [comment]
Log output at: https://github.com/anfichtn/test?files=1

**Comment by anfichtn** [comment]
New receiver recived. Logfiles will be updated shortly.

**Comment by anfichtn** [comment]
Logfiles updated.
But no reciving of protocol "M7".

**Comment by sidey79** [comment]
Logfile has no messages from the arduino. Seems to be something wrong in communication or the arduino is crashed

**Comment by sidey79** [comment]
Data looks like:

		#Eurochron EAS 800
				4	 8      12                      24      28               36
	      #          0011 0110 1010  000100000010  1111  00111000 Kanal 3, 25.8 Grad, 56%
	      #          0011 0110 1010  000011110011  1111  00111000 Kanal 3, 24.3 Grad, 56%
	      #          0011 0001 1001  000100001001  1111  00111101 Kanal 2, 26.5 Grad, 61%
	      #          0011 1000 1000  000100000011  1111  01000000 Kanal 1
	      
	      #                     ID?  CHN       TMP                ??     HUM

**Comment by sidey79** [comment]
@anfichtn : Test again with current version of signalduino

**Comment by Ralf9** [comment]
Die Prüfung "if ($l == 10)" habe ich eingebaut da es bei mir ab und zu auch Nachrichten mit einer Länge von 6 und 7 gibt:

2015.09.16 23:44:21 3: SIGNALduino_ID7_Parse  EAS800z (u7FFFFF0) length: 6
2015.09.16 23:46:52 3: SIGNALduino_ID7_Parse  EAS800z (u77FFFFF0) length: 7
2015.09.16 23:47:32 3: SIGNALduino_ID7_Parse  EAS800z (u75690D3F400) length: 10

**Comment by sidey79** [comment]
Vielleicht kannst Du noch mal mit Verbose 5 und auch dem Debug Attribut das Signal empfangen und die Log Ausgabe Posten.


Ich vermute, das Signal hat 36 Bit und ich fülle es dann auf volle bytes auf.

Somit könnte man dann in der Regex auf 8 Hex Stellen und die letzte 0 prüfen.
Vielleicht finden wir auch noch einen validen Header.

**Comment by Ralf9** [comment]
wie kann ich Dir eine log Datei schicken, ich kann hier keine txt-Datei anhängen und im fhem-forum kann ich bei einer privaten Nachricht keine Anlage hinzufügen.

**Comment by Ralf9** [comment]
Ich habe den EAS800z mal in die Gefriertruhe gelegt:

SIGNALduino_ID7_Parse  EAS800z (u7569FE7F340)  -> ca -1,2 Grad
EAS800z converted to bits: 0101 0110 1 001 111111100111 1111 00110100 0000
EAS800z decoded protocolid: 7 sensor id=49, channel=2, temp=407.1, hum=52, bat=ok

SIGNALduino_ID7_Parse  EAS800z (u7569FE0F3D0)  -> ca -3,2 Grad
EAS800z converted to bits: 0101 0110 1 001 111111100000 1111 00111101 0000
EAS800z decoded protocolid: 7 sensor id=49, channel=2, temp=406.4, hum=61, bat=ok

SIGNALduino_ID7_Parse  EAS800z (u7569FD9F3D0)  -> ca -5,2 Grad
EAS800z converted to bits: 0101 0110 1 001 111111011001 1111 00111101 0000
EAS800z decoded protocolid: 7 sensor id=49, channel=2, temp=405.7, hum=61, bat=ok

**Comment by sidey79** [comment]
Ah,  so etwas in der Art hatte ich erwartet.

Man müsste für die negativen Temperaturen wohl 4095 abziehen. Also 

if temp>100 temp=temp-4095
Vermutlich braucht man auch nur das 1. Bit prüfen.

Das 1. Nibble scheint auch ein Teil von der Sensor ID zu sein. Das 2. ist mir dann unschlüssig.

Vermutlich ist das Bit vor dem Kanal die Batterie Info.

**Comment by Ralf9** [comment]
Ich habe an der 14_SIGNALduino_ID7.pm ein paar Änderungen vorgenommen.
Ich habe ein push in Deinen Zweig "dev-proto7" versucht ich habe aber eine Fehlermeldung bekommen. Ich habe es wie folgt versucht:

  git clone -b dev-proto7 https://github.com/RFD-FHEM/RFFHEM.git
  git add 14_SIGNALduino_ID7.pm
  git commit -m "Daten ignorieren, wenn humidity groesser 100"
  git push origin master

Ich habe nun bei meinem github ein repository angelegt, damit ist es mir dann gelungen:
https://github.com/Ralf9/FHEM-SIGNALduino

**Comment by sidey79** [comment]
Hallo Ralf,

ich nutze GIT nicht sonderlich oft von der Kommandozeile.

Die Fehlermeldung würde sicher helfen.

git push origin dev-proto7 wäre aber bestimmt besser.

Clonen brauchst Du es auch nicht jedes mal. Da gibt es dann git pull.

Grüße 



Am 18. September 2015 00:30:09 MESZ, schrieb Ralf9 <notifications@github.com>:
>Ich habe an der 14_SIGNALduino_ID7.pm ein paar Änderungen vorgenommen.
>Ich habe ein push in Deinen Zweig "dev-proto7" versucht ich habe aber
>eine Fehlermeldung bekommen. Ich habe es wie folgt versucht:
>
>  git clone -b dev-proto7 https://github.com/RFD-FHEM/RFFHEM.git
>  git add 14_SIGNALduino_ID7.pm
>  git commit -m "Daten ignorieren, wenn humidity groesser 100"
>  git push origin master
>
>Ich habe nun bei meinem github ein repository angelegt, damit ist es
>mir dann gelungen:
>https://github.com/Ralf9/FHEM-SIGNALduino
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RFD-FHEM/RFFHEM/issues/11#issuecomment-141255424

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Ralf9** [comment]
mit "git push origin dev-proto7" hat es jetzt geklappt.
Ich benutze die Kommandozeile, da ich noch nicht herausgefunden habe welche GUI für Linux (Opensuse) brauchbar ist.
Welche GUI für Git benutzt Du?

Ich habe es mal mit einer schwachen Batterie getestet. Das mit dem Bat-Bit passt so.

Ich habe mir auch mal das mit der humidity > 100 angeschaut.
Bei humidity > 100 fehlt im Datensatz bei der Temperatur ein Bit:

EAS800z converted to bits: 0101 0110 1 001 000011100000 1111 00111111 0000
EAS800z decoded protocolid: 7 sensor id=49, channel=2, temp=22.4, hum=63, bat=ok

EAS800z converted to bits: 0101 0110 1 001 000011000001 1110 01111110 0000
EAS800z decoded protocolid: 7 sensor id=49, channel=2, temp=19.3, hum=126, bat=ok

**Comment by sidey79** [comment]
Hallo Ralf,

probiert doch smartgit.
Ich verwende tortoise GIT und egit (in Eclipse).
Allerdings unter Windows.

Das mit dem Batteriebit ist gut, ich hatte ja nur geraten, welches es ist.

Das mit der Humidity >100 ist interessant. Da steckt sicher noch mehr dahinter.
Vielleicht stimmen die ausgewählten Bits doch nicht... Hmm

**Comment by Ralf9** [comment]
Die Bits müssten eigentlich so stimmen. Die Ursache können auch Empfangsprobleme sein. Ich habe den Arduino mit dem Receiver mit dem mitgelieferten 25cm USB-Kabel am PC eingesteckt.

Mit dieser Abfrage müsste es passen:
my $bit24bis27 = substr($bitData,24,4);
if ($hum > 100 || $hum == 0 || $bit24bis27 ne '1111') {
  return undef;
}

**Comment by sidey79** [comment]
Ja, Empfangsprobleme oder Störungen können auftreten, dazu könnte eine checksumme übertragen werden.

Ich habe aber so ein bisschen das Gefühl, die fehlt bei diesem Sensor, sie bei so einigen anderen leider auch.

Sven

Am 18. September 2015 22:47:15 MESZ, schrieb Ralf9 <notifications@github.com>:
>Die Bits müssten eigentlich so stimmen. Die Ursache können auch
>Empfangsprobleme sein. Ich habe den Arduino mit dem Receiver mit dem
>mitgelieferten 25cm USB-Kabel am PC eingesteckt.
>
>Mit dieser Abfrage müsste es passen:
>my $bit24bis27 = substr($bitData,24,4);
>if ($hum > 100 || $hum == 0 || $bit24bis27 ne '1111') {
>  return undef;
>}
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RFD-FHEM/RFFHEM/issues/11#issuecomment-141564010

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sidey79** [comment]
Added support for sensor from @anfichten without humidity, they are all 0, so humidty is 0. 

2015.09.23 00:17:30 4: SIGNALduino_ID7_Parse  EAS800z (u772A0BCF000) length: 10
2015.09.23 00:17:30 3: EAS800z converted to bits: 01110010 1 010 000010111100 1111 00000000
2015.09.23 00:17:30 3: EAS800z decoded protocolid: 7 sensor id=72, channel=3, temp=18.8, hum=0, bat=ok
2015.09.23 00:17:30 4: SIGNALduino_ID7: EAS800z_3 (72A0BCF000)


/cc @anfichtn
