### ISSUE TITLE
Rolladensteuerung

### ISSUE THREAD

**Issue by GuentherP** [RFD-FHEM/RFFHEM#1117]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: AMC
  - model name:  51084721
  - pictures of the device / the board (very helpful)
![205_03-big](https://user-images.githubusercontent.com/113351363/189641790-7750abd0-4156-46bb-95c7-ef771e1ffa3a.png)

  
## Specifications 

  - Microcontroller:
  - Version (Firmware):  
 
Latest Revision: 26130
File              Rev   Last Change

```
fhem.pl           26115 2022-06-04 09:50:00Z rudolfkoenig
98_autocreate.pm  23727 2021-02-12 20:31:37Z rudolfkoenig
14_CUL_TX.pm      17102 2018-08-08 05:34:42Z rudolfkoenig
91_eventTypes.pm  23471 2021-01-04 19:24:21Z rudolfkoenig
01_FHEMWEB.pm     25943 2022-04-10 11:34:15Z rudolfkoenig
92_FileLog.pm     26084 2022-05-24 11:22:55Z rudolfkoenig
14_Hideki.pm      25560 2022-01-25 21:43:09Z Sidey
98_JsonList2.pm   23727 2021-02-12 20:31:37Z rudolfkoenig
91_notify.pm      25888 2022-03-27 10:22:58Z rudolfkoenig
14_SD_UT.pm       24839 2021-08-09 19:55:13Z HomeAuto_User
14_SD_WS.pm       25484 2022-01-17 20:50:12Z Sidey
14_SD_WS07.pm     25485 2022-01-17 20:52:47Z Sidey
00_SIGNALduino.pm 25549 2022-01-23 10:59:59Z Sidey
10_SOMFY.pm       26122 2022-06-05 19:43:53Z viegener
99_SUNRISE_EL.pm  24249 2021-04-14 05:45:49Z rudolfkoenig
98_SVG.pm         25876 2022-03-23 11:28:24Z rudolfkoenig
99_Utils.pm       24128 2021-04-02 16:29:11Z rudolfkoenig
98_version.pm     15140 2017-09-26 09:20:09Z markusbloch

Blocking.pm       23268 2020-12-01 11:48:48Z rudolfkoenig
DevIo.pm          26055 2022-05-17 20:12:20Z rudolfkoenig
HttpUtils.pm      26007 2022-04-30 18:12:02Z rudolfkoenig
RTypes.pm         10476 2016-01-12 21:03:33Z borisneubert
SD_Protocols.pm   25549 2022-01-23 10:59:59Z Sidey
TcpServerUtils.pm 25866 2022-03-21 09:01:16Z rudolfkoenig

f18.js                     25656 2022-02-08 09:49:53Z rudolfkoenig
fhemweb.js                 25983 2022-04-19 17:26:44Z rudolfkoenig
```

Auszug aus dem Logfile:
```
2022.09.12 13:45:48 4: duino: HandleWriteQueue, called
2022.09.12 13:45:48 4: duino: HandleWriteQueue, nothing to send, stopping timer
2022.09.12 13:46:04 4: duino: Read, msg: MC;LL=-1271;LH=1253;SL=-630;SH=668;D=433D3C22B8710;C=636;L=49;R=6;
2022.09.12 13:46:04 4: duino: Parse_MC, Found manchester protocol id 52 clock 636 RSSI = -71 -> Oregon Scientific PIR
2022.09.12 13:46:04 5: duino: Parse_MC, extracted data 1011110011000010110000111101110101000111100011101111 (bin)
2022.09.12 13:46:04 5: duino: Parse_MC, protocol does not match return from method: (undef)
2022.09.12 13:46:04 4: duino: Read, msg: MC;LL=-1310;LH=1281;SL=-630;SH=669;D=433D0;C=648;L=17;R=14;
2022.09.12 13:46:04 4: duino: Read, msg: MC;LL=-1310;LH=1281;SL=-630;SH=669;D=E115C38AA8;C=648;L=38;R=14;
2022.09.12 13:46:04 4: duino: Read, msg: MC;LL=-1309;LH=1293;SL=-674;SH=628;D=0CF4F08;C=650;L=25;R=16;
2022.09.12 13:46:05 4: duino: Read, msg: MC;LL=-1312;LH=1257;SL=-605;SH=685;D=433D3C22B87155;C=643;L=56;R=249;
2022.09.12 13:46:05 4: duino: Parse_MC, Found manchester protocol id 43 clock 643 RSSI = -77.5 -> Somfy RTS
2022.09.12 13:46:05 5: duino: Parse_MC, extracted data 01000011001111010011110000100010101110000111000101010101 (bin)
2022.09.12 13:46:05 4: duino: lib/mcBit2SomfyRTS, bitdata: 01000011001111010011110000100010101110000111000101010101 (56)
2022.09.12 13:46:05 5: duino: Dispatch, Ys433D3C22B87155, test ungleich: disabled
2022.09.12 13:46:05 5: duino: Dispatch, Ys433D3C22B87155, -77.5 dB, dispatch
2022.09.12 13:46:05 5: duino: dispatch Ys433D3C22B87155
2022.09.12 13:46:05 4: duino: Somfy RTS preprocessing check: E enc: 433D3C22B87155 dec: 437E011E9AC924
2022.09.12 13:46:05 4: SOMFY Parse: SOMFY_24C99A msg: Ys437E011E9AC924  --> 70-   --> io is SIGNALduino
2022.09.12 13:46:05 5: Starting notify loop for SOMFY_24C99A, 1 event(s), first is received: 70
2022.09.12 13:46:05 5: End notify loop for SOMFY_24C99A
2022.09.12 13:46:05 4: duino: Read, msg: MC;LL=-1263;LH=1322;SL=-611;SH=681;D=433D3C22B871550;C=646;L=57;R=249;
2022.09.12 13:46:05 4: duino: Parse_MC, Found manchester protocol id 43 clock 646 RSSI = -77.5 -> Somfy RTS
2022.09.12 13:46:05 5: duino: Parse_MC, extracted data 010000110011110100111100001000101011100001110001010101010000 (bin)
2022.09.12 13:46:05 4: duino: lib/mcBit2SomfyRTS, bitdata: 010000110011110100111100001000101011100001110001010101010000 (57)
2022.09.12 13:46:05 4: duino: lib/mcBit2SomfyRTS, bitdata: 10000110011110100111100001000101011100001110001010101010, truncated to length: 56
2022.09.12 13:46:05 5: duino: Dispatch, Ys867A784570E2AA, test ungleich: disabled
2022.09.12 13:46:05 5: duino: Dispatch, Ys867A784570E2AA, -77.5 dB, dispatch
2022.09.12 13:46:05 5: duino: dispatch Ys867A784570E2AA
2022.09.12 13:46:05 4: duino: Somfy RTS preprocessing check: C enc: 867A784570E2AA dec: 86FC023D359248
2022.09.12 13:46:05 4: SOMFY Parse: SOMFY_489235 msg: Ys86FC023D359248  --> F0-   --> io is SIGNALduino
2022.09.12 13:46:05 5: Starting notify loop for SOMFY_489235, 1 event(s), first is received: F0
2022.09.12 13:46:05 5: End notify loop for SOMFY_489235
2022.09.12 13:46:05 4: duino: Read, msg: MC;LL=-1259;LH=1316;SL=-613;SH=678;D=3C22B871550;C=644;L=41;R=255;
2022.09.12 13:46:05 4: duino: Read, msg: MC;LL=-1285;LH=1296;SL=-723;SH=633;D=433D3C;C=656;L=23;R=253;
2022.09.12 13:46:07 4: duino: Read, msg: MC;LL=-1244;LH=1333;SL=-625;SH=682;D=42BCBDA2B871550;C=647;L=57;R=250;
2022.09.12 13:46:07 4: duino: Parse_MC, Found manchester protocol id 43 clock 647 RSSI = -77 -> Somfy RTS
2022.09.12 13:46:07 5: duino: Parse_MC, extracted data 010000101011110010111101101000101011100001110001010101010000 (bin)
2022.09.12 13:46:07 4: duino: lib/mcBit2SomfyRTS, bitdata: 010000101011110010111101101000101011100001110001010101010000 (57)
2022.09.12 13:46:07 4: duino: lib/mcBit2SomfyRTS, bitdata: 10000101011110010111101101000101011100001110001010101010, truncated to length: 56
2022.09.12 13:46:07 5: duino: Dispatch, Ys85797B4570E2AA, test ungleich: disabled
2022.09.12 13:46:07 5: duino: Dispatch, Ys85797B4570E2AA, -77 dB, dispatch
2022.09.12 13:46:07 5: duino: dispatch Ys85797B4570E2AA
2022.09.12 13:46:07 4: duino: Somfy RTS preprocessing check: C enc: 85797B4570E2AA dec: 85FC023E359248
2022.09.12 13:46:07 4: SOMFY Parse: SOMFY_489235 msg: Ys85FC023E359248  --> F0-   --> io is SIGNALduino
2022.09.12 13:46:07 5: Starting notify loop for SOMFY_489235, 1 event(s), first is received: F0
2022.09.12 13:46:07 5: End notify loop for SOMFY_489235
2022.09.12 13:46:12 4: duino: Read, msg: MC;LL=-1264;LH=1312;SL=-638;SH=638;D=443C3D22B8;C=641;L=39;R=18;
2022.09.12 13:46:15 4: duino: Read, msg: MC;LL=-1263;LH=1315;SL=-665;SH=646;D=B8391903CA8;C=648;L=41;R=16;

```
  

  - Versionmodul (FHEM Module):

**Comment by GuentherP** [comment]
- Microcontroller: CC1101
- Versionmodul (FHEM Module): V 3.4.0 SIGNALduino cc1101 (chip CC1101) - compiled at Jul 16 2020 20:52:15

**Comment by HomeAutoUser** [comment]
Hallo @GuentherP, hast du zu dem Hersteller AMC einen passenden Link oder woher hast du diesen entnommen?
Ist es richtig, das du den Modellname mit 51084721 angegeben hast und auf dem Bild 5108472A steht?
Ist das der Hersteller bzw. Vertrieb? https://www.amc-production.fr/volet-roulant

**Comment by GuentherP** [comment]
Hallo, 
ja, das dürfte der Hersteller sein. Ich glaube die stellen auch SOMFY her. FHEM erkennt die Fersteuerung auch als SOMFY und erstellt hierfür devices, allerdings funktioniert es damit nicht.
Beim Modellnamen habe ich mich offenbar verschrieben. 5108472A ist korrekt.
Die Rolladenmotoren sowie die Steuerung habe ich bei https://rolladen7.de/ gekauft.

**Comment by elektron-bbs** [comment]
Mhmm, "allerdings funktioniert es damit nicht." ist wenig aussagekräftig. Was funktioniert damit nicht?
Ich habe persönlich keine Erfahrung mit SOMFY und eben kurz das Internet bemüht und fand auf Anhieb, das man da einiges beachten muss. Hast du das schon gelesen und durchgeführt: https://wiki.fhem.de/wiki/Somfy_via_SIGNALduino

**Comment by elektron-bbs** [comment]
Was schreibt den die Bedienungsanleitung dazu, wie zusätzliche Fernbedienungen angelernt werden?
Ist es genau so, wie bei SOMFY?
Wir stochern hier ziemlich im Nebel, wenn du nicht beschreibst, was genau nicht funktioniert.
Im Wiki steht ja z.B.:

> Auf der Rückseite des Senders befindet sich in der Regel eine kleine Vertiefung (Loch) mit einem Taster, der z.B. über ein Streichholzende für 0,5 sec gedrückt werden muss. Danach fährt der Rolladen zur Quittierung kurz nach unten und wieder zurück (ruckt).

**Comment by GuentherP** [comment]
Hallo
vielleicht habe ich mich etwas kurz gehalten, weil das alles für mich selbstverständlich war.
Also mal etwas ausführlicher
Ich habe einen SYMFO Markise die ich mit FHEM problemlos in Betrieb nehmen konnte. 
Wie ghabe ich das gemacht.
Ein entsprechendes Device in FHEM angelegt und eine ID vergeben. Auf der orginal Fernbedienung die Taste zur Kopplung drücken -> die Markise fährt kurz vor und zurück -> in FHEM den Befehl set Device prog" abgesetzt. -> die Markise fähr kurz vor und zurück. Anschließend lässt sich die Markise mit FHEM bedienen.

Das selbe mit dem Rollo versucht.
Ein Device angelegt, eine ID vergeben (eine andere als bei der Markise) -> Auf der orginal Fernbedienung für den Rollo die Taste zur Kopplung gedrückt -> der Rollo fährt kurz vor und zurück -> in FHEM den Befehl set Device prog" abgesetzt -> **nichts passiert.** 
Der Rollo reagiert weder auf den Versuch sich mit FHEM zu koppeln, noch reagiert er auf einen Versuch ihn rauf oder runter zu fahren.
Mir ist klar dass es ohne Kopplung nicht funktionieren kann. Aber genau das ist das Problem, die Koppling funktionert nicht.

**Comment by elektron-bbs** [comment]
Wir wissen jetzt schon mal, das das Rollo in den Programmiermodus geht, aber offensichtlich den set-prog-Befehl aus FHEM nicht erkennt.
Im Wiki ist noch die Rede von: "SOMFY-RTS Systeme senden auf 433,42Mhz." - hast du das eingestellt?
Dann hatte ich noch gefragt, wie die Bedienungsanleitung das Anlernen beschreibt.

**Comment by GuentherP** [comment]
Hallo elektron-bbs,
das Anlernen der Fernbedienung ist exakt geich wie bei der SOMFY Markise.

Das bringt mich aber alles nicht weiter. Du kannst mir glauben dass ich des lesens mächtig bin und die Gebrauchsanweisungen meiner Fernbedienung sowie jede Menge Wikis und Anleitungen im Internet gelesen habe bevor ich hier Hilfe gesucht habe.

Fakt ist dass der SignalDuino bzw. FHEM die Fernsteuerung als SOMFY Device erkennt. Es damit aber nicht funktioniert. Das Protokoll scheint ähnlich wie das von SOMFY zu sein, aber eben nur ähnlich. Irgend ein Tetail ist anders.
Ich hätte mir hier Hilfe erwartet wie die Logmeldungen von FHEM richtig interpretieren kann. Wie kann ich den Algorithmus herausfinden den meine Fernedienung für die Steuerung des Rollos verwendet. Wie bekomme ich mehr Informationen über das Protokoll der Fernbedienung.

**Comment by elektron-bbs** [comment]
Da kann ich dann leider auch nicht weiter helfen. In der Maintainer.txt ist folgendes hinterlegt:

```
File                         Maintainer           Forum
=========================================================================
FHEM/10_SOMFY.pm             viegener             Sonstige Systeme
```

**Comment by elektron-bbs** [comment]
@GuentherP 
Bist du im Forum oder direkt mit dem Maintainer des Moduls weiter gekommen?

**Comment by elektron-bbs** [comment]
Hervorragend, dann können wir das Issue hier ja schließen.
Deine Änderungen könntest du dann im Forum veröffentlich, oder halt den Maintainer kontaktieren.

**Comment by elektron-bbs** [comment]
Keine Rückmeldung erhalten seit Dezember 2022 - ich schließe das Problem.
