### ISSUE TITLE
Protokoll für Roto Dachfensterrolläden | Aurel Handsender

### ISSUE THREAD

**Issue by dsgrafiniert** [RFD-FHEM/RFFHEM#113]
Wäre es möglich das Rolling-Code Protokoll der Aurel Handsender für Roto Dachfensterrolläden zu dekodieren?
Ein Signal-Schnippsel findet ihr hier: https://forum.fhem.de/index.php/topic,53823.0.html

Ich kenne mich bisher leider überhaupt nicht mit der Materie aus, würde mich aber gern einarbeiten. Es würde mich sehr freuen, hier Unterstützung zu finden.

Danke im Voraus!

**Comment by HomeAutoUser** [comment]
Guten Abend @dsgrafiniert ,

lange ist dein Post her.
Wir versuchen hier ein wenig "Ordnung zu schaffen" und möchten auch diesen Faden prüfen.

Deine damalige Meldung umfasst die Decodierung deines Roto Dachfenster mit dem SIGNALduino.
Wie ist der Stand aktuell? Wird dein Roto Dachfenster decodiert / verarbeitet?

Über eine Rückmeldung würden wir uns freuen.
MfG

**Comment by dsgrafiniert** [comment]
Hi, ich bin umgezogen und habe das Thema daher nicht weiterverfolgt.
