### ISSUE TITLE
protected branch hook declined

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#1144]
## Actual Behavior
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/master_Inkbird-IBS-P01R_01.        
remote: error: 4 of 6 required status checks are expected.        
To https://github.com/RFD-FHEM/RFFHEM.git
 ! [remote rejected]   master_Inkbird-IBS-P01R_01 -> master_Inkbird-IBS-P01R_01 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/RFD-FHEM/RFFHEM.git'

Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 433 bytes | 433.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
remote: error: GH006: Protected branch update failed for refs/heads/master_SD_GT_feature.        
remote: error: 6 of 6 required status checks are expected.        
To https://github.com/RFD-FHEM/RFFHEM.git
 ! [remote rejected]   master_SD_GT_feature -> master_SD_GT_feature (protected branch hook declined)
error: failed to push some refs to 'https://github.com/RFD-FHEM/RFFHEM.git'

Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 4 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 676 bytes | 676.00 KiB/s, done.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.        
remote: error: GH006: Protected branch update failed for refs/heads/master_Inkbird-IBS-P01R.        
remote: error: 6 of 6 required status checks are expected.        
To https://github.com/RFD-FHEM/RFFHEM.git
 ! [remote rejected]   master_Inkbird-IBS-P01R -> master_Inkbird-IBS-P01R (protected branch hook declined)
error: failed to push some refs to 'https://github.com/RFD-FHEM/RFFHEM.git'

Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 1.95 KiB | 999.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
remote: error: GH006: Protected branch update failed for refs/heads/master_Inkbird-IBS-P01R_02.        
remote: error: 6 of 6 required status checks are expected.        
To https://github.com/RFD-FHEM/RFFHEM.git
 ! [remote rejected]   master_Inkbird-IBS-P01R_02 -> master_Inkbird-IBS-P01R_02 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/RFD-FHEM/RFFHEM.git'

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Microcontroller:
  - Version (Firmware):

  - Versionmodul (FHEM Module):

**Comment by sidey79** [comment]
Hast Du einen Link zur dem Job? Ich finde ihn leider nicht.

**Comment by elektron-bbs** [comment]
Ich durfte es ja nicht ausführen, deshalb habe ich auch keinen Link.
Selbst bei dem eben neu erstellten Branch master_Inkbird-IBS-P01R_02 bekomme ich diese Meldung:

```
! [remote rejected] master_Inkbird-IBS-P01R_02 -> master_Inkbird-IBS-P01R_02 (protected branch hook declined)
error: failed to push some refs to 'https://github.com/RFD-FHEM/RFFHEM.git'
```

**Comment by sidey79** [comment]
Kommt die etwa wenn Du von lokal etwas pushen möchtest?

**Comment by elektron-bbs** [comment]
Genau so ist es.

**Comment by sidey79** [comment]
Geht es denn jetzt wieder?

**Comment by elektron-bbs** [comment]
Ja

**Comment by sidey79** [comment]
Gut zu wissen. Ich hatte eine Regel "feature*" in master[-_] umbenannt. Die führte dann dazu dass ein Merge erst möglich ist, wenn die Checks durchgelaufen sind.

Das macht dann so keinen Sinn. Ich habe das deaktiviert.

**Comment by elektron-bbs** [comment]
OK, danke für die schnelle Hilfe.
