### ISSUE TITLE
Flash for Arduino Uno

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#123]
Flashing Arduino UNO does not work.

avrdude: ser_recv(): programmer is not responding 
avrdude: stk500_recv(): programmer is not responding 
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00 

Error occures, because upload speed 57600 is wrong for Arduino uno

**Comment by elektron-bbs** [comment]
Arduino Uno wird nicht mehr unterstützt.
