### ISSUE TITLE
Rotating codes not stored in backup

### ISSUE THREAD

**Issue by normen** [RFD-FHEM/RFFHEM#1230]
## Expected Behavior
When learning the codes of a remote with rotating codes (e.g. SilverCrest / SD_GT) they should be backed up when doing a backup of FHEM.

## Actual Behavior
When doing a backup and restoring it, the codes seem to be missing. I have to re-learn the codes of all SD_GT plugs.

## Steps to Reproduce the Problem

  1. Add a SD_GT plug and learn all codes
  2. Do a FHEM backup
  3. Restore the backup

Not sure if I'm simply missing a file thats not backed up, otherwise the remotes work great, thanks for this module!

## Specifications

  - Microcontroller: SIGNALDuino
  - Version (Firmware): 3.5.0

  - Versionmodul (FHEM Module): 3.5.5

**Comment by elektron-bbs** [comment]
Hast du die Datei fhem.save aus dem Log-Verzeichnis auch wiederhergestellt? Dort sollten die Codes eigentlich mit gespeichert werden, wie z.B. hier:

```
setstate SD_GT_8070A_A off
setstate SD_GT_8070A_A 2022-12-31 16:58:05 CodesOff 8E3F20,81E490,86BB10
setstate SD_GT_8070A_A 2022-12-31 16:59:58 CodesOn 8FF840,8DDAB0,89A130,851970
setstate SD_GT_8070A_A 2022-12-30 20:54:17 IODev sduinoUSB0
setstate SD_GT_8070A_A 2022-12-31 16:59:58 SendCode 8FF840
setstate SD_GT_8070A_A 2022-12-31 16:59:58 SystemCode 8070A
setstate SD_GT_8070A_A 2022-12-31 16:59:58 SystemCodeDec 526090
setstate SD_GT_8070A_A 2022-12-31 16:59:58 Version 2
setstate SD_GT_8070A_A 2022-12-31 17:21:36 state off
```

**Comment by elektron-bbs** [comment]
Das kann ich nicht beantworten. Vielleicht fragst du das besser die Experten im Forum von FHEM.

**Comment by normen** [comment]
Ok, Danke. Zumindest weiss ich jetzt erstmal worauf ich achten muss beim nächsten restore.
