### ISSUE TITLE
TFA Windmesser 30.3168

### ISSUE THREAD

**Issue by E-magic545** [RFD-FHEM/RFFHEM#1239]
Hallo, mein Windmesser "TFA Dostmann Windmesser 30.3168", funktioniert nicht mehr, nachdem ich das Gehäuse geöffnet habe sah ich das da irgendwas mit den eingebauten Accus passiert ist, 3 Stück zusammen geschaltet, Ni-MH AAA, 650mA/h 3,6 V.
Kann mir jemand erklären wie die Accus zusammen geschaltet werden um 3,5 Volt Ausgangsspannung zu erzielen, auf den alten Accus ist keine Polarität angegeben.
Danke
MfG
Erwin Liedke

**Comment by elektron-bbs** [comment]
Normalerweise ist der Becher, also das Gehäuse der Minuspol. Die Akkus werden dann in Reihe geschaltet, also jeweils Pluspol des einen Akkus mit dem Minuspol des anderen verbinden.
Falls die Erklärung nicht ausreichen sollte, wäre evtl. ein Bild des Akkus hilfreich.
