### ISSUE TITLE
CC1101 868.3 MHZ FSK Sensoren empfangen

### ISSUE THREAD

**Issue by pejonp** [RFD-FHEM/RFFHEM#124]
Hallo Sidey,

ich habe mal beim CC1101 ein Paar  Anpassungen durchgeführt so das er 2-FSK empfangen kann. Ich empfange jetzt auch etwas. Ich hoffe das sind meine Sensoren. Wie kann ich aus den Daten die Hex-Nachrichten machen. Als Anlage noch der Aufbau der Sensornachrichten. Vielen Dank.

##############
Using sFIFO
Reading values fom eeprom
CCInit
CCVersion=20
CCPartnum=0
Starting timerjob
receiver enabled
MU;P0=107;P1=-94;P2=310;P3=-191;D=0101010101010101010101010101012103230101210323010;CP=0;R=227;
V 3.3.1-dev SIGNALduino cc1101 - compiled at Jan  8 2017 16:43:33
ccreg 00: 0D 2E 2D 02 00 00 3D 04 32 00 00 06 00 21 65 6A  ccreg 10: 89 5C 06 23 B9 56 07 00 18 14 6C 07 00 90 87 6B  ccreg 20: F8 56 11 EF 2C 19 1F 41 00 59 7F 07 88 31 0B 
ccFactoryReset done
ccreg 00: 0D 2E 2D 02 00 00 3D 04 32 00 00 06 00 21 65 6A  ccreg 10: 89 5C 06 23 B9 56 07 00 18 14 6C 07 00 90 87 6B  ccreg 20: F8 56 11 EF 2C 1A 1F 41 00 59 7F 3F 88 31 0B 
MU;P0=-212;P1=203;P2=-311;P3=104;P4=-108;P5=312;P6=-496;D=012343434343434343234145434323432303634361652163417;CP=3;R=225;
MU;P0=-348;P1=105;P2=-103;P3=208;P4=312;P5=-208;P7=-524;D=012121212121212101232421210121015101210374037123;CP=1;R=225;
MU;P0=-341;P1=106;P2=-101;P4=210;P5=316;P6=-572;P7=-896;D=01212121212121210124252121012101612121056101240421217;CP=1;R=225;
MU;P0=-481;P1=107;P2=-102;P3=-312;P4=211;P5=320;P6=-212;P7=-876;D=0121212121212121312425212131213161012104040401242171;CP=1;R=225;
MC;LL=-340;LH=456;SL=-108;SH=205;D=AAAA8E;C=270;L=23;R=225;
MU;P0=456;P1=-116;P2=-340;P3=205;P4=315;P6=-198;P7=-1048;D=40101216101030101610101236401710173616301210403610061136061;CP=0;R=225;
MU;P0=-311;P1=102;P2=-107;P3=207;P4=316;P5=-212;P6=-498;D=012121212121212101232421210121015161216364036123;CP=1;R=225;
MU;P0=-314;P1=103;P2=-103;P3=211;P4=312;P5=-209;P6=-472;D=01212121212121210123242121012101516121636403515121237;CP=1;R=225;
MU;P0=-330;P1=110;P2=-102;P3=212;P4=314;P5=-572;P7=-964;D=0121212121212121012324212101210151212104510123032121712;CP=1;R=225;
MU;P0=442;P1=-104;P2=-338;P3=209;P4=312;P6=-203;P7=-1044;D=0101010101010101210304010121610103010161010123640171017361630161640361006113201;CP=0;R=225;
MU;P0=355;P1=106;P2=-102;P3=-313;P4=207;P6=-210;P7=-1042;D=161212421216121213460217121746164216160246120612430;CP=1;R=225;
MU;P0=386;P1=-102;P2=-361;P3=207;P6=-210;P7=-1152;D=0101010101010101210300010121610103010161010123012170730021212113202310;CP=0;R=225;
MU;P0=-328;P1=107;P2=-101;P3=212;P4=318;P5=-572;P7=-900;D=01212121212121210123242121012101512121045101230321217;CP=1;R=225;
MU;P0=364;P1=101;P2=-119;P3=206;P5=-419;P6=-212;P7=-1150;D=01212121212121210123202121516121232121612121032151707063532151230053202;CP=1;R=225;
MU;P0=-332;P1=104;P2=-105;P3=208;P4=314;P5=-570;P7=-900;D=01212121212121210123242121012101512121045101230321217;CP=1;R=225;
ccreg 00: 0D 2E 2D 02 00 00 3D 04 32 00 00 06 00 21 65 6A  ccreg 10: 89 5C 06 23 B9 56 07 00 18 14 6C 07 00 90 87 6B  ccreg 20: F8 56 11 EF 2C 1A 1F 41 00 59 7F 3F 88 31 0B 
MU;P0=-546;P1=106;P2=-100;P3=-329;P4=212;P5=314;D=0121212121212121312425212131213101212135013124342121;CP=1;R=225;
MU;P0=-501;P1=100;P2=-107;P3=-314;P4=208;P5=312;P6=-208;P7=-1088;D=0121212121212121312425212131213161012104053401247;CP=1;R=225;

**Comment by sidey79** [comment]
Hast Du zufällig die Carrier Sense Threshold vetwendet, um sicher zu stellen, dass kein Rauschen ausgewertet wird?

Bei fsk-2 würde mich halt interessieren, ob ein Bit nicht durch mehrere Pulsfolgen dargestellt wird.

**Comment by pejonp** [comment]
Hallo Sidey,
habe da mal was gefunden (http://elektroniktutor.de/signalkunde/fsk.html). 
Da ich davon nicht so die Ahnung, also keine habe.  Habe ich mir vom CUL und der Umschaltung auf die LaCross Sensoren die Einstellungen geholt. Bzw. mit dem Tool vom TI SmartRF Studio (http://www.ti.com/tool/SMARTRFTM-STUDIO) das berechnen lassen.

// Address Config = Address check, no broadcast 
// Base Frequency = 868.299866 
// CRC Autoflush = false 
// CRC Enable = true 
// Carrier Frequency = 868.299866 
// Channel Number = 0 
// Channel Spacing = 49.987793 
// Data Format = Normal mode 
// Data Rate = 17.2577 
// Deviation = 5.157471 
// Device Address = 0 
// Manchester Enable = false 
// Modulated = true 
// Modulation Format = 2-FSK 
// PA Ramping = false 
// Packet Length = 255 
// Packet Length Mode = Variable packet length mode. Packet length configured by the first byte after sync word 
// Preamble Count = 2 
// RX Filter BW = 58.035714 
// Sync Word Qualifier Mode = 30/32 + carrier-sense above threshold 
// TX Power = 0 
// Whitening = false 
// PA table 
#define PA_TABLE {0x50,0x00,0x00,0x00,0x00,0x00,0x00,0x00,}
// Rf settings for CC1101
RF_SETTINGS code rfSettings = {
    0x0D,  // IOCFG2              GDO2 Output Pin Configuration
    0x2E,  // IOCFG1              GDO1 Output Pin Configuration
    0x2D,  // IOCFG0              GDO0 Output Pin Configuration
    0x07,  // FIFOTHR             RX FIFO and TX FIFO Thresholds
    0xD3,  // SYNC1               Sync Word, High Byte
    0x91,  // SYNC0               Sync Word, Low Byte
    0xFF,  // PKTLEN              Packet Length
    0x05,  // PKTCTRL1            Packet Automation Control
    0x05,  // PKTCTRL0            Packet Automation Control
    0x00,  // ADDR                Device Address
    0x00,  // CHANNR              Channel Number
    0x06,  // FSCTRL1             Frequency Synthesizer Control
    0x00,  // FSCTRL0             Frequency Synthesizer Control
    0x21,  // FREQ2               Frequency Control Word, High Byte
    0x65,  // FREQ1               Frequency Control Word, Middle Byte
    0x6A,  // FREQ0               Frequency Control Word, Low Byte
    0xF9,  // MDMCFG4             Modem Configuration
    0x5C,  // MDMCFG3             Modem Configuration
    0x07,  // MDMCFG2             Modem Configuration
    0x00,  // MDMCFG1             Modem Configuration
    0xF8,  // MDMCFG0             Modem Configuration
    0x15,  // DEVIATN             Modem Deviation Setting
    0x07,  // MCSM2               Main Radio Control State Machine Configuration
    0x0C,  // MCSM1               Main Radio Control State Machine Configuration
    0x18,  // MCSM0               Main Radio Control State Machine Configuration
    0x14,  // FOCCFG              Frequency Offset Compensation Configuration
    0x6C,  // BSCFG               Bit Synchronization Configuration
    0x03,  // AGCCTRL2            AGC Control
    0x40,  // AGCCTRL1            AGC Control
    0x92,  // AGCCTRL0            AGC Control
    0x87,  // WOREVT1             High Byte Event0 Timeout
    0x6B,  // WOREVT0             Low Byte Event0 Timeout
    0xFB,  // WORCTRL             Wake On Radio Control
    0x56,  // FREND1              Front End RX Configuration
    0x10,  // FREND0              Front End TX Configuration
    0xE9,  // FSCAL3              Frequency Synthesizer Calibration
    0x2A,  // FSCAL2              Frequency Synthesizer Calibration
    0x00,  // FSCAL1              Frequency Synthesizer Calibration
    0x1F,  // FSCAL0              Frequency Synthesizer Calibration
    0x41,  // RCCTRL1             RC Oscillator Configuration
    0x00,  // RCCTRL0             RC Oscillator Configuration
    0x59,  // FSTEST              Frequency Synthesizer Calibration Control
    0x7F,  // PTEST               Production Test
    0x3F,  // AGCTEST             AGC Test
    0x81,  // TEST2               Various Test Settings
    0x35,  // TEST1               Various Test Settings
    0x09,  // TEST0               Various Test Settings
    0x00,  // PARTNUM             Chip ID
    0x04,  // VERSION             Chip ID
    0x00,  // FREQEST             Frequency Offset Estimate from Demodulator
    0x00,  // LQI                 Demodulator Estimate for Link Quality
    0x00,  // RSSI                Received Signal Strength Indication
    0x00,  // MARCSTATE           Main Radio Control State Machine State
    0x00,  // WORTIME1            High Byte of WOR Time
    0x00,  // WORTIME0            Low Byte of WOR Time
    0x00,  // PKTSTATUS           Current GDOx Status and Packet Status
    0x00,  // VCO_VC_DAC          Current Setting from PLL Calibration Module
    0x00,  // TXBYTES             Underflow and Number of Bytes
    0x00,  // RXBYTES             Overflow and Number of Bytes
    0x00,  // RCCTRL1_STATUS      Last RC Oscillator Calibration Result
    0x00,  // RCCTRL0_STATUS      Last RC Oscillator Calibration Result
};

aktuell ist das hier eingestellt. Und es kommen ein paar Daten.
ccregAll: 

ccreg 00: 0D 2E 2D 02 00 00 3D 04 32 00 00 06 00 21 65 6A
ccreg 10: 89 5C 06 23 B9 56 07 00 18 14 6C 07 00 90 87 6B
ccreg 20: F8 56 11 EF 2C 19 1F 41 00 59 7F 3F 88 31 0B

**Comment by sidey79** [comment]
Okay, bin jetzt nicht so Firm in allen Registern, aber vermutlich wandelt der CC1101 das Signal bereits um..... nur was kommen dann am GDO0 an? Oder wie hast Du die Daten abgeholt?

**Comment by pejonp** [comment]
Der Aufbau ist wie beim Signalduino_CC1101.  Die Anschlüsse sind so geblieben.

**Comment by sidey79** [comment]
Also soweit ich das mit den Registern verstehe, hast Du die Packet Funktionen des cc1101 aktiviert.

Der GDO0 Pin befindet sich damit nicht mehr im Serial Output modus.

Damit wird auch deine Wetterstation nicht mehr empfangen und richtig dekodiert .

Hier steht nun eine Entscheidung an.
Packet Funktionen des cc1101 verwenden, dann legt man einen Betriebsmodus fest, oder man versetzt den cc1101 wieder in den asynchron Serial Mode und deaktiviert die Packet handler im cc1101. Damit man nicht dauern rauschen empfängt, braucht man das Carrier Sense Register.

Die FSK Demodulation müsste man dann in SW vornehmen.
Eventuell muss man da schon was im Arduino machen, das kommt halt etwas darauf an, wie lange die Übertragung ist. Der Puffer könnte knapp werden.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.

**Comment by HomeAutoUser** [comment]
Hallo @pejonp,

hast du mit deiner Einstellung vom Post oben https://github.com/RFD-FHEM/RFFHEM/issues/124#issuecomment-271410349 einen Empfang von Sensoren gehabt?

Wenn ja, welche Hardware und welche Sensoren nutzt du da?
