### ISSUE TITLE
Unable to set Clients attribute

### ISSUE THREAD

**Issue by Devirex** [RFD-FHEM/RFFHEM#1264]
This return statement does not allow to set the Clients attribute. If removed it works good. 
https://github.com/RFD-FHEM/RFFHEM/blob/be887b5a07a4fcd5deac31b7854e1e14bbd1296b/FHEM/00_SIGNALduino.pm#L3120

**Comment by sidey79** [comment]
Can i have some more details how to reproduce the error?

**Comment by Devirex** [comment]
Sure, just try to add another value to the list of existing Clients. Copy all the existing Clients from the internals, and add some module (maybe a new module which is in development) to the string. There is always a message „Setting defaults“ and no attribute „Clients“ is added to a device. If you comment out that line everything works as expected. You can then set all Clients for which messages should be dispatched.

**Comment by sidey79** [comment]
I got it, the internal ist updated but the attribute self isn't set to the provided value.

**Comment by sidey79** [comment]
I've fixed the error, can you give it a try?

`update force https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/sidey79/issue1264/controls_signalduino.txt`

**Comment by Devirex** [comment]
Hi, i was able to test it. For the firt try it looked good (MY_Module: added):
![ClientList](https://github.com/user-attachments/assets/fb1d536a-94a0-455e-9a8e-5068b0c1068b)

But after a "shutdown restart" the Clients list gets destroyed:
![ClientList-broken](https://github.com/user-attachments/assets/784157e2-efad-44ad-a89d-be835d0f2458)

**Comment by Devirex** [comment]
Setting the Attribute now works good (added MY_Module):
![ClientList](https://github.com/user-attachments/assets/f48c0388-bef7-4143-bfd6-b072743cdecf)

But a "shutdown restart" resets the value ( to the Clients from "selected protocols"?)  without using the custom values from the Attribute
![ClientList-broken](https://github.com/user-attachments/assets/3798370e-8339-4598-8893-c834619fea64)

**Comment by sidey79** [comment]
Can you confirm, that you are not using the whitelist_IDs attribute? Because, if you use the Whitelist_IDs attribute, the Clientlist ist created from the modules selected matching the modules listed in the whitelist_IDs attribute.

If you want to control the Clients attribute by yourself, then you can't use the whitelist_IDs attribute.

**Comment by Devirex** [comment]
Ok thanks for the hint 👍I removed the whitelist_ID Atrributes.
Now the Clients are defaulting to standard after reboot even if attribute Clients is set.

**Comment by sidey79** [comment]
Okay, i will check this.

**Comment by sidey79** [comment]
I updated the code and i think the reload problem is now also fixed. You can update with the same url as last time.

**Comment by sidey79** [comment]
@Devirex 

Do you have an update for us?

**Comment by Devirex** [comment]
Hey sorry for teh delay, works great now!
