### ISSUE TITLE
Protokoll u31 / u34

### ISSUE THREAD

**Issue by Kolbi** [RFD-FHEM/RFFHEM#127]
Ich erhalte mit meinem Signalduino (dev-r33 - V 3.3.1-dev SIGNALduino - compiled at Jan 3 2017 

```
23:59:32) folgende Daten:
2017.01.17 18:22:52 4: sduino/msg READ: MU;P0=450;P1=-1002;P2=1155;P4=-25956;D=012101010121010101210121212101010101010104;CP=0;
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: decoded matched MU Protocol id 31 dmsg u31#88B80 length 20
2017.01.17 18:22:52 4: SIGNALduino_unknown incomming msg: u31#88B80
2017.01.17 18:22:52 4: SIGNALduino_unknown rawData: 88B80
2017.01.17 18:22:52 4: SIGNALduino_unknown Protocol: 31
2017.01.17 18:22:52 4: SIGNALduino_unknown converted to bits: 10001000101110000000
2017.01.17 18:22:52 4: Unknown, please report
2017.01.17 18:22:52 3: sduino: Unknown code u31#88B80, help me!
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 5 -> unitec6899 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino/msg READ: MU;P0=-112;P1=1178;P2=-973;P3=463;P4=-21904;D=01212121232123212121212121232323212121232123212121232323212323232123212121232323232323234;CP=3;
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: decoded matched MU Protocol id 8 dmsg TXA07147747E length 44
2017.01.17 18:22:52 4: CUL_TX CUL_TX_56 56 (XA07147747E)
2017.01.17 18:22:52 4: CUL_TX temperature CUL_TX_56 56 T: -2.3 UnknownFlag: 1
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino/msg READ: MU;P0=-955;P1=1219;P2=482;P3=-19952;D=010101010101020102010101010101020202010101020102010101020202010202020102010101020202020202023;CP=2;
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2017.01.17 18:22:52 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
```

Jemand eine Ahnung was dies sein könnte?

**Comment by sidey79** [comment]
Hmm, eine Funksteckdose?   Kommt das denn dauernd oder nur sporadisch?

**Comment by Kolbi** [comment]
Das Signal bekomme ich in unregelmäßigen Abständen öfters am Tag. Mehr weiß ich leider nicht.

**Comment by Kolbi** [comment]
Ich bekomme das Signal teilweise in sehr kurzen Abständen:

> 2018.10.26 00:04:23.984 3: sduino: Unknown code u31#E99E9, help me!
> 2018.10.26 00:31:23.812 3: sduino: Unknown code u31#E99E9, help me!
> 2018.10.26 00:35:57.247 3: sduino: Unknown code u31#E99E9, help me!
> 2018.10.26 00:47:57.581 3: sduino: Unknown code u31#EA9EA, help me!
> 2018.10.26 01:09:12.044 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 01:39:39.396 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 01:41:30.141 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 02:10:42.623 3: sduino: Unknown code u31#EB9EC, help me!
> 2018.10.26 02:16:05.269 3: sduino: Unknown code u31#EB9EC, help me!
> 2018.10.26 02:34:54.010 3: sduino: Unknown code u31#EB9EC, help me!
> 2018.10.26 02:53:42.886 3: sduino: Unknown code u31#EB9EC, help me!
> 2018.10.26 03:52:46.818 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 03:55:35.913 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 03:58:19.057 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 04:02:56.964 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 04:06:37.389 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 04:07:32.776 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 04:34:12.090 3: sduino: Unknown code u31#EC9EC, help me!
> 2018.10.26 05:07:25.605 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 05:09:16.402 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 05:25:53.113 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 06:14:50.800 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 06:17:41.782 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 06:33:50.789 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 06:54:41.235 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 07:36:27.621 3: sduino: Unknown code u31#EE9EF, help me!
> 2018.10.26 07:42:10.010 3: sduino: Unknown code u31#EE9EF, help me!

**Comment by Kolbi** [comment]
> 2018.10.26 07:56:06.325 1: DEBUG>sduino: incomming message: (MU;P0=481;P1=-961;P2=1210;P3=-26360;D=01010121212121012121210121010121212121012121212321212121012101212121212121010101212121212101012121212101212121012101012121212101212121232121212101210121212121212101010121212121210101212121210121212101210101212121210121212120;CP=2;R=0;)
> 2018.10.26 07:57:00.369 1: DEBUG>sduino: incomming message: (MU;P0=172;P1=-959;P2=1212;P3=484;P4=-26360;D=0121313121212121312121213121313121212121312121212421212121312131212121212121313131212121212131312121212131212121312131312121212131212121242121212131213121212121212131313121212121213131212121213121212131213131212121213121212120;CP=2;R=0;)
> 2018.10.26 07:57:55.736 1: DEBUG>sduino: incomming message: (MU;P0=485;P1=-967;P2=1207;P4=-26358;D=01212121012121210121010121212121012121212421212121012101212121212121010101212121212101012121212101212121012101012121212101212121242121212101210121212121212101010121212121210101212121210121212101210101212121210121212120;CP=2;R=0;) 
> 2018.10.26 07:58:51.116 1: DEBUG>sduino: incomming message: (MU;P0=471;P1=-958;P2=1215;P4=-26356;D=01212121012121210121010121212121012121212421212121012101212121212121010101212121212101012121212101212121012101012121212101212121242121212101210121212121212101010121212121210101212121210121212101210101212121210121212120;CP=2;R=0;)

Ich bin mir hier aber nicht sicher, ob dies die u31 Messages sind...

**Comment by Kolbi** [comment]
`2018.10.29 08:21:36.649 4: sduino/msg READredu: MU;P0=136;P1=-969;P2=474;P3=1204;P4=-26332;D=0121312131213131312131213121312131213121212431313131213121313131313131212121313131213121312131213121313131213121312131213121312121243131313121312131313131313121212131313121312131213121312131313121312131213121312131212120;CP=2;R=0;
2018.10.29 08:21:36.650 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2018.10.29 08:21:36.651 4: sduino: decoded matched MU Protocol id 8 dmsg TXA071551556 length 44 RSSI = -74
2018.10.29 08:21:36.662 4: sduino: decoded matched MU Protocol id 8 dmsg TXA071551556 length 44 RSSI = -74
2018.10.29 08:21:36.662 4: sduino Dispatch: TXA071551556, Dropped due to short time or equal msg
2018.10.29 08:21:36.662 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2018.10.29 08:21:36.663 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2018.10.29 08:21:36.664 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.10.29 08:21:36.664 4: sduino: Fingerprint for MU Protocol id 31 -> Pollin Isotronik matches, trying to demodulate
2018.10.29 08:21:36.664 4: sduino: decoded matched MU Protocol id 31 dmsg u31#AEAA8 length 20 RSSI = -74
2018.10.29 08:21:36.687 4: SIGNALduino_unknown incomming msg: u31#AEAA8
2018.10.29 08:21:36.687 4: SIGNALduino_unknown rawData: AEAA8
2018.10.29 08:21:36.687 4: SIGNALduino_unknown Protocol: 31
2018.10.29 08:21:36.687 4: SIGNALduino_unknown converted to bits: 10101110101010101000
2018.10.29 08:21:36.687 4: SIGNALduino_unknown sduino Protocol:31 | To help decode or debug, please add u31! (attr sduino development u31)
2018.10.29 08:21:36.687 4: Unknown, please report
2018.10.29 08:21:36.691 3: sduino: Unknown code u31#AEAA8, help me!
2018.10.29 08:21:36.692 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2018.10.29 08:21:36.692 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2018.10.29 08:21:36.693 4: sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2018.10.29 08:21:36.693 4: sduino: Fingerprint for MU Protocol id 69 -> Hoermann matches, trying to demodulate
2018.10.29 08:21:36.693 4: sduino: Fingerprint for MU Protocol id 71 -> PV-8644 matches, trying to demodulate
2018.10.29 08:22:02.315 4: sduino/keepalive ok, retry = 0
2018.10.29 08:22:32.352 4: sduino/msg READredu: MU;P0=256;P1=-962;P2=478;P3=1213;P4=-26324;D=0121312131213131312131213121312131213121212431313131213121313131313131212121313131213121312131213121313131213121312131213121312121243131313121312131313131313121212131313121312131213121312131313121312131213121312131212120;CP=2;R=0;
2018.10.29 08:22:32.352 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2018.10.29 08:22:32.353 4: sduino: decoded matched MU Protocol id 8 dmsg TXA071551556 length 44 RSSI = -74
2018.10.29 08:22:32.359 4: sduino: decoded matched MU Protocol id 8 dmsg TXA071551556 length 44 RSSI = -74
2018.10.29 08:22:32.360 4: sduino Dispatch: TXA071551556, Dropped due to short time or equal msg
2018.10.29 08:22:32.360 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2018.10.29 08:22:32.361 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2018.10.29 08:22:32.361 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.10.29 08:22:32.361 4: sduino: Fingerprint for MU Protocol id 31 -> Pollin Isotronik matches, trying to demodulate
2018.10.29 08:22:32.361 4: sduino: decoded matched MU Protocol id 31 dmsg u31#AEAA8 length 20 RSSI = -74
2018.10.29 08:22:32.366 4: SIGNALduino_unknown incomming msg: u31#AEAA8
2018.10.29 08:22:32.366 4: SIGNALduino_unknown rawData: AEAA8
2018.10.29 08:22:32.366 4: SIGNALduino_unknown Protocol: 31
2018.10.29 08:22:32.366 4: SIGNALduino_unknown converted to bits: 10101110101010101000
2018.10.29 08:22:32.366 4: SIGNALduino_unknown sduino Protocol:31 | To help decode or debug, please add u31! (attr sduino development u31)
2018.10.29 08:22:32.366 4: Unknown, please report
2018.10.29 08:22:32.370 3: sduino: Unknown code u31#AEAA8, help me!
2018.10.29 08:22:32.371 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2018.10.29 08:22:32.371 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2018.10.29 08:22:32.372 4: sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2018.10.29 08:22:32.373 4: sduino: Fingerprint for MU Protocol id 69 -> Hoermann matches, trying to demodulate
2018.10.29 08:22:32.373 4: sduino: Fingerprint for MU Protocol id 71 -> PV-8644 matches, trying to demodulate
2018.10.29 08:25:19.484 4: sduino/msg READredu: MU;P0=-961;P1=475;P2=808;P3=-168;P4=144;P5=1217;P6=-26332;D=0102340105010501050505010501050105010501050101016505050501050105050505050501010105050501050105010501050105050501050105010501050105010101650505050105010505050505050101010505050105010501050105010505050105010501050105010501010;CP=1;R=0;
2018.10.29 08:25:19.485 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2018.10.29 08:25:19.486 4: sduino: decoded matched MU Protocol id 8 dmsg TXA071551556 length 44 RSSI = -74
2018.10.29 08:25:19.497 4: sduino: decoded matched MU Protocol id 8 dmsg TXA071551556 length 44 RSSI = -74
2018.10.29 08:25:19.498 4: sduino Dispatch: TXA071551556, Dropped due to short time or equal msg
2018.10.29 08:25:19.498 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2018.10.29 08:25:19.498 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2018.10.29 08:25:19.499 4: sduino: Fingerprint for MU Protocol id 19 -> minify matches, trying to demodulate
2018.10.29 08:25:19.502 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2018.10.29 08:25:19.502 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2018.10.29 08:25:19.502 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.10.29 08:25:19.503 4: sduino: Fingerprint for MU Protocol id 31 -> Pollin Isotronik matches, trying to demodulate
2018.10.29 08:25:19.503 4: sduino: decoded matched MU Protocol id 31 dmsg u31#AEAA8 length 20 RSSI = -74
2018.10.29 08:25:19.508 4: SIGNALduino_unknown incomming msg: u31#AEAA8
2018.10.29 08:25:19.508 4: SIGNALduino_unknown rawData: AEAA8
2018.10.29 08:25:19.508 4: SIGNALduino_unknown Protocol: 31
2018.10.29 08:25:19.508 4: SIGNALduino_unknown converted to bits: 10101110101010101000
2018.10.29 08:25:19.508 4: SIGNALduino_unknown sduino Protocol:31 | To help decode or debug, please add u31! (attr sduino development u31)
2018.10.29 08:25:19.508 4: Unknown, please report
2018.10.29 08:25:19.513 3: sduino: Unknown code u31#AEAA8, help me!
2018.10.29 08:25:19.514 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2018.10.29 08:25:19.514 4: sduino: Fingerprint for MU Protocol id 49 -> QUIGG_GT-9000 matches, trying to demodulate
2018.10.29 08:25:19.514 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2018.10.29 08:25:19.515 4: sduino: Fingerprint for MU Protocol id 61 -> FS10 matches, trying to demodulate
2018.10.29 08:25:19.516 4: sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2018.10.29 08:25:19.517 4: sduino: Fingerprint for MU Protocol id 69 -> Hoermann matches, trying to demodulate
2018.10.29 08:25:19.517 4: sduino: Fingerprint for MU Protocol id 70 -> FHT80TF matches, trying to demodulate
2018.10.29 08:25:19.518 4: sduino: Fingerprint for MU Protocol id 71 -> PV-8644 matches, trying to demodulate
2018.10.29 08:25:19.518 4: sduino: Fingerprint for MU Protocol id 72 -> Siro shutter matches, trying to demodulate
2018.10.29 08:25:19.518 4: sduino: Fingerprint for MU Protocol id 74 -> FS20 matches, trying to demodulate
2018.10.29 08:25:19.519 4: sduino: Fingerprint for MU Protocol id 80 -> EM (Energy-Monitor) matches, trying to demodulate`

Interessant irgendwie scheint es etwas mit dem Temperatursensor zu tun zu haben?

**Comment by HomeAutoUser** [comment]
Du hast Recht, es ist ein Temperatursensor  der ID8.

@sidey79 das Problem würde behoben werden, wenn wir den PR https://github.com/RFD-FHEM/RFFHEM/pull/334 umsetzen. So würde in diesem Falle vermutlich nicht mehr die ID zutreffen und der User hat eine eindeutige Erkennung.

**Comment by Kolbi** [comment]
Dann schliesse ich mal den Issue hier und hoffe auf PR #334 :)

**Comment by sidey79** [comment]
@HomeAutoUser 
Alles klar. Ich komme halt nicht immer ganz so schnell nach, bemühe mich aber die PRs zeitnah zu schließen.

**Comment by HomeAutoUser** [comment]
@sidey79 
deswegen ergänzen wir uns ja alle in dem Projekt :-)

**Comment by sidey79** [comment]
Ich finde es funktioniert gut :)  Die Änderungen sind klein und überschaubar. (meistens geht es dann schnell)

**Comment by Kolbi** [comment]
Jetzt kommt u34 anstatt u31 in Log...

**Comment by Kolbi** [comment]
> 2018.10.30 07:45:00.369 3: sduino: Unknown code u34#2F53E, help me!
> 2018.10.30 07:46:54.485 3: sduino: Unknown code u34#2F53E, help me!

**Comment by HomeAutoUser** [comment]
Hallo,
um eine klare Aussage treffen zu können, müsstest du bitte erneut eine Aufzeichnung mit Verbose 4 offenlegen wo man die passende Nachricht sieht was der Auslöser ist.

Es kann vorkommen, das manche Definitionen „Doppel“ zutreffen und du so ein u erhältst.

Im Falle u34 würde ein Aktor dahinter stehen für wen das Protokoll definiert wurde. Da manche Sensoren/Aktoren keine Prüfsumme besitzen, so „läuft das durch“. Sollte es nicht eingegrenzt werden können, so bleibt die Möglichkeit, blacklist_ID auf 34 setzen.

**Comment by Kolbi** [comment]
```
2018.10.30 10:52:42.596 4: sduino/msg READredu: MU;P0=204;P1=-969;P2=473;P3=1192;P4=-25314;D=0121213131312121312131213121213121312134313131312131213131313131312121213131313131213121312121313131212131213121312121312131213;CP=2;R=0;
2018.10.30 10:52:42.597 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2018.10.30 10:52:42.598 4: sduino: decoded matched MU Protocol id 8 dmsg TXA07056356A length 44 RSSI = -74
2018.10.30 10:52:42.612 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2018.10.30 10:52:42.613 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2018.10.30 10:52:42.614 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.10.30 10:52:42.614 4: sduino: Fingerprint for MU Protocol id 31 -> Pollin Isotronik matches, trying to demodulate
2018.10.30 10:52:42.615 4: sduino: Fingerprint for MU Protocol id 34 -> QUIGG_GT-7000 matches, trying to demodulate
2018.10.30 10:52:42.615 4: sduino: decoded matched MU Protocol id 34 dmsg u34#3952A length 20 RSSI = -74
2018.10.30 10:52:42.621 4: SIGNALduino_unknown incomming msg: u34#3952A
2018.10.30 10:52:42.621 4: SIGNALduino_unknown rawData: 3952A
2018.10.30 10:52:42.622 4: SIGNALduino_unknown Protocol: 34
2018.10.30 10:52:42.622 4: SIGNALduino_unknown converted to bits: 00111001010100101010
2018.10.30 10:52:42.622 4: SIGNALduino_unknown sduino Protocol:34 | To help decode or debug, please add u34! (attr sduino development u34)
2018.10.30 10:52:42.622 4: Unknown, please report
2018.10.30 10:52:42.626 3: sduino: Unknown code u34#3952A, help me!
2018.10.30 10:52:42.627 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2018.10.30 10:52:42.628 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2018.10.30 10:52:42.628 4: sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2018.10.30 10:52:42.629 4: sduino: Fingerprint for MU Protocol id 69 -> Hoermann matches, trying to demodulate
2018.10.30 10:52:42.629 4: sduino: Fingerprint for MU Protocol id 71 -> PV-8644 matches, trying to demodulate

2018.10.30 11:02:34.489 4: sduino/msg READredu: MU;P0=-971;P1=479;P2=1209;P3=-26328;D=010102020102020201020102010102010102023202020201020102020202020201010102020201020102010201010202010202020102010201010201010202320202020102010202020202020101010202020102010201020101020201020202010201020101020101020;CP=1;R=0;
2018.10.30 11:02:34.490 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2018.10.30 11:02:34.491 4: sduino: decoded matched MU Protocol id 8 dmsg TXA07156456C length 44 RSSI = -74
2018.10.30 11:02:34.502 4: sduino: decoded matched MU Protocol id 8 dmsg TXA07156456C length 44 RSSI = -74
2018.10.30 11:02:34.502 4: sduino Dispatch: TXA07156456C, Dropped due to short time or equal msg
2018.10.30 11:02:34.502 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2018.10.30 11:02:34.503 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2018.10.30 11:02:34.503 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.10.30 11:02:34.503 4: sduino: Fingerprint for MU Protocol id 31 -> Pollin Isotronik matches, trying to demodulate
2018.10.30 11:02:34.504 4: sduino: Fingerprint for MU Protocol id 34 -> QUIGG_GT-7000 matches, trying to demodulate
2018.10.30 11:02:34.504 4: sduino: decoded matched MU Protocol id 34 dmsg u34#37526 length 20 RSSI = -74
2018.10.30 11:02:34.508 4: SIGNALduino_unknown incomming msg: u34#37526
2018.10.30 11:02:34.508 4: SIGNALduino_unknown rawData: 37526
2018.10.30 11:02:34.509 4: SIGNALduino_unknown Protocol: 34
2018.10.30 11:02:34.509 4: SIGNALduino_unknown converted to bits: 00110111010100100110
2018.10.30 11:02:34.509 4: SIGNALduino_unknown sduino Protocol:34 | To help decode or debug, please add u34! (attr sduino development u34)
2018.10.30 11:02:34.509 4: Unknown, please report
2018.10.30 11:02:34.512 3: sduino: Unknown code u34#37526, help me!
2018.10.30 11:02:34.513 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2018.10.30 11:02:34.513 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2018.10.30 11:02:34.514 4: sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2018.10.30 11:02:34.514 4: sduino: Fingerprint for MU Protocol id 69 -> Hoermann matches, trying to demodulate
2018.10.30 11:02:34.514 4: sduino: Fingerprint for MU Protocol id 71 -> PV-8644 matches, trying to demodulate

2018.10.30 11:07:12.914 4: sduino/msg READredu: MU;P0=-963;P1=478;P2=1211;P3=-27422;D=010102020102020201020102010102010102023202020201020102020202020201010102020201020102010201010202010202020102010201010201010202320202020102010202020202020101010202020102010201020101020201020202010201020101020101020230;CP=1;R=0;
2018.10.30 11:07:12.915 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2018.10.30 11:07:12.916 4: sduino: decoded matched MU Protocol id 8 dmsg TXA07156456C length 44 RSSI = -74
2018.10.30 11:07:12.923 4: sduino: decoded matched MU Protocol id 8 dmsg TXA07156456C length 44 RSSI = -74
2018.10.30 11:07:12.923 4: sduino Dispatch: TXA07156456C, Dropped due to short time or equal msg
2018.10.30 11:07:12.924 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2018.10.30 11:07:12.924 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2018.10.30 11:07:12.925 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.10.30 11:07:12.925 4: sduino: Fingerprint for MU Protocol id 31 -> Pollin Isotronik matches, trying to demodulate
2018.10.30 11:07:12.925 4: sduino: Fingerprint for MU Protocol id 34 -> QUIGG_GT-7000 matches, trying to demodulate
2018.10.30 11:07:12.925 4: sduino: decoded matched MU Protocol id 34 dmsg u34#37526 length 20 RSSI = -74
2018.10.30 11:07:12.930 4: SIGNALduino_unknown incomming msg: u34#37526
2018.10.30 11:07:12.930 4: SIGNALduino_unknown rawData: 37526
2018.10.30 11:07:12.930 4: SIGNALduino_unknown Protocol: 34
2018.10.30 11:07:12.930 4: SIGNALduino_unknown converted to bits: 00110111010100100110
2018.10.30 11:07:12.930 4: SIGNALduino_unknown sduino Protocol:34 | To help decode or debug, please add u34! (attr sduino development u34)
2018.10.30 11:07:12.930 4: Unknown, please report
2018.10.30 11:07:12.934 3: sduino: Unknown code u34#37526, help me!
2018.10.30 11:07:12.934 4: sduino: Fingerprint for MU Protocol id 48 -> TFA Dostmann matches, trying to demodulate
2018.10.30 11:07:12.935 4: sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2018.10.30 11:07:12.935 4: sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2018.10.30 11:07:12.936 4: sduino: Fingerprint for MU Protocol id 69 -> Hoermann matches, trying to demodulate
2018.10.30 11:07:12.936 4: sduino: Fingerprint for MU Protocol id 71 -> PV-8644 matches, trying to demodulate


```

**Comment by HomeAutoUser** [comment]
Ich finde es komisch, das hier die 8 und 34 zutreffen.
Die 34 ist klar weil kein start definiert ist und das ist auch so bei der 8.
Könnte es sein das bei der 8 ein start von [1,-61] zutreffen würde?

Wieso trifft die 8 und 34 zu wenn längenbegrenzungen drin sind?
@elektron-bbs , kannst du dir dies mal ansehen?

**Comment by elektron-bbs** [comment]
Da scheint zufällig jeweils der Beginn der Nachricht bis zur ersten längeren Pause zu passen:
0 | 10 10 20 20 | 10 20 20 20 | 10 20 10 20 | 10 10 20 10 | 10 20 2
ergibt      3 | 7 | 5 | 2 | 6 
Wie allerdings aus den letzten Fragmenten ein Nibble von 6 wird, kann ich nicht nachvollziehen. Machts aus dem "halben" Bit automatisch eine 1 und hängt noch ein Bit von 0 an?

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
