### ISSUE TITLE
Add SEAV BeEasy TX blind controller

### ISSUE THREAD

**Issue by xschmidt2** [RFD-FHEM/RFFHEM#1276]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: SEAV
  - model name: BeEasy TX
  - pictures of the device / the board (very helpful)
![IMG_0084](https://github.com/user-attachments/assets/236e4863-28b6-43f6-b90b-2c27b265c03d)
![IMG_0085](https://github.com/user-attachments/assets/b0e33e27-c538-4ff9-9ea4-297e5cf510ba)
![IMG_0667](https://github.com/user-attachments/assets/21201683-ff33-4f90-b0b4-2bdb177a7473)
[txs1,_2,_3_en.pdf](https://github.com/user-attachments/files/17331310/txs1._2._3_en.pdf)

Was identified via Signalduino as Protokoll 30 or Protokoll 83
Remote control is used to steer blinds (up and down)
Config is done via dip switches.
Unitec_47031
  
## Specifications 

  - Microcontroller:
  - Version (Firmware):
  
14_SD_UT.pm:v1.0.5-s0/2024-09-08
  - Versionmodul (FHEM Module):SD_UT
  

DEF | Unitec_47031 4D
 
FUUID | 67023eb2-f33f-3e5d-dca7-2523db39ed6745dc
FVERSION | 14_SD_UT.pm:v1.0.5-s0/2024-09-08
IODev | sduino
LASTInputDev | sduino
MSGCNT | 61
NAME | Unitec_47031_4D
NR | 51
STATE | 1
TYPE | SD_UT
bitMSG | 010011010101
eventCount | 61
lastMSG | 4D5
sduino_DMSG | P83#4D5
sduino_MSGCNT | 65
sduino_Protocol_ID | 83
sduino_RAWMSG | MU;P0=-4896;P1=112;P2=-23212;P3=294;P4=-343;P5=620;P6=-680;P7=-11304;D=0123456345456363456345634563734563454563634563456345637345634545636345634563456373456345456363456345634563734563454563634563456345637345634545636345634563456373456345456363456345634563;CP=3;R=50;
sduino_RSSI | -49
sduino_TIME | 2024-10-10 07:43:37

Log file output (verbose 4)

```
sduino: Read, msg READredu: MU;P0=-29780;P1=292;P2=-660;P3=-349;P4=596;P5=-11066;D=01213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134;CP=1;R=16;O;
sduino: Read, msg READredu: MU;P0=-664;P1=279;P2=-360;P3=589;P4=-11047;P6=132;D=0123014101232301230123012301230141012323012301230123012301410123230123012301230123014101232301230123012301230141012323012301230123012306;CP=1;R=28;
sduino: Read, msg READredu: MU;P0=-3860;P1=298;P2=-652;P3=-334;P4=608;P5=-11053;D=01213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134;CP=1;R=28;O;
sduino: Read, msg READredu: MU;P0=-28952;P1=278;P2=-666;P4=-350;P5=594;P6=-11055;D=012145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521;CP=1;R=31;
sduino: Read, msg READredu: MU;P0=144;P1=298;P2=-646;P4=-332;P5=619;P6=-11040;P7=-428;D=12145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161217545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521612140;CP=1;R=31;
sduino: Read, msg READredu: MU;P0=-7152;P1=287;P2=-659;P4=-344;P5=610;P6=-11037;D=01214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145;CP=1;R=32;O;
sduino: Read, msg READredu: MU;P0=-3956;P1=262;P2=-685;P3=-371;P4=572;P5=-11060;D=01213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134;CP=1;R=36;O;
sduino: Read, msg READredu: MU;P0=-674;P1=274;P2=-357;P3=594;P4=-11052;D=01012341012323012301230123010123410123230123012301230101234101232301230123012301012341012323012301230123010123410123230123012301230101;CP=1;R=36;
sduino: Read, msg READredu: MU;P0=-347;P1=265;P2=-677;P5=597;P6=-11054;P7=200;D=12105052105210521052121056121050521052105210521210561210505210521052105212105612705052705210521052121056121050521052105210521210561210505210521052105212105612105052105210521052121056121050521052105210521210561210505210521052105212105612105052105210521052;CP=1;R=42;O;
sduino: Read, msg READredu: MU;P0=254;P1=-703;P2=-390;P3=563;P4=-11056;D=01023401023231023102310231010234010232310231023102310102340102323102310231023101023;CP=0;R=43;
sduino: Read, msg READredu: MU;P0=-23636;P1=257;P2=-686;P3=-369;P4=575;P5=-11058;D=01213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134;CP=1;R=17;O;
sduino: Read, msg READredu: MU;P0=-680;P1=262;P2=-360;P3=582;P4=-11048;D=010123410123230123012301230101234101232301230123012301012341012323012301230123010123;CP=1;R=24;
sduino: Read, msg READredu: MU;P0=-3680;P1=280;P2=-665;P4=-350;P5=594;P6=-11060;D=01214545214521452145212145612145452145214521452121456121454521452145214521214561214545214521452145212145612145452145214521452121456121454521452145214521214561214545214521452145212145612145452145214521452121456121454521452145214521214561214545214521452145;CP=1;R=5;O;
sduino: Read, msg READredu: MU;P0=-11057;P1=266;P2=-681;P3=152;P4=-492;P5=584;P7=-360;D=12341252175217521752121750121757521752175217521217501217575217521752175212175012175752175217521752121750121757521752175217521217501217575217521752175212175012175752175217521752121750121757521752175217521217501217575217521752175212175012175752175217521752;CP=1;R=23;O;
sduino: Read, msg READredu: MU;P0=279;P1=-666;P2=-358;P3=590;P4=-11054;D=0102340102323102310231023101023401023231023102310231010234010232310231023102310102340102323102310231023101023401023231;CP=0;R=26;
```

**Comment by elektron-bbs** [comment]
Ich denke, diese Fernbedienung dürfte keine größere Hürde darstellen. Der Chip ist ein HT12E - Protokoll 83 passt also schon mal.

Du könntest erst mal versuchen das Attribut "model" auf den Wert "RH787T" zu setzen. Das ist eine Fernbedienung für einen Deckenventilator, allerdings mit mehr als zwei Tasten.

Vermutlich müssen wir aber ein neues Modell anlegen. Dafür benötigen wir die Nachrichten wie oben, aber gekennzeichnet mit welcher Taste ausgelöst wurde und welche Adresse mit den DIP-Schaltern eingestellt ist.

**Comment by xschmidt2** [comment]
Hi Elektron-bbs - das ging schnell! Den Typ RH787T hab ich eingestellt, leider reagiert der überhaupt nicht, also ich sehe keinen state der ankommt. Ich hab gerade für einen Schalter nochmal 5x Taste runter und 5x Taste hoch gedrückt, anbei die Schnipsel:

Die Belegung der Pins ist folgendermaßen:

1 | off
2 | on
3 | on
4 | off
5 | on
6 | off
7 | on
8 | off
9 | on
10 | off

Taste runter:
	
sduino: Read, msg READredu: MU;P0=-17444;P1=290;P2=-654;P4=-349;P5=596;P6=-11045;D=012145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545;CP=1;R=29;
sduino: Read, msg READredu: MU;P0=-31388;P1=288;P2=-661;P3=-354;P4=596;P5=-11033;D=012134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134;CP=1;R=32;
sduino: Read, msg READredu: MU;P0=-16412;P1=283;P2=-662;P3=-354;P4=594;P5=-11048;D=012134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512;CP=1;R=33;
sduino: Read, msg READredu: MU;P0=-5312;P1=294;P2=-658;P4=-335;P5=598;P6=-11050;D=0121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521612145452145;CP=1;R=35;
sduino: Read, msg READredu: MU;P0=-23776;P1=285;P2=-665;P3=-340;P4=610;P5=-11040;D=01213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134;CP=1;R=31;
sduino: Read, msg READredu: MU;P0=-27112;P1=295;P2=-650;P3=-339;P4=608;P5=-11042;D=012134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134213421;CP=1;R=24;
sduino: Read, msg READredu: MU;P0=-15496;P1=286;P2=-646;P4=-345;P5=614;P6=-11035;D=012145452145214521452145216121454521452145214521452161214545214521452145214521612145452145214521452145216121454521452145214521452161214545214521452145214521;CP=1;R=31;
sduino: Read, msg READredu: MU;P0=-668;P1=283;P2=-349;P3=597;P4=-11039;D=01230141012323012301230123012301410123230123012301230123014101232301230123012301230141012323012301230123012301;CP=1;R=29;
sduino: Read, msg READredu: MU;P0=-11039;P1=283;P2=-653;P4=-340;P5=613;P6=220;D=01214545214521452145214521012145452145214521452145210121454521452145214521452101214545214521452145214521012145452145214521452145210121454521452145214521452101264545214521452145214521012145452145214521452145210121454521452145214521452101214545214521452145;CP=1;R=29;O;

Taste hoch:
sduino: Read, msg READredu: MU;P0=-670;P1=282;P2=-369;P3=579;P4=-11054;P5=212;D=0101234105232305230523012301012341012323;CP=1;R=41;
sduino: Read, msg READredu: MU;P0=-25696;P1=269;P2=-667;P3=-354;P4=588;P5=-11065;D=01213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134212134512134342134213421342121345121343421342134213421213451213434213421342134;CP=1;R=41;O;
sduino: Read, msg READredu: MU;P0=-18816;P1=254;P2=-717;P4=-393;P5=550;P6=-11051;D=01214545214521452145212145612145452145214521452121456121454521452145214521214561214545214521452145212145612145452145214521452121456121454521452145214521214561214545214521452145212145612145452145214521452121456121454521452145214521214561214545214521452145;CP=1;R=42;O;
sduino: Read, msg READredu: MU;P0=245;P2=-680;P4=-354;P5=585;P6=-11053;D=0204545204520452045202045602045452045204520452020456020454520452045204520204560204545204520452045202045602045452045204520452020456020454520452045204520204560204545204520452045202045602045452045204520452020456020;CP=0;R=43;
sduino: Read, msg READredu: MU;P0=-701;P1=242;P2=-388;P3=557;P4=-11070;D=01012341012323012301230123010123410123230123012301230101;CP=1;R=52;
sduino: Read, msg READredu: MU;P0=-11047;P1=250;P2=-712;P4=-408;P5=537;D=01214545214521452145212145012145452145214521452121450121454521452145214521214501214545214521452145212145012145452145214521452121450121454521452145214521214501214545214521452145212145012145452145214521452121450121454521452145214521214501214545214521452145;CP=1;R=42;O;
sduino: Read, msg READredu: MU;P0=282;P1=-666;P2=-346;P3=593;P4=-11061;P5=219;D=010234015232315231023102310102340102323102310231023101023401523231523102310231010234010232310231023102310102340102323;CP=0;R=43;
sduino: Read, msg READredu: MU;P0=591;P1=273;P2=-671;P3=-350;P5=-11053;D=12130302130213021302121305121303021302130213021213051213030213021302130212130512130302130213021302121305121303021302130213021213051213030213021302130212130512130302130213021302121305121303021302130213021213051213030213021302130212130512130302130213021302;CP=1;R=41;O;
sduino: Read, msg READredu: MU;P0=-687;P1=264;P4=-358;P5=585;P6=-11056;D=010145450145014501450101456101454501450145014501014561014545014501450145010145610145450145014501450101456101454501450145014501014561014545014501450145010145610145450145014501450101456101454501450145014501014561014545014501450145010145610145450145;CP=1;R=36;

Ich hab noch 5 weitere Sender, macht es Sinn das gleiche Spiel mit allen durchzuspielen?

**Comment by elektron-bbs** [comment]
Ich denke, ich habe die Codes schon erkannt:

```
          DIP: 1234567890 BB
P83#955   Bit: 1001010101 01
P83#956   Bit: 1001010101 10

DIP-Switch: 1-10
Button:     01 - down, 10 - up
```

Wenn bei den anderen Sendern verschiedene Schalter-Kombinationen eingestellt sind, dann wäre es günstig diese auch noch zu erfassen.  Die ersten 10 Bit stellen offensichtlich die Schalterstellungen dar.
Unklar ist mir noch der Jumper. Der scheint laut Platine wahrscheinlich die Schalter 1-4 zu beeinflussen. Diesen müssten wir auch noch probieren.

Mit dem Modell RH787T kann das nicht funktionieren. Ich muss ein neues Modell erstellen.

**Comment by xschmidt2** [comment]
OK, zweiter Sender:
1	on
2	off
3	on
4	on
5	off
6	off
7	on
8	off
9	on
10	off
Jumper steht ebenfalls auf 1-2
![IMG_0671](https://github.com/user-attachments/assets/29b69d1b-98e2-48ac-bcbe-b64c28e901e5)


Taste hoch:
Zeile 323: 2024.10.11 19:44:34 4: sduino: Read, msg READredu: MU;P0=-679;P1=283;P2=-347;P3=621;P4=-11300;D=0123014123012323010123012301230141230123230101230123012301;CP=1;R=37;
	Zeile 356: 2024.10.11 19:44:34 4: sduino: Read, msg READredu: MU;P0=-25312;P1=286;P2=-354;P3=626;P4=-677;P5=-11292;D=01234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123;CP=1;R=37;O;
	Zeile 387: 2024.10.11 19:44:32 4: sduino: Read, msg READredu: MU;P0=-675;P1=288;P2=-354;P3=612;P4=-11291;D=0123014123012323010123012301230141230123230101230123012301412301232301012301230123014123012323010123012301230141230123230101230123012301412301232301012301230123014123012323010123012301230141230123230101230123012;CP=1;R=38;
	Zeile 423: 2024.10.11 19:44:32 4: sduino: Read, msg READredu: MU;P0=-7756;P1=297;P2=-344;P3=631;P4=-664;P6=-11307;D=01234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123;CP=1;R=37;O;
	Zeile 458: 2024.10.11 19:44:31 4: sduino: Read, msg READredu: MU;P0=-3360;P1=290;P2=-360;P3=604;P4=-683;P5=-11299;P6=92;D=01234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123412341512341232341412341234123415123412323414123412341234156;CP=1;R=37;
	Zeile 497: 2024.10.11 19:44:29 4: sduino: Read, msg READredu: MU;P0=-17488;P1=298;P2=-353;P3=616;P4=-668;P5=-11301;D=01234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123412341512341232341412341234123415123412323414123412341234151234123234141234123;CP=1;R=38;O;
	Zeile 530: 2024.10.11 19:44:27 4: sduino: Read, msg READredu: MU;P0=-29236;P1=281;P2=-353;P3=620;P4=-684;P6=-11302;D=01234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123;CP=1;R=34;O;
	Zeile 557: 2024.10.11 19:44:24 4: sduino: Read, msg READredu: MU;P0=-663;P1=292;P2=-344;P3=634;P4=-11310;D=012301412301232301012301230123014123012323010123012301230141230123230101230123012301;CP=1;R=18;
	Zeile 597: 2024.10.11 19:44:24 4: sduino: Read, msg READredu: MU;P0=-4208;P1=303;P2=-343;P3=621;P4=-668;P6=-11300;D=01234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123412341612341232341412341234123416123412323414123412341234161234123234141234123;CP=1;R=3;O;

Taste runter:
Zeile  59: 2024.10.11 19:45:15 4: sduino: Read, msg READredu: MU;P0=-687;P1=280;P2=-369;P3=592;P4=-11314;D=0101234123012323010123012301012341230123230101230123010123;CP=1;R=40;
	Zeile  92: 2024.10.11 19:45:15 4: sduino: Read, msg READredu: MU;P0=-24160;P1=277;P2=-363;P3=602;P4=-690;P6=-11311;D=01234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123;CP=1;R=38;O;
	Zeile 123: 2024.10.11 19:45:13 4: sduino: Read, msg READredu: MU;P0=-8732;P1=268;P2=-381;P3=590;P4=-699;P6=-11320;D=01234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123;CP=1;R=40;O;
	Zeile 152: 2024.10.11 19:45:11 4: sduino: Read, msg READredu: MU;P0=-700;P1=261;P2=-367;P3=593;P4=-11322;D=010123412301232301012301230101234123012323010123012301012341230123230101230123010123;CP=1;R=54;
	Zeile 184: 2024.10.11 19:45:10 4: sduino: Read, msg READredu: MU;P0=-21288;P1=251;P2=-415;P3=553;P4=-732;P6=-11305;P7=184;D=01234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123414123612341232341412341234141236123412323414123412341412361234123234141234123414123612341232341412341234141236123412323414123412341412361234723234141234123;CP=1;R=36;O;
	Zeile 205: 2024.10.11 19:45:08 4: sduino: Read, msg READredu: MU;P0=-692;P1=278;P2=-371;P3=582;P4=-11313;D=01012341230123230101230123010123412301232301012301230101234123012323;CP=1;R=24;
	Zeile 240: 2024.10.11 19:45:08 4: sduino: Read, msg READredu: MU;P0=-20372;P1=256;P2=-391;P3=583;P4=-709;P5=-11321;D=01234123234141234123414123512341232341412341234141235123412323414123412341412351234123234141234123414123512341232341412341234141235123412323414123412341412351234123234141234123414123512341232341412341234141235123412323414123412341412351234123234141234123;CP=1;R=22;O;
	Zeile 268: 2024.10.11 19:45:06 4: sduino: Read, msg READredu: MU;P0=-703;P1=262;P2=-374;P3=593;P4=-11323;D=010123412301232301012301230101234123012323010123012301012341230123230101230123010123;CP=1;R=33;
	Zeile 300: 2024.10.11 19:45:05 4: sduino: Read, msg READredu: MU;P0=-1064;P1=273;P2=-382;P3=586;P4=-690;P5=-11322;D=01234123234141234123414123512341232341412341234141235123412323414123412341412351234123234141234123414123512341232341412341234141235123412323414123412341412351234123234141234123414123512341232341412341234141235123412323414123412341412351234123234141234123;CP=1;R=35;O;
	

Hoffe das hilft weiter

**Comment by elektron-bbs** [comment]
Ja, das hilft weiter. Nur ist diesmal die Richtung hoch/runter gerade umgekehrt:

```
          DIP: 1234567890 BB
P83#955   Bit: 1001010101 01 - Taste runter
P83#956   Bit: 1001010101 10 - Taste hoch

          DIP: 1234567890 BB
P83#4D5   Bit: 0100110101 01 - Taste hoch
P83#4D6   Bit: 0100110101 10 - Taste runter
```

Entweder hast du dich beim Beschriften vertan, oder ich habe das Prinzip noch nicht richtig verstanden. Du kannst das auch selbst mal probieren. Wenn du deinen SIGNALduino auf verbose 4 stellst, siehst du ja auch die Ausgabe der Bits:

```
2024.10.11 20:39:28 4: sduino_dummy: SD_UT protocol 86, bitData 100101010101, hlen 3
```

**Comment by elektron-bbs** [comment]
Ich habe jetzt schon mal etwas vorbereitet. Es gibt einen neuen Branch für diese Fernbedienung. Das Update darauf erfolgt mit folgendem Befehl:
```
update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/master_SEAV-BeEasy-TX/controls_signalduino.txt
```

Das Attribut "model" für diese Fernbedienung ist "BeEasy_TX".
Bitte testen und berichten.

**Comment by xschmidt2** [comment]
Hallo Elektron-bbs,

Vielen Dank, funktioniert super!
Nur zwei Anpassungen: der eine Rolladen bei mir läuft tatsächlich verkehrt herum, kann man die Signale einfach tauschen?
Ansonsten bekomme ich beim Senden von Signale. Immer folgenden Hinweis: die Angaben die du senden möchtest sind nicht sicher, möchten sie trotzdem senden? Kann man das abstellen?

Aber ich konnte alle Rollläden einrichten, super Job und vielen Dank!

Liebe Grüße 
Marco

**Comment by elektron-bbs** [comment]
> Vielen Dank, funktioniert super! Nur zwei Anpassungen: der eine Rolladen bei mir läuft tatsächlich verkehrt herum, kann man die Signale einfach tauschen?

D.h. den einen Funktaster musst du um 180° drehen, damit die Pfeile in die richtige Richtung zeigen? Da ist dann sicher der Motor falsch angeschlossen. Also am besten richtig anklemmen.

> Ansonsten bekomme ich beim Senden von Signale. Immer folgenden Hinweis: die Angaben die du senden möchtest sind nicht sicher, möchten sie trotzdem senden? Kann man das abstellen?

Mhmm, die Meldung habe ich noch nie gesehen. Kommt das vom Browser?

Lädst du mal bitte  noch Nachrichten hoch, einmal die Jumper-Stellung 1-2 und dann 2-3.

**Comment by xschmidt2** [comment]
Hallo Elektron-bbs,

sorry, hat etwas gedauert. Anbei nochmal mit der Jumperstellung 2-3:
Taste Runter
sduino: SD_UT protocol 83, bitData 100101010101, hlen 3

sduino: Read, msg READredu: MU;P0=108;P1=-647;P2=298;P3=-343;P4=606;P6=-190;P7=-11023;D=01234341234123412341264127212346412341234123412341272123434123412341234123412721234341234123412341234127212343412341234123412341272123434123412341234123412;CP=2;R=222;
sduino: Read, msg READredu: MU;P0=-23836;P1=315;P2=-648;P3=-336;P4=606;P5=-11030;D=012134342134213421342134215121343421342134213421342151;CP=1;R=222;
sduino: Read, msg READredu: MU;P0=324;P1=-1476;P2=420;P3=-616;P4=224;P5=-305;P6=649;P7=-11013;D=0123456305630563070305656305630563056305630703056563056305630563056307030565630563056305630563070305656305630563056305630;CP=0;R=224;
sduino: Read, msg READredu: MU;P0=-31100;P1=303;P2=-640;P3=-356;P4=608;P5=-11025;P6=188;D=01213434213421342134213421512134342134213421342134215121343421342134213421342151213436;CP=1;R=225;
sduino: Read, msg READredu: MU;P0=-108;P1=306;P2=-635;P3=-330;P4=632;P5=-11021;P6=231;D=01213434213421342134213421512134342134213421342134215121343421342134213421342151213434263426342634263421512134342134213421342134215121343421342134213421342151213434213421342134213421512134342134213421342134215121343421342134213421342151213434213421342134;CP=1;R=224;O;
sduino: Read, msg READredu: MU;P0=-645;P1=288;P2=-11021;P3=-336;P4=619;P5=-17112;D=012101343401340134013401340121013434013401340134013401210134340134013401340134012101343401340134013401340121013434013401340134013401210134340134013401340134015;CP=1;R=237;
sduino: Read, msg READredu: MU;P0=-2664;P1=279;P3=-659;P4=196;P5=-338;P6=613;P7=-11035;D=01013456315631563156317131565631563156315631563171315656315631563156315631713156563156315631563156317131565631563156315631563171315656315631563156315631713156563156315631563156317131565631563156315631563171315656315631563156315631713156563156315631563156;CP=1;R=238;O;

Taste hoch
sduino: SD_UT protocol 83, bitData 100111111110, hlen 3

sduino: Read, msg READredu: MU;P0=-11055;P1=275;P2=-675;P3=-362;P4=579;D=01213434212121212121212134012134342121212121212121340121343421212121212121213401213434212121212121212134012134342121212121212121340121343421212121212121213401213434212121212121212134012134342121212121212121340121343421212121212121213401213434212121212121;CP=1;R=244;O;
sduino: Read, msg READredu: MU;P0=-11051;P1=262;P2=-673;P4=-362;P5=593;P6=-3572;P7=180;D=1214545212167272145012145452121212121212121450121454521212121212121214501214545212121212121212145012145452121212121212121450121454521212121212121214501214545212121212121212145012145452121212121212121450121454521212121212121214501214545212121212121212145;CP=1;R=241;
sduino: Read, msg READredu: MU;P0=-367;P1=576;P2=-11053;P3=265;P4=-682;D=01234301014343434343434343012343010143434343434343430123430101434343434343434301234301014343434343434343012343010143434343434343430123430101434343434343434301234301014343434343434343012343010143434343434343430123430101434343434343434301;CP=3;R=244;
sduino: Read, msg READredu: MU;P0=-672;P1=268;P2=-365;P3=581;P4=-11040;P5=-24992;D=01010101010101012341012323010101010101010123410123230101010101010101235;CP=1;R=244;
sduino: Read, msg READredu: MU;P0=-672;P1=268;P2=-379;P3=573;P4=-11054;D=01010101012341012323010101010101010123410123230101010101010101234101232301010101010101012341012323010101010101010123410123230101010101010101234101232301010101010101012341012323010101010101010123410123230101010101010101234101232301010101010101012341012323;CP=1;R=244;O;
sduino: Read, msg READredu: MU;P0=265;P1=-359;P2=594;P3=-11048;P4=-674;D=01230401212404040404040404012304012124040404040404040123040121240404040404040401230401212404040404040404012;CP=0;R=244;
sduino: Read, msg READredu: MU;P0=-11058;P1=270;P2=-668;P4=-363;P5=584;P6=-1696;P7=138;D=12145452121212121672745012145452121212121212121450121454521212121212121214501214545212121212121212145012145452121212121212121450121454521212121212121214501214545212121212121212145012145452121212121212121450121454521212121212121214501214545212121212121212;CP=1;R=243;O;

Das ist wieder der "verdrehte" Rolladen - kann sein dass ich hoch und runter wieder vertauscht habe. In eine Richtung fährt er trotzdem, in die Andere bei Jumper 2-3 nicht. Wenn ich die Anleitung richtig verstanden habe, können darüber Gruppen gesteuert werden.

Für mich funktioniert die Implementierung schon sehr gut. Einziger "Minibug" den ich gefunden habe: eine Fernbedienung hat den Hex wert 020, der wird aber nur als 20 übergeben und dann abgelehnt, weil zu kurz. Von Hand konnte ich das Device aber über define korrekt anlegen, nur autocreate funktioniert dann nicht.

Vielen Dank für Deinen Einsatz!
kommt das Modul zukünftig in den offiziellen Signalduino Branch?

LG
Marco

**Comment by xschmidt2** [comment]
Noch eine Anmerkung zu den Jumpern:
a) 12 Bit Standard-Konfiguration T1, T2
Der Sender wiird werkseitig in folgender Konfiguration geliefert: Jumper J1 (1-2)
b) Kanalseparation: 1 gemeinsam und 1 privat.
Jumper J1 (2-3).
In dieser Anordnung erzeugt die Funksteuerung einen gemeinsamen Code (T1) (z.B.: Mitbesitzereingang) und einen Privatnutzer-Code (T2).
Die Codetrennung ist die des Typs 4 + 6, demnach dienen die ersten 4 SW1-Schalter zur Kodierung des gemeinsamen Codes, und die restlichen 6 zur Kodierung des Privat-Codes

**Comment by elektron-bbs** [comment]
> sorry, hat etwas gedauert. Anbei nochmal mit der Jumperstellung 2-3: Taste Runter sduino: SD_UT protocol 83, bitData 100101010101, hlen 3

Mhmm, das ist aber der gleiche Code den du schon am Anfang mal gepostet hattest:

`Taste runter: 100101010101
`

wahrscheinlich also hier noch Jumper auf 1-2.
 
> Taste hoch sduino: SD_UT protocol 83, bitData 100111111110, hlen 3

Jetzt sind die Bits 5-10 alle auf 1 gesetzt. Unverändert bleiben die ersten 4 Bit (1001). Das erste Nibble ist also für die Gruppe, hier in diesem Beispiel die 9.

Den Jumper hätten sie sich demnach eigentlich sparen können, da ich das gleiche ja auch mit DIP-Schalter 5-10 einstellen könnte. Naja, egal, ich denke an der Software muss ich dafür nichts ändern. Es legt halt jetzt ein Gerät mit Ident 9FC an.

 
> Das ist wieder der "verdrehte" Rolladen - kann sein dass ich hoch und runter wieder vertauscht habe. In eine Richtung fährt er trotzdem, in die Andere bei Jumper 2-3 nicht. Wenn ich die Anleitung richtig verstanden habe, können darüber Gruppen gesteuert werden.

Vielleicht muss der Gruppencode ja auch erst angelernt werden.

> Für mich funktioniert die Implementierung schon sehr gut. Einziger "Minibug" den ich gefunden habe: eine Fernbedienung hat den Hex wert 020, der wird aber nur als 20 übergeben und dann abgelehnt, weil zu kurz. Von Hand konnte ich das Device aber über define korrekt anlegen, nur autocreate funktioniert dann nicht.

Das sehe ich mir nochmal an. Ich gebe Bescheid, wenn ich den Fehler gefunden habe.

> Vielen Dank für Deinen Einsatz! kommt das Modul zukünftig in den offiziellen Signalduino Branch?

Ja, wenn es fertig ist.

**Comment by elektron-bbs** [comment]
Ich habe den Fehler mit dem 0x0xx jetzt behoben. Bitte führe nochmal ein Update wie hier https://github.com/RFD-FHEM/RFFHEM/issues/1276#issuecomment-2408666935 beschrieben durch und teste das Anlegen des Tasters mit der Adresse 0x020 nochmal.

**Comment by xschmidt2** [comment]
Perfekt, hab’s getestet, funktioniert!
vielen Dank!

**Comment by xschmidt2** [comment]
Nein, klappt einwandfrei! darfst du gerne mergen!

LG
Marco

Am So., 27. Okt. 2024 um 21:37 Uhr schrieb elektron-bbs <
***@***.***>:

**Comment by elektron-bbs** [comment]
Der Branch ist jetzt im Master.
Ich betrachte das Problem als gelöst und schließe dieses.
