### ISSUE TITLE
Protokoll für "Rolladen7" Domo 40 F Rolläden u57

### ISSUE THREAD

**Issue by DanielSFL** [RFD-FHEM/RFFHEM#137]
Arduino Nano mit SignalduinoFW und RF-5V Empfänger

Gedrückt wurde die Stop-Taster am mitgelieferten Wandsender.

(Hinweis:  nachgekaufte Sender werden als Dooya erkannt. Die Wandsender jedoch nicht. zumindest nicht automatisch)

2017.02.24 18:52:21 4: sduino/msg READ: MC;LL=-789;LH=635;SL=-421;SH=297;D=5554AA524AAA952490;C=356;L=69;
2017.02.24 18:52:21 4: sduino: Found manchester Protocol id 10 clock 356 -> OSV2o3
2017.02.24 18:52:21 4: sduino: Found manchester Protocol id 57 clock 356 -> m-e
2017.02.24 18:52:21 4: SIGNALduino_unknown incomming msg: u57#AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown rawData: AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown Protocol: 57
2017.02.24 18:52:21 4: SIGNALduino_unknown converted to bits: 101010101010101101010101101011011011010101010101011010101101101101101111
2017.02.24 18:52:21 4: Unknown, please report
2017.02.24 18:52:21 4: SIGNALduino_unknown incomming msg: u57#AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown rawData: AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown Protocol: 57
2017.02.24 18:52:21 4: SIGNALduino_unknown converted to bits: 101010101010101101010101101011011011010101010101011010101101101101101111
2017.02.24 18:52:21 4: Unknown, please report
2017.02.24 18:52:21 3: sduino: Unknown code u57#AAAB55ADB5556ADB6F, help me!
2017.02.24 18:52:21 4: sduino/msg READ: MU;P0=-783;P1=-422;P2=350;P5=647;D=20202020202020512020202051202051205120512020202020202051202020512051205120512051;CP=2;
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 40 -> romotec matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 49 -> quigg_gt9000 matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: Fingerprint for MU Protocol id 60 -> WS7000 matches, trying to demodulate
2017.02.24 18:52:21 4: sduino: decoded matched MU Protocol id 60 dmsg KFEF6AFEEAA length 40
2017.02.24 18:52:21 1: CUL_WS Cannot decode KFEF6AFEEAA
2017.02.24 18:52:21 4: sduino/msg READ: MC;LL=-768;LH=659;SL=-400;SH=316;D=5554AA524AAA952490;C=357;L=69;
2017.02.24 18:52:21 4: sduino: Found manchester Protocol id 10 clock 357 -> OSV2o3
2017.02.24 18:52:21 4: sduino: Found manchester Protocol id 57 clock 357 -> m-e
2017.02.24 18:52:21 4: SIGNALduino_unknown incomming msg: u57#AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown rawData: AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown Protocol: 57
2017.02.24 18:52:21 4: SIGNALduino_unknown converted to bits: 101010101010101101010101101011011011010101010101011010101101101101101111
2017.02.24 18:52:21 4: Unknown, please report
2017.02.24 18:52:21 4: SIGNALduino_unknown incomming msg: u57#AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown rawData: AAAB55ADB5556ADB6F
2017.02.24 18:52:21 4: SIGNALduino_unknown Protocol: 57
2017.02.24 18:52:21 4: SIGNALduino_unknown converted to bits: 101010101010101101010101101011011011010101010101011010101101101101101111
2017.02.24 18:52:21 4: Unknown, please report
2017.02.24 18:52:21 3: sduino: Unknown code u57#AAAB55ADB5556ADB6F, help me!
2017.02.24 18:52:21 4: sduino/msg READ: MC;LL=-768;LH=659;SL=-400;SH=316;D=5554AA524AAA95249;C=357;L=68;
2017.02.24 18:52:21 4: sduino: Found manchester Protocol id 10 clock 357 -> OSV2o3
2017.02.24 18:52:21 4: sduino: Found manchester Protocol id 57 clock 357 -> m-e
2017.02.24 18:52:21 4: SIGNALduino_unknown incomming msg: u57#AAAB55ADB5556ADB6
2017.02.24 18:52:21 4: SIGNALduino_unknown rawData: AAAB55ADB5556ADB6
2017.02.24 18:52:21 4: SIGNALduino_unknown Protocol: 57
2017.02.24 18:52:21 4: SIGNALduino_unknown converted to bits: 10101010101010110101010110101101101101010101010101101010110110110110
2017.02.24 18:52:21 4: Unknown, please report
2017.02.24 18:52:21 4: SIGNALduino_unknown incomming msg: u57#AAAB55ADB5556ADB6
2017.02.24 18:52:21 4: SIGNALduino_unknown rawData: AAAB55ADB5556ADB6
2017.02.24 18:52:21 4: SIGNALduino_unknown Protocol: 57
2017.02.24 18:52:21 4: SIGNALduino_unknown converted to bits: 10101010101010110101010110101101101101010101010101101010110110110110
2017.02.24 18:52:21 4: Unknown, please report
2017.02.24 18:52:21 3: sduino: Unknown code u57#AAAB55ADB5556ADB6, help me!
2017.02.24 18:52:35 4: sduino/KeepAliveOk: 1
2017.02.24 18:52:35 4: sduino/keepalive retry = 0

**Comment by sidey79** [comment]
Ist dein Fall noch aktuell?

**Comment by DanielSFL** [comment]
Ich kann mich zumindest nicht mehr an offene Probleme erinnern.... von daher hatte sich das bestimmt erledigt. Wobei ich ehrlich zugeben muss, dass ich mich nicht mehr genau dran erinnern kann, was letztendlich das Problem gelößt hat.  Von daher kann das gern dicht. Danke der Nachfrage.
