### ISSUE TITLE
Vorschlag zur besseren Übersichtlichkeit | uProtokolldaten in Datei umlenken

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#141]
Hallo,
ich beleuchte und beschäftige mich gerade mit einem unbekannten Protokoll.
Da sämtliche unbekannten Protokolle "nur" zwischen den normalen Ereignissen im Logfile auftauchen und somit es schwierig ist bei sehr vielen Sensoren das passende zu finden bzw. alle passenden vom "Unbekannten" zu finden, so leite ich mir gerade mit einer Modifikation sämtliche Unbekannten in deine Datei.

Dabei ging mir durch den Kopf bzw. bei einem Brainstorming mit Usern, das man doch ggf. eine Option integrieren könnte, welche sämtliche unbekannten, Bsp. u40 oder u6 in separat in eine Datei weiterleitet.
Somit sind in einer Datei nur Meldungen vom zu untersuchenden Protokoll mit Daten. Das Ganze erleichtert natürlich das Beleuchten und Auswerten der Daten einfacher.

Denkt mal drüber nach.

**Comment by HomeAutoUser** [comment]
Vorschlag für die sub SIGNALduino_un_Parse($$) | 90_SIGNALduino_un.pm

Somit erstellt er ein Logfile in das Stammverzeichnis von FHEM.
Definierbar für die Protocoll_ID & Länge um das für "Jedermann Umgebung" anzupassen.

`	################################# TEST #############################
	# Ausgabe uProtokolle | derzeit nur u40#
	if ($protocol == "40"&& length($bitData)>=16)
	{
	### Ausgabe in Datei Umleiten
	my $datestring = strftime("%Y.%m.%d %H:%M:%S", localtime);				# Zeitformat
	
	my $Dateiname = ">>_Log_u$protocol.txt";
	open (STDOUT, "|tee $Dateiname") or die "Error tee $!\n";

	print "$datestring - $msg - $bitData\n";								# Ausgabe - Datum|Zeit - msg - BitData
	close(STDOUT);
	################################# ENDE #############################`

Somit kann man Rohdaten sammeln und es ist auch leichter nachvollziehbar.

**Comment by sidey79** [comment]
Vom Prinzip her kenne ich das Problem und würde es auch gerne lösen. Irgendwie finde ich die Lösung eine Datei im Dateisystem anzulegen nicht so mega gut. Vielleicht kann man die Ausgabe so umstellen, dass ein Event generiert wird, welches wir dann an ein Filelog senden können
