### ISSUE TITLE
Protokoll für WOFI Deckenleuchte

### ISSUE THREAD

**Issue by djbone92** [RFD-FHEM/RFFHEM#143]
Signalduino mit RXB6 Empfänger 433Mhz
V 3.3.1-dev SIGNALduino - compiled at Jan 3 2017 23:59:32

Im EventMonitor mit verbous3:
Tastendruck ROT:
2017-03-12 20:08:29 SIGNALduino sduino433 UNKNOWNCODE iDDD503
2017.03.12 20:08:29 3 : sduino433: Unknown code iDDD503, help me!

Das Wäre die RAWMSG dazu:
MS;P0=748;P1=-257;P2=247;P3=-7746;P4=-755;D=23010124010101240101012401240124012424242424240101;CP=2;SP=3;O;

Hier mit verbous4:
2017.03.12 20:17:54 4 : sduino433/msg READ: MS;P0=-760;P1=747;P2=-259;P3=241;P4=-7741;D=34121230121212301212123012301230123030303030301212;CP=3;SP=4;O;
2017.03.12 20:17:54 4 : sduino433: Matched MS Protocol id 3 -> itv1
2017.03.12 20:17:54 4 : sduino433: Decoded MS Protocol id 3 dmsg iDDD503 length 24
2017.03.12 20:17:54 4 : sduino433 IT: message "iDDD503" (7)
2017.03.12 20:17:54 4 : sduino433 IT: msgcode "1F1F1FFF0001" (12) bin = 110111011101010100000011
2017.03.12 20:17:54 4 : sduino433 IT: message "iDDD503" (7)
2017.03.12 20:17:54 4 : sduino433 IT: msgcode "1F1F1FFF0001" (12) bin = 110111011101010100000011
2017-03-12 20:17:54 SIGNALduino sduino433 UNKNOWNCODE iDDD503
2017.03.12 20:17:54 3 : sduino433: Unknown code iDDD503, help me!
2017.03.12 20:17:54 4 : sduino433/msg READ: MS;P0=-747;P1=756;P2=-248;P3=253;P4=-7709;D=34121230121212301212123012301230123030303030301212;CP=3;SP=4;O;
2017.03.12 20:17:54 4 : sduino433: Matched MS Protocol id 3 -> itv1
2017.03.12 20:17:54 4 : sduino433: Decoded MS Protocol id 3 dmsg iDDD503 length 24
2017.03.12 20:17:54 4 : sduino433: Dropped (iDDD503) due to short time or equal msg
2017.03.12 20:17:54 4 : sduino433/msg READ: MS;P0=-746;P1=250;P2=754;P3=-252;P4=-7706;D=14232310232323102323231023102310231010101010102323;CP=1;SP=4;
2017.03.12 20:17:54 4 : sduino433: Matched MS Protocol id 3 -> itv1
2017.03.12 20:17:54 4 : sduino433: Decoded MS Protocol id 3 dmsg iDDD503 length 24
2017.03.12 20:17:54 4 : sduino433: Dropped (iDDD503) due to short time or equal msg

Die Fernbedienung hat insgesamt 6 Buttons...
Rot, Grün, Blau, LED, Lamp, ON/OFF;

Jemand eine Idee wie ich die Signale entweder über ntfy senden oder ein vielleicht sogar ein Modul für den Signalduino ?!?

mfg
bone

**Comment by sidey79** [comment]
@Ralf9   scheint wohl mal wieder ein PT2262 Modulation zu sein, die an das IT Modul geht

**Comment by Ralf9** [comment]
Ja, wird auch vom IT-Modul sauber verarbeitet
```
2017.03.12 21:51:22.233 4: sduinoD/msg get raw: MS;P0=-760;P1=747;P2=-259;P3=241;P4=-7741;D=34121230121212301212123012301230123030303030301212;CP=3;SP=4;O;
2017.03.12 21:51:22.233 4: sduinoD: Matched MS Protocol id 3 -> itv1
2017.03.12 21:51:22.233 5: sduinoD: Starting demodulation at Position 2
2017.03.12 21:51:22.233 4: sduinoD: Decoded MS Protocol id 3 dmsg iDDD503 length 24
2017.03.12 21:51:22.233 5: sduinoD: converted Data to (iDDD503)
2017.03.12 21:51:22.233 5: sduinoD: dispatch iDDD503
2017.03.12 21:51:22.248 4: sduinoD IT: message "iDDD503" (7)
2017.03.12 21:51:22.248 4: sduinoD IT: msgcode "1F1F1FFF0001" (12) bin = 110111011101010100000011
2017.03.12 21:51:22.248 5: sduinoD IT: V1 housecode = 1F1F1FFF00  onoffcode = 01
2017.03.12 21:51:22.248 4: sduinoD IT: 1F1F1FFF00 not defined (Switch code: 01)
```

**Comment by djbone92** [comment]
Danke Leute
hatte wohl gestern einen kleinen Aussetzer 👎 
Funktioniert
🥇
