### ISSUE TITLE
Hörmann Garagentorsender

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#149]
damit es nicht verloren geht
https://forum.fhem.de/index.php/topic,58397.msg605258.html#msg605258
und
https://forum.fhem.de/index.php/topic,71877.msg642879.html

**Comment by Ralf9** [comment]
@habeIchVergessen, @sidey79 könnt ihr euch dies bitte mal anschauen?
https://forum.fhem.de/index.php/topic,71877.msg642879.html

Kann ich @habeIchVergessen hier irgendwie zufügen?

**Comment by Ralf9** [comment]
hier ist eine weitere Info dazu:
https://forum.fhem.de/index.php/topic,63055.msg668023.html#msg668023

```
Ich denke im Moment es gibt mehrere Hörmann Systeme:

1) >20 Jahre alt, 433 MHz, orange Tasten FB, keine FHEM Unterstützung
2) >10 Jahre alt, 868 MHz, blaue Tasten FB, toggle geht zum öffnen/schliessen per CUL, aktuelle Tests mit Signalduino,
3) >4 Jahre alt, 868 MHz, blaue Tasten FB (gleich zu 2), wird gehört, aber toggle bewirkt nichts, aktuelle Tests mit Signalduino, zB. Supramatic
4) aktuell, 868 MHz, schwarze Tasten FB mit Encryption oder Signierung (zB. HSE 1 BiSecur), bisher keine Unterstützung in FHEM, zB. Supramatic BiSecur oder HET/S 2 BS
```

**Comment by Ralf9** [comment]
https://github.com/RFD-FHEM/RFFHEM/commit/1108d1dcf3c585913b7d78d46b694a4626d1eb9a

**Comment by Jarnsen** [comment]
Hallo Ralf9,

ich habe mal ein wenig geschaut. 


Tastenfarbe | Sendefrequenz
grün | 26,975 MHz
grau | 40,685 MHz
orange | 433,92 MHz
blau / schwarz / weiß | 868 MHz
Tasten in Gehäusefarbe | 433,92 MHz Rolling Code
Tasten in Gehäusefarbe | 868 MHz BiSecur

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
