### ISSUE TITLE
Came Toröffner

### ISSUE THREAD

**Issue by andreasloe** [RFD-FHEM/RFFHEM#151]
Lässt sich ein Toröffner von Came integrieren? Ich habe von einer Fernbedienung zwei Scans ("Links") und von einer weiteren einen Scan ("Rechts").

[Came.txt](https://github.com/RFD-FHEM/RFFHEM/files/921795/Came.txt)

**Comment by HomeAutoUser** [comment]
Guten Abend @andreasloe 

lange ist dein Post her.
Wir versuchen hier ein wenig "Ordnung zu schaffen" und möchten auch diesen Faden prüfen.

Deine damalige Meldung umfasst die Decodierung deines Toröffner mit dem SIGNALduino.
Wie ist der Stand aktuell? Wird dein Toröffner decodiert / verarbeitet?

Über eine Rückmeldung würden wir uns freuen.
MfG

**Comment by HomeAutoUser** [comment]
Mit würde deine Umsetzung mal interessieren. 

Hast du dir selbst etwas gebastelt? Wenn du von öffnen aus FHEM sprichst, so sendest du eine Signalfolge worauf er reagiert ?

Vielleicht findet sich ein Weg um diesen auch für andere User leichter zu implementieren.

Mfg

**Comment by andreasloe** [comment]
Das war eine sehr lange Geschichte. [Hier](https://forum.pilight.org/showthread.php?tid=2771) habe ich beschrieben, wie ich den Code ausgelesen habe. Das war deshalb nicht so einfach, weil ich am Anfang einen sehr schlechten Empfänger verwendet habe. Die Umsetzung habe ich dann nicht in pilight, sondern in FHEM gemacht, das ist [hier](https://forum.fhem.de/index.php?topic=63370.0) erläutert. Das Programmieren eines Zusatz-Moduls ist mir nicht gelungen, aber es geht mit Hardcodierung. Und [auf dieser Seite](https://forum.fhem.de/index.php?topic=78972.0) habe ich jemanden geholfen, seine Came einzubinden - keine Ahnung, ob das bei ihm läuft.

**Comment by andreasloe** [comment]
Ich nutze das auch zum Empfangen von Wetterstationen und Funksteckdosen sowie einer Garagentoröffnung. Ralf9 aus dem FHEM-Forum hat mich gerade nach den MU-Nachrichten von Came gefragt, da bleibe ich mal dran. Ich hatte damals solche Dinge, war aber mit dem Einbau in den Signalduino-Code überfordert - obwohl ich die Stelle gefunden hatte, in die das hinein muss.

**Comment by HomeAutoUser** [comment]
Entweder du postest hier oder im Forum die MU Nachrichten. Hier kann auch Ralf Mitlesen und das implementieren werden er und ich mal unter die Lupe nehmen.

Angepasst wäre, du machst erstmal ein Update der Firmware deines Signalduinos.

**Comment by Ralf9** [comment]
Die Firmware passt schon.
Wir können gerne auch hier weitermachen.
Ich habe mir die MU Nachrichten aus dem  FHEM-Forum angeschaut, sie sind ähnlich wie die ID 79 VTX-BELL der start ist aber anders:
```
MU;P0=711;P1=-15288;P4=132;P5=-712;P6=316;P7=-313;D=4565656705656567056567056165656567056565670565670561656565670565656705656705616565656705656567056567056165656567056565670565670561656565670565656705656705616565656705656567056567056165656567056565670565670561656565670565656705656705616565656705656567056;CP=6;R=52;
U86#112
MU;P0=-322;P1=136;P2=-15241;P3=288;P4=-735;P6=723;D=0123434343064343430643434306234343430643434306434343062343434306434343064343430623434343064343430643434306234343430643434306434343062343434306434343064343430623434343064343430643434306234343430643434306434343062343434306434343064343430;CP=3;R=27;
U86#111
MU;P0=-15281;P1=293;P2=-745;P3=-319;P4=703;P5=212;P6=152;P7=-428;D=01212121342121213421213421012121213421212134212134210121212134212121342121342101212121342121213421213421012121213421212134212134210121243134212121342121342101252526742121213425213421012121213421212134212134210121212134212;CP=1;R=23;
U86#112
```

```
	"86" => ## Came Toröffner
		{
			name		=> 'Came Drehtor Antrieb',
			#comment	=> '',
			id		=> '86',
			zero		=> [-2,1], 	#
			one		=> [-1,2],   	# 
			start  		=> [-46,1],	#
			clockabs     	=> 330,
			format 		=> 'twostate',	    # 
			preamble	=> 'U86#',	# prepend to converted message	
			#clientmodule    => 'SD_UT',   	# not used now
			#modulematch     => '^U86#.*', # not used now
			length_min      => '12',
			length_max      => '12',
		},
```

**Comment by HomeAutoUser** [comment]
Das sieht doch schonmal gut aus.
Wenn wir noch mehr MU Nachrichten erhalten würden, so würde ich die gern durch meine Scchleife schicken um zu sehen wie wir mit der Definition liegen.

Ich werde die Definition mal implementieren. Den Einbau in das SD_UT Modul wäre denkbar, da würden wir aber erstmal den Code um stellen wollen bevor wir weiter die Modelle erweitern.

**Comment by andreasloe** [comment]
Ich hatte ja damals den Rohcode versucht zu verstehen. Es gibt zwischen HIGH und LOW nur zwei denkbare Pausen, das sind 335 ms (im Folgenden 0) oder 665 ms (im Folgenden 1). Dann sieht ein pulse immer wie folgt aus. Er beginnt mit 0 und dann folgen entweder 01 oder 10. Zuletzt kommt der Footer mit einer Länge von 15018.

(Siehe auch [hier](https://forum.pilight.org/showthread.php?tid=2771&page=3), bzw mit pilight
`433gpio:  343 627 324 667 337 665 335 331 672 676 309 696 308 681 321 370 623 698 305 682 321 683 320 350 630 14894 -#: 26
433gpio:  333 685 317 663 338 668 335 328 676 673 312 695 308 678 325 355 654 682 306 696 307 677 326 339 641 15180 -#: 26
433gpio:  345 660 342 667 318 712 291 342 661 671 331 669 334 674 313 351 657 677 327 682 305 723 281 356 640 14872 -#: 26
433gpio:  354 656 345 666 319 680 326 360 642 667 334 681 322 669 317 371 638 673 330 675 313 697 305 356 640 15158 -#: 26
433gpio:  354 657 347 656 342 661 341 323 663 667 335 671 351 670 314 333 659 673 330 675 329 674 329 331 649 14870 -#: 26
`)

Kann ich da noch etwas helfen?

**Comment by HomeAutoUser** [comment]
@andreasloe 
kannst du mal bitte via dem SIGNALduino verbose 4 Nachrichten aufzeichnen? Somit sehen wir was er empfängt und wir dann auch richtig liegen mir den Zeiten. Am besten die Taste mehrfach hintereinander drücken am Sender.

in etwas sollte das dann so aussehen im Logfile
>MU;P0=711;P1=-15288;P4=132;P5=-712;P6=316;P7=-313;D=4565656705656567056567056165656567056565670565670561656565670565656705656705616565656705656567056567056165656567056565670565670561656565670565656705656705616565656705656567056567056165656567056565670565670561656565670565656705656705616565656705656567056;CP=6;R=52;

**Comment by Ralf9** [comment]
@andreasloe
Kannst Du ungefähr abschätzen wieviele Wiederholungen er pro Tastendruck sendet und ob diese von der Länge des Tastendrucks abhängen.
Sind es z.B. bei 0,5 oder 1 sec deutlich mehr Wiederholungen?

**Comment by andreasloe** [comment]
Ich habe fünf Mal gedrückt und dann das hier empfangen
`2018.10.24 18:52:30 4: sduino/msg READredu: MU;P0=-17364;P1=429;P2=-1020;P3=1432;P4=1052;P5=-28780;D=012121212121212321232323232321232123232;CP=1;R=225;w=0;
2018.10.24 18:52:30 4: sduino/msg READredu: MU;P0=-32001;P1=453;P2=-1006;P4=1431;P5=140;D=01212424242424212121212121212124242421242;CP=1;R=219;
2018.10.24 18:52:32 4: sduino/msg READredu: MU;P0=285;P1=-5472;P2=-27740;P3=-744;P4=-337;P5=713;P6=-15266;D=0102030303045303030453030304560303030453030304530303045603030304530303045303030456030303045303030453030304560303030453030304530303045603030304530303045303030456030303045303030453030304560303030453030304530303045603030304530303045303030450;CP=0;R=39;
2018.10.24 18:52:33 4: sduino/msg READredu: MU;P0=-32001;P1=287;P2=-739;P3=-338;P4=710;P5=-15264;D=0121212134212121342121213451212121342121213421212134512121213421212134212121345121212134212121342121213451212121342121213421212134512121213421212134212121345121212134212121342121213451212121342121213421212134512121213421212134212121345121212134212121342;CP=1;R=39;
2018.10.24 18:52:34 4: sduino/msg READredu: MU;P0=-309;P1=754;P2=-724;P3=306;P4=-15256;D=0123232301232323014323232301232323012323230143232323012323230123232301432323230123232301232323014323232301232323012323230143232323012323230123232301432323230123232301232323014323232301232323012323230143232323012323230123232301432323230123232301232323014;CP=3;R=40;
2018.10.24 18:52:34 4: sduino/msg READredu: MU;P0=-728;P1=304;P2=-310;P3=730;P4=-15256;P5=92;D=01010123010101230101012341010101230101012301010;CP=1;R=26;
2018.10.24 18:52:34 4: sduino/msg READredu: MU;P0=112;P1=-1957;P2=476;P3=-982;P4=-4040;P6=-276;P7=1000;D=012123232323232323232323232323212323212323212121212123232323232323232423232121232323232323232323232323232670;CP=2;R=221;
2018.10.24 18:52:35 4: sduino/msg READredu: MU;P0=-740;P1=196;P2=-325;P3=713;P4=-15283;P5=294;D=0123450505052305050523050505234505050523050505230505052345050505230505052305050523450505052305050523050505234505050523050505230505052345050505230505052305050523450505052305050523050505234505050523050505230505052345050505230505052305050523450505052305050;CP=5;R=35;
2018.10.24 18:52:35 4: sduino/msg READredu: MU;P0=-307;P1=730;P2=-729;P3=301;P4=-15266;P5=92;D=0123232301432323230123232301232323014323232301232323012;CP=3;R=25;
2018.10.24 18:52:35 4: sduino/msg READredu: MS;P1=-990;P2=477;P3=-3981;P4=366;P5=-1963;D=23412125252121212121212121212121212125212125212125252525252121212121212121;CP=2;SP=3;R=220;m=0;
2018.10.24 18:52:35 4: sduino/msg READredu: MS;P1=-990;P2=477;P3=-3981;P4=366;P5=-1963;D=23412125252121212121212121212121212125212125212125252525252121212121212121;CP=2;SP=3;R=220;m=1;
2018.10.24 18:52:36 4: sduino/msg READredu: MU;P0=-29840;P1=281;P3=-748;P4=-325;P5=712;P6=-15263;D=01013131314531313145313131456131313145313131453131314;CP=1;R=27;w=0;
2018.10.24 18:52:36 4: sduino/msg READredu: MU;P1=295;P3=-745;P4=-324;P5=708;P6=-15264;D=6131313145313131453131314561313131453131314531313145613131314531313145313131456131313145313131453131314561313131453131314531313145613131314531313145313131456131313145313131453131314561313131453131314531313145613131314531313145313131456131313145313131453;CP=1;R=27;
`
Als ich das mit pilight ausgewertet hatte, waren es fünf Sequenzen pro Tastendruck.

**Comment by HomeAutoUser** [comment]
@Ralf9 , bitte vorsichtig und zu voreilig mit einer neuen Definition. Die bisherigen Daten aus dem Ersten Post werden schon erkannt als U57.

```
[2018.10.24 18:58:14 3: Dispatch: #####################################################################
2018.10.24 18:58:14 3: Dispatch: ##### -->>> DISPATCH_TOOL is running (max dispatch=5) !!! <<<-- #####
2018.10.24 18:58:14 4: sduino_dummy/msg get raw: MC;LL=-708;LH=611;SL=-364;SH=296;D=55AAAC;C=329;L=22;R=26;
2018.10.24 18:58:14 4: sduino_dummy: Found manchester Protocol id 57 clock 329 RSSI -61 -> m-e
2018.10.24 18:58:15 4: SIGNALduino_unknown incomming msg: u57#AA5553
2018.10.24 18:58:15 4: SIGNALduino_unknown rawData: AA5553
2018.10.24 18:58:15 4: SIGNALduino_unknown Protocol: 57
2018.10.24 18:58:15 4: SIGNALduino_unknown converted to bits: 101010100101010101010011
2018.10.24 18:58:15 4: SIGNALduino_unknown sduino_dummy Protocol:57 | To help decode or debug, please add u57! (attr sduino_dummy development u40,m30,y73,y73.1,y74,m81,m83,u85,m72,u34,u41,u57)
2018.10.24 18:58:15 4: Unknown, please report
2018.10.24 18:58:15 4: SIGNALduino_unknown incomming msg: u57#AA5553
2018.10.24 18:58:15 4: SIGNALduino_unknown rawData: AA5553
2018.10.24 18:58:15 4: SIGNALduino_unknown Protocol: 57
2018.10.24 18:58:15 4: SIGNALduino_unknown converted to bits: 101010100101010101010011
2018.10.24 18:58:15 4: SIGNALduino_unknown sduino_dummy Protocol:57 | To help decode or debug, please add u57! (attr sduino_dummy development u40,m30,y73,y73.1,y74,m81,m83,u85,m72,u34,u41,u57)
2018.10.24 18:58:15 4: Unknown, please report
2018.10.24 18:58:15 3: sduino_dummy: Unknown code u57#AA5553, help me!
2018.10.24 18:58:15 4: sduino_dummy/msg get raw: MC;LL=-708;LH=601;SL=-376;SH=296;D=55AAAC;C=330;L=22;R=26;
2018.10.24 18:58:15 4: sduino_dummy: Found manchester Protocol id 57 clock 330 RSSI -61 -> m-e
2018.10.24 18:58:15 4: sduino_dummy Dispatch: u57#AA5553, Dropped due to short time or equal msg
2018.10.24 18:58:15 4: sduino_dummy/msg get raw: MC;LL=-708;LH=601;SL=-376;SH=296;D=55AAAC;C=330;L=22;R=26;
2018.10.24 18:58:15 4: sduino_dummy: Found manchester Protocol id 57 clock 330 RSSI -61 -> m-e
2018.10.24 18:58:15 4: sduino_dummy Dispatch: u57#AA5553, Dropped due to short time or equal msg
2018.10.24 18:58:15 4: sduino_dummy/msg get raw: MC;LL=-708;LH=601;SL=-376;SH=296;D=55AAAC;C=330;L=22;R=26;
2018.10.24 18:58:15 4: sduino_dummy: Found manchester Protocol id 57 clock 330 RSSI -61 -> m-e
2018.10.24 18:58:15 4: sduino_dummy Dispatch: u57#AA5553, Dropped due to short time or equal msg
2018.10.24 18:58:15 4: sduino_dummy/msg get raw: MC;LL=-708;LH=601;SL=-376;SH=296;D=55AAAC;C=330;L=22;R=26;
2018.10.24 18:58:15 4: sduino_dummy: Found manchester Protocol id 57 clock 330 RSSI -61 -> m-e
2018.10.24 18:58:15 4: sduino_dummy Dispatch: u57#AA5553, Dropped due to short time or equal msg
2018.10.24 18:58:15 3: Dispatch: ##### -->>> DISPATCH_TOOL is STOPPED !!! <<<-- #####
2018.10.24 18:58:15 3: Dispatch: ####################################################]
```

ES MUSS erst sicher gestellt werden wie die Nachrichten JETZT erkannt werden. MU oder MC.!
@andreasloe ist da von nöten.

**Comment by andreasloe** [comment]
Und wie kriege ich das raus?

**Comment by HomeAutoUser** [comment]
Erstmal bitte sicherstellen welche Version du soeben nutzt mit dem SIGNALduino.
Interessant ist was hier steht bei dir!

... so sollte das aussehen (angaben findest du auf dem Empfänger)
version | V 3.3.1-RC8 SIGNALduino cc1101  - compiled at Oct  4 2018 21:44:45
versionmodul | v3.3.3-dev_15.09.

**Comment by Ralf9** [comment]
Die Nachrichten aus dem Ersten Post sind wahrscheinlich nicht brauchbar, da er da noch eine ältere Firmware hatte, wo die Nachrichten fälschlicherweiser als MC erkannt wurde.
Dieser Erkennungsfehler ist in den aktuellen Firmwaren behoben.

**Comment by HomeAutoUser** [comment]
>In der Firmware die er verwendet ist dieser Fehler behoben.

Das mag sein, das sollten wir aber verifizieren und können uns nicht auf unsere Version verlassen.
Bisher haben wir mit der Definition von oben ca. 50 % Ausbeute. Da muss noch ein genauer Blick drauf geworfen werden. 12 Dispatched und 6 kamen an.

**Comment by HomeAutoUser** [comment]
@andreasloe 
bitte ersetze mal deine signalduino_protocols.hash mit der [signalduino_protocols.txt](https://github.com/RFD-FHEM/RFFHEM/files/2511682/signalduino_protocols.txt) (wurde umbenannt weil Github keine andere Endung zulässt)

1) Restart FHEM
2) Tastendruck
3) Blick ins Logfile ob u86 drin steht

**Comment by andreasloe** [comment]
ich habe

version
V 3.3.2-rc2 SIGNALduino cc1101 - compiled at Jun 1 2018 23:56:22
Soll ich da was ändern?

Am Mi., 24. Okt. 2018 um 19:14 Uhr schrieb HomeAutoUser <
notifications@github.com>:

**Comment by HomeAutoUser** [comment]
@andreasloe 

Wenn du einen Ardunino mit CC1101 besitzt bitte hiermit flashen.
> set sduino flash https://github.com/RFD-FHEM/SIGNALDuino/releases/download/3.3.1-RC8/SIGNALDuino_nanocc11013.3.1-RC8.hex

Erläuterung steht im Wiki ggf oder bitte fragen :-)

**Comment by andreasloe** [comment]
OK, zwei fragen: Alte version ist kein Problem (ich hatte mal eine Sache mit der falschen Somfy-Frequenz, die wurde nicht zurückgestellt) und wo finde ich signalduino_protocols.hash?

Und ja, es kann sein, dass es acht Wiederholungen sind - ganz einfach dann, wenn ich einen Tick zu lange drücke.

**Comment by HomeAutoUser** [comment]
>... und wo finde ich signalduino_protocols.hash?

befindet sich im FHEM / lib Verzeichnis

**Comment by andreasloe** [comment]
OK, jetzt habe ich 
`version | V 3.3.1-RC8 SIGNALduino cc1101 - compiled at Oct 4 2018 21:44:45`
und hash ersetzt. Nun nochmal drücken?

**Comment by HomeAutoUser** [comment]
erst das Modul bitte noch updaten, dann die HASH ersetzen. Danach ein FHEM restart.
Dann kanns losgehen.

**Comment by andreasloe** [comment]
Passt. Soll ich das besser im FHEM Forum einfügen, mit Codetags? 

https://forum.fhem.de/index.php/topic,63370.msg849474.html#msg849474

**Comment by HomeAutoUser** [comment]
Jetzt machst du mal 
>attr sduino development u86

danach wird ein Device angelegt.
Da kannst du nun Drücken und das sollte dir immer das Reading aktualisieren und registrieren im Logfile.

Da drückst du mal alle Tasten durch und schaust ob das Reading regelmäßig aktualisiert wird.

Kannst du mal ein Bild der Remote hier posten bitte.

**Comment by andreasloe** [comment]
Passt:

2018-10-24_20:19:13 SIGNALduino_unknown_86 bitMsg: 000100010010
2018-10-24_20:19:13 SIGNALduino_unknown_86 bitMsg_invert: 111011101101
2018-10-24_20:19:13 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:19:13 SIGNALduino_unknown_86 hexMsg: 112
2018-10-24_20:19:13 SIGNALduino_unknown_86 hexMsg_invert: EED
2018-10-24_20:19:13 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:19:13 SIGNALduino_unknown_86 lastInputDev: sduino
2018-10-24_20:19:30 SIGNALduino_unknown_86 bitMsg: 000100010001
2018-10-24_20:19:30 SIGNALduino_unknown_86 bitMsg_invert: 111011101110
2018-10-24_20:19:30 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:19:30 SIGNALduino_unknown_86 hexMsg: 111
2018-10-24_20:19:30 SIGNALduino_unknown_86 hexMsg_invert: EEE
2018-10-24_20:19:30 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:19:30 SIGNALduino_unknown_86 lastInputDev: sduino
2018-10-24_20:19:39 SIGNALduino_unknown_86 bitMsg: 000100010010
2018-10-24_20:19:39 SIGNALduino_unknown_86 bitMsg_invert: 111011101101
2018-10-24_20:19:39 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:19:39 SIGNALduino_unknown_86 hexMsg: 112
2018-10-24_20:19:39 SIGNALduino_unknown_86 hexMsg_invert: EED
2018-10-24_20:19:39 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:19:39 SIGNALduino_unknown_86 lastInputDev: sduino
2018-10-24_20:19:41 SIGNALduino_unknown_86 bitMsg: 000100010001
2018-10-24_20:19:41 SIGNALduino_unknown_86 bitMsg_invert: 111011101110
2018-10-24_20:19:41 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:19:41 SIGNALduino_unknown_86 hexMsg: 111
2018-10-24_20:19:41 SIGNALduino_unknown_86 hexMsg_invert: EEE
2018-10-24_20:19:41 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:19:41 SIGNALduino_unknown_86 lastInputDev: sduino

Ich habe nur einen Clone hier, aber das Ding sieht so aus:
![fernbedienung](https://user-images.githubusercontent.com/10688946/47452346-5426e180-d7ca-11e8-8e5a-746b33092b8b.png)

**Comment by HomeAutoUser** [comment]
Sieht gut aus!
Nun bitte das selbe nochmal indem du vor dem Tastendruck auf das Device gehst (...86) und
>set UserMsg anklickst

Und dahinter die Taste schreibst welche du drückst, dann Taste drücken .... und das selbe mit allen Tasten bitte.

Frage, kannst du den Code / Hauscode der Fernbedienung einstellen an der Fernbedienung?

**Comment by andreasloe** [comment]
Code kann ich nicht einstellen, der ist fix in der Fernbedienung (jede hat zwei Tasten).

Der Befehl muss irgendwie anders lauten. Ich habe nur set SIGNALduino_unknown_86 UserInfo und brauche da aber noch eine Zahl.

**Comment by andreasloe** [comment]
Kapiert, so etwa:

2018-10-24_20:51:44 SIGNALduino_unknown_86 UserMSG: rechteTaste
2018-10-24_20:52:12 SIGNALduino_unknown_86 bitMsg: 000100010010
2018-10-24_20:52:12 SIGNALduino_unknown_86 bitMsg_invert: 111011101101
2018-10-24_20:52:12 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:52:12 SIGNALduino_unknown_86 hexMsg: 112
2018-10-24_20:52:12 SIGNALduino_unknown_86 hexMsg_invert: EED
2018-10-24_20:52:12 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:52:12 SIGNALduino_unknown_86 lastInputDev: sduino

**Comment by andreasloe** [comment]
und die linke noch

2018-10-24_20:52:55 SIGNALduino_unknown_86 UserMSG: linkeTaste
2018-10-24_20:52:57 SIGNALduino_unknown_86 bitMsg: 000100010001
2018-10-24_20:52:57 SIGNALduino_unknown_86 bitMsg_invert: 111011101110
2018-10-24_20:52:57 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:52:57 SIGNALduino_unknown_86 hexMsg: 111
2018-10-24_20:52:57 SIGNALduino_unknown_86 hexMsg_invert: EEE
2018-10-24_20:52:57 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:52:57 SIGNALduino_unknown_86 lastInputDev: sduino
2018-10-24_20:52:58 SIGNALduino_unknown_86 bitMsg: 000100010001
2018-10-24_20:52:58 SIGNALduino_unknown_86 bitMsg_invert: 111011101110
2018-10-24_20:52:58 SIGNALduino_unknown_86 bitCount: 12
2018-10-24_20:52:58 SIGNALduino_unknown_86 hexMsg: 111
2018-10-24_20:52:58 SIGNALduino_unknown_86 hexMsg_invert: EEE
2018-10-24_20:52:58 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-24_20:52:58 SIGNALduino_unknown_86 lastInputDev: sduino

**Comment by andreasloe** [comment]
Und das wusste ich noch aus dem pilight-Test: Die letzten beiden HIGH-LOW sind bei den Tasten vertauscht, das sieht man auch deutlich. Einmal steht hinten 01 und einmal 10. Der Rest sollte gleich sein.

**Comment by HomeAutoUser** [comment]
Danke für die Info :-)

Hast du mal geschaut ob es regelmäßig empfängt?
Kannst du irgendwas noch einstellen an der FB oder dem Tor?

Wie bindet die remote sich an daas Tor? von den 12bits haben wir 2....

**Comment by andreasloe** [comment]
Ja, der empfängt regelmäßig. Ich muss jetzt mal die andere Fernbedienung heraussuchen, ich finde die gerade nicht (und dann müssen noch die Kids ins Bett...), außerdem gibt es eine graue FB, die hat eine etwas andere Folge von H und L, die werde ich auch mal heraussuchen. Ansonsten kann man da nichts einstellen. Man kauft eine FB, lernt die am Tor an (drückt einen Knopf am Tor und dann die FB und dann ist sie "registriert") und das war es. 

Bei dem pilight-Ding habe ich herausgefunden, dass es zwölf Bits sind und die entweder HL oder LH Folgen darstellen, wobei H und L jeweils 335 oder 655 microSekunden sind.  Ihr habt doch den Code obe, oder was ist 000100010010? Das sind doch die zwölf Bits, oder?

**Comment by andreasloe** [comment]
PS Danke!!

**Comment by HomeAutoUser** [comment]
Das mit der anderen FB wäre sehr gut!
Wenn du weißt, das die andere FB ggf. anders sendet, dann BITTE versuche mal der jetzigen remote die Modelbezeichnung zu entnehmen für die Dokumentation.

**Comment by elektron-bbs** [comment]
Da du von zwei Tasten an der Fernbedienung schreibst, handelt es sich wahrscheinlich um das Model "Top TOP-432EV 433,92 MHz"?

**Comment by andreasloe** [comment]
korrekt, das ist sie. Hier noch eine weitere Erfassung mit einem anderen Sender

S018-10-25_17:41:41 SIGNALduino_unknown_86 bitMsg_invert: 111101111101
2018-10-25_17:41:41 SIGNALduino_unknown_86 bitCount: 12
2018-10-25_17:41:41 SIGNALduino_unknown_86 hexMsg: 082
2018-10-25_17:41:41 SIGNALduino_unknown_86 hexMsg_invert: F7D
2018-10-25_17:41:41 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-25_17:41:41 SIGNALduino_unknown_86 lastInputDev: sduino
2018-10-25_17:42:37 SIGNALduino_unknown_86 bitMsg: 000010000010
2018-10-25_17:42:37 SIGNALduino_unknown_86 bitMsg_invert: 111101111101
2018-10-25_17:42:37 SIGNALduino_unknown_86 bitCount: 12
2018-10-25_17:42:37 SIGNALduino_unknown_86 hexMsg: 082
2018-10-25_17:42:37 SIGNALduino_unknown_86 hexMsg_invert: F7D
2018-10-25_17:42:37 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-25_17:42:37 SIGNALduino_unknown_86 lastInputDev: sduino
2018-10-25_17:43:03 SIGNALduino_unknown_86 bitMsg: 000010000010
2018-10-25_17:43:03 SIGNALduino_unknown_86 bitMsg_invert: 111101111101
2018-10-25_17:43:03 SIGNALduino_unknown_86 bitCount: 12
2018-10-25_17:43:03 SIGNALduino_unknown_86 hexMsg: 082
2018-10-25_17:43:03 SIGNALduino_unknown_86 hexMsg_invert: F7D
2018-10-25_17:43:03 SIGNALduino_unknown_86 hexCount_or_nibble: 3
2018-10-25_17:43:03 SIGNALduino_unknown_86 lastInputDev: sduino

**Comment by HomeAutoUser** [comment]
@elektron-bbs
wollen wir den Typ „Top TOP-432EV“ in das Modul SD_UT aufnehmen?

Hast du bezüglich der HexDaten schon eine Zusammenfassung?

**Comment by HomeAutoUser** [comment]
Du kannst jederzeit gern auf das neuere updaten. So bekommen wir heraus ob da noch Fehler sind bzw vielleicht noch eine Anpassung vorgenommen werden muss.

Wie äußert sich dein Fehler oder von was „sprichst du wenn du von Fehler schreibst“?

**Comment by andreasloe** [comment]
Es gab (nach somfy Bedienung) eine Frequenzumschaltung auf 93MHz, die in der neuen Versuon behoben ist.

**Comment by elektron-bbs** [comment]
Meinst du jetzt die Firmware des SIGNALduino oder das FHEM-Modul?
Aktuelle Entwicklerversionen wären z.Z.:

version V 3.3.1-RC8_2018-10-04_UB_DN022 SIGNALduino cc1101 (433Mhz) - compiled at Oct 15 2018 21:09:59
versionmodul v3.3.3-dev_15.09.

Die obere Zeile (Firmware) weicht bei mir ab, da ich selbst kompiliert habe.

**Comment by andreasloe** [comment]
Das war in der Firmware (Ralf9 hat das gesagt). Jedenfalls habe ich jetzt 
`V 3.3.2-rc2 SIGNALduino cc1101 - compiled at Jun 1 2018 23:56:2`
und damit sei das Problem behoben, sagte er.

**Comment by HomeAutoUser** [comment]
Ich glaube es gibt hier wieder einen Widerspruch.
Es gibt keine V 3.3.2-rc2.
[Hier ist ](https://github.com/RFD-FHEM/SIGNALDuino/releases) die aktuelle Version.

BITTE AUFPASSEN!!!! Woher hast du die Version? Hat die Ralf bereitgestellt? Ralf seine FW wird teilweise von Ihm erweitert was hier in der Version nicht so umgestezt wird oder später. Hier in dem Faden wird bezugnehmend auf RFD-FHEM/SIGNALDuino von @sidey79 diskutiert und erweitert. Du kannst die Version gern testen und sollte dort der Fehler vorhanden sein, so gib bescheid. Dann müsste der Fehler auch in der Version korrigiert werden.

**Comment by andreasloe** [comment]
Uups. Ich habe die Version aus diesem Post, von heute vormittag
[https://forum.fhem.de/index.php/topic,63370.msg852050.html#msg852050](url)
Soll ich eine andere nehmen?

Der Fehler ist hier dokumentiert, https://forum.fhem.de/index.php/topic,82379.msg805840.html#msg805840

**Comment by HomeAutoUser** [comment]
Wenn ich das richtig sehe im Faden, so ist das Ralf seine Version. Bitte teste es mit [den Versionen](https://github.com/RFD-FHEM/SIGNALDuino/releases) von hier. Dann können wir auch eine Aussage dazu teffen. Zu deiner Version kann nur @Ralf9 eine Aussage treffen.

**Comment by andreasloe** [comment]
OK.

**Comment by HomeAutoUser** [comment]
Guten Abend @andreasloe,
deine Remote wurde in das Modul eingearbeitet.

Bitte mache eine update
> update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt

starte FHEM neu und trage bei development im Empfänger m86 ein.
Ab sofort solltest du bei einem Tastendruck deiner remote ein Device angelegt bekommen.

Das senden via Set kannst du gern mal testen aber das ist noch nicht verbindlich, weil wir da die Wiederholungen ggf anpassen müssen.

**Comment by HomeAutoUser** [comment]
Hallo, hast du mal ein Update gemacht und das Modul bzw. neu angelegte Device getestet?
MfG

**Comment by andreasloe** [comment]
Oh ja, das läuft schon eine ganze Weile. Allerdings habe ich nur zwei Fernbedienungen, mit denen ich das getestet habe. Wir können vermutlich die Frage hier schließen und wenn jemand damit ein Problem hat, dann kann das ja als "bug" o.Ä. weiterbehandelt werden.
