### ISSUE TITLE
Warema MU ?

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#153]
Nach einem Update am 16.04.2017 wird mir hier das Log zugepflastert mit solchen Einträgen:
2017.04.17 13:40:52 3: sduino: Unknown code u63000000000, help me!
2017.04.17 13:40:54 3: sduino: Unknown code u63A92AAAA4A48424850, help me!
2017.04.17 13:41:01 3: sduino: Unknown code u6300000000, help me!
2017.04.17 13:41:39 3: sduino: Unknown code u6300000000, help me!
2017.04.17 13:41:43 3: sduino: Unknown code u63000000000, help me!
2017.04.17 13:41:44 3: sduino: Unknown code u630000000, help me!
2017.04.17 13:41:45 3: sduino: Unknown code u63000000000, help me!
2017.04.17 13:41:53 3: sduino: Unknown code u63A92AAAA4A482A92128, help me!
2017.04.17 13:41:53 3: sduino: Unknown code u6362AAA92920AA484A, help me!
2017.04.17 13:42:17 3: sduino: Unknown code u6300000000, help me!
2017.04.17 13:42:50 3: sduino: Unknown code u63A92AAAA4A455524540, help me!
2017.04.17 13:42:55 3: sduino: Unknown code u6300000000, help me!
2017.04.17 13:42:56 3: sduino: Unknown code u630000000000000000, help me!
2017.04.17 13:43:02 3: sduino: Unknown code u630000000, help me!
2017.04.17 13:43:26 3: sduino: Unknown code u63000000000, help me!
2017.04.17 13:43:37 3: sduino: Unknown code u630000000000000, help me!
2017.04.17 13:43:47 3: sduino: Unknown code u63A92AAAA4A455524540, help me!
2017.04.17 13:43:47 3: sduino: Unknown code u63AAAA4A455524540, help me!
2017.04.17 13:44:11 3: sduino: Unknown code u6300000000, help me!

u40 ist noch so ein Kandidat der relativ häufig auftaucht:
2017.04.17 00:00:01 3: sduino: Unknown code u40#FE50BDEF7AC6, help me!
2017.04.17 00:03:00 3: sduino: Unknown code u40#FE71BD672A52D38, help me!
2017.04.17 00:03:57 3: sduino: Unknown code u40#FB42639DA569DEE4382, help me!
2017.04.17 00:06:25 3: sduino: Unknown code u40#FE55B4EF7AC6, help me!
2017.04.17 00:09:09 3: sduino: Unknown code u40#FE72B8A719DA800, help me!
2017.04.17 00:10:34 3: sduino: Unknown code u40#FE95806F7B82, help me!
2017.04.17 00:15:21 3: sduino: Unknown code u40#FE738C2F7BDED28, help me!

**Comment by sidey79** [comment]
Ja, ich versuche mit Protokoll 63 ein etwas besondere Signalfolge zu demodulieren.
Das klappt leider bei sehr vielen Protokollen. Ich werde mir da noch etwas überlegen, wenn ich schlauer bin.
Protokoll 63 sollte erst mal nicht in die whitelistID aufgenommen werden, außer man will mit entwickeln

**Comment by HomeAutoUser** [comment]
Ich habe auch u63 und u40 Kanidaten.

Kann man Dir @sidey79 irgendwelche Zuarbeiten vornehmen oder Logauszüge zukommen lassen um behilflich dabei zu sein ?

> 2017.04.27 00:00:03 4: sduino_radino: decoded matched MU Protocol id 63 dmsg u637FFFFFFE length 32 RSSI = -47.5
2017.04.27 18:01:41 4: sduino_radino: decoded matched MU Protocol id 63 dmsg u6380000000000000 length 56 RSSI = -58
2017.04.27 00:00:25 4: sduino_radino: decoded matched MU Protocol id 63 dmsg u635FEFFDD55 length 36 RSSI = -91
2017.04.27 00:00:25 4: sduino_radino: decoded matched MU Protocol id 63 dmsg u63FBFF75557DB7FBFF755 length 76 RSSI = -92

Hier mal Auszüge von verschiedenen Längen.

**Comment by sidey79** [comment]
Aktuell nicht. Ich weiss prinzipiell warum das Protokoll #63 so oft passt. Am besten nimmst Du es nicht in die Whitelist auf.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
