### ISSUE TITLE
Absturz FHEM bei "reload 00_SIGNALduino.pm"

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#154]
Das passiert neuerdings des Öfteren bei Ausführung des Befehls "reload 00_SIGNALduino.pm":

2017.04.25 21:19:12 1: PERL WARNING: Use of uninitialized value $clockabs in division (/) at ./FHEM/00_SIGNALduino.pm line 2983.
Illegal division by zero at ./FHEM/00_SIGNALduino.pm line 2983.

2017.04.27 10:27:34 1: PERL WARNING: Use of uninitialized value $clockabs in division (/) at ./FHEM/00_SIGNALduino.pm line 2987.
Illegal division by zero at ./FHEM/00_SIGNALduino.pm line 2987.

2017.04.27 10:39:35 1: PERL WARNING: Use of uninitialized value $clockabs in division (/) at ./FHEM/00_SIGNALduino.pm line 2987.
Illegal division by zero at ./FHEM/00_SIGNALduino.pm line 2987.

Ich habe das erst mal für mich gefixt, indem ich folgende Zeilen geändert habe:

Zeile 2951:
	my $clockabs = 1;  #Clock will be fetched from Protocol
Zeile 2967:
	$clockabs= $ProtocolListSIGNALduino{$id}{clockabs};

**Comment by elektron-bbs** [comment]
Es wäre schön, wenn solche Fehler zeitnah korrigiert würden :-(
Oder spricht irgend etwas dagegen, eine Division durch 0 zu verhindern?

Die Zeilennummern stimmen natürlich jetzt nicht mehr. Hier noch einmal die beiden Änderungen in der "sub SIGNALduino_Parse_MU($$$$@)":

#my $clockabs;  #Clock will be fetched from Protocol
in:
my $clockabs = 1;  #Clock will be fetched from Protocol   

my $clockabs= $ProtocolListSIGNALduino{$id}{clockabs};
in:
$clockabs= $ProtocolListSIGNALduino{$id}{clockabs};

**Comment by sidey79** [comment]
Ah sorry,

ich hatte die letzten Wochen nicht so viel Zeit.
Da ist es mir nicht aufgefallen, dass Du hier einen Fehler inkl. Behebung bekanntgegeben hast.

**Comment by sidey79** [comment]
Passiert das seit dem Fix vom 10. Juni noch?

**Comment by HomeAutoUser** [comment]
@elektron-bbs,
bekommst du zusammen wann der Fehler auftritt? Einmal hatten wir ja den Fall vor kurzen.

**Comment by elektron-bbs** [comment]
Ja, freilich, da der Fehler trotz des Fixes jetzt doch wieder auftritt. Der Absturz von FHEM passiert eigentlich fast immer, nachdem FHEM neu gestartet wurde und anschließend irgendwann ein "reload 00_SIGNALduino.pm" ausgeführt wird. Wenn es einmal funktioniert hat, dann kann man auch weiterhin das reload anwenden. Meistens passiert mir das nach einem Update wenn ich anschließend noch die Definitionen wie u40, u63 usw. auskommentiere, da sie mir zu viele sinnlose Einträge im Log hinterlassen.

**Comment by sidey79** [comment]
Könnt ihr das noch mal mit einem stacktrace mitloggen?

**Comment by elektron-bbs** [comment]
Eben zweimal probiert:
1. shutdown restart
2. ein Protokoll in 00_SIGNALduino.pm auskommentieren
3. reload 00_SIGNALduino.pm

2017.10.01 13:38:31 1: PERL WARNING: Subroutine SIGNALduino_filterSign redefined at ./FHEM/00_SIGNALduino.pm line 4721.
2017.10.01 13:38:31 1: PERL WARNING: Subroutine SIGNALduino_compPattern redefined at ./FHEM/00_SIGNALduino.pm line 4793.
2017.10.01 13:38:41 1: PERL WARNING: Use of uninitialized value $clockabs in division (/) at ./FHEM/00_SIGNALduino.pm line 3253.
2017.10.01 13:38:41 1: stacktrace:
2017.10.01 13:38:41 1:     main::__ANON__                      called by ./FHEM/00_SIGNALduino.pm (3253)
2017.10.01 13:38:41 1:     main::SIGNALduino_Parse_MU          called by ./FHEM/00_SIGNALduino.pm (3601)
2017.10.01 13:38:41 1:     main::SIGNALduino_Parse             called by ./FHEM/00_SIGNALduino.pm (2539)
2017.10.01 13:38:41 1:     main::SIGNALduino_Read              called by fhem.pl (3448)
2017.10.01 13:38:41 1:     main::CallFn                        called by fhem.pl (692)
Illegal division by zero at ./FHEM/00_SIGNALduino.pm line 3253.

2017.10.01 13:41:32 1: PERL WARNING: Subroutine SIGNALduino_filterSign redefined at ./FHEM/00_SIGNALduino.pm line 4721.
2017.10.01 13:41:32 1: PERL WARNING: Subroutine SIGNALduino_compPattern redefined at ./FHEM/00_SIGNALduino.pm line 4793.
2017.10.01 13:41:32 1: PERL WARNING: Use of uninitialized value $clockabs in division (/) at ./FHEM/00_SIGNALduino.pm line 3253.
2017.10.01 13:41:32 1: stacktrace:
2017.10.01 13:41:32 1:     main::__ANON__                      called by ./FHEM/00_SIGNALduino.pm (3253)
2017.10.01 13:41:32 1:     main::SIGNALduino_Parse_MU          called by ./FHEM/00_SIGNALduino.pm (3601)
2017.10.01 13:41:32 1:     main::SIGNALduino_Parse             called by ./FHEM/00_SIGNALduino.pm (2539)
2017.10.01 13:41:32 1:     main::SIGNALduino_Read              called by fhem.pl (3448)
2017.10.01 13:41:32 1:     main::CallFn                        called by fhem.pl (692)
Illegal division by zero at ./FHEM/00_SIGNALduino.pm line 3253.

Dieses tritt auch nach einem Neustart regelmäßig auf, führt aber nicht zum Absturz:

2017.10.01 13:36:12 1: PERL WARNING: Use of uninitialized value $returnvalues[0] in join or string at ./FHEM/00_SIGNALduino.pm line 3847.
2017.10.01 13:36:12 1: stacktrace:
2017.10.01 13:36:12 1:     main::__ANON__                      called by ./FHEM/00_SIGNALduino.pm (3847)
2017.10.01 13:36:12 1:     main::SIGNALduino_callsub           called by ./FHEM/00_SIGNALduino.pm (3387)
2017.10.01 13:36:12 1:     main::SIGNALduino_Parse_MU          called by ./FHEM/00_SIGNALduino.pm (3601)
2017.10.01 13:36:12 1:     main::SIGNALduino_Parse             called by ./FHEM/00_SIGNALduino.pm (2539)
2017.10.01 13:36:12 1:     main::SIGNALduino_Read              called by fhem.pl (3448)
2017.10.01 13:36:12 1:     main::CallFn                        called by fhem.pl (692)

**Comment by sidey79** [comment]
Ich bin nicht sicher, ob das witklich ein Bug ist.

Kannst Du mir sagen, auf welche Revision sich die Zeilennummer beziehen und was genau Du auskommentiert hast.

Was ich überlegt habe ist, dass wenn man die protokoll Definition verändert und dann ein reload macht, wird die Funktion SIGNALduino_IdList nicht erneut aufgerufen. Das passiert nur, wenn das whitelist Attribut geändert wird oder wenn define aufgerufen wird. 

Definiert mal etwas falsches im Protokoll, könnte es zu diesem Fehler kommen.

**Comment by elektron-bbs** [comment]
OK, war ungünstig, das mit meiner Entwicklerversion zu testen. Die Zeilennummern passen da natürlich nicht. Die Fehlermeldung mit Zeilennummer 3253 bezog sich auf diese Zeile:

%patternList = map { $_ => round($patternListRaw{$_}/$clockabs,1) } keys %patternListRaw; 

Ich wollte es eben noch mal mit der aktuellen Version (Update FHEM und RFFHEM vor ca. 1 h) probieren, diese verabschiedet sich allerdings sofort mit folgender letzter Zeile im Log:

Can't use an undefined value as an ARRAY reference at ./FHEM/00_SIGNALduino.pm line 3667.

Ich habe es 3 mal probiert, mit gleichem Ergebnis. Dann habe ich meine vorhergehende 00_SIGNALduino.pm wieder eingespielt.

**Comment by sidey79** [comment]
Ich denke der Fehler von gestern ist behoben (Zeile 3667).

Deinen Fehler kann ich so noch nicht finden.
Kannst Du noch mal prüfen, ob dieser Fehler in der git Version von Heute auftritt?

**Comment by elektron-bbs** [comment]
@sidey79 wrote:

> Was ich überlegt habe ist, dass wenn man die protokoll Definition verändert und dann ein reload macht, wird die Funktion SIGNALduino_IdList nicht erneut aufgerufen. Das passiert nur, wenn das whitelist Attribut geändert wird oder wenn define aufgerufen wird.

Ich schätze, du hast Recht. Seit der Einführung der Blacklist ist der Absturz beim Reload bei mir nicht wieder aufgetreten. Vorher hatte ich immer die entsprechenden Definitionen auskommentiert und ein Reload getätigt. Dank Blacklist muss ich das jetzt nicht mehr.

Ich denke, das hat sich erledigt und schließe das Thema.
