### ISSUE TITLE
Protokoll für Nobily Funk Rollladen

### ISSUE THREAD

**Issue by N3M3SIS81** [RFD-FHEM/RFFHEM#157]
Hi leider bekomme ich meine Rollladen nicht geschaltet.
Benützt wird die Hardware SIGNALduino cc1101 mit der Version V 3.3.1-dev

Hab jetzt ein paar logs mitgeschnitten und lege die Logs per Anhang bei.

Hoffe das wir das gebacken bekommen :)
Sollte was fehlen oder Ihr benötigt noch mehr sachen einfach bescheid geben.

https://www.file-upload.net/download-12485667/HandsenderNobily.zip.html

Lg

**Comment by HomeAutoUser** [comment]
Hallo @N3M3SIS81,

funktionieren deine Rollladen nun via SIGNALduino?
[HIER](https://forum.fhem.de/index.php/topic,43548.msg354848.html#msg354848) wurde das ganze schonmal behandelt. Vermutlich P16.

Sollte es nun funktionieren, wärest du bitte so nett und würdest diesen Faden bitte schließen?

MfG

**Comment by N3M3SIS81** [comment]
Hi,

nein leider noch nicht.
Es sind andere Motoren wie in dem vorhanden thread im Forum.
Für jede Hilfe dankbar.
Lg

**Comment by Jarnsen** [comment]
Welche Motoren hast du???

Von meinem iPhone gesendet

**Comment by HomeAutoUser** [comment]
Guten Abend @N3M3SIS81 ,

lange ist dein Post her.
Wir versuchen hier ein wenig "Ordnung zu schaffen" und möchten auch diesen Faden prüfen.

Deine damalige Meldung umfasst die Decodierung deines Rollladen mit dem SIGNALduino.
Wie ist der Stand aktuell? Wird dein Rollladen decodiert / verarbeitet?

Über eine Rückmeldung würden wir uns freuen.
MfG

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
