### ISSUE TITLE
SIGNALduino_SendFromQueue problem

### ISSUE THREAD

**Issue by andreasloe** [RFD-FHEM/RFFHEM#158]
It seems there is a problem with the above function, in particular
`Write the next buffer not earlier than 0.23 seconds`
rudolfkoenig says this is a mistake within SIGNALduino, see https://forum.fhem.de/index.php/topic,71592.0.html
I need at least 0.6 seconds so that every shutter closes with one command. Even with 0.4 seconds the second shutter does not move.

**Comment by sidey79** [comment]
Bitte mit der aktuellen dev-r33 Version noch mal verifizieren ob das Problem noch besteht.
