### ISSUE TITLE
Neues Protokoll WS7035

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#160]
Ich habe ein neues Protokoll eines Temperatursensors für den Signalduino eingebaut. Es handelt sich dabei um ein älteres Modell einer Temperaturanzeige mit Funksensor. Beschriftet sind die Teile mit "Remote Temp Transmitter & Remote Thermo Model 7035". Das Protokoll ist ähnlich dem "Lacrosse TX2/TX3" und wird deshalb auch von dem Modul "14_CUL_TX" weiter verarbeitet. Die Verarbeitung läuft bei mir seit etwa einer Woche fehlerfrei und könnte so übernommen werden:

   "66" => ## TX2 Protocol (Remote Temp Transmitter & Remote Thermo Model 7035)
            # MU;P0=13312;P1=-2785;P2=4985;P3=1124;P4=-6442;P5=3181;P6=-31980;D=0121345434545454545434545454543454545434343454543434545434545454545454343434545434343434545621213454345454545454345454545434545454343434545434345454345454545454543434345454343434345456212134543454545454543454545454345454543434345454343454543454545454545;CP=3;R=73;O;
            # MU;P0=32001;P1=-2783;P2=4976;P3=1129;P4=-6455;P5=3181;P6=-31980;D=0121345434545454545434545454543454545434343454543434545434545454545454343434545434343434545621213454345454545454345454545434545454343434545434345454345454545454543434345454343434345456212134543454545454543454545454345454543434345454343454543454545454545;CP=3;R=73;O;
            # MU;P0=10080;P1=-2787;P2=4981;P3=1136;P4=-6447;P5=3177;P6=-31972;D=0121345434545454545434545454543454545434343454543434545434545454545454343434545434343434545621213454345454545454345454545434545454343434545434345454345454545454543434345454343434345456212134543454545454543454545454345454543434345454343454543454545454545;CP=3;R=73;O;
      {
         name           => 'WS7035',	
         id             => '66',
         zero           => [8,-16],
         one            => [3,-16],
         clockabs       => 400,
         preamble	      => 'TX',	      # prepend to converted message
         clientmodule   => 'CUL_TX',
         modulematch    => '^TX......',
         length_min     => '43',
         length_max     => '44',
         remove_zero    => 1,	         # Removes leading zeros from output
         postDemodulation => \&SIGNALduino_postDemo_WS7035,
      }, 	

sub SIGNALduino_postDemo_WS7035($@) {
	my ($name, @bit_msg) = @_;
	my $msg = join("",@bit_msg);
	my $parity = 0;									# Parity even

	if (substr($msg,0,8) ne "10100000") {		# check ident
		Log3 $name, 3, "$name: WS7035 ERROR - Ident not 1010 0000";
		return 0, undef;
	} else {
		for(my $i = 15; $i < 28; $i++) {			# Parity over bit 15 and 12 bit temperature
	      $parity += substr($msg, $i, 1);
		}
		if ($parity % 2 != 0) {
			Log3 $name, 3, "$name: WS7035 ERROR - Parity not even";
			return 0, undef;
		} else {
			Log3 $name, 4, "$name: WS7035 $msg";
			Log3 $name, 5, "$name: WS7035 before: " . substr($msg,0,4) ." ". substr($msg,4,4) ." ". substr($msg,8,4) ." ". substr($msg,12,4) ." ". substr($msg,16,4) ." ". substr($msg,20,4) ." ". substr($msg,24,4) ." ". substr($msg,28,4) ." ". substr($msg,32,4) ." ". substr($msg,36,4) ." ". substr($msg,40,4);
			substr($msg, 27, 4, '');				# delete nibble 8
			Log3 $name, 5, "$name: WS7035 after:  " . substr($msg,0,4) ." ". substr($msg,4,4) ." ". substr($msg,8,4) ." ". substr($msg,12,4) ." ". substr($msg,16,4) ." ". substr($msg,20,4) ." ". substr($msg,24,4) ." ". substr($msg,28,4) ." ". substr($msg,32,4) ." ". substr($msg,36,4);
			return (1,split("",$msg));
		}
	}
}

**Comment by Ralf9** [comment]
MU;P0=10080;P1=-2787;P2=4981;P3=1136;P4=-6447;P5=3177;P6=-31972;D=**0121**34543454545454543454545454345454543434345454343454543454545454545434343454543434343454562121345434545454545434545454543454545434343454543434545434545454545454343434545434343434545**62121**34543454545454543454545454345454543434345454343454543454545454545;CP=3;R=73;O;

Es fehlt noch der start. Du kannst es mal mit 121 versuchen
start => [-7,12,-7],

**Comment by elektron-bbs** [comment]
Ja, danke, das funktioniert auch.
Hat eigentlich der Parameter "format" irgendeine Bedeutung?  Wenn ja, welche?

**Comment by Ralf9** [comment]
ich habe es commitet

Momentan wird format nur zur Erkennung von manchester verwendet

**Comment by elektron-bbs** [comment]
Ich habe diesen Sensor mit dem Oszi vermessen und die Definitionen dementsprechend angepasst.
[WS7035.txt](https://github.com/RFD-FHEM/RFFHEM/files/1120040/WS7035.txt)

**Comment by elektron-bbs** [comment]
Ändert ihr dann mal bitte noch die Sensordefinition (siehe Anhang in meinem Post vom 3. Juli).

**Comment by sidey79** [comment]
Ich hätte das nicht mehr auf auf dem Schirm, dass in der txt Datei Codeänderungen stehen. Ich werde es die aufnehmen.

_Gesendet von meinem Motorola XT1650 mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
