### ISSUE TITLE
Protokoll für Lidl T/H-Sensor IAN 60107 / Z32171D-TX

### ISSUE THREAD

**Issue by dennis82ni** [RFD-FHEM/RFFHEM#161]
Hardware: Arduino Nano V3 mit CC1101 433 MHz (Selbstbau-CUL)
Firmware: V 3.3.1-dev SIGNALduino cc1101 - compiled at Mar 10 2017 22:54:50

```
2017.05.31 21:19:20 4: sduino: Matched MS Protocol id 51 -> weather51
2017.05.31 21:19:20 4: sduino: Decoded MS Protocol id 51 dmsg W51#B5A4678452 length 40 RSSI = -35.5
2017.05.31 21:19:20 4: SD_WS_Parse: Protocol: 51, rawData: B5A4678452
2017.05.31 21:19:20 4: sduino decoded protocolid: 51 (Lidl Wetterstation 2759001/IAN114324) sensor id=5812, channel=2, temp=24.2, hum=45, bat=crititcal
2017.05.31 21:19:20 4: sduino using longid: 1 model: SD_WS_51_TH
2017.05.31 21:19:21 4: sduino/msg READ: MS;P0=554;P1=-4074;P2=-1853;P3=-15996;P4=994;P5=-1020;P6=-7897;D=06010201010201020101020102020102020201010202010101010202020201020202010201020201020345454545;CP=0;SP=6;R=78;O;

```
Ein anderer Lidl-Sensor wurde korrekt erkannt (CUL_TCM97001 ) und als AURIOL_23 angelegt. Die übertragenen Werte (channel=2, temp=24.2, hum=45) passen zum Display des Sensors, der nicht angelegt wird..

Es werden laufen neue Devices "SD_WS_51_TH_xxxxx" mit wechselnden IDs (xxxxx) angelegt, die aber entweder falsche Werte anzeigen oder nur kurze Zeit aktualisiert werden. Nach Neustart stehen sie auf "Defined".

Vielen Dank für die Hilfe und die tolle Arbeit,
schöne Grüße 
Dennis

**Comment by dennis82ni** [comment]
Hallo,
ich habe keine Antwort auf meinen Post bekommen und bin daher davon ausgegangen, dass nicht an diesem Fall gearbeitet wurde. Auch ich selbst bin hier leider nicht weiter gekommen.

Von daher ist die Antwort: Nein, der Sensor wird nicht decodiert / verarbeitet.

Ich würde mich aber sehr freuen, wenn sich das doch noch ein Experte anschauen würde!

Viele Grüße,
dennis82ni

**Comment by HomeAutoUser** [comment]
Hallo @dennis82ni,
hast du mal ein update gemacht um vielleicht Daten zur Verfügung zu stellen um einen Versuch zu wagen den Sensor zu erfassen?

MfG

**Comment by dennis82ni** [comment]
Hallo,
ich bin leider noch nicht dazu gekommen und kann auch leider noch nicht sagen, wann mal etwas Zeit zum Ausprobieren und Basteln habe ;-)

MfG

**Comment by dennis82ni** [comment]
Hallo,
ich habe endlich etwas Zeit gefunden, mir die Sache nochmal anzuschauen. Nach einem umfassenden Update nach eurer Beschreibung wird der Sensor tatsächlich erkannt, vielen Dank für die gute Arbeit!

Laut Doku [https://wiki.fhem.de/wiki/SIGNALduino (Unterstützte Geräte)](url) hätte ich erwartet, dass der Auriol-Sender als CUL_TCM97001 angelegt wird, tatsächlich wird er jedoch als SD_WS angelegt. Aber es funktioniert, also alles gut!

Viele Grüße,
Dennis

**Comment by HomeAutoUser** [comment]
Hallo, das klingt ja gut @dennis82ni.
Somit kann wohl der Faden erstmal als erledigt betrachtet werden?
LG

**Comment by dennis82ni** [comment]
Hi,
im automatisch angelegten Device finde ich nur die Angabe SD_WS_51_TH_7704_1, reicht das als Info?

Gruß Dennis

**Comment by elektron-bbs** [comment]
Ja, danke, das reicht uns.

**Comment by dennis82ni** [comment]
Hallo,
leider muss ich das Thema doch nochmal öffnen bzw. wieder aufgreifen, da der Sensor doch noch nicht zufriedenstellend funktioniert.
Nach ein paar Tagen Betrieb zeigt sich folgendes Phänomen: Es werden per autocreate laufend neue Devices angelegt, alle vom Typ SD_WS, jedoch mit unterschiedlichen Codes. Fast alle angelegten Devices werden auch weiterhin aktualisiert, jedoch jeder einzelne sehr selten. Dasjenige Device, welches zuletzt aktualisiert wurde, zeigt den aktuellsten Wert des Sensors an (bei Vergleich mit dem Original-Empfänger).

![grafik](https://user-images.githubusercontent.com/29105705/52814836-6be9e480-309d-11e9-927b-4bcc29c7dee6.png)

**Comment by elektron-bbs** [comment]
Das sieht ganz danach aus, als ob die Sensor-ID und einige andere Bits nicht richtig ausgewertet werden.
Um der Sache auf den Grund zu gehen, benötigen wir Logs von dem(n) Sensor(en).

Wenn du bereits das Attribut "addvaltrigger" bei deinem SIGNALduino auf 1 gesetzt hast:
Packe alle Logs der Sensoren SD_WS_51_TH_xxxx in ein Archiv und lade das dann hier hoch.

Wenn das Attribut noch nicht gesetzt ist, dann stelle es bitte auf 1 und zusätzlich das Attribut "verbose" auf 4. Lass dann das Log so etwa 6 h mitlaufen, am besten in einem Zeitraum, wo sich Temperatur und Feuchte möglichst stark ändern. Das fhem-Log wird dadurch ziemlich groß.  Deshalb dieses dann hier bitte hochladen (nicht als Text einfügen).

**Comment by dennis82ni** [comment]
Hallo,

ich habe das Log so wie beschrieben heute Vormittag mal mitlaufen lassen, da hatten wir einen schönen Temperaturanstieg und Feuchteabfall.

Vielen Dank für die Unterstützung!
[fhem-2019-02.log](https://github.com/RFD-FHEM/RFFHEM/files/2872281/fhem-2019-02.log)

**Comment by elektron-bbs** [comment]
Mein Verdacht hat sich bestätigt. Du könntest schon mal zum Test die Datei "14_SD_WS.pm" durch die aus diesem Archiv ersetzen:
[14_SD_WS.zip](https://github.com/RFD-FHEM/RFFHEM/files/2872345/14_SD_WS.zip)

Es müsste dir nach einem Neustart von FHEM dann ein neuer Sensor "SD_WS_51_TH_F0_1" angelegt werden.

Was du bitte noch probieren müsstest, wäre die Sendetaste am Sensor. Das neue Reading "sendmode" sollte bei Betätigung von "auto" zu "manual" wechseln.

**Comment by dennis82ni** [comment]
Hi,
ich habe die Datei heute Morgen getauscht und es hat wie beschrieben funktioniert, perfekt und vielen Dank für die tolle und schnelle Arbeit!
Eben habe ich einmalig die TX-Taste am Sender gedrückt, die rote LED auf der Vorderseite hat daraufhin kurz geleuchtet. Das Reading "sendmode" steht aber weiterhin auf "auto".

Neben dem gewünschten Sender wurden noch zwei weitere CUL_TCM97001-Devices angelegt:
- Unknown (Code: F031523641)
- W044_240
Es kann aber gut sein, dass das Sender von Nachbarn sind, es stört auch nicht weiter.

Vielen Dank nochmal und schöne Grüße,
Dennis

**Comment by elektron-bbs** [comment]
Dieses Device "Unknown (Code: F031523641)" und auch "W044_240" dürfte durch deinem Sensor angelegt worden sein. "F0" (240 dez entspricht F0 hex)  ist ja auch die Ident deines Sensors. Das TCM97001-Modul legt für alle Sensoren, die es nicht dekodieren kann, diese eigentlich sinnlosen Unknown an, statt sie zu ignorieren. "W044_240" müsstest du mal verfolgen, ob es sinnvolle Werte dekodiert.

Um das Bit für den Sendmode zu identifizieren, würde ich dich bitten, noch einmal ein Log mit Betätiguung der TX-Taste zu posten.

**Comment by dennis82ni** [comment]
Hi,
hier nochmal ein kurzes Logfile mit addvaltrigger=1 und verbose=4 beim sduino, währenddessen habe ich 4 Mal auf die TX-Taste gedrückt.
[fhem-2019-02 4xTX.log](https://github.com/RFD-FHEM/RFFHEM/files/2877084/fhem-2019-02.4xTX.log)

"W044_240" macht den Anschein einer Wetterstation mit Regensensor, deren Werte aber eher nach Regenwald im Monsum als nach Deutschland im Winter passen...

**Comment by elektron-bbs** [comment]
Danke, das Bit für sendmode passt eigentlich. Wenn ich die Nachrichten hier dispatche, geht sendmode auf "manual".

Hast du eigentlich am Sensor den Kanal 1 eingestellt? Ich habe mich da bisher auf den Code verlassen, der schon vorhanden war, würde ich aber gern auch noch verifizieren. Ich könnte dann auch noch eine Prüfung einbauen, ob ein gültiger Kanal (1-3) empfangen wurde. Ich sehe in deinem Log ab und an "SD_WS_51_TH_F0_0" - Kanal 0 gibt es ja eigentlich nicht.

Da "W044_240" offensichtlich nur "Datenmüll" produziert, könntest du die Protokolle 0 bis 0.4 (TCM97001) deaktivieren. Damit sollte dann auch kein "unknown" mehr angelegt werden.

**Comment by dennis82ni** [comment]
Ja, der Sender ist auf Kanal eingestellt, an der Original-Basisstation wird auch Kanal 1 angezeigt.

Wie deaktiviere ich bestimmte Protokolle denn am elegantesten?

**Comment by HomeAutoUser** [comment]
Hallo, drücke im Empfänger im oberen Teil des Bildschirms auf Display Protocollist.
Da kannst du die gewünschten heraus nehmen via Checkbox und auf Save klicken.

**Comment by elektron-bbs** [comment]
@dennis82ni 
Dann sollten die Bits für den Kanal stimmen. Ich habe die Datei 14_SD_WS.pm darauf angepasst. Die "SD_WS_51_TH_F0_0" sollten nach dem Einspielen dieses Moduls nicht mehr erscheinen:
[14_SD_WS_2.zip](https://github.com/RFD-FHEM/RFFHEM/files/2886315/14_SD_WS_2.zip)

**Comment by dennis82ni** [comment]
Super, vielen Dank für die Unterstützung. Werde es nach meiner Dienstreise in 2 Wochen nochmal testen, hab mir gestern auf die Schnelle irgendwas zerschossen mit dem sduino, nachdem ich alle Protokolle bis auf 51 deaktiviert hatte. Hab den Stick erstmal abgezogen und der Rest läuft wieder.

**Comment by dennis82ni** [comment]
Hallo,
die "SD_WS_51_TH_F0_0" erscheinen mit dem neuen Modul nicht mehr. Ich habe auch die Kanäle 0 bis 0.4 deaktiviert und es werden keine TCM97001-Devices mehr angelegt, alles fein.

Leider hat sich jetzt zum zweiten Mal der fhem-Server aufgehangen, nachdem er mit dem neuen Modul und dem sduino ein paar Stunden läuft. Beim ersten mal konnte ich ihn noch per ssh erreichen und neu starten, beim zweiten mal ließ er sich nicht mal mehr pingen. Beide Male musste ich den sduino abziehen, damit fhem sauber startet und wieder wie gewohnt läuft.

Habt ihr eine Idee, woran das liegen könnte oder Tips, mit welchen Einstellungen ich mal loggen o.ä. sollte?

Viele Grüße,
Dennis

**Comment by elektron-bbs** [comment]
Zeigt denn das Log von FHEM oder auch die Logs des Betriebssystems irgendwelche Auffälligkeiten? Was steht im Log, bevor sich das System "aufgehangen" hat? Was für ein Rechner und Betriebssytem ist es überhaupt?

**Comment by dennis82ni** [comment]
Gestern Morgen wurden bis ca. 5:30 Uhr Daten vom Auriol-Sender aufgezeichnet, die letzten Meldungen im Log waren folgende (der letzte Eintrag ca. 2h vor dem Einfrieren):
`2019.03.08 13:53:17 3: sduino: Unknown code u40#22C5C098, help me!
2019.03.08 16:21:37 3: sduino: Unknown code u40#1E7228CC048FDDEC, help me!
2019.03.08 21:28:15 1: sduino: SD_WS_Parse UNDEFINED sensor SD_WS_33_TH detected, code SD_WS_33_TH_961_1
2019.03.09 03:06:57 1: sduino: SD_WS_Parse UNDEFINED sensor SD_WS_33_TH detected, code SD_WS_33_TH_960_1`

FHEM läuft bei mir auf einem Raspberry Pi 2 unter Raspbian Jessie. Welche OS-Logs sollte ich hier mal anschauen?

**Comment by elektron-bbs** [comment]
Auf dem Raspi ist das Logging sowieso ziemlich stark eingeschränkt. Vieleicht mal /var/log/syslog ansehen und auch die restlichen Logs in diesem Verzeichnis. Eventuell hat auch die Speicherkarte einen weg.

**Comment by dennis82ni** [comment]
Im angehangenen [syslog](https://github.com/RFD-FHEM/RFFHEM/files/2953897/syslog.txt) sieht man, dass um 5:17 Uhr irgendwas passiert ist, für mich Linux-Noob sieht es wie ein Neustart aus. Dann taucht gut 8h lang nichts im Log auf, bis ich den nicht mehr funktionierten FHEM bemerkt habe und gegen 13:30 Uhr einen Kaltstart gemacht habe.

**Comment by elektron-bbs** [comment]
Bei deinem Linux-Problem kann ich dir leider nicht helfen. Mit FHEM hängt das sicher nicht zusammen.

Konntest du mittlerweile den Sensor testen? Wenn das funktioniert, würde ich gern ein Update des Moduls veranlassen.

**Comment by dennis82ni** [comment]
Wenn du das Modul oder FHEM als Ursache für die Abstürze ausschließen kannst, hilft mir das ja auch weiter!

Der Sensor lief jetzt einige Tage mit vernünftigen Werten, ich würde sagen das funktioniert soweit gut. Außer dass sendmode bei mir nicht auf manuell geht. 

Vielen Dank nochmal für die tolle Arbeit!

**Comment by elektron-bbs** [comment]
Die Änderungen sind jetzt in der Entwicklerversion eingearbeitet. Ich schließe dieses Issue.
