### ISSUE TITLE
Neues Protokoll WS7053

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#162]
Nein, das ist nicht wieder das gleiche Protokoll und auch kein Zahlendreher :-)
Ich hatte hier noch einen ähnlichen Funksensor nebst Anzeige liegen und habe dessen Protokoll analysiert und eingebaut. Es handelt sich um eine Temperaturanzeige, beschriftet mit "Remote Thermo Model 7053" und den dazugehörigen Sensor "Remote Datalink Model 7053". Das Protokoll ist ähnlich TX2 und wird deshalb auch vom Modul CUL_TX ausgewertet. Der Sensor sendet mit zwei verschiedenen Impulslängen. Ich habe deshalb die Definitionen zweimal eingefügt (66 und 67.1).
Die Auswertung des Sensors läuft bei mir jetzt seit ca. 2 Wochen fehlerfrei und könnte so übernommen werden.

   "67" => ## TX2 Protocol (Remote Datalink & Remote Thermo Model 7053)
            # das letzte Bit fehlt meistens
            # MU;P0=3381;P1=-672;P2=-4628;P3=1142;P4=-30768;D=0102320232020202020232020232020202320232323202323202020202020202020401023202320202020202320202320202023202323232023232020202020202020200;CP=0;R=45;
            # MU;P0=1148;P1=3421;P6=-664;P7=-4631;D=16170717071717171717071717071717171717070707170717171717070717171710;CP=1;R=29;
            # MU;P0=3389;P3=2560;P4=-720;P5=1149;P7=-4616;D=345407570757070707070757070757070707070757570707075707070707570757575;CP=5;R=253;
      {
         name           => 'WS7053',	
         id             => '67',
         one            => [-18,5],
         zero           => [-18,14],      # V1 - low ca. 3400
         #start          => [18,-2,18],   # mit "start" kaum Empfang
         clockabs       => 250,
         preamble	      => 'TX', 	      # prepend to converted message
         clientmodule   => 'CUL_TX',
         modulematch    => '^TX......',
         length_min     => '32',
         length_max     => '32',
         postDemodulation => \&SIGNALduino_postDemo_WS7053,
      }, 	
   "67.1" => ## TX2 Protocol (Remote Datalink & Remote Thermo Model 7053)
            # das letzte Bit fehlt meistens
            # MU;P0=-448;P1=1141;P2=-720;P3=602;P4=-4622;P6=-30776;D=012341434143434343434143434143434343434141414341434141434343434343436323414341434343434341434341434343434341414143414341414343434343434;CP=3;R=41;
            # MU;P0=32001;P1=-664;P2=602;P3=-4630;P4=1138;P6=-30880;D=012343234323232323234323234323232343234343432343232323234323232323262123432343232323232343232343232323432343434323432323232343232323232;CP=2;R=34;
            # MU;P0=-30784;P1=529;P2=1137;P3=-708;P4=280;P5=-208;P7=-4630;D=234517271727171717171727171727171717271727272717271717171727171717171013172717271717171717271717271717172717272727172717171717271717171710;CP=1;R=33;
      {
         name           => 'WS7053',	
         id             => '68',
         one            => [-18,5],
         zero           => [-18,3],       # V2 - low ca. 600-800
         #start          => [3,-2,3],     # mit "start" kaum Empfang
         clockabs       => 250,
         preamble	      => 'TX',	         # prepend to converted message
         clientmodule   => 'CUL_TX',
         modulematch    => '^TX......',
         length_min     => '32',
         length_max     => '32',
         postDemodulation => \&SIGNALduino_postDemo_WS7053,
      }, 	
);

sub SIGNALduino_postDemo_WS7053($@) {
	my ($name, @bit_msg) = @_;
	my $msg = join("",@bit_msg);
	my $new_msg ="";
	my $parity = 0;									# Parity even
	if (substr($msg,0,8) ne "10100000") {		# check ident
		Log3 $name, 3, "$name: WS7053 ERROR - Ident not 1010 0000 - " . substr($msg,0,8);
		return 0, undef;
	} else {
		for(my $i = 15; $i < 28; $i++) {			# Parity over bit 15 and 12 bit temperature
	      $parity += substr($msg, $i, 1);
		}
		if ($parity % 2 != 0) {
			Log3 $name, 3, "$name: WS7053 ERROR - Parity not even";
			return 0, undef;
		} else {
			Log3 $name, 4, "$name: WS7053 bit_msg $msg";
			Log3 $name, 5, "$name: WS7053 before: " . substr($msg,0,4) ." ". substr($msg,4,4) ." ". substr($msg,8,4) ." ". substr($msg,12,4) ." ". substr($msg,16,4) ." ". substr($msg,20,4) ." ". substr($msg,24,4) ." ". substr($msg,28,4);
         # Format from 7053:  Bit 0-7 Ident, Bit 8-15 Rolling Code/Parity, Bit 16-27 Temperature (12.3), Bit 28-31 Zero
			$new_msg = substr($msg,0,28) . substr($msg,16,8) . substr($msg,28,4);
         # Format for CUL_TX: Bit 0-7 Ident, Bit 8-15 Rolling Code/Parity, Bit 16-27 Temperature (12.3), Bit 28 - 35 Temperature (12), Bit 36-39 Zero
			Log3 $name, 5, "$name: WS7053 after:  " . substr($new_msg,0,4) ." ". substr($new_msg,4,4) ." ". substr($new_msg,8,4) ." ". substr($new_msg,12,4) ." ". substr($new_msg,16,4) ." ". substr($new_msg,20,4) ." ". substr($new_msg,24,4) ." ". substr($new_msg,28,4) ." ". substr($new_msg,32,4) ." ". substr($new_msg,36,4);
			return (1,split("",$new_msg));
		}
	}
}

**Comment by sidey79** [comment]
Hi, eine Frage.

Was genau meinst Du mit  ```# mit "start" kaum Empfang``` ?
Zu ID 67. Wieso hast Du clock 250 gewählt. Die scheint ja eher um 650 zu liegen.
Wenn man die Zuordnung wie folgt wählt, nehme ich an, dass ein weiteres Bit erkannt wird,
```
one => [5,-18],
zero => [14,-18], # V1 - low ca. 3400
```

Zu 67.1 was Du 68 benannt hast:

Wäre die Zuordnung vielleicht eher so. Dann dürfte da auch kein Bit fehlen denke ich.
```
one => [5,-18],
zero => [3,-18], # V2 - low ca. 600-800
```

**Comment by elektron-bbs** [comment]
Wenn ich versuche mit den Werten für "start" zu arbeiten kommen kaum noch Pakete durch. Der SIGNALduino scheint mit den Startzeiten nicht so richtig klar zu kommen.

"clock" habe ich jetzt sogar auf 122 genommen. Wenn ich die Zuordnung für 1 und 0 drehe, also mit dem High-Pegel beginne, passen die Bits nicht mehr zum Format. Wenn vorn der Low-Pulse steht, erhalte ich exakt die 32 Bit, die benötigt werden (Das das letzte Bit fehlt, kannst du streichen).

Da ich heute gerade den Oszi auf dem Tisch hatte, habe ich den Sensor mal vermessen. Er wiederholt das komplette Protokoll 4 mal im Abstand von ca. 32 mSek.
![ws753-01](https://user-images.githubusercontent.com/26026988/27013767-ea0ceaba-4eea-11e7-89ab-ec3aadb34c40.png)

**Comment by elektron-bbs** [comment]
Anbei noch einmal der komplette Code. Der Test läuft jetzt seit ca. 3 Wochen zur vollsten Zufriedenheit und könnte so übernommen werden.
[WS7053.txt](https://github.com/RFD-FHEM/RFFHEM/files/1120375/WS7053.txt)
