### ISSUE TITLE
Anbindung von GW-iwds07 Protokoll

### ISSUE THREAD

**Issue by Honkerr** [RFD-FHEM/RFFHEM#165]
Hallo,

Ich habe zur Zeit Pilight im Einsatz und möchte gern auf Signaliduino umbauen damit alles rein nur im FHEM ist und ich keine Zusatzsoftware brauche die eine Fehlerursache sein könnte.

Das Pilight Projekt unterstützt einen Fensterkontaktsensor, kann man nicht diese Protokoll Beschreibung benutzen um das auch hier zu integrieren? Ich würde meine Hilfe anbieten wenn ich etwas tuen kann. Habe die sensoren noch nicht, sind aber auf dem und erhalte die in den nächsten Tagen.

https://github.com/wo-rasp/pilight/blob/test_dev/libs/pilight/protocols/433.92/iwds07.c
https://github.com/wo-rasp/pilight/blob/test_dev/libs/pilight/protocols/433.92/iwds07.h

Die Sensoren übertragen Unit Code, Battery, OPEN|CLOSED (State)

**Comment by sidey79** [comment]
Prinzipiell sieht das schon machbar aus.

Kannst Du den Sensor mit einem Signalduino loggen?

**Comment by Honkerr** [comment]
Das kann ich machen sobald die Sensoren bei mir angekommen sind! Ich denke das wird anfang Nächster Woche soweit sein!

In Pimatic ist das Protokoll auch integriert worden. In den beiden Foren wurden mit deren tools auch schon Logs von den raw Signalen gepostet. Falls euch das das sollte stelle ich das zusammen und bereite das für euch auf. Müsst ihr nur sagen.

Zum loggen dann einfach nur signalduino auf verbose 5 stellen und schauen was für Nachrichten reinkommen richtig?

**Comment by sidey79** [comment]
Das Problem bei den Raw Logs von z.B. Pilight ist, dass der Pegelstand (low oder high) nicht mit ausgegeben wird.
Daher sind die Informationen nur bedingt geeignet.

Daher, poste bitte die Daten, sobald Du den Kontakt hast.

**Comment by Honkerr** [comment]
Hi, Also die Sensoren sind bei mir angekommen inkl. eines C1101 Empfänger/Sender. Damit läuft das ganze jetzt noch viel besser. Bin sehr begeistert von eurem Projekt. Also hier die ersten Mitschnitte.

Sensor 1, Kontakt entfernen (Fenster/Tür Öffnen)

```
2017.06.27 15:21:27 4: sduino/msg READ: MS;P0=-472;P1=1353;P3=440;P4=-1363;P5=-14033;D=35103434101010341010341034343434103434343410341034;CP=3;SP=5;R=36;O;
2017.06.27 15:21:27 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:21:27 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10A length 24 RSSI = -56
2017.06.27 15:21:27 4: sduino IT: message "i9DA10A" (7)
2017.06.27 15:21:27 4: sduino IT: msgcode "" (0) bin = 100111011010000100001010
2017.06.27 15:21:27 3: sduino IT: Code 1010 not supported by IT_1527x9da10.
2017.06.27 15:21:27 4: sduino IT: message "i9DA10A" (7)
2017.06.27 15:21:27 4: sduino IT: msgcode "" (0) bin = 100111011010000100001010
2017.06.27 15:21:27 3: sduino IT: Code 1010 not supported by IT_1527x9da10.
2017.06.27 15:21:27 3: sduino: Unknown code i9DA10A, help me!
2017.06.27 15:21:27 4: sduino/msg READ: MS;P0=-1364;P1=442;P2=1346;P3=-466;P4=-14034;D=14231010232323102323102310101010231010101023102310;CP=1;SP=4;R=35;O;
2017.06.27 15:21:27 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:21:27 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10A length 24 RSSI = -56.5
2017.06.27 15:21:27 4: sduino Dispatch: i9DA10A, Dropped due to short time or equal msg
2017.06.27 15:21:27 4: sduino/msg READ: MS;P0=-459;P1=1378;P2=458;P3=-1361;P4=-13993;D=24102323101010231010231023232323102323232310231023;CP=2;SP=4;R=33;O;
2017.06.27 15:21:27 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:21:27 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10A length 24 RSSI = -57.5
2017.06.27 15:21:27 4: sduino Dispatch: i9DA10A, Dropped due to short time or equal msg
2017.06.27 15:21:27 4: sduino/msg READ: MS;P0=-465;P1=475;P2=-1363;P3=1370;P4=-14479;D=14301212303030123030123012121212301212121230123012;CP=1;SP=4;R=27;
2017.06.27 15:21:27 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:21:27 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10A length 24 RSSI = -60.5
2017.06.27 15:21:27 4: sduino Dispatch: i9DA10A, Dropped due to short time or equal msg
```

Sensor 2, Kontakt zusammenbringen (Fenster/Tür Schließen)
```
2017.06.27 15:25:09 4: sduino/msg READ: MS;P1=1367;P2=-473;P3=440;P4=-1353;P5=-14012;D=35123434121212341212341234343434123434343412121234;CP=3;SP=5;R=22;O;
2017.06.27 15:25:09 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:25:09 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10E length 24 RSSI = -63
2017.06.27 15:25:09 4: sduino IT: message "i9DA10E" (7)
2017.06.27 15:25:09 4: sduino IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.27 15:25:09 3: sduino IT: Code 1110 not supported by IT_1527x9da10.
2017.06.27 15:25:09 4: sduino IT: message "i9DA10E" (7)
2017.06.27 15:25:09 4: sduino IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.27 15:25:09 3: sduino IT: Code 1110 not supported by IT_1527x9da10.
2017.06.27 15:25:09 3: sduino: Unknown code i9DA10E, help me!
2017.06.27 15:25:10 4: sduino/msg READ: MS;P0=-1361;P1=455;P2=1343;P3=-463;P4=-14017;D=14231010232323102323102310101010231010101023232310;CP=1;SP=4;R=23;O;
2017.06.27 15:25:10 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:25:10 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10E length 24 RSSI = -62.5
2017.06.27 15:25:10 4: sduino Dispatch: i9DA10E, Dropped due to short time or equal msg
2017.06.27 15:25:10 4: sduino/msg READ: MS;P0=471;P1=-1355;P2=1356;P3=-480;P4=-14045;D=04230101232323012323012301010101230101010123232301;CP=0;SP=4;R=22;O;
2017.06.27 15:25:10 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:25:10 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10E length 24 RSSI = -63
2017.06.27 15:25:10 4: sduino Dispatch: i9DA10E, Dropped due to short time or equal msg
2017.06.27 15:25:10 4: sduino/msg READ: MS;P0=1321;P1=-500;P2=444;P3=-1403;P4=-13994;D=24012323010101230101230123232323012323232301010123;CP=2;SP=4;R=19;
2017.06.27 15:25:10 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.27 15:25:10 4: sduino: Decoded MS Protocol id 3 dmsg i9DA10E length 24 RSSI = -64.5
2017.06.27 15:25:10 4: sduino Dispatch: i9DA10E, Dropped due to short time or equal msg
2017.06.27 15:25:10 4: sduino/msg READ: MU;P0=-465;P1=1379;P3=453;P4=-1357;P5=-14052;D=0103410343434341034343434101010343510343410101034101034103434343410343434341010103;CP=3;R=18;
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 5 -> unitec6899 matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 63 -> Warema matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: decoded matched MU Protocol id 63 dmsg u6392A9554CAA52552AA8 length 72 RSSI = -65
2017.06.27 15:25:10 3: sduino: Unknown code u6392A9554CAA52552AA8, help me!
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2017.06.27 15:25:10 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2017.06.27 15:25:11 4: sduino/keepalive ok, retry = 0
```

Irgendwie ist das komisch das da so viele Nachrichten gesendet werden? Könnt ihr damit etwas anfangen? Ich verstehe leider noch nicht genau wie ihr die Nachrichten analysiert und im Code außeinander nehmt, sonst würde ich helfen. Versuche das zu verstehen.

**Comment by sidey79** [comment]
Hallo @Ralf9 


So wie ich das einschätze bedarf es einer kleinen Anpassung im IT Modul, damit diese Sensoren auch damit arbeiten.
Kannst Du das wieder machen?

Grüße Sidey

**Comment by Ralf9** [comment]
Ich habe es mal mit meiner aktuellen angepassten Version getestet.
https://forum.fhem.de/index.php/topic,52827.0.html
`update all https://raw.githubusercontent.com/Ralf9/test/master/controls_signalduino.txt`

Damit funktioniert es
```
2017.06.27 20:42:30.413 4 : sduinoD/msg get dispatch: i9DA10E
2017.06.27 20:42:30.430 4 : sduinoD IT: message "i9DA10E" (7)
2017.06.27 20:42:30.430 4 : sduinoD IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.27 20:42:30.430 4 : sduinoD IT: 1527x9da10 not defined (Switch code: 1110)
2017-06-27 20:42:30.433 Global global UNDEFINED IT_1527x9da10 IT 1527x9da10 1110 0000
2017.06.27 20:42:42.168 4 : sduinoD/msg get dispatch: i9DA10E
2017.06.27 20:42:42.168 4 : sduinoD IT: message "i9DA10E" (7)
2017.06.27 20:42:42.168 4 : sduinoD IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.27 20:42:42.168 4 : sduinoD IT: 1527x9da10 not defined (Switch code: 1110)
2017.06.27 20:42:42.169 2 : autocreate: define IT_1527x9da10 IT 1527x9da10 1110 0000
2017.06.27 20:42:42.171 2 : autocreate: define FileLog_IT_1527x9da10 FileLog ./log/IT_1527x9da10-%Y-%m.log IT_1527x9da10
2017-06-27 20:42:42.178 Global global UNDEFINED IT_1527x9da10 IT 1527x9da10 1110 0000
2017-06-27 20:42:42.178 Global global DEFINED IT_1527x9da10
2017-06-27 20:42:42.178 Global global DEFINED FileLog_IT_1527x9da10
2017-06-27 20:42:42.178 Global global SAVE
2017.06.27 20:42:49.811 4 : sduinoD/msg get dispatch: i9DA10E
2017.06.27 20:42:49.811 4 : sduinoD IT: message "i9DA10E" (7)
2017.06.27 20:42:49.811 4 : sduinoD IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.27 20:42:49.811 3 : sduinoD IT: IT_1527x9da10 ???->on
2017-06-27 20:42:49.815 IT IT_1527x9da10 on
```

**Comment by Honkerr** [comment]
Hi,

Okay das wusste ich nicht das ich das IT Modul updaten muss. Gehen deine Änderungen denn irgendwann auch in den offiziellen FHEM SVN rein?

Wäre es möglich nicht nur on/off auszulesen sondern wie die pilight Entwickler, dass gesamte protokoll, jetzt wo ich die message mitgeschnitten habe?

```
	unit = binToDec(binary, 0, 19);
	battery = binToDec(binary, 20, 20);
	state = binToDec(binary, 21, 21);
createMessage(unit, battery, state);
```

Die haben da ja schöne unit, batterie und dann state mit open/closed

```
	json_append_member(iwds07->message, "unit", json_mknumber(unit, 0));
	json_append_member(iwds07->message, "battery", json_mknumber(battery, 0));
	if(state == 1) {
		json_append_member(iwds07->message, "state", json_mkstring("closed"));
	} else {
		json_append_member(iwds07->message, "state", json_mkstring("opened"));
}
```

https://github.com/wo-rasp/pilight/blob/test_dev/libs/pilight/protocols/433.92/iwds07.c

**Comment by Honkerr** [comment]
Habe jetzt mal das IT Modul aus dem anderen Repo von dir benutzt. Damit ist es wie vorher unverändert.

**Comment by Ralf9** [comment]
Hast Du den on- und off code angepasst?
`defmod IT_1527x9da10 IT 1527x9da10 1110 1010`

In der Device specific help vom IT-Modul habe ich das mit dem on- und off code beschrieben.

```
unit = binToDec(binary, 0, 19);
battery = binToDec(binary, 20, 20);
state = binToDec(binary, 21, 21);
```
Das ITv1 hat 24 Bit. Ich vermisse hier die Bits 22 + 23

Interessant wäre ein Log Mitschnitt bei fast leerer Batterie, ob sich da was ändert

**Comment by Honkerr** [comment]
Also Das habe ich natürlich nicht gewusst das ich den On / Off Code verändern muss. Im Nachhinein logisch aber bin ich nicht von selber drauf gekommen. Damit funktioniert das jetzt alles extrem gut!

Ich müsste jetzt irgendwie die Batterien, mal leer werden lassen und dann schauen was sich ändert? Nicht das die Führende 1 im On Off Code **1**110 **1**010 Sowas wie die Batterieanzeige ist.
Denn in der Message (unten) habe ich ja genau 24 Bits.
Oder der Letzte Bit in der erkannten "UNIT-ID" die ist ja auch gleich. Im Pilight code wird die Batterie variable auf -1 gesetzt und dann reagiert wenn es eine 0 wird weil das eine Bit auf 1 springt und dann zugerechnet wird.


Aber Ansich funktioniert alles im Zusammenhang mit dem Signalduino sehr gut! Mein einer Wettersensor wird mit negativen Temperaturwerten erkannt statt mit positiven aber da kann ich ja mal noch nen anderes Issue aufmachen. Auch mein Garagentorantrieb kann ich ja mal posten hier. Vielen dank für die Mühen.


```
root@raspi:/opt/fhem/log# tail -f fhem-2017-06.log | grep IT
2017.06.29 15:29:02 4: sduino IT: message "i98940A" (7)
2017.06.29 15:29:02 4: sduino IT: msgcode "" (0) bin = 100110001001010000001010
2017.06.29 15:29:02 3: sduino IT: Fensterkontakt_2 on->off
2017.06.29 15:29:06 4: sduino IT: message "i98940E" (7)
2017.06.29 15:29:06 4: sduino IT: msgcode "" (0) bin = 100110001001010000001110
2017.06.29 15:29:06 3: sduino IT: Fensterkontakt_2 off->on
2017.06.29 15:29:07 4: sduino IT: message "i98940E" (7)
2017.06.29 15:29:07 4: sduino IT: msgcode "" (0) bin = 100110001001010000001110
2017.06.29 15:29:07 3: sduino IT: Fensterkontakt_2 on->on
2017.06.29 15:29:14 4: sduino IT: message "i9DA10A" (7)
2017.06.29 15:29:14 4: sduino IT: msgcode "" (0) bin = 100111011010000100001010
2017.06.29 15:29:14 3: sduino IT: Fensterkontakt_1 off->off
2017.06.29 15:29:18 4: sduino IT: message "i9DA10E" (7)
2017.06.29 15:29:18 4: sduino IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.29 15:29:18 3: sduino IT: Fensterkontakt_1 off->on
2017.06.29 15:29:20 4: sduino IT: message "i9DA10A" (7)
2017.06.29 15:29:20 4: sduino IT: msgcode "" (0) bin = 100111011010000100001010
2017.06.29 15:29:20 3: sduino IT: Fensterkontakt_1 on->off
2017.06.29 15:29:23 4: sduino IT: message "i9DA10E" (7)
2017.06.29 15:29:23 4: sduino IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.29 15:29:23 3: sduino IT: Fensterkontakt_1 off->on
2017.06.29 15:29:23 4: sduino IT: message "i9DA10E" (7)
2017.06.29 15:29:23 4: sduino IT: msgcode "" (0) bin = 100111011010000100001110
2017.06.29 15:29:23 3: sduino IT: Fensterkontakt_1 on->on

```

**Comment by Honkerr** [comment]
Eine weitere Anmerkung,
Wie im vorherigen Post geschrieben kann es die erste Stelle der letzten 4 Zahlen nicht sein. Die Kontakte haben noch ein extra kontakt wenn man bei Missbrauch die Batterie Klappe öffnet senden sie ein anderes Signal.

```
2017.06.29 15:23:16 4: sduino/msg READ: ^BMS;P1=482;P3=1380;P4=-474;P6=-1353;P7=-13998;D=17341616343416161634161634163416161616161616343434;CP=1;SP=7;R=33;O;^C
2017.06.29 15:23:16 4: sduino: Matched MS Protocol id 3 -> itv1
2017.06.29 15:23:16 4: sduino: Decoded MS Protocol id 3 dmsg i989407 length 24 RSSI = -57.5
2017.06.29 15:23:16 4: sduino IT: message "i989407" (7)
2017.06.29 15:23:16 4: sduino IT: msgcode "" (0) bin = 100110001001010000000111
2017.06.29 15:23:16 3: sduino IT: Code 0111 not supported by Fensterkontakt_2.
2017.06.29 15:23:16 4: sduino IT: message "i989407" (7)
2017.06.29 15:23:16 4: sduino IT: msgcode "" (0) bin = 100110001001010000000111
2017.06.29 15:23:16 3: sduino IT: Code 0111 not supported by Fensterkontakt_2.
2017.06.29 15:23:16 3: sduino: Unknown code i989407, help me!
```

Dann gibt es statt dem 1010 und 1110 ein 0111 zu emfangen, kann man diesen Code auch noch irgendwie auswerten als dritten State?

**Comment by Ralf9** [comment]
Du kannst hinter dem On / Off Code optional noch den dimup- und dimdown- Code anhängen.
Dann wird z.B. bei 0111 dimup angezeigt.

**Comment by Honkerr** [comment]
Ah okay damit funktioniert auch das. Ja dann bedanke ich mich für die hilfe. Funktioniert so wie gewünscht.

Nur ist die Reichweite der Sensoren nicht gerade der bringer. mehr als 6-7 Meter sind drinnen nicht möglich trotz Nano+cc1101 auf 433 MHz. Vielleicht muss ich da dann doch auf bessere / teurere Kontakte umsteigen die mehr reichweite haben :(

**Comment by sidey79** [comment]
Ich habe mir so ein Gerät jetzt auch besorgt. Klang ja recht interessant.

Vorweg, es funktioniert.
Das mit der Reichweite kann ich bestätigen. Im gleichen Raum geht es gut. Durch zwei Stahlbeton Decken wird das Signal dann nur sehr selten noch empfangen.

**Comment by Honkerr** [comment]
Ja funktioniert gut, aber leider ist die reichweite zu gering. bin daher immer noch auf der Suche nach günstigen Fensterkontakten mit guter Reichweite. Die Homematic teile sind einfach unverschämt teuer :(

**Comment by sidey79** [comment]
Wir können hier schließen oder?
