### ISSUE TITLE
TFA 30.3161 Regenmesser mit Thermosensor

### ISSUE THREAD

**Issue by WagnerSystems** [RFD-FHEM/RFFHEM#166]
Hallo,
habe einen Kombisensor von TFA Temperatur und Regenmenge in gebrauch, TFA 30.3161.
Der Sensor wird als "CUL_TCM97001" erkannt und scheint auch die korrekte Temperatur zu liefern, bringt aber natürlich einen fehler bei der Luftfeuchte.
In Fhem werden keine Readings ausser state angelegt.

Ich setze aktuell die Version : V 3.3.1-dev SIGNALduino - compiled at Jan 3 2017 23:59:32 ein.
Als Empfänger nutze ich ein SRX882 433MHz modul.

Hier ein Mitschnitt aus dem Log von heute morgen.

`2017.06.25 11:40:01 4: sigduino/msg READ: MS;P1=430;P2=-4084;P3=-2010;P4=-9085;D=14121212121313131313121313121212131313131312131313121313131312121313131313;CP=1;SP=4;O;
2017.06.25 11:40:01 4: sigduino: Matched MS Protocol id 0 -> weather1
2017.06.25 11:40:01 5: sigduino: Starting demodulation at Position 2
2017.06.25 11:40:01 4: sigduino: Decoded MS Protocol id 0 dmsg sF04E08860000 length 40
2017.06.25 11:40:01 5: sigduino Dispatch: sF04E08860000, test gleich
2017.06.25 11:40:01 5: sigduino Dispatch: sF04E08860000,  dispatch
2017.06.25 11:40:01 5: sigduino: dispatch sF04E08860000
2017.06.25 11:40:01 4: CUL_TCM97001 Unknown 240 (F04E08860000) length: 12
2017.06.25 11:40:01 4: CUL_TCM97001 Parse Name: Unknown , devicecode: CUL_TCM97001_240 , Model defined: Unknown
2017.06.25 11:40:01 5: KW9010 CRC Matched: (111100000010011100000001000101100000000000000000)
2017.06.25 11:40:01 5: KW9010 t:26.3 / h:-59 mismatch
2017.06.25 11:40:01 4: CUL_TCM97001 Device not implemented yet name Unknown msg F04E08860000
2017.06.25 11:40:02 4: sigduino/msg READ: MS;P0=-2013;P1=431;P2=-4082;P3=-9092;D=13121212121010101010121010121212101010101012101010121010101012121010101010;CP=1;SP=3;O;
2017.06.25 11:40:02 4: sigduino: Matched MS Protocol id 0 -> weather1
2017.06.25 11:40:02 5: sigduino: Starting demodulation at Position 2
2017.06.25 11:40:02 4: sigduino: Decoded MS Protocol id 0 dmsg sF04E08860000 length 40
2017.06.25 11:40:02 5: sigduino Dispatch: sF04E08860000, test gleich
2017.06.25 11:40:02 4: sigduino Dispatch: sF04E08860000, Dropped due to short time or equal msg
2017.06.25 11:40:02 4: sigduino/msg READ: MU;P0=-2008;P1=431;P2=-9088;P3=-4086;D=010101010121313131310101010101310101313131010101010131010101;CP=1;
2017.06.25 11:40:02 4: sigduino: Fingerprint for MU Protocol id 13.1 -> FLAMINGO FA21 b matches, trying to demodulate
2017.06.25 11:40:02 5: sigduino: start pattern for MU Protocol id 13.1 -> FLAMINGO FA21 b mismatches, aborting
2017.06.25 11:40:02 5: sigduino: applying filterfunc SIGNALduino_filterSign
2017.06.25 11:40:02 5: sigduino: applying filterfunc SIGNALduino_compPattern
2017.06.25 11:40:02 5: sigduino: applying filterfunc SIGNALduino_filterMC`

Vielen Dank für die Umsetzung von Signalduino, für jegliche Hilfe beim einbinden meines Sensors möchte ich mich jetzt schon bedanken.

**Comment by pejonp** [comment]
@WagnerSystems zeigt der Regenmesser auch die Temp an ?
es wird ein  KW9010 t:26.3 / h:-59 mismatch in Log angezeigt.

**Comment by mellowman13** [comment]
Ich denke, die Luftfeuchtigkeit wird nicht gemessen, die Temparatur gemäss Anleitung schon. 
Ausserdem:
Anzeige der Regemenge gesamt, der letzten Stunde, der letzten 24 Stunden und des letzten Regens unter Angabe der Zeit und Datum der Speicherung.
Was davon vom Regenmesser kommt und was die Basisstation berechnet, weiss ich nicht.

**Comment by pejonp** [comment]
@mellowman13 

Könntet du mal den Regensensor auf Nullstellen und dann mitlesen.  Und dokumentieren welcher wert angezeigt wird.  z.B. 1 wippenschlag =0,3 mm Niederschlag.

**Comment by mellowman13** [comment]
Leider habe ich nur den Sensor und keine Basisstation :-(

**Comment by WagnerSystems** [comment]
**@pejonp** 
Ja der Regenmesser misst auch die Aussentemperatur. Luftfeuchtigkeit wird nicht gemessen, der Regenmesser hat keinen Sensor dafür. 3 x Wippenschlag gibt 1 mm Niederschlag

**Comment by WagnerSystems** [comment]
Das habe ich aus dem Fhem log.
`MS;P0=-3733;P1=481;P2=-1967;P3=-9046;D=13101012101212101212121212101010121210121210121212121212121212121210121210;CP=1;SP=3;`

**Comment by WagnerSystems** [comment]
Hier noch ein mitschnitt aus einem Terminalprogramm. Bei den letzten Zeilen habe ich jeweils einen Wippenschlag ausgelöst.

`MS;P0=-1986;P1=455;P2=-4056;P3=-9053;D=13121212121010101010121010101010101010101012101010121010121010101212121010;CP=1;SP=3;O;
MS;P0=-1986;P1=451;P2=-4061;P3=-9058;D=13121212121010101010121010101010101010101012101010121010121010101212121010;CP=1;SP=3;O;
MU;P0=-4059;P1=452;P2=-1987;P3=-9060;D=010101212131010101012121212121012121212121212121212101212121012121012121;CP=1;
MS;P1=463;P2=-4050;P3=-1985;P4=-9058;D=14121212121313131313121313121212121212121213131313121313121313131213131313;CP=1;SP=4;O;
MS;P0=-4059;P1=452;P2=-1987;P3=-9062;D=13101010101212121212101212101010101010101012121212101212101212121012121212;CP=1;SP=3;O;
MU;P0=-32001;P1=412;P2=-4082;P3=-2040;P4=312;P5=180;D=0121213121313121313131313121213131213131312131313131313131343435;CP=1;
MU;P0=252;P1=-2004;P2=436;P3=-4076;P4=-9076;D=0121212121212121212121212321242323212321212321212121212323210;CP=2;
MS;P1=455;P2=-4058;P3=-1997;P4=-9061;D=14121212121313131313121313121212121212121213131313121313121313131213131313;CP=1;SP=4;O;
MS;P0=-4064;P1=448;P2=-1991;P3=-9063;D=13101010101212121212101212101010101010101012121212101212101212121012121212;CP=1;SP=3;O;
MS;P1=455;P2=-4059;P3=-1989;P4=-9064;D=14121212121313131313121313121212121212121213131313121313121313131213131313;CP=1;SP=4;O;
MS;P0=-4055;P1=455;P2=-1985;P3=-9063;D=13101010101212121212101212101010101010101012121212101212101212121012121212;CP=1;SP=3;O;
MU;P0=176;P1=-1999;P2=440;P3=-4077;P4=-9100;P5=96;D=01212123212121212121212121212121212321242323212321212321212121212323212123215;CP=2;
MU;P0=164;P1=-4074;P2=440;P3=-2000;P4=-9108;P5=260;D=01232421212321232321232323232321212323212323235;CP=2;
MS;P1=-2071;P3=440;P4=328;P5=-4069;P6=-9082;D=36353531353131353131313141353531313531313135313131314131313141313131313531;CP=3;SP=6;
MS;P1=441;P2=-4072;P3=-1998;P4=-9073;D=14121212121313131313121313121212121212121213131313121313121313131213131313;CP=1;SP=4;O;
MS;P0=-4074;P1=446;P2=-1992;P3=-9075;D=13101010101212121212101212101010101010101012121212101212101212121012121212;CP=1;SP=3;O;
MU;P0=-4072;P1=172;P2=120;P3=-1999;P4=442;P5=320;P6=-9080;D=01023434043434340434343434343434343434353434043464040434043434043434343434040434340434343404343434343434343431;CP=4;
MS;P1=-4072;P2=440;P3=-2003;P4=-9083;D=24212123212323212323232323212123232123232321232323232323232323232323232123;CP=2;SP=4;O;
MS;P1=445;P2=-4070;P3=-1996;P4=-9066;D=14121212121313131313121313131212121212121213131313121313121313131212121212;CP=1;SP=4;O;
MS;P0=-4061;P1=449;P2=-1992;P3=-9064;D=13101010101212121212101212121010101010101012121212101212101212121010101010;CP=1;SP=3;O;
MS;P1=451;P2=-4063;P3=-1992;P4=-9067;D=14121212121313131313121313131212121212121213131313121313121313131212121212;CP=1;SP=4;O;
MS;P0=-4061;P1=450;P2=-1990;P3=-9061;D=13101010101212121212101212121010101010101012121212101212101212121010101010;CP=1;SP=3;O;
MS;P0=-4067;P1=430;P2=-2014;P3=-9068;D=13101012101212101212121212121012121012121210121212121212121212121210101212;CP=1;SP=3;O;
MU;P0=208;P1=-2005;P2=415;P4=-4081;P5=112;D=01212124212124212121242121212121212121215;CP=2;
MS;P1=454;P2=-4058;P3=-1990;P4=-9060;D=14121212121313131313121313131212121212121213131313121313121313131212121212;CP=1;SP=4;O;
MS;P0=-4057;P1=457;P2=-1983;P3=-9057;D=13101010101212121212101212121010101010101012121212101212101212121010101010;CP=1;SP=3;O;
MU;P0=116;P1=-4070;P2=431;P3=-2013;P4=-9084;P5=294;P6=-120;D=0123232421212321232321232323232323512323212323232123532356;CP=2;
MS;P1=452;P2=-4063;P3=-1992;P4=-9066;D=14121212121313131313121313131212121212121213131313131213121313131213131313;CP=1;SP=4;O;
MS;P0=-4059;P1=454;P2=-1985;P3=-9069;D=13101010101212121212101212121010101010101012121212121012101212121012121212;CP=1;SP=3;O;
MU;P0=-2006;P1=196;P2=-4072;P3=436;P5=-9072;D=0123030303230303030303030303030303232303035323230323030323030303030303230303230303032303030301;CP=3;
MS;P1=-1994;P2=441;P3=-4073;P4=-9074;D=24232321232121232121212121212321212321212123212121212121212121212123232121;CP=2;SP=4;
`

**Comment by pejonp** [comment]
@WagnerSystems 

Könntest du bitte den signalduino log anhängen. Den anderen müsste ich erst umrechnen.
2017.06.26 19:27:24 5: sigduino: dispatch sF04708110000

**Comment by mellowman13** [comment]
Wo liegt denn das signalduino-Log?

**Comment by pejonp** [comment]
@WagnerSystems 
Ich meine das fhem.log so wie in deinem ersten post.

**Comment by WagnerSystems** [comment]
@pejonp 
Ich glaube ich empfange mehrere Geräte, wenn ich das Log richtig interpretiere wir ein Gerät Typ 210 und ein Gerät Typ 240 erkannt.
[sigduino.txt](https://github.com/RFD-FHEM/RFFHEM/files/1106302/sigduino.txt)

**Comment by mellowman13** [comment]
Hier sind drei Einträge mit jeweils einem Wippenschlag dazwischen:

2017.06.27 21:56:14 4: sduino/msg READ: MS;P1=433;P2=-4094;P3=-2022;P4=-9118;D=14121212121313131313131312121212131212121213131313121313131312121313131213;CP=1;SP=4;O;
2017.06.27 21:56:14 4: sduino: Matched MS Protocol id 0 -> weather1
2017.06.27 21:56:14 5: sduino: Starting demodulation at Position 2
2017.06.27 21:56:14 4: sduino: Decoded MS Protocol id 0 dmsg sF01EF0862000 length 40
2017.06.27 21:56:14 5: sduino: converted Data to (sF01EF0862000)
2017.06.27 21:56:14 5: sduino: dispatch sF01EF0862000
2017.06.27 21:56:14 4: CUL_TCM97001 Unknown 240 (F01EF0862000) length: 12
2017.06.27 21:56:14 4: CUL_TCM97001 Parse Name: Unknown , devicecode: CUL_TCM97001_240 , Model defined: Unknown
2017.06.27 21:56:14 5: crc calc for: F01EF0862000
2017.06.27 21:56:14 5: calc crc is: 4
2017.06.27 21:56:14 5: ref crc is :4
2017.06.27 21:56:14 5: KW9010 CRC Matched: (111100001000011111110000000101100100000000000000)
2017.06.27 21:56:14 5: KW9010 t:24.7 / h:-59 mismatch
2017.06.27 21:56:14 4: CUL_TCM97001 Device not implemented yet name Unknown msg F01EF0862000
2017.06.27 21:56:14 5: Starting notify loop for Unknown, 1 event(s), first is Code: F01EF08620
2017.06.27 21:56:14 5: End notify loop for Unknown

2017.06.27 21:56:26 4: sduino/msg READ: MS;P0=-2023;P1=432;P2=-4092;P3=-9116;D=13121212121010101010101012121212101212121210101010101210101012121012101210;CP=1;SP=3;O;
2017.06.27 21:56:26 4: sduino: Matched MS Protocol id 0 -> weather1
2017.06.27 21:56:26 5: sduino: Starting demodulation at Position 2
2017.06.27 21:56:26 4: sduino: Decoded MS Protocol id 0 dmsg sF01EF046A000 length 40
2017.06.27 21:56:26 5: sduino: converted Data to (sF01EF046A000)
2017.06.27 21:56:26 5: sduino: dispatch sF01EF046A000
2017.06.27 21:56:26 4: CUL_TCM97001 Unknown 240 (F01EF046A000) length: 12
2017.06.27 21:56:26 4: CUL_TCM97001 Parse Name: Unknown , devicecode: CUL_TCM97001_240 , Model defined: Unknown
2017.06.27 21:56:26 5: crc calc for: F01EF046A000
2017.06.27 21:56:26 5: calc crc is: 5
2017.06.27 21:56:26 5: ref crc is :5
2017.06.27 21:56:26 5: KW9010 CRC Matched: (111100001000011111110000001001100101000000000000)
2017.06.27 21:56:26 5: KW9010 t:24.7 / h:-58 mismatch
2017.06.27 21:56:26 4: CUL_TCM97001 Device not implemented yet name Unknown msg F01EF046A000
2017.06.27 21:56:26 5: Starting notify loop for Unknown, 1 event(s), first is Code: F01EF046A0
2017.06.27 21:56:26 5: End notify loop for Unknown

2017.06.27 21:56:33 4: sduino/msg READ: MS;P0=-4098;P1=429;P2=-2019;P3=-9100;D=13101010101212121212121210121212101010101012121212101012121210101210101012;CP=1;SP=3;O;
2017.06.27 21:56:33 4: sduino: Matched MS Protocol id 0 -> weather1
2017.06.27 21:56:33 5: sduino: Starting demodulation at Position 2
2017.06.27 21:56:33 4: sduino: Decoded MS Protocol id 0 dmsg sF011F0C6E000 length 40
2017.06.27 21:56:33 5: sduino: converted Data to (sF011F0C6E000)
2017.06.27 21:56:33 5: sduino: dispatch sF011F0C6E000
2017.06.27 21:56:33 4: CUL_TCM97001 Unknown 240 (F011F0C6E000) length: 12
2017.06.27 21:56:33 4: CUL_TCM97001 Parse Name: Unknown , devicecode: CUL_TCM97001_240 , Model defined: Unknown
2017.06.27 21:56:33 5: crc calc for: F011F0C6E000
2017.06.27 21:56:33 5: calc crc is: 7
2017.06.27 21:56:33 5: ref crc is :7
2017.06.27 21:56:33 5: KW9010 CRC Matched: (111100001000100011110000001101100111000000000000)
2017.06.27 21:56:33 5: KW9010 t:24.8 / h:-57 mismatch
2017.06.27 21:56:33 4: CUL_TCM97001 Device not implemented yet name Unknown msg F011F0C6E000
2017.06.27 21:56:33 5: Starting notify loop for Unknown, 1 event(s), first is Code: F011F0C6E0
2017.06.27 21:56:33 5: End notify loop for Unknown

**Comment by pejonp** [comment]
@WagnerSystems 
Was wird den bei der Regenmenge angezeigt ?  Stand dieser beim ersten wippenschlag auf null ?

**Comment by WagnerSystems** [comment]
Regenmenge stand auf Null.

**Comment by WagnerSystems** [comment]
FYI
auf meinem Innegerät steht als Typenbezeichnung KW9015. Ich weis nicht ob die Info hilft?

**Comment by sidey79** [comment]
Ich habe da etwas gefunden.
Vielleicht passt dieses Regensensor Protokoll auch für den kw9015:

http://docplayer.net/46869335-Rf-transmission-protocol.html

**Comment by WagnerSystems** [comment]
@pejonp 
Moin Jörg.
Ich habe heute morgen alle Geräte im Fhem gelöscht und danach ein update 
(update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt) gemacht.
Anschliessend wurde von Fhem die folgenden Device mit autocreate angelegt
`GT_WT_02_240
  CUL_TCM97001_240`
und 
`Unknown
   CUL_TCM97001_Unknown
    STATE  Code: F04E506DC0`

Beim GT_WT_02_240 wird jetzt bei humidity ein positiver Wert angezeigt und die Readings für Temperatur und humidity werden angelegt. Die Temperatur in Fhem beträgt 8°C an meinem Innengerät wird 16,4°C angezeigt. bei humidity wird 54 angezeigt. Ich hänge nochmal das Log an.


[fhem.zip](https://github.com/RFD-FHEM/RFFHEM/files/1116953/fhem.zip)

**Comment by pejonp** [comment]
@WagnerSystems 
Hi wenn du das Model vom Sensor auf  KW9010 änders und dann diesen String:

{ Dispatch($defs{sigduino}, "sF01EF0862000", undef) }

in der FHEM Kommandozeile im Browser losschickst. kannst du mehrmals machen, sollte beim Sensor etwas angezeigt werden. bzw. er sollte sich von alleine ändern, da ja diesen Sensor hast.
 Temp sollte richtig sein Hum ist -irgendetwas.

Weiter bin ich noch nicht ;-)

du kannst ja auch mal die 14_CUL_TCM97001.pm austauschen (https://forum.fhem.de/index.php/topic,58397.msg656016.html#msg656016).

**Comment by WagnerSystems** [comment]
@pejonp 
Hi,
ich habe das Model geändert und anschliessend in der Kommandozeile den String abgesetzt.
In Fhem wurde ein neues Device angelegt -> CUL_TCM97001_Unknown
Diesem Device habe ich dann auch als Model -> KW9010 zugewiesen als Antwort kam von Fhem ARRAY(0x1b9f820) 
Als Reading wurde nur -> state Code: F01EF08620 angelegt.

Ich habe die Logs die unter Verbose=5 erstellt worden sind mit angehängt.
[Fhem.zip](https://github.com/RFD-FHEM/RFFHEM/files/1132976/Fhem.zip)

**Comment by pejonp** [comment]
@WagnerSystems 

Hast du mehrer Sensoren von diesem Typ im Einsatz oder sind das verschieden die aber die gleiche ID haben ? 
Weil es wird ja Temp/Hum angezeigt, so wie es angezeigt wird auch plausibel ?!

2017-07-02_15:22:23 KW9010_240 T: 19.5 H: 46
2017-07-02_15:25:21 KW9010_240 temperature: 19.4
2017-07-02_15:25:21 KW9010_240 T: 19.4 H: 46

ab hier hast du sicher die Daten per dispatch eingespielt !?

2017-07-08_14:49:49 KW9010_240 temperature: 24.7
2017-07-08_14:49:49 KW9010_240 humidity: -59
2017-07-08_14:49:49 KW9010_240 T: 24.7 H: -59
2017-07-08_15:03:15 KW9010_240 temperature: 24.7
2017-07-08_15:03:15 KW9010_240 humidity: -59
2017-07-08_15:03:15 KW9010_240 T: 24.7 H: -59

im log steht sowas

2017.07.08 14:53:23 4: CUL_TCM97001 using longid: 1 model: KW9010
2017.07.08 14:53:23 4: CUL_TCM97001 temperature KW9010_240 240 T: 24.7 H: -59
##
ist das ab hier der Regenmesser oder was ganz anderes ?
##
2017.07.08 14:53:23 4: sigduino/msg READ: MS;P1=413;P2=-4103;P3=-2028;P4=-9101;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:53:24 4: sigduino/msg READ: MS;P0=-4099;P1=410;P2=-2031;P3=-9106;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;
2017.07.08 14:53:53 4: sigduino/keepalive ok, retry = 0
2017.07.08 14:53:58 4: sigduino/msg READ: MS;P1=403;P2=-4110;P3=-2037;P4=-9112;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:53:59 4: sigduino/msg READ: MS;P0=-4123;P1=392;P2=-2052;P3=-9117;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;
2017.07.08 14:54:33 4: sigduino/msg READ: MS;P1=412;P2=-4104;P3=-2026;P4=-9109;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:54:34 4: sigduino/msg READ: MS;P0=-4103;P1=409;P2=-2032;P3=-9108;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;
2017.07.08 14:54:53 4: sigduino/keepalive ok, retry = 0
2017.07.08 14:55:08 4: sigduino/msg READ: MS;P1=403;P2=-4110;P3=-2039;P4=-9117;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:55:09 4: sigduino/msg READ: MS;P0=-4114;P1=401;P2=-2035;P3=-9113;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;
2017.07.08 14:55:43 4: sigduino/msg READ: MS;P1=397;P2=-4118;P3=-2044;P4=-9121;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:55:43 4: sigduino/msg READ: MS;P0=-4130;P1=384;P2=-2053;P3=-9124;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;
2017.07.08 14:55:53 4: sigduino/keepalive ok, retry = 0
2017.07.08 14:56:52 4: sigduino/msg READ: MS;P1=399;P2=-4113;P3=-2043;P4=-9120;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:56:53 4: sigduino/keepalive ok, retry = 0
2017.07.08 14:56:53 4: sigduino/msg READ: MS;P0=-4116;P1=399;P2=-2046;P3=-9120;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;
2017.07.08 14:57:27 4: sigduino/msg READ: MS;P1=407;P2=-4111;P3=-2031;P4=-9109;D=14121212121313131313121313121213121312131312131313121213121213121212121213;CP=1;SP=4;O;
2017.07.08 14:57:27 4: sigduino/msg READ: MS;P0=-4107;P1=407;P2=-2033;P3=-9107;D=13101010101212121212101212101012101210121210121212101012101012101010101012;CP=1;SP=3;O;

Da du ja anscheinend den Regensensor hast ? Was wird den im Signalduino angezeigt. Dazu bitte beim angelegten TCM... das Model auf KW9010 stellen.

**Comment by WagnerSystems** [comment]
Also, ich habe nur einen Sensor, ich bin mir aber nicht sicher ob ich nicht Sensoren meiner Nachbarn empfange.
Ich hatte einmal einen Sensor mit der ID/Code  "210" und einen mit "240" CUL_TCM97001_240.
Ich habe auch noch 4 x FA20RF.

Bei meinem angelegten Gerät "CUL_TCM97001_240" habe ich 26,7 °C und auf meiner Innenstation von TFA wird 27,2°C angezeigt falls das keine umrechnungs toleranzen sind dann scheinen mir die Werte nicht plausibel. 
Das Model steht schon seit einigen Tagen auf KW9010. Mein Modell heist KW9015.

**Comment by pejonp** [comment]
@WagnerSystems 

Kannst du mal einen log anhängen in dem man sieht wann der sensor sendet. Wir müssen erst einmal das protokoll finden.
Signalduino ist aktuell, letzter Stand vom github ?

**Comment by WagnerSystems** [comment]
@pejonp 
Ist benutze diese Version
V 3.3.1-dev SIGNALduino - compiled at Jan 3 2017 23:59:32
ist das die aktuelle ?

**Comment by pejonp** [comment]
@WagnerSystems 

ich habe die Version version: V 3.3.1-dev SIGNALduino cc1101 - compiled at Jan 12 2017 23:04:38 mit einem CC1101.

**Comment by WagnerSystems** [comment]
@pejonp 
CC1101 habe ich bestellt, muss jetzt warten bis das Modul eintrifft. Empfang dürfte eigentlich kein Problem sein da der Regensensor ca. 5m vom Empfänger weg ist.

Sobald das CC1101 Modul da ist melde ich mich nochmal.

**Comment by HomeAutoUser** [comment]
@WagnerSystems 
wie ist der Stand dieses Fadens?
Ist das Thema erledigt?

MfG

**Comment by mellowman13** [comment]
Damit lässt sich der Regenmesser auslesen: https://forum.fhem.de/index.php?topic=85746.0

**Comment by sidey79** [comment]
Da wäre eine Anpassung des CUL_TCM97001 Modules notwendig. Dieses Modul entwickeln wir hier leider nicht.

**Comment by elektron-bbs** [comment]
Eine Lösung wurde im wohl im FHEM-Forum geschildert, betrifft aber das Modul CUL_TCM97001.
Ich schließe das Issue. Bei Bedarf bitte wieder öffnen.
