### ISSUE TITLE
Protokoll für TFA 14.1504 (Küchen-Chef Funk-Bratenthermometer)

### ISSUE THREAD

**Issue by git-developer** [RFD-FHEM/RFFHEM#167]
### Gerät
- Küchen-Chef Funk-Bratenthermometer TFA 14.1504
- Frequenz: 433 MHz
- Sender: TPX305 / T 30.3201
Der Sender sendet die die gemessene Temperatur alle 5 Sekunden.
- Hersteller-Infos: http://tfa-dostmann.de/index.php?id=97

### SIGNALduino-Hardware
Arduino Nano mit Superheterodyne-Empfänger RXB6 / 433 MHz
### Vorgehen
Der Messfühler befand sich in erhitztem Wasser, das langsam abkühlt. Sobald die auf dem Display des Senders angezeigte Temperatur gefallen ist, wurde die Zeit notiert.
### Temperaturverlauf
- 12:05:51: 53°C
- 12:06:26: 52°C
- 12:07:10: 51°C
- 12:07:56: 50°C
- 12:08:41: 49°C
- 12:09:26: 48°C
- 12:10:10: 47°C
### Log
[log-1.txt](https://github.com/RFD-FHEM/RFFHEM/files/1100257/log-1.txt)

**Comment by HomeAutoUser** [comment]
Hallo @git-developer,
wie ist der aktuelle Stand deines Fadens?

Sollte das Protokoll nun eingebaut sein im SIGNALduino, bitte Thema schließen.
MfG

**Comment by git-developer** [comment]
Ich selber habe nichts beigetragen und mir ist nicht bekannt, dass jemand anderes das Protokoll bereits implementiert hat.

**Comment by HomeAutoUser** [comment]
Hallo,
kannst du das selbige noch einmal bitte  machen mit [dieser Firmware](https://github.com/RFD-FHEM/SIGNALDuino/tree/dev-r33_cc1101) und einmal mit [dieser](https://github.com/RFD-FHEM/SIGNALDuino/tree/dev-r33_fixmc).

Mit fällt bei deiner Aufzeichnung auf, das das Signal einmal als MC bzw MU erkannt wird.
Im optimalfall sollte nur eine Art von Signal erkannt werden. Sollte bei beiden Varianten jeweils MC und MU erkannt werden, dann deaktive mal MC.

Bei deiner Aufzeichnung, hast du nur diesen Sensor im Empfang oder auch andere? Der optimalfall wäre nur der neu zu erkennende Sensor ;-)

MfG

**Comment by git-developer** [comment]
Wie komme ich an die HEX-Dateien zu den genannten Branches? Ich vermute, dass die in FHEM unter `FHEM/firmware` liegenden Dateien der Version aus dem `master`-Branch entsprechen. Ich habe hier kein Visual Studio, aber eine Arduino-IDE (1.5.8). Wenn ich damit `SIGNUALDuino.ino` oder `RF_Receiver\RF_Receiver.ino` bauen möchte, führt das zu enem Compile-Fehler.

**Comment by git-developer** [comment]
Ich habe jetzt die aktuelle Arduino-IDE (Version 1.8.4) heruntergeladen und die SIGNALDuino-Bibliotheken von `src\_micro-api\libraries` nach `libraries` verlinkt. In den Branches `dev-r33_cc1101` (Commit 7aec17b) und `dev-r33_fixmc` (Commit 37c2863) konnte ich damit den Sketch `RF_Receiver.ino` bauen. Im Branch `master` musste ich zusätzlich in allen Bibliotheken die `library.properties` korrigieren (darin waren `name` und `version` nicht korrekt angegeben); dann war auch hier der Build von `RF_Receiver.ino` möglich.

Ich habe eigentlich erwartet, die Datei `SIGNALDuino.ino` zu bauen; das geht aber nicht, weil die Datei leer ist.

War das Vorgehen so richtig? Ist `RF_Receiver` der SIGNALDuino-Sketch?

**Comment by sidey79** [comment]
@git-developer 
Hi, prinzipiell ist deine Vorgehensweise schon ganz okay.
Compilierte Firmware Stände stelle ich im Normalfall als HEX Datei zur Verfügung.

Das noch Fehler in den library.properties vom Branch master sind, ist korrekt. Die verschwinden, sobald ich wieder mal in den master eine stabile Version merge. Travis kann die aktuelle Entwickler Firmware auch compilieren.

Die Bibliotheken habe ich da auch gelinkt
`
    "arduino --install-library \"ArduinoJson\"",
    "arduino --install-library \"TimerOne\"",
    "ln -s $PWD/src/_micro-api/libraries/bitstore /usr/local/share/arduino/libraries/bitstore",
    "ln -s $PWD/src/_micro-api/libraries/output /usr/local/share/arduino/libraries/output",
    "ln -s $PWD/src/_micro-api/libraries/signalDecoder /usr/local/share/arduino/libraries/signalDecoder",
    "ln -s $PWD/src/_micro-api/libraries/SimpleFIFO /usr/local/share/arduino/libraries/simpleFIFO",
    "ln -s $PWD/src/_micro-api/libraries/fastdelegate /usr/local/share/arduino/libraries/fastdelegate",
    "ln -s $PWD/cc1101.h $PWD/RF_Receiver/cc1101.h",
`
und compiliert wird die RF_Receiver.ino
`
    "arduino -v --verbose-build --verify $PWD/RF_Receiver/RF_Receiver.ino 2>&1"
`

Wenn Du forkst müsstest Du eigentlich auch über travis compilieren können.
Leider kommen da noch nicht alle möglichen Varianten raus, das muss ich irgendwann noch mal verbessern.

**Comment by git-developer** [comment]
Ich habe die Firmware zu den 3 Branches `dev-r33_fixmc`, `dev-r33_cc1101` und `master` wie beschrieben erstellt und auf den Nano hochgeladen. Dann habe ich wieder eine Testreihe mit dem Thermometer durchgeführt. Ergebnis:
* `master`: es wurden Werte empfangen (die zugehörigen Temperaturwerte und Zeitpunkte befinden sich im Log oben); siehe [SIGNALduino_nano_master_3.3.0.log](https://github.com/RFD-FHEM/RFFHEM/files/1351453/SIGNALduino_nano_master_3.3.0.log)
* `dev-r33_fixmc`: es wurden keine Werte empfangen, auch nicht nach Factory-Reset und Reset; Log: [SIGNALduino_nano_dev-r33_fixmc_3.3.1-dev.log](https://github.com/RFD-FHEM/RFFHEM/files/1351455/SIGNALduino_nano_dev-r33_fixmc_3.3.1-dev.log)
* `dev-r33_cc1101`: es wurden keine Werte empfangen; Log: [SIGNALduino_nano_dev-r33_cc1101_3.3.1-dev.log](https://github.com/RFD-FHEM/RFFHEM/files/1351454/SIGNALduino_nano_dev-r33_cc1101_3.3.1-dev.log)

Ich habe wie beschrieben den 433-MHz-Empfänger RXB6, also keinen CC1101, im Einsatz. Eignen sich die Branches `dev-r33_fixmc` und `dev-r33_cc1101` dafür?

**Comment by sidey79** [comment]
Du musst 
#define CMP_CC1101
auskommentieren, dann klappt es auch mit dem superhet Empfänger.

**Comment by git-developer** [comment]
Im Branch `dev-r33_cc1101` ist die Zeile bereits auskommentiert.
Im Branch `dev-r33_cc1101` fehlen nach dem auskommentieren `PIN_RECEIVE`, `PIN_LED`, `PIN_SEND`. Ich habe deshalb dort die Definitionen aus dem `master` ergänzt (2, 13, 11), damit kann ich bauen. Funktionieren tut es aber auch nicht: der Nano reagiert zwar auf Befehle von FHEM, aber es wird nichts empfangen und die Sende-LED leuchtet dauerhaft. Log: [dev-r33_fixmc_3.3.1-dev.log](https://github.com/RFD-FHEM/RFFHEM/files/1353192/dev-r33_fixmc_3.3.1-dev.log)

**Comment by sidey79** [comment]
Hallo git-developer,

ich kann deine Probleme leider nicht so ganz nachvollziehen. Bei mir klappt das compilieren.

Hier die Firmware mit direktem download Link:
superhet Version 
https://drive.google.com/uc?export=download&id=0B3UU1FxM6ZDUVFdDdlN5NUI0SUk

cc1101 Version
https://drive.google.com/uc?export=download&id=0B3UU1FxM6ZDUampST1Y1bGtNVnc


Mit der Modul Version des SIGNALduino von heute, kann man auch direkt eine http Quelle flashen. Manuelles downloaden ist nicht mehr notwendig:


`set sduino flash https://drive.google.com/uc?export=download&id=0B3UU1FxM6ZDUVFdDdlN5NUI0SUk
´

**Comment by git-developer** [comment]
Ich hatte mich oben verschrieben: nicht im Branch `dev-r33_cc1101`, sondern im Branch `dev-r33_fixmc` fehlen die Pindefinitionen. Mich wundert, dass Du `dev-r33_fixmc` (Commit `ab928a9`) bauen kannst, weil die [PIN-Definitionen im Quellcode tatsächlich nicht zu finden sind](https://github.com/RFD-FHEM/SIGNALDuino/blob/dev-r33_fixmc/RF_Receiver/RF_Receiver.ino).

Danke für das Bauen und Hochladen der beiden Firmware-Dateien. Das Verhalten ist damit aber wie den von mir gebauten Varianten:
- die CC1101-Variante empfängt nichts (das Log lässt vermuten, dass `CMP_CC1101` aktiviert ist) und
- bei der `SIGNALDuino_nano_mcfix.hex` leuchtet nach kuzer Zeit die Sende-LED dauerhaft, ; danach hilft nur noch ein Reset.

**Comment by sidey79** [comment]
Der Branch dev-r33_fixmc ist schon in den dev-r33_cc1101 überführt. Den brauchen wir nicht mehr bauen.

Dass der uC aber hängen bleibt wundert mich.
Gibt er auf der seriellen Konsole etwas aus?

**Comment by git-developer** [comment]
Ja:
```
Reading values fom eeprom
Starting timerjob
receiver enabled
Mu;⸮´;⸮⸮⸮;⸮⸮⸮;⸮Ã;⸮⸮⸮;⸮⸮⸮;⸮⸮;dU22B1V%P$6P;C5;R0;
Mu;⸮⸮⸮;⸮⸮⸮;⸮⸮⸮;⸮⸮⸮;⸮⸮⸮;⸮⸮;d@0D@40F@d&F&&&FF;C0;R0;
Reading ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮
```

... und das letzte Zeichen in Endlosschleife.

**Comment by git-developer** [comment]
Könnte die Größe der Firmware ein Problem sein? Der master-Branch hat 48 KB, die anderen Branches 58 KB.

**Comment by git-developer** [comment]
Ich habe zum Testen die Hardware gewechselt (anderer Nano), das Verhalten ist aber unverändert.

**Comment by HomeAutoUser** [comment]
Hallo,

heute kam ich bzw. wir mal kurz dazu den superhet Empfänger zu testen.
@sidey79 , wir müssen leider @git-developer Recht geben, das die Firmware  dev-r33_cc1101
nicht funktioniert wenn man das befolgt wie du geschrieben hattest.

> Du musst
> #define CMP_CC1101
> auskommentieren, dann klappt es auch mit dem superhet Empfänger.

Auf der Konsole "wanderte" nur ein Zeichen (Rechteck) und die LED am Empfänger blieb statisch an.

MfG

**Comment by Ralf9** [comment]
Ich habe bei der Firmware dev-r33_cc1101 für den superhet Empfänger was gefixt, bitte nochmals testen

**Comment by git-developer** [comment]
Das sieht besser aus, vielen Dank!

Hier das Log: [SIGNALduino_nano_dev-r33_cc1101_79d97fd.log](https://github.com/RFD-FHEM/RFFHEM/files/1364368/SIGNALduino_nano_dev-r33_cc1101_79d97fd.log)

Darin finde ich in schöner Regelmäßigkeit den Empfang eines Signals und die Ausgabe `extracted data 1010...010 (bin)`. Das Signal ändert sich zu denselben Zeitpunkten, zu denen sich auch die Temperatur ändert.

Wie geht es jetzt weiter? Ich schätze, als Nächstes ist in FHEM ein `DOIF` o.ä. mit passendem Muster zu erstellen... wird das Signal irgendwo in Hex oder als Zahl ausgegeben?

**Comment by git-developer** [comment]
Log mit Debug-Ausgabe (Temperatur 23°)
```
2017.10.07 11:59:24 5: signalduino/RAW READ: /MC;LL=-489;LH=506;SL=-239;SH=256;D=AACCD554D4CCB5555534CACCAA;C=248;L=103;
2017.10.07 11:59:24 4: signalduino/msg READ: MC;LL=-489;LH=506;SL=-239;SH=256;D=AACCD554D4CCB5555534CACCAA;C=248;L=103;
2017.10.07 11:59:24 1: DEBUG>signalduino: incomming message: (MC;LL=-489;LH=506;SL=-239;SH=256;D=AACCD554D4CCB5555534CACCAA;C=248;L=103;)
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted  pattern LL -489 
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted  pattern LH 506 
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted  pattern SL -239 
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted  pattern SH 256 
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted  data AACCD554D4CCB5555534CACCAA
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted absolute clock 248 
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted  number of 103 bits
2017.10.07 11:59:24 1: DEBUG>signalduino: processing manchester messag len:26
2017.10.07 11:59:24 1: DEBUG>clock and min length matched
2017.10.07 11:59:24 4: signalduino: Found manchester Protocol id 47 clock 248 -> Maverick protocol
2017.10.07 11:59:24 1: DEBUG>signalduino: extracted data 10101010110011001101010101010100110101001100110010110101010101010101010100110100110010101100110010101010 (bin)
2017.10.07 11:59:24 5: signalduino: extracted data 10101010110011001101010101010100110101001100110010110101010101010101010100110100110010101100110010101010 (bin)
2017.10.07 11:59:24 5: signalduino: protocol does not match return from method: ( header not found)
```

Es sieht so aus, als ob das Signal dem Maverick-Protokoll entspricht oder ähnelt, aber einen abweichenden Header hat. Vermutlich ist im FHEM-Modul `00_SIGNALduino` die Funktion `SIGNALduino_Maverick` zu erweitern.

**Comment by git-developer** [comment]
Issue #61 behandelt ebenfalls ein Funk-Grillthermometer mit Maverick-Protokoll, vielleicht gibt es einen Zusammenhang.

**Comment by sidey79** [comment]
Mit welcher Hardware und welcher Firmware hast Du das Signal empfangen?

**Comment by git-developer** [comment]
Da hat sich nichts geändert:
Hardware: Arduino Nano mit Superheterodyne-Empfänger RXB6 / 433 MHz
Firmware: Branch dev-r33_cc1101 (Commit [79d97fd](https://github.com/RFD-FHEM/SIGNALDuino/commit/79d97fdc0d713364612d2ac69c2439ed81b00321)) mit auskommentiertem `CMP_CC1101`

**Comment by git-developer** [comment]
Hallo und danke für die Nachfrage. Der Stand ist unverändert: das Signal wird empfangen, das Protokoll aber nicht dekodiert, weil der Header unbekannt ist.

**Comment by git-developer** [comment]
Erledigt (bei einer Temperatur von 23°C). Log: [rffhem-issue167-2018-11-10.log](https://github.com/RFD-FHEM/RFFHEM/files/2467386/rffhem-issue167-2018-11-10.log)

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.

**Comment by git-developer** [comment]
Ich würde gern wieder öffnen - das ginge aber nur, wenn ich selbst das Ticket geschlossen hätte.

**Comment by sidey79** [comment]
Dann Öffne ich das einfach für dich wieder :)

**Comment by git-developer** [comment]
Danke sehr!

**Comment by elektron-bbs** [comment]
Hier ist evtl. Hilfe in Sicht. Ich habe eben nur mal probehalber messageType von 59 auf 55 in der Datei 14_SD_WS_Maverick.pm geändert:
  if ($messageType eq '55'){
  # if ($messageType eq '59'){

Es wurde ein Gerät SD_WS_Maverick angelegt und die Temperaturen scheinen zu deinen angegebenen Werten zu passen. Ich habe nur keine Ahnung, was diese Varaible "messageType" mit Wert "normal" oder "sync" bewirken sollte. Es scheint bei dem Sensor, für das dieses Modul geschrieben wurde auch zwei Temperaturwerte zu geben: Food: 48 BBQ: disconnected

Vieleicht weiß @sidey79 oder @Ralf9 da noch Details.

**Comment by sidey79** [comment]
Ich hab das recherchiert. 

Der Maverick ET 733 sendet ein Sync Signal 6A nach dem Starten. Später kommt der Wert 59.
Das hat der User @dwuehler damals ausgewertet, da der ET733 keine anderen Werte sendet.

@elektron-bbs 
Wenn ich das richtig verstehe, haben wir hier jetzt ein Gerät, welches das gleiche Protokoll wie der maverick verwendet, allerdings mit nur einem Kanal?

**Comment by elektron-bbs** [comment]
Ja, genau so ist es. Ich habe mir die Bedienungsanleitungen der beiden Thermometer angesehen. Die Teile sehen sich auch ziemlich ähnlich, als ob sie von einem Hersteller stammen.
Im Prinzip müssten wir nur folgendes ändern:

  if ($messageType eq '55' || $messageType eq '59'){
    $messageType="normal";
  }elsif ($messageType eq '6A') {
    $messageType="sync";  
  }else{
    Log3 $iohash, 4, "$name $model ERROR: wrong messageType=$messageType (must be 59 or 6A)";
    return '';
  }

Für $messageType="sync" fehlt jetzt noch der Wert für das neue Thermometer.
Dazu müsste bitte @git-developer noch ein Log hochladen, in dem der Sync-Vorgang enthalten ist. Bitte aber vorher FHEM und SIGNALduino-Firmware aktualisieren.

**Comment by git-developer** [comment]
OK, werde ich in nächster Zeit machen.

**Comment by git-developer** [comment]
Ich habe

- FHEM gestartet
- ein `update` durchgeführt und FHEM neu gestartet
- [SIGNALDuino_nanocc11013.3.1-experimental](https://github.com/RFD-FHEM/SIGNALDuino/releases/download/3.3.1-experimental/SIGNALDuino_nanocc11013.3.1-experimental.hex) (Commit `71ea593`) geflasht

und dann

1. Nur den Sender eingeschaltet ([01-22grad.log](https://github.com/RFD-FHEM/RFFHEM/files/3547756/01-22grad.log))
1. Den Sender ausgeschatet
1. Den Empfänger eingeschaltet und danach den Sender eingeschaltet ([02-sync.log](https://github.com/RFD-FHEM/RFFHEM/files/3547757/02-sync.log))
1. Den Sync-Vorgang gemäß Anleitung durchgeführt ([03-sync.log](https://github.com/RFD-FHEM/RFFHEM/files/3547758/03-sync.log))

Falls das nicht reicht oder noch was fehlt, sagt bitte Bescheid.

**Comment by sidey79** [comment]
Ich habe bei Schritt 1. den MessageType 66 gesehen
und bei Schritt 3. und 4. jeweils MessageType 55.

Hast Du eine Idee, woran das liegen könnte?

**Comment by git-developer** [comment]
Da bin ich überfragt. Ich könnte noch mehr oder längere Mitschnitte machen, wenn das hilft.

**Comment by sidey79** [comment]
Kannst Du Schritt eins mehrfach wiederholen mit Log.

Mich interessiert auch nur der messagetype

**Comment by git-developer** [comment]
Die Datei [04.log](https://github.com/RFD-FHEM/RFFHEM/files/3549346/04.log) enthält die Ausgaben zu folgenden Schritten:

- 8:00:50 Sender ein
- 8:01:30 Sender aus
- 8:02:00 Sender ein
- 8:02:35 Sender aus
- 8:03:00 Sender ein
- 8:03:35 Sender aus
- 8:04:00 Sender ein
- 8:05:00 Betätigung des Sync-Knopfes
- 8:06:00 Betätigung des Sync-Knopfes
- 8:06:15 Sender aus

**Comment by git-developer** [comment]
Die Datei [05.log](https://github.com/RFD-FHEM/RFFHEM/files/3549385/05.log) enthält die Ausgaben zu folgenden Schritten:

- 08:16:55 Sender ein
- 08:17:15 Betätigung des Sync-Knopfes
- 08:17:45 Betätigung des Sync-Knopfes
- 08:18:00 Sender aus

**Comment by elektron-bbs** [comment]
Die Logs sind zu kurz. Ich denke aber doch, das messageType 55 für "normal" steht und 66 für "sync", da ich in der Datei log-1.txt 30 Treffer in ca. 6 Minuten mit messageType 55 finde.

Ich habe es jetzt mal so geändert:

  if ($messageType eq '55' || $messageType eq '59'){
    $messageType="normal";
  }elsif ($messageType eq '66' || $messageType eq '6A') {
    $messageType="sync";  
  }else{
    Log3 $iohash, 4, "$name $model ERROR: wrong messageType=$messageType (must be 55, 59, 66 or 6A)";
    return '';
  }

Am besten, du probierst selbst einmal, in dem du die Datei aus folgendem Archiv in deinem System ersetzt:

[14_SD_WS_Maverick.zip](https://github.com/RFD-FHEM/RFFHEM/files/3551793/14_SD_WS_Maverick.zip)

**Comment by sidey79** [comment]
Hi @elektron-bbs

Mach doch gleich ein Branch für die Anpassung auf.
Dann kann man die Anpassung gleich mit dem Update Befehl aktualisieren.

Für den späteren Merge brauchen wir den Branch ja ohnehin und die Situation wird klarer, welcher Versionsstand hinterlegt ist.

**Comment by elektron-bbs** [comment]
Naja, ich hatte eigentlich die Hoffnung, das das jemand übernimmt, der das Modul (mit)entwickelt hat.  Für mich sind da einige Ungereimtheiten drin, wie z.B. das stateFormat oder die Berechnung der Temperatur. Außerdem fehlen mir Nachrichten vom ursprünglichen Sensor (war es ein ET 732 oder 733?).

**Comment by git-developer** [comment]
Gute Neuigkeiten: mit den Anpassungen von Udo wird ein Maverick-Device angelegt und die Temperatur angezeigt.

Ich habe den Funkverkehr einige Minuten lang mitgeschnitten: [06.log](https://github.com/RFD-FHEM/RFFHEM/files/3552393/06.log) / [SD_WS_Maverick-2019.log](https://github.com/RFD-FHEM/RFFHEM/files/3552397/SD_WS_Maverick-2019.log).

Es hat etwas mehr als 2 Minuten gedauert, bis der Sender erkannt und das Device angelegt wurde.

Die Temperaturen stimmen mit denen des Thermometers überein. Es kommen zwar nicht alle Funknachrichten durch, aber ich schätze, dass es mindestens 1x pro Minute ein Wert geschafft hat. Dabei wurden `temp-food` und `checksum` aktualisiert.

Ich habe gegen Ende 1x den Sync-Knopf betätigt. Dabei wurden die Zeitstempel der Readings `Sensor-1-food_state` und `Sensor-2-bbq_state` aktualisiert.

**Comment by elektron-bbs** [comment]
Dann passt auf jeden Fall schon mal der messageType.
Dafür, das der Sensor alle 5 Sekunden sendet, ist allerdings die Anzahl der dekodierten Nachrichten ziemlich wenig.

**Comment by dwuehler** [comment]
Moin,
ich habe ein Maverick ET733. Das Funkprotokoll des 732 ist aber dasselbe. Das Modul 32_SD_WS_Maverick.pm gab es schon in einer Rohversion. Da war u. a. die Temperaturberechnung enthalten. Stateformat habe ich damals so implementiert. Was gibt es denn da für Anpassungswünsche?

**Comment by elektron-bbs** [comment]
Da unterliege ich wohl einem Irrtum, das das 733 mit 3 Temperaturfühlern ausgestattet ist? Manche Bilder im Netz zeigen das so.

Ich finde es halt nur außergewöhnlich, das es kein Reading "state" gibt, aber dafür vom Modul ein Attribut "stateFormat" mit relativ viel Perl-Code generiert wird. Wenn das der User löscht, wird gar kein State mehr aktualisiert.

**Comment by dwuehler** [comment]
Das Maverick 733 hat zwei Fühler. 

Beim state hast du Recht, glaube aber es stört auch nicht.  Normalerweise ist das Ding eh aus. Und wenn es an ist interessieren die Temperaturen.

**Comment by sidey79** [comment]
Der Sensor selbst hat ja keinen eigenen state den man empfängt oder?
Also welche Information könnte Reading state sinnvoll bereitstellen?

**Comment by elektron-bbs** [comment]
Da es ja ein Temperatursensor ist, halt die Temperatur(en) oder "inactive", würde ich vorschlagen.

**Comment by sidey79** [comment]
Wenn ich es richtig einordne, dann wird im internal STATE über stateformat die Temperatur dargestellt.

Das reading state ansicht wird nicht erstellt, da sich keine derartige Information in den Daten befinden, die dort angezeigt werden könnten.

Man könnte natürlich in das Reading state einen berechneten Zustand schreiben, im Sinne von aktiv / nicht aktiv. Der Zweck dahinter diese Information in das Reading state zu schreiben erschließt sich mir nicht. Wir schreiben ja auch kein reading battery wenn der Sensor keinen Batteriestand sendet. Auch hier wäre natürlich eine Berechnung über Zeit möglich, aber sicherlich fehleranfällig,

Habe auch noch mal im FHEM Wiki nachgesehen:
https://wiki.fhem.de/wiki/DevelopmentState

Da ist jetzt nicht dokumentiert, dass man ein Reading state anlegen muss.
Das mit dem Default leuchtet mir aber anderseits auch ein, hat man es gelöscht, dann ist es blöde.

**Comment by git-developer** [comment]
Meine Erfahrung deckt sich mit der von sidey79: ein Reading `state` ist nicht erforderlich, wichtig ist das Internal `STATE`.

Man könnte den Code, der sich derzeit im Attribut `stateFormat` befindet, benutzen, um `STATE` zu setzen, z.B. in der Subroutine `updateReadings`.

**Comment by elektron-bbs** [comment]
Ich hatte auch noch einige Ergänzungen in der Datei SD_ProtocolData.pm:

		"47"	=>	## Maverick ET-732, ET-733, Kuechen-Chef Funk-Bratenthermometer TFA 14.1504
							# https://github.com/RFD-FHEM/RFFHEM/issues/61 @mawa85 opened this issue on 15 Jan 2016
							# Food: 23 BBQ: 22   MC;LL=-507;LH=490;SL=-258;SH=239;D=AA9995599599A959996699A969;C=248;L=104;
							# https://github.com/RFD-FHEM/RFFHEM/issues/167 @git-developer opened this issue on 25 Jun 2017
			{
				name						=> 'Maverick',
				comment					=> 'BBQ / food thermometer Maverick ET-732, TFA 14.1504',
				id							=> '47',
				knownFreqs      => '433.92',
				clockrange			=> [200,300],		# ? eigentlich Durchschnitt 248
				# clockrange			=> [180,260],		# ? eigentlich Durchschnitt 248
				format					=> 'manchester',
				preamble				=> 'P47#',						# prepend to converted message
				clientmodule		=> 'SD_WS_Maverick',
				modulematch			=> '^P47#[569A]{12}.*',
				length_min			=> '100',
				length_max			=> '108',
				method					=> \&main::SIGNALduino_Maverick,		# Call to process this message
			},

Bei "clockrange" bin ich mir aber nicht sicher, was dort wirklich sinnvoll ist. Bei den meisten Nachrichten, die ich gesehen habe ist C=248.

**Comment by git-developer** [comment]
Wenn ich den Branch `dev-r34` mit Deinem Code vergleiche, sehe ich
- Änderungen in den Kommentaren
- `knownFreqs`:  Leerstring / `433.92`
- `clockRange`: `[180,260]` / `[200,300]`

Bei mir funktioniert das Thermometer mit den Werten aus `dev-r34` gut. Deshalb die Frage: ist eine Änderung von `SD_ProtocolData.pm` für das _TFA 14.1504_ notwendig?

**Comment by elektron-bbs** [comment]
Die Ergänzungen der Kommentare und der Frequenz bitte auf jeden Fall.
Wie schon geschrieben, bin ich mir bei clockrange nicht sicher, weil clock 248 schon ziemlich knapp an der Grenze des alten Wertes 260 ist.
@sidey79 kannst du uns bitte aufklären, welche Werte da sinnvoll sind?

**Comment by elektron-bbs** [comment]
@sidey79 Ich versuche nochmal meine Frage zu präzisieren: Sind für den clockrange bei MC eher die Angaben SL=-276;SH=224 oder der Wert C=248 heranzuziehen?
Welche Toleranz ist sinnvoll, wenn ich hier angenommen von einem Durchschnitt von 250 ausgehe?

**Comment by sidey79** [comment]
Clockgange wird gegen den C= Wert geprüft.
Da die Microcontroller nicht geeicht sind, kann man da ein bisschen toleranter sein.

**Comment by elektron-bbs** [comment]
Mir fällt gerade noch ein offenes Issue von @sidey79 zu diesem Protokoll auf:
https://github.com/RFD-FHEM/RFFHEM/issues/348

**Comment by sidey79** [comment]
Ja, ist mir noch im Gedächtnis.




Holen Sie sich Outlook für Android







On Sun, Sep 1, 2019 at 1:26 PM +0200, "Udo" <notifications@github.com> wrote:












Mir fällt gerade noch ein offenes Issue von @sidey79 zu diesem Protokoll auf:


#348

**Comment by HomeAutoUser** [comment]
Somit ist wohl dann der Faden abgeschlossen?
