### ISSUE TITLE
Protokoll Temperaturfühler TFA

### ISSUE THREAD

**Issue by Honkerr** [RFD-FHEM/RFFHEM#168]
Hi

Ich kann aktuell noch nicht genau sagen was für ein Temeperaturfühler (bin physisch noch nicht vorort) jedoch bekommt ich eine Nachricht von einem Temepraturfühler rein.

Mit der aktuelle version vom FHEM Trunk wurde der immer per Autocreate angelegt und als SD_WH Fühler erkannt. Die Temperatur war immer schwankend zwischen -25 und -30 Grad, jedoch die Luftfeuchtigkeit war richtig. Habe das mit dem wetter verglichen schwankend zwischen 0 und 100%.

Habe mich dann etwas belesen und mal das neue update vom dev-r33 branch eingefügt und habe dann gesehen das für manche protkolle ein CRC Perl Paket gebraucht wird. Habe das nachinstalliert und seitdem wird der Fühle vom autocreate aus UKNOWN erkannt. Komischerweise wird mein anderer Sensor seitdem extrem besser erkannt. (Auriol_128), vorher hatte ich pro stunde vielleicht 1-2 Werte empfangen, jetzt bekomme ich werte von dem im 5 Minuten Takt. Freut mich natürlich, erklären kann ich mir das aber nicht, wieso das mit dem CRC Paket und dem dev-r33 branch zusammenhängt. den dev-r33 hatte ich vorher auch schon mal drauf.

```
define Unknown CUL_TCM97001 CUL_TCM97001_Unknown
attr Unknown room CUL_TCM97001
define FileLog_Unknown FileLog ./log/Unknown-%Y.log Unknown
attr FileLog_Unknown logtype text
attr FileLog_Unknown room CUL_TCM97001
```

```
/opt/fhem/log# tail Unknown-2017.log
2017-07-15_13:34:09 Unknown Code: 808080
2017-07-15_13:35:41 Unknown Code: 8080B2
2017-07-15_13:53:15 Unknown Code: 8080B0
2017-07-15_13:55:19 Unknown Code: 8080B8
2017-07-15_14:01:00 Unknown Code: 8080B8
2017-07-15_14:14:26 Unknown Code: 808080
2017-07-15_14:29:56 Unknown Code: 808080
2017-07-15_14:36:08 Unknown Code: 8080C6
2017-07-15_15:05:04 Unknown Code: 8080C0
2017-07-15_15:06:06 Unknown Code: 808000
```

```
2017.07.15 15:06:06 4: sduino/msg READ: ^BMS;P1=364;P2=-8667;P3=-4036;P4=-2082;P5=948;P6=-612;D=1213141414141414141314141414141414145613141413141413141314141313141316;CP=1;SP=2;R=246;^C
2017.07.15 15:06:06 4: sduino: Matched MS Protocol id 4 -> arctech2
2017.07.15 15:06:06 4: sduino: Matched MS Protocol id 68 -> PFR-130
2017.07.15 15:06:06 4: sduino: Decoded MS Protocol id 68 dmsg s80800000 length 24 RSSI = -79
```

```
2017.07.15 14:36:08 4: sduino/msg READ: ^BMS;P1=391;P2=-8700;P3=276;P4=-4018;P5=-2061;D=12343535353515151514151515151515151414151515141415141415141514151517;CP=1;SP=2;R=246;^C
2017.07.15 14:36:08 4: sduino: Matched MS Protocol id 68 -> PFR-130
2017.07.15 14:36:08 4: sduino/msg READ: ^BMS;P0=-7558;P1=368;P2=-3756;P3=-2071;D=101213131313131313121313131313131312121313131212131212131213121;CP=1;SP=0;R=246;^C
2017.07.15 14:36:08 4: sduino: Matched MS Protocol id 68 -> PFR-130
2017.07.15 14:36:08 4: sduino: Decoded MS Protocol id 68 dmsg s8080C6D400 length 32 RSSI = -79
2017.07.15 14:36:08 4: sduino/msg READ: ^BMS;P1=-7411;P2=351;P3=-4054;P4=-2101;P6=112;P7=212;D=21232424242424242423242424242424242323242424232361737423242324242;CP=2;SP=1;R=248;^C
2017.07.15 14:36:08 4: sduino: Matched MS Protocol id 68 -> PFR-130
2017.07.15 14:36:08 4: sduino: Decoded MS Protocol id 68 dmsg s8080C600 length 24 RSSI = -78
```

**Comment by HomeAutoUser** [comment]
Hallo @Honkerr,
wie ist der Stand dieses Thema´s.
Dein Thema lautet Protokoll Temperaturfühler TFA. Hast du neuere Informationen zu dem TFA Sensor. (Bezeichnung oder eine Artikelnummer)

Das Modul  CUL_TCM97001 sammelt ALLES nicht verarbeitetn Daten unter Unknown. Sollte einmal Datenmüll erscheinen bzw. interprätiert werden, so landet das automatisch darin.

Sollte das Thema abgehakt sein, bitte schließen.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
