### ISSUE TITLE
Add Cresta Protocol

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#17]

**Comment by sidey79** [comment]
Module basics are done.
Deconding works for temp humidity sensors

**Comment by sidey79** [comment]
Clockrange 420-450 is to small.
Some Arduino measure higher clock. Up to 505.

**Comment by pejonp** [comment]
ich habe einmal im 14_SIGNALduino_un.pm  einen Test eingebaut. Leider kann ich jetzt die Datei in fhem mit update .... nicht aktuallisieren. Fehler:
.....
UPD FHEM/14_SIGNALduino_RSL.pm 
UPD FHEM/14_SIGNALduino_un.pm 
Got 10422 bytes for FHEM/14_SIGNALduino_un.pm, not 10239 as expected, 
aborting. 
Ich habe diese per Web gemacht.
Jörg

**Comment by hjgode** [comment]
Wenn Du ein update force machst, must die Datei
controls_signaludino.txt auch die korrekten Dateigrössen beinhalten.
Ich habe für Perl ein kleines Script geschrieben, welches die
controls_signalduino.txt für den dev-cresta branch erstellen kann:

Aufruf aus dem Verzeichnis über dem FHEM Verzeichnis unter Angabe des
Verzeichnisses FHEM: "perl build_controls_list.pl FHEM"
%<------------------------------------------------------
use strict;
use warnings;
use File::Find;
use POSIX;

main();

our @file_list=();

{ #closure to process find file
    my @results;
    sub mywanted {
        push @results, $File::Find::name;
    }
    sub findfiles{
        @results=();
        find \&mywanted, $_[0];
        return @results;
    }
}

sub listfiles2{
    my @dirlist = shift;
    foreach my $dir (@dirlist){
        #print ("error: $dir is not a directory\n"), next unless -d;
        my @files=findfiles($dir);
        my @lines=();
        foreach my $file (@files){
            if( (-e $file) && (! -d $file) ){ #test exist and is not a dir name
                #print "$dir contains $file\n";
                my $fi = file_info($file);
                my $date = POSIX::strftime("%Y_%d_%m_%H:%M:%S",
localtime( $fi->{mtime} ));
                #test if firmware
                if ( $file =~ /(firmware|\.hex|\.HEX)/ ){
#                    print "$file is a firmware\n";
                    push @lines, sprintf("DEL %s\n", $fi->{path});
                }
                push @lines, sprintf("UPD %s %-7s %s\n", $date,
$fi->{size}, $fi->{path});
            }
        }

        open(my $fh, '>', 'controls_signalduino.txt');
        foreach my $l (sort @lines){
            print $l;
            print $fh $l;
        }
        close $fh;
    }
}

sub main {

        listfiles2(@ARGV);
        return;
}

**Comment by Ralf9** [comment]
Ich habe mal das Cresta Modul mit dem Hama TS33C Temperatursensor getestet, dabei ist mir aufgefallen, daß die battery noch fehlt.
Ich habe es mal mit schwachen Batterien getestet und verglichen. Ich habe im Byte 2 (Package Length) eine Änderung festgestellt. Bat ok = 0xCE und Bat low = 0x0E.
Es müssten demnach das Bit 6+7 sein.

Zum Crestaprotocol habe ich folgendes gefunden. Gibt es was besseres wo auch was über die Battery steht?
http://members.upc.nl/m.beukelaar/Crestaprotocol.pdf

In fhem steht bei den lastMSG die rawData, wäre es nicht sinnvoller dort den decodedString einzutragen?
Macht beim cresta bei der bitMSG die rawBitData überhaupt sinn?

Ralf

**Comment by sidey79** [comment]
Hi Ralf,

ich weiss nicht, ob diese Sensoren einen Batterie Status übertragen.

Hinsichtlich Protokoll Beschreibung kenne ich auch nichts besseres. Man könnte mal nach hideiki Protokoll suchen, das ist glaube ich die Quelle für dieses Protokoll.

Ob es wirklich im Längenfeld steckt, wird denn eine andere Länge übertragen, wenn die Batterie schwach ist?

Die Variable rawBitData kann vermutlich entfallen, die hatte ich mal als Basis eingefügt, bevor ich wusste wie man die Daten am besten dekodiert.
Bei rawData kann man auch decodedString eintragen.

Du bist herzlich eingeladen die Änderungen vor zunehmen.
Es gibt ja zum Glück noch zwei weitere Personen, die sich aktiv an dem Modul beteiligt haben. Vermutlich sollte man auch hier einfach zur Sicherheit mal Werte außerhalb des Messbereiche heraus filtern.

Eigentlich müsste im TRXWeather Modul der Cresta Sensor auch implementiert sein, aber ich habe das nicht verstanden. :(

Sven



Am 18. September 2015 22:11:54 MESZ, schrieb Ralf9 <notifications@github.com>:
>Ich habe mal das Cresta Modul mit dem Hama TS33C Temperatursensor
>getestet, dabei ist mir aufgefallen, daß die battery noch fehlt.
>Ich habe es mal mit schwachen Batterien getestet und verglichen. Ich
>habe im Byte 2 (Package Length) eine Änderung festgestellt. Bat ok =
>0xCE und Bat low = 0x0E.
>Es müssten demnach das Bit 6+7 sein.
>
>Zum Crestaprotocol habe ich folgendes gefunden. Gibt es was besseres wo
>auch was über die Battery steht?
>http://members.upc.nl/m.beukelaar/Crestaprotocol.pdf
>
>In fhem steht bei den lastMSG die rawData, wäre es nicht sinnvoller
>dort den decodedString einzutragen?
>Macht beim cresta bei der bitMSG die rawBitData überhaupt sinn?
>
>Ralf
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141554498

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Ralf9** [comment]
Ich habe die Änderungen vorgenommen.
Mir ist noch nicht klar wo ich die minsecs ändern kann.

**Comment by sidey79** [comment]
Mit minsecs gibst Du beim Define des Gerätes an, in welchem Mindestabstand neue Werte akzeptiert werden. Sendet der Sensor z.B. alle 50 Sekunden, kann das einem ja das Log aufblähen. Also kannst Du z.B. mit dem Wert 300 festlegen, dass Du nur einen neuen Wert akzeptierst, wenn 300 Sekunden vergangen sind.

Mit equalmsg steuert Du, ob Du die gleiche Nachricht wie zuvor akzeptierst.

**Comment by Ralf9** [comment]
Die Funktion von minsecs war mir schon klar. Ich habe aber keine möglichkeit gefunden den Wert von 
minsecs zu ändern.
Bei den "attr" von "sduino" habe ich nur event-min-interval gefunden.

**Comment by sidey79** [comment]
Define <Name>  Cresta <Code> [minsecs] [equalmsg]

Sollte so auch in der Hilfe zum Cresta Modul stehen.
Also einfach an den  bereits definierten Sensor, im Feld DEF, den Wert hinten anfügen.

**Comment by Ralf9** [comment]
ok, so funktioniert es. Dies über das define zu machen ist aber eher etwas ungewöhnlich.
Wäre es nicht sinnvoller den Wert von minsecs über ein attr zu ändern?

**Comment by hjgode** [comment]
Hallo

also ausser dem PDF zum Cresta habe ich bisher noch keine andere Doku
gefunden. Auch zu Hideki gibt es nix im Netz. Es wird wohl beim
Arduino Project RemoteSensors erwähnt.

Das Batterie Flag ist im PDF nicht beschrieben und deshalb wäre ich
vorsichtig damit dies allgemein für Cresta festzulegen.
Haben die denn die Hama Sensoren einen anderen Typ als 0x1E (Zeile 128
in 14_Cresta.pm)?

Übrigens ist der Code dev-cresta zwar auf GIT gehostet, es wird aber
Subversion benutzt!
Erstes checkout:
svn co https://github.com/RFD-FHEM/RFFHEM/branches/dev-cresta

Änderungen hochladen:
svn commit -m "Text zu den Änderungen"
(im Verzeichnis das beim ersten checkout angelegt wurde)

Lokale Kopie aktualisieren:
svn update
(im Verzeichnis ....)

Unter Linux nutzt ich subversion svn Kommandos. Unter Windows Github
for Windows oder TortoiseSVN oder TortoiseGit. In Eclipse dann egit.

Gruss
Josef

**Comment by sidey79** [comment]
Das mit dem Batteriestatus ist schon interessant.

Zeigt die Station denn den Batterie zustand an?
Denkbar wäre auch, dass die Batterieinformation in einem eigenen Telegramm übermittelt wird.

Die Aussage, es wird SVN verwendet, kann ich nicht nachvollziehen.
Das Projekt liegt auf Github und das ist für GIT gemacht. Warum sollte man da svn nutzen?


Am 19. September 2015 19:18:43 MESZ, schrieb hjgode <notifications@github.com>:
>Hallo
>
>also ausser dem PDF zum Cresta habe ich bisher noch keine andere Doku
>gefunden. Auch zu Hideki gibt es nix im Netz. Es wird wohl beim
>Arduino Project RemoteSensors erwähnt.
>
>Das Batterie Flag ist im PDF nicht beschrieben und deshalb wäre ich
>vorsichtig damit dies allgemein für Cresta festzulegen.
>Haben die denn die Hama Sensoren einen anderen Typ als 0x1E (Zeile 128
>in 14_Cresta.pm)?
>
>Übrigens ist der Code dev-cresta zwar auf GIT gehostet, es wird aber
>Subversion benutzt!
>Erstes checkout:
>svn co https://github.com/RFD-FHEM/RFFHEM/branches/dev-cresta
>
>Änderungen hochladen:
>svn commit -m "Text zu den Änderungen"
>(im Verzeichnis das beim ersten checkout angelegt wurde)
>
>Lokale Kopie aktualisieren:
>svn update
>(im Verzeichnis ....)
>
>Unter Linux nutzt ich subversion svn Kommandos. Unter Windows Github
>for Windows oder TortoiseSVN oder TortoiseGit. In Eclipse dann egit.
>
>Gruss
>Josef
>
>On 9/18/15, sidey79 <notifications@github.com> wrote:
>> Hi Ralf,
>>
>> ich weiss nicht, ob diese Sensoren einen Batterie Status übertragen.
>>
>> Hinsichtlich Protokoll Beschreibung kenne ich auch nichts besseres.
>Man
>> könnte mal nach hideiki Protokoll suchen, das ist glaube ich die
>Quelle für
>> dieses Protokoll.
>>
>> Ob es wirklich im Längenfeld steckt, wird denn eine andere Länge
>übertragen,
>> wenn die Batterie schwach ist?
>>
>> Die Variable rawBitData kann vermutlich entfallen, die hatte ich mal
>als
>> Basis eingefügt, bevor ich wusste wie man die Daten am besten
>dekodiert.
>> Bei rawData kann man auch decodedString eintragen.
>>
>> Du bist herzlich eingeladen die Änderungen vor zunehmen.
>> Es gibt ja zum Glück noch zwei weitere Personen, die sich aktiv an
>dem Modul
>> beteiligt haben. Vermutlich sollte man auch hier einfach zur
>Sicherheit mal
>> Werte außerhalb des Messbereiche heraus filtern.
>>
>> Eigentlich müsste im TRXWeather Modul der Cresta Sensor auch
>implementiert
>> sein, aber ich habe das nicht verstanden. :(
>>
>> Sven
>>
>>
>>
>> Am 18. September 2015 22:11:54 MESZ, schrieb Ralf9
>> <notifications@github.com>:
>>>Ich habe mal das Cresta Modul mit dem Hama TS33C Temperatursensor
>>>getestet, dabei ist mir aufgefallen, daß die battery noch fehlt.
>>>Ich habe es mal mit schwachen Batterien getestet und verglichen. Ich
>>>habe im Byte 2 (Package Length) eine Änderung festgestellt. Bat ok =
>>>0xCE und Bat low = 0x0E.
>>>Es müssten demnach das Bit 6+7 sein.
>>>
>>>Zum Crestaprotocol habe ich folgendes gefunden. Gibt es was besseres
>wo
>>>auch was über die Battery steht?
>>>http://members.upc.nl/m.beukelaar/Crestaprotocol.pdf
>>>
>>>In fhem steht bei den lastMSG die rawData, wäre es nicht sinnvoller
>>>dort den decodedString einzutragen?
>>>Macht beim cresta bei der bitMSG die rawBitData überhaupt sinn?
>>>
>>>Ralf
>>>
>>>
>>>---
>>>Reply to this email directly or view it on GitHub:
>>>https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141554498
>>
>> --
>> Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail
>> gesendet.
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141568826
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141690445

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Ralf9** [comment]
Der Hama TS33C hat als Typ auch 0x1E
Ja, bei einer schwachen Batterie wird das Batteriesymbol angezeigt.
Hier sind einige $decodedStrings:
9f39 0e 5e 53c2 56 f2 5c5f00  Bat low
9f39 0e 9e 50c2 55 fe 90cc00 Bat low
9f3e ce 5e 70c2 57 f2 b96c00 Bat ok
9f3e ce 5e 66c2 55 f2 adbb00 Bat ok
9f3e ce 5e 50c2 54 fe 96f000 Bat ok

**Comment by Ralf9** [comment]
@hjgode: Danke für den Tipp mit dem SVN, damit kann ich kdesvn nutzen.
Ich habe es mal versucht und ein commit ins dev-proto7 übernommen.
Kann ich ein commit auch zurücknehmen?

**Comment by Ralf9** [comment]
Ich habe mal ein Vorschlag für die minsecs ins dev-proto7 übernommen, damit kann man die minsecs wahlweise auch allgemein im sduino festlegen.

**Comment by hjgode** [comment]
Bei github kann man via git or subversion arbeiten. Dann hat man
entweder ein .git oder ein .svn Verwaltungsverzeichnis in seiner
lokalen Kopie. Danach kann man dann nur git oder svn als client
verwenden. Oder man lädt das Repro in einem neuen Verzeichnis.

**Comment by sidey79** [comment]
Moin,

ja man kann auch einen svn client nutzen. Das stimmt. Warum man das tun sollte weiss ich nicht, außer man hat sich an einen Client schon gewöhnt.

Mich hatte hält der Satz "Es wird aber SVN benutzt" etwas überrascht. Du wolltest wohl ausdrücken, dass man auch SVN nutzen kann. :)

Grüße
Sidey

Am 20. September 2015 07:49:50 MESZ, schrieb hjgode <notifications@github.com>:
>Bei github kann man via git or subversion arbeiten. Dann hat man
>entweder ein .git oder ein .svn Verwaltungsverzeichnis in seiner
>lokalen Kopie. Danach kann man dann nur git oder svn als client
>verwenden. Oder man lädt das Repro in einem neuen Verzeichnis.
>
>
>On 9/19/15, sidey79 <notifications@github.com> wrote:
>> Das mit dem Batteriestatus ist schon interessant.
>>
>> Zeigt die Station denn den Batterie zustand an?
>> Denkbar wäre auch, dass die Batterieinformation in einem eigenen
>Telegramm
>> übermittelt wird.
>>
>> Die Aussage, es wird SVN verwendet, kann ich nicht nachvollziehen.
>> Das Projekt liegt auf Github und das ist für GIT gemacht. Warum
>sollte man
>> da svn nutzen?
>>
>>
>> Am 19. September 2015 19:18:43 MESZ, schrieb hjgode
>> <notifications@github.com>:
>>>Hallo
>>>
>>>also ausser dem PDF zum Cresta habe ich bisher noch keine andere Doku
>>>gefunden. Auch zu Hideki gibt es nix im Netz. Es wird wohl beim
>>>Arduino Project RemoteSensors erwähnt.
>>>
>>>Das Batterie Flag ist im PDF nicht beschrieben und deshalb wäre ich
>>>vorsichtig damit dies allgemein für Cresta festzulegen.
>>>Haben die denn die Hama Sensoren einen anderen Typ als 0x1E (Zeile
>128
>>>in 14_Cresta.pm)?
>>>
>>>Übrigens ist der Code dev-cresta zwar auf GIT gehostet, es wird aber
>>>Subversion benutzt!
>>>Erstes checkout:
>>>svn co https://github.com/RFD-FHEM/RFFHEM/branches/dev-cresta
>>>
>>>Änderungen hochladen:
>>>svn commit -m "Text zu den Änderungen"
>>>(im Verzeichnis das beim ersten checkout angelegt wurde)
>>>
>>>Lokale Kopie aktualisieren:
>>>svn update
>>>(im Verzeichnis ....)
>>>
>>>Unter Linux nutzt ich subversion svn Kommandos. Unter Windows Github
>>>for Windows oder TortoiseSVN oder TortoiseGit. In Eclipse dann egit.
>>>
>>>Gruss
>>>Josef
>>>
>>>On 9/18/15, sidey79 <notifications@github.com> wrote:
>>>> Hi Ralf,
>>>>
>>>> ich weiss nicht, ob diese Sensoren einen Batterie Status
>übertragen.
>>>>
>>>> Hinsichtlich Protokoll Beschreibung kenne ich auch nichts besseres.
>>>Man
>>>> könnte mal nach hideiki Protokoll suchen, das ist glaube ich die
>>>Quelle für
>>>> dieses Protokoll.
>>>>
>>>> Ob es wirklich im Längenfeld steckt, wird denn eine andere Länge
>>>übertragen,
>>>> wenn die Batterie schwach ist?
>>>>
>>>> Die Variable rawBitData kann vermutlich entfallen, die hatte ich
>mal
>>>als
>>>> Basis eingefügt, bevor ich wusste wie man die Daten am besten
>>>dekodiert.
>>>> Bei rawData kann man auch decodedString eintragen.
>>>>
>>>> Du bist herzlich eingeladen die Änderungen vor zunehmen.
>>>> Es gibt ja zum Glück noch zwei weitere Personen, die sich aktiv an
>>>dem Modul
>>>> beteiligt haben. Vermutlich sollte man auch hier einfach zur
>>>Sicherheit mal
>>>> Werte außerhalb des Messbereiche heraus filtern.
>>>>
>>>> Eigentlich müsste im TRXWeather Modul der Cresta Sensor auch
>>>implementiert
>>>> sein, aber ich habe das nicht verstanden. :(
>>>>
>>>> Sven
>>>>
>>>>
>>>>
>>>> Am 18. September 2015 22:11:54 MESZ, schrieb Ralf9
>>>> <notifications@github.com>:
>>>>>Ich habe mal das Cresta Modul mit dem Hama TS33C Temperatursensor
>>>>>getestet, dabei ist mir aufgefallen, daß die battery noch fehlt.
>>>>>Ich habe es mal mit schwachen Batterien getestet und verglichen.
>Ich
>>>>>habe im Byte 2 (Package Length) eine Änderung festgestellt. Bat ok
>=
>>>>>0xCE und Bat low = 0x0E.
>>>>>Es müssten demnach das Bit 6+7 sein.
>>>>>
>>>>>Zum Crestaprotocol habe ich folgendes gefunden. Gibt es was
>besseres
>>>wo
>>>>>auch was über die Battery steht?
>>>>>http://members.upc.nl/m.beukelaar/Crestaprotocol.pdf
>>>>>
>>>>>In fhem steht bei den lastMSG die rawData, wäre es nicht sinnvoller
>>>>>dort den decodedString einzutragen?
>>>>>Macht beim cresta bei der bitMSG die rawBitData überhaupt sinn?
>>>>>
>>>>>Ralf
>>>>>
>>>>>
>>>>>---
>>>>>Reply to this email directly or view it on GitHub:
>>>>>https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141554498
>>>>
>>>> --
>>>> Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail
>>>> gesendet.
>>>>
>>>> ---
>>>> Reply to this email directly or view it on GitHub:
>>>> https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141568826
>>>
>>>
>>>---
>>>Reply to this email directly or view it on GitHub:
>>>https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141690445
>>
>> --
>> Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail
>> gesendet.
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141697811
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/RFD-FHEM/RFFHEM/issues/17#issuecomment-141751747

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sidey79** [comment]
Ich habe mir gerade noch mal das TRX_Weather Modul angeschaut, dort wird das Hideik Protokoll, welches von Cresta, TFA etc. verwendet wird ja auch dekodiert.

Die extrahieren nach meiner Meinung eine Batterie Information, aus jeder Nachricht in der auch Temp und Hum steckt.

Es wird TRX_WEATHER_simple_battery aufgerufen.

Vom Prinzip wird das gemacht:

  my $battery_level = $bytes->[9] & 0x0f;
  if ($battery_level == 0x9) { $battery = 'ok'}
  elsif ($battery_level == 0x0) { $battery = 'low'}

Ich vermute aber mal, was beim RFX Device als byte 9 kommt, ist bei uns nicht unbedingt byte 9, aber es kommt auf jeden Fall direkt nach der Feuchtigkeit.

Ansonsten, kann man sich in diesem Modul auch das ein oder andere mal ansehen, das ist schon ganz gut aufgebaut.

**Comment by sidey79** [comment]
Die Längenprüfung im FHEM Modul wurde angepasst.
