### ISSUE TITLE
FHT80TF-2 | Type CUL_FHTTK

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#171]
Hallo,
da ich mir nun einen Arduino Nano + 868Mhz gebaut habe, 
so habe ich als ersten Versuch den FHT80TF-2 geloggt.

- Kontakt geöffnet

> 2017.08.22 14:02:09 4: sduino_USB0/msg READredu: MU;P0=-1016;P1=445;P2=-343;P3=648;P4=-550;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212123412341234341234121212;CP=1;R=73;
2017.08.22 14:06:17 4: sduino_USB0/msg READredu: MU;P0=-12932;P1=527;P2=-337;P4=-547;
D=012121212121212121212121214121414121214141212141414121214121414141412141414121214141212121212121412141214141214121212;CP=1;R=46;
2017.08.22 14:10:25 4: sduino_USB0/msg READredu: MU;P0=-2268;P1=435;P2=-353;P3=633;P4=-560;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212123412341234341234121212;CP=1;R=46;
2017.08.22 14:14:33 4: sduino_USB0/msg READredu: MU;P0=-32001;P1=436;P2=-350;P3=643;P4=-553;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234121212121212123434121234341234121234;CP=1;R=45;
2017.08.22 14:18:41 4: sduino_USB0/msg READredu: MU;P0=-7912;P1=450;P2=-338;P3=648;P4=-540;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212123412341234341234121212;CP=1;R=45;
2017.08.22 14:22:49 4: sduino_USB0/msg READredu: MU;P0=-26140;P1=441;P2=-341;P3=640;P4=-555;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234121212121212123434121234341234121234;CP=1;R=29;
2017.08.22 14:26:57 4: sduino_USB0/msg READredu: MU;P0=-30888;P1=528;P2=-336;P4=-548;
D=012121212121212121212121214121414121214141212141414121214121414141412141414121214141212121212121412141214141214121212;CP=1;R=28;

- Kontakt geschlossen

> 2017.08.22 14:35:13 4: sduino_USB0/msg READredu: MU;P0=-32001;P1=529;P2=-338;P4=-548;
D=012121212121212121212121214121414121214141212141414121214121414141412141414121214121212121212141214121214141214121412;CP=1;R=78;
2017.08.22 14:39:21 4: sduino_USB0/msg READredu: MU;P0=-32001;P1=441;P2=-347;P3=638;P4=-551;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234121212121212341234121234341234123412;CP=1;R=79;
2017.08.22 14:43:29 4: sduino_USB0/msg READredu: MU;P0=-9288;P1=441;P2=-345;P3=640;P4=-555;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212341212341234341234123434;CP=1;R=78;
2017.08.22 14:47:37 4: sduino_USB0/msg READredu: MU;P0=-547;P1=527;P2=-351;
D=012121212121212121212121210121010121210101212101010121210121010101012101010121210101212121212101212101210101210121010;CP=1;R=78;
2017.08.22 14:51:45 4: sduino_USB0/msg READredu: MU;P0=-4168;P1=431;P2=-352;P3=638;P4=-557;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212341212341234341234123434;CP=1;R=78;
2017.08.22 14:55:53 4: sduino_USB0/msg READredu: MU;P0=-7820;P1=438;P2=-352;P3=637;P4=-555;
D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212341212341234341234123434;CP=1;R=78;

Da es ja ein fertiges Modul für den CUL bereits gibt, so müssen wir diesen Sensor "nur" in die 00_SIGNALduino.pm aufnehmen und an das Modul übergeben.
Die Zuordnung der Readings, Battery, Previous, Reliability, Window und state untersuche ich.
MfG

**Comment by HomeAutoUser** [comment]
Hallo @Ralf9 | @sidey79 ,
könnt Ihr bitte dies hinzufügen.
Es handelt sich hierbei um einen 868Mhz Kontakt - Marke FHT80TF.
Da ich über das Wissen für einen Pull requests noch nicht verfüge, so schreibe ich es hier nieder.

> my $clientsSIGNALduino = ":IT:"
> ...
**> ."CUL_FHTTK:"**
> ; 

> my %matchListSIGNALduino = (
**>      "9:CUL_FHTTK"          => "^T[A-F0-9]{8}",**
> );

> 	"70" => ## FHT80TF (Funk-Tür-Fenster-Melder FHT 80TF und FHT 80TF-2 868Mhz)
> 			# MU;P0=-24396;P1=417;P2=-376;P3=610;P4=-582;D=012121212121212121212121234123434121234341212343434121234123434343412343434121234341212121212341212341234341234123434;CP=1;R=35;
> 			# MU;P0=-21652;P1=429;P2=-367;P4=634;P5=-555;D=012121212121212121212121245124545121245451212454545121245124545454512454545121245451212121212124512451245451245121212;CP=1;R=38;
> 			# 0 – 400 us of carrier, 400 us of silence
>     		# 1 – 600 us of carrier, 600 us of silence
> 		{
> 			name         	=> 'FHT80TF',
> 			id           	=> '70',
> 			one         	=> [3,-3],
> 			zero         	=> [2,-2],
> 			clockabs     	=> 200,
> 			clientmodule    => 'CUL_FHTTK',
> 			preamble     	=> 'T',
>          length_min     => '48',
>          length_max     => '58',
> 			postDemodulation => \&SIGNALduino_postDemo_FHT80TF,
> 		},

> sub SIGNALduino_postDemo_FHT80TF($@) {
> 	my ($name, @bit_msg) = @_;
> 	my $datastart = 0;
> 	my $sum = 12;
>    while ($bit_msg[$datastart] == 0) { $datastart++; }	      # Start bei erstem Bit mit Wert 1 suchen
>    splice(@bit_msg, 0, $datastart + 1);                        # delete preamble + 1 bit
>    if (@bit_msg < 45) {                                        # check count of databits
> 		Log3 $name, 3, "$name: FHT80TF - ERROR lenght of message";
> 		return 0, undef;
>    }
>    for(my $b = 0; $b < 45; $b += 9) {	                        # check parity over 5 byte
>       my $parity = 0;					                           # Parity even
>       for(my $i = $b; $i < $b + 9; $i++) {			            # Parity over 1 byte + 1 bit
>          $parity += @bit_msg[$i];
>       }
>       if ($parity % 2 != 0) {
>          Log3 $name, 3, "$name: FHT80TF ERROR - Parity not even";
>          return 0, undef;
>       }
>    }
>    for(my $b = 0; $b < 36; $b += 9) {	                        # build sum over first 4 bytes
>       $sum += oct( "0b".(join "", @bit_msg[$b .. $b + 7]));
>    }
>    my $checksum = oct( "0b".(join "", @bit_msg[36 .. 43]));    # Checksum Byte 5
>    if (($sum & 0xFF) != $checksum) {
>       Log3 $name, 3, "$name: FHT80TF ERROR - Checksum $checksum != $sum";
>       return 0, undef;
>    }
>    for(my $b = 44; $b > 0; $b -= 9) {	                        # delete 5 parity bits
>       splice(@bit_msg, $b, 1);
>    }
>    splice(@bit_msg, 32, 8);                                    # delete checksum
>    return (1, @bit_msg);
> }

Vielen Dank fürs eintragen.
LG

**Comment by Ralf9** [comment]
Ich habe es commitet

**Comment by Ralf9** [comment]
In der 
sub SIGNALduino_postDemo_FHT80TF($@) {
passt was nicht
https://forum.fhem.de/index.php/topic,58397.msg684146.html#msg684146

@sidey79 , @HomeAutoUser könnt ihr euch das mal anschauen?

**Comment by elektron-bbs** [comment]
Die Warnung von Perl wollte ich sowieso noch melden, habe ich allerdings nicht als so tragisch eingeschätzt.

2017.09.09 11:37:41 1: PERL WARNING: Scalar value @bit_msg[...] better written as $bit_msg[...] at ./FHEM/00_SIGNALduino.pm line 3896, <$fh> line 162.

Bitte mal noch ändern, von:
         $parity += @bit_msg[$i];
in
         $parity += $bit_msg[$i];

**Comment by Ralf9** [comment]
Mir ist nicht klar warum fhem damit stehen bleibt:

`PERL WARNING: Use of uninitialized value within @bit_msg in numeric eq (==) at ./FHEM/00_SIGNALduino.pm line 3888`

**Comment by Ralf9** [comment]
`while ($bit_msg[$datastart] == 0) { $datastart++; } # Start bei erstem Bit mit Wert 1 suchen`

Hier fehlt eine Abfrage ob das Ende der $bit_msg[] erreicht ist, sonst kommt es zu einer Fehlermeldung, wenn $bit_msg[] nur aus Nullen besteht!

**Comment by elektron-bbs** [comment]
Diese Idee hatte ich auch. Eigenartigerweise hat vor dieser Änderung noch keiner Probleme vorher gemeldet. In der sub SIGNALduino_postDemo_WS2000($@) ist die gleiche Abfrage seit ca. einem halben Jahr schon drin. Ich habe die Abfrage jetzt folgendermaßen umgestellt:

``   for ($datastart = 0; $datastart < $protolength; $datastart++) {   # Start bei erstem Bit mit Wert 1 suchen
      last if $bit_msg[$datastart] eq "1";
   }
   if ($datastart == $protolength) {                                 # all bits are 0
		Log3 $name, 3, "$name: FHT80TF - ERROR message all zeros";
		return 0, undef;
   }

**Comment by HomeAutoUser** [comment]
Guten Abend,

ich habe die [Codeänderung FHT80F](https://github.com/RFD-FHEM/RFFHEM/pull/175/commits/7702acf678f8fb476b22b75cb72e17a7bc97041d) soeben hochgeladen.
Es lief mit der Änderung 1h bei 6 Kontakten problemlos.

Zwecks WS2000 und dem selbigen "Fehler". Da werden wir ggf. den Pull Request nachreichen.
MfG

**Comment by Ralf9** [comment]
Ok, dann warten wir mit dem mergen der pull request bis ihr den Pull Request für den selben Fehler bei WS2000 nachgereicht habt.

@sidey79 
Ich habe noch nie ein merge Pull Request gemacht, wie geht man da vor?
Oder mergest Du die Pull Requests selber?

**Comment by sidey79** [comment]
@ralf9 für den ws2000 wäre das ein anderer Pull Request.

Mergen kann man einfach in github mit dem Befehl.

**Comment by Ralf9** [comment]
Ich habe es gemerged, es war recht einfach

**Comment by HomeAutoUser** [comment]
Vielen Dank Ralf.
Es folgt demnächst dennoch eine weitere Anpassung, da bei dem jetzigen Code sämtliche Device mit selbigen Protokollaufbau als Checksumm Error FHTTK im Logfile erscheinen. Da sind wir soeben dran, dies zu korrigieren, damit kein User denkt, der Sensor meldet einen Fehler, sondern es ist ein anderes Device.

**Comment by Ralf9** [comment]
@HomeAutoUser 
hast Du mitbekommen, daß die ID 72 inzwischen von Siro belegt ist
98_Siro.pm (Ansteuerung von motorisierten Innensichtschutzrollos)
https://forum.fhem.de/index.php/topic,77167.0.html

Kannst Du mal die Protokolldefinitionen posten von den Sachen die bei Dir gerade in Entwicklung sind.

Ich möchte was einbauen, damit ProtokollIds reserviert werden können.

Bei diesen ProtokollIds kommt dann in den comment rein, daß diese reserviert ist.
In die Protokolldefinition kommt dann z.B. developId    => 'p73', rein.
Damit wird diese Id nur noch verwendet, wenn sie in die whitelist oder in einem neuen Attribut "development" eingetragen ist.

**Comment by HomeAutoUser** [comment]
@Ralf,
danke für die Information.
In meinen Testfiles habe ich folgende Protokoll ID´s verwendet.

>	"72" => ## FHT80 - Raumthermostat (868Mhz)
		{
			name         	=> 'FHT80',
			comment		   => 'reserviert, Roomthermostat (868Mhz only receive)',
			id           	=> '72',
			one         	=> [1.5,-1.5],	# 600
			zero         	=> [1,-1],	# 400
			clockabs     	=> 400,
			format         => 'twostate',  # not used now
			clientmodule   => 'FHT',
			preamble     	=> '810c04xx0909a001',
			length_min     => '59',
			length_max     => '67',
			#postDemodulation => \&SIGNALduino_postDemo_FHT80,
		},
	"73" => ## FS20 - 'Remote Control
		{
			name         	=> 'FS20',
			comment		   => 'reserviert, Remote Control (868Mhz)',
			id           	=> '73',
			one         	=> [1.5,-1.5],	# 600
			zero         	=> [1,-1],	# 400
			clockabs     	=> 400,
			format         => 'twostate',  # not used now
			clientmodule   => 'FS20',
			preamble     	=> '810b04f70101a001',
			length_min     => '50',
			length_max     => '67',
			#postDemodulation => \&SIGNALduino_postDemo_FS20,
		},

Wenn du mir nun das OK gibst, so würde ich diese ab sofort unter 73 und 74 führen wollen, da ich der Annahme bin, das demnächst das P72 eingepflegt wird.

Die Idee, die ID´s zu reservieren finde ich gut! Somit versuchen wir ein wenig Ordung einzupflegen.
In diesem Zusammenhang würde ich mal anregen wollen, das ID´s welche Unbekannt sind und bisher nur Leichen sind ohne Verarbeitung, ob man diese nicht herausnimmt und die "Lücken" mit neuen Protokollen auffüllt. Was meint Ihr? Eine Ansammlung von "blinden Protokollen welche nicht implementiert sind sollte doch nicht das Ansinnen sein.

Parallel würde ich dafür vorschlagen, ein Issues zu eröffnen wo diese "Reservierten" hier intern bekannt gegeben werden können, somit würden wir vermeiden, das wir bei einer Neuentwicklung die selbige ID nutzen, sollte jemand nicht aktuell schauen oder 2 Neuentwicklungen parallel laufen sollten.

**Comment by Ralf9** [comment]
Id 73 + 74 passt
siehe
https://github.com/RFD-FHEM/RFFHEM/issues/181

**Comment by elektron-bbs** [comment]
test
