### ISSUE TITLE
Firmware Download direkt aus dem Modul

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#172]
Ich habe ein paar zeilen Code geschrieben, mit dem ich die Releases und die Dateien, die in Github als Releases hinterlegt sind abfragen kann.

Hier ein Beispiel für die aktuell hinterlegten SIGNALESP Releases:

```
      ];
                }
                  'HASH(0x2c85700)' => undef
                  isprerelease => $fwreleases->[0]{isprerelease},
                  releasename => '3.3.1-devmc_',
                           ],
                             }
                               'HASH(0x1b4e988)' => undef
                               dlurl => 'https://github.com/RFD-FHEM/SIGNALESP/releases/download/3.3.1-devmc_/SIGNALESP.cpp.bin',
                               create_date => '2017-08-25T20:28:13Z',
                               filename => 'SIGNALESP.cpp.bin',
                             {
                             #0
                  files => [
                {
                #2
                },
                  releasename => '3.3.1-devmc'
                           ],
                             }
                               'HASH(0x2a359b8)' => undef
                               filename => 'SIGNALESP_test.bin',
                               create_date => '2017-08-29T20:38:11Z',
                               dlurl => 'https://github.com/RFD-FHEM/SIGNALESP/releases/download/3.3.1-devmc/SIGNALESP_test.bin',
                             {
                             #1
                             },
                               create_date => '2017-08-25T20:45:10Z'
                               filename => 'SIGNALESP_cc1101.bin',
                               'HASH(0x1b946a0)' => undef,
                               dlurl => 'https://github.com/RFD-FHEM/SIGNALESP/releases/download/3.3.1-devmc/SIGNALESP_cc1101.bin',
                             {
                             #0
                  files => [
                  'HASH(0x2a35bb0)' => undef,
                  isprerelease => $fwreleases->[0]{isprerelease},
                {
                #1
                },
                  isprerelease => bless( do{\(my $o = 1)}, 'JSON::XS::Boolean' )
                  releasename => 'release3.3.1a_cc1101_devmc',
                           ],
                             }
                               dlurl => 'https://github.com/RFD-FHEM/SIGNALESP/releases/download/release3.3.1a_devmc/SIGNALESP.bin'
                               filename => 'SIGNALESP.bin',
                               'HASH(0x2b64400)' => undef,
                               create_date => '2017-08-28T21:31:13Z',
                             {
                             #0
                  files => [
                  'HASH(0x2c57100)' => undef,
                {
                #0
2017.08.29 23:31:11.589 1: DEBUG> releases = $fwreleases = [
```

Es handelt sich um drei Releases die dort aktuell hinterlegt sind. Im Release #1 befinden sich zwei Firmware Dateien.

Weitere Idee:

Anzeigen einer List mit veröffentlichten Releases. Sortiert nach Datum.
Bei Auswahl des Releases soll das changelog für dieses angezeigt werden mit der Option, diese FW herunter zu laden + flashen.

**Comment by sidey79** [comment]
@ralf9

Ich soll keine binär Dateien mehr über das FHEM Update verteilen.

Ich bin noch nicht sicher, ob ich das jetzt noch umsetzen oder dann im Release 3.3.2

**Comment by Ralf9** [comment]
Es ist wahrscheinlich am einfachsten, wenn Du in einem ersten Schritt die firmware binär Dateien alle im github ablegst.
Z.B. in
https://github.com/RFD-FHEM/SIGNALDuino/tree/master/FHEM/firmware
wenn Du dann noch
https://github.com/RFD-FHEM/SIGNALDuino/blob/master/controls_signalduino.txt
dann können die firmware binär Dateien mit update geladen werden.

Wenn Du dann beim flashen noch eine Abfrage machst ob es die firmware binär Datei gibt, dann kannst Du beim fehlen der binär Datei eine Meldung ausgeben mit dem update Befehl

**Comment by sidey79** [comment]
Gut, dann müssen die Anwender wieder mit update Add etc etwas einbinden und herunterladen.

Mit den releases fand ich es nicht wirklich schwer, da diese ja automatisch erzeugt werden können und dort noch mehr Informationen als nur der Dateiname gleich mit liegen.
Nur die Eingabefelder müsste ich halt einbauen. Das ist wohl der zeitaufwändige Teil.

Man ist dann vom update Befehl auch gänzlich unabhängig und lädt nur genau die Firmware herunter die man auch wirklich installieren möchte.
