### ISSUE TITLE
Protokoll für EliteScreens Motorleinwand

### ISSUE THREAD

**Issue by Pfriemler** [RFD-FHEM/RFFHEM#173]
Geloggt mit SIGNALEsp, V 3.3.1-dev SIGNALduino cc1101 - compiled at Aug 18 2017 18:37:31
Motorleinwand EliteScreens (diverse Produkte mit vermutlich gleicher Steuerung). Sendung auf ca 434 MHz, "hörbar" (mit RTL-SDR) sehr unterschiedliche Signalfolgen je nach Taste, aber immer gleich (also eher kein Rollingcode). Zur Verfügung stehen UP, DOWN und STOP. 

Ich halte es für sehr fraglich, ob dieses Protokoll vernünftig erkannt werden kann, deshalb die Voranfrage 
an die Experten, ob das schon mal irgendeinen Sinn macht.

In der Umgebung ist es sehr ruhig, es kommen außer "u40#" derzeit kaum Meldungen. Ich habe nach verbose 4 und 5 (!) kurzen (!) Tastendrücken auf STOP im Abstand von ca 10 Sekunden diese Zeilen im Log:

```
2017.08.30 15:12:59 4: SIGNALEsp433/msg READ: MU;P0=-1045;P1=2645;P2=1025;P3=651;P4=-216;P6=1472;P7=-615;D=2343434343434343434343434343434343434343434343464373034341024343067202430643737643;CP=3;R=208;
2017.08.30 15:13:01 4: SIGNALEsp433/msg READ: MU;P0=-861;P1=855;P2=-364;P3=361;D=01212123012123012301212121230121212303012301212303012301230121212303012123012301230301230303012303;CP=3;R=232;
2017.08.30 15:13:02 4: SIGNALEsp433/msg READ: MU;P0=-1038;P1=2489;P2=1227;P3=591;P4=-219;P7=-672;D=23434343434343434343434343434343434343434343434243730343410243430272024302437142;CP=3;R=208;
2017.08.30 15:13:10 4: SIGNALEsp433/msg READ: MU;P0=-1038;P1=2489;P2=1227;P3=591;P4=-219;P7=-672;D=23434343434343434343434343434343434343434343434243730343410243430272024302437142;CP=3;R=208;
2017.08.30 15:13:11 4: SIGNALEsp433/msg READ: MU;P0=996;P1=654;P2=-315;P3=-205;P4=1459;P5=-622;P6=-1094;P7=2672;D=0121212121212121343151613137603131645060216431503431;CP=1;R=208;
2017.08.30 15:13:20 4: SIGNALEsp433/msg READ: MU;P0=2672;P1=996;P2=-608;P3=654;P4=-317;P5=-205;P6=1459;P7=-1094;D=2343434343434343434343535353535353535343434343565323735350715353762171437653215653;CP=3;R=209;
2017.08.30 15:13:22 4: SIGNALEsp433/msg READ: MU;P0=-869;P1=352;P2=834;P3=-385;D=01010102310102323231023102323102310101010101023231010102310101023231010102323101;CP=1;R=208;
2017.08.30 15:13:26 4: SIGNALEsp433/msg READ: MU;P0=-869;P1=834;P2=-385;P3=352;D=0121230303030301230301212123012301212301230303030303012123030301230303012123030301212303;CP=3;R=208;
```

Unerklärlich mir, warum teilweise im Sekundenabstand Signale erkannt wurden und dass sich das 10-Sekundenraster (nach Sekundenzeiger auf der Uhr) nicht eindeutig wiederfinden lässt.

Genauer krieg ich es nicht hin; wenn sich hier schon kein Muster ableiten lässt, dann wird das wohl nix. (Die Leinwand hat zum Glück genug andere Steuermöglichkeiten). 

THX, Pfriemler

**Comment by HomeAutoUser** [comment]
Guten Abend @Pfriemler,

lange ist dein Post her.
Wir versuchen hier ein wenig "Ordnung zu schaffen" und möchten auch diesen Faden prüfen.

Deine damalige Meldung umfasst die Decodierung deiner EliteScreens Motorleinwand mit dem SIGNALduino. Wie ist der Stand aktuell? Wird dein Aktor decodiert / verarbeitet?

Über eine Rückmeldung würden wir uns freuen.
MfG

**Comment by HomeAutoUser** [comment]
Danke für deine Rückmeldung.
Da werden wir deinen Faden hier schließen.

Solltest du erneut Fragen oder ein Anliegen haben, so melde dich einfach bitte zu Wort.
