### ISSUE TITLE
FHEM hängt sich auf durch Fehler im 00_SIGNALduino.pm Modul

### ISSUE THREAD

**Issue by prodigy7** [RFD-FHEM/RFFHEM#176]
Eben gerade passiert: fhem (Perl) hatte 100% Auslastung auf meinem RPi, war nichts mehr ansprechbar. Letzte Meldung im Logfile war:
```
2017.09.12 20:31:19.313 3: sduino433: Unknown code u63AAAAAAAAA, help me!
2017.09.12 20:31:21.416 3: sduino433: Unknown code u63A95556AAD550, help me!
2017.09.12 20:31:31.586 3: sduino433: Unknown code u63555555555, help me!
2017.09.12 20:31:37.871 1: PERL WARNING: Use of uninitialized value within @bit_msg in numeric eq (==) at ./FHEM/00_SIGNALduino.pm line 3888.
```
Musste den perl-Prozess killen und FHEM neu starten.

Ursache war Update aus dem Repo mit aktueller Version. Nach Revert auf vorherige Version bis dato kein Problem mehr.

**Comment by HomeAutoUser** [comment]
Guten Abend,

du kannst mal bitte [diese](https://github.com/RFD-FHEM/RFFHEM/pull/175/commits/7702acf678f8fb476b22b75cb72e17a7bc97041d) Änderung ausprobieren.

Ich habe das ganze System ebenfalls auf dem RPi und es klappt.
Du kannst ebenso mal bitte die Protokolle einschränken via Whitelist testweise.
Meine Erfahrungen sind, wenn ich meinen 868Mhz nutze und alle Protokolle bis 70 freigebe, so erfolgt irgendwann ein Data overflow.

**Comment by prodigy7** [comment]
Bis dato lief bei mir alles über Monate ohne Probleme durch, wäre komisch wenn ausgerechnet jetzt ein overflow eintreten würde. Ich werde die Änderung mal ausprobieren, Danke! Rückmeldung folgt!
