### ISSUE TITLE
Thermo-/Hygrosensor Bresser 7009994 (Protokoll 34/37)

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#177]
Ich empfange seit einer Woche mit einem SignalESP einen Sensor, dessen Puls- Pausenzeiten mit den vorhandenen Protokolleinträgen 34 und 37 harmonieren. Ich habe mir die Dekodierung genauer angesehen und konnte diese einem Sensor Bresser 7009994 zuordnen. Das Protokoll ist gut dokumentiert hier zu finden: https://github.com/merbanan/rtl_433_tests/tree/master/tests/bresser_3ch

Die Protokolldefinition habe ich folgendermaßen angepasst:

    "37" =>	## Bresser 7009994
			# MU;P0=729;P1=-736;P2=483;P3=-251;P4=238;P5=-491;D=010101012323452323454523454545234523234545234523232345454545232345454545452323232345232340;CP=4;
			# MU;P0=-790;P1=-255;P2=474;P4=226;P6=722;P7=-510;D=721060606060474747472121212147472121472147212121214747212147474721214747212147214721212147214060606060474747472121212140;CP=4;R=216;
			# short pulse of 250 us followed by a 500 us gap is a 0 bit
			# long pulse of 500 us followed by a 250 us gap is a 1 bit
			# sync preamble of pulse, gap, 750 us each, repeated 4 times
     	 {   
       		name			=> 'Bresser 7009994',		
       		id          	=> '37',
			one				=> [2,-1],
			zero			=> [1,-2],
			start		 	=> [3,-3,3,-3],
			clockabs   		=> '250',		
			format     		=> 'twostate',  		# not used now
			preamble		=> 'W37#',				# prepend to converted message	
			clientmodule    => 'SD_WS', 
			length_min      => '40',
			length_max      => '40',
    	},

Der Eintrag für Protokoll 34 (u34) kann meiner Meinung nach damit entfernt werden.

Die Dekodierung im Modul 14_SD_WS.pm habe ich um eine Checksummenprüfung und das Batteriebit ergänzt. Die Berechnung der Temperatur erschien mir etwas "abenteuerlich" und habe sie korrigiert.

	if ($protocol eq "37") {		# Bresser 7009994
		# Protokollbeschreibung:
		# https://github.com/merbanan/rtl_433_tests/tree/master/tests/bresser_3ch
		# The data is grouped in 5 bytes / 10 nibbles
		# ------------------------------------------------------------------------
		# 0         | 8    12   | 16        | 24        | 32
		# 1111 1100 | 0001 0110 | 0001 0000 | 0011 0111 | 0101 1001 0  65.1 F 55 %
		# iiii iiii | bscc tttt | tttt tttt | hhhh hhhh | xxxx xxxx
		# i: 8 bit random id (changes on power-loss)
		# b: battery indicator (0=>OK, 1=>LOW)
		# s: Test/Sync (0=>Normal, 1=>Test-Button pressed / Sync)
		# c: Channel (MSB-first, valid channels are 1-3)
		# t: Temperature (MSB-first, Big-endian)
		#    12 bit unsigned fahrenheit offset by 90 and scaled by 10
		# h: Humidity (MSB-first) 8 bit relative humidity percentage
		# x: checksum (byte1 + byte2 + byte3 + byte4) % 256
		#    Check with e.g. (byte1 + byte2 + byte3 + byte4 - byte5) % 256) = 0
		$model = "SD_WS37_TH";
		$SensorTyp = "Bresser 7009994";
		my $checksum = (SD_WS_binaryToNumber($bitData,0,7) + SD_WS_binaryToNumber($bitData,8,15) + SD_WS_binaryToNumber($bitData,16,23) + SD_WS_binaryToNumber($bitData,24,31)) & 0xFF;
		if ($checksum != SD_WS_binaryToNumber($bitData,32,39)) {
			Log3 $name, 3, "$name: SD_WS37 ERROR - checksum $checksum != ".SD_WS_binaryToNumber($bitData,32,39);
			return "";
		} else {
			Log3 $name, 4, "$name: SD_WS37 checksum ok $checksum = ".SD_WS_binaryToNumber($bitData,32,39);
			$id = SD_WS_binaryToNumber($bitData,0,7);
			$id = sprintf('%02X', $id);           # wandeln nach hex
			$bat = int(substr($bitData,8,1)) eq "0" ? "ok" : "low";		# Batterie-Bit konnte nicht geprueft werden
			$channel = SD_WS_binaryToNumber($bitData,10,11);
			$rawTemp = 	SD_WS_binaryToNumber($bitData,12,23);
			$hum = SD_WS_binaryToNumber($bitData,24,31);
			my $tempFh = $rawTemp / 10 - 90;							# Grad Fahrenheit
			$temp = (($tempFh - 32) * 5 / 9);							# Grad Celsius
 			$temp = sprintf("%.1f", $temp + 0.05);						# round
			Log3 $name, 4, "$name: SD_WS37 tempraw = $rawTemp, temp = $tempFh F, temp = $temp C, Hum = $hum";
			Log3 $name, 4, "$name: SD_WS37 decoded protocol = $protocol ($SensorTyp), sensor id = $id, channel = $channel";
		}
	}

Ich hänge noch die beiden Programmteile in Textform an:
[SD_WS37_sensor.txt](https://github.com/RFD-FHEM/RFFHEM/files/1309072/SD_WS37_sensor.txt)
[SD_WS37_decod.txt](https://github.com/RFD-FHEM/RFFHEM/files/1309073/SD_WS37_decod.txt)

**Comment by elektron-bbs** [comment]
Der Eintrag 34 in dem Array ProtocolListSIGNALduino sollte noch entfernt werden, sonst kommt es immer zu folgenden Einträgen im Log:

2017.09.23 20:02:48 3: sduinoIP: Unknown code u34#0F35E83E6A, help me!
2017.09.23 20:06:45 3: sduinoIP: Unknown code u34#0F35E63E68, help me!
2017.09.23 20:09:23 3: sduinoIP: Unknown code u34#0F35E53E67, help me!
2017.09.23 20:10:42 3: sduinoIP: Unknown code u34#0F35E53E67, help me!
2017.09.23 20:12:01 3: sduinoIP: Unknown code u34#0F35E53E67, help me!
2017.09.23 20:14:39 3: sduinoIP: Unknown code u34#0F35E43F67, help me!

Die Protokolldefinitionen 34 und 37 sind identisch bis auf clockabs und start.

**Comment by elektron-bbs** [comment]
Wenn die Protokolldefinition "unknown34" entfernt würde, könnten wir sicher auch dieses Thema schließen. Ich muss das Protokoll 34 jedenfalls immer in die Blacklist nehmen, um o.g. Einträge im Log zu vermeiden.

**Comment by sidey79** [comment]
wir könnten developid setzen

**Comment by elektron-bbs** [comment]
Das wäre eine Möglichkeit, aber warum willst du ungenutzte Definitionen weiter mitschleppen, wenn sie nicht mehr gebraucht werden?
Die Definitionen sind identisch bis auf die doppelte Startsequenz bei u34. Der Sensor sendet diese zwar zweimal (sync preamble of pulse, gap, 750 us each, repeated 4 times), aber der SIGNALduino bekommt diese aber nicht immer komplett ausgewertet. Deshalb habe ich mich für nur 2 entschieden. Damit funktioniert der Empfang zuverlässiger.

    "34" =>
     	 {   
       		name			=> 'unknown34',		
       		id          	=> '34',
			one				=> [2,-1],
			zero			=> [1,-2],
			start			=> [3,-3,3,-3,3,-3,3,-3],
			clockabs   		=> '240',		
			format     		=> 'twostate',  		# not used now
			preamble		=> 'u34#',				# prepend to converted message	
			postamble		=> '',					# Append to converted message	 	
			#clientmodule    => '',      			# not used now
			#modulematch     => '',     			# not used now
			length_min      => '40',
			length_max      => '40',
    	},
    "37" =>	## Bresser 7009994
     	 {   
       		name			=> 'Bresser 7009994',		
       		id          	=> '37',
			one				=> [2,-1],
			zero			=> [1,-2],
			start		 	=> [3,-3,3,-3],
			clockabs   		=> '250',		
			format     		=> 'twostate',  		# not used now
			preamble		=> 'W37#',				# prepend to converted message	
			clientmodule    => 'SD_WS', 
			length_min      => '40',
			length_max      => '40',
    	},
