### ISSUE TITLE
RFR Router / Repeater Signalduino

### ISSUE THREAD

**Issue by Honkerr** [RFD-FHEM/RFFHEM#179]
Hi

Ich habe zuhause sehr dicke Wände und meine Reichtweite ist mehr als bescheiden. Mir kam dabei die Idee ob es nicht möglich ist ähnlich wie beim CUL eine RFR Router / Repeater funktion einzubauen?

https://wiki.fhem.de/wiki/RFR_CUL

Ich habe habe im Code etwas dazu gefunden, gibt es sowas vielleicht schon?

```
  if($hash->{TYPE} eq "SIGNALduino_RFR") {
    # Prefix $msg with RRBBU and return the corresponding SIGNALduino hash.
    ($hash, $msg) = SIGNALduino_RFR_AddPrefix($hash, $msg); 
}
```

**Comment by sidey79** [comment]
Aktuell gibt es keinen repeater.

Spricht etwas dagegen  einfach mehrere Signalduino Devices im Haus zu verteilen?

**Comment by Honkerr** [comment]
Okay verstehe. Leider funktioert der RFR_Cul ja nicht mit Intertechno.

Naja das Problem was ich dann habe ist das das ding ja nicht einfach an einen usb netzteil stecken kann und fertig. Ich müsste ja einen raspberry kaufen und den Signalduino anstecken und die daten dann irgendwie an meinen FHEM übertragen. Da brauch ich ja auch wieder WLAN/LAN an dieser stelle wo der zweite Signalduino hängt plus einen übertriebenen Raspi für diesen kleinen zweck :(

Oder gibt es andere Möglichkeiten?

**Comment by sidey79** [comment]
Für den Fall, dass bereits alles mit WLAN ausgeleuchtet ist, wäre folgendes meine Idee:

Signalduino seriell an einen ESP hängen. Den ESP gibt es Ser2Net oder so ähnlich. Das überträgt die Daten dann über WLAN.

Vom Prinzip kann man den ESP auch als Signalduino kaufen lassen (SignalESP). Da bin ich aber noch nicht ganz fertig.

**Comment by Honkerr** [comment]
Danke für deine Antworten!

WLAN hätte ich an dieser Stelle nur bedingt. Das fällt für mich auch raus an dieser stelle. Finde einfach keine gute Lösung zum selber basteln in dieser ganzen Geschichte. Ein RFR Cul wäre wie gemacht dafür aber leider kann das teil nicht mit IT.
Da bleibt einen ja am Ende doch wieder nur die Möglichkeit sehr teure Sensoren/Aktoren zu kaufen für die es schon etwas gibt. Zum selber programmieren fehlt mir allerdings absolut das Wissen, meinen allergrößten Repsekt an alle.

Man bräuchte irgendwie etwas das die IT Signale auffängt und einfach weiter broadcastet.

**Comment by pejonp** [comment]
Hast du einen LAN Anschluss in der Nähe . Da gibt es was komme jetzt aber schlecht an die Daten. Info kommt am Wochenende.

**Comment by Honkerr** [comment]
LAN habe ich da auch nicht :(
Das Haus ist fertig gebaut und Kabel verlegen wird schwer. WLAN Bis dorthin repeaten macht halt auch wenig sinn

**Comment by pejonp** [comment]
es gibt doch PowerLan-Adapter (Lan über Stromnetz) vielleicht hilft das weiter. Ich denke das die Signale duch den Repeater nicht besser werden, eher werden noch mehr Störungen eingebaut und der Aufwand ist zu hoch, da ja jedes empfangene Signal 1:1 weitergesendet werden sollte/müßte wenn man für die Zukunft offen bleiben möchte.

**Comment by Ralf9** [comment]
hier ist eine Info zum LAN und WLAN Anschluss:
https://forum.fhem.de/index.php/topic,69042.msg605241.html#msg605241

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
