### ISSUE TITLE
update force  in dev-cresta does not work

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#18]
Nach Aufruf von:

update force https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-cresta/controls_signalduino.txt

erscheint folgende Ausgabe

RMDIR: ./restoreDir/2015-08-28 
UPD FHEM/00_SIGNALduino.pm
 
https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-cresta/FHEM/00_SIGNALduino.pm
: empty file received

**Comment by hjgode** [comment]
Welchen SVN client verwendest Du?

Unter Debian 8, mit svn 1.8.10 bekomme ich folgende Ausgabe zu svn info:

hgode@aoa150:~/Documents/perl/dev-cresta$ svn info
Path: .
Working Copy Root Path: /home/hgode/Documents/perl/dev-cresta
URL: https://github.com/RFD-FHEM/RFFHEM/branches/dev-cresta
Relative URL: ^/branches/dev-cresta
Repository Root: https://github.com/RFD-FHEM/RFFHEM
Repository UUID: 2cfc220e-7866-e341-06ff-ce57b7db7bff
Revision: 118
Node Kind: directory
Schedule: normal
Last Changed Author: sidey79
Last Changed Rev: 118
Last Changed Date: 2015-09-05 00:28:43 +0200 (Sat, 05 Sep 2015)

Da sieht man, dass ich nicht den main trunk sondern den Branch Zweig
dev-cresta verwende.

Und svn update --force gibt bei mir:

hgode@aoa150:~/Documents/perl/dev-cresta$ svn update --force
Updating '.':
UU   FHEM/00_SIGNALduino.pm
UU   FHEM/14_Cresta.pm
UU   controls_signalduino.txt
Updated to revision 126.

Sieht OK aus.

~Josef

**Comment by sidey79** [comment]
Hi,

das Problem habe ich nicht aus dem SVN Client, sondern bei Update force aus FHEM.

Ich vermute da gibt es ein Berechtigungsproblem.

**Comment by sidey79** [comment]
Lag daran, dass tortoisegit automatisch das lf durch ein crlf in der controls datei ausgetauscht hat.
