### ISSUE TITLE
Schreibweise Protokollbeschreibung bei dazugehöriger langer Pause im Signal

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#180]
Wie muss die richtige Definition lauten, wenn ein Signal Bsp: 0121212121212121212121212341212341212121212341212341234341212341212121212121212123412341212343412121212121212121212123434343434343412341**5**12121212121212121212121234121234121212121234121234123434121234121212121212121212341234121234341212121212121212121212 ausschaut und SIGNALduino das Signal splittet.

Die Zeiten des Protokolls sind bekannt und auch richtig definiert.
Einziger Haken, ich erhalte mindestens 2 Stückelungen weil die Pause von ca 9000 das Signal trennt.

one         	=> [1.5,-1.5],	# 600
zero         	=> [1,-1],	# 400
clockabs    => 400,

1) Die Schreibweise mit sync => XXX wurden getestet aber brachten kein Erfolg oder 
ich machte einen Fehler.
2) Funktioniert die sync => XXX Definition in allen Protokollen MC MU MS?

Es wäre schön, wenn ich in der Sache dazulernen könnte ;-)

MfG

**Comment by sidey79** [comment]
Den Parameter sync gibt es nur bei MS Protokollen.
Wie wird das ganze denn vom Signalduino übergeben?

**Comment by HomeAutoUser** [comment]
Wie meinst du deine Frage?

Vom Signalduino wird das interprätierte Signal "normal" weiter verarbeitet. (so wie ich es definierte)
Im explizieten Fall wäre im Langen Signal das selbige Signal noch einmal vorhanden nur ohne Checksumme. Da die Pause bei dem MU Signal der Signalduino als Pause definiert, so ist der 2. Teil des Signales (gleiche Bitreihenfolge wie im ersten Teil) eine neue "Message" welche aber unter Umständen genau in eine andere Definition passt. Das Ganze könnte man unterscheiden, wenn wir es hinbekämen, das lange Signal zu nutzen. Der Nachteil der Splittung gegenüber des realen 1 Signal ist auch die 2-fache verarbeitung, doppelter Logeintrag und somit auch jeweils MSG-Counter + 2 anstatt eins. 

Bsp: Signal in etwa so (auf die schnelle herbeigesucht)
MU;P0=-32001;P1=392;P2=-8398;P4=-395;P5=611;P6=-607;D=012121212121212121212121234121234121212121234121234123434121234121212121212121212341234121234341212121212121212121212343434343434341234151212121212121212121212123412123412121212123412123412343412123412121212121212121234123412123434121212121212121212121;CP=1;R=27;

P2 ist einmal vertreten in der Mitte was somit die Message splittet. Alles als eins wäre besser.

Hauptgrund der Frage ist, das bei Verarbeitung des langen Signals, man die "Fehlintepretation" des Signales somit minimieren könnte.

**Comment by HomeAutoUser** [comment]
Hier hast du mal vorab Signale

MU;P0=-29016;P1=386;P3=612;P4=-615;P6=-386;P7=-8948;D=
MU;P0=-388;P1=152;P2=-609;P3=112;P5=406;P6=610;P7=-8952;D=
MU;P0=-12448;P1=398;P2=-397;P3=614;P4=-616;P5=-8928;D=

Ich werde unabhängig davon noch 2 - 3 komplette Messages bereitstellen. Die Nachrichtensignale muss ich aber am anderen System aufnehmen da die o.g. aus dem FHEM entnommen wurden nach der Einbindung.

----

Message splitten ist wie folgt gemeint.
In den o.g. Daten welche so lang sind, gibt es eine einzige Pause. Bei all den Zahlen sieht man diese meist schlecht ;-) Bezogen auf das Signal, es wird mit 126 Bit übertragen. Nach dem 67, erfolgt eine wiederholung des Signales nur ohne Checksumme. 

**_"Darstellung aufgeteilt"_** (ein Signal -> 5 ist die Pause)
0
121212121212121212121212341212341212121212341212341234341212341212121212121212123412341212343412121212121212121212123434343434343412341
5
12121212121212121212121234121234121212121234121234123434121234121212121212121212341234121234341212121212121212121212

Das definierte Protokoll FHT80b welches das genau ist, wird im ersten Teil dekodiert und auch umgesetzt ABER unmittel nach der "Pause" wenn der 2. Teil folgt, wird das Signal ebenso als eine neue Message erkannt aber ohne Plausiblitätsprüfung weil diese nur im 1. Teil der Nachricht vorhanden ist.

Erfahrungen im Testlauf zeigen, es funktioniert ABER da das FHTTK Protokoll ähnlich lang ist und in dem 2. Teil keine Checksumme übertragen wird, so kann es vorkommen, das ein FHT80b als [FHTTK erkannt ](https://github.com/RFD-FHEM/RFFHEM/pull/174#issuecomment-332319888)wird. Wenn man nun die Realisierung hinbekäme, dann kann man 2 Fehlerquellen minimieren.

**Comment by sidey79** [comment]
Okay, es geht darum, das in FHEM aus dem Signal zwei Übertragungen gemacht werden.
Tia, aktuell funktioniert das so, dass so lange demoduliert wird, bis eine Pegeldauer gefunden wir die entweder start entspricht oder keiner bekannten Sequenz von one oder zero.
Die lange pause ist ja auch ganz sicher eine pause und gehört nicht zu der eigentlichen Nachricht.

Eine gute Lösung, die beide zu verarbeiten fällt mir spontan nicht ein.

Grüße Sidey

**Comment by HomeAutoUser** [comment]
@sidey79 

> Die lange pause ist ja auch ganz sicher eine pause und gehört nicht zu der eigentlichen Nachricht.

[Falsche Vermutung. Mehr dazu hier. Es ist eine Pause IM Signal und KEINE Pause nach einem Signal ;-)](
https://github.com/RFD-FHEM/RFFHEM/issues/111)

**Comment by sidey79** [comment]
Vielleicht habe ich Tomaten auf den Augen, in der von dir verlinkten seite steht:

0: 400µs High, 400µs Low 600-1000µs Periodendauer
1: 600µs High, 600µs Low 1000-1450µs Periodendauer

Eine Pegeldauer von 8000-9000 sieht für mich als Pause zwischen den Wiederholungen aus.
