### ISSUE TITLE
Befehl für "Signalsimulation"

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#182]
Ist es machbar oder gibt es einen Weg, dem SIGNALdunino ein Signal zu simmulieren, ähnlich dem 
dispatch Befehl? 

> ({ Dispatch($defs{sduino}, "sE26CC0007000", undef) })

Meine Vorstelung wäre, ähnlich diesem Schema 

> MU;P1= xxx ;P2= xxx ;P3= xxx ;P4=xxx ;P5=xxx ;D=xxxx

etwas zu simmulieren um besser testen bzw. mitwirken zu können.

MfG

**Comment by pejonp** [comment]
Schau mal ab hier 
https://forum.fhem.de/index.php/topic,58397.msg656090.html#msg656090

**Comment by HomeAutoUser** [comment]
Vielen Dank, werde ich sofort mal testen.

**Comment by Ralf9** [comment]
ich mache es mit einem dummy sduino

```
define sduinoD SIGNALduino none
attr sduinoD dummy 1
attr sduinoD verbose 5
```
Zum simulieren dann
get sduinoD raw
