### ISSUE TITLE
ID 72, Siro (motorisierte Innensichtschutzrollos)

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#183]
Beim Siro Protokoll gibt es auch das Problem, daß MU Nachrichten ab und zu als MC Nachrichten erkannt werden.
Für mich sieht es so aus als wären es MS Nachrichten die, wenn der sync am Anfang fehlt, auch als MU erkannt werden.

https://forum.fhem.de/index.php/topic,77282.msg692288.html#msg692288
https://forum.fhem.de/index.php/topic,77167.0.html

Die MS und MU Nachtrichten ergeben nach dem demodulieren die selbe dmsg
```
2017.09.30 19:41:39.549 4 : sduinoD/msg get raw: MS;P0=4798;P1=-1531;P3=337;P4=-759;P5=682;P6=-411;P7=-9219;D=3701345634565634565634563434343434563456565634343434563434343434345634343456565656;CP=3;SP=7;R=49;O;
2017.09.30 19:41:39.550 4 : sduinoD: Matched MS Protocol id 72.1 -> Siro shutter
2017.09.30 19:41:39.550 4 : sduinoD: Decoded MS Protocol id 72.1 dmsg P72#5B4170811E length 40 RSSI = -49.5

2017.09.30 19:43:27.563 4 : sduinoD/msg get raw: MU;P0=-408;P1=348;P2=-749;P3=684;P4=-9196;P5=4800;P6=-1512;D=01230301230301230121212121230123030301212121230121212121212301212123030303014561230123030123030123012121212123012303030121212123012121212121230121212303030301;CP=1;R=55;
2017.09.30 19:43:27.563 4 : sduinoD: Fingerprint for MU Protocol id 72 -> Siro shutter matches, trying to demodulate
2017.09.30 19:43:27.563 5 : sduinoD: Starting demodulation at Position 79
2017.09.30 19:43:27.563 4 : sduinoD: decoded matched MU Protocol id 72 dmsg P72#5B4170811E length 40 RSSI = -46.5
```

**Comment by sidey79** [comment]
Bezüglich Siro hatte mich der Nutzer Dr. Smag angeschrieben, ob ich es einbaue.

Ich habe da aber noch einige Fragen, die noch nicht beantwortet sind. So ganz in Ordnung scheint mir die Definition nicht zu sein.

**Comment by elektron-bbs** [comment]
Hallo @Ralf9 , ich denke, du hast das richtig erkannt. Wie ich schon im [Forum](https://forum.fhem.de/index.php/topic,77282.msg692577.html#msg692577) erläutert hatte, beginnt bei dem Siro-Protokoll ein Datenpaket immer mit einem relativ langen Sync-Puls von 5000mS High, 1500mS Low. Das sollte dann folglich immer als MS erkannt werden. Die Wiederholungen (beginnend immer mit diesem Sync-Puls) erfolgen jeweils nach einer Pause von 9000mS.

Bei FS20 gibt es keinen Sync-Puls. Dort beginnt die Übertragung mit einer Präambel, bestehend aus 12 Nullen (400mS High, 400mS Low). Was ihr als "sync" bezeichnet, ist bei FS20 einfach eine Pause von 10 mS (Low-Pegel) zwischen zwei Datenpaketen. Ein Beginn einer Sendung kann bei OOK ja niemals mit Low beginnen. Dieses Protokoll sollte dann eigentlich immer als MU definiert werden.

Das Problem ist, das der SIGNALduino sich unter anderem bei diesen beiden Protokollen nicht eindeutig zwischen MC, MS und MU entscheiden kann. Ich habe fast den Eindruck, das das immer bei Überlauf des Empfangs-Puffers passiert. Kann es sein, das dabei Variablen überschrieben werden, oder ein Interrupt etwas durcheinander bringt?

**Comment by sidey79** [comment]
@elektron-bbs 

Es gibt irgendein Problem, beim verschieben im Puffer, danach kann das System hängen bleiben.
Das steht aber eher nicht im Zusammenhang mit MC, MS oder MU Erkennung.

**Comment by Ralf9** [comment]
Wenn ich das richtig überblicke, dann werden nur bestimmte sync als MS erkannt.
Ein clock gefolgt von einem sync.
Der sync wird wie folgt geprüft:
`(syncabs < 17000 && syncabs / pattern[clock] <= 39) && (syncabs > 6*pattern[clock])`

**Comment by HomeAutoUser** [comment]
@sidey79 
wie kann man dem Problem 

> Es gibt irgendein Problem, beim verschieben im Puffer, danach kann das System hängen bleiben.

auf den Grund gehen?

**Comment by sidey79** [comment]
@ralf

genau so ist es

@homeAutoUser
Ich habe ein unit Test, mit der ich die Libs teste. Vermutlich muss ich die Tests erweitern um den Fehler zu finden.
leider weiss ich noch nicht, welche Konstellation zu dem Fehlverhalten führt.
Debuggen ist leider auch nicht so simpel.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
