### ISSUE TITLE
Protokoll für Rossmann Funk-Außensteckdose

### ISSUE THREAD

**Issue by Nolbeltsan** [RFD-FHEM/RFFHEM#188]
Moin,
habe einen Standard Signalduino nanoCC1101 433MHz.

Genannte Funksteckdose wird gerade bei Rossmann billigst verkauft. Sie ist originär von Intertek, es werden auch sporadisch IT-Befehle erkannt, aber wirklich nur sporadisch, und auch nicht immer dieselben. Habe die 8 Tasten der Fernbedienung nacheinander mehrfach gedrückt, nach folgendem Muster:
- 20s lang mehrfach die Taste kurz gedrückt mit ca. 2s Pause dazwischen
- 5s lang die Taste festgehalten
- 5s Pause
Das ganze 8 Mal nacheinander für alle 8 Tasten: Kanal1 links (an), Kanal1 rechts (aus), Kanal2 links (an), usw.. Im Anhang die zugehörigen Logs, schon getrennt nach Tasten. Ist doch bestimmt nur eine Protokollvariante, die sich schnell dem IT-Protokoll beibringen lässt, oder?

Es werden 8 Devices angelegt, aber kaum Befehle erkannt (siehe auch Logfile), nur bei 2 Tasten, die anderen logs sind leer:

-rw-r--r-- 1 fhem root   **0** Okt 11 20:34 IT_1527xb13d5-2017.log
-rw-r--r-- 1 fhem root **111** Okt 11 20:34 IT_1527xb4091-2017.log
-rw-r--r-- 1 fhem root   **0** Okt 11 20:35 IT_1527xb98a2-2017.log
-rw-r--r-- 1 fhem root   **0** Okt 11 20:35 IT_1527xb3e5e-2017.log
-rw-r--r-- 1 fhem root   **0** Okt 11 20:35 IT_1527xb0a80-2017.log
-rw-r--r-- 1 fhem root   **0** Okt 11 20:36 IT_1527xb572c-2017.log
-rw-r--r-- 1 fhem root   **0** Okt 11 20:37 IT_1527xb2549-2017.log
-rw-r--r-- 1 fhem root  **37** Okt 11 20:38 IT_1527xb7103-2017.log

[Rossmann-Steckdose.log](https://github.com/RFD-FHEM/RFFHEM/files/1379564/Rossmann-Steckdose.log)

Danke!!!

**Comment by HomeAutoUser** [comment]
Guten Abend @Nolbeltsan,

lange ist dein Post her.
Wir versuchen hier ein wenig "Ordnung zu schaffen" und möchten auch diesen Faden prüfen.

Deine damalige Meldung umfasst die Decodierung deines Aktors mit dem SIGNALduino.
Wie ist der Stand aktuell? Wird dein Aktor decodiert / verarbeitet?

Über eine Rückmeldung würden wir uns freuen.
MfG

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
