### ISSUE TITLE
FS20 und FHT

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#194]
Ich bin gerade beim Einbau der Senderoutinen für das FS20-Protokoll. Laut Protokollbeschreibung und auch durch eigene Ermittlung mit einer Fernbedienung FS20 S20 wird ein Datenpaket gesendet und zweimal wiederholt, unterbrochen von jeweils einer Pause von 10 mSek. Ich habe jetzt versucht mit folgendem Befehl zu senden:

$newmsg .= "0#R3";
IOWrite($hash, 'sendMsg', $newmsg);                                     # send SIGNALduino

Dabei wird offensichtlich ohne Pause zwischendurch gesendet und ein CUL an einem Raspberry detektiert das nicht.
Beholfen habe ich mir dann erst einmal mit folgender Lösung:

$newmsg .= "0#R1";
IOWrite($hash, 'sendMsg', $newmsg);                                     # send SIGNALduino
IOWrite($hash, 'raw', 'SR;R=1;P0=-10000;D=0;');
IOWrite($hash, 'sendMsg', $newmsg);                                     # send SIGNALduino
IOWrite($hash, 'raw', 'SR;R=1;P0=-10000;D=0;');
IOWrite($hash, 'sendMsg', $newmsg);                                     # send SIGNALduino

Auf diese Art werden die Befehle vom CUL einwandfrei empfangen. Andere Empfänger zum Test stehen mir leider nicht zur Verfügung. Für eigene Tests hänge ich die Datei schon mal vorab an.
[10_FS20.zip](https://github.com/RFD-FHEM/RFFHEM/files/1483048/10_FS20.zip)

Frage: Gibt es mittlerweile eine Option, dem SIGNALduino mitzuteilen, das er eine Pause zwischen den Wiederholungen lassen soll, oder habt ihr eine andere Lösung?

**Comment by Ralf9** [comment]
es gibt in der Protokoldefinition eine "msgOutro", siehe z.B. bei der ID 72

**Comment by elektron-bbs** [comment]
Das funktioniert nicht. msgIntro und msgOutro wird offensichtlich nur bei Manchester verwendet:

if  ($ProtocolListSIGNALduino{$protocol}{format} eq 'manchester') {
....
my $intro = "";
my $outro = "";
		
$intro = $ProtocolListSIGNALduino{$protocol}{msgIntro} if ($ProtocolListSIGNALduino{$protocol}{msgIntro});
$outro = $ProtocolListSIGNALduino{$protocol}{msgOutro}.";" if ($ProtocolListSIGNALduino{$protocol}{msgOutro});
....
}

**Comment by elektron-bbs** [comment]
Ich habe dem SIGNALduino jetzt eine neue Variable "pause" verpasst:

	"74" => ## FS20 - 'Remote Control (868Mhz),  @HomeAutoUser
		{
			name			   => 'FS20',
			comment        => 'Remote Control (868Mhz)',
			id             => '74',
			developId      => 'y',
			one			   => [1.5,-1.5],    # 600
			zero			   => [1,-1],        # 400
			pause			   => [-25],         # 10000 - NEW - pause between repeats of messages (clockabs*pause must be < 32768 ???)
			clockabs		   => 400,
			clientmodule   => 'FS20',
			preamble		   => '810b04f70101a001',
			length_min		=> '50',
			length_max		=> '67',
			postDemodulation => \&SIGNALduino_postDemo_FS20,
		},

Die Pattern-Schleife habe ich um diese Variable erweitert:

		foreach my $item (qw(sync start one zero float pause))

und hänge dann anschließend wenn $repeats > 1 an $SignalData den Wert an:

		my $SignalData="D=";
		
		$SignalData.=$signalHash{sync} if (exists($signalHash{sync}));
		$SignalData.=$signalHash{start} if (exists($signalHash{start}));
		foreach my $bit (@bits)
		{
			next if (!exists($bitconv{$bit}));
			#Log3 $name, 5, "encoding $bit";
			$SignalData.=$signalHash{$bitconv{$bit}}; ## Add the signal to our data string
		}
		if ($repeats > 1) {
			$SignalData.=$signalHash{pause} if (exists($signalHash{pause}));
		}

Aus dem Modul 10_FS20.pm kann ich jetzt mit folgendem Befehl senden:

       $newmsg .= "0#R3";            # . $SignalRepeats;
       IOWrite($hash, 'sendMsg', $newmsg);                                     # send SIGNALduino

Auf dem Oszi sehen die Signale jedenfalls gut aus und werden auch anstandslos vom CUL empfangen.
![zwischenablage-1](https://user-images.githubusercontent.com/26026988/33241909-d8d2e306-d2cc-11e7-8a46-40f8df13d312.png)

Können wir das so machen und liege ich mit der Annahme, das die Zeit nicht größer als 32768 sein darf, richtig?

**Comment by sidey79** [comment]
Sieht vom Prinzip gut aus, müssten wir noch Mal mit msgoutro abgleichen, was da der Unterschied ist und ob wir beides brauchen.

Deine Annahme ist richtig, da wir die Werte als Int definiert haben.

**Comment by Ralf9** [comment]
> Ich habe dem SIGNALduino jetzt eine neue Variable "pause" verpasst:

Ich finde dies zu unflexibel. Wie machst Du damit z.B. für FS10 eine Pause von 128ms?

Ein Möglichkeit wäre das msgOutro auch für MS- und MU-Nachrichten einzubauen.

Oder sendmsg um eine Pausenoption zu erweitern. #P würde passen dies ist aber leider schon für die Protocol ID belegt. Eine Möglichkeit wäre #B (break). Es müssten eigentlich ms reichen.

Für eine Pause von 100ms könnte es z.B. so aussehen:
$newmsg .= "0#R3#B100";

**Comment by sidey79** [comment]
Die 128 ms kann man mit seiner Variante doch machen, indem man mehrfach den puls angibt der pausiert werden soll.

**Comment by Ralf9** [comment]
Ja, ok so passt es auch

**Comment by elektron-bbs** [comment]
So wie es aussieht, möchte Rudolf nur ungern etwas an seinem FS20-Modul ändern [Forumsbeitrag](https://forum.fhem.de/index.php/topic,84699.0.html). Ich hatte jetzt die Anpassung zum Senden über den SIGNALduino dort eingebaut.
Meine Frage jetzt: Soll ich besser gleich ein 2. Modul für FS20 schreiben, oder machen wir die Anpassung in der 00_SIGNALduino.pm?

**Comment by sidey79** [comment]
@elektron-bbs 

Als ein eigenes FS20 Modul ist meiner Meinung nach Quatsch.

Die Umwandung im SIGNALDuino Modul zu machen eigentlich auch, aber wenn Rudolf sich weigert bleiben wenig Optionen.

Was genau muss denn umgewandelt werden? Ich habe das noch nicht richtig verstanden.

**Comment by elektron-bbs** [comment]
Das erste Problem betrifft die Parse-Funktion im FS20-Modul. Das FS20-Modul erwartet die Übergabe von Hex-Werten mit Kleinbuchstaben, SIGNALduino liefert diese aber mit großen Buchstaben. Wenn ich das jetzt in der SIGNALduino.pm ändern wollte, gilt das wohl für alle Protokolle - was anderweitig Probleme verursachen könnte. Oder man bastelt eine Ausnahme für FS20 - finde ich aber eigentlich nicht schön.

Das zweite betrifft die Umwandlung des Sendekommandos in der sub FS20_Set. Für den CUL wird ein Hex-String mit
IOWrite($hash, "04", "010101" . $hash->{XMIT} . $hash->{BTN} . $c);     # send CUL
übergeben. SIGNALduino erwartet aber eine Bitfolge, diverse Parameter und das Kommando "sendMsg":
IOWrite($hash, 'sendMsg', $newmsg);		# send SIGNALduino
Auch das könnte man basteln, in dem man die "04", "010101" auswertet.

**Comment by elektron-bbs** [comment]
Ich sehe darin auch kein Problem, aber Rudolf hat wohl Bedenken, warum auch immer.

Die Zeichenfolge "04", "010101" wird in der CUL.pm ausgewertet als Sendekommando für FS20. wenn ich das richtig verstanden habe.

**Comment by sidey79** [comment]
Patche auftrennen und einzeln betrachten. Beim Parse sehe ich gute Argumentationsmöglichkeiten.

Ich wüsste nicht mal, wieso man das überhaupt in die Parse routine so einbaut.

Beim Senden. Hmm ist ja blöd wenn man jetzt CUL.pm Kommandos nachbauen müsste

**Comment by elektron-bbs** [comment]
Scheint halt dort üblich, das Hex in lower case umgewandelt wird. Welchen Vorteil das hat, weiß ich nicht. Vielleicht ist ja in C lower case üblich.

Naja, Konvertierungen zu CUL, Oregon, TCM, TX u.s.w. sind ja schon einige in der SIGNALduino. Ist aber immer noch besser, als alle Module doppelt oder dreifach einzubauen.

**Comment by sidey79** [comment]
Also HEX ist groß oder klein identisch.

Das kann man problemlos patchen. Dazu hat sch Rudolf doch auch überhaupt nicht geäußert.

Den CUL Nachbauen ist meiner Meinung nach der Falsche Ansatz. Er wollte ja nur wissen, ob es mehr Aufwand ist das im signalduino einzubauen,

**Comment by elektron-bbs** [comment]
Jo, wenn ich aber dann den String vergleiche, ist es nicht mehr identisch.

Ich habe jetzt nochmal im Forum dazu geschrieben, mal sehen, wie die Reaktion ist.

**Comment by elektron-bbs** [comment]
So wie es aussieht, lässt sich Rudolf nicht davon überzeugen, irgendwelche Änderungen im FS20-Modul vorzunehmen [Forum](https://forum.fhem.de/index.php/topic,84699.0.html). Ich hatte die Anpassungen auch zum Senden eigentlich schon fertig 
[10_FS20.zip](https://github.com/RFD-FHEM/RFFHEM/files/1800195/10_FS20.zip). Nun müssen wir wohl sehen, das wir das in der SIGNALduino.pm unterbringen :-(

**Comment by Ralf9** [comment]
Ich habe mal das Senden von FS20 und FHT in die SIGNALduino_Write() eingebaut. Abgeschaut habe ich es von der 00_CUL.pm.
Jetzt fehlen nur noch die SIGNALduino_PreparingSendFS20( und SIGNALduino_PreparingSendFHT(
Ist von Euch auch geplant das Senden vom FHT einzubauen?

```
sub
SIGNALduino_Write($$$)
{
  my ($hash,$fn,$msg) = @_;
  my $name = $hash->{NAME};

  if ($fn eq "") {
    $fn="RAW" ;
  }
  elsif($fn eq "04" && substr($msg,0,6) eq "010101") {   # FS20
    $fn="sendMsg";
    $msg = substr($msg,6);
    $msg = SIGNALduino_PreparingSendFS20($msg);
  }
  elsif($fn eq "04" && substr($msg,0,6) eq "020183") {   # FHT
    $fn="sendMsg";
    $msg = substr($msg,6,4) . substr($msg,10);     # was ist der Unterschied zu "$msg = substr($msg,6);" ?
    $msg = SIGNALduino_PreparingSendFHT($msg);
  }
  Log3 $name, 5, "$name/write: sending via Set $fn $msg";
  
  SIGNALduino_Set($hash,$name,$fn,$msg);
}
```

**Comment by sidey79** [comment]
@elektron-bbs 

Ich werde das mit Rudi klären. Das ist meiner Meinung nach nicht wartbar, wenn wir Funktionen des Log. Moduls in das Physische einbauen

**Comment by Ralf9** [comment]
Für mich ist nicht nachvollziehbar warum in der sub FHT_Parse($$) das lowercase eingebaut ist:
```
  $msg = lc($msg);
  my $dev = substr($msg, 16, 4);
  my $cde = substr($msg, 20, 2);
  my $val = (length($msg) > 26 ? substr($msg, 26, 2) : undef);
```

In der sub FS20_Parse aber nicht.

**Comment by elektron-bbs** [comment]
Ich hatte eigentlich vor, das Senden für FHT auch mit einzubauen, habe es mir aber bisher noch nicht genauer angesehen. Es sollte eigentlich kein Problem darstellen, da es das gleiche Protokoll wie FS20 ist. Vielleicht kann man ja sogar SIGNALduino_PreparingSend.... für beide verwenden.

**Comment by Ralf9** [comment]
Ich habe bei mir in der 00_SIGNALduino.pm das Senden von FS20 mal eingebaut.
Ich habe die Routine von @elektron-bbs etwas vereinfacht und optimiert:

```
sub SIGNALduino_PreparingSendFS20 {
	my $msg = shift;
	my $sum = 6;
	my $temp = 0;
	my $newmsg = "P74#0000000000001";	  # 12 Bit Praeambel, 1 bit
	
	for (my $i=0; $i<length($msg); $i+=2) {
		$temp = hex(substr($msg, $i, 2));
		$sum += $temp;
		$newmsg .= dec2binppari($temp);
	}
	
	$newmsg .= dec2binppari($sum & 0xFF);   # Checksum		
	$newmsg .= "0P#R3";            		# EOT, Pause, 3 Repeats    
	
	return $newmsg;
}

sub dec2binppari {      # dec to bin . parity
	my $num = shift;
	my $parity = 0;
	my $nbin = sprintf("%08b",$num);
	foreach my $c (split //, $nbin) {
		$parity ^= $c;
	}
	my $result = $nbin . $parity;		# bin(num) . paritybit
	return $result;
}
```

**Comment by HomeAutoUser** [comment]
ACHTUNG ! ?

@Ralf9 
>Ich habe bei mir in der 00_SIGNALduino.pm das Senden von FS20 mal eingebaut.

Ralf, du hast dies bei @sidey79 in der 00_SIGNALduino.pm geändert! Uns fällt auf, das auch andere Änderungen auf einmal "heimlich" zurückgeändert wurden. Existiert hier ein Durcheinander?
Auch andere Commits bei @sidey79 wurden durch Ralf hinzugefügt? Ist das richtig ??

**Comment by sidey79** [comment]
Ich verstehe nur Bahnhof.

Ich habe mir einige commits aus Ralfs Fork (welche er als Patches bezeichnet hat) einzeln gezogen und in dev-r33 aufgenommen.

Bei denen ist auch sauber erkennbar, dass sie von Ralf9 kommen.

Fs20 Anpassungen waren da aber glaube ich keine mit dabei.

**Comment by Ralf9** [comment]
Das FS20 senden habe ich vorerst nur in der 00_SIGNALduino.pm lokal bei mir auf dem PC und hier geändert.

**Comment by Ralf9** [comment]
> Vielleicht kann man ja sogar SIGNALduino_PreparingSend.... für beide verwenden.

ich habe mir mal beide Protokolle angeschaut, sie sind sehr ähnlich.
Es müsste sich eigentlich wie folgt zusammenfassen lassen:

```
sub
SIGNALduino_Write($$$)
{
  my ($hash,$fn,$msg) = @_;
  my $name = $hash->{NAME};

  if ($fn eq "") {
    $fn="RAW" ;
  }
  elsif($fn eq "04" && substr($msg,0,6) eq "010101") {   # FS20
    $fn="sendMsg";
    $msg = substr($msg,6);
    $msg = SIGNALduino_PreparingSend_FS20_FHT(74, 6, $msg);
  }
  elsif($fn eq "04" && substr($msg,0,6) eq "020183") {   # FHT
    $fn="sendMsg";
    $msg = substr($msg,6,4) . substr($msg,10);     # was ist der Unterschied zu "$msg = substr($msg,6);" ?
    $msg = SIGNALduino_PreparingSend_FS20_FHT(73, 12, $msg);
  }
  Log3 $name, 5, "$name/write: sending via Set $fn $msg";
  
  SIGNALduino_Set($hash,$name,$fn,$msg);
}
```

```
sub SIGNALduino_PreparingSend_FS20_FHT($$$) {
	my ($id, $sum, $msg) = @_;
	my $temp = 0;
	my $newmsg = "P$id#0000000000001";	  # 12 Bit Praeambel, 1 bit
	
	for (my $i=0; $i<length($msg); $i+=2) {
		$temp = hex(substr($msg, $i, 2));
		$sum += $temp;
		$newmsg .= dec2binppari($temp);
	}
	
	$newmsg .= dec2binppari($sum & 0xFF);   # Checksum		
	$newmsg .= "0P#R3";            		# EOT, Pause, 3 Repeats    
	
	return $newmsg;
}
```

**Comment by Ralf9** [comment]
> Uns fällt auf, das auch andere Änderungen auf einmal "heimlich" zurückgeändert wurden

@HomeAutoUser 
Welche Änderungen/Commits sind dies, die zurückgeändert wurden?

**Comment by elektron-bbs** [comment]
Ich werde das nachher zumindest mit FS20 testen. Für FHT fehlen mir die passenden Regler. Das kann nur @HomeAutoUser

**Comment by elektron-bbs** [comment]
Die Funktion der Variante 2 beim Senden mit der FS20-Fernbedienung kann ich schon mal bestätigen. Es fehlt nur noch die Pause in der Definition:

``

**Comment by Ralf9** [comment]
> Mir war aufgefallen, das in der sub SIGNALduino_OSV1 das invertieren wieder nach der Checksummenprüfung erfolgt. Das hatte @sidey79 meines Erachtens schon mal korrigiert.

Ich habe mal geschaut, ich konnte keinen commit finden wo das Invertieren vor der Checksummenprüfung erfolgt. Ich konnte nur diesen commit finden:
https://github.com/RFD-FHEM/RFFHEM/commit/781465d9079520476573c76d8bd7a9a5f5298ede

**Comment by Ralf9** [comment]
Da sich das Einbauen vom FS20 senden nun seit November hinzieht, würde ich gerne solangsam einen Abschluß reinbringen.
Ist es für Euch ok, wenn ich die o.g. Anpassungen beim dev-r33 von @sidey79 committe, damit eine Grundlage für Kommentare da ist

> Auch andere Commits bei @sidey79 wurden durch Ralf hinzugefügt? Ist das richtig ??

Oder ist es für Euch nicht ok, wenn ich was direkt in die dev-r33 von @sidey79 committe?
Dann könnt Ihr es gerne auch selbst commiten und ich halte mich dann da raus.

**Comment by elektron-bbs** [comment]
Auch ich würde es sehr begrüßen, wenn ich da mal einen Haken dran machen könnte. Wenn du es direkt commitest, erspart mir das die Umstände mit dem Pullrequest. Das ist immer eine ziemliche Bastelei.

**Comment by sidey79** [comment]
@Ralf9 
 Hau rein :)   Wenns dann was nicht geht, ist es halt so.. Dafür ist der dev Branch da.

Ich habe jetzt auch mal PullRequests angefangen zu schließen... Die sind für Kommentare und Abstimmung halt besser geeignet als ein commit, aber hier gab es ja schon viel Austausch. Also bin ich für einen commit.

**Comment by Ralf9** [comment]
https://github.com/RFD-FHEM/RFFHEM/commit/e664ec2e358ea319c6a4406c47b22b01f69c1b23
Das FHT80 senden ist noch ungetestet

**Comment by HomeAutoUser** [comment]
@Ralf9 , nicht das du meine Aussage falsch verstanden hast, ich wollte damit nur zum Ausdruck bringen, das eventuell was verloren ging, was du vielleicht nicht eingebunden hast aber @sidey79 schon hatte. Natürlich ist es gewollt und erwünscht, das du mit zurarbeitest / ergänzt. (Es kann aber auch sein, das bei den vielen Branch´s das @sidey79 in einen anderen nahm und nicht in Dev überführte)

>Hau rein :) Wenns dann was nicht geht, ist es halt so.. Dafür ist der dev Branch da.

Richtig!

>@HomeAutoUser
Welche Änderungen/Commits sind dies, die zurückgeändert wurden?

@elektron-bbs  und mir waren aufgefallen, [das die OSV1 Drehung in der Routine](https://github.com/RFD-FHEM/SIGNALDuino/issues/75#issuecomment-362933551) auf einmal wieder gedreht ist.[ Angedacht war ja auch mal der Hideki 2 mach 1](https://github.com/RFD-FHEM/RFFHEM/pull/215#issuecomment-371286956) (dazu fragte ja @sidey79  auch nochmal damals) Vielleicht kann @elektron-bbs das BITTE mal heraussuchen. Ich selbst bin für ein paar Tage heraus, weil ich mich in der Sonne aale fernab vom PC.

Nachdem ich wieder im Lande bin, so werde ich das FS20 bei den FHT´s testen.

Es muss auch noch ein Test meinerseits gefahren werden mit dem aktuellen Branch, da dieser wieder den THR128 "abschneidet" und diverse "Hideki" Sensoren. Ich deutete dies schonmal an aber mir fehlte bisher die Zeit. ((Vermutlich sind es bei dem Branch Erscheinungen, wenn ein Sensor über "x" Entfernung kommt oder..... Nur wenn mein ein Downgrad macht kommen die beiden Sensoren wieder zuverlässig))

**Comment by Ralf9** [comment]
https://github.com/RFD-FHEM/RFFHEM/commit/e664ec2e358ea319c6a4406c47b22b01f69c1b23

> Ich hatte da gerade noch eine Idee, wie wir die FS20-Fehlermeldung von korrekten FHT-Nachrichten unterbinden können: Einfach auf die Prüfsumme von FHT checken und wenn das passt, die weitere Verarbeitung abbrechen. 

Evtl macht es Sinn, in diesem Fall mit loglevel 5 eine Meldung auszugeben, daß die FS20-Erkennung abgebrochen wurde, da die Prüfsumme auf  FHT passt

**Comment by Ralf9** [comment]
Comment von @elektron-bbs 
Könnte man machen, aber in dem Fall sollten ja dann auch Log-Ausgaben von der sub SIGNALduino_postDemo_FHT80 erfolgen.

**Comment by Ralf9** [comment]
ok, mit dieser Log-Ausgabe in sub SIGNALduino_postDemo_FS20 und SIGNALduino_postDemo_FHT80 wäre es für mich so ok.

@elektron-bbs und @HomeAutoUser 
könnt Ihr dies mal bei Euch so einbauen und testen ob es so wie gedacht funktioniert.
Ich werde es dann in die dev-r33 committen

**Comment by Ralf9** [comment]
ich habe den Titel von diesem Issue gerade umbenannt, ich hoffe dies ist für Euch so ok

**Comment by elektron-bbs** [comment]
>

**Comment by Ralf9** [comment]
Ich dachte es wäre klar wie ich es gemeint habe. Der log Text muß natürlich noch nach Englisch übersetzt werden.
```
  my $checksum = oct( "0b".(join "", @bit_msg[$protolength - 9 .. $protolength - 2]));   # Checksum Byte 5 or 6
  if ((($sum + 6) & 0xFF) == $checksum) {		## Message from FHT80 roothermostat
			SIGNALduino_Log3 $name, 5, "$name: FS20 - Erkennung abgebrochen, da die Prüfsumme auf FHT passt";
			return 0, undef;
  }
  if (($sum & 0xFF) == $checksum) {
```

Ich habe es noch nicht committed, da ich nicht weiß ob Ihr es bei Euch schon getestet habt ob es so wie gedacht bei FS20 und FHT funktioniert.

**Comment by elektron-bbs** [comment]
Bis auf die zusätzliche Log-Ausgabe habe ich das natürlich schon getestet. Die zusätzliche Log-Ausgabe erscheint mir zwar erst mal überflüssig, aber bei Log-Level 5 sieht das ja eh keiner :-)

**Comment by Ralf9** [comment]
Kannst Du mir den Text der zusätzlichen Log-Ausgabe nach Englisch übersetzen?

**Comment by sidey79** [comment]
FS20 - Detektion aborted, crc Matches FHT code

**Comment by Ralf9** [comment]
Bitte mal testen ob es so passt
https://github.com/RFD-FHEM/RFFHEM/commit/a7d4cf263981064ac9c6fc0713a2a26329de3c7a

**Comment by HomeAutoUser** [comment]
Hallo, Frohe Ostern!
Erstmal schauen was hier so alles passierte :-D
2 Wochen weg und schon ist man heraus aus allem.

**Comment by sidey79** [comment]
Hi, frohe Ostern,

ich hab die letzten Tage nichts mehr in dem Bereich gemacht.
Wollte erst mal abwarten was ihr mir für Rückmeldungen gebt.

**Comment by HomeAutoUser** [comment]
Hallo, was den Fadenangeht, auf was soll ich achten bzw. testen? 
Einmal zwecks dem Abbruch der Verarbeitung 
- FS20 - Detection aborted, checksum matches FHT code
- FHT80 - Detection aborted, checksum matches FS20 code

- senden? 

Bin nicht ganz auf den laufenden, denn daher gezielt die Frage worauf ich testen soll :-D

**Comment by elektron-bbs** [comment]
Das auch, aber wichtiger wäre, zu prüfen, ob die Senderoutine mit FHT funktioniert. FS20 habe ich durchprobiert, aber FHT kann ich mangels passenden Reglers nicht ausprobieren.

**Comment by HomeAutoUser** [comment]
Zur kurzen Info @sidey79 und @Ralf9,
das senden im Zusammenhang mit dem FHT geht noch nicht. Heute haben wir dies mal kurz getestet.
Im Befehl fehlt noch etwas. @elektron-bbs schaute dies sich an.

**Comment by elektron-bbs** [comment]
Ich glaube, ich habe den Fehler schon gefunden. Bei FHT muss beim Senden noch ein zusätzliches Byte eingefügt werden. Ich habe das jetzt so gelöst:

  elsif($fn eq "04" && substr($msg,0,6) eq "020183") {   # FHT
		SIGNALduino_Log3 $name, 5, "$name/write: incoming from 11_FHT fn=$fn msg=$msg";
    $fn="sendMsg";
    $msg = substr($msg,6,6) . "00" . substr($msg,12);		# insert Byte 3 always 0x00
    $msg = SIGNALduino_PreparingSend_FS20_FHT(73, 12, $msg);
  }

Außerdem habe ich noch die Anzahl der Wiederholungen korrigiert:

	$newmsg .= dec2binppari($sum & 0xFF);   # Checksum
	my $repeats = $id - 71;									# FS20(74)=3, FHT(73)=2
	$newmsg .= "0P#R" . $repeats;        		# EOT, Pause, Repeats

@Ralf9 

$msg = substr($msg,6,4) . substr($msg,10);     # was ist der Unterschied zu "$msg = substr($msg,6);" ?

**Comment by Ralf9** [comment]
Das
`$msg = substr($msg,6,4) . substr($msg,10); `
habe ich aus der 00_cul.pm. Meiner Meinung nach müsste `$msg = substr($msg,6);` das Selbe machen, war mir aber nicht ganz sicher.

**Comment by Ralf9** [comment]
Ja, die Kommunikation mit dem Regler FHT80b sieht recht komplex aus. 
Die zu sendenden Befehle müssen gepuffert werden.
```
Control the FHT80b. In this mode we have to wait for a message from the
FHT80b, and then send all buffered messages to it, with a strange
ask/reply protocol.
```
https://github.com/heliflieger/a-culfw/blob/master/culfw/clib/fht.c

**Comment by elektron-bbs** [comment]
Wir haben die Kommunikation des FHT80b jetzt mal etwas genauer unter die Lupe genommen. Das größte Problem ist wohl, das der Regler jede Nachricht von der Zentrale, in unserem Fall also FHEM, bestätigt haben will. Wir haben diese Kommunikation hier mal mit einer EZcontrol aufgezeichnet:

![fht80b_ezcontrol](https://user-images.githubusercontent.com/26026988/42133968-3f18d54e-7d22-11e8-9043-54e45cfde047.png)

Wenn die Bestätigung nicht innerhalb von maximal ca. 180 mS empfangen wird, wiederholt der Regler die Nachricht noch einmal und wenn wieder keine Bestätigung erfolgt, wird die Kommunikation beendet. Im umgekehrten Fall (EZcontrol sendet zum Regler) verläuft es auch so, jeder Empfang einer Nachricht muss vom Regler bestätigt werden.

Das Problem ist jetzt, das SIGNALduino/FHEM wahrscheinlich die Bestätigung innerhalb dieser Zeit nicht hinbekommen. Bei einem Test mit SIGNAL-ESP wurde die Bestätigung immer erst so nach ca. 150 bis 180 mS gesendet. Ich habe jetzt keine Vorstellung, ob die Übertragung per WLAN schneller als seriell erfolgt.

Ich habe die Zeiten mal für eine serielle Übertragung durchgerechnet:
ca. 40 mS für den MU-String (allerdings ohne Komprimierung - wieviel bringt die Komprimierung?)
ca. 50 mS bis das Protokoll in FHEM erkannt und für eine Antwort bearbeitet wurde
ca. 23 mS serielle Übertragung des Sendestrings zum SIGNALduino

In Summe macht das knapp 120 mS. Hinzu kommen noch Zeiten für die Verarbeitung im SIGNALduino. Da bringt bereits das Abschalten von MC und MS einiges. Ich schätze, das ist zuviel. Die EZcontrol sendet bereits nach etwa 70 mS die Antwort.

Wie schätzt ihr das ein? Sind die Antwortzeiten irgendwie hinzubekommen?

**Comment by sidey79** [comment]
Mit der Kompression kommt man vermutlich auf 26 ms für den MU String (annahme).

WLAN ansich kann höhere Bandbreiten als die serielle Übertragung. Es kann aber sein, dass gerade ein anderes Gerät sendet und dann stellt sich ein delay ein.

Um das ganze innerhalb der 120 ms zu realisieren müsste man vermutlich einen eigenen decoder dafür Zusätzlich zum MU Decoder einbauen. Alles andere, ist vermutlich zu fehleranfällig, da zu viele Abhängigkeiten.

**Comment by elektron-bbs** [comment]
FS20 ist abgeschlossen, der Empfang des Reglers FHT auch. Das Senden zum Regler ist zu zeitkritisch und deshalb nicht in FHEM realisierbar.
Ich schließe dieses Issue.
