### ISSUE TITLE
Logausgabe in ein Filelog

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#196]
Die Ausgabe von Loginformationen soll auch in eigene Filelogs erfolgen können

**Comment by sidey79** [comment]
@Ralf9 

Ich habe die Logausgaben mal Paralell auch als Events ausgegeben.

```
2017-11-25 00:37:30.621 SIGNALduino sduino 5: sduino: Starting demodulation at Position 7
2017-11-25 00:37:30.655 SIGNALduino sduino 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2017-11-25 00:37:30.670 SIGNALduino sduino 5: sduino: Starting demodulation at Position 7
2017-11-25 00:37:30.687 SIGNALduino sduino 5: sduino: dispatching bits: 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0
2017-11-25 00:37:30.702 SIGNALduino sduino 4: sduino: decoded matched MU Protocol id 8 dmsg TXAE0761061C length 44 RSSI = -74
2017-11-25 00:37:30.717 SIGNALduino sduino 5: sduino Dispatch: TXAE0761061C, test ungleich: disabled
2017-11-25 00:37:30.732 SIGNALduino sduino 5: sduino Dispatch: TXAE0761061C, -74 dB, dispatch
2017-11-25 00:37:30.801 CUL_TX CUL_TX_3 T: 20.1 H: 61.0
2017-11-25 00:37:30.801 CUL_TX CUL_TX_3 humidity: 61.0
2017-11-25 00:37:30.820 SIGNALduino sduino 5: sduino: dispatching bits: 0 0 0 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0
2017-11-25 00:37:30.836 SIGNALduino sduino 4: sduino: decoded matched MU Protocol id 8 dmsg TXAE0761061C length 44 RSSI = -74
2017-11-25 00:37:30.850 SIGNALduino sduino 5: sduino Dispatch: TXAE0761061C, test gleich

```

Das ganze kann natürlich auch in ein Filelog geschrieben werden:
```
2017-11-25_00:37:30 sduino 5: sduino: applying filterfunc SIGNALduino_filterSign
2017-11-25_00:37:30 sduino 4: sduino/msg READ: MU;P0=-1035;P1=200;P2=116;P3=-4920;P4=1272;P5=489;P6=-27706;D=01023204040404050405040505050404040404040505050405050404040405040404040405050404040405050504056404040405040504050505040404040404050505040505040404040504040404040505040404040505050405640404040504050405050504040404040405050504050504040404050404040404050504;CP=5;R=0;O;
2017-11-25_00:37:30 sduino 5: sduino: Starting demodulation at Position 1
2017-11-25_00:37:30 sduino 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2017-11-25_00:37:30 sduino 5: sduino Dispatch: TXA00670170E, -74 dB, dispatch
2017-11-25_00:37:30 sduino 5: sduino Dispatch: TXA00670170E, test ungleich: disabled
2017-11-25_00:37:30 sduino 4: sduino: decoded matched MU Protocol id 8 dmsg TXA00670170E length 44 RSSI = -74
2017-11-25_00:37:30 sduino 5: sduino: dispatching bits: 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1 1 1 0
```


Über ein Zusätzliches Attribut könnte man das verhalten beeinflussen.
Folgende Optionen stelle ich mir vor

1. Attribut ist nicht gesetzt = es erfolgt keine Ausgabe dieser Events
2. Attribut kann mit einem oder mehreren Werten (1-5) gesetzt werden. Es werden die Meldungen mit genau den gesetzten Verbose Level ausgeben.  
1,2,3,5 sollte alles bis auf Verbose 4 als Event ausgeben.

Alternativ könnte man auch eine Regex setzen, vielleicht könnte man auch eine Regex setzen. Das würde es sehr flexibel gestalten.

Das Filelog sollte via autocreate angelegt werden, das habe ich aber noch nicht eingebaut.
Wollte deine Meinung erst mal hören und ein wenig Testen.

**Comment by Ralf9** [comment]
Mir ist der Sinn noch nicht ganz klar, zu was das gut sein könnte für alle log Ausgaben Events erzeugen zu können.
Z.B. die loglevel 5 Ausgaben sind doch überwiegend zum Entwickeln und debuggen gedacht.
Wer entwickelt dürfte doch normalerweise ein Testsystem haben. Da Du das auch benötigst, bedeutet dies, daß Du kein Testsystem hast?

Es gibt bereits das Attribut "rawmsgEvent" (When set to "1" received raw messages triggers events)
Evtl macht auch ein Attribut "rawmsgEventRegex" Sinn.

Es könnte auch Sinn machen bei ausgewählten weiteren logs (wie beim parse die matched, found und decoded Ausgaben) events zu erzeugen.
Eine andere Möglichkeit wäre
Log3 $name, v4, "$name:
Das v4 wäre dann per default auf 4 und man könnte es dann per Attribut z.B. auf 3 setzen.

**Comment by sidey79** [comment]
@Ralf9 

Testsystem habe ich, aber es gab doch bereits mehrfach Anfragen, die Daten in eigene Logs wandern zu lassen.
Das "rawmsgEvent" war in meiner Erinnerung so ein Schnellschuss um das wenigstens mal für die Raw Messages zu implementieren. Der Rest wird aber weiterhin nur mittels Log in das FHEM Log ausgegeben.

Mir ging es jetzt die Tage auch auf den Keks, dass alle Devices in dem gleichen Log landen. Wenn ich mit dem Testen anfange, dann lädt das ja noch schnell, aber gegen Ende hin, dauert es jedes mal 30 Sekunden bis das geladen ist.

Mit den Events, kann man das recht komfortabel sogar heraus filtern, was man möchte. z.B. alle Verbose 3 und 5.. 
Debug läuft jetzt allerdings noch immer ins FHEM Log.

**Comment by HomeAutoUser** [comment]
@sidey79,

1)
Ist diese Möglichkeit schon implemetiert, wenn ja wie funktioniert das genau?
>Das ganze kann natürlich auch in ein Filelog geschrieben werden:

Ich werde aus deiner Erklärung hier nicht "schlau". Ich würde das ganze mal nutzen wollen um vielleicht den THR128 Sachverhalt zu "untersuchen".

----------------
2)
Daraus resultieren ergibt sich auch noch diese Frage.
Da es im Livesystem immer schwer ist, sämtliche Nachrichten zu filtern wenn ein Sensor flasch erkennt wird oder Probleme macht, so habe ich teilweise die Decoder abgeschalten um die puren MU -Nachrichten zu erhalten. Da bei mir einige mehrere Sensoren mit unterschiedlichsten Zeiten senden und es so schwierig ist, diesen einen richtig zu filtern,so kam mit eine Überlegung. Daraus resultierend die Frage hier.

Ist es machbar, die Debugausgabe oder den Loglevel soweit einzugrenzen, das ich bei einer Einstellung des Log´s nur den einen Sensor mit den speziellen Puls Pause Zeiten erhalte und nicht alle?

Ich stelle derzeit Bsp. eine Wihtelist auf 99 welche ID nicht vorhanden ist und so erhalte ich im Log alle RAW Nachrichten. Nun möchte ich davon nur diesen einen Sensor haben mit den beliebigen Zeiten. Bestmöglich natürlich ohne weitere Verarbeitung. So könnte man gezielter auf Fehlersuche nach einer FW Änderung beitragen.

Aus dieser u.g. Auswahl würde ich angenommen nur diese Nachrichten sehen wollen mit den Zeiten von ca. P1=478;P2=-4053;P4=-9078;P5=-2000 ...

>2017.12.05 19:04:57 4: Arduino_Nano_433Mhz/msg READredu: MS;P2=-3898;P3=489;P4=-988;P5=-1957;D=32343535343434353535343434343434343434353535343434353535353434343435343435;CP=3;SP=2;R=223;O;
2017.12.05 19:04:57 4: Arduino_Nano_433Mhz/msg READredu: MS;P0=491;P1=-974;P2=-1945;P3=-3904;D=03010202010101020202010101010101010101020202010101020202020101010102010102;CP=0;SP=3;R=224;O;
2017.12.05 19:04:57 4: Arduino_Nano_433Mhz/msg READredu: MS;P0=491;P1=-978;P2=-1950;P3=-3940;P4=136;D=030102020101010202020101010101010101010202020101010202020201010101020101024;CP=0;SP=3;R=225;
2017.12.05 19:05:03 4: Arduino_Nano_433Mhz/msg READredu: MS;P1=478;P2=-4053;P4=-9078;P5=-2000;D=514121215121515151215121215121215151215121212121515151215151515151512151215;CP=1;SP=4;R=52;O;m=2;
2017.12.05 19:05:04 4: Arduino_Nano_433Mhz/msg READredu: MS;P1=478;P2=-4046;P4=-9065;P5=-2020;D=14121215121515151215121215121215151215121212121515151215151515151512151215;CP=1;SP=4;R=52;O;m=1;
2017.12.05 19:05:04 4: Arduino_Nano_433Mhz/msg READredu: MS;P1=488;P2=-4043;P4=-9056;P5=-2017;D=14121215121515151215121215121215151215121212121515151215151515151512151215;CP=1;SP=4;R=52;O;m=0;
2017.12.05 19:05:04 4: Arduino_Nano_433Mhz/msg READredu: MS;P1=481;P2=-4050;P4=-9056;P5=-2012;D=14121215121515151215121215121215151215121212121515151215151515151512151215;CP=1;SP=4;R=52;
2017.12.05 19:05:06 4: Arduino_Nano_433Mhz/msg READ: Mc;LL=-1018;LH=935;SL=-524;SH=459;D=573B4BA53279F438AA33B10;C=489;L=91;R=57;
2017.12.05 19:05:06 4: Arduino_Nano_433Mhz/msg READ: Mc;LL=-1008;LH=944;SL=-521;SH=461;D=74A24F3E87154654C0;C=488;L=70;R=58;
2017.12.05 19:05:06 4: Arduino_Nano_433Mhz/msg READ: Mc;LL=-1017;LH=946;SL=-522;SH=451;D=573B4BA52279F438AA333C0;C=489;L=91;R=57;
2017.12.05 19:05:10 4: Arduino_Nano_433Mhz/keepalive ok, retry = 0
2017.12.05 19:05:12 4: Arduino_Nano_433Mhz/msg READredu: MS;P1=471;P2=-7929;P3=-2037;P4=-3936;P5=248;D=012131453131414141413131313131413141413131313141413;CP=1;SP=2;R=247;O;m=2;
2017.12.05 19:05:12 4: Arduino_Nano_433Mhz/msg READredu: MS;P1=459;P2=-7938;P3=-2041;P4=-3934;D=12131413131414141413131313131413141413131313141413;CP=1;SP=2;R=247;O;m=1;

Ist das derzeit möglich zu filtern oder könnte man das ggf. irgendwie "einbauen"? Somit sollte es vielleicht leichter fallen für beteiligte Entwickler mehr Erkenntnisse zusammen zu tragen.

MfG

**Comment by sidey79** [comment]
@HomeAutoUser 
Ich dachte ich hätte es committet aber scheinbar habe ich das nicht. Meine Implementeriung ist nun weg :(

Zu 2.
Auf einen Sensor kann man im SIGNALduino schlecht filtern, der Sensor ist ja dem SIGNALduino nicht bekannt. Erst nach einigen Prüfungen übergeben wir die Daten an ein Modul, welches die Daten einem Sensor zuordnen kann.

**Comment by HomeAutoUser** [comment]
@sidey79 

zu 2)
Das ist mir bewusst. Könnte man etwas "schaffen" wo man wie einen Puls Pausen Filter setzen könnte um nur diese Nachrichten zu finden?

>Ich dachte ich hätte es committet aber scheinbar habe ich das nicht. Meine Implementeriung ist nun weg :(

Vielleicht kann man dies ja erneut finden bzw. implementieren.

**Comment by Ralf9** [comment]
ich würde das mit dem log und filelog erstmal hinten anstellen.
Ich finde es momentan wichtiger, wenn erstmal der MC-Decoder richtig funktioniert.

**Comment by HomeAutoUser** [comment]
@Ralf9 
keine Frage, da stimme ich dir zu!
Ich lasse ja schon eben wieder die FW laufen um Erkenntnisse zu sammeln und zu testen ;-)

Generelle Frage, @sidey79 / @Ralf9 würde es dir was helfen, wenn man dir ggf. den oder die Sensoren zuschicken würde und du sie selbst vor Ort zum testen hast? Nach dem Motto, so lange bis es eine eindeutige und keine mehrdeutige Erkennung ist ?

**Comment by HomeAutoUser** [comment]
@sidey79, die wenigen Minuten wo ich die FW von Dir seoben laufen lassen habe, empfange ich nun den Sensor garnicht mehr. Dafür deutet er öfter nun wie o.genannt schon

>2017-12-09_13:29:55 THR128_4 temperature: -159.2
2017-12-09_13:29:55 THR128_4 battery: low
2017-12-09_13:29:55 THR128_4 T: -159.2 BAT: low
2017-12-09_13:29:55 THR128_4 DMSG: 500A4D400BC4F808004F00
2017-12-09_13:29:55 THR128_4 RAWMSG: Mc;LL=-2696;LH=3164;SL=-1244;SH=1683;D=DB31FF16;C=1464;L=32;R=231;
2017-12-09_13:29:55 THR128_4 RSSI: -86.5
2017-12-09_13:30:55 THR128_4 temperature: -159.1
2017-12-09_13:30:55 THR128_4 battery: low
2017-12-09_13:30:55 THR128_4 T: -159.1 BAT: low
2017-12-09_13:30:55 THR128_4 RSSI: -78.5
2017-12-09_13:30:55 THR128_4 DMSG: 500A4D400BB4F808004E00
2017-12-09_13:30:55 THR128_4 RAWMSG: Mc;LL=-2729;LH=3141;SL=-1254;SH=1683;D=D3D1FFEA;C=1467;L=32;R=247;
2017-12-09_13:31:55 THR128_4 temperature: -159.1
2017-12-09_13:31:55 THR128_4 battery: low
2017-12-09_13:31:55 THR128_4 T: -159.1 BAT: low
2017-12-09_13:31:55 THR128_4 RSSI: -81
2017-12-09_13:31:55 THR128_4 DMSG: 500A4D400BB4F808004E00
2017-12-09_13:31:55 THR128_4 RAWMSG: Mc;LL=-2699;LH=3158;SL=-1245;SH=1682;D=D3D1FFEA;C=1463;L=32;R=242;

Er scheint nun wo anderes noch was zu verschieben. Habe ich noch nicht genauer geschaut.

**Comment by HomeAutoUser** [comment]
Verbos 5 - Ausgabe
>2017.12.09 13:38:55 4: Arduino_Nano_433Mhz/msg READ: Mc;LL=-2715;LH=3161;SL=-1241;SH=1681;D=B07800D4;C=1466;L=30;R=208;
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz: Found manchester Protocol id 18 clock 1466 RSSI -98 -> OSV1
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz: extracted data 10110000011110000000000011010100 (bin)
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz: protocol does not match return from method: ( message is to short)
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz/msg READ: DMc;P0=-2630;P3=1677;P4=-1259;P7=3191;D=563470743034343434743434303434343434343434343474307071
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz/noMsg Parse: DMc;P0=-2630;P3=1677;P4=-1259;P7=3191;D=563470743034343434743434303434343434343434343474307071
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz/msg READ: Mc;LL=-2630;LH=3191;SL=-1259;SH=1677;D=D3E1FFCA;C=1459;L=32;R=245;
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz: Found manchester Protocol id 18 clock 1459 RSSI -79.5 -> OSV1
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz: extracted data 11010011111000011111111111001010 (bin)
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz: OSV1 input data: 11010011111000011111111111001010
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz: OSV1 protocol id (18) translated to RFXSensor format
2017.12.09 13:38:55 4: Arduino_Nano_433Mhz: converted to hex: (500A4D400B74F808004A00)
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz Dispatch: 500A4D400B74F808004A00, test ungleich: disabled
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz Dispatch: 500A4D400B74F808004A00, -79.5 dB, dispatch
2017.12.09 13:38:55 5: Arduino_Nano_433Mhz: dispatch 500A4D400B74F808004A00
2017.12.09 13:38:55 5: OREGON: decoding delay=30 hex=500A4D400B74F808004A00
2017.12.09 13:38:55 5: OREGON: sensor_id=0a4d BitsMsg=80 Bits=80
2017.12.09 13:38:55 5: OREGON: checksum2 = 74 berechnet: 74
2017.12.09 13:38:55 4: THR128_4 decoded Oregon: T: -158.7 BAT: low

**Comment by HomeAutoUser** [comment]
Es gehört zwar nicht hier her, aber "Vorankündigung".  In der aktuellen FW gehen auch die IT nicht mehr. Ich downgrade erstmal sonst gibts Ärger daheim *fG*

**Comment by Ralf9** [comment]
ITv1 oder ITv1. Funktioniert das Senden oder empfangen nicht?

Habe es gerade bei mir getestet. Bei ITv1 funktioniert senden und empfangen.

**Comment by sidey79** [comment]
Also das mit der Logausgabe in ein Filelog kann ich wieder implementieren.

Ich hatte mir da was mit regex überlegt, das ich halt erst mal wieder hinfummeln muss :)
