### ISSUE TITLE
14_SD_WS09 und 14_Hideki in SVN übernehmen

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#200]
Improvemnt from PR #199 in SVN übernehmen.

- [x] 14_Hideki reviewen
- [x] 14_SD_WS9 reviewen

**Comment by Ralf9** [comment]
Wenn dieser commit im master ist, dann kann das 14_Hideki  ins svn
https://github.com/RFD-FHEM/RFFHEM/pull/202/commits/05152f4e918e6855725b702ff695761483ffe990

**Comment by Ralf9** [comment]
Im Oregon Modul passt eine kleinigkeit nicht.
In der Zeile 1121 steht
`Log3 $iohash, 4, "$name decoded Oregon: $val";`
dies müsste aber heissen:
`Log3 $name, 4, "$name decoded Oregon: $val";`

Ist es ok, wenn ich diesen fix direkt ins master commite?

Ist dies ab Zeile 1111 zu ok?
```
print "\nOREGON: Unknown: "; 
print "Type: ".$i->{type}.", ";
print "Value: ".$i->{current}."\n";
```
oder ist es so ` Log3 $iohash, 4, "....`  besser?

**Comment by sidey79** [comment]
@Ralf9 

Man kann den Hash oder den Namen übergeben. Beides ist richtig. Wird der Hash auf die Geräteinstanz übergeben, wird das in der Funktion umgewandelt in den Namen.

Bezüglich commit in den Master. Spricht etwas dagegen es in dev-r33 zu committen? Ich nehme an: nein.

**Comment by Ralf9** [comment]
Habe es ins dev-r33 zu committet
https://github.com/RFD-FHEM/RFFHEM/commit/063703180776a5374ae551cf22d51110aece9af7

**Comment by sidey79** [comment]
Ich denke ich habe den gewünschten code übernommen... ich hoffe es zumindest
