### ISSUE TITLE
FHEM Update schlägt fehlt

### ISSUE THREAD

**Issue by bismosa** [RFD-FHEM/RFFHEM#203]
Hallo,

ich habe gerade versucht auf die Developer Version umzustellen.
`update add https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`

Aber bei einem Update erhalte ich immer wieder:
`Got 19404 bytes for FHEM/14_Hideki.pm, expected 21737
aborting.`

Oder mache ich einen Fehler?

Gruß
Bismsoa

**Comment by sidey79** [comment]
Nein, Fehler ist auch bekannt.


Gibt es einen speziellen Grund, wieso Du die Development Version benötigst?

**Comment by bismosa** [comment]
Nicht wirklich. Ich probiere gerade mit dem IT Protokoll rum.
https://forum.fhem.de/index.php/topic,52827.msg567013.html#msg567013
Hier steht, das das Attribut userV1setCodes nur mit der dev Version funktioniert. Ich denke aber das die Information veraltet ist (?)
Hintergrund ist das ich mehrere IT Codes für den gleichen Befehl benötige:

**Comment by sidey79** [comment]
Du hast Recht, die Information ist Veraltet.


@Ralf9 
Eventuell den Beitrag anpassen.

**Comment by bismosa** [comment]
Danke für die superschnelle Info!
Gruß
Bismosa
