### ISSUE TITLE
Add FA21RF demodulation

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#21]
Fix Protocol Detektion for FA21 RF smoke detectors.

Signal ist capured with Signalduino here:
Mdorenka/fhemduino#27

Signaltype is MS with Sync 1,-30 followed by two additional preamble pulses.

**Comment by sidey79** [comment]
@kolbi Demodulation is included, now we need A ligical Module which decodedString the right bits.

To identify all of them, some testing is needed.

**Comment by Kolbi** [comment]
Okay, thank you. So you think the possibility to get them into FHEM is given?

Then I'm going to buy the FA21RF and an FTDI Arduino Nano these days. Thank you!

**Comment by sidey79** [comment]
I think thats not a Big deal, we only need to identify some Bits like Bad battery etc.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Kolbi** [comment]
Just ordered some FA21RF, maybe I'm building up my SIGNALDuino with a CH340 Arduino Nano...

**Comment by sidey79** [comment]
Ch340 works,i am using them also.

It is possible to program a new device ID into the ftdi chip, or just address it by the USBport number.

**Comment by Kolbi** [comment]
@sidey79 
I just read about the possibility to adress via USBport: http://forum.fhem.de/index.php/topic,36062.0.html

I guess that's a quick solution to be able to use MySensors and Signalduino. Will try it maybe on Wednesday.
