### ISSUE TITLE
Update - Welche Version?

### ISSUE THREAD

**Issue by bismosa** [RFD-FHEM/RFFHEM#211]
Hallo,

ich bin gerade etwas sehr unbeholfen. Ich habe gestern ein FHEM-Update durchgeführt. Als ich die Changed Datei durchgelesen habe, habe ich gesehen, das es auch ein Update von SIGNALduino geben sollte.
Ich hatte die Einrichtung wie im FHEM Wiki beschrieben vorgenommen. Also mittels:
`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`

Hatte allerdings nicht dauerhaft die Updates der DEV-Version übernommen.
`update add https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`

Also laufe ich derzeit noch auf Version
`V 3.3.1-dev SIGNALduino cc1101 - compiled at Mar 10 2017 22:54:50`

Ich bin jedoch sehr neugierig, ob die Verbesserungen seit der Version nicht auch meine Schwierigkeiten beim Empfang meiner Fenstersensoren sehr nützlich sind. Gerade die Änderung:

> 30.09.2016
>   SIGNALduino is now nonblocking
>   improved init and keepalive

Macht mich sehr neugierig!

Meine Frage ist nun:
Welche Version sollte der Endanwender nun eigentlich benutzen? Die dev-r33? Ist das Wiki da noch aktuell? Oder sollte ich eher auf die in FHEM eingecheckte Version gehen? (Wie geht das?)

Seit dem Update gestern tauchen bei mir in der FHEM LOG regelmäßig diese Meldungen auf:
SIGNALduino/noMsg Parse: OK
Liegt das jetzt auch an einer alten Version? 

Vielen Dank!

Gruß
Bismosa

**Comment by sidey79** [comment]
Hi,

mit dem normalen FHEM Update kommen "stabile" Versionen. Wenn möglich, natürlich diese verwenden.

Wenn Du von "https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt" updatest, dann kann diese öfters mal einen Fehler enthalten.
Andererseits, ist es auch gut wenn der ein oder andere diese Verwendet und mit Rückmeldung gibt. :)

Wenn Du version eingibst, dann wird dir auch angezeigt, welche Version dein Modul gerade hat.

Folgende Ausgabe, kommt von der Firmware auf einem arduino:
`
V 3.3.1-dev SIGNALduino cc1101 - compiled at Mar 10 2017 22:54:50
`
Du hast da schon eine Entwicklung Version ( für cc1101 gitbt es auch nichts anderes)

Wie Du die aktuelle Entwicklungs Firmware bekommst, steht im Wiki:
https://wiki.fhem.de/wiki/SIGNALduino#Flashen_einer_Firmware_.C3.BCber_HTTP

`set sduino flash https://drive.google.com/uc?export=download&id=1sIac8-Qhts4c7OEkFH72Lv6hhgbOadFQ
`



Empfehlung:
Modul über das normale Update verwenden
Aktuelle Entwicklungsversion der Firmware testen

**Comment by bismosa** [comment]
Hallo,
vielen Dank für die Ausführliche Rückmeldung.
Mein Fehler bestand wohl darin, dass ich die Modulversion und die Firmwareversion durcheinanderbringe.
Ich nutze jetzt die Modulversion 
`00_SIGNALduino.pm   15471 2017-11-21 23:34:50Z Sidey`
und die Firmware (gerade mal aktualisiert)
`V 3.3.1-RC2 SIGNALduino cc1101 - compiled at Jan 6 2018 00:45:28`
Ich hoffe das es nun so richtig ist. (Wie empfohlen)

Habe ich es richtig verstanden, das ich beim Modul zwischen der DEV und der Offiziellen Version springen kann indem ich entweder 
`update add https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`
oder
`update delete https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`
ausführe? (Hinterher ein Update von FHEM machen)

Ich habe gerade mal meine Fenstersensoren (IT) durchprobiert. Scheint direkt besser zu funktionieren als vorher! (Ich hatte den Eindruck, das einige Signale nicht empfangen wurden, wenn mein Raspberry zu stark ausgelastet war) 
Vielen Dank für eure Bemühungen!

Gruß
Bismosa
