### ISSUE TITLE
Hideki invertiert oder nicht

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#212]
Das Hideki-Protokoll wird  mal invertiert und auch mal nicht invertiert vom SIGNALduino übermittelt:

2018.01.16 09:40:22 3: sduino_USB0: receive hideki protocol inverted
2018.01.16 09:41:11 3: sduino_USB0: receive hideki protocol not inverted
2018.01.16 09:42:49 3: sduino_USB0: receive hideki protocol not inverted
2018.01.16 09:44:27 3: sduino_USB0: receive hideki protocol inverted
2018.01.16 09:45:16 3: sduino_USB0: receive hideki protocol inverted
2018.01.16 09:46:05 3: sduino_USB0: receive hideki protocol not inverted
2018.01.16 09:56:41 3: sduino_USB0: receive hideki protocol not inverted
2018.01.16 09:57:30 3: sduino_USB0: receive hideki protocol inverted
2018.01.16 09:59:08 3: sduino_USB0: receive hideki protocol inverted
2018.01.16 09:59:57 3: sduino_USB0: receive hideki protocol inverted
2018.01.16 10:00:47 3: sduino_USB0: receive hideki protocol not inverted
2018.01.16 10:05:40 3: sduino_USB0: receive hideki protocol not inverted
2018.01.16 10:08:08 3: sduino_USB0: receive hideki protocol not inverted

Dafür hätte ich einen kleinen Fix anzubieten::

sub	SIGNALduino_Hideki()
{
	my ($name,$bitData,$id,$mcbitnum) = @_;
	my $debug = AttrVal($name,"debug",0);
	my $invert = 0;
    Debug "$name: search in $bitData \n" if ($debug);
	my $message_start = index($bitData,"10101110");

	if ($message_start < 0) {
		$bitData =~ tr/01/10/;										# invert message
		$message_start = index($bitData,"10101110");			# 0x75 but in reverse order
	}

	if ($message_start >= 0 )   # 0x75 but in reverse order

Die Protokolldefinition 12.1 könnte damit entfallen.

**Comment by HomeAutoUser** [comment]
@sidey79 

Bitte nichts zu früh übernehmen!
>2018.02.27 00:55:02 3: nano_433Mhz: receive Hideki protocol inverted
2018.02.27 00:55:06 3: nano_433Mhz: receive Hideki protocol not inverted
2018.02.27 01:05:17 3: nano_433Mhz: receive Hideki protocol not inverted
2018.02.27 01:05:25 3: nano_433Mhz: receive Hideki protocol inverted
2018.02.27 01:21:23 3: nano_433Mhz: receive Hideki protocol inverted
2018.02.27 01:21:23 3: nano_433Mhz: receive Hideki protocol not inverted
2018.02.27 05:25:20 3: nano_433Mhz: receive Hideki protocol inverted
2018.02.27 05:25:21 3: nano_433Mhz: receive Hideki protocol not inverted

Dieser Auszug im Log, zeigt einen Teil der falschen Erkennungen und dies ist NICHT behoben!
Ich bzw. wir vermuten, wenn du die Tests mit "konstanten" Zeiten durchlaufen lässt, so tritt der Fall nicht ein. 

Der aktuelle Commit https://github.com/RFD-FHEM/SIGNALDuino/commit/22c18261154bae11bc46d70224a6df29743a44a8 oder auch https://github.com/RFD-FHEM/SIGNALDuino/commit/1bf17ec45226bc2c55b601ffb6b4bad3b9edbfe9 bzw. https://github.com/RFD-FHEM/SIGNALDuino/commit/3daccba98aa188e357e8bfe0b5e6127be25e3344 haben das Problem nicht behoben. Getestet habe ich dies über 10h mit dem https://github.com/RFD-FHEM/SIGNALDuino/commit/b9bf1b533c03a8845542c289dca24a8255228717.

**Comment by sidey79** [comment]
Ähm, jetzt sind wir im FHEM Modul oder?

Die hoffentlich funktionsfähige Firmware gibt es in diesem Zweig:

https://github.com/RFD-FHEM/SIGNALDuino/commits/dev-r33_cc1101

Ich bin aber geneigt, das cc1101 Thema zu beenden ( da es funktioniert) und auch diesen Zweig in dev-r33 zu überführen.

**Comment by HomeAutoUser** [comment]
Wenn ich das richtig überblicke ist das Thema abgehakt und könnte geschlossen werden.
