### ISSUE TITLE
Unbekanntes Protokoll 868Mhz = Durchschlag Hideki-Sensoren 433Mhz

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#217]
Hallo,
die Zeiten sind immer und immer wieder identisch.
Was wäre eine passende Protokolldefinition?

>2018.02.18 20:11:04 4: nano_868Mhz/msg READredu: MU;P0=-21832;P1=922;P2=-1051;P3=-529;P4=437;D=0121213434243434312434313424312134342124312124343121243434313434243134343434212434313434342434312121212434312434343134213434343434342430;CP=4;R=215;
2018.02.18 20:11:04 4: nano_868Mhz/msg READredu: MU;P0=-9480;P1=911;P2=-1033;P3=-554;P4=429;D=01212134342434343124343134243121343421243121243124312434343134342431343434342124343134343424343121212124343124343434343431243121342430;CP=4;R=215;
2018.02.18 20:13:19 4: nano_868Mhz/msg READredu: MU;P0=-17152;P1=915;P2=-1036;P3=-544;P4=428;D=012121343424343431243431342431213434212431212431342124343431343424313434343421243431343434243431212121243431243434343121212434312430;CP=4;R=215;
2018.02.18 20:13:19 4: nano_868Mhz/msg READredu: MU;P0=-5156;P1=919;P2=-1041;P3=-565;P4=411;D=0121213434243434312434313424312134342124312124343121243434313434243134343434212434313434342434312121212434312434343134213434343434342430;CP=4;R=214;
2018.02.18 20:14:04 4: nano_868Mhz/msg READredu: MU;P0=-21932;P1=889;P2=-1059;P3=-580;P4=399;D=012121343424343431243431342431213434212431212431342124343431343424313434343421243431343434243431212121243431243434343121212434312;CP=4;R=212;

**Comment by sidey79** [comment]
Könnte man machen, aber wir wissen halt überhaupt nicht was es ist.

Aber da du es mit einem CC1101 empfangen hast können wir Störungen ausschließen :)

**Comment by elektron-bbs** [comment]
Auch diese Nachrichten dürften von einem Hideki stammen. Ich habe jetzt nur die ersten Pulse mit den Oszillogrammen verglichen. Auch die Länge der Nachrichten passt dazu.
Was mir hier auffällt: @sidey79

**Comment by HomeAutoUser** [comment]
Ja es sind auf einmal Hideki Sensoren welche "durchschlagen". Das konnte ich verifizieren und es kommen auch manchmal welche durch und werden richtig erkannt.
