### ISSUE TITLE
Arduino Nano neuer Bootloader 2018 Baudrate 115200

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#225]
Ich musste mir jetzt einen neuen SIGNALduino zusammen stecken, weil bei dem bisherigen der CC1101 sich mit Rauchzeichen verabschiedet hat. Verwendet habe ich einen neu gekauften Arduino Nano. Ich habe mich dann gewundert, das sich dieser aus FHEM nicht mehr flashen lies. In der Arduino-IDE geht es aber problemlos.

Nach einiger Suche fand ich dann heraus, das diese Arduinos seit Anfang 2018 mit einem anderen Bootloader ausgeliefert werden (wahrscheinlich [Optiboot](https://github.com/Optiboot)) (Siehe auch [Arduino Nano.](https://www.arduino.cc/en/Guide/ArduinoNano)). Das Flashen erfolgt jetzt mit einer Baudrate von 115200.

Die "AttrList" habe ich geändert in:

." hardware:nano328,nano328newBl,nanoCC1101,nanoCC1101newBl,promini328,radino,uno"

und das Kommando "flash" etwas erweitert:

		my $hardware=AttrVal($name,"hardware","nano328");
		my $baudrate=$hardware eq "uno" ? 115200 : 57600;
		if (substr($hardware,-5) eq "newBl") {
			$baudrate=115200;
			substr($hardware, -5) = "";
		}

**Comment by sidey79** [comment]
Danke für die Info.

Das ist ja schwer feststellbar, welchen bootloader man hat. Gerade bei den clonen 

Vielleicht könnte man auch einbauen, dass man beide Optionen im hintergrund probiert. Wäre aktuell aber halt nur mit code im Modul realisierbar.

2. Hardware Definition überlässt es halt dem Anwender es zu setzen.

**Comment by HomeAutoUser** [comment]
@sidey79 
da wir hier auch noch nicht "gehandelt" haben, die Frage wie wir verfahren wollen.

Entweder ein neues Hardwaremodell wie von @elektron-bbs vorgeschlagen oder den Hinweis in der Doku, das man ggf. mit der Option Uno probieren soll. Basierend darauf

`>	my $baudrate=$hardware eq "uno" ? 115200 : 57600;`

Definitiv, müsste mindestens ein Hinweis in unsere Doku, das es vermutlich ab 2018 einen neuen BL gibt.

Mir persönlich wäre es mit dem neuen Hardwaremodell am symphatischsten und parallel der Hinweis in der Doku. (Vorschlag Hardwaremodellname: nanoCC1101_newBL)

**Comment by sidey79** [comment]
In de Arduino IDE wurde ein neuer Eintrag für die alte Hardware eingefügt.

Wir könnten beim Nano auch einfach beide Baudraten ausprobieren.

**Comment by HomeAutoUser** [comment]
@elektron-bbs 
kannst du mal bitte bei dir folgends Kommando auf den neuen Bootloader "loslassen"?
> avrdude -p m328p -F -c avr109 -P /dev/ttyUSB1 -v -U lfuse:r:-:i 

Es gibt dir Informationen aus ohne zu schreiben.
Mich interssiert dort die Information

> Description     : Atmel AppNote AVR109 Boot Loader

Sollte beim neuen BL eine andere Beschreibung drin stehen, so könnte man auslesen, vergleichen und dann je Typ flashen. 

>Wir könnten beim Nano auch einfach beide Baudraten ausprobieren.

Einfach probieren? Da "generieren" wir ja eine Fehlermeldung.
Eher die Auswahl via zusätzlichen Hardwaremodel wie es auch in ArduinoIDE gehandhabt wird.

**Comment by elektron-bbs** [comment]
Das Thema wird jetzt langsam relevant, wie ich so im Forum mitbekomme, wie z.B. hier:
https://forum.fhem.de/index.php/topic,58397.msg912414.html#msg912414

**Comment by sidey79** [comment]
Oh, irgendwie dachte ich, wir hätten das schon eingebaut 

Was machen wir denn jetzt? 
Wenn wir beide Varianten probieren, könnten wir doch in der Rückgabe von avrdude suchen ob es geklappt hat oder eben nicht und dann die 2. Variante probieren.
Die Fehlermeldung der 1. Variabte könnten wir ja im Erfolgsfall für uns behalten.

Wisst ihr was ich meine?

**Comment by Ralf9** [comment]
Ich finde ein neues Hardwaremodel auch besser. (nano328_newBl, nanoCC1101_newBl)
Und dann eine neue Sub get_hardware()
my ($baudrate, $hardware) = get_hardware($name);
in die Sub kann dann auch rein:
    if ($hardware eq "nano") {
       $hardware = "nano328";
    }

**Comment by sidey79** [comment]
Woher weiss der Anwender, welche Variante er hat und was ist der Vorteil ihm diese Auswahl zu überlassen, anstatt es im Hintergrund für ihn zu regeln?

**Comment by sidey79** [comment]
Wenn ich das richtig sehe sind wir hier nicht weiter gekommen

**Comment by HomeAutoUser** [comment]
@sidey79 , ja hier haben wir noch keine richtige Lösung gefunden.

**Comment by elektron-bbs** [comment]
Lösung wäre evtl. hier: https://github.com/RFD-FHEM/RFFHEM/pull/662#issuecomment-543786076

**Comment by elektron-bbs** [comment]
Flash des Arduino Nano mit neuem Bootloader OptiBoot wurde mit PR https://github.com/RFD-FHEM/RFFHEM/pull/675 realisiert.
