### ISSUE TITLE
Überlegung zur Wiki

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#228]
Hallo, ich verfolge auch parallel die Wiki und habe mir einen Zugang zu Ihr geben lassen.
Was haltet Ihr davon, [die Wiki](https://wiki.fhem.de/wiki/SIGNALduino) soweit zu aktualisieren, das wir dort entnehmen welches Frequenzband dies ist?

Für eine weitere Vereinfachung um dies abzugleichen wäre es aber Hilfreich, **das wir ordentliche Kommentare in der Protokolldefinition verankern und nicht nur den Hersteller**. Mir liegt vieles daran, überflüssige Fragen zu vermeiden und auch  die Wiki aktueller zu halten was die DEV bzw. Stable Version angeht.

... mal in die Meinungsrunde geworfen.

Bei Zustimmung oder Beführwortung würde ich dies auf "meine" Seite ziehen.

**Comment by sidey79** [comment]
Ich fände es gut, wenn die Doku einen guten Stand hat.

Leider habe ich das selbst in der Vergangenheit nicht geschafft.  Da kommt ein neues Gerät auf, es wird etwas entwickelt und am ende... naja gibts keine 100%ige Gewissheit ob es funktioniert oder nicht.
Naja natürlich hat man oft auch bessere Rückmeldung, aber manchmal verläuft es halt doch leider so.

**Comment by HomeAutoUser** [comment]
>Ich fände es gut, wenn die Doku einen guten Stand hat.

Ich werde mir dies mal ansehen.
Eine Überlegung von mir ist, die vorhanden Tabelle mit den Protokollen zu aktualisieren und diese auch so zu splitten für stable und dev! Da wäre nur die BITTE, das wir in der Programmeigenen Protokollliste "sinnvolle Bezeichnungen verwenden". Das erleichtert uns die Dokumentationsarbeit in der Wiki.

Danach werde ich mir mal den Text vornehmen und bei einer größeren Änderung hier im Faden erstmal nachfragen wenn ich mir unsicher bin.

**Comment by sidey79** [comment]
Gute idee. Ich frage mich nur, wie wir den Stand aktuell halten, wenn von dev nach Master überführt wird.

Manchmal hab ich da echt Probleme das zu rekonstruieren.

Die Kommentare / Beschreibung der Protokolle könnte man übrigens auch komplett aus dem Wiki laden und in FHEM anzeigen. Das würde doppelte Pflege sparen.

Gut würde mir auch gefallen, wenn wir die Protokollinformationen aus dem Modul in eine extra "Datei" auslagern könnten. Ich hatte schon mal an JSON gedacht, aber auf Anhieb nichts brauchbares gefunden mit dem man das in Perl einfach erzeugt und auch wieder einliest.

eval möchte ich nicht nehmen, da man ja so jeden beliebigen code einschleusen könnte.

**Comment by HomeAutoUser** [comment]
@sidey79  was hälst du von solch einer Aktualisierung in der Wiki?
Spricht da was dagegen? Alle Protokolle sind NICHT aufgenommen, ausgeschlossen unter anderem die Development Varianten und wovon man nichts findet im Internet. Wir müssen unbedingt auf eindeutige Bezeichnungen achten!
**--> Name!
--> comment!**

\| Bewegungsmelder   \|\| Oregon Scientific \|\| E \|  \|\| OREGON   \|\| 52
\| Fernbedienung \|\| AK-HD-4 remote \|\| E   \|  \|\| none \|\| 59
\| Fernbedienung \|\| Globaltronics Quigg   GT-1000 \|\| E S \|  \|\| IT \|\| 55
\| Fernbedienung \|\| Visivon remote pt4450   \|\| E \|  \|\| none \|\| 24
\| Garagentor \|\| Einhell HS 434/6 \|\| E   \|  \|\| none \|\| 21
\| Handsender \|\| Somfy RTS \|\| E S \|  \|\| SOMFY \|\| 43
\| Klingel \|\| Elro (Smartwares) Doorbell   DB200 \|\| E \|  \|\| none \|\| 41
\| Klingel \|\| FreeTec PE-6946 \|\| E \|  \|\| none \|\| 32
\| Klingel \|\| TCM 234759 (Tchibo) \|\| E   \|  \|\| none \|\| 15
\| Rauchmelder \|\| Flamingo FA20RF / FA21RF   \|\| E \|  \|\| none \|\| 13
\| Regenmesser \|\| PFR-130 \|\| E \|  \|\| CUL_TCM97001 \|\| 68
\| Rolladen / Markisen \|\| Dooya shutter /   Rohrmotor24 \|\| E S \|  \|\| Dooya \|\| 16
\| Schalter / Steckdosen \|\| ELV - FS10 \|\|   E S \|  \|\| FS10 \|\| 61
\| Schalter / Steckdosen / Bewegungsmelder   \|\| Intertechno \|\| E S \|  \|\| IT \|\|   3,4,5,17
\| Schalter / Steckdosen \|\| mumbi m-FS300   \|\| E \|  \|\| none \|\| 26,27
\| Tür/Fensterkontakt \|\| FHT80TF \|\| E   \|  \|\| CUL_FHTTK \|\| 70
\| Wetterstation / Sensoren \|\| ABS 700 \|\|   E \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| AURIOL \|\| E   \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| Bresser   7009994 \|\| E \|  \|\| SD_WS \|\| 37
\| Wetterstation / Sensoren \|\| Bresser   Temeo Trend \|\| E \|  \|\| SD_WS09 \|\| 44
\| Wetterstation / Sensoren \|\| Bresser   Temp/Hydro Sensor \|\| E \|  \|\| Hideki \|\|   12
\| Wetterstation / Sensoren \|\| ELV - LA   CROSSE (WS2000/WS3000/WS7000) \|\| E \| eq3 / S300 … \|\| CUL_WS \|\| 60
\| Wetterstation / Sensoren \|\| Eurochron   eas800z \|\| E \|  \|\| SD_WS07 \|\| 7
\| Wetterstation / Sensoren \|\| FreeTec   Außenmodul NC-7344 \|\| E \|  \|\| SD_WS07   \|\| 7
\| Wetterstation / Sensoren \|\| GT-WT-02 \|\|   E \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| Hama TS33C   \|\| E \|  \|\| Hideki \|\| 12
\| Wetterstation / Sensoren \|\| Lacrosse   TX2/TX3 Sensoren \|\| E \|  \|\| CUL_TX \|\| 8
\| Wetterstation / Sensoren \|\| LIDL \| IAN   275901  \|\| E \|  \|\| SD_WS \|\| 51
\| Wetterstation / Sensoren \|\| Logilink \|\|   E \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| Mebus \|\| E   \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| Meteo   TX-EZ6 \|\| E \|  \|\| none \|\| 22
\| Wetterstation / Sensoren \|\| Model   WS7053 / WS7035 \|\| E \| TX2 Protokoll \|\| CUL_TX \|\| 66,67
\| Wetterstation / Sensoren \|\| NC / WS \|\|   E \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| Oregon   Scientific \|\| E \| Protokoll V1 / V2 / V3 \|\| OREGON \|\| 10, 18
\| Wetterstation / Sensoren \|\| Prologue \|\|   E \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| QUIGG   GT9000 (Globaltronics/ALDI)  \|\| E   \|  \|\| none \|\| 49
\| Wetterstation / Sensoren \|\| Rubicson \|\|   E \|  \|\| CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| TCM (97001   und 21xxx Serie) \|\| E \|  \|\|   CUL_TCM97001 \|\| 0
\| Wetterstation / Sensoren \|\| Technoline   WS6750/TX70DTH \|\| E \|  \|\| SD_WS07 \|\| 7
\| Wetterstation / Sensoren \|\| TFA 30.3200   \|\| E \|  \|\| none \|\| 33
\| Wetterstation / Sensoren \|\| TFA   30320902 \|\| E \|  \|\| SD_WS07 \|\| 7
\| Wetterstation / Sensoren \|\| TFA   Dostmann Joker \|\| E \|  \|\| none \|\| 48
\| Wetterstation / Sensoren \|\| TFA   Temp/Hydro Sensor \|\| E \|  \|\| Hideki \|\|   12
\| Wetterstation / Sensoren \|\|   WH1080/WH3080/CTW600 \|\| E \|  \|\| SD_WS09   \|\| 9
\|    \|\| Conrad RSL Funkschalter \|\| E S \| Funktioniert aktuell nicht \|\|   SIGNALduino_RSL \|\|
\|    \|\| Heidemann HX \|\| E \|  \|\| none   \|\| 14
\|    \|\| Livolo \|\| E \|  \|\| none \|\| 20
\|    \|\| Smartwares SH5-TSO-A \|\| E S \|    \|\| IT \|\|  ?
\|    \|\| X10 Security Devices \|\| E \|    \|\| none \|\| 39

**Comment by sidey79** [comment]
@HomeAutoUser 

Aus meiner sicht spricht nichts dagegen :)

**Comment by HomeAutoUser** [comment]
Dann werden wir darauf aufbauen :-)

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
