### ISSUE TITLE
Homeeasy

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#230]
Ich habe bei mir mal den Empfang von Homeeasy HE800 und HE_EU eingebaut. Es wird das Modul IT verwendet.
Das Senden habe ich nicht eingebaut, dazu fehlt mir eine Steckdose zum Testen.

Für HE_EU habe ich die id65 angepasst:

```
	"65" => ## Homeeasy
		{
		# MS;P1=231;P2=-1336;P4=-312;P5=-8920;D=15121214141412121212141414121212121414121214121214141212141212141212121414121414141212121214141214121212141412141212;CP=1;SP=5;
			name         => 'HE_EU',
			comment      => 'Homeeasy',
			id           => '65',
			one          => [1,-5.5],
			zero         => [1,-1.2],
			sync         => [1,-38],
			clockabs     => 230,
			format       => 'twostate',  # not used now
			preamble     => 'ih',
			clientmodule => 'IT',
			length_min   => '57',
			postDemodulation => \&SIGNALduino_HE_EU,
		},
```
Für HE800 verwende ich die neue id80.
Die id35 (socket35) würde fast passen, ich bin mir unsicher ob ich diese dafür verwenden soll,
oder ob es besser ist eine neue (id80) zu verwenden.

```
	"80" =>
		{
		# MS;P0=907;P1=-376;P2=266;P3=-1001;P6=-4860;D=2601010123230123012323230101012301230101010101230123012301;CP=2;SP=6;
			name		=> 'HE800',
			comment		=> 'Homeeasy',
			id		=> '80',
			one		=> [1,-4],
			zero		=> [3.4,-1],
			sync		=> [1,-18],
			clockabs   	=> '280',		
			format     	=> 'twostate',  		# not used now
			preamble	=> 'ih',				# prepend to converted message	
			postamble	=> '',					# Append to converted message	 	
			clientmodule	=> 'IT',      			# not used now
			#modulematch	=> '',     			# not used now
			length_min	=> '28',
			length_max	=> '40',
			postDemodulation => \&SIGNALduino_HE800,
		},
```
```
sub SIGNALduino_HE800($@)
{
	my ($name, @bit_msg) = @_;
	my $protolength = scalar @bit_msg;
	
	if ($protolength < 40) {
		for (my $i=0; $i<(40-$protolength); $i++) {
			push(@bit_msg, 0);
		}
	}
	return (1,@bit_msg);
}

sub SIGNALduino_HE_EU($@)
{
	my ($name, @bit_msg) = @_;
	my $protolength = scalar @bit_msg;
	
	if ($protolength < 72) {
		for (my $i=0; $i<(72-$protolength); $i++) {
			push(@bit_msg, 0);
		}
	}
	return (1,@bit_msg);
}
```

**Comment by Ralf9** [comment]
Hier sind einige raw Nachrichten:
HE800:
```
MS;P0=-4853;P1=905;P2=-376;P3=277;P4=-1001;D=3012341234341212121234123412121234343412341212343412123434;CP=3;SP=0;O;m0;
MS;P0=-4846;P1=905;P2=-375;P3=278;P4=-998;D=3012341234341212121234123412121234343412341212343412123434;CP=3;SP=0;O;m1;
MS;P0=-4847;P1=909;P2=-374;P3=276;P4=-998;D=3012341234341212121234123412121234343412341212343412123434;CP=3;SP=0;O;m2;
MS;P0=-4845;P1=906;P2=-377;P3=278;P4=-997;D=3012341234341212121234123412121234343412341212343412123434;CP=3;SP=0;O;m3;

MS;P0=-4855;P1=905;P2=-385;P3=267;P4=-1002;D=3012341234341234121234343434341212341234123412341212123434;CP=3;SP=0;O;m0;
MS;P0=-4846;P1=910;P2=-374;P3=279;P4=-999;D=3012341234341234121234343434341212341234123412341212123434;CP=3;SP=0;O;m1;
MS;P0=-4845;P1=908;P2=-377;P3=275;P4=-998;D=3012341234341234121234343434341212341234123412341212123434;CP=3;SP=0;O;m2;
MS;P0=-4844;P1=905;P2=-370;P3=284;P4=-998;D=3012341234341234121234343434341212341234123412341212123434;CP=3;SP=0;O;m3;
```

HE_EU:
```
MS;P1=223;P2=-1339;P3=-317;P4=-8926;D=14121213131312121212131313121212121313121212131213121213121312131312121313121313121312131213131213121212131312121312;CP=1;SP=4;O;m0;
MS;P1=238;P2=-1324;P3=-304;P4=-8906;D=14121213131312121212131313121212121313121212131213121213121312131312121313121313121312131213131213121212131312121312;CP=1;SP=4;O;m1;
MS;P1=241;P2=-1323;P3=-300;P4=-8903;D=14121213131312121212131313121212121313121212131213121213121312131312121313121313121312131213131213121212131312121312;CP=1;SP=4;O;m2;
MS;P1=242;P2=-1321;P3=-302;P4=-8899;D=14121213131312121212131313121212121313121212131213121213121312131312121313121313121312131213131213121212131312121312;CP=1;SP=4;O;m3;

MS;P1=224;P2=-317;P3=-1331;P4=-8924;D=14131312121213131313121212131313131212131313121312131312131213121213131212131212131213121312121213131313121213131213;CP=1;SP=4;O;m0;
MS;P1=239;P2=-301;P3=-1324;P4=-8908;D=14131312121213131313121212131313131212131313121312131312131213121213131212131212131213121312121213131313121213131213;CP=1;SP=4;O;m1;
MS;P1=239;P2=-298;P3=-1325;P4=-8904;D=14131312121213131313121212131313131212131313121312131312131213121213131212131212131213121312121213131313121213131213;CP=1;SP=4;O;m2;
MS;P1=241;P2=-299;P3=-1323;P4=-8900;D=14131312121213131313121212131313131212131313121312131312131213121213131212131212131213121312121213131313121213131213;CP=1;SP=4;O;m3;
```

**Comment by sidey79** [comment]
Spitzen Arbeit.

Machst Du einen commit oder PR?

**Comment by Ralf9** [comment]
Ich weiß noch nicht wie ich es mit dem HE800 machen soll.
Soll ich die id35 verwenden, welche fast passt (es erfolgt ein match), oder soll ich eine neue (id80) verwenden.
Die id35 hat einen nichts sagenden Namen socket35.
Ist es ok, wenn ein neues Protokoll eine alte id bekommt, oder ist es besser wenn wir für neue Protokolle eine neue ID am Ende nehmen?

**Comment by sidey79** [comment]
Tia, die Sache mit socket35, entstand in dem Thema #60 
Die Fernbedienung hat wohl mehrere Protokolle gesendet. Vermutlich ist es das gleiche wie HE800.. kannst es dir ja mal ansehen ob es passt.

Da wir aktuell auf u35 laufen würde ich sagen, dass wir es auch in P35 ändern können.

**Comment by Ralf9** [comment]
ich habe es ins dev-r33 commitet
https://github.com/RFD-FHEM/RFFHEM/commit/98ba81b12ef8c83c4363009dc7ebeb7c6ebb35bf

**Comment by HomeAutoUser** [comment]
Hallo @Ralf9,
kann es sein das die Protokolle von HomeEasy dem Protokoll "Matched MS Protocol id 17" ähneln.
Ich besitze einen Bewegungsmelder welcher als 17 erkannt wird aber zusätzlich auch unbekannte IT generiert. Es ist der PIR-1000 von Intertechno und [wenn ich Google befrage, dann sieht der HomeEasy PIR genau so aus](https://www.amazon.de/Home-Easy-HE851-Funk-Bewegungsmelder/dp/B005VA9OGA). Nicht das wir eine doppelte ID generieren wo die Zeiten fast identisch sind.

Was die Steckdosen angeht, so habe ich auch welche und könnte das mal testen.

Ich habe auf dem Schirm, den Bewegungsmelder mal an den LogicAnalyzer anzuschließen für genaue erkenntnisse, da die 

Was steht bei dir auf dem PIR genau bzw. kannst du diesen für das Siganl an einen LogicAnalyzer anschließen das wir dies verifizieren könnten?

>2018.04.02 11:17:03 3: nano_433Mhz IT: IT_V3_da910c9 aus->on
2018.04.02 11:18:07 3: nano_433Mhz IT: IT_V3_da910c9 an->off
2018.04.02 11:18:07 3: nano_433Mhz IT: message "i569A6659595600" (15) too short!
2018.04.02 11:18:07 3: nano_433Mhz IT: message "i569A6659595600" (15) too short!
2018.04.02 11:18:07 3: nano_433Mhz: Unknown code i569A6659595600, help me!
2018.04.02 11:18:07 3: nano_433Mhz IT: message "i569A6659595400" (15) too short!
2018.04.02 11:18:07 3: nano_433Mhz IT: message "i569A6659595400" (15) too short!
2018.04.02 11:18:07 3: nano_433Mhz: Unknown code i569A6659595400, help me!
2018.04.02 11:18:07 3: nano_433Mhz IT: message "i569A6659595600" (15) too short!
2018.04.02 11:18:07 3: nano_433Mhz IT: message "i569A6659595600" (15) too short!
2018.04.02 11:18:07 3: nano_433Mhz: Unknown code i569A6659595600, help me!
2018.04.02 11:18:07 3: nano_433Mhz IT: IT_V3_da910c9 aus->off
2018.04.02 11:18:08 3: nano_433Mhz IT: message "i569A6659595600" (15) too short!
2018.04.02 11:18:08 3: nano_433Mhz IT: message "i569A6659595600" (15) too short!
2018.04.02 11:18:08 3: nano_433Mhz: Unknown code i569A6659595600, help me!
2018.04.02 11:18:08 3: radino_433Mhz IT: message "i569A665959500" (14) too short!
2018.04.02 11:18:08 3: radino_433Mhz IT: message "i569A665959500" (14) too short!
2018.04.02 11:18:08 3: radino_433Mhz: Unknown code i569A665959500, help me!
2018.04.02 11:18:08 3: nano_433Mhz IT: IT_V3_da910c9 aus->off
2018.04.02 11:18:08 2: nano_433Mhz IT: 00000000000000000000000000000000000000000000000000000 not defined (Address: 0000000000000000000000000000000000000000000000 Unit: 0000000 Switch code: 00 GroupCode: 0)
2018.04.02 11:18:08 3: nano_433Mhz IT: IT_V3_da910c9 aus->off

So sieht das bei mir aus bei einem Schaltvorgang

**Comment by Ralf9** [comment]
Nein das HE800 hat keine Ähnlichkeit mit der id 17.
Wenn Du in das IT-Modul reinschaust siehst Du, daß es keine Ähnlichkeit hat.
Das HE800 verwendet u.a. einen Rolling Code.

Ich habe die Homeeasy Fernbedienung HE844A, da kann ich per Dip Schalter auswählen ob sie HE800, HE_EU oderITv1 sendet.
Zum Testen habe ich einen signalduino zum cul umgeflasht.

**Comment by HomeAutoUser** [comment]
@Ralf9 
bei deinem Protocoll müssen wir noch feinschliff betreiben vermutlich.
Bei mir kommen ab und zu solche Definitionen durch

>  IT_00000000000000000000000000000000000000000000000000000

> mode | single |  
> protocol | HE_EU |  
> unit | 0000000

>MS;P0=-9536;P1=243;P2=-2612;P4=-274;P5=-1077;D=1214151415141515141514141515141514141515141415151414151415151414151415141515141415141514151415151415141415141515141514141514151514100;CP=1;SP=2;R=11;

Ich vermute da kommt von dem PIR-1000 intertechno welchen in ich der mache habe und [einen Faden](https://github.com/RFD-FHEM/RFFHEM/issues/232) erstellt habe.

**Comment by HomeAutoUser** [comment]
>2018.04.04 20:55:59 4: nano_433Mhz: Matched MS Protocol id 65 -> HE_EU
2018.04.04 20:55:59 4: nano_433Mhz: Decoded MS Protocol id 65 dmsg ih000000000000000000 length 72 RSSI = -75
2018.04.04 20:55:59 4: nano_433Mhz IT: message "ih000000000000000000" (20)
2018.04.04 20:55:59 4: nano_433Mhz IT: msgcode "000000000000000000000000000000000000000000000000000000000" (57) bin = 000000000000000000000000000000000000000000000000000000000000
2018.04.04 20:55:59 4: nano_433Mhz IT: message "ih000000000000000000" (20)
2018.04.04 20:55:59 4: nano_433Mhz IT: msgcode "000000000000000000000000000000000000000000000000000000000" (57) bin = 000000000000000000000000000000000000000000000000000000000000
2018.04.04 20:55:59 3: nano_433Mhz: Unknown code ih000000000000000000, help me!

**Comment by Ralf9** [comment]
Das passt was nicht in der SIGNALduino_Parse_MS:

```
2018.04.04 21:35:50.540 4 : sduinoD/msg get raw: MS;P0=-9536;P1=243;P2=-2612;P4=-274;P5=-1077;D=1214151415141515141514141515141514141515141415151414151415151414151415141515141415141514151415151415141415141515141514141514151514100;CP=1;SP=2;R=11;
2018.04.04 21:35:50.541 4 : sduinoD: Matched MS Protocol id 65 -> HE_EU, bitLen=65.5
2018.04.04 21:35:50.541 5 : sduinoD: Starting demodulation at Position 132
2018.04.04 21:35:50.541 5 : sduinoD: Found wrong signalpattern, catched 0 bits, aborting demodulation
2018.04.04 21:35:50.541 5 : sduinoD: applying postDemodulation, value before:
2018.04.04 21:35:50.541 5 : sduinoD: rcode=1, modified value after postDemodulation: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
2018.04.04 21:35:50.541 4 : sduinoD: Decoded MS Protocol id 65 dmsg ih000000000000000000 length 72 RSSI = -68.5
```

Die sub postDemodulation wird aufgerufen, obwohl die Demodulation abgebrochen wurde.

**Comment by Ralf9** [comment]
Ich habe es mir nochmals genauer angeschaut. Das Problem ist, daß der SIGNALduino_callsub vor dem prüfen der length steht.

Es müsste so aussehen:
```
			$valid = $valid && $ProtocolListSIGNALduino{$id}{length_min} <= scalar @bit_msg  if (defined($ProtocolListSIGNALduino{$id}{length_min})); 
			$valid = $valid && $ProtocolListSIGNALduino{$id}{length_max} >= scalar @bit_msg  if (defined($ProtocolListSIGNALduino{$id}{length_max}));
			next if (!$valid);  

			my ($rcode,@retvalue) = SIGNALduino_callsub('postDemodulation',$ProtocolListSIGNALduino{$id}{postDemodulation},$name,@bit_msg);
			next if ($rcode < 1 );

			my $dmsg = SIGNALduino_b2h(join "", @bit_msg);
```

**Comment by HomeAutoUser** [comment]
@Ralf9,
wenn die Änderung läuft, würdest du bitte einen Commit ins Dev_r33 machen von @sidey79 ?

**Comment by Ralf9** [comment]
@sidey79 
Ist es ok, wenn ich dies so ins Dev_r33 committe?
https://github.com/Ralf9/RFFHEM/blob/9bd31bcfee5e22fa0e2c5844e9aba0391e5e0d46/FHEM/00_SIGNALduino.pm#L3382-L3392

**Comment by Ralf9** [comment]
Ich habe es commitet
https://github.com/RFD-FHEM/RFFHEM/commit/bd02c3acbab0cfa69cb0607958ca1a743df1e99a

**Comment by HomeAutoUser** [comment]
@Ralf9 

bei deinen all zu verfügenden RAWMSG ist jeweils die Länge 40.
Können wir hier

```
     "35" => # Homeeasy
			 # MS;P0=907;P1=-376;P2=266;P3=-1001;P6=-4860;D=2601010123230123012323230101012301230101010101230123012301;CP=2;SP=6;
		{   
			name		=> 'HE800',
			comment		=> 'Homeeasy',	
			id          	=> '35',
			one			=> [1,-4],
			zero			=> [3.4,-1],
			sync			=> [1,-18],
			clockabs   		=> '280',		
			format     		=> 'twostate',  		# not used now
			preamble		=> 'ih',				# prepend to converted message	
			postamble		=> '',					# Append to converted message	 	
			clientmodule    => 'IT',
			#modulematch     => '',
			length_min      => '28',
			length_max      => '40',
			postDemodulation => \&SIGNALduino_HE800,
    	},
```

auch die Länge anpassen? Wieso ist dort ein min von 28 drin?

**Comment by Ralf9** [comment]
Da ist eine length_min von 28 drin da die RAWMSG eine Länge von 28 haben.

```
2018.11.29 17:37:47.187 4 : sduinoD/msg get raw: MS;P0=907;P1=-376;P2=266;P3=-1001;P6=-4860;D=2601010123230123012323230101012301230101010101230123012301;CP=2;SP=6;
2018.11.29 17:37:47.187 4 : sduinoD: Matched MS Protocol id 35 -> HE800, bitLen=28
2018.11.29 17:37:47.187 5 : sduinoD: applying postDemodulation, value before: 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0
```

**Comment by HomeAutoUser** [comment]
@Ralf9 bitte vergleichen und @sidey79 liegt hier ein Bug vor?

Ich habe die selbe RAWMSG vom Vorpost genommen:

```
2018.11.29 18:49:16 4: sduino_dummy/msg get raw: MS;P0=907;P1=-376;P2=266;P3=-1001;P6=-4860;D=2601010123230123012323230101012301230101010101230123012301;CP=2;SP=6;
2018.11.29 18:49:16 4: sduino_dummy: Matched MS Protocol id 35 -> HE800
2018.11.29 18:49:16 4: sduino_dummy: Decoded MS Protocol id 35 dmsg ih1AE282A000 length 40
2018.11.29 18:49:16 4: sduino_dummy IT: message "ih1AE282A000" (12)
2018.11.29 18:49:16 4: sduino_dummy IT: msgcode "0001101011100010100000101010" (28) bin = 00011010111000101000001010100000
2018.11.29 18:49:16 4: sduino_dummy IT: msg:ih1AE282A000 msgcode:1AE282A0
2018.11.29 18:49:16 4: sduino_dummy IT: HEX:ih1AE282A000 DEC:451052192
2018.11.29 18:49:16 4: sduino_dummy IT: DEC:240244693
2018.11.29 18:49:16 4: sduino_dummy IT: DEC:155672407
2018.11.29 18:49:16 4: sduino_dummy IT: mn: 7 5 15 5 7 4 0
2018.11.29 18:49:16 4: sduino_dummy IT: mn: 3 12 14 15 8 3 0 
2018.11.29 18:49:16 4: receiverID    : 3
2018.11.29 18:49:16 4: OFF/ON/DIM    : 0
2018.11.29 18:49:16 4: Rolling-Code  : 3
2018.11.29 18:49:16 4: Transmitter-ID: 14590
```

**Comment by Ralf9** [comment]
Die length min/max wird vor der postDemodulation geprüft:
```
2018.11.29 18:56:23.280 5 : sduinoD: applying postDemodulation, value before: 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0
2018.11.29 18:56:23.280 5 : sduinoD: rcode=1, modified value after postDemodulation: 0 0 0 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
```

**Comment by sidey79** [comment]
> @Ralf9 bitte vergleichen und @sidey79 liegt hier ein Bug vor?

Würde ich so nicht sagen.
Die Länge wird möglichst früh verifiziert. Die Mindestlänge kann man problemlos vor einer postdemodulation verifizieren, da in der Regel das Signal hier nicht länger wird.
Die Maximallänge vor der postdemodulation zu prüfen ist diskussionsfähig.

Sie wird aktuell vor postdemodulation geprüft um möglichst viel schon vorher zu filtern. Je nachdem, was in der postdemodulation Routine passiert, ist das vielleicht mehr oder weniger sinnvoll.
Man könnte vielleicht die max Längenprüfung eventuell nach postdemodulation verschieben. Das wird aber zu mehr Aufrufen dieser Funktionen führen.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
