### ISSUE TITLE
Rauchmelder LM-101LD wird nicht erkannt von radino_CC1101-if00

### ISSUE THREAD

**Issue by Wahrschauer** [RFD-FHEM/RFFHEM#233]
Der Rauchmelder LM-101LD 
wird leider nicht erkannt von 
radino_CC1101-if00

Foto der Rauchmelders anbei.

Bin gern bereit das Gerät für Tests zur Verfügung zu stellen.

![img_4946](https://user-images.githubusercontent.com/38333032/38703666-2c0b19c4-3ea4-11e8-8800-70c68e9afb5b.JPG)

**Comment by sidey79** [comment]
Was taucht im Log bei Verbose 4 auf, wenn der Melder etwas sendet (vermutlich muss er ausgelöst werden)

**Comment by Wahrschauer** [comment]
Habe mal die MS heraussortiert

2018.04.13 14:33:23 4: CUL_433: Matched MS Protocol id 1 -> ConradRSL

2018.04.13 14:33:23 4: CUL_433/msg READ: MS;P0=-1412;P1=  786;P2=-2714;P3=-8771;P4= 240;P5=  176;D=1343521012121010101012121212121212121210121012121212;CP=1;SP=3;R=20;
2018.04.13 14:33:22 4: CUL_433/msg READ: MS;P0= -948;P3=  799;P4=-1402;P5=-8854;P6= 240;P7=  144;D=3565703430303434343430303030303030303034303430303030;CP=3;SP=5;R=20;
2018.04.13 14:33:21 4: CUL_433/msg READ: MS;P2=-1413;P3=-2717;P4=  729;P5=-8477;P6=8128;P7= -912;D=4567434243434242424243434343434343434342434243434343;CP=4;SP=5;R=21;
2018.04.13 14:33:21 4: CUL_433/msg READ: MS;P1=-2707;P2=  803;P3=-1400;P4= 8120;P5=-908;P7=-8654;D=2745212321212323232321212121212121212123212321212121;CP=2;SP=7;R=20;
2018.04.13 14:33:21 4: CUL_433/msg READ: MS;P1=-2708;P2=  796;P3=-1387;P4=-8477;P5=8136;P6= -904;D=2456212321212323232321212121212121212123212321212121;CP=2;SP=4;R=21;
2018.04.13 14:33:20 4: CUL_433/msg READ: MS;P0=-7786;P1=  787;P2=-2720;P3=-1406;P5=8112;P6= -920;D=1056121312121313131312121212121212121213121312121212;CP=1;SP=0;R=21;
2018.04.13 14:33:20 4: CUL_433/msg READ: MS;P1=-2711;P2=  797;P3=-1406;P4=-9156;P5=8120;P6= -904;D=2456212321212323232321212121212121212123212321212121;CP=2;SP=4;R=21;
2018.04.13 14:33:19 4: CUL_433/msg READ: MS;P0=-9142;P3=  806;P4=-2738;P5=-1400;P6=1448;         D=30603534343535353534343434343434343435343534343434;  CP=3;SP=0;R=24;O;
2018.04.13 14:33:18 4: CUL_433/msg READ: MS;P1=  799;P2=-1392;P3=-2704;P4=-8943;P5=8124;P6= -912;D=1456131213131212121213131313131313131312131213131313;CP=1;SP=4;R=22;
2018.04.13 14:33:17 4: CUL_433/msg READ: MS;P1=  764;P2=-1401;P3=-2729;P4=-8696;P5=8128;P6= `-904;D=1456131213131212121213131313131313131312131213131313;CP=1;SP=4;R=22;```

**Comment by Ralf9** [comment]
Welche Firmwareversion verwendest Du?
Es sind auch einige MU-Nachrichten dabei.
Mich interessiert wie es als MU-Nachrichten aussieht.
Dazu mit
set CUL_433 disableMessagetype syncedMS
die MS-Nachrichten abschalten

**Comment by Wahrschauer** [comment]
Moin, die MU-Nachrichten sind doch in dem Beitrag oben drüber schon da.

**Comment by Wahrschauer** [comment]
OK, das kann ich erst wieder am Montag abend beantworten, weil ich unterwegs bin.

**Comment by Wahrschauer** [comment]
So, hier habe ich nun die MU-Nachrichten als Datei:

[fhem433mu.txt](https://github.com/RFD-FHEM/RFFHEM/files/1915049/fhem433mu.txt)

**Comment by Ralf9** [comment]
Welche Firmware version hat dein radino?

**Comment by Wahrschauer** [comment]
TYPE
	
SIGNALduino <http://192.168.6.12:8083/fhem?cmd=list%20TYPE=SIGNALduino>
sendworking
	
0
version
	
V 3.3.1-dev SIGNALduino cc1101 (433Mhz )- compiled at Mar 10 2017 23:27:29
versionmodul
	
v3.3.3-dev_11.04.



Am 16.04.2018 16:52, schrieb Ralf9:

**Comment by Ralf9** [comment]
Ich habe mal eine erste Version in den dev-r33 branch committed, es muss evtl noch verfeinert werden.
https://github.com/RFD-FHEM/RFFHEM/commit/a3f444fe1662054be8cfedab0d38140f40d8aa8b

```
2018.04.17 19:09:22.289 4 : sduinoD/msg get raw: MS;P1=-2708;P2=796;P3=-1387;P4=-8477;P5=8136;P6=-904;D=2456212321212323232321212121212121212123212321212121;CP=2;SP=4;
2018.04.17 19:09:22.289 4 : sduinoD: Matched MS Protocol id 80 -> LM-101LD Rauchm, bitLen=24
2018.04.17 19:09:22.289 4 : sduinoD: Decoded MS Protocol id 80 dmsg U80#B0FFAF length 24
2018-04-17 19:09:22.295 SIGNALduino sduinoD DMSG U80#B0FFAF
```

**Comment by Wahrschauer** [comment]
Tut mir leid, muss mangels hinreichendem Wissen Overflow anmelden.
Versuche schon den ganzen Tag den SIGNALduino Stick zu flashen, es gelingt mir nicht.
Details in angehängter Datei. 
[flash.txt](https://github.com/RFD-FHEM/RFFHEM/files/1921127/flash.txt)

Die 2te Meldung las ich, verstanden habe ich sie nicht.

**Comment by Ralf9** [comment]
Mit dem flashen vom radino kann ich leider nicht weiterhelfen.
Du kannst mal testen ob es so wie ich es einbaut habe für Dich ausreichend ist. Dazu die MS-Nachrichten wieder aktivieren.
`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`

Auf das U80#B0FFAF event kannst Du mit einem notify oder doif reagieren.

**Comment by HomeAutoUser** [comment]
Bei mir war es so, das ich den radino nicht via Konsole flashen konnte aufgrund des anderen Bootloaders.
Den Flashvorgang habe ich direkt via der ISP Schnittstelle vorgeommen.

**Comment by Wahrschauer** [comment]
Nun hat er was angelegt

2018.04.17 22:35:14 2: autocreate: define FileLog_SD_WS_51_TH_1 FileLog ./log/SD_WS_51_TH_1-%Y.log SD_WS_51_TH_1
2018.04.17 22:35:14 2: autocreate: define SD_WS_51_TH_1 SD_WS SD_WS_51_TH_1
2018.04.17 22:35:14 1: SD_WS: UNDEFINED sensor SD_WS_51_TH detected, code SD_WS_51_TH_1
2018.04.17 22:34:58 1: CUL_433 SD_WS07: UNDEFINED sensor SD_WS07_TH_1 detected, code P7#0E809CF39
2018.04.17 22:34:05 2: autocreate: define FileLog_Unknown FileLog ./log/Unknown-%Y.log Unknown
2018.04.17 22:34:05 2: autocreate: define Unknown CUL_TCM97001 CUL_TCM97001_Unknown
2018.04.17 22:34:05 2: CUL_433: CUL_TCM97001 Unknown device Unknown, please define it

Internals:
   CFGFN      
   CODE       CUL_TCM97001_Unknown
   DEF        CUL_TCM97001_Unknown
   NAME       Unknown
   NR         551
   STATE      Defined
   TYPE       CUL_TCM97001
   lastH      0
   lastT      0
Attributes:
   room       CUL_TCM97001

Internals:
   CFGFN      
   DEF        ./log/Unknown-%Y.log Unknown
   NAME       FileLog_Unknown
   NOTIFYDEV  Unknown
   NR         552
   NTFY_ORDER 50-FileLog_Unknown
   REGEXP     Unknown
   STATE      active
   TYPE       FileLog
   currentlogfile ./log/Unknown-2018.log
   logfile    ./log/Unknown-%Y.log
Attributes:
   logtype    text
   room       CUL_TCM97001

**Comment by Wahrschauer** [comment]
Das vorher hier gepostete kam woanders her.

Nun empfing ich:
2018-04-17 22:49:19 SIGNALduino CUL_433 DMSG U80#B0FFAF
2018-04-17 22:49:22 SIGNALduino CUL_433 DMSG U80#B0FFAF

**Comment by Ralf9** [comment]
ok, das passt nun.
Wenn es so zuverlässig funktioniert, brauchst Du nicht unbedingt flashen.
Das flashen scheint beim radino nicht so einfach zu sein.

**Comment by Wahrschauer** [comment]
![000](https://user-images.githubusercontent.com/38333032/38898758-3923b724-4296-11e8-9345-ca3fd6f23561.jpg)
![001](https://user-images.githubusercontent.com/38333032/38898770-40daa4aa-4296-11e8-8307-834941dfc43e.jpg)
meldet sich als
Internals:
   CFGFN      
   CODE       SD_WS_51_TH_1
   CUL_433_DMSG W51#CB60659511
   CUL_433_MSGCNT 5
   CUL_433_RAWMSG MS;P0=-7872;P1=-4105;P2=-1860;P3=-16008;P4=1000;P6=576;P7=-1018;D=60616162626162616162616162626262626261616262616261616262616261626162626261626262616347474747;CP=6;SP=0;R=10;
   CUL_433_RSSI -69
   CUL_433_TIME 2018-04-17 23:16:37
   DEF        SD_WS_51_TH_1
   LASTInputDev CUL_433
   MSGCNT     5
   NAME       SD_WS_51_TH_1
   NR         555
   STATE      T: 22.5 H: 51
   TYPE       SD_WS
   bitMSG     1100101101100000011001011001010100010001
   lastMSG    CB60659511
   lastReceive 1523999797
   READINGS:
     2018-04-17 23:16:37   battery         ok
     2018-04-17 23:16:37   channel         1
     2018-04-17 23:16:37   humidity        51
     2018-04-17 23:16:37   state           T: 22.5 H: 51
     2018-04-17 23:16:37   temperature     22.5
     2018-04-17 23:16:37   trend           rising
Attributes:
   comment    außen Pearl FWS 150

**Comment by Ralf9** [comment]
@sidey79 
gibt es in github die Möglichkeit danach zu suchen ob es bereits ein issue zu der ID 51 gibt?

**Comment by Wahrschauer** [comment]
Moin,
habe noch einen 2ten LM-101LD in Betrieb genommen.

Der meldet sich so:
Internals:
   CFGFN      
   CODE       FE7D82
   CUL_433_DMSG P13#FE7D82
   CUL_433_MSGCNT 9
   CUL_433_RAWMSG MU;P0=-2739;P1=788;P2=-1555;P3=-20004;P4=8132;P5=-928;P6=552;D=012121212121012121010101010121013451212121212121210101212121212101212101010101012101345121212121212121010121262;CP=1;R=4;
   CUL_433_RSSI -72
   CUL_433_TIME 2018-04-18 08:29:07
   DEF        FE7D82
   IODev      CUL_433
   LASTInputDev CUL_433
   MSGCNT     9
   NAME       FLAMINGO_FE7D82
   NR         1556
   STATE      no alarm
   TYPE       FLAMINGO
   bitMSG     
   lastMSG    
   lastReceive 1524032947
   READINGS:
     2018-04-18 08:29:07   state           no alarm | im Alarmfall state alarm, stetig wechselnd
Attributes:
   IODev      CUL_433

Das muss man nicht verstehen.

**Comment by elektron-bbs** [comment]
Nochmal zum Flashen des Radino: Der Bootloader muss manuell gestartet werden. Es werden aber auch noch zwei verschiedene Bootloader eingesetzt. Je nach Variante sind verschiedene Tastenbetätigungen notwendig.

Variante 1:
Force the radino into bootloader by pressing reset button twice 
Now the L-LED should fading and the correct serial port will be visible 

Variante 2:
Press & hold BSL- and RESET-Button 
Release RESET-button 
Release BSL-button

**Comment by Ralf9** [comment]
@Wahrschauer 
So wies aussieht sind die Nachrichten ähnlich dem Flamingo FA20RF / FA21RF.
Evtl ist der LM-101LD bau- oder funktionsgleich wie der Flamingo?
Gibt es beim LM-101LD auch Master und Slave?
https://forum.fhem.de/index.php/topic,57735.msg499476.html#msg499476

**Comment by elektron-bbs** [comment]
Die Teile sehen zumindest ziemlich gleich aus und werden vertrieben unter Jucon, Renkforce und Flamingo.

**Comment by Wahrschauer** [comment]
Hatte beide Bootloader-Varianten probiert, ging nicht.

Die Anleitung passt haargenau.
Hatte auch den schlechten mal mit dem guten gekoppelt.
Habe ich verworfen, denn dann
weiß ich zwar dass, aber nicht wo es brennt.

Udo <notifications@github.com> schrieb am Mi., 18. Apr. 2018, 21:09:

**Comment by sidey79** [comment]
@Ralf9 

Ja man kann danach suchen. Leider haben wir kein festes Schema und eine 51 kommt durchaus öfters mal vor. Ich habe jetzt einfach via BLAME Funktion nachgesehen, mit welchen commits etwas an protokoll51 geändert wurde und bin dabei auf #118 gestoßen.

**Comment by Ralf9** [comment]
Dann ist es besser, wenn ich die ID 80 nach ID 13.2 ändere.
Ich habe es mir mal angeschaut, warum die Rauchmelder als verschiedene IDs erkannt werden.
Das Problem ist, daß der zweite Wert beim sync/start bei den verschiedenen Rauchmeldern recht stark schwankt.
Ist der zweite Wert ca -16000 ist es ID 13
Ist der zweite Wert ca -9000 ist es ID 13.2
Ist der zweite Wert  > -17000 ist es ID 13.1. Wegen syncMaxMicros 17000 wird sie dann als MU-Nachricht erkannt.

```
ID 13    sync	=> [1,-20,   10, -1],
ID 13.1  start	=> [  -23.5, 10, -1],
ID 13.2  sync	=> [1,-11,   10, -1.2],
```

Wenn es die Möglichkeit geben würde, bei sync/start einen Bereich anzugeben, dann könnten wir auf die ID 13.2 verzichten.
z.B.:
`ID 13    sync	=> [1, -10 to -20,   10,  -1],`

**Comment by Ralf9** [comment]
Ich habe die ID 80 in ID 13.2 geändert
https://github.com/RFD-FHEM/RFFHEM/commit/1a988276148dfd4eb968d40df981bcaa217a04c1

**Comment by Wahrschauer** [comment]
Danke sehr.
Nach obiger Änderung musste ich die alte Definition und auch die DOIF löschen und neu anlegen (lassen).
Nun meldet sich auch der ursprüglich (ganz oben erklärte) RM völlig korrekt.

Außerdem funktioniert nun auch das ganz alte Modell dieser Baureihe (siehe Foto) korrekt
![000 1](https://user-images.githubusercontent.com/38333032/39129975-45cfc86c-470c-11e8-9a07-0e704a516732.jpg)
und meldet sich so:
Internals:
   CFGFN      
   CODE       32E44F
   CUL_433_DMSG P13#32E44F
   CUL_433_MSGCNT 9
   CUL_433_RAWMSG MS;P0=-1413;P1=757;P2=-2779;P3=-16079;P4=8093;P5=-954;D=1345121210101212101210101012121012121210121210101010;CP=1;SP=3;R=33;O;
   CUL_433_RSSI -57.5
   CUL_433_TIME 2018-04-23 15:19:29
   DEF        32E44F
   IODev      CUL_433
   LASTInputDev CUL_433
   MSGCNT     9
   NAME       FLAMINGO_32E44F
   NR         5723
   STATE      no alarm
   TYPE       FLAMINGO
   bitMSG     
   lastMSG    
   lastReceive 1524489569
   READINGS:
     2018-04-23 15:19:29   state           no alarm | Alarm bei Alarm abwechseld mit no alarm
Attributes:
   IODev      CUL_433
   room       Rauchmelder

Aber Vorsicht: wer das alte Modell verwenden möchte, der sollte wissen, dass diese bei Alarmende nicht automatisch wieder aufhört. Man muss die 9V-Batterie entfernen für Ruhe.

**Comment by HomeAutoUser** [comment]
@Wahrschauer 
wird der Rauchmelder bei dir nun erkannt? Wenn ja, könnte das Thema als erledigt betrachet werden oder gibt es noch einwände?

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
