### ISSUE TITLE
LIDL Florabest Funk Grill Thermometer FFGT 433 A1

### ISSUE THREAD

**Issue by DuschdrBabbe** [RFD-FHEM/RFFHEM#234]
## Gerät das nicht erkannt wird:
LIDL Florabest Funk Grill Thermometer FFGT 433 A1
https://www.lidl.de/de/florabest-funk-grillthermometer/p271491
[log.txt](https://github.com/RFD-FHEM/RFFHEM/files/1906881/log.txt)

## SIGNALduino-Hardware:
Arduino Nano CC1101 
V 3.3.1-RC4 SIGNALduino cc1101 - compiled at Mar 10 2018 23:20:23

## Fhem defmod SIGNALduino (v3.3.3-dev_11.04.)
```
defmod SIGNALduino SIGNALduino /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0@57600
attr SIGNALduino flashCommand avrdude -c arduino -b [BAUDRATE] -P [PORT] -p atmega328p -vv -U flash:w:[HEXFILE] 2>[LOGFILE]
attr SIGNALduino hardware nanoCC1101
attr SIGNALduino room System->Bridge
setstate SIGNALduino opened
setstate SIGNALduino 2018-04-08 14:25:02 ccconf freq:433.920MHz bWidth:325KHz rAmpl:42dB sens:4dB  (DataRate:5603.79Baud)
setstate SIGNALduino 2018-04-08 14:25:15 config MS=1;;MU=1;;MC=1;;Mred=0
setstate SIGNALduino 2018-04-13 10:54:21 ping OK
setstate SIGNALduino 2018-04-13 11:38:27 state opened
setstate SIGNALduino 2018-04-13 11:38:27 version V 3.3.1-RC4 SIGNALduino cc1101  - compiled at Mar 10 2018 23:20:23
```

## Angelegtes device durch Autoreate:

```
defmod Unknown CUL_TCM97001 CUL_TCM97001_Unknown
attr Unknown alias florabest
attr Unknown model Unknown
attr Unknown room _Neue_
setstate Unknown Code: E2883574
setstate Unknown 2018-04-13 11:51:16 state Code: E2883574
```

## Log Verbose 4 Device

```
2018.04.13 11:50:26 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288358800) length: 10
2018.04.13 11:50:26 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288358800
2018.04.13 11:50:30 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288358800) length: 10
2018.04.13 11:50:30 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288358800
2018.04.13 11:50:34 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288358400) length: 10
2018.04.13 11:50:34 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288358400
2018.04.13 11:50:38 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288358400) length: 10
2018.04.13 11:50:38 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288358400
2018.04.13 11:50:42 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288358400) length: 10
2018.04.13 11:50:42 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288358400
2018.04.13 11:50:47 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288357800) length: 10
2018.04.13 11:50:47 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288357800
2018.04.13 11:50:51 4: SIGNALduino: CUL_TCM97001 Unknown 226 (E288357800) length: 10
2018.04.13 11:50:51 4: SIGNALduino: CUL_TCM97001 Device not implemented yet name Unknown msg E288357800

```
## Log Verbose 4 SIGNALduino

```
2018.04.13 11:52:03 4: SIGNALduino/msg READ: MS;P1=-2000;P2=517;P3=-3992;P4=-8966;D=24232323212121232123212121232121212121232321232123212323212121;CP=2;SP=4;R=249;O;m2;
2018.04.13 11:52:03 4: SIGNALduino: Matched MS Protocol id 0 -> weather1
2018.04.13 11:52:03 5: SIGNALduino: Starting demodulation at Position 2
2018.04.13 11:52:03 4: SIGNALduino: Decoded MS Protocol id 0 dmsg sE288356000 length 32 RSSI = -77.5
2018.04.13 11:52:03 5: SIGNALduino Dispatch: sE288356000, test gleich
2018.04.13 11:52:03 5: SIGNALduino Dispatch: sE288356000, -77.5 dB, dispatch
2018.04.13 11:52:03 5: SIGNALduino: dispatch sE288356000
2018.04.13 11:52:03 4: SIGNALduino: Matched MS Protocol id 68 -> PFR-130
2018.04.13 11:52:03 5: SIGNALduino: Starting demodulation at Position 2
2018.04.13 11:52:03 4: SIGNALduino: Decoded MS Protocol id 68 dmsg sE288356000 length 32 RSSI = -77.5
2018.04.13 11:52:03 5: SIGNALduino Dispatch: sE288356000, test gleich
2018.04.13 11:52:03 4: SIGNALduino Dispatch: sE288356000, Dropped due to short time or equal msg
2018.04.13 11:52:03 4: SIGNALduino/msg READ: MS;P1=-1996;P2=516;P3=-3995;P4=-8972;D=24232323212121232123212121232121212121232321232123212323212121;CP=2;SP=4;R=249;O;m1;
2018.04.13 11:52:03 4: SIGNALduino: Matched MS Protocol id 0 -> weather1
2018.04.13 11:52:03 5: SIGNALduino: Starting demodulation at Position 2
2018.04.13 11:52:03 4: SIGNALduino: Decoded MS Protocol id 0 dmsg sE288356000 length 32 RSSI = -77.5
```

mehr im Log.txt oben

**Comment by HomeAutoUser** [comment]
Hallo, es wäre sehr hilfreich, wenn du das selbe erneut machst, aber parallel dazu das Display abliest und kommentierst. Das kann viel erleichtern und man weiß worauf man hinarbeiten müßte ;-)

Wenn du vielleicht das hinbekommst, wenn nur eine Änderung erfolgt, wäre das "einfacher".
Bsp: 1) Target 22 / Current 21 / Well || 2) Target 23 / Current 21 / Well ...

**Comment by HomeAutoUser** [comment]
Hallo Pascal,
danke für die Messungen.

Für eine Auswertung wäre es schön, wenn die Werte sich mehrfach verändern ABER nur bestmöglich einmal ;-) (in dem Beispiel das Current)

>3)Eingestellt Rind Target:71 Current :27 MEDIUM
>4)Eingestellt Rind Target:71 Current :36 MEDIUM

Da kannst du gern ja mal sammeln.
Man muss versuchen an der Stelle anzusetzen wo sich so wenig wie möglich verändert.

Was für Änderungensschritte (Auflösung) gibt das Display her?

- GradCelsius ohne Kommastelle?
- Zustand WELL .... (3 verschiedene?  oder mehr)
....

**Comment by RaiderXXL** [comment]
Hallo,

Das Gerät Sendet (denke ich ) nur den Batteriestatus und die Temperatur an das Display, diese Zeigt Grad in ganzen Zahlen ohne Komma. Kann beim Sender am Boden auf Fahrenheit umgestellt werden.
Ich versuche mein bestes da bei uns Funktechnisch einiges los ist und ich nicht immer genau sagen kann das kommt jetzt von dem oder von dem Gerät. Außerdem habe ich Schwierigkeiten beim Synchronisieren der Daten da ich Über das log nur Zeitversetzt rankomme um die Display Werte zu den Datensätzen zuzuordnen...

weitere Daten folgen...

**Comment by RaiderXXL** [comment]
Und wieder eine Messung... 

[neue messung1.txt](https://github.com/RFD-FHEM/RFFHEM/files/1923063/neue.messung1.txt)

**Comment by HomeAutoUser** [comment]
Hallo @RaiderXXL,
erstmal danke für deine Mühe der Messungen.

>2018-04-18 10:21:32 CUL nanoCUL UNKNOWNCODE p11  512 3984  496 4000  496 2000  30  1  3 6   496  8976     0 2A E288419C

Was sind dies für Zahlen oder wie kamen diese zu stande? Ohne Erklärung diesbezüglich kann man da nichts anfangen mit.
- P11 ist sicherlich das Protokoll
- letzten Zahlen wie E288419C sind das die Dispatch?

>2018.04.14 14:06:57 4: SIGNALduino/msg READ: MS;P1=-3996;P2=508;P3=-2005;P4=-8974;D=24212121232323212321232323212323232323212123212321212123232323;CP=2;SP=4;R=1;O;m0;
So wären sie am schönsten aber gern kannst du mir deine Liste erläutern wie diese zustande kam.

**Comment by RaiderXXL** [comment]
Hallo,

anbei das Device:
`defmod SIGNALduino_unknown_0 SIGNALduino_un SIGNALduino_unknown_0
attr SIGNALduino_unknown_0 IODev SIGNALduino
attr SIGNALduino_unknown_0 room _Neue_
attr SIGNALduino_unknown_0 stateFormat {ReadingsVal('SIGNALduino_unknown_0', 'state', '').' | '.ReadingsTimestamp('SIGNALduino_unknown_0', 'state', '-');;}

setstate SIGNALduino_unknown_0 E288353C | 2018-10-09 11:00:23
setstate SIGNALduino_unknown_0 2018-10-09 10:58:40 UserMSG Rind D82 T26 Well
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 bitCount 32
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 bitMsg 11100010100010000011010100111100
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 bitMsg_invert 00011101011101111100101011000011
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 hexCount or nibble 8
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 hexMsg E288353C
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 hexMsg_invert 1D77CAC3
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 lastInputDev SIGNALduino
setstate SIGNALduino_unknown_0 2018-10-09 11:00:23 state E288353C

`

Falls du weiterkommst gut aber für mich hat sich das Thema erledigt...
Danke vielmals für deine Zeit und Hilfe!

Pascal

**Comment by HomeAutoUser** [comment]
Hallo Pascal,

danke für deinen einen Eintrag.
Leider können wir mit nur einem Eintrag kein Protokoll implementieren.
Wenn das Thema für dich erledigt ist, so würden wir das Thema abhaken wenn du einverstanden bist.

Solltest du natürlich dennoch Interesse / ein wenig Gedult und Mithilfe beisteuern in Form von mehreren solchen Auszügen oder sogar die komplette **SIGNALduino_unknown_0.log Datei**, so bestände die möglichkeit das Ziel zu erreichen :-)

Man muss das Protokoll "erarbeiten" und dann den Code im Cul_TCM Modul erweitern.
LG Marco

**Comment by elektron-bbs** [comment]
> 
> Falls du weiterkommst gut aber für mich hat sich das Thema erledigt...
> Danke vielmals für deine Zeit und Hilfe!
> 
> Pascal

Da sich das Thema für den User erledigt hat, können wir das Issue wohl schließen.
