### ISSUE TITLE
Protokoll Liste auslagern

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#240]
## Expected Behavior

Die Protokolldefinitionen sind unabhängiger von der Modulentwicklung und können einfacher ausgetauscht / aktualisiert werden.

## Actual Behavior

Modul und Protokolle befinden sich in einem perl Modul und können nur in Kombination aktualisiert werden.
Dadurch kommt es zu Abhängigkeiten.

**Comment by sidey79** [comment]
@Ralf9 
@HomeAutoUser 

Ich habe eine sehr einfache Möglichkeit gefunden, die Protokoll Liste in einer separaten Datei auszulagern.
Klappt bei mir auch super. Änderungen an den Prokokollen müssen dadurch aber jetzt in der separaten Datei vorgenommen werden.
Über fhemweb kann man leider Dateien in Unterverzeichnissen nicht editieren.

**Comment by HomeAutoUser** [comment]
@sidey79, ist der Issues nocht gültig oder kann dieser CLOSED?
