### ISSUE TITLE
function developId incorrect ?

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#242]
## Expected Behavior
Testing and correction code

## Actual Behavior
Sobald nur eine developId (wie 80y,) eingetragen wird, so erscheint auch Bsp: u63 Protokoll welches in der Entwicklung ist aber bei mir NICHT unter developId eingetragen ist. Sobald ich alle Einträge aus developId heraus lösche, so erscheint auch keine u63 mehr im Logfile.
Vermutung die Funktion "developId" funktioniert nicht korrekt

## Steps to Reproduce the Problem

  1. developId definieren 80y
  2. Kontrolle Logfile wenn man Protokoll 63 empfängt (obwohl es nicht in developId definert ist)

>"63" => ## Warema MU
		{    #MU;P0=-2988;P1=1762;P2=-1781;P3=-902;P4=871;P5=6762;P6=5012;D=0121342434343434352434313434243521342134343436;
			name         => 'Warema',
			comment      => 'developId, is still experimental',
			id           => '63',
			developId    => 'y',
			one          => [1],
			zero         => [0],
			clockabs     => 800, 
			syncabs		 => '6700',# Special field for filterMC function
			preamble     => 'u63', # prepend to converted message
			#clientmodule => '', 
			#modulematch => '', 
			length_min   => '24',
			filterfunc   => 'SIGNALduino_filterMC',

  3. sämtliche Einträge in developId entfernen und sofort ist auch keine Empfang des u63 mehr vorhanden
  4. mehrfach reproduzierbar

## Specifications

  - Version: v3.3.3-dev_20.04.
  - Microcontroller: Nano + Radino

**Comment by Ralf9** [comment]
Ich habe mir das mit den developIds mal angeschaut. Das passt noch nicht ganz.
Ich habe es bei mir ein wenig angepasst.

Nun ist das Verhalten wie folgt:

Die whitelist_IDs haben nun vorrang vor der developId option.
Wenn im development Attribut "y" enthalten ist, dann werden alle Protokolle mit  developId => 'y' verwendet.
Wenn im development Attribut "p" gefolgt von der ID eingetragen wird, dann wird nur diese developId verwendet.

Mit z.B. attr development p63p78
werden nur die developId 63 und 78 verwendet.

Ist diese Verhalten so ok?

```
sub SIGNALduino_IdList($@)
{
	my ($param, $aVal, $blacklist, $develop) = @_;
	my (undef,$name) = split(':', $param);
	my $hash = $defs{$name};

	my @msIdList = ();
	my @muIdList = ();
	my @mcIdList = ();

	if (!defined($aVal)) {
		$aVal = AttrVal($name,"whitelist_IDs","");
	}
	Log3 $name, 3, "$name sduinoIdList: whitelistIds=$aVal";
	
	if (!defined($blacklist)) {
		$blacklist = AttrVal($name,"blacklist_IDs","");
	}
	Log3 $name, 3, "$name sduinoIdList: blacklistIds=$blacklist";
	
	if (!defined($develop)) {
		$develop = AttrVal($name,"development","");
	}
	$develop = lc($develop);
	Log3 $name, 3, "$name sduinoIdList: development=$develop";

	my %WhitelistIDs;
	my %BlacklistIDs;
	my $wflag = 0;		# whitelist flag, 0=disabled
	my $bflag = 0;		# blacklist flag, 0=disabled
	if (defined($aVal) && length($aVal)>0)
	{
		if (substr($aVal,0 ,1) eq '#') {
			Log3 $name, 3, "$name Attr whitelist disabled: $aVal";
		}
		else {
			%WhitelistIDs = map { $_ => 1 } split(",", $aVal);
			#my $w = join ', ' => map "$_" => keys %WhitelistIDs;
			#Log3 $name, 3, "Attr whitelist $w";
			$wflag = 1;
		}
	}
	if ($wflag == 0) {		# whitelist disabled
		if (defined($blacklist) && length($blacklist)>0) {
			%BlacklistIDs = map { $_ => 1 } split(",", $blacklist);
			my $w = join ', ' => map "$_" => keys %BlacklistIDs;
			Log3 $name, 3, "$name Attr blacklist $w";
			$bflag = 1;
		}
	}
	
	my $id;
	my $devid;
	my $wIdFound;
	foreach $id (keys %ProtocolListSIGNALduino)
	{
		next if ($id eq 'id');
		$wIdFound = 0;
		
		if ($wflag == 1)				# whitelist
		{
			if (defined($WhitelistIDs{$id}))	# Id wurde in der whitelist gefunden
			{
				$wIdFound = 1;
			}
			else
			{
				#Log3 $name, 3, "skip ID $id";
				next;
			}
		}
		
		if ($wIdFound == 0)	# wenn die Id in der whitelist gefunden wurde, dann die folgenden Abfragen ueberspringen
		{
			if ($bflag == 1 && defined($BlacklistIDs{$id})) {
				Log3 $name, 3, "$name skip Blacklist ID $id";
				next;
			}
		
			if (defined($ProtocolListSIGNALduino{$id}{developId}) && substr($ProtocolListSIGNALduino{$id}{developId},0,1) eq "p") {
				$devid = "p$id";
				if ($develop !~ m/$devid/) {						# skip wenn die Id nicht im Attribut development steht
					Log3 $name, 3, "$name: ID=$devid skiped (developId=p)";
					next;
				}
			}
		
			if (defined($ProtocolListSIGNALduino{$id}{developId}) && substr($ProtocolListSIGNALduino{$id}{developId},0,1) eq "y") {
				$devid = "p$id";
				if (($develop !~ m/y/) && ($develop !~ m/$devid/)) {			# skip wenn y nicht im Attribut development steht
					Log3 $name, 3, "$name: ID=$id skiped (developId=y)";
					next;
				}
			}
		}
		
		if (exists ($ProtocolListSIGNALduino{$id}{format}) && $ProtocolListSIGNALduino{$id}{format} eq "manchester")
		{
			push (@mcIdList, $id);
		} 
		elsif (exists $ProtocolListSIGNALduino{$id}{sync})
		{
			push (@msIdList, $id);
		}
		elsif (exists ($ProtocolListSIGNALduino{$id}{clockabs}))
		{
			push (@muIdList, $id);
		}
	}

	@msIdList = sort @msIdList;
	@muIdList = sort @muIdList;
	@mcIdList = sort @mcIdList;

	Log3 $name, 3, "$name: IDlist MS @msIdList";
	Log3 $name, 3, "$name: IDlist MU @muIdList";
    Log3 $name, 3, "$name: IDlist MC @mcIdList";
	
	$hash->{msIdList} = \@msIdList;
    $hash->{muIdList} = \@muIdList;
    $hash->{mcIdList} = \@mcIdList;
}
```

**Comment by Ralf9** [comment]
Hier ist ein Vergleich meiner Änderung:

Derzeitiger Code:
```
	my $id;
	foreach $id (keys %ProtocolListSIGNALduino)
	{
		next if ($id eq 'id');
		if ($wflag == 1 && !defined($WhitelistIDs{$id}))
		{
			#SIGNALduino_Log3 $name, 3, "skip ID $id";
			next;
		}
		if ($bflag == 1 && defined($BlacklistIDs{$id}))
		{
			SIGNALduino_Log3 $name, 4, "$name skip Blacklist ID $id";
			next;
		}
		
		if (defined($ProtocolListSIGNALduino{$id}{developId}) && substr($ProtocolListSIGNALduino{$id}{developId},0,1) eq "p") {
			my $devid = "p$id";
			if ($develop !~ m/$devid/) {		# skip wenn die Id nicht im Attribut development steht
				SIGNALduino_Log3 $name, 3, "$name: ID=$devid skiped (developId=p)";
				next;
			}
		}
		
		if (defined($ProtocolListSIGNALduino{$id}{developId}) && substr($ProtocolListSIGNALduino{$id}{developId},0,1) eq "y") {
			if ($develop !~ m/y/) {			# skip wenn y nicht im Attribut development steht
				SIGNALduino_Log3 $name, 3, "$name: ID=$id skiped (developId=y)";
				next;
			}
		}
```
meine geänderter Code:
```
	my $id;
	my $devid;
	my $wIdFound;
	foreach $id (keys %ProtocolListSIGNALduino)
	{
		next if ($id eq 'id');
		$wIdFound = 0;
		
		if ($wflag == 1)				# whitelist
		{
			if (defined($WhitelistIDs{$id}))	# Id wurde in der whitelist gefunden
			{
				$wIdFound = 1;
			}
			else
			{
				#Log3 $name, 3, "skip ID $id";
				next;
			}
		}
		
		if ($wIdFound == 0)	# wenn die Id in der whitelist gefunden wurde, dann die folgenden Abfragen ueberspringen
		{
			if ($bflag == 1 && defined($BlacklistIDs{$id})) {
				SIGNALduino_Log3 $name, 3, "$name IdList: skip Blacklist ID $id";
				next;
			}
		
			if (defined($ProtocolListSIGNALduino{$id}{developId}) && substr($ProtocolListSIGNALduino{$id}{developId},0,1) eq "p") {
				$devid = "p$id";
				if ($develop !~ m/$devid/) {						# skip wenn die Id nicht im Attribut development steht
					SIGNALduino_Log3 $name, 3, "$name IdList: ID=$devid skiped (developId=p)";
					next;
				}
			}
		
			if (defined($ProtocolListSIGNALduino{$id}{developId}) && substr($ProtocolListSIGNALduino{$id}{developId},0,1) eq "y") {
				$devid = "p$id";
				if (($develop !~ m/y/) && ($develop !~ m/$devid/)) {			# skip wenn y nicht im Attribut development steht
					SIGNALduino_Log3 $name, 3, "$name IdList: ID=$id skiped (developId=y)";
					next;
				}
			}
		}
```

**Comment by sidey79** [comment]
@HomeAutoUser 
Das ist gefixt oder?

**Comment by HomeAutoUser** [comment]
Ich denke es ist gefixt, wennn ich deine Frage auf MEINEN ersten Post beziehe.

Soeben habe ich es versucht nachzuvollziehen nach der Zeit.
Vorgehensweise, dummy auf developID y90 gestellt und auch nur diese kommt. Gegenprobe, ohne developID y63 habe ich eine MU Message von 63 dispatched und alles blieb stillt.

Ich würde es als erledigt ansehen.

Ralf seine vorgeschlagene Variante ist in der dev-r33 nicht implementiert.

**Comment by HomeAutoUser** [comment]
@sidey79 , ähm

>all IDs in the development attribute with developId => 'y' are used

nein so klappt es nicht. 

Ich habe es auf nur y definiert und eine Message von einem devID dispatched und nichts passierte.

**Comment by sidey79** [comment]
@HomeAutoUser 
War in dem Protokoll developID = 'y' gesetzt?

**Comment by HomeAutoUser** [comment]
>War in dem Protokoll developID = 'y' gesetzt?

JA ich hatte nur ein einzelnes y eingetragen

**Comment by sidey79** [comment]
ok ich habe mich falsch ausgedrückt sorry. Ich meinte ob das passende Protokoll development = 'y' gesetzt hat :)

` # developId   => 'y'       # protocol is under development, all IDs in the development attribute with developId => 'y' are used
 `

**Comment by HomeAutoUser** [comment]
mit dem Eintrag im Attribut developId =>

` y73` geht das einzelne Dev-Protokoll
` y` spricht kein Dev-Protokoll an

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
