### ISSUE TITLE
Dopplung Protokoll 0 und 68 - eines könnte entfernt werden?

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#248]
## Expected Behavior
- Nach Prüfung und Beurteilung eine Definition herausnehmen da unnötig

## Actual Behavior
-  Der Wettersensor PF130 - wird bei beiden Protokollen gematch.
>2018.07.04 23:39:26 4: nano_433Mhz: Matched MS Protocol id 0 -> weather1
2018.07.04 23:39:26 4: nano_433Mhz: Decoded MS Protocol id 0 dmsg s116C00000000 length 40 RSSI = -38.5
2018.07.04 23:39:26 4: nano_433Mhz Dispatch: s116C00000000, Dropped due to short time or equal msg
2018.07.04 23:39:26 4: nano_433Mhz: Matched MS Protocol id 68 -> PFR-130
2018.07.04 23:39:26 4: nano_433Mhz: Decoded MS Protocol id 68 dmsg s116C00000000 length 40 RSSI = -38.5
2018.07.04 23:39:26 4: nano_433Mhz Dispatch: s116C00000000, Dropped due to short time or equal msg

## Specifications

>    "0"    => 
        {
            name			=> 'weather1',		# Logilink, NC, WS, TCM97001 etc.
			comment		=> 'Logilink, NC, WS, TCM97001 etc',
			id          	=> '0',
			one				=> [1,-8],
			zero			=> [1,-4],
			sync			=> [1,-18],		
			clockabs   		=> '500',		# not used now
			format     		=> 'twostate',  # not used now
			preamble		=> 's',			# prepend to converted message	 	
			postamble		=> '00',		# Append to converted message	 	
			clientmodule    => 'CUL_TCM97001',   # not used now
			#modulematch     => '^s[A-Fa-f0-9]+', # not used now
			length_min      => '24',
			length_max      => '42',
			paddingbits     => '8',				 # pad up to 8 bits, default is 4
        },
		
		
>  "68" => ##  PFR-130 ###########################################################################
		{
    # MS;P0=-3890;P1=386;P2=-2191;P3=-8184;D=1312121212121012121212121012121212101012101010121012121210121210101210101012;CP=1;SP=3;R=20;O;
    # MS;P0=-2189;P1=371;P2=-3901;P3=-8158;D=1310101010101210101010101210101010121210121212101210101012101012121012121210;CP=1;SP=3;R=20;O;
			name         => 'PFR-130',
			id           => '68',
      		one				=> [1,-10],
			zero			=> [1,-5],
      		sync			=> [1,-21],	
			clockabs   		=> 380,		# not used now
      		preamble		=> 's',			# prepend to converted message	 	
			postamble		=> '00',		# Append to converted message	 	
			clientmodule    => 'CUL_TCM97001',   # not used now
     		length_min      => '24',
			length_max      => '42',
			paddingbits     => '8',				 # pad up to 8 bits, default is 4
		}, 

------------------

Eine Andere Überlegung könnte sein, das man solche Fälle aufgreift und die "Decode Schleife" abbricht weil ein Match erfolgte. Wie steht Ihr dazu?

**Comment by sidey79** [comment]
Die decode Schleife abbrechen habe ich deshalb nicht eingebaut, da nicht eindeutig zurück kommt, ob der Datensatz vollständig korrekt verarbeitet wurde. So würde man halt unter Umständen dann doch abbrechen.

Die Protokoll ID 68 hat bestimmt den Hintergrund, dass der genannte Sensor nicht immer im Toleranzbereich der ID 0 liegt.

**Comment by HomeAutoUser** [comment]
`Die Protokoll ID 68 hat bestimmt den Hintergrund, dass der genannte Sensor nicht immer im Toleranzbereich der ID 0 liegt.`

Einspruch.
Es werden immer beide genommen. Die Protokoll 68 wird sofort bei der 0 mit Dispatcht.
>2018.07.03 23:54:21 4: nano_433Mhz/msg READredu: MS;P3=-2038;P4=468;P5=-9081;P6=-4050;D=45434343464343434643464643464643434343434343434343434343434343434343434343;CP=4;SP=5;R=75;m=0;
2018.07.03 23:54:21 4: nano_433Mhz: Matched MS Protocol id 0 -> weather1
2018.07.03 23:54:21 4: nano_433Mhz: Decoded MS Protocol id 0 dmsg s116C00000000 length 40 RSSI = -36.5
2018.07.03 23:54:21 4: nano_433Mhz Dispatch: s116C00000000, Dropped due to short time or equal msg
2018.07.03 23:54:21 4: nano_433Mhz: Matched MS Protocol id 68 -> PFR-130
2018.07.03 23:54:21 4: nano_433Mhz: Decoded MS Protocol id 68 dmsg s116C00000000 length 40 RSSI = -36.5
2018.07.03 23:54:21 4: nano_433Mhz Dispatch: s116C00000000, Dropped due to short time or equal msg

`Die decode Schleife abbrechen habe ich deshalb nicht eingebaut, da nicht eindeutig zurück kommt, ob der Datensatz vollständig korrekt verarbeitet wurde. So würde man halt unter Umständen dann doch abbrechen.`

Was hälst du von der Variante? Ich habe mal einen Test gemacht und deine Dispatch mit einem Rückgabewert versehen. Wenn ein Modul richtig übergeben wurde, so erhält man die Hash Referenzt zurück. bei einer Doppelten Nachricht kommt "double" zurück von Dispatch und sollte nichts passen, so ist "" drin. Code könnte ich dir geändert mal zukommen lassen. Ich lasse dies bei mir Probelaufen soeben und sobald ein Dispatch richtig erfolgte bricht die Schleife ab. Dadurch erziele ich bei meinen vielen Sensoren einen Performencgewinn.

**Comment by HomeAutoUser** [comment]
@sidey79 
>Die decode Schleife abbrechen habe ich deshalb nicht eingebaut, da nicht eindeutig zurück kommt, ob der Datensatz vollständig korrekt verarbeitet wurde. So würde man halt unter Umständen dann doch abbrechen.

Ich fasse mal deine Aussage erneut auf. Ein abbrechen der Decode Schleife ist nicht vorgesehen oder umgesetzt derzeit. Wenn man den Dispatch ggf. anpassen würde, so würden wir eine Meldung zurück erhalten ob er richtig weiter gegeben wurde. Wäre das im Sinne von dir ? Sobald die Nachricht von einem Dispatch abgegeben wurde, so wird nicht weiter gelaufen.

Zur Einschätzung mal der Code als Stücke. Ein PR gern bei Interesse.

```
sub SIGNALduno_Dispatch($$$$$)
{
....
		SIGNALduino_Log3 $name, SDUINO_DISPATCH_VERBOSE, "$name Dispatch: $dmsg, $rssi dispatch";
		#Dispatch($hash, $dmsg, \%addvals);  ## Dispatch to other Modules
		
		############################### NEW ###############################
		my $rcode = Dispatch($hash, $dmsg, \%addvals); # ARRAY(xxxx) OK / doppelte Message oder kein I.O ""
		return $rcode;
		
	}	else {
		SIGNALduino_Log3 $name, 4, "$name Dispatch: $dmsg, Dropped due to short time or equal msg";
		return "double";
		############################### END ###############################
```

```
sub
SIGNALduino_Parse_MS($$$$%)
{
...
				############################### NEW ###############################
				#SIGNALduno_Dispatch($hash,$rmsg,$dmsg,$rssi,$id);
				my $rcode = SIGNALduno_Dispatch($hash,$rmsg,$dmsg,$rssi,$id);
				if (not defined $rcode) { $rcode = "" };	# sonst PERL WARNINGS
				if ($rcode ne "") { $message_dispatched=1 };
				#SIGNALduino_Log3 $name, 3, "$name: Dispatch rcode=$rcode message_dispatched=$message_dispatched";
				if ($message_dispatched == 1) { return };
				############################### END ###############################
				
			}
```
