### ISSUE TITLE
Protocol for HE850 HE800 Home Easy

### ISSUE THREAD

**Issue by SirIcy** [RFD-FHEM/RFFHEM#249]
## Expected Behavior
Autocreate Home Easy Device HE850 or at least work with manual created Home Easy devices.

## Actual Behavior
No Autocreate; Created devices cannot be controlled by Signalduino

## Steps to Reproduce the Problem

  1. Press button at Home Easy Remote Control
  2. Turn Home Easy Device on in fhem
  3. nothing happens

## Specifications

  - Version: V 3.3.1-dev SIGNALduino cc1101
  - Microcontroller: Arduino Nano

Solved by this post:
https://forum.fhem.de/index.php/topic,36399.105.html

**Comment by HomeAutoUser** [comment]
Hallo @SirIcy,

ich habe soeben mir beiden Varianten
> get sduino_dummy raw   MS;;P0=-4853;;P1=905;;P2=-376;;P3=277;;P4=-1001;;D=3012341234341212121234123412121234343412341212343412123434;;CP=3;;SP=0;;O;;m0;;


> get sduino_dummy raw   MS;;P1=223;;P2=-1339;;P3=-317;;P4=-8926;;D=14121213131312121212131313121212121313121212131213121213121312131312121313121313121312131213131213121212131312121312;;CP=1;;SP=4;;O;;m0;;

das Ganze AutoCreate nachgestellt und es funktionierte. Laut Actual Behavior wird ein AutoCreate bei dir nicht durchgeführt? Eine Steuerung via FHEM ist meinerseits natürlich nicht testbar, da ich nicht solche Geräte besitze.

Ist dein Problem noch aktuell?

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
