### ISSUE TITLE
Protokoll für m-e BELL-201-TX (Funkgong)

### ISSUE THREAD

**Issue by a13xde** [RFD-FHEM/RFFHEM#252]
### Gerät
- m-e BELL-201-TX (Funkgong)
- Frequenz: 434 MHz
- Hersteller-Infos: https://shop-m-e.de/produkte/tuerglocken/funk-gongs/funk-tuerglockensystem-bell/116/zusatz-sender-fuer-1-2-und-3-familien-haus-kunstst.-oder-alu-ap?c=160

### SIGNALduino-Hardware:
Arduino Nano V3.0 ATMEGA328P FT232RL FTDI mit CC1101 433MHz Funkmodul
freq:433.920MHz bWidth:541KHz rAmpl:42dB sens:4dB (DataRate:5603.79Baud)

### Vorgehen
BELL-201-TX hat 3 Knöpfe mit unterschiedlichen Kodierungen, jeder Knopf wurde insg. 3 x gedrückt. Nach dem Batteriewechsel wird zufällig eine neue Kodierung für die Knöpfe bestimmt. Signale werden in FHEM nur bei deaktivierten MS und MC Nachrichten auf verbose 4 erkannt.

### Log:
[m-e_BELL-201-TX.txt](https://github.com/RFD-FHEM/RFFHEM/files/2300371/m-e_BELL-201-TX.txt)

**Comment by elektron-bbs** [comment]
Die sollte eigentlich in der aktuellen Entwickler-Version erkannt werden. ([](url)

**Comment by a13xde** [comment]
Danke für den Hinweis ! Ich hatte wohl nicht die richtige Version im FHEM

`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`

brachte Besserung !

**Comment by sidey79** [comment]
Mich würde interessieren, wie gut die aktuelle Implementierung funktioniert.


Wenn es brauchbar ist, kann ich es auch in die normale FHEM Version übernehmen.
