### ISSUE TITLE
Protokoll EM 1000 nn zu SIGNALduino ohne Erkennung

### ISSUE THREAD

**Issue by Derwelcherichbin** [RFD-FHEM/RFFHEM#253]
Liebe Entwickler,

fhem System erkennt keine elv Energie-Sensoren.
Bitte um Hilfe.

## Hardware:
SIGNALduino <-> EM1000WZ u. s. w. 
## Internals
Clients
:IT:CUL_TCM97001:SD_RSL:OREGON:CUL_TX:SD_AS:Hideki:SD_WS07:SD_WS09: :SD_WS:RFXX10REC:Dooya:SOMFY:SD_UT:SD_WS_Maverick:FLAMINGO:CUL_WS:Revolt: :FS10:CUL_FHTTK:Siro:FHT:FS20:SIGNALduino_un:
DEF	
/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_mySR0001-if00-port0@57600
DMSG
XXX... 
DevState
initialized
DeviceName
/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_mySR0001-if00-port0@57600
FD
11
ITClock
250
LASTDMSG
XXX... 
MSGCNT
7629
NAME
meinCUL1
NR
24
NR_CMD_LAST_H
1
PARTIAL
RAWMSG
MU;XXX... 
RSSI
-65
STATE
opened
TIME
1534795842
TYPE
SIGNALduino
sendworking
0
unknownmessages
version
V 3.3.2-rc2 SIGNALduino cc1101 - compiled at Jun 1 2018 23:56:22
versionmodul
v3.3.3-dev_20.04.
## Readings
ccconf
freq:868.190MHz bWidth:650KHz rAmpl:42dB sens:8dB (DataRate:5603.79Baud)
2018-08-17 18:02:18
ccpatable
C3E = 00 61 00 00 00 00 00 00
2018-08-08 16:59:43
cmds
V R t X F S P C r W x e
2018-08-08 14:44:49
config
MS=1;MU=1;MC=1;Mred=1;Mdebug=1_MScnt=4;MuSplitThresh=8000;MdebFifoLimit=80
2018-08-17 18:28:09
freeram
476
2018-08-08 14:44:53
ping
OK
2018-08-20 21:36:48
raw
fifolimit mcmbl mscnt muthresh
2018-08-17 17:18:09
state
opened
2018-08-18 23:37:23
uptime
0 02:56:12
2018-08-08 14:12:37
version
V 3.3.2-rc2 SIGNALduino cc1101 - compiled at Jun 1 2018 23:56:22
2018-08-18 23:37:23
## Attributes
blacklist_IDs
57
deleteattr
debug
0
deleteattr
development
y61,y73,y74
deleteattr
doubleMsgCheck_IDs
0,3,7,61
deleteattr
flashCommand
avrdude -c arduino -b [BAUDRATE] -P [PORT] -p atmega328p -vv -U flash:w:[HEXFILE] 2>[LOGFILE]
deleteattr
group
CULs
deleteattr
hardware
nanoCC1101
deleteattr
icon
cul_868
deleteattr
longids
14_SD_WS07,14_Hideki, 41_OREGON, 14_CUL_TCM97001
deleteattr
room
Homescreen
deleteattr
verbose
0
deleteattr

## logfile:

2018.08.20 17:44:30 3: meinCUL1: setting Verbose to: 0
2018.08.20 17:44:30 4: meinCUL1: Calling Getting Attr sub with args: set verbose = 0
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 79 -> VTX-BELL_Funkklingel mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 79 -> VTX-BELL_Funkklingel matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 74 -> FS20 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 73 -> FHT80 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 72 -> Siro shutter mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 72 -> Siro shutter matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 70 -> FHT80TF matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 61 -> FS10 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 49 -> quigg_gt9000 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 49 -> quigg_gt9000 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: applying filterfunc SIGNALduino_compPattern
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 37 -> Bresser 7009994 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 37 -> Bresser 7009994 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 30 -> unitec47031 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 29 -> HT12e remote mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 28 -> IC Ledspot mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: applying filterfunc SIGNALduino_filterSign
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 16 -> Dooya shutter mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2018.08.20 17:44:28 4: meinCUL1/msg READredu: MU;P1=-417;P2=385;P3=-815;P4=-12058;D=42121212121212121212121212121212121232321212121212121232321212121212121232323212323212321232121212321212123232121212321212121232323212121212121232121212121212121232323212121212123232321232121212121232123232323212321;CP=2;R=87;
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 79 -> VTX-BELL_Funkklingel mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 79 -> VTX-BELL_Funkklingel matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 74 -> FS20 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 73 -> FHT80 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 72 -> Siro shutter mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 72 -> Siro shutter matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 70 -> FHT80TF matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 1
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 61 -> FS10 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 49 -> quigg_gt9000 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 49 -> quigg_gt9000 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: applying filterfunc SIGNALduino_compPattern
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 37 -> Bresser 7009994 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 37 -> Bresser 7009994 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 30 -> unitec47031 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 29 -> HT12e remote mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 28 -> IC Ledspot mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: applying filterfunc SIGNALduino_filterSign
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 16 -> Dooya shutter mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2018.08.20 17:44:28 4: meinCUL1/msg READredu: MU;P1=-418;P2=390;P3=-818;P4=-12058;D=42121212121212121212121212121212121232321212121212121232321212121212121232323212323212321232121212321212123232121212321212121232323212121212121232121212121212121232323212121212123232321232121212121232123232323212321;CP=2;R=86;w=1;
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 79 -> VTX-BELL_Funkklingel mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 79 -> VTX-BELL_Funkklingel matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 2
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 74 -> FS20 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 2
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 73 -> FHT80 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 72 -> Siro shutter mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 72 -> Siro shutter matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 2
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 70 -> FHT80TF matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: Starting demodulation at Position 2
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 61 -> FS10 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: applying filterfunc SIGNALduino_compPattern
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 37 -> Bresser 7009994 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 37 -> Bresser 7009994 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 30 -> unitec47031 mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 29 -> HT12e remote mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 28 -> IC Ledspot mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2018.08.20 17:44:28 5: meinCUL1: applying filterfunc SIGNALduino_filterSign
2018.08.20 17:44:28 5: meinCUL1: start pattern for MU Protocol id 16 -> Dooya shutter mismatches, aborting
2018.08.20 17:44:28 4: meinCUL1: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2018.08.20 17:44:28 4: meinCUL1/msg READredu: MU;P0=32001;P1=-419;P2=376;P3=-824;P4=-12056;D=012121212121212121212121212121212123232121212121212123232121212121212123232321232321232123212121232121212323212121232121212123232321212121212123212121212121212123232321212121212323232123212121212123212323232321232124;CP=2;R=87;w=0

## Sachverhalt:
Träger auf 868,19MHz mit SDR gemessen, klappt aber bei Bandbreite auch auf..., 35!
Die 3 MU Wiederholungen von 17:44:28 sind definitiv EM1000 Signale,
konnte dies per Uhr an Hand der Sende LED rt am Sensor stoppen.
5min vorher gab es, danach kann man Uhren stellen, wieder diese Pakete.
Weiterhin hab ich "auf Papier" mit http://fhz4linux.info/tiki-index.php?page=EM+Protocol verglichen.

Die Fingerprints rauschen durch bis zur ID79, dann ist Schluss?
Es scheint sich kein Modul für diese doch so schönen Muster zu interessieren?
Mein laienhaftes editieren, der nach meinen bisherigen Erkenntnissen beteiligten 00_SIGNALduino.pm, lässt auch den Schluss zu,
es ist gar nicht implementiert?
Nirgends ein ^E... o. ä.?

Bisherige Recherchen im web liefern dort stets Probleme mit den "Faktoren", ein autocreate scheint dagegen bei allen trivial?
Oder muss man die MSGs zu den benötigten/vorhandenen Modulen (CUL_EM?) irgendwie umleiten? 
Bitte um nützliche Hinweise, gerne Links mit Doku zum Procedere.

venceremos

**Comment by sidey79** [comment]
Danke für den Hinweis,

ja wir müssen wohl ein neues Protokoll für diese Sensoren implementieren.
Das ist auch noch der einfache Teil, da Du bereits wichtige Hinweise hinterlegt hast:

wir würden
```
clock=400 
one=[1,-2]   
zero=[1,-1]

```
definieren. Bei start bin ich mir nicht sicher, ob es funktioniert, wenn wir nach mindestens 12 * 0  suchen und 1 * 1 suchen.
Würde dann wohl grob so aussehen
start=[1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-2]

Dann würde das SIGNALduino Modul schon mal wissen, wie aus den Daten die Bits errechnet werden.
Der Aufwändige Teil ist dann vermutlich, an das CUL_EM die Daten im richtigen Format zu übergeben. Das kenne ich jetzt noch nicht.

**Comment by HomeAutoUser** [comment]
Hallo @sidey79,
spricht etwas hingegen das das Protokoll die ID 80 erhällt?

@Derwelcherichbin,
kannst du bitte mal mehr MU Nachrichten zur Verfügung stellen und mit richtigen Werten versehen um das Ganze zu vergleichen.

Ich habe heute die Implementierung als Protokoll und Umsetzung der Berechnung vorgenommen. Das würde ich gern Prüfen mit mehr Nachrichten. Wenn ich sehe die Richtigkeit ist vorhanden erfolgt ein PullRequest für @sidey79 zur Einbindung.

Bei deiner MU Nachricht von 17:44Uhr kamen da Werte wie
>CNT: 91 CUM: 14.560 5MIN: 0.240 TOP: 0.170

heraus?

MfG Marco

**Comment by Derwelcherichbin** [comment]
Hallo Ihr Guten,
und ich dachte, ich bekomme es nur nicht parametriert.
Schreit doch danach zu schauen, wie es die anderen CULs machen,
kann/darf man dieses "Fahrrad" nicht einfach abkupfern?
Dachte die liefern auch diese Art von Beschreibungen (MSG) bez. der gemessenen Puls/Pausen-Werte und deren Abfolge incl. Wiederholungen? 
Wie muss man eigentlich die ca. 12000er microsec werten?
Ist dies dann eine gemessene Periode? 
Und wie steht es mit den P2ern d. h. 376 bis 390 microsec,
ist doch gewiss auch als ein 400er Wert zu betrachten (miese Flanken)?
In der Beschreibung steht was von mind. 12 Sync-Nullen,
ich zähl aber immer 17? (ist ja auch mind. 12!)
Den Einen, ersten, 32000er verstehe ich gar nicht, oder ist das der zufällige Abstand zum vorhergehenden Gerät oder irgend ein Wischer? 
Wie arbeiten eigentlich alle über AM sendenden Hersteller, 
tasten sie 0 und 1 mit nix und 100 Prozent Träger,
oder schalten diese zum senden auf irgendeinen Pegel, um dann z. B. zwischen 75 und 100 Prozent zu modulieren?
Würde die gelegentlichen "Spitzen" zu Beginn erklären (auch bei anderen)?
Blenden die Module "in Software" sowas intelligent aus?

Fühle mich mal als Verursacher auch angesprochen und liefere umgehend noch paar MUs.
Denke ich finde noch zweiten (Gas <-> Strom) Sensor im log.
Müssten beide Adresse 1 haben, also 1 und 9. 

Grüße

**Comment by Derwelcherichbin** [comment]
## weitere MUs

!!! Achtung, bei Gas momentan ohne Optik d. h. kein weiterzählen!!! 
. 
. 
. 
---log bereits in github---
2018.08.20 17:44:28...
. 
. 
.
---zweiter, anderer Sensor---
2018.08.20 17:43:25 4: meinCUL1/msg READredu: MU;P1=-443;P2=394;P3=-867;P4=-12248;P5=288;D=45121212121212121212121212121212121232323212121212121232321212321212121232123232323232321232321232321212121232121212121212121232121212121212121232121212121212121232321232321212121232121212121212121232121232123232321;CP=2;R=23;
... 
2018.08.20 17:43:25 4: meinCUL1/msg READredu: MU;P1=-423;P2=420;P3=-844;P4=-12248;P5=288;D=45121212121212121212121212121212121232323212121212121232321212321212121232123232323232321232321232321212121232121212121212121232121212121212121232121212121212121232321232321212121232121212121212121232121232123232321;CP=2;R=19;w=1;
... 
2018.08.20 17:43:25 4: meinCUL1/msg READredu: MU;P0=32001;P1=-423;P2=415;P3=-847;P4=-12224;D=012121212121212121212121212121212123232321212121212123232121232121212123212323232323232123232123232121212123212121212121212123212121212121212123212121212121212123232123232121212123212121212121212123212123212323232124;CP=2;R=23;w=0;
.
.
.
---erster Sensor 5min zuvor---
2018.08.20 17:39:28 4: meinCUL1/msg READredu: MU;P1=-402;P2=389;P3=-829;P4=-12044;D=42121212121212121212121212121212121232321212121212121232321212121212121232123212323212321232321232121212123232121212321212121232321212121212121232121212121212121232121212323232123232323212321212121232321232121232321;CP=2;R=86;
...
2018.08.20 17:39:28 4: meinCUL1/msg READredu: MU;P1=-418;P2=384;P3=-819;P4=-12044;D=42121212121212121212121212121212121232321212121212121232321212121212121232123212323212321232321232121212123232121212321212121232321212121212121232121212121212121232121212323232123232323212321212121232321232121232321;CP=2;R=87;w=1;
...
2018.08.20 17:39:28 4: meinCUL1/msg READredu: MU;P0=32001;P1=-419;P2=375;P3=-823;P4=-12032;D=012121212121212121212121212121212123232121212121212123232121212121212123212321232321232123232123212121212323212121232121212123232121212121212123212121212121212123212121232323212323232321232121212123232123212123232124;CP=2;R=86;w=0;
.
.
.
---zweiter, anderer Sensor 5min zuvor---
2018.08.20 17:38:25 4: meinCUL1/msg READredu: MU;P1=-421;P2=401;P3=-860;P4=-12230;P5=286;P6=-24220;D=45121212121212121212121212121212121232323212121212121232321212321212121232321232323232321232321232321212121232121212121212121232121212121212121232121212121212121232321232321212121232121212121212121232323232123232321260;CP=2;R=19;
... 
2018.08.20 17:38:24 4: meinCUL1/msg READredu: MU;P1=-430;P2=407;P3=-851;P4=-12230;P5=286;D=45121212121212121212121212121212121232323212121212121232321212321212121232321232323232321232321232321212121232121212121212121232121212121212121232121212121212121232321232321212121232121212121212121232323232123232321;CP=2;R=22;w=1;
... 
2018.08.20 17:38:24 4: meinCUL1/msg READredu: MU;P0=32001;P1=-420;P2=419;P3=-839;P4=-12212;D=012121212121212121212121212121212123232321212121212123232121232121212123232123232323232123232123232121212123212121212121212123212121212121212123212121212121212123232123232121212123212121212121212123232323212323232124;CP=2;R=23;w=0;
.
.
.
Viel Erfolg!
Höre mit fünnef!

**Comment by Derwelcherichbin** [comment]
... Werte:
GZ (Gas) müsste Adresse 9 haben bei zweitem Byte. 
Fortlaufenden Zähler kann ich nicht vergleichen. 
Zählerwerte wegen fehlender Optik műssten momentan 0 sein.

WS (Wechselstrom) müsste Adresse 1 haben.
Beim fortlaufenden Zähler ist es wieder unbekannt. 
Zählerwerte heute bei 0,020 kWh absolut (auf EM1010PC Display [Neustart] )
d. h. gestern kleiner.
Müsste genau nach Telegramm ablesen.
Grüße

**Comment by HomeAutoUser** [comment]
Guten Morgen @Derwelcherichbin,

das Protokoll ist bekannt und wurde auch schon umgesetzt. Die Daten werden vom SIGNALduino "zurechtgedreht" so das es weiter an das CUL-Modul übergeben wird.
>http://fhz4linux.info/tiki-index.php?page=EM+Protocol

Die hier stehenden Informationen wurden bereits umgesetzt. (Typ - Messwerte unsw...)

Danke für die MU Nachrichten. Ich werde diese später mal Dispatchen und schauen was am Ende herauskommt. Es sollten ja die Werte in FHEM dann deinem Display entsprechen ;-) daher die Bitte, beides angeben. MU + Displayanzeige. Ich melde mich später mit dem Dispatchresultat.

Gute Nacht erstmal

**Comment by HomeAutoUser** [comment]
Hallo @Derwelcherichbin,

in der Entwicklerversion wurde soeben die EM Auswertung eingebunden.
Du müsstest mal ein Update machen, y80 bei developID eintragen und schauen was passiert.

Sollte ein Device angelegt werden und nicht die genauen Werte des Displays entsprechen, dann beschäftige dich bitte mit der Commandref. Bei diesem Gerät kann man nocht einiges einstellen, das die Werte dann auch deinem Verhalten angepasst werden.

Über eine Rückmeldung würden wir uns sehr freuen.

**Comment by Derwelcherichbin** [comment]
Hallo HomeAutoUser und siday79,
erstmal Dank für die prompte Umsetzung. 
Habe soeben update durchgeführt und y80 gesetzt.
Parallel EM1010PC resetet und Faktoren definiert für künftigen Vergleich.
Geräte, Logs und Plots wurden vom ersten möglichen 5min Paket an, sofort autocreatet.
Comand.Ref bereits vorbereitend studiert und indiv. Corrs berechnet und zur Eingabe bereit gelegt.
Beobachte und vergleiche nun und melde mich in Kürze mit Ergebnissen. 
Gar nicht so einfach, in dieser Jahreszeit den Gaszähler von genügender Rotation zu überreden ;-) 
Gruß Torsten

**Comment by Derwelcherichbin** [comment]
Hallo liebe Entwickler,
Zwischen-Info:
EM1000WZ läuft zufriedenstellend seit einigen Tagen synchron
mit dem mechanischen Zählwerk des Elektrozählers.
BasicFeePerMonth | 4.0791
-- | --
CFGFN |  
CODE | 1
CostPerUnit | 0.3923
DEF | 1 96 1152 0.3923 4.0791
 
IODev | meinCUL1
LASTInputDev | meinCUL1
MSGCNT | 1099
NAME | CUL_EM_1
NR | 220
STATE | CNT: 85 CUM: 31477.979 5MIN: 0.375 TOP: 0.372
TYPE | CUL_EM
corr1 | 0.125
corr2 | 0.0104166666666667
meinCUL1_DMSG | E010155D5050300F003
meinCUL1_MSGCNT | 1099
meinCUL1_RAWMSG | MU;P0=-424;P1=387;P2=-819;P3=-12050;D=31010101010101010101010101010101010121210101010101010121210101010101010121210121012101210121210121012101212121210121010101010121212101010101010121010101010101010121010101012121212121212101010101010121210121012121210;CP=1;R=86;w=1;
meinCUL1_RSSI | -31
meinCUL1_TIME | 2018-08-30 21:08:47

Repräsentantive Werte des EM1000GZ folgen nach dem WE.
Grüße

**Comment by sidey79** [comment]
Das sind ja gute Neuigkeiten. Danke für die Information

**Comment by HomeAutoUser** [comment]
@Derwelcherichbin 
gibt es neue Erkenntnisse der zuverlässigkeit des Modules und den Werten?
Wenn du sagst es funktioniert, so können wir demnächst den Faden schließen und das Protokoll vom Entwicklerstatus zum "Normalmodus" überführen.

**Comment by Derwelcherichbin** [comment]
Hab die gleichen Problemchen wie wohl viele andere Nutzer mit dem Verständnis der corr1 und corr 2 Werte bei "Gas".hab jetzt vor Wochenende (Warmwasser) mal corr1 korrigiert(marginal von 0.01 auf 0.009999...) Sonntag abend hab ich aktuelle Daten.Wie gesagt "Strom" ist o.k.."Gas" ist auch nur im Promille Bereich abweichend, der reale mechanische Zähler läuft dem "total" Wert auch nur nach dem Komma etwas vorweg.Evtl. fehlen auf 868 einfach einige Pakete.Weis leider nicht, wie das Modul bei evtl. Sprüngen im Counter der Telegramme,  das mit den ja wohl auch übertragenen anderen summierten Werten ausgleicht.Würde trotzdem jetzt schon behaupten es ist alles plausibel.Bis Sonntag?Am 07.09.2018 15:39 schrieb HomeAutoUser <notifications@github.com>:@Derwelcherichbin
gibt es neue Erkenntnisse der zuverlässigkeit des Modules und den Werten?
Wenn du sagst es funktioniert, so können wir demnächst den Faden schließen und das Protokoll vom Entwicklerstatus zum "Normalmodus" überführen.

**Comment by Derwelcherichbin** [comment]
Hallo HomeAutoUser,
ich nochmal,
denke die Sache kann abgeschlossen werden.
Empfang und Dekodierung ist stabil.
Abweichungen sind wohl Ausreißer wegen gestörter Messwert Übertragung.
Dies wird wohl auch schon im Forum diskutiert und kann durch max. gültige Grenzwerte beseitigt werden.
Sende noch paar screenshots.
Vielen Dank noch einmal,
hoffe dies kommt nun auch anderen Signalduino Nutzern zu Gute. 
Gruß Torsten
Am 07.09.2018 15:39 schrieb HomeAutoUser <notifications@github.com>:@Derwelcherichbin
gibt es neue Erkenntnisse der zuverlässigkeit des Modules und den Werten?
Wenn du sagst es funktioniert, so können wir demnächst den Faden schließen und das Protokoll vom Entwicklerstatus zum "Normalmodus" überführen.

**Comment by HomeAutoUser** [comment]
@Derwelcherichbin 
vielen Dank für die Information und gern wieder. *daumen hoch*
Wenn du nun zufrieden bist und die Sache als abgeschlossen betrachtest, so kannst du selbst den Faden hier schließen (unten rechts auf Close drücken). Wir als mitschreibende können das nicht schließen, maximal @sidey79 vielleicht noch.

**Comment by sidey79** [comment]
müsste automatisch geschlossen werden, wenn ein commit der fixed <nummer> in den master branch kommt :)
