### ISSUE TITLE
434 MHz Fernotron Protokoll der Rademacher Funkrolladenmotoren 

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#257]
@zwiebert ist gerade am entwickeln eines Moduls (10_Fernotron.pm) für das unidirektionale Fernotron Protokoll.
Mir ist gerade nicht so richtig klar, was die nächste freie ID ist (81 oder 82)?

https://forum.fhem.de/index.php/topic,12599.msg75856.html

```
	"82" => ## Fernotron shutters and light switches   
			#MU;P0=-32001;P1=435;P2=-379;P4=-3201;P5=831;P6=-778;D=01212121212121214525252525252521652161452525252525252161652141652521652521652521614165252165252165216521416521616165216525216141652161616521652165214165252161616521652161416525216161652161652141616525252165252521614161652525216525216521452165252525252525;CP=1;O;
			# the messages received are usual missing 12 bits at the end for some reason. So the checksum byte is missing.
			# Fernotron protocol is unidirectional. Here we can only receive messages from controllers send to receivers. 
		{
			name           => 'Fernotron',
			id             => '82',       # protocol number
			developId      => 'm',
			one            => [1,-2],     # on=400us, off=800us
			zero           => [2,-1],     # on=800us, off=400us
			float          => [1,-8],     # on=400us, off=3200us. each 10bit word has one [1,-8] in front
			clockabs       => 400,        # 400us
			preamble       => 'P82#',     # prepend our protocol number to converted message
			clientmodule   => 'Fernotron',
			length_min     => '100',      # actual 120 bit (12 x 10bit words to decode 6 bytes data), but last 20 are for checksum
			length_max     => '3360',     # 3360 bit (336 x 10bit words to decode 168 bytes data) for full timer message
	     	},
```

```
my %matchListSIGNALduino = (
...
     "25:Fernotron"  => '^P82#.*',
```
```
my $clientsSIGNALduino =
     ."Fernotron:"
```

**Comment by Ralf9** [comment]
mit dem o.g. fix sieht ein Parse_MU dann so aus:

```
2018.08.29 22:35:11.085 4 : sduinoD/msg get raw: MU;P0=-32001;P1=435;P2=-379;P4=-3201;P5=831;P6=-778;D=01212121212121214525252525252521652161452525252525252161652141652521652521652521614165252165252165216521416521616165216525216141652161616521652165214165252161616521652161416525216161652161652141616525252165252521614161652525216525216521452165252525252525;CP=1;O;
2018.08.29 22:35:11.086 4 : sduinoD: Fingerprint for MU Protocol id 82 -> Fernotron matches, trying to demodulate
2018.08.29 22:35:11.086 5 : sduinoD: Starting demodulation (Signal: (16|52|14) Pos 15)
2018.08.29 22:35:11.086 5 : sduinoD: dispatching bits: F0000000101F0000000110F1001001001F1001001010F1011101001F1011101010F1001110101F1001110110F1100010001F1100010010F010000000
2018.08.29 22:35:11.086 4 : sduinoD: decoded matched MU Protocol id 82 dmsg P82#F0000000101F0000000110F1001001001F1001001010F1011101001F1011101010F1001110101F1001110110F1100010001F1100010010F010000000 length 120
2018.08.29 22:35:11.086 3 : sduinoD: ID=m82 skiped dispatch (developId=m). To use, please add m82 to the attr development
```

Wenn
P82#F0000000101F0000000110F1001001001F1001001010F1011101001F1011101010F100111010
so nicht gefällt, dann könnte man auch notfalls in einer 
postDemodulation => \&SIGNALduino_postDemo_Fernotron
die "F" entfernen und dann nach Hex wandeln.

**Comment by zwiebert** [comment]
Das Binär-Format mit den Fs ist ok. Hab 10_Fernotron.pm entsprechend geändert. Kommt jetzt klar mit der alten Byte-DMSG und dem Binären Format mit oder ohne die Fs.   Habs getestet.  Die Protokollnummer prüft 10_Fernotron.pm übringens nicht. Kann also bei Bedarf beliebig geändert werden.

Danke.

**Comment by Ralf9** [comment]
@sidey79 
Damit auch mit sendMsg gesendet werden kann, sind noch 2 kleine Änderungen notwendig.
Ist es ok, wenn ich diese Änderungen direkt ins dev-r33 commite?

in die Protokolldefinition 
`pause          => [1,-1],`

und in der sub SIGNALduino_Set($@)
fehlt hier  'F'=> "float"
`my %bitconv = (1=>"one", 0=>"zero", 'D'=> "float", 'F'=> "float", 'P'=> "pause");`

Damit ergibt ein
`sendMsg P82#FPPPPPPPF0000000001F0000000010F`
`sduinoRXB SendrawFromQueue: msg=SR;R=1;P0=400;P1=-800;P2=800;P3=-400;P4=-3200;D=04030303030303030423232323232323232301042323232323232323012304;`

Da es dafür nichts passendes gibt, wird hier die Pause für die preamble verwendet.

hier sind die Timings der RAW message:
```
my $p_string = 'P0=400;P1=-400;P2=-3200;P3=-800;P4=800;';
 my $d_pre_string = '01010101010101';    # preamble
 my $d_stp_string = '02';                # stop comes before each preamble and before each word
 my $d_dt0_string = '41';                # data bit 0 (/..long..\short)
 my $d_dt1_string = '03';                # data bit 1 (/short\..long..)
```

**Comment by sidey79** [comment]
Ich kann es nicht einschätzen. Scheint ein Workaround zu sein oder?

Ich habe nichts dagegen :)

**Comment by Ralf9** [comment]
https://github.com/RFD-FHEM/RFFHEM/commit/1d9b67f8cf547f9975c15b9423e60a6ca9a3b0cd
https://github.com/RFD-FHEM/RFFHEM/commit/51a98c8b573474253b388c1b820236e17fc9fa0a

**Comment by Ralf9** [comment]
Ja, das verwenden von P als preamble ist ein Workaround

**Comment by HomeAutoUser** [comment]
@Ralf9 + @sidey79 
können wir einen Möglichkeit schaffen, das der normale User, welcher die develop Einstellung aktiv hat, soetwas nicht erhält?

>2019.03.01 00:43:38 0: ERROR: Cannot autoload Fernotron
2019.03.01 00:43:38 3: nano_868Mhz: Unknown code P82#1111111111110110111110110100110101111000100001100111111111111010111F1111111110110111110110100110101101001100110000111011011111, help me!

Ich tendiere fast, das man das Modul welches noch in Entwicklung ist, für die anderen auf u82 stellt solange es nicht ladbar ist.

**Comment by Ralf9** [comment]
Diese Fehlermeldung kommt nur, wenn die ID 82 in die whitelist eingetragen wird.
Ich denke es ist sinnvoll in den comment einen Hinweis zu schreiben:
"developModule. Fernotron is not in github or svn"

**Comment by HomeAutoUser** [comment]
>"developModule. Fernotron is not in github or svn"

Sowas sollte mindestens ergänzt werden weil man kann nicht immer davon ausgehen, das jeder Benutzer / Entwickler mit setzung einer kompletten selekt all Liste --> Whitelist alle kommentare liest ob es in Github drin ist.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
