### ISSUE TITLE
Double length_min for protocol 40 (romotec)

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#265]
We have two definitions of min legth. But only one will work

https://github.com/RFD-FHEM/RFFHEM/blob/cdd1d650056352276c87c8944bbae41d23d3e7ef/FHEM/lib/signalduino_protocols.hash#L741-L754

**Comment by sidey79** [comment]
@HomeAutoUser 

Was ist denn hier richtig?

**Comment by elektron-bbs** [comment]
Siehe: https://github.com/RFD-FHEM/RFFHEM/issues/71

**Comment by elektron-bbs** [comment]
Würde es nicht Sinn machen, wenigstens noch min und max Länge auf sinnvolle Werte zu begrenzen, oder wird das bei "u" sowieso nicht gerpüft?
Da sich zu dem Protokoll seit über 2,5 Jahren keiner geäußert hat, würde ich ja dazu plädieren, es komplett zu entfernen.

**Comment by sidey79** [comment]
min und max wird immer geprüft, wenn vorhanden :)
