### ISSUE TITLE
Flash radionoCC1101 / Hardware Attrbute missing

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#267]
## Expected Behavior
When flashing an board, avrdude or espflash needs board specific options to allow proper flashing of a firmware.

## Actual Behavior
When Flashing a Firmware, avrdude gets everytime the options for atmega328p which is not correct for some boards (esp, radino)

## Steps to Reproduce the Problem

  1.   Use a microcontroller not equal to promini or nano
  2.  Try to flash that microcontroller
  3.  Flash will fail

## Specifications

  - Version:   v3.3.3-dev
  - Microcontroller:  atmega32u4, esp, esp32, arduino uno

**Comment by sidey79** [comment]
- Anpassung im Wiki
- Anpassen des Flash Kommandos im Modul
- Hinweis, dass Radino eine andere USB ID im bootloader Modus erhält einbauen

**Comment by HomeAutoUser** [comment]
Ich bin soeben dabei die Umsetzung fürs flashen mit dem radino einzubauen.
Entnehme ich dem Code richtig, das bisher 2 Befehls-Varianten zum flashen notwendig sind?

Bisher nur
`avrdude -c avr109 -b [BAUDRATE] -P [PORT] -p atmega32u4 -vv -D -U flash:w:[HEXFILE] 2>[LOGFILE]`

und dann mit Einbindung radino diese:
alles außer radino
`avrdude -c arduino -b [BAUDRATE] -P [PORT] -p atmega328p -vv -U flash:w:[HEXFILE] 2>[LOGFILE]`
radinocc1101
`avrdude -c avr109 -b [BAUDRATE] -P [PORT] -p atmega32u4 -vv -D -U flash:w:[HEXFILE] 2>[LOGFILE]`

**Comment by sidey79** [comment]
Ja, die Hardware Varianten habe ich in einem anderen branch schon eingebaut:  #256

**Comment by HomeAutoUser** [comment]
Wie ist da die beste Vorgehensweise wenn wir dies ins dev-r33 implementieren wollen?
Möchte natürlich nicht falsch handeln.

**Comment by sidey79** [comment]
Also in dem verlinkten Pull Request, bzw. in dem Branch "fwfromghreleases" habe ich die Hardware wie folgt definiert: 					  ." hardware:nano328,uno,promini328,nanoCC1101,miniculcc1101,radinocc1101,ESP_1M,ESP32"

Die Namen hier passen 1:1 zu den Dateinamen.
Was bei diesem PR noch fehlt, ist ein sauberes Handling des FlashCommand Attributes.

Wenn Du eine Lösung dafür findest, hau es direkt in diesen Branch. Mir ist keine Lösung eingefallen, wie man das macht, denn Attribute sollten wir ja eigentlich nicht überschreiben. Es könnte ja sein, dass der Benutzer sich hier ein eigenes Kommando hinterlegt hat oder es halt angepasst wurde. z.B. serieller Port fürs Flashen anders definieren.

**Comment by HomeAutoUser** [comment]
Spricht funktionsmäßig was dagegen wenn ich mir deinen Code ins aktuelle DEV-r33 bei mir einbinde? So würde ich dort dann das Handling mir ansehen und nach Fertigung einen PR machen.

Nun muss ich nur noch herausbekommen wie ich das "sauber" einbinden kann in den jetzigen Code. So tief war ich noch nicht in Git vorgedrungen.

**Comment by sidey79** [comment]
Also, du syncst den Branch dev-r33-fwfromghreleases neu . (Du benutzt doch hoffentlich TortoiseGit), da geht das immer recht einfach finde ich. Also checkout auf diesen Branch, dann git pull.

Dann machst Du merge und sucht bei dir in deinem homeautouser repo den branch dev-r33-flash branch. (Sofern Du da überhaupt schon änderungen vorgenommen hast).

**Comment by HomeAutoUser** [comment]
Den Branch dev-r33-fwfromghreleases habe ich gesynct zu mir und ich benutze GitHubDesktop und fahre bisher damit gut.

Änderungen hatte ich noch nicht vorgenommen, diese würde ich mir nun ansehen was du schon so weit drin hast und was noch fehlt. Auf 2 Wegen weiterentwickeln wollte ich dann doch nicht ;-)

**Comment by sidey79** [comment]
Kurz zusammengefasst, holt diese Erweiterung eine Liste von Firmwareversionen (quelle Github Releases) und lädt die passende (Attribut Hardware) herunter.

Jetzt hat man also eine Datei heruntergeladen aber nicht unbedingt den passenden Flash Befehl.
Beim ESP geht das ja nicht mit avrdude sondern mittels esptool oder sowas.

**Comment by HomeAutoUser** [comment]
Ich werde es mal testen und aufs System schieben.

**Comment by HomeAutoUser** [comment]
@sidey79 
>Wenn Du eine Lösung dafür findest, hau es direkt in diesen Branch. Mir ist keine Lösung eingefallen, wie man das macht, denn Attribute sollten wir ja eigentlich nicht überschreiben. Es könnte ja sein, dass der Benutzer sich hier ein eigenes Kommando hinterlegt hat oder es halt angepasst wurde. z.B. serieller Port fürs Flashen anders definieren.

*grobe Überlegung*
Was hälst du von der Idee, wir setzen das Flash-Kommando nach jeweiligen Typ einmal standardmäßig vorab bei Auswahl der Hardware. Sobald ein User dieses ändert ohne die Hardware zu ändern, merken wir uns dies in einer "Variablen welche nicht Usersichtbar ist" und diese löschen wir erst wennder User das Hardwaremodel ändert. Sobals diese Markierung vorhanden ist, müssen wir das neu definierte Flashkommando auslesen und dürfen es nicht nach dem Standard nehmen.

**Comment by sidey79** [comment]
Bin nicht sicher ob ich es verstanden habe, im Attribut FlashCommand steht immer das Kommando was verwendet wird.

Beim Ändern der Hardware überschreiben wir es aber mit einem von uns definierten Default.

**Comment by HomeAutoUser** [comment]
Du hast mich halb verstanden.

Wir definieren je nach Hardware das Attribut FlashCommand.
Wenn nun der User nach Auswahl der Hardware die Standardparameter abändert ohne eine Änderung der Hardware, so merken wir uns das in einer Variable. Ab diesem Zeitpunkt sind wir gezwungen immer dieses "mod FlashCommand" zu nutzen.

Wenn ich nun eine neue Hardware auswähle ändert sich das FlashCommand auf den von uns ersten vorgegebnen Wert.

Wenn der User das Attribut Hardwre löscht, so löscht sich auch das FlashCommand.

... alle Fälle muss ich mir mal noch niederschreiben oder versuchen mal abzufangen.
Ich denke man sollte es hinbekommen das der User auch seine modifizierte Zeile nutzen kann solange er die Hardware nicht umstellt oder das Attrib löscht.

**Comment by HomeAutoUser** [comment]
@sidey79 
hast du deine eingebauten Optionen Update schonmal getestet?
Deine URL wo er das abruft und zusammenbaut ist erreichbar bzw. die Dateien sind vorrätig?

Welches $arg
>url        => "https://api.github.com/repos/RFD-FHEM/SIGNALDuino/releases/tags/$args[0]",

verbirgt sich dahinter? Hardware? Hexfile?

**Comment by sidey79** [comment]
Ja, hat bei mir schon funktioniert.

**Comment by HomeAutoUser** [comment]
Ich habe mich nun durchgewühlt und mitbekommen da fehlten noch return Einträge um leere Angaben abzufangen.

Nun stellt sich die Frage für mich was du mit dem set update ... machst, da sich bei mir da auch kein Firmware file neu "updatet" ? Eine Beschreibung wurde auch noch nicht angefangen.

**Comment by sidey79** [comment]
Stimmt, ich bin abgekommen das fertig zu machen.

Bin mir halt auch noch nicht sicher ob es wirklich "gut" implementiert ist.

Es gibt set Update -> Damit soll man wählen, ob nur "stabile" auch auch "Test" Versionen angeboten werden sollen. Ist vermutlich besser in einem Attribut aufgehoben,

Dann gibt es get queryFirmware -> Dadurch werden die verfügbaren "stable" oder "tesing" Versionen in das Auswahlfeld für set flash geschrieben.

**Comment by HomeAutoUser** [comment]
Ich habe mal nun noch ein wenig getestet.
So richtig einschätzen wie weit das Ziel erreicht wurde mit dem Branch kann ich nicht.
Beim hin und her schalten oder "spielen" sehe ich im Auswahlfeld die Versionen aber ob das nun der Hardware entspricht, kannst nur du zuordenen.

Sollte es "nur an dem set Update" gehen, so können wir das gern als Attribut nehmen weil ja der User auch beim ausführen des set Update Befehls keine Information oder Eintrag im Log erhält.

Das was auffällt, es ist auf jedenfall sehr viel Docu nun enthalten, welche im DEV-r33 sehr nützlich wäre.

**Comment by sidey79** [comment]
Vorschlag:
Das Set Update entfernen wir und fügen ein Attribut hinzu.
updateChannelFW und Default ist stable. Alternativ gibt es noch Testing 

Das herunterladen der richtigen Firmware funktioniert aktuell nur für Arduino für den ESP funktioniert es noch nicht, da die Dateien in einem anderen Repo liegen.
Da hatte ich schon über verschiedenes nachgedacht.

In die Download URL wird einfach der Wert des Attributes Hardware mit eingebaut, dadurch erhält man die richtige Datei.


Was die Auswahloptionen der Firmware angeht, die wird immer größer das stimmt.
Wie wir hier die richtige Reduzierung vornehmen weiss ich aktuell nicht.

**Comment by HomeAutoUser** [comment]
Moin Moin,
Der Vorschlag mit dem Attribut updateChannelFW klingt gut.
Default ist stable. Alternativ gibt es noch Testing. 👍 

Ich werde das Ganze nochmal sortiert angehen.
Was hälst du davon,
1) - Anpassung der Doku zwecks flaschen im dev-r33 was eh notwendig ist (so wie der jetzige flashZustand ist, mit erwähnung ESP geht nicht)
2) - Anpassung flashCommand für radino weil das ja ebenso schon geht zu flash in der dev-r33
3) - Einarbeitung Attribut Hardware in Download URL, könnte auch schon angefasst werden in der dev-r33 weil dies ja "nur eine Übernahme aus dem Attribut" ist.

4...) - Attribut updateChannelFW + Firmwareauswahl

Wenn man Punkte 1 bis 3 erledigt, somit sollte sich die Übersicht der notwendigen mehreren Attribute verringern und der "Umbau" leichter gestalten. Alles mit einmal in einen Schritt, das wird bestimmt derzeit an der Umsetzung bzw. gescheiten Lösungsvariante viel Zeit und somit ein "rückstellen" darstellen.

**Comment by sidey79** [comment]
Die Punkte 1,2 und 3 sind doch vom Prinzip erledigt.

Punkt 4 scheint mir keine große Sache zu sein.

Wenn wir das gemeinsam angehen sollte es in 2-3 Tagen erledigt sein.

**Comment by HomeAutoUser** [comment]
Ich bin scchon dabei Schritt für Schritt es nochmal anzugehen.
Anbei dokumentiere ich was ich mir dabei gedacht habe.

Sobald ich das meinerseits mögliche durch habe und auch die Docu, so stelle ich Dir es zur Verfügung und ab dort dann gemeinsam weiter, um es zeitnah zu erledigen. Somit hätten wir wieder einen Schritt weiter,  und eine Erleichterung der User.

Halte dich hier auf dem laufenden bzw. wenn Fragen kommen, dann hier :-D

**Comment by HomeAutoUser** [comment]
@sidey79, kann losgehen :-D

Frage,
ist es machbar bzw spricht was dagegen die Einarbeitung stufenweise zu integrieren?

Ich hätte nun einen Zwischenstand welche für die DEV-r33 wäre wo wir nur Doc und radino flashCommand angepasst haben.  https://github.com/HomeAutoUser/RFFHEM/commit/426589677aebd388007d60ce68f3b5c0490c4063
Dieser ist basierend auf unseren Stand des DEV-r33. Solltest du dies auch so sehen (daher die das genaue Chancelog, so mache ich einen PR aufs DEV-r33 und würde dich bitte, das du dies bei dem Branch dev-r33-fwfromghreleases aktualisierst)

Der Code mit den Änderungen minimiert sich natürlich dadurch und ab diesem Stand müssen wir "nur" das hinzufügen was wir wirklich benötigen. (( Ich denke gern Schrittweise um es nachvollziehbar zu strukturieren )) 

1) Ab diesem Punkt wäre nun die Überlegung welche Attribute wir sinnvoll integrieren.
Attribut updateChannelFW, mit den Werten "stable" & "Test" 
2) die Übersicht der Firmware / Auswahloptionen würde ich nicht aufblähen. (stable / Testing und somit abgreifbar über das Attribut updateChannelFW)
3) flashCommand via Hardware modifizieren (Abhängig von den Modellen bis auf Ausnahme ESP)
4) Befehl flash via Hexfile und URL (Prüfung ob eine Datei existiert, wenn nicht via URL - wäre das eine Überlegung)

... da ich mit jedem neuen PR nur mehr "Undurchsichtigkeit" schaffe, hatte ich den schon von mir geöffneten geschlossen. Die Ordnung würde ich hier basierend fortführen.

**Comment by sidey79** [comment]
Für HomeAutoUser@4265896 kannst Du gerne einen PR erstellen.

Kleine Änderungen mag ich auch lieber :)

**Comment by sidey79** [comment]
Das Auswahlfeld mit den FW Releases würde ich so lassen.
Die von dir angesprochenen Entwickler können ja weiterhin problemlos eine Datei in dem Flash command angeben .

**Comment by HomeAutoUser** [comment]
>Für HomeAutoUser/RFFHEM@4265896 kannst Du gerne einen PR erstellen.
Kleine Änderungen mag ich auch lieber :)

Dann mache ich das und dann kommt nen Schälchen Heeßen und Bildschirmpause.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
