### ISSUE TITLE
PERL WARNING: Use of uninitialized - line 1234

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#272]
## Expected Behavior
- fix PERL WARNING

## Actual Behavior
- PERL WARNING: Use of uninitialized value in numeric eq (==) at ./FHEM/00_SIGNALduino.pm line 1234.

line with uninitialized value:

  InternalTimer(gettimeofday() + 0.1, "SIGNALduino_HandleWriteQueue", "HandleWriteQueue:$name") if (@{$hash->{QUEUE}} == 1 && $hash->{sendworking} == 0);

## Steps to Reproduce the Problem

  1. FHEM restart
  2. FHEM commando: set sduino_dummy raw P83#011001110111#R4
  3.

## Specifications

  - Version: v3.3.3-dev_15.09.
  - Microcontroller:

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
