### ISSUE TITLE
Docu SIGNALduino HASH File + development commandref

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#274]
## Expected Behavior
added docu

## Actual Behavior
no docu in file

## Steps to Reproduce the Problem
-

```
################################################################################
# The file is part of the SIGNALduino project
#
# !!! useful hints !!!
# --------------------
# name        => ' '       # name of device or group of all devices
# comment     => ' '       # exact description or example of devices
# id          => ' '       # number of the protocol definition, each number only once use ((accepted no .)
# one         => [ , ]     # only MU + MS signals | value pair for a one bit, must be always a positive and negative factor of clockabs (accepted . | example 1.5)
# zero        => [ , ]     # only MU + MS  signals | value pair for a zero bit, must be always a positive and negative factor of clockabs (accepted . | example -1.5)
# clockabs    => ' '       # only MU + MS  signals | value pulse / pause times
# clockabs    => '-1'      # only MS signals | value pulse / pause times is automatically
# clockrange  => [ , ]     # only MC signals | min , max of pulse / pause times
# start       => [ , ]     # value pair for start message
# sync        => [ , ]     # value pair for sync pulse of signal
# length_min               # minimum length of bits of the message
# length_max               # maximum length of bits of the message
#
# developId   => 'm'       # logical module is under development
# developId   => 'p'       # protocol is under development or to reserve IDs, the ID in the development attribute with developId => 'p' are only used without the other entries
# developId   => 'y'       # protocol is under development, all IDs in the development attribute with developId => 'y' are used
#
# preamble    => ' '       # prepend to converted message
# preamble    => 'u..'     # message is unknown and without module, forwarding SIGNALduino_un or FHEM DOIF
# preamble    => 'U..'     # message can be unknown and without module, no forwarding SIGNALduino_un but forwarding can FHEM DOIF
#
# clientmodule => ' '      # FHEM module for processing
# filterfunc  => ' '       # SIGNALduino_filterSign | SIGNALduino_compPattern --> SIGNALduino internal filter function, it remove the sign from the pattern, and compress message and pattern
#                          # SIGNALduino_filterMC --> SIGNALduino internal filter function, it will decode MU data via Manchester encoding
# float       => [ , ]     # Convert 0F -> 01 (F) to be compatible with CUL
# format      => ' '       # twostate | pwm | manchester --> modulation type of the signal, only manchester use SIGNALduino internal, other types only comment
# method      => \&        # call to process this message
# modulematch => ' '       # RegEx on the exact message including preamble
# paddingbits => ' '       # default is 4, pad up to x bits
# paddingbits => '1'       # will disable padding
# pause       => [ ]       # value, pause when sending between two signals
# polarity    => 'invert'  # only MC signals | invert bits of the signal
# postamble   => ' '       # hangs a string to the demodulated signal
# postDemodulation => \&   # SIGNALduino internal sub for processing in front of the module
# remove_zero => 1         # removes leading zeros from output
#
#####################################################################################
# !!!! please, documentation minimum one MU / MC / MS message at new protocols !!!! #
#####################################################################################
```

Hier ist ein Vorschlag der Dokumentation für die Datei wie ich mir es bestmöglich zusammen reimen konnte.

@sidey79 @Ralf9 @elektron-bbs bitte mal darüber schauen was wir ggf noch hinzufügen sollten bzw abändern sollten um auch dort nicht immer nachzudenken ;-)

**Comment by elektron-bbs** [comment]
Mal abgesehen davon, wie es beschrieben ist, ist die Funktion bei "y" z.B. folgende:
Es werden auch die im Attribut "development" eingetragenen Protokolle verarbeitet. Die Syntax ist z.B. "y81,y83" - also getrennt mit Komma. Bei "m" ist es wohl ebenso. Es können auch "m" und "y" gemischt angegeben werden.
"p" habe ich bisher nicht verwendet. Ich hoffe, die Syntax ist auch Kommagetrennt, wie üblich.

**Comment by Ralf9** [comment]
> developId   => 'p'   # the protocol is under development, the log in the development attribute with developId => 'p' are only used without the other entries

hier evtl noch eine Ergänzung:
p kann verwendet werden um noch nicht funktionierende Protokoll IDs zu reservieren.
Z.B. solche die filterfunc, method oder postDemodulation enthalten deren Code noch nicht voll funktionsfähig ist.

Es ist zu überlegen ob bei
"63" => ## Warema MU
das
developId   => 'p' 
nicht sinnvoller ist.

**Comment by elektron-bbs** [comment]
Mal abgesehen davon, wie es beschrieben ist, ist die Funktion bei "y" z.B. folgende:
Es werden auch die im Attribut "development" eingetragenen Protokolle verarbeitet. Die Syntax ist z.B. "y81,y83" - also getrennt mit Komma. Bei "m" ist es wohl ebenso. Es können auch "m" und "y" gemischt angegeben werden.
"p" habe ich bisher nicht verwendet. Ich hoffe, die Syntax ist auch Kommagetrennt, wie üblich. Wenn ich Ralf9 richtig verstehe, sollte das wohl eine Art "Umkehr" der jetzigen Funktion von "y" werden. Also mit "y" alle einschalten und dann mit "p" selektieren.

**Comment by Ralf9** [comment]
Die whitelist_IDs sollen vorrang vor der developId y und p haben. D.h. wenn z.B. in der whitelist die ID 73 steht, muß im Attribut develop kein y oder p73 stehen.

Wenn im Attribut develop y steht, dann werden alle IDs mit developId => 'y' verwendet, unerwünschte IDs wie z.B die 63 können in die blacklist eingetragen werden.

Mit p im Attribut develop können die IDs einzeln ausgewählt werden. z.B. p63p78

**Comment by elektron-bbs** [comment]
Ist das jetzt Stand deiner Version, oder der offiziellen dev?

**Comment by Ralf9** [comment]
Es ist dieser Stand:
https://github.com/RFD-FHEM/RFFHEM/issues/242#issuecomment-398514077
https://github.com/RFD-FHEM/RFFHEM/issues/242#issuecomment-402551803

**Comment by sidey79** [comment]
Kann jemand einen Lebenszyklus der Protokolle und die dazu passenden Buchstaben hier erstellen?
Ich blicke leider kaum noch durch.
Ich würde annehmen, dass ein neues Protokoll zuerst immer ein "y" erhält. Aber ich könnt hier auch "p" verwenden.

**Comment by HomeAutoUser** [comment]
@sidey79 

im ersten Post ganz oben habe ich eigendlich bisher alles zusammengefasst. Bitte auch dazu die bzw. den Kommentar lesen.

**Comment by sidey79** [comment]
Kurz noch mal zurück. 

Was genau soll mit dem Attribut development erreicht werden? Dass wir hier recht vielfältige Möglichkeiten haben und das Zusammenspiel mit whitlelistid und blacklistid es ein wenig komplex macht, gefällt mir nicht sonderlich gut.

Ich hatte das wie folgt verstanden:

Protokolle die noch nicht "stabil" entwickelt wurden, bekommen ein Flag, damit sie durch den Anwender manuell aktiviert werden müssen. Dazu gibt es y und m .

- `y` bedeutet es gibt noch kein Modul
- `m` bedeutet, es gibt ein Modul aber das ist noch nicht fertig.

Wann verwende ich als Anwender das?
Vermutlich dann, wenn ich diese "neue" noch unfertige Protokoll empfange und zur Entwicklung beitragen möchte.

Bitte korrigieren was ich falsch wiedergegeben habe :)

**Comment by Ralf9** [comment]
Attribut development y ist für Anwender und Entwickler gedacht, die keine whitlelistid verwenden und alle IDs verwenden wollen. Z.B. um zu schauen ob es für unbekannte Sensoren bereits eine ID gibt.

Das y macht bei Protokoll IDs Sinn, wo filterfunc, method oder postDemodulation verwendet wird und der enthaltene Code noch nicht voll funktionsfähig oder komplett getestet ist.

m kann auch bedeuten, daß es zwar ein fertiges Modul gibt, es aber nicht im normalen fhem update (svn) ist, z.B. im git vom Entwickler des Moduls

**Comment by Ralf9** [comment]
Bei sehr einfachen Protokolldefinitionen wie z.B. der ID 78 geiger müsste man eigentlich auf das
developId => 'y'
verzichten können,
Da kann eigentlich beim parse nichts schief gehen.

**Comment by HomeAutoUser** [comment]
@Ralf9 @elektron-bbs @sidey79 
vorerst unabhänig von der derzeitigen Funktion development. Habt ihr Einwende bzw. Ergänzungen der o.g. Docu im ersten Post? Diese würde ich als "Basis" verwenden wollen für diverse Docu-Zwecke.

**Comment by Ralf9** [comment]
Wenn interesse an Verbesserungen und Optimierungen der sub SIGNALduino_Parse_MU() bestehen, dann gibt es für MU-Nachrichten zukünftig noch:
clockpos		=>
damit kann eindeutig aus der MU-Nachricht die clock ermittelt werden.
Z.Zt. wird bei MU-Nachrichten nicht die clock verglichen, damit wäre dies dann möglich. 

Wenn in one und zero die clock enhalten ist, dann kann die clock aus cp der Nachricht geholt werden 
```
			id			=> '80',
			one			=> [1,-2],	# 800
			zero			=> [1,-1],	# 400
			clockabs		=> 400,
			clockpos		=> ['cp',0],
```

Wenn die clock nur in one ist, dann muss in clockpos angeben werden, daß die clock in one steht.
`one	=> [1,-2], `  dann    `clockpos	=> ['one',0],`
`one	=> [-2,1],`   dann   ` clockpos	=> ['one',1],`

Wenn die clock nur in zero ist, dann muss in clockpos angegeben werden, daß die clock in zero steht.
z.B.
```
			id          	=> '48',
			clockabs     	=> 250, 		# In real it is 500 but this leads to unprceise demodulation 
			clockpos     => ['zero',1],
			one		=> [-4,6],
			zero		=> [-4,2],
```

**Comment by Ralf9** [comment]
@elektron-bbs 
was möchstest Du mir damit sagen?

**Comment by sidey79** [comment]
Ich finde die Syntax von clockpos noch immer schwierig zu verstehen,
Es gibt Bezeichner (cp, one, Zero) aber auch Werte die angegeben werden können.

Irgendwie blicke ich nicht durch :(

**Comment by Ralf9** [comment]
Ja, es ist recht kompliziert, aber ich habe keine Idee wie man es einfacher machen könnte.
Hier ist noch ein Beispiel mit der ID 8 und dieser MU-Nachricht (ID 79)
`MU;P0=656;P1=-656;P2=335;P3=-326;P4=-5024;CP=2;D=01230121230123030303012423012301212301230303030124230123012123012303030301242301230121230123...`
hier ist 21 one und 01 zero

```
			id          	=> '8',
			one				=> [1,-2],
			zero			=> [2,-2],
			clockabs     	=> 470,			# 
			clockpos	=> ['one',0],
```
Die 0 bei clockpos bedeutet für:
Die clock aus der Nachricht beim one string (21) die postition 0, also 2, dies ergibt mit P2 die clock 335.
Die clock aus der ProtokollListe (one => [1,-2]) vom Array das Element 0, dies ergibt  470 x 1 = die clock 470


Bei diesem Beispiel (ID 48)
```
			id          	=> '48',
			clockabs     	=> 250, 		# In real it is 500 but this leads to unprceise demodulation 
			clockpos     => ['zero',1],
			one		=> [-4,6],
			zero		=> [-4,2],
```
bedeutet `clockpos     => ['zero',1],` für
Die clock aus der ProtokollListe (zero => [-4,2],) vom Array das Element 1, dies ergibt 250 x 2 = die clock 500

**Comment by Ralf9** [comment]
und hier ist ein Beispiel wo es mit der clock aus der Nachricht nicht passen würde,
`MU;P0=1148;P1=3421;P6=-664;P7=-4631;D=16170717071717171717071717071717171717070707170717171717070717171710;CP=1;`
CP=1 ergibt eine clock von P1=3421.
Nach der ProtokollListe ist die clock aber 122 x 10 = 1220
und mit dem oneString 70 ergibt sich mit pos 1 die richtige clock von P0=1148

```
         	id             => '67',
         	one            => [-38,10],
         	zero           => [-38,28],      
         	clockabs       => 122,
         	clockpos       => ['one',1],
```

**Comment by HomeAutoUser** [comment]
@Ralf9 ,
ich denke langsam zu verstehen was du damit meinst bzw. wie dies zusammen spielt.
Kann man nicht dies irgendwie zum Verständnis so anpassen, das wenn bisher

>clockpos       => ['one',1],

ist,

>clockpos       => ['one',10],

dort hinein muss. ich sehe die 10 als Faktor und somit kann es mit 1 zum Missverständis kommen.

```
         	id             => '67',
         	one            => [-38,10],
         	zero           => [-38,28],      
         	clockabs       => 122,
         	clockpos       => ['one',1],
```

**Comment by Ralf9** [comment]
> clockpos => ['one',10
> dort hinein muss. ich sehe die 10 als Faktor und somit kann es mit 1 zum Missverständis kommen.

Das Problem dabei ist, wie kann man dann mit 10 die richtige clock P0=1148 aus der o.g. MU-Nachricht ermitteln?

**Comment by Ralf9** [comment]
Nein, ob bei clockpos 0 oder 1 steht, hängt davon ab ob im Array von one oder zero die clock im Arrayelement 0 oder 1 steht.
`one            => [-38,10], ` die clock steht im Arrayelement 1
`one            => [10,-38], ` die clock steht im Arrayelement 0

Man könnte es vereinfachen, wenn man in der sub parse_MU das richtige Arrayelement ermittelt,
die clock ist der niedrigste positive Wert.
Man müsste dann z.B. mit
`foreach $searchpattern (@{$search})`
alle Arrayelemente von one oder zero testen

**Comment by elektron-bbs** [comment]
> @elektron-bbs
> was möchstest Du mir damit sagen?

Da war wohl etwas nicht gespeichert worden :-(

>

**Comment by Ralf9** [comment]
Wir sollten auch ab und zu mal im Protocol hash die developId Einträge durchschauen.

> 	"63" => ## Warema MU
> 			comment      => 'developId, is still experimental',
> 			developId => 'y',

@sidey79 
ist diese ID so weit entwickelt, daß sie verwendet werden kann?
Hast Du vor sie weiter zu entwickeln?
Macht es evtl Sinn die developId von y auf p zu ändern?

> "78" => 
> 			name			=> 'geiger',
> 			comment			=> 'geiger blind motors',
> 			developId => 'y', 

hier müsste eigentlich das `developId => 'y',` entfernt werden können

> "72" => # Siro blinds 
> 			name			=> 'Siro shutter',
> 			comment         => 'developModule. Siro is not in github or SVN available',
> developId => 'm',

das `developId => 'm'` und der comment kann weg, da das Siro Modul mittlerweile im SVN ist

**Comment by HomeAutoUser** [comment]
@Ralf9 
JA wir müssen die HASH Datei auch pflegen. Da habe ich nun immer ein Auge mit drauf genommen was Bezeichnungen von Typen unsw betrifft.

- bei "72" würde ich dir vorerst wiedersprechen das

> developId => 'm',

zu entfernen.

Grund: Hier muss nachgebesser werden. Da wir die ID 16 und ID 72 gleich sind, so wird jedes mal 2 Geräte mit unterschiedlichem Namen angelegt. Ich selbst habe beim Senior den Fall. Da auch gern unterschiedliche Geräte angelegt werden weil die ID bzw. Def sich ändert, so habe ich nach wenigen Tagen nicht 3 Geräte sondern immer 6.

Das Problem **wurde auch schon im Forum benannt**.
Den Link habe ich auf die Schnelle nicht gefunden.

[glaube hier]( https://forum.fhem.de/index.php/topic,49523.0.html) oder [hier](https://forum.fhem.de/index.php?topic=77167.0)

Die ID 72 ist natürlich besser ausgereift vom Modul. Entweder man nimmt die ID "16" als "m" oder wenn jemand prüfen kann, das es sich wirklich um das GLEICHE handelt aber da 2 Module entwickelt wurde, so kann man das "schlechtere" vorerst auskommentieren. Da müssen die ModulMaintainer ggf. handeln. Entweder eine Attribut Hardware einrichten oder darauf hinweisen, das SIRO und Dooya (Rohrmotor24 ) bzw. gleich sind weil der "kleine Chinese" die selbe Hardware einbaute und dies an 2 Hersteller vertrieb.

--------------------

Genau deswegen habe ich bereits die Kommentare gesetzt.

```
	"16" => # Rohrmotor24 und andere Funk Rolladen / Markisen Motoren
			# ! same definition how ID 72 !
```

```
	"72" => # Siro blinds MU    @Dr. Smag
			# ! same definition how ID 16 !
```

**Comment by sidey79** [comment]
Siro und dooya ist meiner Erinnerung nach nicht so ganz gleich.

**Comment by HomeAutoUser** [comment]
>Ich habe mir das SIRO- und Dooya-Modul mal angeschaut. Vom Empfang her sieht es gleich aus.

Solch verhalten haben wir auch bei dem SD_UT Modul. Die Protokolle sind sehr ähnlich aber beim senden ist es minimal anders. Wir haben dort die Modelle untereinadner "verschachtelt" was wiederum immer schwieriger wir desto mehr ähnliche Protokolle. Um das Problem zu lösen ist noch eine clevere Lösung gesucht! Das begleitet und lastet dann immer auf uns wenn die Protokolle sich vermehren.

**Comment by HomeAutoUser** [comment]
Ich mache nochmal auf den https://github.com/RFD-FHEM/RFFHEM/issues/242#issuecomment-398514077 einen Hinweis. Wollen wir es auf den Stand von Ralf bringen um bei den Versionen "identisch" zu bleiben?

**Comment by sidey79** [comment]
Keine Ahnung was der Stand von Ralf genau ist?
Ich hatte tatsächlich die Tage ein Fehlerbild eines Anwenders, der konnte den Rolladen nicht schalten.
Die Zeiten sahen eher so aus wie beim Siro Modul. Ich habe ihn die clock beim Dooya (Protokoll 16) auf 320 anpassen lassen. Dann ging es bei ihm. @Jarnsen habe ich gebeten auch mal mit der geänderten Taktrate zu testen. Würde durchaus gerne wissen ob die dooya motoren sind generell damit schalten lassen.

Zu dem Zeitpunkt habe ich aber überhaupt nicht an das Siro Protokoll gedacht.

@Jarnsen 
Vielleicht kannst Du uns ja noch erhellen, ob es zwischen Dooya und Siro einen Unterschied gibt,

**Comment by Ralf9** [comment]
Mir ist bei paddingbits nicht klar welchen Sinn andere Werte als 4 oder 8 haben.
Bei der id 21 ist es 1 und bei der id 78 ist es 2

**Comment by sidey79** [comment]
mit paddingbits = 1 wird nichts angehängt. Quasi deaktiviert

Mit paddingbits 2 wird auf eine gerade Anzahl aufgefüllt, also maximal 1 bit

**Comment by sidey79** [comment]
Das issue können wir schließen oder?

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
