### ISSUE TITLE
unit tests running in background

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#275]
## Expected Behavior

After changes to the module or the protocol hash are done, automated tests are started to verify if the expected behaviour is reached.

## Actual Behavior

Changes to the module or the protocol hash are not easily to verify in a consistent way

## Steps to Reproduce the Problem

  1.  change something in the module
  2.  Do manual testing of what you think
  

## Specifications

There is an approch from another user. He starts fhem on a travis-ci build server.
After fhem runs he sends some data to his module which provides a tcp server. After this, he connects to fhem via telnet and pushes some fhem commands over the telnet connection. 
He then checks the results returned from the command.

All this is done via easy to define text files. 

In the last step, the global logfile is checked for warnings.

The idea of this issue is to discuss, if this approach can be reused in this project.
Automatic parsing the global logfile is a easy job and can be seen as a quick win to provide more stability and less bugs.

Additional it would be possible to send some raw messages via a defined dummy signalduino and check 1. was the device automatically created
2. Has the name of the device the expected format (verify longid support)
3. Check if the values fit 

https://github.com/markusfeist/FhemMobileAlerts/tree/master/test

**Comment by sidey79** [comment]
Ich habe da mal was ausprobiert;

https://travis-ci.org/RFD-FHEM/RFFHEM/builds

**Comment by sidey79** [comment]
@homeautouser

Zur Info

**Comment by sidey79** [comment]
@homeautouser

Zur Info

**Comment by HomeAutoUser** [comment]
@sidey79 

>@HomeAutoUser
Zur Info

ja ich habe dies vernommen und mir angesehen aber nicht ganz verstanden. Wie läuft dies ab oder wie hat dies einfluss auf unsere PR´s?

**Comment by sidey79** [comment]
@homeAutoUser

Ich habe zwei Dinge implementiert:

Sobald ein Pullover Requests geöffnet wird, werden build Jobs auf Travis Ci gestartet.

Travis clont das git in einen virtuellen Server , installiert FHEM und kopiert die Module in das FHEM Verzeichnis.

In der laufenden FHEM Instanz können dann Tests ausgeführt werden.
Da bin ich aktuell noch dran.
Die Idee ist, dass man einen Test für ein neues Protokoll schreibt, welches verifiziert, ob der richtige Wert an Dispatch übergeben wird.

Die 2. Funktion ist das aktualisieren der controls Datei.
Travis ruft dafür ein kleines Shell Script auf, was die controls Datei neu erstellt.
Wenn der Branch in diesem Repo erstellt wurde, dann kann die Änderung auch zurück in das git geschrieben werden.

Das würde ich euch auch anbieten, dass ich euch schreibrechte in diesem Repo gebe.

Das vorgehen  einen eigenen Branch zu erstellen oder pull requests einstellen funktioniert wie bisher.

**Comment by sidey79** [comment]
@HomeAutoUser  @Ralf9  

Ich hab das jetzt mal ein zusammen gebastelt:

Ich habe einen Beispiel Test geschrieben, der soll prüfen, ob das erwartete Ergebnis an die FHEM Funktion Dispatch übergeben wird, nachdem SIGNALduino_Parse_MS aufgerufen wurde.

Zunächst schreibt man einen Testfall. Dazu habe ich ein kleines Hilfsmodul geschrieben, welches den Code in runden Klammern ausführt. (Kommentare kann man aktuell dort keine hintlerlassen, da alle Zeilenumbrüche entfernt werden.)
https://github.com/RFD-FHEM/RFFHEM/blob/dev-r33-travis-update/test/test3-definition.txt

In dem Testfall werden ein paar Variablen / Objekte definier.

- `Mock::Sub->new` ist ein Objekt, welches es ermöglicht eine Funktion zu überschreiben.

- `$Dispatch = $mock->mock("Dispatch");`  Hiermir wird die FHEM Funktion Dispatch "überschrieben".

- `$rmsg` hält die Daten, welche an  SIGNALduino_Split_Message` übergeben werden.
Geht man atomar vor, dann würden man an dieser Stelle das Ergebnis von `Split_Message` prüfen,  ich habe das hier aber nicht gemacht, um den Test etwas anschaulicher zu machen. Dadurch wird allerdings nun implizit die Funktion `SIGNALduino_Split_Message` mit getestet, jedoch nicht verifiziert ob sie funktioniert.

- `SIGNALduino_Parse_MS` wird im wesentlichen mit dem Rückgabewert von `SIGNALduino_Split_Message` aufgerufen. 

- `is($Dispatch->called_count, 1, "Called Dispatch from parse MS");`  Hiermit wird geprüft, ob die Dispatch Funktion aufgerufen wurde. Wir prüfen hiermit ab, ob die Funktion 1x aufgerufen wurde.

- Hier werten wir aus, welche Parameter an die `Dispatch` Funktion übergeben wurden. Der 2. Parameter ist die erwartete Nachricht und wir wollen wissen, ob das erwartete Ergebnis zutrifft. 
```my @called_args = $Dispatch->called_with;
 is( $called_args[1], "s5C080FC32000", "Parse_MS dispatched message for Module CUL_TCM_97001" );
```

Der Testfall wird in eine Textdatei geschrieben und hier abgelegt:
https://github.com/RFD-FHEM/RFFHEM/blob/dev-r33-travis-update/test/

Es gibt ein kleine shell Script, welches die im Testfall hinterlegte Definition in eine laufende FHEM Instant anlegt und das Ergebnis auswertet. Im Fehlerfall werden auch alle Einträge aus dem Logfile gesammelt, welche den Test betreffen:
https://github.com/RFD-FHEM/RFFHEM/blob/dev-r33-travis-update/test/test-runner.sh
Dadurch wird dann die Definition `test/test3-definition.txt` geladen.

Da die Testfälle noch nicht automatisch gesucht werden, habe ich in einem Makefile den Aufruf des `test-runner.sh` scriptes mit dem Testfall `test3` hinterlegt.
https://github.com/RFD-FHEM/RFFHEM/blob/29f63e724e41d38343dcd4dfe8600731f02ea3f2/Makefile#L19


Das Ergebnis wird dann am Ende so so aus:
https://travis-ci.org/RFD-FHEM/RFFHEM/jobs/432091028#L864
```
--------- Starting test test3 ---------\n\n
Output of test3:\n\n
ok 1 - Called Dispatch from parse MS
ok 2 - Parse_MS dispatched message for Module CUL_TCM_97001
--------- Test test3: ok ---------
```
Wenn der Test nicht ok war, kann man den Fehler auch so melden, dass auf Github ein Fehler zu sehen ist, dass etwas nicht gestimmt hat.
Ein Blick in das Logfile gibt dann hinweise, was nicht passt.

Also zusammengefasst:

1. Im Ordner `/test/<namedestests>-definition.txt` einen Test definieren
2. https://github.com/RFD-FHEM/RFFHEM/blob/29f63e724e41d38343dcd4dfe8600731f02ea3f2/Makefile#L17-L19 
um den Aufruf erweitern

Seit ihr in der Lage, bei zukünftigen Code Anpassungen einen Test zu schreiben, der das gewünschte Verhalten verifiziert?

**Comment by sidey79** [comment]
@HomeAutoUser 
Die Abdeckung des Tests lässt sich auch recht einfach auswerten. Dazu habe ich coveralls eingebunden.

[![Coverage Status](https://coveralls.io/repos/github/RFD-FHEM/RFFHEM/badge.svg?branch=dev-r33-travis-update)](https://coveralls.io/github/RFD-FHEM/RFFHEM?branch=dev-r33-travis-update)

Erstaunlich, dass ich mit dem bisschen Test schon 17% des quellcodes abgedeckt habe.

So kann auch leicht geprüft werden, ob denn alle Bedingungen im Test abgefangen werden:
https://coveralls.io/builds/19145796/source?filename=FHEM%2F00_SIGNALduino.pm#L1713

Wie zu sehen ist, wurden nicht alle Bedingungen geprüft. War ja auch nicht mein Ansinnen mit dem genannten Test. Es Macht also durchaus Sinn die `split_message` Funktion separat mit allen Varianten zu testen. 

In der `parse_MS `Funktion ist es ähnlich:
https://coveralls.io/builds/19145796/source?filename=FHEM%2F00_SIGNALduino.pm#L1868

Mit ein paar Tests lassen sich wohl schnell 50% vom Code testen nehme ich an.

**Comment by HomeAutoUser** [comment]
@sidey79 
ich hätte mal noch eine Idee zwecks Test bzw. Funktion. Die Umsetzung sollte kein Thema sein für Dich und vielleicht ist sogar mit dem oder den vorhandenen Test schon ein Anfang gesetzt.

Ein Test wie [hier](https://github.com/RFD-FHEM/RFFHEM/pull/307#issuecomment-427155551) welcher mir aus einer Datei welche ich hinterlege, mir sämtliche "REED" Nachrichten also 
> 2017.02.04 09:56:18 4 : sduino/msg READ: �MU;P0=-30878;P1=1307;P2=-1119;P3=529;P4=344;P5=-600;P6=-1776;D=0121212123212321212121212323232121232121212321232121232123212124542123212321212363212123210;CP=1;�
herausliest und im Test dispatcht.

Mein Gedanke ist dabei, der User gibt uns ein Logfile wo ich nicht manuell die Nachrichten heraussuchen möchte weil ich diese Dispatchen möchte.

In meinem jetzigen Fall möchte ich dadurch sehen
>2018.10.04 22:50:18 4: sduino_dummy: decoded matched MU Protocol id 49 dmsg U49#165B60 length 24 RSSI = -63.5

ob es immer die selbe **length** besitzt. 
.... oder gibt es den Test schon in deinem System ;-)

Konntest du mir folgen?
