### ISSUE TITLE
Travis Check - facts - questions

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#302]
Here you can learn all about Travis.
- Improvements or Questions ....

**Comment by HomeAutoUser** [comment]
@sidey79 
Mir kam soeben eine Idee zwecks Test welche vielleicht hilfreich und eine Sicherheit darstellen könnte.

Könnte man bei einem PR, welcher die Datei 
`signalduino_protocols.hash`
enthält einen Test auf diese Datei laufen lassen.

Darin prüfen ob mindestens die Struktur

```
(
    "NR"    => 

        {
              name            => 'Bezeichner',
              id              => 'NR',
              one             => [1,-8],
              zero            => [1,-4],
              length_min      => '55',
        },
);
```

vorkommt.

Wir haben oft den Fall, wo wir vielleicht Definitionen via Textdatei / Kommentarfeld zugereicht werden können. Sobald man diese übernimmt und vielleicht doch mal etwas übersieht würde man bei Annahme des PR diese Datei nicht zum laden bekommen mit dem Modul SIGNALduino aufgrund von SYNTAXFehler.

1) Strukturprüfung Datei ( Beginn & Ende jeweils eine Klammer, Zum Schluss ein Semikolion )
2) Strukturprüfung Definition ( NR | name | id | one | zero | length_min )
3) Syntaxprüfung (ob jeweils hinter dem => ein ' .... ' UND, enthalten ist)

**Comment by sidey79** [comment]
Grundsätzlich geht das ja.

Soll der Test immer auf die neue ID laufen oder generell über alle?
Letzteres wäre leichtet denke ich.

Wir würden einfach die Datei mittels Eval laden und die Parameter prüfen.
Fehlt ein , gibt es schon beim Laden einen Fehler.
Fehlt ein Bezeichner finden wir das ja raus indem wir prüfen ob er existiert.

**Comment by HomeAutoUser** [comment]
Wenn dann würde ich es nur für sinnvoll erachten den Test generell laufen zu lassen.
Die Datei erweitern wir ständig und diese wird ja auch gepflegt mit Kommentaren oder mit Änderung/ Löschung des "developId".

**Comment by sidey79** [comment]
Also Prüfung 2 können wir problemlos aus FHEM heraus laufen lassen.
Dazu lassen wir in einer Schleife die Daten prüfen. Eventuell ändere ich was im SignalDuino Modul und wir schlagen zwei Fliegen mit einer Klappe.
Test 1 und 3 laufen schon impliziert mit, wenn FHEM gestartet wird.
Vielleicht kannst Du ja Mal Fehler provozieren und das bestätigen. Sonst haben wir hier halt noch Handlungsbedarf.

Gute Idee mit dem Test :)

**Comment by HomeAutoUser** [comment]
Der Test 3
>Syntaxprüfung (ob jeweils hinter dem => ein ' .... ' UND, enthalten ist)

endet darin, das wir bisher KEINE separate Ausgabe erhalen, das ein Fehler vorhanden ist in der Hash-Datei. Die Listen bleiben einfach kommentarlos leer.

```
2018.10.01 13:33:36 3: radino_433Mhz: IDlist MS 
2018.10.01 13:33:36 3: radino_433Mhz: IDlist MU 
2018.10.01 13:33:36 3: radino_433Mhz: IDlist MC 
```
--------------------
Test 1
>Strukturprüfung Datei ( Beginn & Ende jeweils eine Klammer, Zum Schluss ein Semikolion )

zeigt das selbe Verhalten wie bei Test 3

```
2018.10.01 13:37:40 3: nano_868Mhz: IDlist MS 
2018.10.01 13:37:40 3: nano_868Mhz: IDlist MU 
2018.10.01 13:37:40 3: nano_868Mhz: IDlist MC
```

War es gewollt ohne zusätzlichen Hinweis?

**Comment by HomeAutoUser** [comment]
Da bei einem Syntaxfehler 

`%ProtocolListSIGNALduino =  eval $protocol_data ;`

leer ist, so könnte man doch mit 
```

if (exists $ProtocolListSIGNALduino{"0"}) {
      ## ja
  } else {
      ## nein
  };
```

Das korrekte Laden abfangen und ggf. ein Log generieren. Somit erhält man die Erklärung wieso die IDList MS ... MU .. MC leer sind im Logfile

Was für ein Fehler sich dahinter verbirgt habe ich noch nichts diesbezüglich gefunden um das zu spezifizieren.

**Comment by sidey79** [comment]
Gewollt würde ich nicht unbedingt sagen :)

Das ist ein Resultat des eval Befehls.

Ich denke wir packen das einlesen des Protokoll Hashes in eine Funktion die als Rückgabe unter anderem auch den Fehler übergibt.

Die Funktion können wir dann problemlos auch in einem Test aufrufen :)

**Comment by HomeAutoUser** [comment]
Wenn wir das so machen würden

```
my %ProtocolListSIGNALduino = eval($protocol_data);

# If there's a problem eval'ing the
# code, eval() returns undef and
# the error is found in $@.
unless(%ProtocolListSIGNALduino) {
    print $@;
}
```

könnte man sich die Fehlermeldung beim Syntax ausgeben lassen und eine schöne optische Logmeldung ins File schreiben :-D

```
syntax error at (eval 2) line 1623, near ",
        #},
)"
Missing right curly or square bracket at (eval 2) line 1623, at end of line
```

Oder eben eine Funktion das es wieder was zum testen gäbe ;-)

**Comment by sidey79** [comment]
Ich habs so in der art gemacht ja. Sollte im groben funktionieren und lässt sich auch gut in einen Test einbinden

879f6cd9a41a449836a982e3ef4116f4743914fd

**Comment by HomeAutoUser** [comment]
Ich habe es soeben gesehen das du es eingebaut hast :-) Der Test läuft auch schon mit Ihr am LiveSystem.

**Comment by sidey79** [comment]
Ich habe es auch grob getestet... 100% aussagefähig ist es nicht immer, aber zumindest weiss man wo man suchen muss.
