### ISSUE TITLE
not correct distinction - Definition 30 and 83 - same?

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#305]
Ehe ich mich der Problematik ähnliche Protokolle widme, so möchte ich natürlich ggf erstmal "bereinigen".

Die Definitionen 30 und 83 sind im Prinzip gleich. Stimmt Ihr mir da zu?
Da beide auf das Modul SD_UT "zugreifen", so würde ich hier eine ggf davon herausnehmen weil innerhalb des Modules auf die ProtokollID abgefragt wird.

Def 30
```
	"30" => # a unitec remote door reed switch
			# MU;P0=-10026;P1=-924;P2=309;P3=-688;P4=-361;P5=637;D=123245453245324532453245320232454532453245324532453202324545324532453245324532023245453245324532453245320232454532453245324532453202324545324532453245324532023245453245324532453245320232454532453245324532453202324545324532453245324532023240;CP=2;O;
			# MU;P0=307;P1=-10027;P2=-691;P3=-365;P4=635;D=0102034342034203420342034201020343420342034203420342010203434203420342034203420102034342034203420342034201020343420342034203420342010203434203420342034203420102034342034203420342034201;CP=0;
		{
                        name			=> 'diverse',	
			comment         => 'unitec remote door reed switch 47031 (developModule SD_UT module is only in github available)',
			id          	=> '30',
			developId       => 'm',
			one				=> [-2,1],
			zero			=> [-1,2],
			start			=> [-30,1],				# Message is not provided as MS, worakround is start
			clockabs		=> 330,                 # ca 300 us
			format 			=> 'twostate',	  		# there is a pause puls between words
			preamble		=> 'P30#',				# prepend to converted message	
			clientmodule    => 'SD_UT', 
			modulematch     => '^P30#.{3}',
			length_min      => '12',
			length_max      => '12',				# message has only 10 bit but is paddet to 12
		},
```

Def 83

```
	"83" => ## Remote control RH787T based on MOSDESIGN SEMICONDUCTOR CORP (CMOS ASIC encoder) M1EN compatible HT12E
			# for example Westinghouse Deckenventilator Delancey, 6 speed buttons, @zwiebelxxl
			# https://github.com/RFD-FHEM/RFFHEM/issues/250
			# Taste 1 MU;P0=388;P1=-112;P2=267;P3=-378;P5=585;P6=-693;P7=-11234;D=0123035353535356262623562626272353535353562626235626262723535353535626262356262627235353535356262623562626272353535353562626235626262723535353535626262356262627235353535356262623562626272353535353562626235626262723535353535626262356262627235353535356262;CP=2;R=43;O;
			# Taste 2 MU;P0=-176;P1=262;P2=-11240;P3=112;P5=-367;P6=591;P7=-695;D=0123215656565656717171567156712156565656567171715671567121565656565671717156715671215656565656717171567156712156565656567171715671567121565656565671717156715671215656565656717171567156712156565656567171715671567121565656565671717171717171215656565656717;CP=1;R=19;O;
			# Taste 3 MU;P0=564;P1=-392;P2=-713;P3=245;P4=-11247;D=0101010101023231023232323431010101010232310232323234310101010102323102323232343101010101023231023232323431010101010232310232323234310101010102323102323232343101010101023231023232323431010101010232310232323234310101010102323102323232343101010101023231023;CP=3;R=40;O;
		{
                         name			=> 'RH787T',	
			comment         => 'Remote control for example Westinghouse Delancey 7800140 (developModule SD_UT is only in github available)',
			id          	=> '83',
			developId       => 'm',
			one				=> [-2,1],
			zero			=> [-1,2],
			start			=> [-35,1],				# calculated 12126,31579 µS
			clockabs		=> 335,                 # calculated ca 336,8421053 µS short - 673,6842105µS long 
			format 			=> 'twostate',	  		# there is a pause puls between words
			preamble		=> 'P83#',				# prepend to converted message	
			clientmodule    => 'SD_UT', 
			modulematch     => '^P83#.{3}',
			length_min      => '12',
			length_max      => '12',
		},
```

@elektron-bbs, du hattest mit mir schonmal drüber geschaut, was meinst du?
Die Nachrichten von dem 30er gehen ja auch bei dem 83er durch. Doppelte Einträge müssen ja nicht sein.

**Comment by elektron-bbs** [comment]
Nun ja, gleich sind sie auf jeden Fall nicht (start).
Bei der 83 wissen wir, welcher Chip verbaut ist. Dadurch lässt sich clockabs leicht aus dem start errechnen:
Taste 1: 11234+267=11501     11501/36=319
Das passt in etwa zu den Zeiten laut Doku zum Schaltkreis.
Bei der 30 passt das nicht:
10026+309=10335     10335/36=287
Vielleicht ist das kein HT12E oder kompatibler.
Hattest du nicht Kontakt zu einem User, der diesen Kontakt im Einsatz hat?

**Comment by sidey79** [comment]
1b935c4a20293a9ceeb9325996e5ff5d314d1976

Zum Glück haben wir eine ID aus dem Forum

**Comment by elektron-bbs** [comment]
Ich habe gerade nochmal im Forum https://forum.fhem.de/index.php/topic,43346.0.html nachgesehen. Da ist ein PIC verbaut. Der Prozessor kann zwar das Protokoll verwenden, muss sich aber nicht unbedingt an die Timings halten.

**Comment by elektron-bbs** [comment]
Hier ist dir aber ein Fehler unterlaufen. Protokoll 30 hat 330 als clockabs und nicht 500! 
Die Gesamtzeit kannst du auch nicht verwenden, wenn die Faktoren für one und Zero verschieden sind. Dann ergeben sich ja auch verschiedene Gesamtzeiten je nach Anzahl von Nullen und Einsen.

**Comment by HomeAutoUser** [comment]
@elektron-bbs 
war ein Kopierfehler. Die Gesamtzeit zum vergleichen geht dann aufgrund der Anzahl der 0 und 1 auch nicht? Wenn das Signal bei beiden Protokollen die gleiche Anzahl an 0 und 1 herausbringt??

Wenn aber die Zahlen 9900 zu 11700 sehe, so würde mich der Tolleranzbereich mal interessieren.
Das sind fast 16% Unterschied.

**Comment by elektron-bbs** [comment]
Bei Protokoll 16 ist eine 1 clockabs*3 und eine 0 clockabs*4 - ergibt also ziemliche Unterschiede je nach Anzahl Nullen oder Einsen.
Bei Protokoll 72 haben beide einen Gesamtfaktor von 3,2 - da spielt die Anzahl demnach keine Rolle.
