### ISSUE TITLE
different definition - P3.1 - P5 - P47

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#308]
Sind das "Useranpassungen" @Ralf9  oder durchaus Kleinigkeiten welche nicht in einen PR gebracht wurden?
-----------------------
**Protokoll 3.1**
@sidey79 - Version
```
one   => [3,-1],
zero  => [1,-3],
float => [1,-1],	# fuer Gruppentaste (nur bei ITS-150,ITR-3500 und ITR-300), siehe Kommentar in sub SIGNALduino_bit2itv1
sync  => [1,-40],
```

@Ralf9 - Version

```
one   => [3.5,-1],
zero  => [1,-3.8],
float => [1,-1],	# fuer Gruppentaste (nur bei ITS-150,ITR-3500 und ITR-300), siehe Kommentar in sub SIGNALduino_bit2itv1
sync  => [1,-44],
```

-----------------------
**Protokoll 5**
@sidey79 - Version
https://github.com/RFD-FHEM/RFFHEM/blob/b59d9af91939f95329447efeae38bd934da032cb/FHEM/lib/signalduino_protocols.hash#L172

@Ralf9 - Version
https://github.com/Ralf9/RFFHEM/blob/97df6d26fbe3f9e7eab5cd6ae8484cdd3794098e/FHEM/00_SIGNALduino.pm#L304

-----------------------
**Protokoll 47**
@sidey79 - Version
https://github.com/RFD-FHEM/RFFHEM/blob/b59d9af91939f95329447efeae38bd934da032cb/FHEM/lib/signalduino_protocols.hash#L939

@Ralf9 - Version
https://github.com/Ralf9/RFFHEM/blob/97df6d26fbe3f9e7eab5cd6ae8484cdd3794098e/FHEM/00_SIGNALduino.pm#L1061

**Comment by Ralf9** [comment]
**Protokoll 3.1**
sync  => [1,-44],
Ich habe -44 gewählt, damit ein großer Bereich abgedeckt ist und die Überlappung mit der ID 3 [1,-31] mit der Toleranz 0.18 nur recht gering ist.
Warum ich für one   => [3.5,-1] gewählt habe, kann ich nicht mehr nachvollziehen, wahrscheinlich hat es mit den MU-Nachrichten des users besser gepasst.

**Protokoll 5**
Da bei der ID 5 steht: Similar protocol as intertechno
habe ich mal den dispatch zum IT-Modul getestet, da ich bis jetzt noch keine MU-Nachricht hatte, bei das IT-Modul gepasst hat,
ist es wahrscheinlich besser als preamble U5# oder u5# zu nehmen 
p5# macht auch nicht so richtig Sinn

**Protokoll 47**
die clockrange => [180,260], ist wahrscheinlich besser, muß ich bei mir auch noch anpassen.

**Comment by HomeAutoUser** [comment]
@Ralf9 https://github.com/RFD-FHEM/RFFHEM/issues/218#issuecomment-369945644
deswegen vielleicht deine angepassten Werte bei Protokoll 3.1?

**Comment by HomeAutoUser** [comment]
@Ralf9 
hast du mal die Änderungen für das Protokoll 47 getestet?
>clockrange => [180,260],

**Comment by Ralf9** [comment]
> hast du mal die Änderungen für das Protokoll 47 getestet?

Ich habs kurz getestet, dies passt so. Dadurch wird auch bei der Clock ein größerer Toleranzbereich vom Sensor abgedeckt.

**Comment by HomeAutoUser** [comment]
Ich habe als letztes von dem Issues noch die Frage der Definition 3.1 offen.

Da gibt es einen Unterschied wie oben schon angedeutet.

@Ralf9 Variante
```
    "3.1"    => # MS;P0=-11440;P1=-1121;P2=-416;P5=309;P6=1017;D=150516251515162516251625162516251515151516251625151;CP=5;SP=0;R=66;
			    # MS;P1=309;P2=-1130;P3=1011;P4=-429;P5=-11466;D=15123412121234123412141214121412141212123412341234;CP=1;SP=5;R=38;  Gruppentaste, siehe Kommentar in sub SIGNALduino_bit2itv1
			    # need more Device Infos / User Message
        {
            name			=> 'itv1_sync40',	
			comment		=> 'IT remote Control PAR 1000, ITS-150',
			id          	=> '3',
			one		=> [3.5,-1],
			zero		=> [1,-3.8],
			sync		=> [1,-44],
... gekürzt dargestellt ....
},
```

@sidey79 Variante 
```
    "3.1"    => # MS;P0=-11440;P1=-1121;P2=-416;P5=309;P6=1017;D=150516251515162516251625162516251515151516251625151;CP=5;SP=0;R=66;
			    # MS;P1=309;P2=-1130;P3=1011;P4=-429;P5=-11466;D=15123412121234123412141214121412141212123412341234;CP=1;SP=5;R=38;  Gruppentaste, siehe Kommentar in sub SIGNALduino_bit2itv1
			    # need more Device Infos / User Message
        {
            name			=> 'itv1_sync40',	
			comment         => 'IT remote Control PAR 1000, ITS-150, AB440R',
			id          	=> '3',
			one             => [3,-1],
			zero		=> [1,-3],
			sync		=> [1,-40],
... gekürzt dargestellt ....
			},
```

Gern hätte ich das noch abgeglichen um den Faden zu schließen.
Können wir die Variante mit mehr Tolleranz einfach übernehmen oder gab es andere Dinge welche dies dafür sorgten?

**Comment by HomeAutoUser** [comment]
Ich habe selbst die Lösung gefunden https://github.com/RFD-FHEM/RFFHEM/issues/218#issuecomment-369945644.
Das würde heißen, wir @sidey79 sollten die Definition aufgrund dessen anpassen.

**Comment by sidey79** [comment]
Könnte man so anpassen denke ich :)
