### ISSUE TITLE
Support for door bell FreeTec PE-6946-675 (from PEARL)

### ISSUE THREAD

**Issue by git-developer** [RFD-FHEM/RFFHEM#315]
##  Specifications for new push-button

  - manufacturer: [FreeTec](http://www.free-tec.de/) (distributed by [PEARL](https://www.pearl.de/))
  - model name: Funkklingel PE-6946-675
  - manual from [FreeTec](http://www.free-tec.de/Funkklingel-mit-Voic-PE-6946-919.shtml#downloads) ([PDF](https://www.pearl.de/pdocs/PE6946_11_71399.pdf))
  
## Specifications for receiver

  - Microcontroller: Arduino Nano
  - Versionmodul (Firmware): N/A
  - Version (SIGNALduino): `V 3.3.1-RC8 SIGNALduino - compiled at Oct 4 2018 21:45:15`
  - Version (FHEM module): v3.3.2 (stable release 3.3) / `00_SIGNALduino.pm 16624 2018-04-15 18:58:49Z rudolfkoenig`

## Log
[freetec-funkklingel.log](https://github.com/RFD-FHEM/RFFHEM/files/2485914/freetec-funkklingel.log)

**Comment by sidey79** [comment]
Look like u40#2A9FFE,  is the code, the bell is sending. Does this code show up in the event log, when the bell is ringing?

Can you also please update the module to the current developer version, there are some changes which can affect your bell:
`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt
`

**Comment by git-developer** [comment]
> Look like u40#2A9FFE, is the code, the bell is sending. Does this code show up in the event log, when the bell is ringing?

Yes.

Monitoring of the bell is already working in FHEM using a combination of a dummy and a notify device, but I'd like to avoid the log messages about unknown device.

I will update to the developer version and report.

**Comment by git-developer** [comment]
Changes to my environment:
- Update to `00_SIGNALduino.pm 10488 2018-09-19 11:00:00Z v3.3.3-dev`
- `attr signalduino development u40`

Logs:  
- [freetec-funkklingel-20181017-0822.log](https://github.com/RFD-FHEM/RFFHEM/files/2486063/freetec-funkklingel-20181017-0822.log)
- [SIGNALduino_unknown_40-2018.log](https://github.com/RFD-FHEM/RFFHEM/files/2486064/SIGNALduino_unknown_40-2018.log)

**Comment by HomeAutoUser** [comment]
Hello @git-developer,
how far is the bell from the Arduino?

**Comment by git-developer** [comment]
~4m with 1 wall inbetween. Signal quality should be fine.

**Comment by git-developer** [comment]
Logs:
- [freetec-funkklingel-20181017-1052.log](https://github.com/RFD-FHEM/RFFHEM/files/2486553/freetec-funkklingel-20181017-1052.log)
- [SIGNALduino_unknown_40-20181017-1052.log](https://github.com/RFD-FHEM/RFFHEM/files/2486556/SIGNALduino_unknown_40-20181017-1052.log)

**Comment by elektron-bbs** [comment]
Diese Klingel wurde 2016 schon mal behandelt:
https://github.com/RFD-FHEM/RFFHEM/issues/49
Das Protokoll ist eigentlich schon eingerichtet worden, damals allerdings als MS. Das Signal wird allerdings jetzt als MU-Nachricht erkannt.
Bitte ersetze den Eintrag für das Protokoll 32 in der Datei signalduino_protocols.hash durch diesen Eintrag:

	"32" => #FreeTec PE-6946 -> http://www.free-tec.de/Funkklingel-mit-Voic-PE-6946-919.shtml
				# https://github.com/RFD-FHEM/RFFHEM/issues/49
		    # MS;P0=-266;P1=160;P3=-690;P4=580;P5=-6628;D=15131313401340134013401313404040404040404040404040;CP=1;SP=5;O;
				# https://github.com/RFD-FHEM/RFFHEM/issues/315
				# MU;P0=-6676;P1=578;P2=-278;P4=-680;P5=176;P6=-184;D=541654165412545412121212121212121212121250545454125412541254125454121212121212121212121212;CP=1;R=0;
				# MU;P0=146;P1=245;P3=571;P4=-708;P5=-284;P7=-6689;D=14351435143514143535353535353535353535350704040435043504350435040435353535353535353535353507040404350435043504350404353535353535353535353535070404043504350435043504043535353535353535353535350704040435043504350435040435353535353535353535353507040404350435;CP=3;R=0;O;
				# MU;P0=-6680;P1=162;P2=-298;P4=253;P5=-699;P6=555;D=45624562456245456262626262626262626262621015151562156215621562151562626262626262626262626210151515621562156215621515626262626262626262626262;CP=6;R=0;
    	{   
			name           => 'freetec 6946',
			comment        => 'Doorbell FreeTec PE-6946',
			id             => '32',
			one            => [4,-2],
			zero           => [1,-5],
			start          => [1,-45],
			#sync           => [1,-49],
			clockabs       => 150,
			format         => 'twostate',
			preamble       => 'u32#',				# prepend to converted message	
			#clientmodule   => '',   				# not used now
			#modulematch    => '',  				# not used now
			length_min     => '24',
			length_max     => '24',
    	},

Das Protokoll 40 kannst du in die Blacklist nehmen. Das erzeugt nur "Zufallszahlen".

**Comment by elektron-bbs** [comment]
Nein, der eine "Treffer" bei IT war sicher auch nur wieder Zufall, aber das müsste ich mir erst genauer ansehen. Du solltest jetzt mittels Befehl
attr signalduino development u32
dieses Protokoll als "in Entwicklung" aufnehmen und dann kontrollieren, ob die Klingelsignale zuverlässig erkannt werden.

**Comment by git-developer** [comment]
Aus meiner Sicht sieht das gut aus.

`fhem.cfg`:
```
        attr signalduino development u32
        attr signalduino blacklist_IDs 19,40
```

FHEM-Log:
```
        2018.10.18 08:04:58 1: signalduino: SIGNALduino_unknown UNDEFINED sensor SIGNALduino_unknown_32 detected
        2018.10.18 08:04:58 2: autocreate: define SIGNALduino_unknown_32 SIGNALduino_un SIGNALduino_unknown_32
        2018.10.18 08:04:58 2: autocreate: define FileLog_SIGNALduino_unknown_32 FileLog %L/SIGNALduino_unknown_32-%Y.log SIGNALduino_unknown_32
```

`SIGNALduino_unknown_32-2018.log`:
```
        2018-10-18_08:21:59 SIGNALduino_unknown_32 bitMsg: 000101010100111111111111
        2018-10-18_08:21:59 SIGNALduino_unknown_32 bitMsg_invert: 111010101011000000000000
        2018-10-18_08:21:59 SIGNALduino_unknown_32 bitCount: 24
        2018-10-18_08:21:59 SIGNALduino_unknown_32 hexMsg: 154FFF
        2018-10-18_08:21:59 SIGNALduino_unknown_32 hexMsg_invert: EAB000
        2018-10-18_08:21:59 SIGNALduino_unknown_32 hexCount or nibble: 6
        2018-10-18_08:21:59 SIGNALduino_unknown_32 lastInputDev: signalduino
        2018-10-18_08:27:02 SIGNALduino_unknown_32 bitMsg: 000101010100111111111111
        2018-10-18_08:27:02 SIGNALduino_unknown_32 bitMsg_invert: 111010101011000000000000
        2018-10-18_08:27:02 SIGNALduino_unknown_32 bitCount: 24
        2018-10-18_08:27:02 SIGNALduino_unknown_32 hexMsg: 154FFF
        2018-10-18_08:27:02 SIGNALduino_unknown_32 hexMsg_invert: EAB000
        2018-10-18_08:27:02 SIGNALduino_unknown_32 hexCount or nibble: 6
        2018-10-18_08:27:02 SIGNALduino_unknown_32 lastInputDev: signalduino
        2018-10-18_08:27:03 SIGNALduino_unknown_32 bitMsg: 000101010100111111111111
        2018-10-18_08:27:03 SIGNALduino_unknown_32 bitMsg_invert: 111010101011000000000000
        2018-10-18_08:27:03 SIGNALduino_unknown_32 bitCount: 24
        2018-10-18_08:27:03 SIGNALduino_unknown_32 hexMsg: 154FFF
        2018-10-18_08:27:03 SIGNALduino_unknown_32 hexMsg_invert: EAB000
        2018-10-18_08:27:03 SIGNALduino_unknown_32 hexCount or nibble: 6
        2018-10-18_08:27:03 SIGNALduino_unknown_32 lastInputDev: signalduino
```

Mit einem passenden IT device verhält es sich dann schon genau so, wie ich es mir vorstelle:

`fhem.cfg`:
```
        define it_tuerklingel IT 0FFFF01111 11 11
        attr   it_tuerklingel model itremote
        attr   it_tuerklingel stateFormat [it_tuerklingel:state:t]
```

FHEM-Log:
```
        2018.10.18 08:27:02 3: signalduino IT: it_tuerklingel 2018-10-18 08:21:59->on
        2018.10.18 08:27:03 3: signalduino IT: it_tuerklingel 2018-10-18 08:27:02->on
```

**Comment by git-developer** [comment]
> Hast du 2x heute morgen die Klingel gedrückt?

Ja.
> Wiederhole das bitte mehrfach nochmal.

Habe ich gemacht. Hat funktioniert, d.h. jedes Klingeln wurde korrekt erkannt. Logs:
- [freetec-funkklingel-20181018-1410.log](https://github.com/RFD-FHEM/RFFHEM/files/2491869/freetec-funkklingel-20181018-1410.log)
- [funk-20181018-1410.log](https://github.com/RFD-FHEM/RFFHEM/files/2491873/funk-20181018-1410.log) (Ich pflege dieses separate Log für Funk-Daten)

> Was möchtest du mit dem IT? Das ist ein Schalter bzw ein Modul wo vieles zusammenläuft.
> Möchtest du ein Device in FHEM sehen was dein Klingelknopf wiederspiegelt?

Ja. Setzt man für ein IT-Gerät das Attribut `model` auf den Wert `itremote`, dann werden die Schaltfunktionen deaktiviert, das passt sehr gut. Mit der o.g. Konfiguration sieht das so aus:
![grafik](https://user-images.githubusercontent.com/7452817/47154520-d7d06200-d2e2-11e8-8d81-cacf33848f44.png)

Ich nehm auch gern was anderes als ein IT-Gerät, hab aber nichts besseres gefunden. Gefällt mir jedenfalls besser als ein Dummy, weil es so out-of-the-box (also ohne notify oder DOIF) funktioniert. Ein eigenes Modul zu schreiben erscheint mir für den Anwendungsfall zu aufwändig.

**Comment by elektron-bbs** [comment]
Naja, das das jetzt so passt, ist vieleicht nur Zufall. Wenn ich das richtig deute, spricht bei deiner Klingel jetzt immer auch Protokoll 62 an:
signalduino: decoded matched MU Protocol id 62 dmsg i154FFF
Da dieses Protokoll aber für Funk-Steckdosen ist (siehe https://github.com/RFD-FHEM/RFFHEM/issues/142), kann sein, das das nach dem nächsten Batteriewechsel nicht mehr funktioniert, weil sich evtl. der Code des Senders ändert.
Außerdem passen die Timings von Protokoll 32 und 62 nicht so richtig zueinander.

**Comment by git-developer** [comment]
OK. Dann wäre also ein `dummy` auf Basis von `DMSG u32#154FFF` die robustere Wahl? Oder gibt es noch eine andere Alternative?

**Comment by HomeAutoUser** [comment]
@git-developer ,
die angedachte Variante von dir mit dem Dummy sollte in Ordnung sein.
Eine weitere Alternative habe ich gerade in Diskussion gegeben bei uns Entwicklern. Die Vielzahl von Klingeln nimmt zu und so kam mir die Überlegung, das generell umzusetzen wie du möchtest.

Das hätte den Vorteil, du bekommst automatisch ein Device angelegt wo du auch selbst in FHEM dich anklingeln könntest bzw. den Status des letzten klingeln siehst.
Bis zur Umsetzung könnte aber noch ein paar Tage dauern wenn wir dies "beschließen" oder das ganze auf ein guten Nenner stößt.

**Comment by git-developer** [comment]
Das klingt nach einer guten Idee, fände ich super.

Auch mit einem Dummy komme ich gut klar. Aus meiner Sicht ist dieses Thema erfolgreich erledigt und kann geschlossen werden.

**Comment by HomeAutoUser** [comment]
@git-developer,

Sobald das Modul für die Klingeln "online" kommt, so wirst du dies mit dem verteilen der dev-r33 erhalten. Sollten dennoch Probleme beim Empfang oder mit dem späteren Modul auftreten, so melde dich bitte wieder hier an dieser Stelle bei Github.

Das Thema kannst du bei bedarf selbst schließen, mit einem "klick" unten rechts "Close and comment" or "Close".
