### ISSUE TITLE
90_SIGNALduino_un - Überlegung - BELL Integration - zunehmende Anzahl von BELL´s

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#323]
Weil es eine Vielzahl von Bells, Klingeln unsw. gibt welche zum Teil nur als Notify verarbeitet werden aber auch wie [hier](https://github.com/RFD-FHEM/RFFHEM/issues/315#issuecomment-430992684) gern als Device dargestellt werden wollen, so kam mir und @elektron-bbs die Idee.

Wir belassen alle Klingeln als "uID" und erweitern das 90_SIGNALduino_un Modul, wo wir den Empfang des Devices 1:1 wieder herausgeben. Somit können wir dem User ein Device anlegen und man erhält auch die Funktion set "Bell" aus FHEM heraus. 

Die Anpassung im Modul zu machen, erschien uns als am effektivsten weil wir da kein zusätzliches Modul erstellen + veröffentlichen müssen weil wir das un-Modul ja für unbekannte Nachrichten eh weiterhin nutzen / behalten.

Der Vorteil einer "uID" belassung ohne änderung des preamble, das bestehende user keine Beeinträchtigung haben. Sie erhalten nur ein zusätzliches Device nach Integration und dann können Sie selbst entscheiden wie sie mit dem Device - Notifiy weiter verfahren.

EINEN Sonderfall haben wir gesehen, das die ID79 ein großes U als preamble besitzt.
Bei der ID hatten wir ja eh schon überlegt diese ins SD_UT Modul einzubinden. Diese Einbindung würden wir dann nicht durchführen sondern gleich ans un-Modul zum Abschnitt Bell.

Bevor wir hier einfach einen PR Vorschlag unterbreiten, so wollten wir mal die Idee diskutieren.

**Comment by sidey79** [comment]
Das 90_SIGNALduino_un   ist eher für unknown gedacht und mehr eine art Notlösung um mal schnell das ein oder andere noch nach einem dispatch verarbeiten zu können.

Ein Modul, in der art von SD_WS  (vielleicht SD_BL ) wäre da meiner Einschätzung nach ein besserer Ansatz.

**Comment by HomeAutoUser** [comment]
Dann werde ich nen Modul dazu beginnen. ;)
Vorlage ist ja schon da.

**Comment by Ralf9** [comment]
mir ist nicht klar, warum man dazu nicht das schon vorhandene Modul SD_UT nehmen kann?
Eine saubere Trennung wäre dann "uID" nach SIGNALduino_un und "UID" nach SD_UT
und dann noch eine neue Protokolldefinition "noDispatch", wenn definiert, dann erfolgt kein dispatch

**Comment by elektron-bbs** [comment]
SD_UT war doch sicher ursprünglich eher für für unitec gedacht. Das Konzept mit "WS" für Wetterstationen, "BL" für Bell halte ich eigentlich für besser.

**Comment by Ralf9** [comment]
dann möchstest Du nur für Bell (ID 79) ein eigenes Modul machen, was ist dann mit den IDs 81 und 83?
Oder ist Bell der Erfinder es Protokolls

**Comment by elektron-bbs** [comment]
Ich finde z.Z. 5 Protokolle von Klingeln in der signalduino_protocols.hash. Diese könnten alle im neuen Modul "Bell" landen.
Die Protokolle 81 und 83 sind im Modul SD_UT gelandet, weil sie alle auf dem Protokoll des Chips HT12E beruhen. Eigentlich sollte man es umbenennen. Ursprung war wahrscheinlich irgendeine Funkfernbedienung, die unter dem Label "unitec" vertrieben wird/wurde.

**Comment by HomeAutoUser** [comment]
Wenn ein neues Modul, dann wo alles Klingeln darauf reagieren sollen. Nur für eine bzw ein Protokoll macht kein Sinn.

Wenn eine Klingel nun für das UT Modul vorgesehen ist (id 79 glaube), so würde ich das umswitchen weil das bisher nurvorgesehen ist. Eine Verarbeitung für das Modul erfolgt noch nicht.

Die saubere Trennung SD_BL klingt am vernünftigen.

**Comment by Ralf9** [comment]
> Die Protokolle 81 und 83 sind im Modul SD_UT gelandet, weil sie alle auf dem Protokoll des Chips HT12E beruhen. 

Du gehst also davon aus, daß die Klingeln nicht auf dem Protokoll des Chips HT12E beruhen?

Ich fände es besser dies alles in einem Modul zu haben, die Protokolle sind alle sehr ähnlich.
Dies ist aber nur meine Meinung. Letztendlich ist entscheidend wie Sidey es gerne hätte.

**Comment by HomeAutoUser** [comment]
>Vielleicht sollte man aber ein Modul für Klingeln und eins für Funksteckdosen machen und dann das SD_UT aussterben lassen.

Da in dem SD_UT auch Devices wie Ventilatoren und Festerkontakte oder Alarmkontakte drin sind, so ist ein aussterben nicht ratsam weil es gerade mit Ventilatoren schon genutzt wird.

Im Konsens höre ich heraus, das ein separates Modul für Klingeln am besten wäre. So haben wir die Unterteilung und eine Trennung zu den anderen.

**Comment by HomeAutoUser** [comment]
Eine Variante könnte auch sein, wir lassen aufgrund der Ähnlichkeit das SD_UT Modul und fügen die Klingeln dort hinzu. Da Steht UT für Universal Technik :D

Dort sind derzeit Devices mit einer 12Bit länge verarbeitet. Klingeln haben auch längere Codes aber dazu teste ich mal eine Klingel welche ich Hardwaremäßig vorliegend habe, ob diese wirklich 12Bit hat oder einen anderen längeren Code.

**Comment by sidey79** [comment]
Okay das mit Universal klicken gut.
Da könnte ich ja auch meine Funk Lichterkette dann einbauen :(

**Comment by HomeAutoUser** [comment]
Ich habe mal das [BELL Modul erstellt](https://github.com/HomeAutoUser/RFFHEM/commit/b564de64b24291cea7c463ff159a2fbf001a10cb). Es wäre schön wenn ihr mal drüber schaut bevor ich den PR erstelle.

**Comment by sidey79** [comment]
Habe dir Kommentare hinterlassen, nichts wildes :)

**Comment by HomeAutoUser** [comment]
[Ich habe die Anpassungen hier vorgenommen.](https://github.com/HomeAutoUser/RFFHEM/commit/7416bdf3bbcaf915c8e42cc8198217f8cf2ca292)
[Das komplette Modul wäre hier.](https://github.com/HomeAutoUser/RFFHEM/blob/dev-r33_bell/FHEM/14_SD_BELL.pm)
Sollten alle Dinge geklärt sein, so überführe ich es zu uns in einem PR und wir können Schritt 2 vorehmen, die Klingeln zum Modul "umleiten" in der Hash.

**Comment by sidey79** [comment]
Gegen einen PR spricht nichts.  Wenn wir das Modul auch ins SVN bringen wollen wäre die maintainer Frage zu klären.


Ich frage halt halt vielleicht noch 2 sachen nach, aber nur weil ich es nicht auf Anhieb verstehe.
Ich habe auch das Gefühl, dass es gut klappt um sich gegenseitig den code zu erklären.

**Comment by HomeAutoUser** [comment]
>Gegen einen PR spricht nichts. Wenn wir das Modul auch ins SVN bringen wollen wäre die maintainer Frage zu klären.

Ich notiere oben im Modul meinen Namen und sobald wir das Modul im Github haben in der DEV-r33 würde ich im Forum noch einen Faden eröffnen.

Gern kann ich es auch direkt von mir ins SVN stellen aber ich fände den Weg über das DEV-r33 besser weil es Bestandteil des Signalduinos ist.

Abschließend noch die „Abnickungsfrage“ ob alle einverstanden sind, das wir die Bells welche unter uXX laufen so lassen und mit u auswerten weil ein User ja ggf ein Notify haben könnte.

Die einzige Änderung würde ich bei U79 vornehmen in P79.

Jeweils bei den Bell ID‘s natürlich auf das Modul „Switchen“.

**Comment by elektron-bbs** [comment]
Ich würde keine Protokolle unter "uXX" laufen lassen, für die ein Modul / eine Auswertung existiert. Das bringt das Konzept durcheinander. Du hast selbst folgenden Satz in die Doku geschrieben:

"preamble => 'u..' # message is unknown and without module, forwarding SIGNALduino_un or FHEM DOIF"

Die wenigen Nutzer, die jetzt mit DOIF oder notify auf die Klingeln reagieren lassen, werden ja wohl merken, das ab sofort ein Device angelegt wird, mit dem es sich besser auswerten lässt.

**Comment by sidey79** [comment]
Können wir hier schließen. Das Modul für die Klingeln existiert ja nun.

**Comment by HomeAutoUser** [comment]
Mit diesem https://github.com/RFD-FHEM/RFFHEM/pull/366 PR ist dann der Faden hier geschlossen und die Integration abgeschlossen.
