### ISSUE TITLE
dev-cresta -> devrawIn

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#33]
- [x] Commandref anpassen
- [x] Wiederholung der Nachricht aus Hideki filtern.
- [x] Die Daten erhalten ein Präfix nach dem Schema P<ID>#<Nachricht> wenn P noch nicht verwendet wird.

**Comment by Ralf9** [comment]
Ich habe jetzt die Änderungen von 00_SIGNALduino.pm von dev-rawin nach dev-cresta übernommen

**Comment by sidey79** [comment]
Ich weiss nicht was Du gemacht hast, aber :

This branch is 97 commits ahead, 22 commits behind dev-rawIn.

Kann also nicht stimmen, dass Du rawin in dev-cresta geführt hast, sonst wäre er nicht 22 behind.

**Comment by sidey79** [comment]
Nicht falsch verstehen, ich habe es jetzt zurück gesetzt... ohne merge klappt das im log nicht.

**Comment by sidey79** [comment]
Ich habe Präfix und Commandref aktualisiert.

Ich habe es auch getestet, es funktioniert bei mir mit Testdaten.

**Comment by sidey79** [comment]
Gut, da ich nichts negatives oder positives vernommen habe, mache ich mich jetzt an das Zusammenführen.
