### ISSUE TITLE
attr cc1101_patable_"frequenz" from ccconf without attr cc1101_frequency?

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#356]
## Expected Behavior
- cc1101_patable_433 always no matter what frequency

## Actual Behavior
- attr cc1101_patable_868 not in set list if attr cc1101_frequency not set

## Steps to Reproduce the Problem

  1. receiver with config 868Mhz and cc1101, set attrb list
  2. ccconf frequency 868Mhz
  3. view attr list

## Specifications

  - Microcontroller: nanoCC1101
  - Versionmodul (Firmware): V 3.3.1-RC8_181106 SIGNALduino cc1101
  - Version (SIGNALduino): v3.3.3-dev_12.11.

**Comment by HomeAutoUser** [comment]
... das das Atttribut cc1101_frequency gesetzt werden muss war mir neu ....

@sidey79 , kann man die Frequenz nicht auslesen aus dem ccconf ohne diese manuell einzustellen?

@elektron-bbs, wieder was dazu gelernt.

**Comment by elektron-bbs** [comment]
Ähm, ja, aber wozu soll das Attribut gut sein?

**Comment by HomeAutoUser** [comment]
Es werden so versch. Einstellungen eingestellt vom Empfänger je nach Version wenn ich das richtig überblicke.

```
my %patable = (
  "433" =>
  {
    "-10_dBm"  => '34',
    "-5_dBm"   => '68',
    "0_dBm"    => '60',
    "5_dBm"    => '84',
    "7_dBm"    => 'C8',
    "10_dBm"   => 'C0',
  },
  "868" =>
  {
    "-10_dBm"  => '27',
    "-5_dBm"   => '67',
    "0_dBm"    => '50',
    "5_dBm"    => '81',
    "7_dBm"    => 'CB',
    "10_dBm"   => 'C2',
  },
);
```

Da könnte man ggf. auch das Reading ccconf nutzen um keines separat zu definieren wenn ich das richtig durchschaue.

**Comment by Kolbi** [comment]
Wäre nicht auch die Hilfe falsch?

cc1101_frequency
Frequenzeinstellung des cc1101. | Bsp: 433.920Mhz / 868.350Mhz

Es werden doch nur 433 oder 868 erwartet?

**Comment by elektron-bbs** [comment]
Ja, es erscheint eine Perl-Warnung:
2018.11.15 17:38:48 1: PERL WARNING: Argument "433.920Mhz" isn't numeric in numeric lt (<) at ./FHEM/00_SIGNALduino.pm line 2800.

**Comment by sidey79** [comment]
in cc1101_frequency sollte man die Frequenz durchaus genau einstellen können oder? 433 ist ja nicht 433.920
