### ISSUE TITLE
SD WS Device mit updated after rename

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#363]
## Expected Behavior

Renamed device gets updates 

## Actual Behavior

Renamed device ist not updated

## Steps to Reproduce the Problem

 Signalduino Empfängt Daten einer Wetterstation über ein 433er selbstbau CUL und legt ein neues Device "SD_WS37_TH_2".
Dieses Device wird in "WS_Aussen_Bresser" umbenannt.
Danach empfängt "WS_Aussen_Bresser" keine Telegramme mehr und es wird ein neues "SD_WS37_TH_2" angelegt.
  

## Specifications

  - Microcontroller:
  - Versionmodul (Firmware):
( where can I find? devicename -> Internals -> versionmodul )
  - Version (SIGNALduino):
( where can I find? devicename -> Internals -> version )

https://r.tapatalk.com/shareLink?url=https%3A%2F%2Fforum%2Efhem%2Ede%2Findex%2Ephp%3Ftopic%3D93309%2E0&share_tid=93309&share_fid=75100&share_type=t

**Comment by elektron-bbs** [comment]
Das kann ich leider nicht nachvollziehen. Ich habe z.B: ein SD_WS_33_T_2. Nach Umbenennen in "Kuehschrank" wird ganz normal weiter empfangen und in das Log geschrieben. Einen Sensor mit Protokoll 37 steht mir nicht zur Verfügung.

**Comment by sidey79** [comment]
Habe es nachgestellt, aber konnte den Fehler nicht reproduzieren
