### ISSUE TITLE
SD_BELL Error or other interaction

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#368]
> Undefined subroutine &SD_BELL::readingsBeginUpdate called at ./FHEM/14_SD_BELL.pm line 201.

Obwohl Subroutine definiert
@Sidey79 da benötige ich deine Hilfe weil du wolltest diese Variante und ich diese nicht „beherrsche“ ;)

Schade das dieser Fehler nicht auftauchte wenn man manche Daten dispatchte. Finde ich komisch.

Schnelles Handeln sollten wir haben da der Fehler FHEM stoppt.

**Comment by HomeAutoUser** [comment]
Ich habe nun erneut nochmal mir die Daten beim Senior angesehen. Wenn ich das Signal dispatche welche vor dem Fehler erschien passiert nichts. Die einzige Erklärung welche ich habe, das der shutdown restart Befehl bei FHEM oder der reload bei dem Modul nicht akzeptiert wurde. Ich lasse es nun laufen mit Augen auf den Fehler ob er wieder auftritt.

**Comment by trosenda** [comment]
Ich kann mein Fhem damit auch abschießen. Einfach 2 Mal klingeln.

**Comment by HomeAutoUser** [comment]
@trosenda 
BITTE FHEM neustarten, schauen welche ID an das Modul gegeben wurde und als Workaround die ID als BlackID eintragen im Empfänger. Ich suche schon und versuche es nachzustellen aber leider läuft es derzeit auf dem Testsystem ....

**Comment by HomeAutoUser** [comment]
@trosenda dieser Fehler sollte nun behoben sein. Funktioniert es bei dir? Bei den Testsystemen habe ich keinen Abschuss mehr.

**Comment by trosenda** [comment]
konnte keinen absturz mehr erzeugen !
