### ISSUE TITLE
Intertek 1946518 / ELRO Funksteckdose

### ISSUE THREAD

**Issue by Kolbi** [RFD-FHEM/RFFHEM#382]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: Intertek Modell: 1946518 // ELRO 
  - model name:
  - pictures of the device / the board (very helpful)

  
## Specifications 

  - Microcontroller: Arduino Nano + 433 Mhz low cost 
  - Version (Firmware): V 3.3.1-RC9 SIGNALduino - compiled at Nov 14 2018 23:02:48
  - Versionmodul (FHEM Module): v3.3.3-dev_12.11.

```
MS;P1=290;P2=-1015;P3=924;P4=-393;P5=-10144;D=15121212121212121212121212123412341234123412341212;CP=1;SP=5;R=0;O;m2;

MS;P1=296;P2=-1008;P3=931;P4=-383;P5=-10137;D=15121212121212121212121212123412341234123412341212;CP=1;SP=5;R=0;O;m2;

```
Es wird bereits als Gerät angelegt:
```
defmod IT_000000FFFF IT 000000FFFF 0F F0
attr IT_000000FFFF IODev sduino
attr IT_000000FFFF room IT

setstate IT_000000FFFF off
setstate IT_000000FFFF 2018-11-12 23:59:56 protocol V1
setstate IT_000000FFFF 2018-11-27 09:21:49 state off

```
Jedoch lassen sich die Funksteckdosen aus FHEM nicht schalten.

Log:
```
2018.11.24 00:22:01.097 3: sduino433 IT: IT_000000FFFF on->off
2018.11.24 08:18:28.118 3: sduino433 IT: Code 11 not supported by IT_000000FFFF.
2018.11.24 08:18:28.119 3: sduino433 IT: Code 11 not supported by IT_000000FFFF.
2018.11.24 08:18:28.124 3: sduino433: Unknown code i00055F, help me!
2018.11.24 08:18:29.342 3: sduino433 IT: IT_000000FFFF off->off
2018.11.25 20:05:16.556 3: sduino433 IT: IT_000000FFFF off->off
2018.11.26 20:10:54.351 3: sduino433 IT_set: IT_000000FFFF on
2018.11.26 20:10:56.323 3: sduino433 IT_set: IT_000000FFFF off
2018.11.26 20:11:03.148 3: sduino433 IT: IT_000000FFFF off->on
2018.11.26 20:16:57.993 3: sduino433: Unknown code u19#001550, help me!
2018.11.26 20:16:58.015 3: sduino433: Unknown code u19#00055, help me!
2018.11.26 20:16:58.170 3: sduino433 IT: IT_000000FFFF on->off
2018.11.27 09:01:48.892 3: sduino433 IT: IT_000000FFFF off->on
2018.11.27 09:21:49.965 3: sduino433 IT: IT_000000FFFF on->off
```

Ich schaue heute Abend nach der genauen Bezeichnung und kann weitere Logs zu allen Tasten geben.

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @sidey79, @HomeAutoUser, and @elektron-bbs.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/114 (Protokoll für minify Funksteckdose), https://github.com/RFD-FHEM/RFFHEM/issues/70 (Elro (Smartwares) Doorbell DB200), and https://github.com/RFD-FHEM/RFFHEM/issues/47 (Penny Funksteckdose Modell: 2335191R).

**Comment by sidey79** [comment]
Hast Du schon versucht das Attribut itclock für das IT Gerät  anzupassen?
290 könnte funktionieren.

**Comment by Kolbi** [comment]
Nein habe ich noch nicht, In dem Fall entspricht itclock = +- P1 ?

Probiere ich gerne heute Abend.

**Comment by Kolbi** [comment]
Itclock 290 oder 250 bringt leider keine Besserung. Ich logge nachher nochmal ausführlich mit Verbose 4.

**Comment by elektron-bbs** [comment]
Zuerst wären eigentlich erst mal genauere Infos zu dem Teil angesagt, "ELRO Funksteckdose" ist ziemlich allgemein.
Vieleicht musst du auch nur eine passende Adresse einstellen, damit sie als IT durchgehen (siehe https://wiki.fhem.de/wiki/Intertechno_Code_Berechnung).

**Comment by Kolbi** [comment]
Sorry sind Intertek Modell: 1946518

(Handy daher kurz gehalten)

**Comment by Kolbi** [comment]
Taste A ein:
`2018.12.05 19:13:01.610 4: sduino433/msg READredu: MS;P0=288;P1=-370;P2=-10135;P3=-1013;P4=943;D=02030303030303030303030303034103410341034141414141;CP=0;SP=2;R=0;m2;
2018.12.05 19:13:01.611 4: sduino433: Matched MS Protocol id 3 -> itv1
2018.12.05 19:13:01.611 4: sduino433: Decoded MS Protocol id 3 dmsg i00055F length 24 RSSI = -74
2018.12.05 19:13:01.611 4: sduino433 IT: message "i00055F" (7)
2018.12.05 19:13:01.612 4: sduino433 IT: msgcode "000000FFFF11" (12) bin = 000000000000010101011111
2018.12.05 19:13:01.612 3: sduino433 IT: Code 11 not supported by IT_000000FFFF.
2018.12.05 19:13:01.612 4: sduino433 IT: message "i00055F" (7)
2018.12.05 19:13:01.612 4: sduino433 IT: msgcode "000000FFFF11" (12) bin = 000000000000010101011111
2018.12.05 19:13:01.613 3: sduino433 IT: Code 11 not supported by IT_000000FFFF.
2018.12.05 19:13:01.619 3: sduino433: Unknown code i00055F, help me!`
Taste A aus:
`2018.12.05 19:22:20.278 4: sduino433/msg READredu: MS;P3=272;P4=-1037;P5=911;P6=-407;P7=-10153;D=37343434343434343434343434345634563456345634563434;CP=3;SP=7;R=0;O;m2;
2018.12.05 19:22:20.279 4: sduino433: Matched MS Protocol id 3.1 -> itv1_sync40
2018.12.05 19:22:20.279 4: sduino433: Decoded MS Protocol id 3.1 dmsg i000554 length 24 RSSI = -74
2018.12.05 19:22:20.280 4: sduino433 IT: message "i000554" (7)
2018.12.05 19:22:20.280 4: sduino433 IT: msgcode "000000FFFFF0" (12) bin = 000000000000010101010100
2018.12.05 19:22:20.280 3: sduino433 IT: IT_000000FFFF off->off
2018.12.05 19:22:20.420 4: sduino433/msg READredu: MS;P3=296;P4=-1009;P5=940;P6=-370;P7=-10133;D=37343434343434343434343434345634563456345634563434;CP=3;SP=7;R=0;O;m1;
2018.12.05 19:22:20.420 4: sduino433: Matched MS Protocol id 3 -> itv1
2018.12.05 19:22:20.421 4: sduino433: Decoded MS Protocol id 3 dmsg i000554 length 24 RSSI = -74
2018.12.05 19:22:20.421 4: sduino433 Dispatch: i000554, Dropped due to short time or equal msg
2018.12.05 19:22:20.606 4: sduino433/msg READredu: MS;P3=289;P4=-1012;P5=949;P6=-365;P7=-10133;D=37343434343434343434343434345634563456345634563434;CP=3;SP=7;R=0;m0;
2018.12.05 19:22:20.606 4: sduino433: Matched MS Protocol id 3 -> itv1
2018.12.05 19:22:20.606 4: sduino433: Decoded MS Protocol id 3 dmsg i000554 length 24 RSSI = -74
2018.12.05 19:22:20.606 4: sduino433 Dispatch: i000554, Dropped due to short time or equal msg
2018.12.05 19:22:20.607 4: sduino433/msg READredu: MS;P3=289;P4=-1012;P5=949;P6=-365;P7=-10133;D=37343434343434343434343456345634563456345656565656;CP=3;SP=7;R=0;
2018.12.05 19:22:20.607 4: sduino433: Matched MS Protocol id 3 -> itv1
2018.12.05 19:22:20.607 4: sduino433: Decoded MS Protocol id 3 dmsg i00155F length 24 RSSI = -74
2018.12.05 19:22:20.608 4: sduino433 IT: message "i00155F" (7)
2018.12.05 19:22:20.608 4: sduino433 IT: msgcode "00000FFFFF11" (12) bin = 000000000001010101011111
2018.12.05 19:22:20.608 4: sduino433 IT: 00000FFFFF not defined (Switch code: 11)`

**Comment by sidey79** [comment]
Gibt es hier neue Erkenntnisse oder Infos?

**Comment by elektron-bbs** [comment]
Letzte Nachricht von @Kolbi am 06.12.2018 - es besteht wahrscheinlich kein Interesse mehr.
