### ISSUE TITLE
visivon remote with PT4450 OOK/ASK

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#39]
2 button remote 

2015.10.23 15:41:56 4: SIGNALduino/msg READ: MU;P0=132;P1=500;P2=-233;P3=-598;P4=-980;P5=4526;D=
012120303030303120303030
453120303121212121203121212121203121212121212030303030312030312031203030303030312031203031212120303030303120303030
453120303121212121203121212121203121212121212030303030312030312031203030303030312031203031212120303030;CP=0;O;

53 looks like a end marker
12 bit 0
03 bit 1

**Comment by sidey79** [comment]
Basic Demodulation works.

If first bit is not in message, then a bit will be padded at end and the message length check will cause no abort.

MU Style demodulation could use the long on period to detect this as a begin of a new transmission.

**Comment by sidey79** [comment]
demodulation finished.

**Comment by HomeAutoUser** [comment]
@sidey79 hast du die Hardware dazu oder hattest du die Daten von anderer Stelle?
Ich bin auf der Suche nach RAW Daten um das Protokoll ggf. zu vollenden.

**Comment by sidey79** [comment]
Ich habe die Hardware nicht, leider auch den Foren Beitrag nicht vermerkt :(

**Comment by elektron-bbs** [comment]
Ich habe ihn jetzt wieder gefunden :-)
https://forum.fhem.de/index.php/topic,42273.0.html
