### ISSUE TITLE
MU 00_SIGNALduino.pm: clockabs restriction completely not handled (FATAL?), it seems

### ISSUE THREAD

**Issue by andim2** [RFD-FHEM/RFFHEM#396]
Tried some door bell (Globaltronics GT-RD-1T) again, now that I know a lot more about this stuff:

2018.11.29 21:52:26 5: sduino433: start pattern for MU Protocol id 86 -> CAME \ Novy not found, aborting
2018.11.29 21:52:26 5: sduino433/RAW READ: /^BMU;P0=-10284;P1=336;P2=-941;P3=943;P4=-1573;D=012323234123412341232341232323234141414123;CP=1;R=223;^C

2018.11.29 21:52:26 4: sduino433/msg READ: ^BMU;P0=-10284;P1=336;P2=-941;P3=943;P4=-1573;D=012323234123412341232341232323234141414123;CP=1;R=223;^C
2018.11.29 21:52:26 1: DEBUG>sduino433: incoming message: (MU;P0=-10284;P1=336;P2=-941;P3=943;P4=-1573;D=012323234123412341232341232323234141414123;CP=1;R=223;)

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  pattern 0 -10284 

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  pattern 1 336 

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  pattern 2 -941 

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  pattern 3 943 

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  pattern 4 -1573 

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  data 012323234123412341232341232323234141414123

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted  clockidx 1

2018.11.29 21:52:26 1: DEBUG>sduino433: extracted RSSI 223 

2018.11.29 21:52:26 1: DEBUG>sduino433: processing unsynced message

2018.11.29 21:52:26 1: DEBUG>Testing against Protocol id 5 -> unitec6899

.
.
.

2018.11.29 21:52:26 5: sduino433: start pattern for MU Protocol id 32 -> freetec 6946 not found, aborting
2018.11.29 21:52:26 1: DEBUG>Testing against Protocol id 34 -> QUIGG_GT-7000
2018.11.29 21:52:26 1: DEBUG>Searching in patternList: $VAR1 = {
          '3' => '1.4',
          '1' => '0.5',
          '4' => '-2.4',
          '0' => '-15.6',
          '2' => '-1.4'
        };

2018.11.29 21:52:26 1: DEBUG>tol: looking for (-1 +- 1)
2018.11.29 21:52:26 1: DEBUG>index => gap in tol (+- 1) of pulse (-1) : $VAR1 = {
          '2' => '0.4'
        };

2018.11.29 21:52:26 1: DEBUG>closest pattern has index: 2
2018.11.29 21:52:26 1: DEBUG>tol: looking for (2 +- 1)
2018.11.29 21:52:26 1: DEBUG>index => gap in tol (+- 1) of pulse (2) : $VAR1 = {
          '3' => '0.6'
        };

2018.11.29 21:52:26 1: DEBUG>closest pattern has index: 3
2018.11.29 21:52:26 1: DEBUG>looking for substr 23
2018.11.29 21:52:26 1: DEBUG>Found matched one
2018.11.29 21:52:26 1: DEBUG>added 23 
2018.11.29 21:52:26 1: DEBUG>tol: looking for (-2 +- 1)
2018.11.29 21:52:26 1: DEBUG>index => gap in tol (+- 1) of pulse (-2) : $VAR1 = {
          '4' => '0.4',
          '2' => '0.6'
        };

2018.11.29 21:52:26 1: DEBUG>closest pattern has index: 4
2018.11.29 21:52:26 1: DEBUG>closest pattern has index: 2
2018.11.29 21:52:26 1: DEBUG>tol: looking for (1 +- 1)
2018.11.29 21:52:26 1: DEBUG>index => gap in tol (+- 1) of pulse (1) : $VAR1 = {
          '1' => '0.5',
          '3' => '0.4'
        };
2018.11.29 21:52:26 1: DEBUG>closest pattern has index: 3
2018.11.29 21:52:26 1: DEBUG>closest pattern has index: 1
2018.11.29 21:52:26 1: DEBUG>looking for substr 43
2018.11.29 21:52:26 1: DEBUG>looking for substr 41
2018.11.29 21:52:26 1: DEBUG>Found matched zero
2018.11.29 21:52:26 1: DEBUG>added 41 
2018.11.29 21:52:26 4: sduino433: Fingerprint for MU Protocol id 34 -> QUIGG_GT-7000 matches, trying to demodulate
2018.11.29 21:52:26 1: DEBUG>signalRegex is (?:23|41){19,} 
2018.11.29 21:52:26 5: part is 2323234123412341232341232323234141414123 starts at position 2 and ends at 42
2018.11.29 21:52:26 5: sduino433: Starting demodulation (regex: (?:)((?:23|41){19,}) Pos 0) length_min_max (19..20) length=20
2018.11.29 21:52:26 1: DEBUG>sduino433: demodulated message raw (1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0 0 0 1), 20 bits

2018.11.29 21:52:26 5: sduino433: dispatching hex: P34#EADE1
2018.11.29 21:52:26 1: DEBUG>sduino433: modmatch passed for: P34#EADE1
2018.11.29 21:52:26 4: sduino433: decoded matched MU Protocol id 34 dmsg P34#EADE1 length 20 dispatch(1/4) RSSI = -90.5

## Expected Behavior

P34 NOT chosen (P34 clockabs is 660, which is an AWFUL LOT higher than CP=1: P1=336).

## Actual Behavior

P34 chosen.

## Steps to Reproduce the Problem

  1. debug = 5, verbose = 1
  3. get sduino_dummy raw MU;P0=-24976;P1=239;P2=-995;P3=902;P4=-1666;D=012323234123412341232341232323234141414123;CP=1;R=221;

I tried to add the clockabs range check available in MS and missing in MU to MU, too:

                        my $valid=1;
                        Debug "Testing against Protocol id $id -> $ProtocolListSIGNALduino{$id}{name}"  if ($debug);
        
                        # Check Clock if is it in range
                        $valid=SIGNALduino_inTol($ProtocolListSIGNALduino{$id}{clockabs},$clockabs,$clockabs*0.30) if ($ProtocolListSIGNALduino{$id}{clockabs} > 0);
                        Debug "validclock = $valid; clockabs proto $ProtocolListSIGNALduino{$id}{clockabs} vs. $clockabs"  if ($debug);
                        
                        next if (!$valid) ;
                
                        Debug "Searching in patternList: ".Dumper(\%patternList) if($debug);

However
my attempt fails since the $clockabs var which is used for that purpose in MS handler currently is assigned-to/used differently in MU handler:
2018.11.29 22:09:54 1: DEBUG>Testing against Protocol id 34 -> QUIGG_GT-7000
2018.11.29 22:09:54 1: DEBUG>validclock = 1; clockabs proto 660 vs. 660

 --> would need further rework to have the actual protocol record's clockabs attribute available for comparison (could you do that? My perl foo is not immediate enough ;). 

VERY IMPORTANT NOTE:
This missing clockabs restriction in MU protocols handling seems to be
one very grave contribution to imprecision in protocol resolution/routing, HOWEVER
I get the impression that
in general, we're being much too imprecise:
e.g. we're doing a clockabs range check with a hard-coded imprecision factor of 0.3, whereas for many protocols this may be undesired, since they are ok with much more restrictive clock pulse values.
Thus 0.3 might remain a builtin default, however it would be useful to
have protocol records support some kind of "range/deviation" attribute which could provide a protocol-specific range precision (or, do it the opposite way: use a VERY STRICT builtin default of some value of maybe 0.1 or so, and require every protocol record which isn't ok with that to specify something more coarse, in order to get decoded successfully).

I believe we need to arrive at a point where all protocol records truly ARE ones for EXACTLY that kind of protocol / device group (only!!), and thus DO NOT "accidentally" / ""conveniently"" (hah!) match enough to "successfully" (hah!) process data of entirely different hardware. The protocol record is the one to delegate things to a destination module (preamble / clientmodule), thus that one is the last moment where we're able to get things right... or completely wrong.

## Specifications

  - Microcontroller:

Arduino CC1101

  - Version (Firmware):
( can be found here: devicename -> Internals -> version )
  - Versionmodul (FHEM Module):
( can be found here: devicename -> Internals -> versionmodul )

version | V 3.3.1-RC10 SIGNALduino cc1101  - compiled at Nov 19 2018 23:11:15
-- | --
versionmodul | v3.3.3-dev_24.11.

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @sidey79, and @HomeAutoUser.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/381 (00_SIGNALduino.pm MU: matching of start pattern: wrong? clarification/docs needed!!), https://github.com/RFD-FHEM/RFFHEM/issues/154 (Absturz FHEM bei "reload 00_SIGNALduino.pm"), https://github.com/RFD-FHEM/RFFHEM/issues/83 (00_SIGNALduino.pm Zeile 2937 dev-r32), https://github.com/RFD-FHEM/RFFHEM/issues/176 (FHEM hängt sich auf durch Fehler im 00_SIGNALduino.pm Modul), and https://github.com/RFD-FHEM/RFFHEM/issues/314 (00_SIGNALduino.pm - FHT80 - WARNING after fhem-5.9 install - Data aus SVN).

**Comment by sidey79** [comment]
The `CP=1` message from the microcontroller can't be trusted for MU messages.

There is no scheme, how the clock will be provided to the receiver as in MS signals.
In MU signals, the clock is an virtual value, wich is used to find the pulse length for zereo and one bit.
In this case, i think the clock is a value around 330 uS.

Changing the default tolerance from 0.3 to another value will be a breaking change, because there are serval factors, which affects time measurements.
So having two arduinos with similar reciver will report different values due to inaccurate system components like crystals and so on.

**Comment by sidey79** [comment]
I haven't noticed any new comments here. I'll close this issue. Please reopen if you have additional questions / comments.
