### ISSUE TITLE
Fehler in 14_SD_UT.pm seit 03.12.2018

### ISSUE THREAD

**Issue by Kolbi** [RFD-FHEM/RFFHEM#405]
## Actual Behavior
2018.12.03 12:02:59.671 1: reload: Error:Modul 14_SD_UT deactivated:
 Global symbol "$readingname" requires explicit package name (did you forget to declare "my $readingname"?) at ./FHEM/14_SD_UT.pm line 825.
Global symbol "$readingname" requires explicit package name (did you forget to declare "my $readingname"?) at ./FHEM/14_SD_UT.pm line 827.
syntax error at ./FHEM/14_SD_UT.pm line 827, near "):"

2018.12.03 12:02:59.671 0: Global symbol "$readingname" requires explicit package name (did you forget to declare "my $readingname"?) at ./FHEM/14_SD_UT.pm line 825.
Global symbol "$readingname" requires explicit package name (did you forget to declare "my $readingname"?) at ./FHEM/14_SD_UT.pm line 827.
syntax error at ./FHEM/14_SD_UT.pm line 827, near "):"

2018.12.03 12:02:59.672 0: ERROR: Cannot autoload SD_UT

## Steps to Reproduce the Problem

  1. Update to latest version
  2. Restart FHEM

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/176 (FHEM hängt sich auf durch Fehler im 00_SIGNALduino.pm Modul), and https://github.com/RFD-FHEM/RFFHEM/issues/45 (HE-12 decoding).

**Comment by HomeAutoUser** [comment]
Hallo, danke für den Hinweis. 
Den Fehler fixen wir umgehend sobald der PC in der Nähe ist heute.

**Comment by sidey79** [comment]
@HomeAutoUser 

Habe einen PR erstellt...

**Comment by HomeAutoUser** [comment]
PR ist durch und somit auch der Fehler gefixt.

**Comment by HomeAutoUser** [comment]
ToDo @sidey79, für solche Fälle würde es sehr sinnvoll sein, das ein Test in TRAVIS die Ladbarkeit vom Modul prüft. Sobald ein Modul nicht geladen werden kann, darf kein ok erscheinen zum mergen.

**Comment by sidey79** [comment]
@HomeAutoUser 

Ja das könnten wir machen.
