### ISSUE TITLE
Release 3.2

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#41]
Todos for r3.2

- [x] Improved whitelist
- [x] Support start and end marker for MU protocols
- [ ] ~~Dynamic logical modules~~
- [x] OSV3 support
- [x] Better message handling, when performing get actions
- [x] Support filter function per protocol 
- [x] Change message length check: check before padding bits not after
- [x] Sendcommand where bits, protocol and repeats can be specified
- [x] Inform User if device has supported firmware

**Comment by Ralf9** [comment]
> Better message handling, when performing get actions
Was ist darunter zu verstehen?

**Comment by sidey79** [comment]
Es kann passieren, dass eine Get Nachricht abgeholt wird und direkt im Anschluss noch eine Signal Nachricht kommt.

Die Signal Nachricht wird dann nicht ausgewertet.

**Comment by Ralf9** [comment]
Ich habe eine Idee wie man das "message handling, when performing get actions" verbessern könnte.
Da muß dann aber einiges geändert werden.
Ich denke das wäre dann was für das dev-v33.
Wenn es für Dich ok ist, könntest Du dann ein Release 3.3 mit einem Todos for r3.3 aufmachen?
Ein "better ping handling" kann dann auch in die r3.3

Außerdem hätte ich gerne noch eine ToDo und Wunschliste mit niederer Priorität.
Das "Dynamic logical modules" könnte dann auch evtl da rein

**Comment by sidey79** [comment]
Hi Ralf,

jedes Issue ist ja quasi ein Todo.
Du kannst deine Vorschläge erst mal einzeln erfassen. Für das Release kann ich dann noch eines für die Übersichtlichkeit erstellen.

Mich würde vor allem interessieren, wie deine Ansätze aussehen.
Gerade das mit den Get Actions hängt meiner Meinung Nach, ja mit dem Serial Buffer zusammen.
Ich würde erwarten, man kann das Problem sehr einfach lösen, indem man auf Arduino Seite auf ein OK von der Fhem Seite wartet.

Beim Ping, könnte man auf der Fhem Seite entweder den Intervall zurücksetzen, wenn etwas empfangen wurde und dadurch nur Abfragen, wenn längere Zeit nichts vom Arduino kommt oder man lässt den Arduino periodisch etwas senden und wertet in Fhem nur noch aus, ob etwas für einen Zeitraum X empfangen wurde.

So langsam könnte man aber natürlich mal das Release 3.2 veröffentlichen. 
Ich will nur noch die Klassen aufräumen und mit aktuelleren Arduino Core kompilieren.

Grüße Sidey

**Comment by sidey79** [comment]
Wenn ich mir so ansehe, haben wir alles geschafft was wir wollten.

Die Firmware läuft stabil und die ganzen Aufgaben (bis auf dynamic logical module) sind erledigt.
Okay einer ist mir noch eingefallen

**Comment by sidey79** [comment]
Jetzt ist es aber wirklich geschafft. Haben wir noch irgendwo ein Thema?

Welche logischen Module sollen in der Version 3.2 aktiviert sein und wie machen wir es mit der Doku / dem Wiki.,

**Comment by Ralf9** [comment]
Ich sehe noch 2 Themen/Probleme:
Der nicht erkannte Windsensor von waschbaerbauch. Kannst Du ausschließen, daß da noch ein Problem in der Firmware sein könnte?
Oder hat er evtl noch Empfangsprobleme.

Bist Du mit der Itv3 weitergekommen, oder kommt dies in das Release 3,3

**Comment by sidey79** [comment]
Itv3 funktioniert bei mir.

Mit dem Windsensor ist das so eine Sache.
Ich kann nie ausschließen, dass es ein Bug ist.
Ich würde mal annehmen, dass es nicht an der Firmware liegt.

Wir können dev32 auch erst mal als 3.2.0 veröffentlichen und später noch eine 3.2.1. 
Es ist vermutlich ohnehin besser, wenn wir die Schritte kleiner wählen.

Ich würde jetzt gerne mal die Doku und alles auf einen aktuellen Stand bringen und dann Richtung Master mergen. In v3.1 sollte aus meiner Sicht nicht mehr können als 3.1.

**Comment by Ralf9** [comment]
Ich habe es mal mit einer raw-Nachricht von einem Itv3 Dimmer von @Hardlife getestet, damit funktioniert es nicht:
```
2016.02.10 20:49:45 4: sduinoD/msg get raw: MS;P0=-10773;P1=-4628;P2=350;P3=-1039;P4=1045;P5=-346;D=21023454523232345232345232345454523454523234523234520234545232323452323452323454545234545232345232345202345452323234523234523234545452345452323452323452023454523232345232345232345454523454520;CP=2;SP=1;O;
2016.02.10 20:49:45 4: sduinoD: Matched MS Protocol id 3 -> itv1
2016.02.10 20:49:45 5: sduinoD: Starting demodulation at Position 53
2016.02.10 20:49:45 4: sduinoD: Decoded MS Protocol id 3 dmsg i0C49D92C49D92C49D8 length 72
2016.02.10 20:49:45 5: sduinoD: converted Data to (i0C49D92C49D92C49D8)
2016.02.10 20:49:45 5: sduinoD dispatch i0C49D92C49D92C49D8
2016.02.10 20:49:45 2: DDD0D10010D1D0D10010D1D0D101D not defined (Address: DDD0D10010D1D0D10010D1D0D1 Group: 0 Unit: 1D Switch code: 0)
```

**Comment by sidey79** [comment]
Das ist ein ITv1 Protokoll was da übertragen wurde.
Kann es sein, dass der Dimmer sowohl ITv1 und ITv3 überträgt? Ich habe es mit einem ITLS-16 getestet.

**Comment by Ralf9** [comment]
@Hardlife hat ein Itv3 Dimmer
http://www.amazon.de/Intertechno-Funksteckdose--300L-Funk-Zwischenstecker-Dimmer/dp/B00556KXZ6/ref=sr_1_1?ie=UTF8&qid=1452426878&sr=8-1&keywords=IT-300L

Die raw-Nachricht habe ich aus einem log von @Hardlife. In der 10_IT.pm wird sie als Itv3dimm erkannt.

**Comment by sidey79** [comment]
Das Set habe ich hier auch. Sender:ITLS-16, Empfänger ITLR-300.

Der Sender sendet auf jeden Fall auch ein ITv3 Signal, das kann man auch entsprechend auswerten.

**Comment by Ralf9** [comment]
Ja, damit passt es. Vielleicht hatte @Hardlife keinen guten Empfang.

**Comment by sidey79** [comment]
Naja, das Signal was zur Diskussion steht wurde nach ITv1 Schema moduliert.

Ich weiss jetzt nicht, woher das gesendet wurde. Bei den Steckdosen (Empfängern) ist es so, dass sie ITv1 (PT2262) und (Arctec) ITv3 Modulierung verstehen.

Ich könnte jetzt annehmen, dass ein Sender das ITv3 Protokoll nicht via Arctec moduliert hat , sondern halt als ITv1 (PT2262).

Da das IT Modul an dem Punkt etwas seltsam ist, kann es sein, dass ein CUL, der die Modulation pt2262 oder Arctec, nicht unterscheidet die Daten immer gleich übergibt, egal nach welchem Modus moduliert wurde.

Jetzt wäre ja nur die Frage, muss der Signalduino das itv3 Protokoll verstehen, wenn es mittels pt2262 moduliert wurde.

Ich möchte hier noch anmerken, dass ich gerade mit einigen Annahmen arbeite, was diesen Post angeht.

@Hardlife: Was hat dieses Signal gesendet?

**Comment by Ralf9** [comment]
> Jetzt wäre ja nur die Frage, muss der Signalduino das itv3 Protokoll verstehen, wenn es mittels pt2262 moduliert wurde.

müssen nicht, aber es wäre schön, wenn der Signalduino den itv3 dimmer Sender von @Hardlife verstehen würde.

Ich denke, daß @Hardlife wahrscheinlich hier nicht mitliest.

**Comment by Ralf9** [comment]
Hier sind noch ein paar raw-Nachrichten von @Hardlife die nach ITv1 Schema moduliert wurden:
```
MS;P0=349;P1=-1040;P2=1045;P3=-346;P4=-10771;D=04012323010101230101230101232323012323010123010123;CP=0;SP=4;O;
MS;P0=-1045;P1=1042;P2=-351;P3=347;P4=-10780;D=34301212303030123030123030121212301212303012303012;CP=3;SP=4;O;
MS;P0=335;P1=-1056;P2=1033;P3=-358;P4=-10784;D=04012323010101230101230101232323012323010123010123;CP=0;SP=4;O;
```

**Comment by sidey79** [comment]
Also ich sehe hier gerade den Anwendungsfall nicht.

Mir ist nicht klar, was da sendet? Ein ITv1 Sender der ein Dimmer ist?
Ich würde sagen, das Thema gehen wir wieder an, sofern mehr Informationen vorliegen
