### ISSUE TITLE
Protokoll für TFA 30320902 (TFA MULTY Funk-Wetterstation)

### ISSUE THREAD

**Issue by michiatlnx** [RFD-FHEM/RFFHEM#42]
nano328 with Super-heterodyne OOK Wireless Receiver Module Strong Interference 433MHZ-116dBm

2015.11.06 16:01:06 4: SIGNALduino/msg READ: MS;P1=474;P2=-1959;P3=-982;P4=-3930;D=14121313131212121212131213131313131212131212131212121212121313121212121312;CP=1;SP=4;O;
2015.11.06 16:01:06 4: Found matched Protocol id 7 -> weatherID7
2015.11.06 16:01:06 4: SD_WS07_Parse  SD_WS07 (P7#8FA0DBF3D) length: 9
2015.11.06 16:01:06 3: SD_WS07 converted to bits: 10001111 1 010 000011011011 1111 00111101
2015.11.06 16:01:06 3: SD_WS07_TH decoded protocolid: 7 sensor id=8F, channel=3, temp=21.9, hum=61, bat=ok
2015.11.06 16:01:06 1: SD_WS07: UNDEFINED sensor SD_WS07_TH detected, code SD_WS07_TH_3
2015.11.06 16:01:06 4: SIGNALduino_unknown incomming msg: P7#8FA0DBF3D
2015.11.06 16:01:06 4: SIGNALduino_unknown rawData: 8FA0DBF3D
2015.11.06 16:01:06 4: SIGNALduino_unknown Protocol: 7
2015.11.06 16:01:06 4: SIGNALduino_unknown converted to bits: 100011111010000011011011111100111101
2015.11.06 16:01:06 4: SIGNALduino_unknown decoded protocolid: 7 (TX70DTH) sensor id=8F, channel=2, temp=21.9, hum=61, bat=ok

2015.11.06 16:01:06 4: SIGNALduino_unknown decoded protocolid: 7 (EAS800z / type=8) mode=auto, sensor id=15, channel=3, temp=21.9, hum=61, bat=ok

2015.11.06 16:01:06 4: SIGNALduino/msg READ: MU;P0=496;P1=-18;P2=-963;P3=-3898;D=010201020202020201010201010201010101010102020101010102010301020202010101010102010202020202010102010102010101010101020201010101020103010202020101010101020102020202020101020101020101010101010202010101010201030102020201010101010201020202020201;CP=0;O;
2015.11.06 16:01:06 4: Fingerprint for Protocol id 16 -> Dooya shutter matches, trying to demodulate
2015.11.06 16:01:06 4: Fingerprint for Protocol id 27 -> remote27 matches, trying to demodulate
2015.11.06 16:01:06 4: Fingerprint for Protocol id 28 -> IC Ledspot matches, trying to demodulate
2015.11.06 16:01:06 4: Fingerprint for Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2015.11.06 16:01:06 4: SIGNALduino/msg READ: MS;P0=-1955;P1=484;P2=-970;P3=-3888;D=13101212121010101010121012121212121010121010121010101010101212101010101210;CP=1;SP=3;O;
2015.11.06 16:01:06 4: Found matched Protocol id 1 -> ConradRSL
2015.11.06 16:01:06 3: sduino: Unknown code r0, help me!
2015.11.06 16:01:06 4: Found matched Protocol id 7 -> weatherID7
2015.11.06 16:01:06 4: SD_WS07_Parse  SD_WS07 (P7#8FA0DBF3D) length: 9
2015.11.06 16:01:06 3: SD_WS07 converted to bits: 10001111 1 010 000011011011 1111 00111101
2015.11.06 16:01:06 3: SD_WS07_TH decoded protocolid: 7 sensor id=8F, channel=3, temp=21.9, hum=61, bat=ok
2015.11.06 16:01:06 1: SD_WS07: UNDEFINED sensor SD_WS07_TH detected, code SD_WS07_TH_3
2015.11.06 16:01:06 4: SIGNALduino_unknown incomming msg: P7#8FA0DBF3D
2015.11.06 16:01:06 4: SIGNALduino_unknown rawData: 8FA0DBF3D
2015.11.06 16:01:06 4: SIGNALduino_unknown Protocol: 7
2015.11.06 16:01:06 4: SIGNALduino_unknown converted to bits: 100011111010000011011011111100111101
2015.11.06 16:01:06 4: SIGNALduino_unknown decoded protocolid: 7 (TX70DTH) sensor id=8F, channel=2, temp=21.9, hum=61, bat=ok

2015.11.06 16:01:06 4: SIGNALduino_unknown decoded protocolid: 7 (EAS800z / type=8) mode=auto, sensor id=15, channel=3, temp=21.9, hum=61, bat=ok

2015.11.06 16:01:06 4: SIGNALduino/msg READ: MU;P0=498;P1=573;P2=-968;P3=-3900;P5=264;D=0101010202010101010201030102020201010101010201020202020201010201010201010101010102020101010102010301020202010101010102010202020202010102010102010101010101020201010101020151;CP=0;
2015.11.06 16:01:06 4: Fingerprint for Protocol id 16 -> Dooya shutter matches, trying to demodulate
2015.11.06 16:01:06 4: Fingerprint for Protocol id 27 -> remote27 matches, trying to demodulate
2015.11.06 16:01:06 4: Fingerprint for Protocol id 28 -> IC Ledspot matches, trying to demodulate
2015.11.06 16:01:06 4: Fingerprint for Protocol id 8 -> TX3 Protocol matches, trying to demodulate

**Comment by michiatlnx** [comment]
Es hat nur länger gebraucht damit es im FHEM erkannt wird.
Es wird jetzt als TYPE SD_WS07 erkannt.
Issue kann geschlossen werden.

**Comment by sidey79** [comment]
Danke für die Info dass der TFA 30320902 auch funktioniert.

Wenn die Sensordaten nicht stimmen sollte, einfach noch mal das Issue öffnen.
