### ISSUE TITLE
Chilitec Großhandel 22640 - LED Christbaumkerzen mit Fernbedienung

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#421]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: Chilltec
  - model name: 22640 
  - pictures of the device / the board (very helpful)
 

Device has on off + - SL FL 

## Specifications 

  - Microcontroller: 
  - Version (Firmware): V 3.3.1-RC10 SIGNALduino - compiled at Nov 19 2018 23:11:10
  

  - Versionmodul (FHEM Module):
  

Jede Taste wird als Protokoll 41 mit einem eigenen code erkannt.

Details:
https://forum.fhem.de/index.php?topic=94211.new;topicseen#new

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/RFD-FHEM/RFFHEM/issues/133 (AK-HD-4 GaragenTor Fernbedienung).

**Comment by sidey79** [comment]
@HomeAutoUser 

Protokoll 41 passt hier mittlerweile nicht mehr, da der Sync eher Faktor 10 ist.

**Comment by HomeAutoUser** [comment]
Ich habe es vernommen.
Beim Test bei mir schlug auch die MSG fehl welche beim User klappte.
Nehme mich der Sache an.

**Comment by sidey79** [comment]
Danke :)

**Comment by HomeAutoUser** [comment]
Hat jemand eine Idee wieso die Nachricht nicht greift?

```
	"14"	=>	## LED X-MAS Chilitec model 22640
			# https://github.com/RFD-FHEM/RFFHEM/issues/421 | https://forum.fhem.de/index.php/topic,94211.msg869214.html#msg869214
			# MS;P0=988;P1=-384;P2=346;P3=-1026;P4=-4923;D=240123012301230123012323232323232301232323;CP=2;SP=4;R=0;O;m=1;
			# MS;P0=-398;P1=974;P3=338;P4=-1034;P6=-4939;D=361034103410341034103434343434343410103434;CP=3;SP=6;R=0;
		{
			name			=> 'LED X-MAS',
			comment			=> 'Chilitec model 22640',
			id			=> '14',
			one			=> [2,-2],
			zero			=> [2,-5],
			sync			=> [2,-25],
			clockabs		=> 200,
			format			=> 'twostate',
			preamble		=> 'u14#',				# prepend to converted message
			#clientmodule		=> '',
			#modulematch		=> '^u14#.*',
			length_min		=> '4',
			length_max		=> '40',
		},
```

Keine Black oder andere Listenatrribute sind gesetzt.

**Comment by elektron-bbs** [comment]
sync müsste passen, aber die Welleform ist:
"01" entspricht 1000,-400 - [5,-2]
"23" entspricht 400,-1000 - [2,-5]

**Comment by elektron-bbs** [comment]
Da fällt mir gerade eine Frage ein, die ich schon immer mal stellen wollte: Ich glaube, mich zu erinnern, das du mal irgendwo geschrieben hast, das möglichst keine Faktoren mit Kommastellen verwendet werden sollen. Erinnere ich mich da richtig und wenn ja, warum?

**Comment by sidey79** [comment]
Naja, ich nehme an jemand verbaut einen Taktgeber in dem Sender.

Und das Signal wird über diesen Takt moduliert. Da wird vermutlich niemand mit halben Takten irgendwas machen, daher nehme ich an, es gibt nur ganze Faktoren und keine halben/drittelt. Das sieht für uns auf der Empfangsseite halt nur so aus, weil es Toleranzen in der Hardware sowohl auf Sendeseite und Empfangsseite gibt.

Da aber alles denkbar ist und so mancher Entwickler scheinbar Spaß daran hat sich ein ganz besonderes Modulations verfahren auszudenken kann auch mit Kommastellen in den Faktoren gearbeitet werden. Sollte in der Regel aber nicht notwendig sein, da der Toleranzfaktor die Toleranzen der Hardware abdecken soll.

**Comment by HomeAutoUser** [comment]
>Clockpulse vom MS Signal ist 350. Der von Protokoll 14 ist halt 200. Mit Toleranzfakto
r von 0,3 dürfte hier nur bis 260 passen.

wie kamst du gezielt zu der Aussage das vom MS 350 ist?
Lag ich mit meiner Rechnung falsch oder hast du den CP genommen welcher ausgegeben wurde?

```
2018.12.10 21:39:03 4: sduino_dummy: Matched MS Protocol id 14 -> LED X-MAS
2018.12.10 21:39:03 4: sduino_dummy: Decoded MS Protocol id 14 dmsg u14#AA808 length 20 RSSI = -74
2018.12.10 21:39:04 4: SIGNALduino_unknown incomming msg: u14#AA808
2018.12.10 21:39:04 4: SIGNALduino_unknown rawData: AA808
2018.12.10 21:39:04 4: SIGNALduino_unknown Protocol: 14
2018.12.10 21:39:04 4: SIGNALduino_unknown converted to bits: 10101010100000001000
```

**Comment by sidey79** [comment]
Ich habe den Wert von CP genommen. Das kommt ja vom Prinzip auch gut hin oder?

**Comment by HomeAutoUser** [comment]
Bisher passt es und ich werde demnäcsht dann mal versuchen an die Tasten zu kommen :-)

**Comment by HomeAutoUser** [comment]
Das Model ist eingearbeitet im SD_UT Modul und auch das senden klappte.
Da seit Dezember keine negativen Rückmeldungen kam, schließe ich den Faden.

Bei Anregungen / Wünschen oder Fehlern bitte erneut melden und einen PR erstellen.

**Comment by Ralf9** [comment]
Ich wollte gerade die ID 14 LED X-MAS mit dem dem dummysduino testen, aber mir gelingt es nicht, daß das "unknown_please_select_model SD_UT" per autocreate angelegt wird.
Bei der ID 46 hat das autocreate geklappt.
Gibt es da bei der ID 14 was zu beachten, daß es per autocreate angelegt wird?

```
2019.03.25 23:02:07.537 4 : sduinoD/msg get raw: MS;P0=988;P1=-384;P2=346;P3=-1026;P4=-4923;D=240123012301230123012323232323232301232323;CP=2;SP=4;R=0;O;m=1;
2019.03.25 23:02:07.537 4 : sduinoD: Matched MS Protocol id 14 -> LED X-MAS, bitLen=20
2019.03.25 23:02:07.537 5 : sduinoD: Starting demodulation at Position 2
2019.03.25 23:02:07.537 4 : sduinoD: Decoded MS Protocol id 14 dmsg P14#AA808 length 20 RSSI = -74
2019.03.25 23:02:07.538 5 : sduinoD: dispatch P14#AA808
2019.03.25 23:02:07.538 4 : sduinoD: SD_UT protocol 14, bitData 10101010100000001000, hlen 5
2019.03.25 23:02:07.538 1 : sduinoD: SD_UT_Parse UNDEFINED sensor unknown detected, protocol 14, data AA808, code AA80
2019-03-25 23:02:07.543 Global global UNDEFINED unknown_please_select_model SD_UT unknown
```

```

2019.03.25 23:14:38.598 4 : sduinoD: SD_UT protocol 46, bitData 11101100111100100000, hlen 5
2019.03.25 23:14:38.598 1 : sduinoD: SD_UT_Parse UNDEFINED sensor unknown detected, protocol 46, data ECF20, code ECF20
2019.03.25 23:14:38.599 2 : autocreate: define unknown_please_select_model SD_UT unknown
2019.03.25 23:14:38.600 2 : autocreate: define FileLog_unknown_please_select_model FileLog ./log/unknown_please_select_model-%Y-%m.log unknown_please_select_model
2019.03.25 23:14:38.601 3 : SD_UT_Attr set model to unknown
```

**Comment by HomeAutoUser** [comment]
Mit dieser RAWMSG (ID 14)
`MS;P0=988;P1=-384;P2=346;P3=-1026;P4=-4923;D=240123012301230123012323232323232301232323;CP=2;SP=4;R=0;O;m=1;`

habe ich es soeben getestet. Device gelöscht und wieder neu anlegen lassen.
Man muss ca. 5 - 6 mal parsen, weil der Autocreatefaktor sehr hoch ist.

**Comment by Ralf9** [comment]
> Man muss ca. 5 - 6 mal parsen, weil der Autocreatefaktor sehr hoch ist.

ok, damit funktioniert es.

Ist dies irgendwo dokumentiert, daß man so oft drücken muß, viele geben wahrscheinlich vorher auf,

**Comment by HomeAutoUser** [comment]
So genau ist es nicht erfasst in der Doku.
Der Auszug aus dem Code `autocreateThreshold => "5:180", GPLOT => ""},`

Das ganze ist auf diesem Wert basierend, weil alles darunter nur Devices anlegt von Empfangsfehlern und willkürlich fremde Geräte erfasst.

Dennoch gibt es Devices wo es auch mit weniger und mehr Widerholungen schneller anlegt.

Einen hinweis kann man gern schaffen in der Commandref aber das genau zu spezifizieren ist nicht machbar aufgrund der verschiedenen repeats.
