### ISSUE TITLE
DummyDevice - too many useless commands

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#423]
## Expected Behavior
- nicht funktionierende Befehle auf dem DummyDevice ausblenden

## Actual Behavior
- get Befehle wie availableFirmware / ccconf / ccpatabke / ccreg / cmds / freeram / raw
- set Befehle wie raw / flash / sendMSG
--> können nicht ausgeführt werden weil diese ein Dummy nicht umsetzen kann

## Steps to Reproduce the Problem

  1. get list ansehen und Befehl ausführen
  2. set list  ansehen und Befehl ausführen
  3.

## Specifications

  - Microcontroller: Dummy
  - Version (Firmware): gibt es nur virtuell

  - Versionmodul (FHEM Module): v3.3.3-dev_09.12.

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

**Comment by HomeAutoUser** [comment]
@sidey79 du hast das Thema angepinnt.
Möchtest du dies als nächstes angehen?

**Comment by sidey79** [comment]
Können wir auch demnächst angehen. Erst mal würde ich aber gerne die Anpassung der Log3 Funktion durchgehen

**Comment by sidey79** [comment]
Es geht nur um das ausblenden im dropdown nicht darum, dass die Befehle nicht akzeptiert werden. Habe ich das soweit richtig verstanden?

**Comment by HomeAutoUser** [comment]
ob wir die Befehle nur ausblenden oder komplett bei einem Dummy "verbieten" müsste man erörtern.

Es ging mir darum, Befehle die man nicht mit einem Dummy ausführen kann, nicht in der Setlist zu haben. Somit würde ich sie auch nicht manuell eingeben wollen bzw. akzeptieren.
Es bringt ja nichts, wenn wir die Befehle nur ausblenden und wenn man diese manuell erzwingt via Kommandozeile, das dann dort unplausible Antworten herauskommen ;-)

**Comment by elektron-bbs** [comment]
Ich habe jetzt z.B. bei einen Dummy "set sduino_dummy close" ausgeführt. Der hat jetzt STATE disconnected - keine Ahnung, was das da für Auswirkungen hat.

**Comment by sidey79** [comment]
Das Ausblenden wäre ein "einfacher" Eingriff.

Wenn wir die Befehle für den Dummy verbieten, dann können wir die mit dem Dummy nicht mehr testen.
Um dann die Tests wieder lauffähig zu bekommen, müssten wir die serielle Schnittstelle emulieren.
Machbar kostet aber Zeit.

Der Dummy wird ja vermutlich eh nur fürs Testen verwendet, ein "ungünstiger" Zustand ist vielleicht nicht so tragisch.

**Comment by HomeAutoUser** [comment]
Der Befehl close ist ja noch harmlos denke ich dabei.

Was wäre mit disableMessagetype  ? Das sollte doch da absolut nichts bezwecken können ?
```
2019.11.11 21:44:34 4: set sduino_dummy disableMessagetype syncedMS CDS
2019.11.11 21:44:34 4: sduino_dummy/HandleWriteQueue: nothing to send, stopping timer
```

**Comment by elektron-bbs** [comment]
Der Befehl ginge ja eigentlich zum SIGNALduino - da es den aber beim Dummy nicht gibt, sollte er gar nichts bewirken (außer evtl. einer Fehlermeldung).

**Comment by HomeAutoUser** [comment]
>Der Befehl ginge ja eigentlich zum SIGNALduino - da es den aber beim Dummy nicht gibt, sollte er gar nichts bewirken (außer evtl. einer Fehlermeldung).

Das ist genau erstmal der GRundsatz den wir klären sollten.

?) was ist mit Befehlen welche überhaupt nicht beim Dummy gehen?
a) ausblenden
b) ebenso via manuellen Kommando verbieten

**Comment by sidey79** [comment]
Das mit der Klingel ist gut. Allerdings gibt es Klingel die blinken.

Ausblenden wäre auf jeden Fall weniger Aufwand und vermutlich würde es 95% Abdecken. Aber das ist eh nur eine Annahme :)

Ich könnte das dann mal vorschlagen, was beim Dummy ausgeblendet wird.

**Comment by HomeAutoUser** [comment]
Dann schlag mal vor, was du ausblenden möchtest oder vielleicht ist es einfacher zu schreiben was man sehen darf ;)

**Comment by sidey79** [comment]
Ich beziehe mich erst einmal nur auf get Befehle:

get raw
get AvailableFirmware

Würde ich noch anzeigen :)

**Comment by elektron-bbs** [comment]
Welche Firmware würdest du denn für den Dummy bereitstellen :-)

**Comment by sidey79** [comment]
Je nachdem, was im Attribut hardware hinterlegt ist, wird bereitgestellt, welche Versionen heruntergeladen werden können.
Wir könnten die Bedingung mit dem Hardware Attribut noch einbauen. Ohne wird nichts abgerufen.

**Comment by elektron-bbs** [comment]
Wozu sollte ich ein Attribut hardware setzen, wenn keine Hardware angeschlossen ist?

**Comment by sidey79** [comment]
Um die Liste der Firmware Versionen sichten zu können.


Wozu es jemand braucht weiss ich nicht, aber es funktioniert.




Holen Sie sich Outlook für Android







On Wed, Nov 13, 2019 at 9:37 PM +0100, "Udo" <notifications@github.com> wrote:












Wozu sollte ich ein Attribut hardware setzen, wenn keine Hardware angeschlossen ist?

**Comment by HomeAutoUser** [comment]
Da könnte man ja bald mal die

Fiter dummy set commands

angehen @sidey79 ;-)

**Comment by sidey79** [comment]
Ja, ich schiebe es immer auf.
Wird ne größere Aktion. Daher würde ich erst Mal 3.4.1 in den Master packen und das in 3.4.2 angehen.

Spricht da was gegen die 3.4.1 fertig zu machen?

**Comment by HomeAutoUser** [comment]
>Ja, ich schiebe es immer auf.
Wird ne größere Aktion. Daher würde ich erst Mal 3.4.1 in den Master packen und das in 3.4.2 angehen.

Das ist eine Aussage und meinerseits auch ein guter Schritt.

>Spricht da was gegen die 3.4.1 fertig zu machen?

Von mir aus, nein.

**Comment by HomeAutoUser** [comment]
@sidey79 
wie denkst du hier über den weiteren Weg? Wir haben ja erst nur die Hälfte durch.

**Comment by sidey79** [comment]
Ich habe nicht nur nachgedacht, ich habe sogar bereits etwas umgesetzt:

https://github.com/RFD-FHEM/RFFHEM/commit/a87747243c91e7de6d05b287419e88391c5f5ea0

**Comment by HomeAutoUser** [comment]
Das sollte mit dem https://github.com/RFD-FHEM/RFFHEM/pull/745 erledigt sein :)
