### ISSUE TITLE
Westinghouse Ventilator rf Modul 433.9

### ISSUE THREAD

**Issue by mveltrup** [RFD-FHEM/RFFHEM#43]
http://www.amazon.de/Universal-Funk-Fernbedienung-f%C3%BCr-Deckenventilator/dp/B0028YFKJC

Dachte mir, hey der hat 433mhz warum nicht, besser als die ir fernbedienung.
Ja nur wird der nicht angezeigt.

**Comment by sidey79** [comment]
Was für Log Meldungen kommen in Thema . Verbose4 wenn Du eine Taste drückst?

**Comment by sidey79** [comment]
Da hier nichts mehr passiert ist, schließe ich das Thema
