### ISSUE TITLE
Krinner 433 Mhz Model

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#452]
##  Specifications for new sensor / switch / or other device ... 
https://forum.fhem.de/index.php?topic=94873.new#new

  - manufacturer: Krinner
  - model name: 572152
  - pictures of the device / the board (very helpful) 
http://www.produktinfo.conrad.com/datenblaetter/550000-574999/572152-an-01-de-BASIS_SET_10_CHRISTBAUMKERZEN_IN_WEISS.pdf
  
## Specifications 

  - Microcontroller:  nano with cc1101
  - Version (Firmware):  3.3.1 RC10
  

  - Versionmodul (FHEM Module): v3.3.3-dev_17.12.
  

Signal has a stat sequence and clock ~400
Start is 1,-24
one is -2,1
zero is 1,-2

32 Bits

```
MU;P0=24188;P1=-16308;P2=993;P3=-402;P4=416;P5=-967;P6=-10162;D=0123234545454523234523234545454545454545232
623452345454545454523234523234545454523234523234545454545454545232
623452345454545454523234523234545454523234523234545454545454545232
623452345454545454523234523234545454523234523234545454545454545232;CP=4;R=25;
```

There are similar Signal fingerprints already available, but all with incompatible length and slight different clock (30,86)

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/43 (Westinghouse Ventilator rf Modul 433.9), and https://github.com/RFD-FHEM/RFFHEM/issues/124 (CC1101 868.3 MHZ FSK Sensoren empfangen).

**Comment by HomeAutoUser** [comment]
@sidey79 
ich denke so

```
MU;P0=24188;P1=-16308;P2=993;P3=-402;P4=416;P5=-967;P6=-10162;
D=012
323454545452323452323454545454545454523
26 
2345234545454545452323452323454545452323452323454545454545454523
26
2345234545454545452323452323454545452323452323454545454545454523
26
2345234545454545452323452323454545452323452323454545454545454523
2;CP=4;R=25;

start  26 P2=993;P6=-10162;
zero  23 P2=993;P3=-402; | 2, -1
one   45 P4=416;P5=-967; | 1, -2
```

ist das amtlich zum einbauen ?

**Comment by HomeAutoUser** [comment]
Quelle: https://forum.fhem.de/index.php/topic,94873.msg876477.html?PHPSESSID=khp4ja64pcqa5gsf6gb63l1es5#msg876477

```
	"92"	=>	## Krinner Lumix - LED X-MAS
						# https://github.com/RFD-FHEM/RFFHEM/issues/452 | https://forum.fhem.de/index.php/topic,94873.msg876477.html?PHPSESSID=khp4ja64pcqa5gsf6gb63l1es5#msg876477
						# MU;P0=24188;P1=-16308;P2=993;P3=-402;P4=416;P5=-967;P6=-10162;D=0123234545454523234523234545454545454545232623452345454545454523234523234545454523234523234545454545454545232623452345454545454523234523234545454523234523234545454545454545232623452345454545454523234523234545454523234523234545454545454545232;CP=4;R=25;
						# MU;P0=11076;P1=-20524;P2=281;P3=-980;P4=982;P5=-411;P6=408;P7=-10156;D=0123232345456345456363636363636363634745634563636363636345456345456363636345456345456363636363636363634745634563636363636345456345456363636345456345456363636363636363634745634563636363636345456345456363636345456345456363636363636363634;CP=6;R=38;
		{
			name					=> 'Krinner Lumix',
			comment				=> 'LED X-MAS model 572152',
			id						=> '92',
			knownFreqs		=> '',
			zero					=> [1,-2],
			one						=> [2,-1],
			start					=> [2,-24],
			clockabs			=> 420,
			format				=> 'twostate',	#
			preamble			=> 'u92#',			# prepend to converted message
			length_min		=> '32',
			length_max		=> '32',
			#clientmodule	=> 'SD_UT',
			#modulematch	=> '^P92#.*',
			developId     => 'y',
		},
```

**Comment by sidey79** [comment]
Ich denke so wie es @HomeAutoUser vorgeschlagen hat passt es:

```
start  26 P2=993;P6=-10162; | 2, -25
one    23 P2=993;P3=-402; | 2, -1
zero   45 P4=416;P5=-967; | 1, -2
```
Die Firmware dahingehend zu modifizieren, dass man es als MS Signal erkennen würde ist keine kurzfristige Aktion. Die ID19 passte bei beim Test des Anwenders nur 1x. Darauf können wir nicht bauen.

> developId => 'y',

Hier wäre doch eher p angebracht solange es noch nicht verifiziert wurde oder?

**Comment by HomeAutoUser** [comment]
>Hier wäre doch eher p angebracht solange es noch nicht verifiziert wurde oder?

Was sollte man verifizieren? Ich arbeite es ins modul ein und würde Y belassen. Wenn der User sagt, JA klappt, Y entfernen.

**Comment by sidey79** [comment]
> > Hier wäre doch eher p angebracht solange es noch nicht verifiziert wurde oder?
> 
> Was sollte man verifizieren? Ich arbeite es ins modul ein und würde Y belassen. Wenn der User sagt, JA klappt, Y entfernen.

Demnach brauchen wir p dann eigentlich auch nicht oder, denn m wäre ja noch ein Zwischending zwischen y und p, solange das SD_UT Modul es nicht verstehen würde.

Im Endeffekt ist es auch egal. Man könnte es auch ohne developID einbauen und den User direkt aus dem Feature Branch testen lassen.

**Comment by HomeAutoUser** [comment]
>Demnach brauchen wir p dann eigentlich auch nicht oder, denn m wäre ja noch ein Zwischending zwischen y und p, solange das SD_UT Modul es nicht verstehen würde.

Ich benötige nur y, egal was da nicht passt. Modul oder Definition, ich habe es als y immer. Ob p oder m, das ist nur ein HINWEIS für uns entwickler.

>Im Endeffekt ist es auch egal. Man könnte es auch ohne developID einbauen und den User direkt aus dem Feature Branch testen lassen.

Solange keine Rückmeldung erfolgte ist das mit dem y schon gut so. So stellen wir sicher, das nur was gegengeprüft ist im Branch als InOrdnung markiert ist sobald developID entfernt ist.

**Comment by elektron-bbs** [comment]
Das scheint doch auch erledigt zu sein?

**Comment by HomeAutoUser** [comment]
Jo
