### ISSUE TITLE
Protocol ID82 can't be enabled via  Display protocollist

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#462]
## Expected Behavior

It should be possible to enable the protocol via  Display protocollist

## Actual Behavior

Protocol 82 is displayed as active:

![image](https://user-images.githubusercontent.com/7968127/50540861-0a77c000-0b9a-11e9-92b2-6f2c66d4549f.png)

Logfile reports, that this protocol is not enabled now:

`ID=82 skipped dispatch (developId=m). To use, please add 82 to the attr whitelist_IDs
`2
## Steps to Reproduce the Problem

  1. delattr Whitelist_IDs
  2. delattr development
  3. get raw 
`MU;P0=-32001;P1=435;P2=-379;P4=-3201;P5=831;P6=-778;D=01212121212121214525252525252521652161452525252525252161652141652521652521652521614165252165252165216521416521616165216525216141652161616521652165214165252161616521652161416525216161652161652141616525252165252521614161652525216525216521452165252525252525;CP=1;
`

It is possible to activate via following steps:
  1. delattr Whitelist_IDs
  2. delattr development
  3. disable Protocol 82 in menu "Protocollist overview". This will write a WhitelistIDs Attribute
  4. enable protocol 82 in menu "Protocollist overview". This will update id82 in whitelistIDs Attribute

## Specifications

  - Versionmodul (FHEM Module):  v3.3.3-dev_19.12.  which should be 29.12
--

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/26 (protocol #9), https://github.com/RFD-FHEM/RFFHEM/issues/144 (revolt protocol), https://github.com/RFD-FHEM/RFFHEM/issues/29 (Livolo Protocol), https://github.com/RFD-FHEM/RFFHEM/issues/52 (OSV3 protocol), and https://github.com/RFD-FHEM/RFFHEM/issues/36 (Wrong protocol detection).

**Comment by sidey79** [comment]
Durch #444 verursacht.

**Comment by Ralf9** [comment]
Kann sein, daß mit der jetzigen alten Version der Display protocollist noch nicht alles passt.
In der zukünftigen neuen Version ist dieser Fall berücksichtigt.
