### ISSUE TITLE
Message so not possible, following 2 negative pulses

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#465]
## Expected Behavior
- message so not possible
- negative than negative does not work

## Actual Behavior
- message is issued with 2 negative in a row
`2018.12.29 00:01:45 4: sduino_433/msg READredu: MU;P0=495;P1=-961;P2=-1955;P3=-3907;P4=136;P5=-32001;P6=360;P7=-428;D=03010201010201010102010102010101010101020102010102020202020102010202010201455670;CP=0;R=14;`

## Steps to Reproduce the Problem

  1. reception with current DEV in the strong transmitter jungle
  2.
  3.

## Specifications

  - Microcontroller: Arduino Nano
  - Version (Firmware): V 3.3.1-RC10 SIGNALduino cc1101 - compiled at 09 November 2018 01:43:10

  - Versionmodul (FHEM Module): v3.3.3-dev_19.12.

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/321 (Equal messages i not dispatched if it is equal and only 2 seconds are between.), https://github.com/RFD-FHEM/RFFHEM/issues/41 (Release 3.2), https://github.com/RFD-FHEM/RFFHEM/issues/103 (Release 3.3.2), and https://github.com/RFD-FHEM/RFFHEM/issues/111 (MU Message - repeats are not demodulated correctly).

**Comment by HomeAutoUser** [comment]
flasche Rubrik https://github.com/RFD-FHEM/SIGNALDuino/issues/105
