### ISSUE TITLE
Erweiterung für 2. Conrad RSL Modul

### ISSUE THREAD

**Issue by litronics** [RFD-FHEM/RFFHEM#470]
Ich habe das aktuelle RSL Modul so angepasst, dass es mit den Conrad RSL Schaltern funktioniert und als eigenes Modul implementiert.

Für das Modul gibt es auch schon einen Thread im Forum:
[https://forum.fhem.de/index.php/topic,78904.0.html](https://forum.fhem.de/index.php/topic,78904.0.html)

Damit das funktioniert benötige ich allerdings drei Anpassungen in dem SIGNALduino Modul.

Folgende Variablen müssten zusätzliche Einträge erhalten:

%matchListSIGNALduino -->
`"75:SD_RSL2" => "^P1RSL2#[A-Fa-f0-9]{8}",`

$clientsSIGNALduino  --> 
`."SD_RSL2:"`

%ProtocolListSIGNALduino  -->
`"75" => 
   {
      name => 'ConradRSL2', 
      id => '75',
      one => [3,-1],
      zero => [1,-3],
      clockabs => 500, 
      format => 'twostate', 
      preamble => 'P1RSL2#', 
      clientmodule => 'SD_RSL2', 
      modulematch => '^P1RSL2#[A-Fa-f0-9]{8}', 
      length_min => '32',
   }, `

**Comment by sidey79** [comment]
Wir sollten das Thema hier weiter behandeln und nicht im Forum.

Was mich sehr wundert ist, dass Du z.B. folgendes um Logfile hast:

`ERROR: >RSL_74A400_4_4< returned by the SD_RSL ParseFn is invalid, notify the module maintainer`

Bei mir sehe ich andere Logmeldungen und auch ein anderes Verhalten.

Kannst Du bitte einmal ein version SIGNALduino.pm absetzen und auch ein List auf dein signalduino device?

**Comment by HomeAutoUser** [comment]
@litronics 
ich muss nochmal anfragen :-) Kannst du bitte ein paar RAWMSG von deinen Devices hier veröffentlichen?
Die eine RAWMSG ist nicht aussagekräftig.

**Comment by litronics** [comment]
@HomeAutoUser 
Ich hab die Schalter wegen ihrer Unzuverlässigkeit mittlerweile ersetzt und hab die in der Schublade liegen. Wenn Du willst, schicke ich sie Dir, dann kannst Du der Sache noch tiefer auf den Grund gehen. Schick mir dazu einfach ein PN mit deiner Adresse.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
