### ISSUE TITLE
Protokoll für OWL USB (CM1XX) - Oregon Scientific v3(?)

### ISSUE THREAD

**Issue by dmqgit** [RFD-FHEM/RFFHEM#472]
Hi,

Referenz FHEM Forum "Signalduino Version 3.3.1 / 3.3.2 / 3.3.3-dev" [https://forum.fhem.de/index.php/topic,58397.msg880676.html#msg880676](https://forum.fhem.de/index.php/topic,58397.msg880676.html#msg880676)

Eingesetzte Komponenten: SignalESP 3.3.1 Release Candidate 4
FHEM: 5.9, 00_SIGNALduino.pm      16624 2018-04-15

READINGS:
     2018-12-20 21:57:04   ccconf          freq:433.920MHz bWidth:325KHz rAmpl:42dB sens:4dB  (DataRate:5603.79Baud)
     2018-12-19 19:23:14   ccpatable       C3E = 00 84 00 00 00 00 00 00  => 5_dBm
     2018-12-20 21:24:01   ccreg           C3E = 00 C0 00 00 00 00 00 00
     2018-12-19 19:23:21   cmds            V R t X F S P C r W x e
     2018-12-20 21:57:11   config          MS=1;MU=1;MC=1
     2018-12-07 18:06:55   freeram         36744
     2018-12-20 21:22:37   ping            OK
     2019-01-03 15:49:52   state           opened
     2018-12-19 19:23:37   uptime          0 00:04:44
     2019-01-03 15:49:52   version         V 3.3.1-rc4 SIGNALESP cc1101 868MHz - compiled at Mar 22 2018 23:45:03
   XMIT_TIME:

Anliegen:

Ich habe SignalESP in der aktuellen stable Version im Einsatz - zurzeit aufgrund IT. Damit ist alles gut. Nun würde ich gerne einen weiteren Sensor auf dieses Gateway oder einen anderen SignalESP abbilden (ich muss meine USB Anbindungen leider los werden): OWL +USB (induktiver Strommesser im Zählerkasten - siehe unten (1) und (2), 433,XX MHZ). Zurzeit habe ich die gesamte Station (Empfänger) und die Sendeeinheit im Zählerkasten im Einsatz. In meiner Recherche habe ich gefunden, dass OWL +USB auch von RFXCom bspw. RFXTRX unterstützt (3) wird und somit auch von dem "Clone" RF Link (4). 

Scheinbar wird das Oregon Scientific Protokoll verwendet - siehe (5), (6) und (7).

verbose 4 log (wiederholt sich):

```
2019.01.03 15:15:15 4: singalesp433/msg READ: MC;LL=-993;LH=961;SL=-515;SH=463;D=00AB3E90627FF5D64DC2BC;C=488;L=86;R=226;
2019.01.03 15:15:15 4: singalesp433: Found manchester Protocol id 10 clock 488 RSSI -89 -> OSV2o3
2019.01.03 15:15:15 4: singalesp433: Found manchester Protocol id 12 clock 488 RSSI -89 -> Hideki protocol
2019.01.03 15:15:15 4: singalesp433: Found manchester Protocol id 52 clock 488 RSSI -89 -> OS_PIR
2019.01.03 15:15:15 4: singalesp433: Found manchester Protocol id 58 clock 488 RSSI -89 -> tfa 30.3208.0
2019.01.03 15:15:15 4: singalesp433/msg READ: MC;LL=-993;LH=961;SL=-515;SH=463;D=FFFB89C8;C=488;L=29;R=226;
2019.01.03 15:15:15 4: singalesp433: Found manchester Protocol id 52 clock 488 RSSI -89 -> OS_PIR
2019.01.03 15:15:27 4: singalesp433/msg READ: MC;LL=-988;LH=964;SL=-496;SH=482;D=0001577D20D8FFEAD49B857FFFE2292;C=488;L=123;R=228;
2019.01.03 15:15:27 4: singalesp433: Found manchester Protocol id 10 clock 488 RSSI -88 -> OSV2o3
2019.01.03 15:15:27 4: singalesp433: Found manchester Protocol id 12 clock 488 RSSI -88 -> Hideki protocol
2019.01.03 15:15:27 4: singalesp433: receive Hideki protocol not inverted
2019.01.03 15:15:27 4: singalesp433: Hideki protocol converted to hex: 752F60F1BFADB2A1FFFF8849 with 107 bits, messagestart 17
2019.01.03 15:15:27 4: singalesp433 Hideki_Parse: incomming P12#752F60F1BFADB2A1FFFF8849
2019.01.03 15:15:27 4: singalesp433 Hideki_crc: rawdata=752F60F1BFADB2A1FFFF8849 to short, count=16 data length=12
2019.01.03 15:15:27 4: singalesp433: Found manchester Protocol id 52 clock 488 RSSI -88 -> OS_PIR
2019.01.03 15:15:27 4: singalesp433: Oregon PIR protocol detected: header_pos = 107
2019.01.03 15:15:27 4: SIGNALduino_unknown incomming msg: u52#FFFEA882DF2700152B647A80001DD6D
2019.01.03 15:15:27 4: SIGNALduino_unknown rawData: FFFEA882DF2700152B647A80001DD6D
2019.01.03 15:15:27 4: SIGNALduino_unknown Protocol: 52
2019.01.03 15:15:27 4: SIGNALduino_unknown converted to bits: 1111111111111110101010001000001011011111001001110000000000010101001010110110010001111010100000000000000000011101110101101101
2019.01.03 15:15:27 4: Unknown, please report
2019.01.03 15:15:27 3: singalesp433: Unknown code u52#FFFEA882DF2700152B647A80001DD6D, help me!
2019.01.03 15:15:27 4: singalesp433: Found manchester Protocol id 58 clock 488 RSSI -88 -> tfa 30.3208.0
2019.01.03 15:15:27 4: singalesp433: TFA 30.3208.0 preamble_pos = 17
2019.01.03 15:15:27 4: singalesp433: TFA message start=17 end=124 with length107
2019.01.03 15:15:27 4: singalesp433: 5105BE4E002A5
2019.01.03 15:15:49 4: singalesp433/keepalive ok, retry = 0
```
Danke vorab,
dmq

(1): http://www.theowl.com/index.php/energy-monitors/standalone-monitors/owl-usb/
(2): https://www.meintechblog.de/2014/01/update-smart-metering-mit-fhem-und-owl-usb/
(3): https://wiki.fhem.de/wiki/RFXtrx
(4): http://www.rflink.nl/blog2/devlist
(5): https://github.com/onlinux/OWL-CM180
(6): http://www.rfxcom.com/oregon/en
(7): http://www.letscontrolit.com/forum/viewtopic.php?t=2632

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/86 (Protokoll Oregon für THGR122N THGRN132N), https://github.com/RFD-FHEM/RFFHEM/issues/159 (Protokoll für GT2000), https://github.com/RFD-FHEM/RFFHEM/issues/369 (Oregon scientific sensor), https://github.com/RFD-FHEM/RFFHEM/issues/224 (Protokoll für Nice Rolladenaktor), and https://github.com/RFD-FHEM/RFFHEM/issues/187 (Protokoll für Ventus W266).

**Comment by sidey79** [comment]
Wir könnten ja bei RF Link nachsehen wie das Protokoll implementiert wurde.

**Comment by HomeAutoUser** [comment]
Hallo und danke @dmqgit das wir hier das Thema weiter verfolgen können.

Nachsehen bei RF Link oder anderen Quellen ist natürlich sehr hilfreich, dennoch hätte ich die Bitte, ein paar mehr RAWMSG mal zu posten. Der Zeitraum ist über fast 30Sekunden nur. Um etwas plausibles zu erstellen können, bitte mal über 3Minuten oder den "Zeitraum X" wo dieses Gerät sendet aufzeichnen.

Wenn Möglich, versuche mal den SIGNALesp auch näher an dem zu sendenden Gerät zu plazieren weil ein RSSI von über -85dB ist schon "weit weg".

LG

**Comment by dmqgit** [comment]
Anbei auf jeden Fall schonmal ein Log (verbose 4) über den Zeitraum 3 Minuten - s.u.

Spannend finde ich diesen Abschnitt:

`2019.01.03 16:59:51 4: singalesp433: OSV3 protocol detected: preamble_pos = 24, message_length = 104
2019.01.03 16:59:51 4: singalesp433: OSV3 protocol =                     2086F9B20007439CB200003661
2019.01.03 16:59:51 4: singalesp433: OSV3 protocol converted to hex: (6C2A80F6B902004793BC020030660) with length (108) bits
2019.01.03 16:59:51 4: OREGON: ERROR: Unknown sensor_id=2a80 bits=108 message='6C2A80F6B902004793BC020030660'.`

Ganzes Log:

`2019.01.03 16:58:29 4: singalesp433/msg READredu: MU;P0=141;P1=2006;P2=-6041;P3=6045;P4=-2021;P5=-93;P6=294;P7=-3385;D=12121234123434123412343412341212121215670412123412343434341210;CP=1;R=227;
2019.01.03 16:58:29 4: singalesp433: Fingerprint for MU Protocol id 13.1 -> FLAMINGO FA21 b matches, trying to demodulate
2019.01.03 16:58:29 4: singalesp433: Fingerprint for MU Protocol id 20 -> livolo matches, trying to demodulate
2019.01.03 16:58:29 4: singalesp433: Fingerprint for MU Protocol id 46 -> EKX1BE matches, trying to demodulate
2019.01.03 16:58:29 4: singalesp433: Fingerprint for MU Protocol id 5 -> unitec6899 matches, trying to demodulate
2019.01.03 16:58:29 4: singalesp433: Fingerprint for MU Protocol id 75 -> ConradRSL2 matches, trying to demodulate
2019.01.03 16:58:51 4: singalesp433/msg READ: MC;LL=-986;LH=973;SL=-490;SH=481;D=000000ABFE906ABFF59AB6C2BFFFF2962;C=488;L=131;R=11;
2019.01.03 16:58:51 4: singalesp433: Found manchester Protocol id 10 clock 488 RSSI -68.5 -> OSV2o3
2019.01.03 16:58:51 4: singalesp433: OSV3 protocol detected: preamble_pos = 24, message_length = 104
2019.01.03 16:58:51 4: singalesp433: OSV3 protocol =                     2086F9A20056A29CB20000B69B
2019.01.03 16:58:51 4: singalesp433: OSV3 protocol converted to hex: (6C2A80F6A90250A692BC0200B0960) with length (108) bits
2019.01.03 16:58:51 4: OREGON: ERROR: Unknown sensor_id=2a80 bits=108 message='6C2A80F6A90250A692BC0200B0960'.
2019.01.03 16:58:51 4: singalesp433: Found manchester Protocol id 12 clock 488 RSSI -68.5 -> Hideki protocol
2019.01.03 16:58:51 4: singalesp433: hideki start pattern (10101110) not found
2019.01.03 16:58:51 4: singalesp433: Found manchester Protocol id 52 clock 488 RSSI -68.5 -> OS_PIR
2019.01.03 16:58:51 4: singalesp433: Oregon PIR protocol detected: header_pos = 116
2019.01.03 16:58:51 4: SIGNALduino_unknown incomming msg: u52#FFFFFF54016F95400A65493D40000D69D
2019.01.03 16:58:51 4: SIGNALduino_unknown rawData: FFFFFF54016F95400A65493D40000D69D
2019.01.03 16:58:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 16:58:51 4: SIGNALduino_unknown converted to bits: 111111111111111111111111010101000000000101101111100101010100000000001010011001010100100100111101010000000000000000001101011010011101
2019.01.03 16:58:51 4: Unknown, please report
2019.01.03 16:58:51 4: SIGNALduino_unknown incomming msg: u52#FFFFFF54016F95400A65493D40000D69D
2019.01.03 16:58:51 4: SIGNALduino_unknown rawData: FFFFFF54016F95400A65493D40000D69D
2019.01.03 16:58:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 16:58:51 4: SIGNALduino_unknown converted to bits: 111111111111111111111111010101000000000101101111100101010100000000001010011001010100100100111101010000000000000000001101011010011101
2019.01.03 16:58:51 4: Unknown, please report
2019.01.03 16:58:51 3: singalesp433: Unknown code u52#FFFFFF54016F95400A65493D40000D69D, help me!
2019.01.03 16:58:51 4: singalesp433: Found manchester Protocol id 58 clock 488 RSSI -68.5 -> tfa 30.3208.0
2019.01.03 16:58:51 4: singalesp433: TFA 30.3208.0 preamble_pos = 26
2019.01.03 16:58:51 4: singalesp433: TFA message start=26 end=132 with length106
2019.01.03 16:58:51 4: singalesp433: 5005BE5500299
2019.01.03 16:58:53 4: singalesp433/keepalive ok, retry = 0
2019.01.03 16:59:39 4: singalesp433/msg READredu: MS;P1=466;P2=-5563;P3=307;P4=-508;P6=-996;P7=964;D=012343434343414141434341414141414141416767676147614141414147674167414141416147614741676141414141414141414761476741614761474161476147614741414167676141414141414141414141414141414141474167674167416741414161;CP=1;SP=2;R=15;
2019.01.03 16:59:39 4: singalesp433: Matched MS Protocol id 41 -> elro doorbell
2019.01.03 16:59:51 4: singalesp433/msg READ: MC;LL=-999;LH=952;SL=-506;SH=471;D=000000ABFE9062BFFF1D36C2BFFFF3997;C=487;L=132;R=15;
2019.01.03 16:59:51 4: singalesp433: Found manchester Protocol id 10 clock 487 RSSI -66.5 -> OSV2o3
2019.01.03 16:59:51 4: singalesp433: OSV3 protocol detected: preamble_pos = 24, message_length = 104
2019.01.03 16:59:51 4: singalesp433: OSV3 protocol =                     2086F9B20007439CB200003661
2019.01.03 16:59:51 4: singalesp433: OSV3 protocol converted to hex: (6C2A80F6B902004793BC020030660) with length (108) bits
2019.01.03 16:59:51 4: OREGON: ERROR: Unknown sensor_id=2a80 bits=108 message='6C2A80F6B902004793BC020030660'.
2019.01.03 16:59:51 4: singalesp433: Found manchester Protocol id 12 clock 487 RSSI -66.5 -> Hideki protocol
2019.01.03 16:59:51 4: singalesp433: hideki start pattern (10101110) not found
2019.01.03 16:59:51 4: singalesp433: Found manchester Protocol id 52 clock 487 RSSI -66.5 -> OS_PIR
2019.01.03 16:59:51 4: singalesp433: Oregon PIR protocol detected: header_pos = 116
2019.01.03 16:59:51 4: SIGNALduino_unknown incomming msg: u52#FFFFFF54016F9D4000E2C93D40000C668
2019.01.03 16:59:51 4: SIGNALduino_unknown rawData: FFFFFF54016F9D4000E2C93D40000C668
2019.01.03 16:59:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 16:59:51 4: SIGNALduino_unknown converted to bits: 111111111111111111111111010101000000000101101111100111010100000000000000111000101100100100111101010000000000000000001100011001101000
2019.01.03 16:59:51 4: Unknown, please report
2019.01.03 16:59:51 4: SIGNALduino_unknown incomming msg: u52#FFFFFF54016F9D4000E2C93D40000C668
2019.01.03 16:59:51 4: SIGNALduino_unknown rawData: FFFFFF54016F9D4000E2C93D40000C668
2019.01.03 16:59:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 16:59:51 4: SIGNALduino_unknown converted to bits: 111111111111111111111111010101000000000101101111100111010100000000000000111000101100100100111101010000000000000000001100011001101000
2019.01.03 16:59:51 4: Unknown, please report
2019.01.03 16:59:51 3: singalesp433: Unknown code u52#FFFFFF54016F9D4000E2C93D40000C668, help me!
2019.01.03 16:59:51 4: singalesp433: Found manchester Protocol id 58 clock 487 RSSI -66.5 -> tfa 30.3208.0
2019.01.03 16:59:51 4: singalesp433: TFA 30.3208.0 preamble_pos = 26
2019.01.03 16:59:51 4: singalesp433: TFA message start=26 end=132 with length106
2019.01.03 16:59:51 4: singalesp433: 5005BE7500038
2019.01.03 16:59:53 4: singalesp433/keepalive ok, retry = 0
2019.01.03 17:00:51 4: singalesp433/msg READ: MC;LL=-982;LH=953;SL=-510;SH=465;D=2AFFA418AFFC260DB0AFFFFC84C0;C=484;L=109;R=12;
2019.01.03 17:00:51 4: singalesp433: Found manchester Protocol id 10 clock 484 RSSI -68 -> OSV2o3
2019.01.03 17:00:51 4: singalesp433: Found manchester Protocol id 12 clock 484 RSSI -68 -> Hideki protocol
2019.01.03 17:00:51 4: singalesp433: hideki start pattern (10101110) not found
2019.01.03 17:00:51 4: singalesp433: Found manchester Protocol id 52 clock 484 RSSI -68 -> OS_PIR
2019.01.03 17:00:51 4: singalesp433: Oregon PIR protocol detected: header_pos = 94
2019.01.03 17:00:51 4: SIGNALduino_unknown incomming msg: u52#D5005BE75003D9F24F5000037B3F
2019.01.03 17:00:51 4: SIGNALduino_unknown rawData: D5005BE75003D9F24F5000037B3F
2019.01.03 17:00:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 17:00:51 4: SIGNALduino_unknown converted to bits: 1101010100000000010110111110011101010000000000111101100111110010010011110101000000000000000000110111101100111111
2019.01.03 17:00:51 4: Unknown, please report
2019.01.03 17:00:51 4: SIGNALduino_unknown incomming msg: u52#D5005BE75003D9F24F5000037B3F
2019.01.03 17:00:51 4: SIGNALduino_unknown rawData: D5005BE75003D9F24F5000037B3F
2019.01.03 17:00:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 17:00:51 4: SIGNALduino_unknown converted to bits: 1101010100000000010110111110011101010000000000111101100111110010010011110101000000000000000000110111101100111111
2019.01.03 17:00:51 4: Unknown, please report
2019.01.03 17:00:51 3: singalesp433: Unknown code u52#D5005BE75003D9F24F5000037B3F, help me!
2019.01.03 17:00:51 4: singalesp433: Found manchester Protocol id 58 clock 484 RSSI -68 -> tfa 30.3208.0
2019.01.03 17:00:53 4: singalesp433/keepalive ok, retry = 0
2019.01.03 17:01:28 4: singalesp433/msg READredu: MU;P0=-2016;P1=2007;P2=-6057;P3=6037;P4=-2868;P5=308;P6=-21943;P7=110;D=01212303030121212145430123030303012121212123036;CP=1;R=232;
2019.01.03 17:01:28 4: singalesp433/msg READredu: MU;P0=-4345;P1=2022;P2=-253;P3=141;P4=-914;P5=-6042;P6=6037;P7=-2010;D=1234151515151515151515671567671567156767151;CP=1;R=229;
2019.01.03 17:01:28 4: singalesp433: Fingerprint for MU Protocol id 20 -> livolo matches, trying to demodulate
2019.01.03 17:01:28 4: singalesp433: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2019.01.03 17:01:51 4: singalesp433/msg READ: MC;LL=-994;LH=957;SL=-501;SH=469;D=FFA41AAFFF17B5B0AFFFFDC418;C=486;L=101;R=11;
2019.01.03 17:01:51 4: singalesp433: Found manchester Protocol id 10 clock 486 RSSI -68.5 -> OSV2o3
2019.01.03 17:01:51 4: singalesp433: Found manchester Protocol id 12 clock 486 RSSI -68.5 -> Hideki protocol
2019.01.03 17:01:51 4: singalesp433: hideki start pattern (10101110) not found
2019.01.03 17:01:51 4: singalesp433: Found manchester Protocol id 52 clock 486 RSSI -68.5 -> OS_PIR
2019.01.03 17:01:51 4: singalesp433: Oregon PIR protocol detected: header_pos = 86
2019.01.03 17:01:51 4: SIGNALduino_unknown incomming msg: u52#005BE55000E84A4F5000023BE7
2019.01.03 17:01:51 4: SIGNALduino_unknown rawData: 005BE55000E84A4F5000023BE7
2019.01.03 17:01:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 17:01:51 4: SIGNALduino_unknown converted to bits: 00000000010110111110010101010000000000001110100001001010010011110101000000000000000000100011101111100111
2019.01.03 17:01:51 4: Unknown, please report
2019.01.03 17:01:51 4: SIGNALduino_unknown incomming msg: u52#005BE55000E84A4F5000023BE7
2019.01.03 17:01:51 4: SIGNALduino_unknown rawData: 005BE55000E84A4F5000023BE7
2019.01.03 17:01:51 4: SIGNALduino_unknown Protocol: 52
2019.01.03 17:01:51 4: SIGNALduino_unknown converted to bits: 00000000010110111110010101010000000000001110100001001010010011110101000000000000000000100011101111100111
2019.01.03 17:01:51 4: Unknown, please report
2019.01.03 17:01:51 3: singalesp433: Unknown code u52#005BE55000E84A4F5000023BE7, help me!
2019.01.03 17:01:51 4: singalesp433: Found manchester Protocol id 58 clock 486 RSSI -68.5 -> tfa 30.3208.0
2019.01.03 17:01:53 4: singalesp433/keepalive ok, retry = 0`

**Comment by dmqgit** [comment]
@sidey79 die Sourcen sind scheinbar nicht (in der Gesamtheit) verfügbar :( 

"The sources are due to some parts being under NDA currently not fully public."

Siehe [https://www.letscontrolit.com/forum/viewtopic.php?t=788](https://www.letscontrolit.com/forum/viewtopic.php?t=788)

**Comment by sidey79** [comment]
Ich habe in den Quellen gesucht.

OWL nutzt offensichtlich die gleiche Manchester Codierung wie Oregon V3.

Im dem Code den ich finden konnte, war der Inhalt der Daten leider nicht aufgeschlüsselt.
Das müssten wir durch Messreihen feststellen, was sich wann ändert.

**Comment by HomeAutoUser** [comment]
@dmqgit mache bitte mal ein Update von der aktuellen DEV-r33. Es besteht so die Möglichkeit das u52#... in ein Log umzuleiten was dann alles mitzeichnet wenn sich dahinter deine Daten verbergen ;-)

**Comment by dmqgit** [comment]
Gibt es irgendwo ein binary für die DEV-r33? 

Ich kenne bisher nur das hier:

https://github.com/RFD-FHEM/SIGNALESP/releases/download/3.3.1RC4/SIGNALESP_331RC4_1M.bin

Unter https://github.com/RFD-FHEM/SIGNALESP/releases/ finde ich auch keine neuere Variante...

**Comment by HomeAutoUser** [comment]
Hallo @dmqgit ,

mit `update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r33/controls_signalduino.txt`
kannst du das Modul auf den dev-r33 Stand bringen. Eine Firmware für den ESP gibt es noch keine aktuellere.

**Comment by dmqgit** [comment]
Neben dem FileLog gibt es nun folgendes device:

Internals:
   CFGFN      
   DEF        SIGNALduino_unknown_52
   IODev      signalesp433
   LASTInputDev signalesp433

   MSGCNT     19
   NAME       SIGNALduino_unknown_52

   NR         1074
   STATE      A802DF2C401F96437A800015CE5 | 2019-01-03 21:31:51
   TYPE       SIGNALduino_un
   bitMSG     101010000000001011011111001011000100000000011111100101100100001101111010100000000000000000010101110011100101
   lastMSG    A802DF2C401F96437A800015CE5
   signalesp433_DMSG u52#A802DF2C401F96437A800015CE5
   signalesp433_MSGCNT 19
   signalesp433_RAWMSG MC;LL=-977;LH=969;SL=-495;SH=491;D=57FD20D3BFE069BC857FFFEA31A;C=488;L=107;R=12;
   signalesp433_RSSI -68
   signalesp433_TIME 2019-01-03 21:31:51
   READINGS:
     2019-01-03 21:31:51   bitCount        108
     2019-01-03 21:31:27   bitCountLength  108 to 132
     2019-01-03 21:31:51   bitMsg          101010000000001011011111001011000100000000011111100101100100001101111010100000000000000000010101110011100101
     2019-01-03 21:31:51   bitMsg_invert   010101111111110100100000110100111011111111100000011010011011110010000101011111111111111111101010001100011010
     2019-01-03 21:31:51   hexCount_or_nibble 27
     2019-01-03 21:31:51   hexMsg          A802DF2C401F96437A800015CE5
     2019-01-03 21:31:51   hexMsg_invert   57FD20D3BFE069BC857FFFEA31A
     2019-01-03 21:31:51   lastInputDev    
signalesp433

     2019-01-03 21:31:51   state           A802DF2C401F96437A800015CE5
Attributes:
   IODev      
signalesp433

   room       SIGNALduino_un
   stateFormat {ReadingsVal('
SIGNALduino_unknown_52', 'state', '').' | '.ReadingsTimestamp('SIGNALduino_unknown_52', 'state', '-');}

**Comment by dmqgit** [comment]
Neben dem FileLog gibt es nun folgendes device:

```
Internals:
   CFGFN
   DEF        SIGNALduino_unknown_52
   IODev      signalesp433
   LASTInputDev signalesp433

   MSGCNT     19
   NAME       SIGNALduino_unknown_52

   NR         1074
   STATE      A802DF2C401F96437A800015CE5 | 2019-01-03 21:31:51
   TYPE       SIGNALduino_un
   bitMSG     101010000000001011011111001011000100000000011111100101100100001101111010100000000000000000010101110011100101
   lastMSG    A802DF2C401F96437A800015CE5
   signalesp433_DMSG u52#A802DF2C401F96437A800015CE5
   signalesp433_MSGCNT 19
   signalesp433_RAWMSG MC;LL=-977;LH=969;SL=-495;SH=491;D=57FD20D3BFE069BC857FFFEA31A;C=488;L=107;R=12;
   signalesp433_RSSI -68
   signalesp433_TIME 2019-01-03 21:31:51
   READINGS:
     2019-01-03 21:31:51   bitCount        108
     2019-01-03 21:31:27   bitCountLength  108 to 132
     2019-01-03 21:31:51   bitMsg          101010000000001011011111001011000100000000011111100101100100001101111010100000000000000000010101110011100101
     2019-01-03 21:31:51   bitMsg_invert   010101111111110100100000110100111011111111100000011010011011110010000101011111111111111111101010001100011010
     2019-01-03 21:31:51   hexCount_or_nibble 27
     2019-01-03 21:31:51   hexMsg          A802DF2C401F96437A800015CE5
     2019-01-03 21:31:51   hexMsg_invert   57FD20D3BFE069BC857FFFEA31A
     2019-01-03 21:31:51   lastInputDev
signalesp433

     2019-01-03 21:31:51   state           A802DF2C401F96437A800015CE5
Attributes:
   IODev
signalesp433

   room       SIGNALduino_un
   stateFormat {ReadingsVal('
SIGNALduino_unknown_52', 'state', '').' | '.ReadingsTimestamp('SIGNALduino_unknown_52', 'state', '-');}

```

**Comment by HomeAutoUser** [comment]
Lass bitte das Logfile etwas füllen mit den Daten und notiere bitte ab und zu mal via klick auf das Device -> UserInfo welche Sichtbaren Stände an deinem Sender sind. Zum Bsp.: Zählerstand usw. Das hilft dabei die Daten zu entschlüsseln wenn man weiß nach was man sucht.

**Comment by dmqgit** [comment]
Danke sidey. Das hatte meine Recherche auch ergeben. Ich frage mich gerade aber, wo wir in die osv_PIR Richtung falsch abgebogen sind :) Danke vorab.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
