### ISSUE TITLE
Autocreate threshhold anpassen

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#474]
https://forum.fhem.de/index.php?topic=58397.msg880735.msg#880735

#  Specifications for new sensor / switch / or other device ... 

  - manufacturer:
  - model name:
  - pictures of the device / the board (very helpful)

  
## Specifications 

  - Microcontroller:
  - Version (Firmware):
  

  - Versionmodul (FHEM Module):
  

```
Im Log erhalte ich zyklisch folgende Meldungen:
2019.01.02 18:47:48 1: sduino: SD_WS_Parse UNDEFINED sensor SD_WS_33_TH detected, code SD_WS_33_TH_1
2019.01.02 18:52:46 1: sduino: SD_WS_Parse UNDEFINED sensor SD_WS_33_TH detected, code SD_WS_33_TH_1
2019.01.02 18:57:46 1: sduino: SD_WS_Parse UNDEFINED sensor SD_WS_33_TH detected, code SD_WS_33_TH_1

```

Der Autocreate Threshhold unterstützt diesen Sensor nicht:

https://github.com/RFD-FHEM/RFFHEM/blob/9a8efc11790079fd3fbdd3f8efb16d6f2b4978bf/FHEM/14_SD_WS.pm#L52

**Comment by elektron-bbs** [comment]
Ich denke, das löst das eigentliche Problem nicht. Von seinen geposteten 4 Nachrichten passen nur 2 (Nachricht 1 und 4) zur Definition von Protokoll 33:

 4: sduino/msg READredu: MS;P1=399;P2=-7743;P3=-2038;P4=-3992;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;m2;
 4: sduino/msg READredu: MS;P1=393;P2=-7752;P3=-2047;P4=-3993;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;m1;
 4: sduino/msg READredu: MS;P1=396;P2=-7759;P3=-2045;P4=-4000;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;m0;
 4: sduino/msg READredu: MS;P1=399;P2=-7733;P3=-2043;P4=-3991;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;

Bei seinen Nachrichten ist clockabs ca. 400, im Protokoll 33 ist aber 500 definiert. Clockabs zu verringern wäre keine gute Idee, da ich bei einem anderen Sensor, den ich gerade bearbeite, auch Zeiten von wenig über 600 sehe.

Mit einer 2. Defintion werden seine 4 Nachrichten dekodiert:

	"33.1" => ## Tchibo Wetterstation
						# https://forum.fhem.de/index.php/topic,58397.msg880339.html#msg880339
						# MS;P1=399;P2=-7743;P3=-2038;P4=-3992;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;m2;
						# MS;P1=393;P2=-7752;P3=-2047;P4=-3993;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;m1;
						# MS;P1=396;P2=-7759;P3=-2045;P4=-4000;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;m0;
						# MS;P1=399;P2=-7733;P3=-2043;P4=-3991;D=12131314141414141313131413131314141414131313141314131414131314131314131313131314131314;CP=1;SP=2;R=230;O;
		{
			name					=> 'weather sensors',
			comment				=> 'other syncpulse',
			id						=> '33.1',
			knownFreqs		=> '433.92',
			one						=> [1,-10],     # 500,-4000
			zero					=> [1,-5],      # 500,-2000
			sync					=> [1,-19],     # 500,-7600
			clockabs			=> '400',
			format				=> 'twostate',
			preamble			=> 'W33#',
			postamble			=> '',
			clientmodule	=> 'SD_WS',
			length_min		=> '42',
			length_max		=> '44',
		},

**Comment by elektron-bbs** [comment]
Die Protokolldefinition wurde jetzt in die Entwicklerversion eingearbeitet.
Ich schließe dieses Issue.
