### ISSUE TITLE
Atlantic Security - MD-210R + other

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#477]
... die Diskussion im Forum wird zu unübersichtlich.
Gern möchte ich dies richtig stellen das der Sensor bei MU und bei MS funktioniert. @Ralf9 

##  Specifications for new sensor / switch / or other device ... 
  - manufacturer: Atlantic Security 
  - model name: MD-210R + other

ab hier ...
https://forum.fhem.de/index.php/topic,58397.1095.html

https://forum.fhem.de/index.php/topic,58397.msg878016.html#msg878016
https://forum.fhem.de/index.php/topic,58397.msg878320.html#msg878320
https://forum.fhem.de/index.php/topic,58397.msg878620.html#msg878620
https://forum.fhem.de/index.php/topic,58397.msg878684.html#msg878684
https://forum.fhem.de/index.php/topic,58397.msg878692.html#msg878692
https://forum.fhem.de/index.php/topic,58397.msg881450.html#msg881450
https://forum.fhem.de/index.php/topic,58397.msg881713.html#msg881713
https://forum.fhem.de/index.php/topic,58397.msg881757.html#msg881757

Es ist auch die Rede von Bug im MS decoder
https://forum.fhem.de/index.php/topic,58397.msg881606.html#msg881606

Wie und wo ist Handlungsbedarf? Sollte es auch einen Unterschied geben in der decodierung von euren Firmwareversionen dann würde ich doch bitten einheitlichung erstmal herzustellen @Ralf9 + @sidey79

**Comment by Ralf9** [comment]
Die vielen Links hier zum fhem Forum sind mir zu unübersichtlich. Ich würde gerne im fhem Forum weiter machen.
Ich mache dafür dort ein neues Thema auf, wo ich es näher beschreibe.
Das Problem ist unhabhängig von der firmware.

**Comment by HomeAutoUser** [comment]
Wir können auch hier alles ordnen aber cih füge mich gern. Auf jedenfall muss es in ein Separates Thema weil wir sonst alles vermischen.

**Comment by HomeAutoUser** [comment]
Hier geht es um das Thema nun zusammenhängend!

https://forum.fhem.de/index.php?topic=95346.new#new
