### ISSUE TITLE
SD_RSL  support set extensions

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#483]
## Specifications 

Support set extensions (on-for-timer, on-till,...)  for RSL Devices

API Details:
https://wiki.fhem.de/wiki/DevelopmentModuleAPI#SetExtensions)

**Comment by sidey79** [comment]
@Ralf9 

Könntest Du das einbauen?

**Comment by Ralf9** [comment]
Ich kann mal versuchen, ob ich es hinbekomme, ich werde aber erst mal abwarten, ich möchte momentan keine weiteren pullrequests mehr aufmachen, wir haben im Moment 8 offene Pullrequests

**Comment by sidey79** [comment]
#682
