### ISSUE TITLE
SD_RSL IODEV not correctly assigned

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#484]
## Expected Behavior
Whet autocreate creates a SD_RSL device, then the IODEV is set to the device, which received the message

## Actual Behavior

IF there are more than one signalduino definition is availble, it is may be set to the wrong signalduino device

## Steps to Reproduce the Problem

  1. Create more than one signalduino definition 
  2, use get raw on different definitions from Type SIGNALduino with valid RSL Data.
  3. Let autocreate create one or more RSL devices
  4. Check if the assigned IODEV is always the same, which was used with the get raw command.

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/RFD-FHEM/RFFHEM/issues/483 (SD_RSL  support set extensions).

**Comment by HomeAutoUser** [comment]
Es wurde mit https://github.com/RFD-FHEM/RFFHEM/pull/523 gefixt.
