### ISSUE TITLE
preamble bei Modulen die mehrere Protokolle unterstützen

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#498]
Momentan muß jedesmal, wenn bei den Modulen SD_UT und SD_BELL ein neues Protokoll dazu kommt auch die ID bei der regex in der Matchlist und beim Match Eintrag im logischen Modul ergänzt werden. Die regex sind inzwischen schon recht lang geworden:
```
17:SD_UT"	=> '^P(?:14|29|30|34|46|69|76|81|83|86|91|91.1|92)#.*', 
"27:SD_BELL"	=> '^P(?:15|32|41|42|57|79)#.*',
```
Ich würde es besser finden, wenn wir für solche Module die mehrere Protokolle unterstützten einen anderen Buchstaben als P am Anfang verwenden könnten.
Eine Möglichkeit wären auch 2 Buchstaben z.B.
pu für SD_UT und
pb für SD_BELL
z.B.
pb15# anstatt P15
pu14# anstatt P14

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

**Comment by HomeAutoUser** [comment]
Von mir aus, können wir gern dies so handhaben.
Ich ändere es demnächst ab und würde vorschlagen anstatt den "Protokollnummern" nutzen wir `PUT` und `PBELL`. Diese Kürzel sind nicht zu kurz und werden somit auch im kompletten System mit Sicherheit keine erneute Benutzung finden.

**Comment by sidey79** [comment]
Ich würde es so lassen wie es ist.
Damit hat man eine durchgängige Zuordnung.

**Comment by HomeAutoUser** [comment]
>Damit hat man eine durchgängige Zuordnung.

Ich gehe davon aus, das du die P08,P15 Variante meinst ;-) ?

**Comment by sidey79** [comment]
Ja genau.

**Comment by Ralf9** [comment]
Ich finde dadurch, daß Ihr auch für das SD_UT und SD_BELL Modul "`P<id>#`" als Preamble verwendet, macht Ihr Euch das Leben unnötigt schwer, es ist auch eine unnötige Fehlerquelle.
Aktuell wurde in der matchListSIGNALduino die id 93 vergessen:
`17:SD_UT"	=> '^P(?:14|29|30|34|46|69|76|81|83|86|90|91|91.1|92)#.*',`

Mit der Preamble PU<id># hätte hier die 00_Signalduino zum Testen nicht ersetzt werden müssen. 
https://github.com/RFD-FHEM/RFFHEM/issues/558#issuecomment-479148093

Und wenn wir noch ein neues Attribut "userprotocol" einführen, dann muss zum Testen auch die SD_ProtocolData.pm nicht ersetzt werden.
In das neue Attribut "userprotocol" wird die neue Protokolldefinition als json String eingetragen.
Z.B. bei der ID 95 sieht der json String so aus:
`{"name":"Techmar", "id":"95", "one":[1,-0.6], "zero":[1,-1.2], "start":[1,-1.8], "clockabs":"550", "format":"twostate", "preamble":"P95#", "clientmodule":"SD_UT", "length_min":"50", "length_max":"50"}`

Das erzeugen des json String kann in das 88_SIGNALduino_TOOL.pm eingebaut werden.

Der Code in der "sub SIGNALduino_Attr" sieht ungefähr so aus. Ist noch nicht fertig.

```
	elsif ($aName eq "userProtocol")
	{
		my $decoded = eval { decode_json($aVal) };
		SIGNALduino_Log3 $name, 3, "$name Attr: userProtocol " . Dumper($decoded);
		my $id = $decoded->{id};
		foreach my $field (keys %{$decoded}) {
			SIGNALduino_Log3 $name, 3, "$name Attr: userProtocol Field=$field : " . $decoded->{$field};
			$ProtocolListSIGNALduino{$id}{$field} = $decoded->{$field};
		}
	}
```

**Comment by HomeAutoUser** [comment]
@Ralf9 
was haben das 
1) preamble 
2) attr userProtocol

miteinader zu tun? Auf den ersten Blick sind das für mich 2 verschiedene Dinge oder welchen Zusammmenhang stellst du damit her? Geht es dir darum, das man nicht die SD_ProtocolData.pm zum testen anpassen muss?

Das man das bzw. die preamble optimieren könnte, ja.

**Comment by Ralf9** [comment]
Ja, es hat nichts miteinander zu tun, wenn interesse an dem Attribut "userprotocol" besteht, kann ich dafür ein Extra Issue aufmachen.

**Comment by Ralf9** [comment]
Ich hab mal versucht für die matchList die neue regex für das SD_UT Modul zu erstellen, ist dies so ok?
`'^PU\d+(\.[0-9]){0,1}#.*'`

**Comment by Ralf9** [comment]
Da für die extra Preamble, bei Modulen die mehrere Protokolle unterstützen, bei Euch anscheinend kein Interesse besteht, kann ich dies hier ja schließen.

**Comment by HomeAutoUser** [comment]
Hallo @Ralf9,

eine sofortige Nichtreaktion heißt automatisch nicht, kein Interesse.
Es gibt Tage und Situation da haben anderes Dinge Priorität und keine Rechnerzeit.

Nach einer ersten Arugmentationsrunde mit @elektron-bbs ist die Idee gut.

Ich hätte nur einen Einwand bzw Verbesserungsvorschlag.

Den Preample PU bitte mindestens 3 stellig. Bei 2 Stellig verbauen wir uns ggf bei einem neuen ähnlich klingenden Modul den „Bezugspunkt“.

Möglichkeiten wären
1) PU(Ordnungszahl)
2) PU(2.Buchstabe vom Modul)

Grüße von mobil

**Comment by Ralf9** [comment]
Ja, es kann natürlich auch z.B. `PUT>id>#` heissen.
Z.B.
`preamble     => 'PUT93#',`

**Comment by HomeAutoUser** [comment]
Ich hätte nichts gegen die den Vorschlag von @Ralf9 mit „PUT93#“.

Wie denken die anderen @sidey79 und @elektron-bbs?

**Comment by sidey79** [comment]
Ich bin der Meinung, die Lösung liegt eher darin, die Matchlist dynamisch zu erzeugen.

Mit dem Ändern der Preamble könnten Kompatibilitats Probleme auftreten.

Ich verstehe aber durchaus die Motivation und kann auch nachvollziehen wieso diese Lösung vorgeschlagen wird.

Müsste man jetzt halt abwegen, ob man das einmal generell oder nur für das eine Logische Modul lösen möchte.

**Comment by Ralf9** [comment]
> Mit dem Ändern der Preamble könnten Kompatibilitats Probleme auftreten.

Ich kann mir da keine Kompatibilitats Probleme vorstellen.
Da bei einem Dispatch zu einem Modul kein event erzeugt wird, kann es auch zu keinen Problemen mit evtl notify kommen.
Und beim Senden ändert sich nichts.

Es wird mit dieser Lösung auch generell gelöst.
Die neuen Preamble werden beim SD_UT, SD_BELL, evtl für SD_Keelog und alle zukünftigen neuen Module, wo es mehrere IDs geben könnte, verwendet.

**Comment by HomeAutoUser** [comment]
@sidey79 
>Mit dem Ändern der Preamble könnten Kompatibilitats Probleme auftreten.

Welche Probleme siehst du darin bzw. welcher Fall würde zum tragen der Inkompatiblität führen?

>Müsste man jetzt halt abwegen, ob man das einmal generell oder nur für das eine Logische Modul lösen möchte.

Wenn ich mir das überlege, so wäre das Ansinnen, das man das generell umsetzt und nicht nur für das SD_UT Modul. Wir fassen es an, so können wir dies generell auch für die Zukunft "sicher" gestalten.

**Comment by sidey79** [comment]
Die Regex in der Matchlist und im logischen Modul müssen passen, damit Nachrichten ausgewertet werden.
Wenn man die Nachricht so anpasst, dass eine Regex nicht mehr stimmt, dann kann das zu Kompatibilitätsproblemen führen.

Wenn sich jemand die Nachrichten Zusätzlich als Event ausgeben lässt und darauf eine Auswertung fährt, dann kommt es auch zu einem Kompatibilitätsproblem.

Sollte es notwendig sein, ein Protokoll einem anderen Modul zuzuweisen, dann würde die Regex wieder angepasst.
All das wäre aus meiner Sicht vermeidbar, wenn man die Matchlist zur Laufzeit generiert. Die Daten, welche die Matchlist ergeben, haben wir ja durchaus vorliegen.

**Comment by Ralf9** [comment]
> Die Regex in der Matchlist und im logischen Modul müssen passen, damit Nachrichten ausgewertet werden.

Dazu wird ja vor dem aproven der neuen preamble getestet, damit dies nicht passieren kann.

> Sollte es notwendig sein, ein Protokoll einem anderen Modul zuzuweisen, dann würde die Regex wieder angepasst.

Dies sollte nie gemacht werden, wie soll ein User dies händeln?
Wenn ein Protokoll einem anderen Modul zugewiesen wird, dann ändert sich beim define vom Sensor die DEF und TYPE, da ist das ändern der regex das kleinste Problem

**Comment by Ralf9** [comment]
Wie gehts hier weiter? Soll ich es zumachen?
Ich habe das Gefühl, daß es sidey nicht gefällt.

**Comment by HomeAutoUser** [comment]
Warte mal noch bitte.
Derzeit ist vielleicht auch er wie ich / wir noch in Osterlaune und selten am PC oder nur Mitleser wie ich am Handy.

Ich denke, das findet noch ein positives Ende.

**Comment by HomeAutoUser** [comment]
@Sidey79, wie stehst du zu der Idee mit dem Preamble?

**Comment by sidey79** [comment]
@HomeAutoUser 

Meiner Meinung nach wäre es flexibler wenn die Matchlist einfach dynamisch erzeugt wird, anstatt dass wir uns je Modul eine Zeichenfolge überlegen mit der es zugewiesen wird.
Aber dazu hat sich bislang nicht wirklich jemand geäußert.

**Comment by HomeAutoUser** [comment]
Was für einen Umfang hätte die Anpassung zur dynamischen preamble und welche Vorteile gäbe es zu der „vereinfachten“ Variante wie von Ralf vorgeschlagen?

Was ist auch abwärts kompatible um auf andere User Rücksicht zu nehmen?

**Comment by Ralf9** [comment]
@sidey79 
Ich denke außer Dir kann sich momentan niemand unter einer dynamischen Matchlist was vorstellen.
Hört sich recht aufwändig und komliziert an. Bei einer dynamisch erzeugten Matchlist wird es wahrscheinlich schwieriger herauszufinden warum ein dispatch nicht funktioniert.
Dieser Eintrag im logischen Modul wird dadurch wahrscheinlich auch nicht einfacher:
`$hash->{Match} = "^P(?:14|29|30|34|46|69|76|81|83|86|90|91|91.1|92|93|95)#.*";`


Wie möchstet Du z.B. solche Einträge dynamisch erzeugen.
```
"4:OREGON"            		=> "^(3[8-9A-F]|[4-6][0-9A-F]|7[0-8]).*",
"23:FHT"      				=> "^81..(04|09|0d)..(0909a001|83098301|c409c401)..",
"24:FS20"    				=> "^81..(04|0c)..0101a001", 
```

**Comment by sidey79** [comment]
Hi @Ralf9 

Scheinbar kann nur ich mir das vorstellen. :(

Die Matchlist hat auch erst mal nichts mit dem Match Eintrag in den logischen Modulen zu tun. Das sind leider zwei getrennte Dinge.

Das Beispiel für Oregon ist recht leicht umgesetzt.

Ich würde dazu das Feld clientmodule auswerten und in dem Hash den Wert
`$nr:$clientmodule => "$modulematch"` definieren. Der Code hat hier nur symbolischen charakter, die Variablen müssen anders angesprochen werden!

https://github.com/RFD-FHEM/RFFHEM/blob/445a5dc11e523bcab3b5bafc65f952eef884a3ce/FHEM/lib/SD_ProtocolData.pm#L385-L386

Bei FS20 und FHT siehts tatsächlich etwas anders aus. Im Protokoll 70 und 74 fehlt leider der Wert für modulematch. Wenn auch noch der Wert clientmodule gesetzt wäre, so könnte dieser Wert gesetzt werden.


Um das Feld $hash->{Match} automatisiert zu befüllen könnte man sich aber einer ähnlichen Funktion verhelfen denke ich,

**Comment by Ralf9** [comment]
Der Match Eintrag in den logischen Modulen mit vielen IDs wird dadurch nicht einfacher.
Ein direkter Dispatch mit `get dummysduino raw` ist damit nicht mehr möglich.

**Comment by Ralf9** [comment]
Mir ist noch nicht richtig klar, möchtest Du vor jedem Dispatch den dazu passenden Eintrag in die Matchliste eintragen? Die Matchliste würde dann nur aus einem Eintrag bestehen und ein direkter Dispatch wäre dann nicht mehr möglich.

Oder möchtest Du am Anfang die matchlist automatisiert erzeugen? Hätte dann die matchlist für jede ID einen Eintrag?

**Comment by sidey79** [comment]
Die Matchlist erzeugt man besser beim define bzw. Kann man hier auch die Whitelist berücksichtigen.

Für Mehrfachnennungen könnte man mit einem oder realisieren.

Das Code Beispiel war jetzt extrem vereinfacht gehalten. Das würde ich bei der Umsetzung zweistufig realisieren.

Der Match Eintrag im logischen Modul ist ja eine weitere Diskussion. Das wird ja vom logischen Modul kontrolliert, was es annehmen möchte.
Aber auch hier kann man den gleichen Mechanismus anwenden wie bei der Matchlist denke ich.

**Comment by Ralf9** [comment]
Dies bestätigt meine Annahme, daß dies recht kompliziert und aufwändig wird.
Die matchlist wird dann wahrscheinlich nicht mehr so kompakt und optimiert sein wie jetzt.

**Comment by HomeAutoUser** [comment]
Was ist der Vorteil wenn man es umstellt? „Nur das wir nichts mehr dort eintragen müssen“?

So richtig habe ich den noch nicht herausgelesen oder „gerafft“.

Ich sehe darin ein Unterschied als zu dem Thema mit vielen Matches der Regex wie das Thema aufkam.

**Comment by sidey79** [comment]
@HomeAutoUser 
Ich verstehe dein Kommentar nicht. :(

**Comment by HomeAutoUser** [comment]
1) Was ist der Vorteil, wenn du die Matchlist dynamisch machen würdest?

2) Die Anpassung der Preamble bei Modulen bzw. id‘s wo viele P12|34|76|.... sind sehe ich als was anderes.

Oder verstehe ich das ganze nicht?

**Comment by sidey79** [comment]
> 1. Was ist der Vorteil, wenn du die Matchlist dynamisch machen würdest?

Der Auftakt war folgender:
> Momentan muß jedesmal, wenn bei den Modulen SD_UT und SD_BELL ein neues Protokoll dazu kommt auch die ID bei der regex in der Matchlist ergänzt werden. Die regex sind inzwischen schon recht lang geworden...

Aus der Diskussion habe ich entnommen, dass es "fehleranfällig" und Äufwändig ist, diese Einträge zu pflegen und auch ab und an mal vergessen wird den Eintrag vorzunehmen.

Das erzeugen zur Laufzeit begegnet diesem Verhalten. Das **Vergessen** kann man so deutlich minimieren, indem die Anpassungen in ProtocolData vorgenommen werden.
Weiterhin haben wir dadurch einen weiteren Schritt unternommen den quellcode des 00_SIGNALduino Modules von den Konfigurationsdaten (SD_ProtocolData) zu trennen.

Der **Aufwand** wird dadurch ebenso minimiert, da prinzipiell die Daten welche in der Matchlist stehen auch bereits in SD_ProtocolData gepflegt sein sollten. 

Die **Fehleranfälligkeit** könnte natürlich erst mal etwas zu ungunsten der manuellen Vorgehensweise leiden. Andererseits können wir das gut testen und ich stelle es mir noch immer nicht mega kompliziert vor.
Die Matchlist selbst, wird ohnehin nur benötigt, damit eine Definition via autocreate angelegt werden kann, wenn das logische Modul noch nicht geladen wurde.




> 2. Die Anpassung der Preamble bei Modulen bzw. id‘s wo viele P12|34|76|.... sind sehe ich als was anderes.
>  Oder verstehe ich das ganze nicht?

Die Anpassung der Preamble um zusätzlichen Identifizierungsmerkmale war doch eine andere Umsetzung um die Anforderugen an Vergessen, Äufwändig und Fehleranfällig zu erfüllen, Wozu braucht es die dann noch, wenn die Matchlist nicht mehr manuell angepasst werden muss?

**Comment by Ralf9** [comment]
> Aus der Diskussion habe ich entnommen, dass es "fehleranfällig" und Äufwändig ist, diese Einträge zu pflegen und auch ab und an mal vergessen wird den Eintrag vorzunehmen.

Ein Punkt war auch, daß mit jeder ID die hinzukommt der Matchlist Eintrag und der Match Eintrag im logischen Modul immer länger wird.

Mir ist nicht klar wie mit der dynamischen Matchlist die Einträge kürzer und einfacher werden sollen.
Bei dem Match Eintrag im logischen Modul bringt die dynamische Matchlist keine Vorteile.

**Comment by sidey79** [comment]
Der Match Eintrag im logischen Modul ist erst einmal entkoppelt von der Matchlist im 00_Signalduino.pm

Bislang ging es um die Matchlist. Die kann meines Erachtens zur Laufzeit erzeugt werden, was doppelte Datenpflege minimiert 

Der Match Eintrag könnte prinzipiell auch dynamisch erzeugt werden, dieser stellt allerdings etwas andere Anforderungen an die Lösung.

**Comment by HomeAutoUser** [comment]
> Der Match Eintrag im logischen Modul ist erst einmal entkoppelt von der Matchlist im 00_Signalduino.pm

Wie bringst du das beides zusammen wenn die eine dynamische erzeugt wird und die andere Matchlist im Modul vorgegeben durch den Maintainer.

**Comment by sidey79** [comment]
Erst Mal ist es so, dass es nicht ein und dasselbe ist.

Die Matchlist sorgt nur dafür, dass Module nachgeladen werden.

Der Match Eintrag ist ja eher ein Filter, was das Modul verarbeiten möchte.

Dass kann auch durchaus bei unterschiedlichen Maintainer liegen.

**Comment by Ralf9** [comment]
Mir geht es eigentlich um beide regex, in der Matchlist und im Match Eintrag im logischen Modul, ich habe es im ersten Beitrag ergänzt.
Diese hängen ja miteinander zusammen, in der Regel sind die regex gleich.
Die dynamische Matchlist hat für mich mehr Nachteile als Vorteile.
Da das mit dem Ändern der preamble (z.B. P93# in PUT93#) @sidey79 anscheinend nicht gefällt, ist es wohl am Besten, wenn wir es so lassen wie es ist.
Für mich hat sich das Thema damit erledigt.

**Comment by HomeAutoUser** [comment]
Welche Nachteile siehst du @Ralf9?

**Comment by Ralf9** [comment]
Der Pflegeaufwand wird damit von der Matchlist in die Protokollhash Datei verschoben.
Die Matchlisteinträge bei Universalmodulen werden sich dadurch nicht vereinfachen.
Die Entwicklung und Programmierung der dynamischen Matchlist wird wahrscheinlich recht kompliziert und umfangreich.

**Comment by Ralf9** [comment]
Wenn Ihr die dynamische Matchlist einbauen wollt, bitte dafür ein neues Issue aufmachen.
