### ISSUE TITLE
Neues Internal ID bei Devices

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#499]
Momentan ist beim Device von einigen logischen Modulen beim Internal DMSG die Protokoll ID nicht erkennbar.
Es sind die Protokolle deren preamble kein "#" als Trenner zwischen ID und msg haben.

Wenn diese Zeile
`$addvals{ID} = $id if (index($dmsg,"#") == -1);`

in die `sub SIGNALduno_Dispatch($$$$$)` eingefügt wird

```
		my %addvals = (DMSG => $dmsg);
		$addvals{ID} = $id if (index($dmsg,"#") == -1);
		if (AttrVal($name,"suppressDeviceRawmsg",0) == 0) {
			$addvals{RAWMSG} = $rmsg
		}
```

dann gibt es bei diesen Fällen im Device ein Interal ID
Siehe
https://forum.fhem.de/index.php/topic,96830.0.html

Wenn dies so ok ist, kann ich ein pullrequest machen.

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/162 (Neues Protokoll WS7053), and https://github.com/RFD-FHEM/RFFHEM/issues/160 (Neues Protokoll WS7035).

**Comment by sidey79** [comment]
Ja, ich denke das könnten wir einbauen,
allerdings würde ich es konsistent halten und das Internal immer übergeben. Auch wenn die Protokoll ID in der Nachricht hängt.

Etwas aufwendiger aber vermutlich sinnvoll wäre es, eine Statistik zu haben, welche Protokolle insgesamt erkannt werden.
Gerade wenn es mehrere gibt wie bei 0.1,0.2 usw.

Ob das aber in diesem Internal gut aufgehoben ist, weiss ich nicht. Besser wäre das vielleicht an andere Stelle.
