### ISSUE TITLE
bug bei get availableFirmware 

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#502]
## Expected Behavior
bei get availableFirmware wird auch das attribut hardware berücksichtigt

## Actual Behavior
bei get availableFirmware wird nicht nach dem attribut hardware gefiltert

## Steps to Reproduce the Problem

  1. attribut updateChannelFW stable
  2. attribut hardware nanocc1101
  3. get availableFirmware 

## Specifications
Momentan wird mit updateChannelFW stable und hardware nanocc1101 nach einem `get availableFirmware` bei set flash die V 3.3.0 angezeigt obwohl es dafür keine firmware für den cc1101 gibt.
Wenn nun ein User versucht diese nicht vorhandene firmware zu flashen, ist es nicht so einfach zu erkennen warum das flashen nicht funktioniert.

Hier ist ein Patch für die sub SIGNALduino_githubParseHttpResponse($)
wenn es so passt, kann ich ein Pullrequest machen:

```
 			my $releaselist="";
+			my $hardware=AttrVal($name,"hardware","nano328");
 			foreach my $release (@fwreleases)
 			{
 				next if (AttrVal($name,"updateChannelFW","stable") eq "stable" && $release->{isprerelease});
 				
+				my $hardwareFlag = 0;
+				foreach my $item (@{$release->{files}}) {		# nur wenn die Hardware passt in die $releaselist eintragen
+					if ($item->{filename} =~ m/$hardware/i) {
+						$hardwareFlag = 1;
+						#Log3 $name, 3, "tag = $release->{tagname}, prerel = $release->{isprerelease}, name = $item->{filename}";
+						last;
+					}
+				}
+				next if ($hardwareFlag == 0);
+				
 				$releaselist.=$release->{tagname}.",";
 			}
 			$releaselist =~ s/,$//;
```

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/499 (Neues Internal ID bei Devices), https://github.com/RFD-FHEM/RFFHEM/issues/24 (Multiple messages get processed within same time), and https://github.com/RFD-FHEM/RFFHEM/issues/154 (Absturz FHEM bei "reload 00_SIGNALduino.pm").

**Comment by sidey79** [comment]
Hi Ralf,

Danke für den Hinweis.

Ich leite zwei Aktivitäten ab.

1. Dateien umbenennen
2. Nur Versionen Anzeigen, wenn es ein Binary für die Hardware gibt.

Ab Perl 5.10 kann man einen Array deutlich einfacher durchsuchen :
` say "'$wanted' matches!" if /$hardware/ ~~ @array;   `

Das würde die innere Schleife und das Flaggschiff einsparen

**Comment by sidey79** [comment]
Die Dateinamen für den Nano habe ich angepasst
