### ISSUE TITLE
Protokoll für Temperatursensor KW9010

### ISSUE THREAD

**Issue by yogiflop** [RFD-FHEM/RFFHEM#51]
Hardware: Arduino Nano
Firmware: V 3.2.0-b3 SIGNALduino - compiled at Nov 13 2015 21:39:55
RF device: ehemaliger FHEMduino

2015.11.25 20:52:15.383 5: SIGNALduino/RAW READ: /MS
2015.11.25 20:52:15.386 5: SIGNALduino/RAW READ: MS/;P0=-4710;P2=496;P3=-194
2015.11.25 20:52:15.389 5: SIGNALduino/RAW READ: MS;P0=-4710;P2=496;P3=-194/6;P5=-8904;D=2523
2015.11.25 20:52:15.392 5: SIGNALduino/RAW READ: MS;P0=-4710;P2=496;P3=-1946;P5=-8904;D=2523/232323232023232323
2015.11.25 20:52:15.395 5: SIGNALduino/RAW READ: MS;P0=-4710;P2=496;P3=-1946;P5=-8904;D=2523232323232023232323/23202320202020232
2015.11.25 20:52:15.398 5: SIGNALduino/RAW READ: MS;P0=-4710;P2=496;P3=-1946;P5=-8904;D=252323232323202323232323202320202020232/020232323232323202
2015.11.25 20:52:15.403 5: SIGNALduino/RAW READ: MS;P0=-4710;P2=496;P3=-1946;P5=-8904;D=252323232323202323232323202320202020232020232323232323202/32323202020232023;CP=2;SP=5;O
2015.11.25 20:52:15.405 5: SIGNALduino/RAW READ: MS;P0=-4710;P2=496;P3=-1946;P5=-8904;D=25232323232320232323232320232020202023202023232323232320232323202020232023;CP=2;SP=5;O/;

2015.11.25 20:52:15.405 4: SIGNALduino/msg READ: MS;P0=-4710;P2=496;P3=-1946;P5=-8904;D=25232323232320232323232320232020202023202023232323232320232323202020232023;CP=2;SP=5;O;
2015.11.25 20:52:15.408 4: Found matched Protocol id 0 -> weather1
2015.11.25 20:52:15.409 5: Starting demodulation at Position 2
2015.11.25 20:52:15.409 5: converted Data to (s0417B023A000)
2015.11.25 20:52:15.445 5: SIGNALduino dispatch s0417B023A000
2015.11.25 20:52:15.788 5: SIGNALduino/RAW READ: /MS;P0=-195
2015.11.25 20:52:15.791 5: SIGNALduino/RAW READ: MS;P0=-195/2;P1=491;P2=-4028;
2015.11.25 20:52:15.793 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;/P3=-8908;D=1
2015.11.25 20:52:15.796 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=1/31010101010
2015.11.25 20:52:15.798 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=131010101010/121010101010121012
2015.11.25 20:52:15.800 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=131010101010121010101010121012/121212101212
2015.11.25 20:52:15.802 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=131010101010121010101010121012121212101212/10101010101
2015.11.25 20:52:15.805 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=13101010101012101010101012101212121210121210101010101/012101010121
2015.11.25 20:52:15.807 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=13101010101012101010101012101212121210121210101010101012101010121/212101210;CP=1;SP=
2015.11.25 20:52:15.809 5: SIGNALduino/RAW READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=13101010101012101010101012101212121210121210101010101012101010121212101210;CP=1;SP=/3;O;

2015.11.25 20:52:15.810 4: SIGNALduino/msg READ: MS;P0=-1952;P1=491;P2=-4028;P3=-8908;D=13101010101012101010101012101212121210121210101010101012101010121212101210;CP=1;SP=3;O;
2015.11.25 20:52:15.815 4: Found matched Protocol id 0 -> weather1
2015.11.25 20:52:15.816 5: Starting demodulation at Position 2
2015.11.25 20:52:15.817 5: converted Data to (s0417B023A000)
2015.11.25 20:52:15.818 4: Dropped (s0417B023A000) due to short time or equal msg

**Comment by sidey79** [comment]
okay, die Daten werden empfangen und gehen dann an das CUL_TCM_97001 Modul, dort ist der kw9010 aber leider nicht abgebildet.

**Comment by sidey79** [comment]
Implementierung wird in CUL_TCM97001 probiert: 
http://forum.fhem.de/index.php?topic=42402.msg370472#msg370472
