### ISSUE TITLE
Update SVN Versions of modules

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#513]
- [ ] 14_BresserTemeo.pm (unklarer Zustand)

Logical modules which must be added to svn before Signalduino version 3.3.3
- [x] 14_FLAMINGO.pm (homeautouser )
- [x] 14_SD_BELL.pm (homeautouser  )
- [x] 10_FS10.pm	 (elektron-bbs  )
- [x] 14_SD_UT.pm	  (homeautouser  )

Updates other modules
- [x] 14_Hideki.pm (sidey)
- [x] 14_SD_RSL.pm	 (sidey  )
- [x] 14_SD_WS.pm  (sidey  )
- [x] 14_SD_WS_Maverick.pm (sidey  )
- [x] 14_SD_WS07.pm (sidey  )
- [x] 14_SD_WS09.pm (sidey  )
- [x] 41_OREGON.pm (sidey  )
- [x] 90_SIGNALduino_un.pm (sidey  )
- [x] 00_SIGNALduino.pm (sidey)
- [x] signalduino_protocols.hash (sidey)

@HomeAutoUser @elektron-bbs

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/9 (Update Docs), https://github.com/RFD-FHEM/RFFHEM/issues/211 (Update - Welche Version?), https://github.com/RFD-FHEM/RFFHEM/issues/8 (Dynamic logical modules), https://github.com/RFD-FHEM/RFFHEM/issues/95 (Add Flamenco module), and https://github.com/RFD-FHEM/RFFHEM/pull/511 (Update 88_SIGNALduino_TOOL.pm).

**Comment by HomeAutoUser** [comment]
@sidey79, sehe ich das richtig, das ich unsere Module in einem Faden vorstellen muss im Forum oder können wir es zusammenfassen?

Das hochladen ins SVN kann ich machen :) und gebe Bescheid.

**Comment by sidey79** [comment]
@HomeAutoUser 
Ich bin nicht sicher ob ein Beitrag im Forum pflicht ist, aber es ist bestimmt gut, wenn für jedes Modul ein eigener Beitrag existiert. Dann kommt auch niemand durcheinander was wo hin gehört :)

Einfach abhaken, wenn der Upload erledigt ist. Ich lade dann anschließend auch hoch.

**Comment by HomeAutoUser** [comment]
@sidey79 
ich mache nun einen Rundschlag. Ich erstelle einen Faden mit Bezifferung der 3 Module im Faden **Ankündigung** und mache ebenso noch einen gekürzten Faden bei **Sonstige Systeme** mit dem Verweis, bei Fragen und Anregungen unsw. hier oder im Forum dazu äußern.

Für alle einen Faden das wäre sicherlich übertrieben.
Die Vorstellung ist gewünscht laut "Wiki".

**Comment by elektron-bbs** [comment]
@sidey79 
Warum lädst du die Module nicht einfach mit hoch? Sie sind doch quasi Bestandteil von SIGNALduino. Ohne SIGNALduino nutzen sie keinem etwas.

**Comment by sidey79** [comment]
@elektron-bbs 
Die FHEM SVN Regeln sind da etwas "altmodisch". Dort wird angenommen, der Maintainer und nur der Maintainer lädt sein Modul hoch. Finde ich auch etwas unpraktisch aber naja.

**Comment by HomeAutoUser** [comment]
@sidey79 
checkin 14_FLAMINGO.pm | 14_SD_BELL.pm | 14_SD_UT.pm erfolgte.
Absofort im SVN mit dem Stand Master

**Comment by elektron-bbs** [comment]
Würde das bedeuten, das ich dann Updates auch immer an zwei Stellen vornehmen müsste?
Die Prozedur fürs SVN ist schon ziemlich umständlich und wenn ich es dort einpflege, dürftest du ja theoretisch keine Änderungen daran mehr vornehmen, obwohl es ja zu SIGNALduino gehört.
Ich glaube, es ist das Beste, du setzt dann erst mal "developId" auf m oder y, damit es nicht wieder zu Fehlermeldungen führt, wie nach dem letzten Update vom SVN (https://forum.fhem.de/index.php/topic,81641.msg737148.html#msg737148). Damals hattest du es ja noch eingepflegt, war aber dann dort wieder "verschwunden".

**Comment by sidey79** [comment]
@elektron-bbs 

Jein.  Also wir entwickeln hier auf GIT und von Zeit zu Zeit aktualisieren wir dann das SVN. 
Hier im GIT gelten ja die FHEM Regeln nicht und wir können wir auch wie bisher gemeinsam an dem Projekt arbeiten.

Leider muss auf dem FHEM SVN Server ein Verantwortlicher benannt werden.
Ein DevelopID m ist meiner Einschätzung nach nicht notwendig. Das FS10 Modul hat sich doch bereits jeder installiert, der die dev-r33 oder den aktuellen master installiert hat. Wenn es da zu Problemen kommen würde, hätten wir das bestimmt schon gehört.

Dass ich das FS10 mal ins SVN gebracht habe, davon weiss ich nichts mehr :(

**Comment by elektron-bbs** [comment]
Ist ja auch über ein Jahr her :-)

Wenn das Modul im SVN nicht existiert, müsstest du aber in der signalduino_protocols.hash im SVN entweder das Protokoll 61 entweder komplett raus nehmen oder eben wenigstens developId setzen. Bedeutet wahrscheinlich zwei hash-Dateien zu pflegen.

Die MAINTAINER.txt musst du ja IMHO selbst manuell bearbeiten. Trägst du halt dort "sidey/elektron-bbs" ein. Dann sind Maintainer und Uploader teilweise identisch, wie auch bei einigen anderen Modulen z.B. Sidey/Ralf9.

**Comment by sidey79** [comment]
Können wir so machen. Eröffnest Du im Forum dann noch einen Beitrag, danach würde ich es committen

**Comment by sidey79** [comment]
@HomeAutoUser @elektron-bbs 
So bis auf das 10_FS10.pm ist das SVN aktualisiert

**Comment by elektron-bbs** [comment]
Schon wieder der nächste Haken: Im FHEM Forum [Ankündigungen](https://forum.fhem.de/index.php/board,40.0.html) habe ich keine Schreibrechte :-(

**Comment by HomeAutoUser** [comment]
@elektron-bbs dein Link ist nicht vollzählig. Wie ist die Forumsnummer bzw. Fadennummer?

**Comment by elektron-bbs** [comment]
Der Link zeigt aufs Brett "Ankündigungen" und dort haben offensichtlich nur Entwickler Schreibrechte.
Danke für das Angebot, aber ich weiß nicht, ob das gut ankommt, wenn die Vorstellung des Moduls wieder unter einem anderen Namen erfolgt.

**Comment by sidey79** [comment]
@elektron-bbs 

Schickst Du mir den Text ich mach dann den Beitrag :)

**Comment by elektron-bbs** [comment]
Danke, Text hatte ich schon vorbereitet:

Das Modul 10_FS10.pm zur Verarbeitung und Steuerung von FS10-Komponenten wird demnächst im SVN zur Verfügung gestellt.
Betrieben werden kann das Sytem z.B. mit folgenden Geräten: FS10-S8, FS10-S4, FS10-ZE, FS10-ST, FS10-MS, WS3000-TV und PC-Wettersensor-Empfänger
Dieses Modul wurde entwickelt für das SIGNALduino Projekt.
Diskussionen zum Modul sollten bitte direkt auf GitHub oder im FHEM Forum SlowRF erfolgen.

**Comment by HomeAutoUser** [comment]
@sidey79 
gern würde ich hier einen neuen Stand mit "allen" Modulen erzielen wollen für das SVN.
Wie denkst du über ein update im SVN zwecks dem SIGNALduino? Dieses würde ich schon gern zeitnah mit den von mir "verbundenen" modulen vornehmen zwecks Protokolldefinitionen und kleinen fixes.

**Comment by sidey79** [comment]
@homeautouser

Danke für den Hinweis.
Ich sehe es ähnlich.
In diesem Issue war ja nur noch das FS10 Modul offen.
Warum wir hier nicht weiter gemacht haben weiss ich jetzt leider auch nicht mehr so recht.

FS10 sollte ja relativ einfach sein.
Beitrag schreiben, Maintainer anpassen und hochladen :)

Den Rest sollten wir unbedingt auch angehen.
Ich hätte es allerdings gerne, dass zumindest der rmsg/dmsg Testfälle erfolgreich beendet sind.

Das wäre dann eine gute Basis aus meiner Sicht.

**Comment by sidey79** [comment]
Ankündigungslink:
https://forum.fhem.de/index.php?topic=102022.new#new

**Comment by sidey79** [comment]
So, SVN Update für FS_10 ist draussen

@elektron-bbs @HomeAutoUser 

Ich schließe dieses Issue und mache ein neues
