### ISSUE TITLE
OSV3 protocol

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#52]
support osv3 protocol:

example:
2015-11-27 13:18:33-MC;LL=-1036;LH=922;SL=-565;SH=457;D=FFFFFF5F1426100A040E41C27700;C=459;

**Comment by Ralf9** [comment]
more example:
MC;LL=-1078;LH=862;SL=-587;SH=408;D=FFFFEA93040F21C0008112D10562;C=423;
MC;LL=-1072;LH=871;SL=-589;SH=402;D=FFFFFEA624583411C0059920;C=424;
MC;LL=-1032;LH=831;SL=-555;SH=414;D=FFFFFD62448034340F302B01890C;C=414;
MC;LL=-1036;LH=903;SL=-567;SH=418;D=FFFFFEB122401A1A06441580259A;C=440;
MC;LL=-1057;LH=903;SL=-565;SH=429;D=FFFFFEB122401A1A06241441652C;C=443;
MC;LL=-1072;LH=871;SL=-587;SH=390;D=FFFFFA989160D00700661180;C=420;
MC;LL=-1061;LH=882;SL=-576;SH=403;D=FFFFF53122C1A00E00CC2300;C=428;
MC;LL=-1059;LH=892;SL=-523;SH=395;D=7FFFFF5891200D0D03620420123300;C=428;
MC;LL=-1035;LH=911;SL=-554;SH=417;D=FFFFAC4890068681E60410614180;C=442;
MC;LL=-1035;LH=912;SL=-568;SH=439;D=FFFFFEBE284C201C081483842E;C=450;
MC;LL=-1041;LH=904;SL=-566;SH=420;D=FFFFFD7C50A31C00200B8F8A8C;C=441;

**Comment by Ralf9** [comment]
Hallo Sidey,

hast Du Dir mal wegen dem Oregon Modul gedanken gemacht?
Hast Du seither mal was von Willi gehört? Sein letzter Besuch im Forum war am 21 Juli 2015.
Willst Du versuchen das Oregon Modul zu übernehmen oder nur meine Änderungen und Ergänzungen ins SVN übernehmen?
Ich könnte mal  in der RFXTRX Gruppe fragen ob dort das Oregon Modul noch von einigen verwendet wird.

**Comment by Ralf9** [comment]
>Hast Du seither mal was von Willi gehört? Sein letzter Besuch im Forum war am 21 Juli 2015.

Ich habe gerade gesehen, daß Willi gestern wieder im Forum aktiv war.

**Comment by sidey79** [comment]
Also, Willi hat mir bislang nicht geantwortet. Prinzipiell könnte ich das Modul übernehmen.
Die paar Änderungen scheinen auch nicht dramatisch zu sein.

Viel besser wäre natürlich, wenn das Modul jemand jemand verantwortet, der auch so einen rfxtrx hat. Wobei ich nicht einschätzen kann, ob da nicht eh schon andere Module verwendet werden. TRX_*,

**Comment by Ralf9** [comment]
Willi hat sich inzwischen meine Änderungen am Oregon Modul mal angeschaut. Sieht recht gut aus:
http://forum.fhem.de/index.php/topic,48914.msg405761.html#msg405761

**Comment by sidey79** [comment]
fixes from e825b48497d8e7fb380edad9fda56a902bd00f9d should be a adapted to osv3
