### ISSUE TITLE
SD_WS07 - Autocreate loop 

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#527]
## Expected Behavior

Device is created once via autocreate

## Actual Behavior

Device is defined with following values:

```
   CODE       1
   DEF        1

```
but should be something like this

```
   CODE       SD_WS07_TH_1
   DEF        SD_WS07_TH_1

```
## Steps to Reproduce the Problem

1. `defmod SD_WS07_TH SD_WS07 SD_WS07_TH`
2. `{ DoTrigger("global","UNDEFINED SD_WS07_TH SD_WS07 1");; }`

## Specifications

  - Versionmodul (FHEM Module): 3.3.4

https://forum.fhem.de/index.php/topic,97704.0.html
https://forum.fhem.de/index.php?topic=97910.new#new

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/RFD-FHEM/RFFHEM/issues/474 (Autocreate threshhold anpassen).

**Comment by sidey79** [comment]
@elektron-bbs 

Nachdem ich mir den code nun noch angesehen habe, bin ich nicht so sicher, wo das Problem liegt.

Was ich aber feststellen konnte ist, dass autocreate eine definition nicht anlegt, wenn es eine defininition mit diesem Namen bereits gibt.

Wir sollten im Modul wohl prüfen, ob es eine Defininition mit diesem Namen bereits gibt:
https://wiki.fhem.de/wiki/DevelopmentModuleAPI#IsDevice

Ich denke, das Problem kommt dadurch, dass vorher $model mit in $deviceCode enthalten war.
`
		$deviceCode=$model.'_'.$id.$channel;
`
bzw.
`
		$deviceCode = $model . "_" . $channel;
`
Jetzt ist $model nicht mehr enthalten:
`		$deviceCode = $id.$channel;`

`
		$deviceCode = $channel;
`

Ich vermute, die Suche nach dem Device schlägt deshalb fehl, ein neu Anlegen klappt aber nicht, wegen der Namensdoppelung :)
`
    my $def = $modules{SD_WS07}{defptr}{$iohash->{NAME} . "." . $deviceCode};
    $def = $modules{SD_WS07}{defptr}{$deviceCode} if(!$def);
`

**Comment by sidey79** [comment]
@elektron-bbs 

hattest Du schon eine Gelegenheit dir das anzusehen?

**Comment by elektron-bbs** [comment]
Es ist so, wie du vermutest. Ich bin da dran, ein PR zur Bugbeseitigung erfolgt sicher am Wochenende.

Am liebsten würde ich allerdings dieses Protokoll mit in das Modul SD_WS verfrachten.
Das hat nur einen Haken: Das Modul 14_CUL_TCM97001.pm scheint SD_WS07 mit z verwenden:

        # Redirect to
        my $SD_WS07_ClientMatch=index($hash->{Clients},"SD_WS07");

**Comment by sidey79** [comment]
Das migrieren in das SD_WS Modul wird etwas aufwendiger.

Das TCM Modul dispatcht Daten, da die culfw das Protokoll 7 und 0 nicht unterscheidet.

**Comment by sidey79** [comment]
Wenn Du Unterstützung brauchst, dann melde dich einfach.

**Comment by Ralf9** [comment]
> Am liebsten würde ich allerdings dieses Protokoll mit in das Modul SD_WS verfrachten.

Dies finde ich nicht so gut, da sind einige Probleme für den Anwender vorhersehbar.
Es gibt recht viele die das SD_WS07 Modul mit dem CUL benutzen, es gibt auch viele die einen CUL und einen Signalduinio benutzen.
Wenn nun nur ein update vom dev-r34 gemacht wird, ist beim cul der bug noch nicht behoben.
Es sind noch weitere Probleme absehbar.

**Comment by elektron-bbs** [comment]
OK, dann belassen wir es so, wie ist und ich behebe nur den Bug.
