### ISSUE TITLE
Protokoll für Thermo-/Hygrosensor S014

### ISSUE THREAD

**Issue by githubWOG** [RFD-FHEM/RFFHEM#53]
Hardware: Arduino Nano mit 433MHz Superheterodyne
Firmware: V 3.2.0-b5 SIGNALduino - compiled at Dec  2 2015 22:20:56

SIGNALduino/msg READ: ^BMU;P0=244;P1=-280;P2=564;P3=-1867;P4=-3769;D=0123232324232423242323242323242323232423232324232424232324232423232424232423232323232320;CP=2;^C

Der Sender wird von Pimatic (weather8) und Pilight (Conrad) erkannt. Bei Pilight gibt es auch eine Beschreibung des Protokolls.

**Comment by sidey79** [comment]
Hi,

die Meldung passt nicht zum pimatic weather 8 Signal.

Es müssten folgende Werte  Px=(+/-) 200, 1000, 2000, 8000 kommen.
Bei Pilight konnte ich jetzt nichts finden.

**Comment by githubWOG** [comment]
Ohh, sorry, da hab ich mich vertippt. Das Signal wird mit Weather9 in Pimatic richtig decodiert. Und mit folgenden im Pilight. https://wiki.pilight.org/doku.php/tfa_v7_0.

**Comment by sidey79** [comment]
Das verlinkte Protokoll müsste als MS Nachricht empfangen werden.
Zumindest denke ich das.

Kannst Du vielleicht ein paar mehr Logs vom Sensor beisteuern?

**Comment by githubWOG** [comment]
Das Protokoll wird bei mir leider nicht als MS Nachricht empfangen. Immer nur als MU Nachricht.
Hier mal noch ein paar Log Zeilen:

2015.12.05 23:38:54 4: SIGNALduino/msg READ: ^BMU;P0=-244;P1=606;P2=-1856;P3=-3731;D=012121313121212121313121212121312121313121313131212121312121212121213121310;CP=1;^C

2015.12.05 23:38:04 4: SIGNALduino/msg READ: ^BMU;P0=-116;P1=596;P2=-1852;P3=-3723;D=001213121313121213131212121213131212121213121213131213131312121213121212121212131215;CP=1;^C

2015.12.05 23:37:14 4: SIGNALduino/msg READ: ^BMU;P0=224;P1=603;P2=-1849;P3=-3716;D=012121312131312121313121212121313121212121312121313121313131212121312121212121213121314;CP=1;^C

2015.12.05 23:35:34 4: SIGNALduino/msg READ: ^BMU;P0=-1992;P1=-560;P2=136;P3=602;P5=-3759;D=012130353530303535303030303535303030303530303535303535353030303530303030303035303532;CP=3;^C

2015.12.05 23:35:34 4: SIGNALduino/msg READ: ^BMU;P0=597;P1=-1861;P2=-3750;P3=170;P4=-276;P5=-1008;D=343501010201020201010202010101010202010101010201010202010202020101010201010101010102010203;CP=0;^C

2015.12.05 23:33:54 4: SIGNALduino/msg READ: ^BMU;P0=-1449;P1=-352;P2=713;P5=-3709;D=012025202525202025252020202025252020202025202025252025252520202025202020202020252023;CP=2;^C

**Comment by sidey79** [comment]
Nagut, probier mal die aktualisierten Module aus.

Ab verbose 4 erscheint dann folgende Zeile im Log:

2015.12.06 00:03:19 4: SIGNALduino_unknown decoded protocolid:  33 (s014/TFA 30.3200/TCM/Conrad ) mode=auto, sensor id=84, channel=1, temp=794.5, hum=53, bat=critical, crc=0000

Gib doch bitte Rückmeldung ob das mit den Werten (Kanal, Batterie, Temp, Hum und mode passt)
Temp passt vermutlich nicht..

**Comment by githubWOG** [comment]
Ja, es kommen passende Zeilen im Log.
2015.12.06 00:41:24 4: SIGNALduino/msg READ: ^BMU;P0=152;P1=600;P2=-1852;P3=-5015;D=012131213131212131312121212121313121212131212131312131313121212131212121212131312121301;CP=1;^C
2015.12.06 00:41:24 5: sduino: applying filterfunc SIGNALduino_filterSign
2015.12.06 00:41:24 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 00:41:24 5: sduino: Starting demodulation at Position 2
2015.12.06 00:41:24 5: dispatching bits: 1 0 1 1 0 0 1 1 0 0 0 0 0 1 1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0
2015.12.06 00:41:24 4: decoded matched MU Protocol id 33 dmsg u33#B30626E20C8 length 44
2015.12.06 00:41:24 5: converted Data to (u33#B30626E20C8)
2015.12.06 00:41:24 5: Triggering sduino (1 changes)
2015.12.06 00:41:24 5: Notify loop for sduino Initialized
2015.12.06 00:41:24 5: sduino dispatch u33#B30626E20C8
2015.12.06 00:41:24 4: SIGNALduino_unknown incomming msg: u33#B30626E20C8
2015.12.06 00:41:24 4: SIGNALduino_unknown rawData: B30626E20C8
2015.12.06 00:41:24 4: SIGNALduino_unknown Protocol: 33
2015.12.06 00:41:24 4: SIGNALduino_unknown converted to bits: 10110011000001100010011011100010000011001000
2015.12.06 00:41:24 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=manual, sensor id=716, channel=1, temp=97.1111111111111, hum=136, bat=ok, crc=1100

2015.12.06 00:42:14 4: SIGNALduino/msg READ: ^BMU;P0=-3758;P1=-1540;P2=147;P3=-256;P4=586;D=123232341414041404041414040414141414140414041414041414040414040404141414041414141414140404142;CP=4;^C
2015.12.06 00:42:14 5: sduino: applying filterfunc SIGNALduino_filterSign
2015.12.06 00:42:14 4: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2015.12.06 00:42:14 5: sduino: Starting demodulation at Position 1
2015.12.06 00:42:14 4: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2015.12.06 00:42:14 5: sduino: Starting demodulation at Position 1
2015.12.06 00:42:14 4: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2015.12.06 00:42:14 5: sduino: Starting demodulation at Position 1
2015.12.06 00:42:14 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 00:42:14 5: sduino: Starting demodulation at Position 2
2015.12.06 00:42:14 5: dispatching bits: 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0
2015.12.06 00:42:14 4: decoded matched MU Protocol id 33 dmsg u33#2CC149B8818 length 44
2015.12.06 00:42:14 5: converted Data to (u33#2CC149B8818)
2015.12.06 00:42:14 5: Triggering sduino (1 changes)
2015.12.06 00:42:14 5: Notify loop for sduino Initialized
2015.12.06 00:42:14 5: sduino dispatch u33#2CC149B8818
2015.12.06 00:42:14 4: SIGNALduino_unknown incomming msg: u33#2CC149B8818
2015.12.06 00:42:14 4: SIGNALduino_unknown rawData: 2CC149B8818
2015.12.06 00:42:14 4: SIGNALduino_unknown Protocol: 33
2015.12.06 00:42:14 4: SIGNALduino_unknown converted to bits: 00101100110000010100100110111000100000011000
2015.12.06 00:42:14 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=manual, sensor id=179, channel=0, temp=19.6111111111111, hum=46, bat=ok, crc=0001

2015.12.06 00:43:04 4: SIGNALduino/msg READ: ^BMU;P0=638;P2=-1840;P3=-3857;P5=168;D=00202030203030202030302020202020302030202030202030302030303020202030202020202020303020352;CP=0;^C
2015.12.06 00:43:04 5: sduino: applying filterfunc SIGNALduino_filterSign
2015.12.06 00:43:04 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 00:43:04 5: sduino: Starting demodulation at Position 2
2015.12.06 00:43:04 5: dispatching bits: 0 1 0 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0
2015.12.06 00:43:04 4: decoded matched MU Protocol id 33 dmsg u33#59829371034 length 44
2015.12.06 00:43:04 5: converted Data to (u33#59829371034)
2015.12.06 00:43:04 5: Triggering sduino (1 changes)
2015.12.06 00:43:04 5: Notify loop for sduino Initialized
2015.12.06 00:43:04 5: sduino dispatch u33#59829371034
2015.12.06 00:43:04 4: SIGNALduino_unknown incomming msg: u33#59829371034
2015.12.06 00:43:04 4: SIGNALduino_unknown rawData: 59829371034
2015.12.06 00:43:04 4: SIGNALduino_unknown Protocol: 33
2015.12.06 00:43:04 4: SIGNALduino_unknown converted to bits: 01011001100000101001001101110001000000110100
2015.12.06 00:43:04 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=manual, sensor id=358, channel=0, temp=121.222222222222, hum=76, bat=ok, crc=0011

Der zweite Eintrag sollte passen. Bei den anderen beiden denke ich ist das Signal nicht von Anfang an.

**Comment by sidey79** [comment]
Ja, das könnte sein.
Kannst Du auch mal Batteriewechsel probieren?

Mich würde ich interessieren, ob Position 10-11 immer 11 sind. Daran könnte man prinzipiell erkennen, ob das Signal von Anfang erkannt wurde.

Dazu dann noch einen Längencheck.
Aus dem CRC bin ich noch nicht schlau geworden.

Bitte auch mal den Kanal wechseln und sofern vorhanden manuell und automatisch senden lassen.

**Comment by githubWOG** [comment]
So hier nun mal ein paar weitere Logeinträge. Ich habe mal die Logausgabe von Pimatic zu den zugehörigen Meßreihen drüber eingefügt.

Manual (TX Button)

debug [pimatic-homeduino]: weather9: { id: 21, channel: 2, temperature: 24.9, humidity: 52, lowBattery: true, sync: true }
21:11:37debug [pimatic-homeduino]: weather3: { id: 84, channel: 2, temperature: 24.9, humidity: 52 }
21:11:37debug [pimatic-homeduino]: received: [ 540, 1904, 3792, 7596 ] 01010102010201020101010201020102010202010101010202010102010101010202020201020102020203

2015.12.06 21:11:26 5: sduino: Starting demodulation at Position 2
2015.12.06 21:11:36 4: SIGNALduino/msg READ: MU;P0=135;P1=-168;P2=620;P3=-1856;P4=-4974;D=0012323232423242324232323242324232423242423232323242423232423232323242424242324232424242405;CP=2;
2015.12.06 21:11:37 5: sduino: applying filterfunc SIGNALduino_filterSign
2015.12.06 21:11:37 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 21:11:37 5: sduino: Starting demodulation at Position 2
2015.12.06 21:11:37 5: dispatching bits: 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 0
2015.12.06 21:11:37 4: decoded matched MU Protocol id 33 dmsg u33#15156190F5E length 44
2015.12.06 21:11:37 5: converted Data to (u33#15156190F5E)
2015.12.06 21:11:37 5: Triggering sduino (1 changes)
2015.12.06 21:11:37 5: Notify loop for sduino Initialized
2015.12.06 21:11:37 5: sduino dispatch u33#15156190F5E
2015.12.06 21:11:37 4: SIGNALduino_unknown incomming msg: u33#15156190F5E
2015.12.06 21:11:37 4: SIGNALduino_unknown rawData: 15156190F5E
2015.12.06 21:11:37 4: SIGNALduino_unknown Protocol: 33
2015.12.06 21:11:37 4: SIGNALduino_unknown converted to bits: 00010101000101010110000110010000111101011110
2015.12.06 21:11:37 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=auto, sensor id=84, channel=1, temp=24.9444444444444, hum=52, bat=critical, crc=0101


Auto
debug [pimatic-homeduino]: weather9: { id: 21, channel: 2, temperature: 24.8, humidity: 41, lowBattery: false, sync: true }
21:12:46debug [pimatic-homeduino]: weather3: { id: 84, channel: 2, temperature: 24.8, humidity: 41 }
21:12:45debug [pimatic-homeduino]: received: [ 544, 1900, 3784, 7608 ] 01010102010201020101020101020101020202010101010202010201010201010201010201020102020103

2015.12.06 21:12:45 5: sduino: Starting demodulation at Position 1
2015.12.06 21:12:45 4: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2015.12.06 21:12:45 5: sduino: Starting demodulation at Position 1
2015.12.06 21:12:45 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 21:12:45 5: sduino: Starting demodulation at Position 2
2015.12.06 21:12:45 5: dispatching bits: 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0
2015.12.06 21:12:45 4: decoded matched MU Protocol id 33 dmsg u33#2A49C3492B0 length 44
2015.12.06 21:12:45 5: converted Data to (u33#2A49C3492B0)
2015.12.06 21:12:45 5: Triggering sduino (1 changes)
2015.12.06 21:12:45 5: Notify loop for sduino Initialized
2015.12.06 21:12:45 5: sduino dispatch u33#2A49C3492B0
2015.12.06 21:12:45 4: SIGNALduino_unknown incomming msg: u33#2A49C3492B0
2015.12.06 21:12:45 4: SIGNALduino_unknown rawData: 2A49C3492B0
2015.12.06 21:12:45 4: SIGNALduino_unknown Protocol: 33
2015.12.06 21:12:45 4: SIGNALduino_unknown converted to bits: 00101010010010011100001101001001001010110000
2015.12.06 21:12:45 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=manual, sensor id=169, channel=2, temp=117.5, hum=66, bat=critical, crc=1011

Kanalwechsel 2 --> 3

Manuel (TX Button)

debug [pimatic-homeduino]: weather9: { id: 21, channel: 3, temperature: 21.6, humidity: 41, lowBattery: true, sync: true }
21:21:14debug [pimatic-homeduino]: weather3: { id: 84, channel: 3, temperature: 21.6, humidity: 41 }
21:21:14debug [pimatic-homeduino]: received: [ 528, 1916, 3792, 7584 ] 01010102010201020101020102010201010201020101010202010201010201010201020202010101020103

2015.12.06 21:21:14 5: sduino: Starting demodulation at Position 1
2015.12.06 21:21:14 4: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2015.12.06 21:21:14 5: sduino: Starting demodulation at Position 1
2015.12.06 21:21:14 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 21:21:14 5: sduino: Starting demodulation at Position 2
2015.12.06 21:21:14 5: dispatching bits: 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 0 0 0
2015.12.06 21:21:14 4: decoded matched MU Protocol id 33 dmsg u33#54A94692E28 length 44
2015.12.06 21:21:14 5: converted Data to (u33#54A94692E28)
2015.12.06 21:21:14 5: Triggering sduino (1 changes)
2015.12.06 21:21:14 5: Notify loop for sduino Initialized
2015.12.06 21:21:14 5: sduino dispatch u33#54A94692E28
2015.12.06 21:21:14 4: SIGNALduino_unknown incomming msg: u33#54A94692E28
2015.12.06 21:21:14 4: SIGNALduino_unknown rawData: 54A94692E28
2015.12.06 21:21:14 4: SIGNALduino_unknown Protocol: 33
2015.12.06 21:21:14 4: SIGNALduino_unknown converted to bits: 01010100101010010100011010010010111000101000
2015.12.06 21:21:14 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=manual, sensor id=338, channel=2, temp=75.6111111111111, hum=180, bat=critical, crc=0010

Auto

debug [pimatic-homeduino]: weather9: { id: 21, channel: 3, temperature: 22.3, humidity: 40, lowBattery: false, sync: true }
21:24:26debug [pimatic-homeduino]: weather3: { id: 84, channel: 3, temperature: 22.3, humidity: 40 }
21:24:26debug [pimatic-homeduino]: received: [ 540, 1900, 3788, 7608 ] 01010102010201020101020102010102020101020102010202010201010101010201010202010201010203

2015.12.06 21:24:25 5: sduino: applying filterfunc SIGNALduino_filterSign
2015.12.06 21:24:25 4: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2015.12.06 21:24:25 5: sduino: Starting demodulation at Position 1
2015.12.06 21:24:25 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 21:24:25 5: sduino: Starting demodulation at Position 2
2015.12.06 21:24:25 5: dispatching bits: 0 0 0 1 0 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0
2015.12.06 21:24:25 4: decoded matched MU Protocol id 33 dmsg u33#152995A09A4 length 44
2015.12.06 21:24:25 5: converted Data to (u33#152995A09A4)
2015.12.06 21:24:25 5: Triggering sduino (1 changes)
2015.12.06 21:24:25 5: Notify loop for sduino Initialized
2015.12.06 21:24:25 5: sduino dispatch u33#152995A09A4
2015.12.06 21:24:25 4: SIGNALduino_unknown incomming msg: u33#152995A09A4
2015.12.06 21:24:25 4: SIGNALduino_unknown rawData: 152995A09A4
2015.12.06 21:24:25 4: SIGNALduino_unknown Protocol: 33
2015.12.06 21:24:25 4: SIGNALduino_unknown converted to bits: 00010101001010011001010110100000100110100100
2015.12.06 21:24:25 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=auto, sensor id=84, channel=2, temp=22.3333333333333, hum=40, bat=ok, crc=1010

**Comment by githubWOG** [comment]
Ich hab die neue Version getestet. Es werden aber nicht alle Bits erkannt.

2015.12.06 22:04:40 5: sduino: Starting demodulation at Position 1
2015.12.06 22:04:40 4: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2015.12.06 22:04:40 5: sduino: Starting demodulation at Position 1
2015.12.06 22:04:40 4: Fingerprint for MU Protocol id 33 -> weathe331 matches, trying to demodulate
2015.12.06 22:04:40 5: sduino: Starting demodulation at Position 2
2015.12.06 22:04:40 5: dispatching bits: 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 1 1 0 1 0 0 1 1 1 1 0 1 1 1 0 0 0 0 0
2015.12.06 22:04:40 4: decoded matched MU Protocol id 33 dmsg u33#2A28A369EE0 length 44
2015.12.06 22:04:40 5: converted Data to (u33#2A28A369EE0)
2015.12.06 22:04:40 5: Triggering sduino (1 changes)
2015.12.06 22:04:40 5: Notify loop for sduino Initialized
2015.12.06 22:04:40 5: sduino dispatch u33#2A28A369EE0
2015.12.06 22:04:40 4: SIGNALduino_unknown incomming msg: u33#2A28A369EE0
2015.12.06 22:04:40 4: SIGNALduino_unknown rawData: 2A28A369EE0
2015.12.06 22:04:40 4: SIGNALduino_unknown Protocol: 33
2015.12.06 22:04:40 4: SIGNALduino_unknown converted to bits: 00101010001010001010001101101001111011100000
2015.12.06 22:04:40 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=manual, sensor id=168, channel=2, temp=124.333333333333, hum=122, bat=critical, crc=1110

Empfangene Bits: 00101010001010001010001101101001111011100000
Richtig wäre: 000101010001010001010001101101001111011100000

**Comment by sidey79** [comment]
Da fehlt das 1. Bit und alles ist dadurch kaputt. Hängen beide am gleichen Empfänger oder wie lässt du beides im Moment parallel laufen?

**Comment by githubWOG** [comment]
Nee, ich habe zwei Empfänger an jeweils einem Raspi. Jeweils ein Arduino Nano einmal mit Signalduino und einmal mit Pimatic-Homeduino.

**Comment by sidey79** [comment]
Dann verstehe ich nicht, weshalb manchmal das 1. Bit fehlt. Das sollte eigentlich nur passieren, wenn der Empfänger etwas nicht empfangen hat.

Hast Du die Nanos schon mal getauscht? Also Homeduino zu SIGNALduino und umgekeht.

Oder einfach mal die Sendemodule tauschen? Man kann in FHEM mehr Prüfungen einbauen um solche fehlerhaften Signale zu verwerfen, aber grundsätzlich müssten beide ja gleich gut empfangen können.

Grüße Sidey

**Comment by githubWOG** [comment]
Hallo Sidey,
du hattest Recht. Ich habe nun mal die Empfänger getauscht und die Signale werden MS empfangen. Ich dachte nicht das da so ein großer Unterschied bei der Empfangsqualität der beiden Empfänger vorhanden ist. (sehen ja fast genauso aus)
Hier mal Logauszüge der  der beiden Sender:
2015.12.09 22:12:33 4: SIGNALduino/msg READ: MS;P0=529;P1=-7580;P2=-1902;P3=-3771;D=01020202030203020202030202020302030302030303020203020303020303020203020202020203020203;CP=0;SP=1;O;
2015.12.09 22:13:59 4: SIGNALduino/msg READ: MS;P0=548;P1=-7610;P2=-1890;P3=-3768;D=01020203020303020203030202020203030303030302030203020303030203020203020202030203030203;CP=0;SP=1;O;
2015.12.09 22:21:22 4: SIGNALduino/msg READ: MS;P0=609;P2=-7568;P3=-1897;P4=-3777;D=02030303040304030303040303030403040304040404030304030404040303030304030303030304030404;CP=0;SP=2;O;
2015.12.09 22:24:01 4: SIGNALduino/msg READ: MS;P2=530;P3=-7572;P4=-1890;P5=-3775;D=23242424252425242424252424242524252425252525242425242525252424242425242424242425242525;CP=2;SP=3;O;
2015.12.09 22:25:40 4: SIGNALduino/msg READ: MS;P0=543;P1=-7586;P2=-1891;P3=-3779;D=01020203020303020203030202020202020202030303020203020303030302020203020202030202020202;CP=0;SP=1;O;
2015.12.09 22:33:09 4: SIGNALduino/msg READ: MS;P0=545;P1=-7589;P2=-1887;P3=-3775;D=01020203020303020203030202020202020202030303020203020303030302020203020202020202020302;CP=0;SP=1;O;

**Comment by sidey79** [comment]
Das wird immer seltsamer, aber für mich ist es erklärbar, wieso es als MS und nicht mehr als MU gewertet wird.

Welche Bezeichnung haben deine Empfänger, sind es die RXB-6 oder ein YK-MK-5V ?

**Comment by githubWOG** [comment]
Das eine ist ein RXB-6 das andere ist der Empfänger aus dem Transceiver Module Set RT056.

**Comment by sidey79** [comment]
ok, bitte noch mal mit der aktuellen Version probieren

**Comment by githubWOG** [comment]
Meine Sensoren werden nun sehr gut erkannt.
Hier ein Auszug aus dem Logfile für beide Sensoren:
Sensor1:
2015.12.14 12:35:38 4: SIGNALduino/msg READ: MS;P0=898;P4=-32001;P5=108;D=0455;CP=0;SP=4;
2015.12.14 12:35:46 4: SIGNALduino/msg READ: MU;P0=-1680;P2=120;P3=-3755;P4=553;D=002340404340434340404343404040404043404340404343404343404343404040404340404040404343434041;CP=4;
2015.12.14 12:35:46 5: sduino: applying filterfunc SIGNALduino_filterSign
2015.12.14 12:35:46 4: SIGNALduino/msg READ: MS;P0=549;P1=-7583;P2=-1896;P3=-3777;D=01020203020303020203030202020202030203020203030203030203030202020203020202020203030302;CP=0;SP=1;O;
2015.12.14 12:35:46 4: Founded matched MS Protocol id 33 -> weather33
2015.12.14 12:35:46 5: Starting demodulation at Position 2
2015.12.14 12:35:46 4: Decoded matched MS Protocol id 33 dmsg u33#2CC14DB0838 length 44
2015.12.14 12:35:46 5: converted Data to (u33#2CC14DB0838)
2015.12.14 12:35:46 5: Triggering sduino (1 changes)
2015.12.14 12:35:46 5: Notify loop for sduino Initialized
2015.12.14 12:35:46 5: sduino dispatch u33#2CC14DB0838
2015.12.14 12:35:46 4: SIGNALduino_unknown incomming msg: u33#2CC14DB0838
2015.12.14 12:35:46 4: SIGNALduino_unknown rawData: 2CC14DB0838
2015.12.14 12:35:46 4: SIGNALduino_unknown Protocol: 33
2015.12.14 12:35:46 4: SIGNALduino_unknown converted to bits: 00101100110000010100110110110000100000111000
2015.12.14 12:35:46 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=auto, sensor id=179, channel=1, temp=20.5, hum=44, bat=critical, crc=0011, sync=false, unkown3=0
Sensor2:
2015.12.14 12:37:37 5: sduino: Starting demodulation at Position 1
2015.12.14 12:37:37 4: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2015.12.14 12:37:37 5: sduino: Starting demodulation at Position 2
2015.12.14 12:37:38 4: SIGNALduino/msg READ: MS;P0=532;P1=-7580;P2=-1897;P3=-3772;D=01020202030203020202030302020302030203020203020203030203030302020203020202020202030303;CP=0;SP=1;O;
2015.12.14 12:37:38 4: Founded matched MS Protocol id 33 -> weather33
2015.12.14 12:37:38 5: Starting demodulation at Position 2
2015.12.14 12:37:38 4: Decoded matched MS Protocol id 33 dmsg u33#146549B881C length 44
2015.12.14 12:37:38 5: converted Data to (u33#146549B881C)
2015.12.14 12:37:38 5: Triggering sduino (1 changes)
2015.12.14 12:37:38 5: Notify loop for sduino Initialized
2015.12.14 12:37:38 5: sduino dispatch u33#146549B881C
2015.12.14 12:37:38 4: SIGNALduino_unknown incomming msg: u33#146549B881C
2015.12.14 12:37:38 4: SIGNALduino_unknown rawData: 146549B881C
2015.12.14 12:37:38 4: SIGNALduino_unknown Protocol: 33
2015.12.14 12:37:38 4: SIGNALduino_unknown converted to bits: 00010100011001010100100110111000100000011100
2015.12.14 12:37:38 4: SIGNALduino_unknown decoded protocolid: 33 (s014/TFA 30.3200/TCM/Conrad ) mode=auto, sensor id=81, channel=2, temp=19.6111111111111, hum=46, bat=critical, crc=0001, sync=false, unkown3=0

**Comment by sidey79** [comment]
Das sieht ja schon mal sehr gut aus.
Jetzt bleibt nur noch das Rätsel mit dem CRC, das habe ich noch nicht heraus gefunden, wie der berechnet wird.

**Comment by sidey79** [comment]
ähnlich Tchibo TCM 269250 Außensender:
https://forum.fhem.de/index.php?topic=68560.new;topicseen#new


Nur die Batteriewerte stimmen nicht
