### ISSUE TITLE
not webCmd - wegen "Information menu" !? failed DeviceOverview

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#545]
## Expected Behavior
- definiertes webCmd attribut für Schnellzugriff in Detailansicht vom Empfänger

## Actual Behavior
- nach setzen vom Attribut webCmd erfolgt keine Ansicht der gesetzen Kommandos

## Steps to Reproduce the Problem

  1. set attrib webCmd 
  2.
  3.

Den Fehler konnte ich soweit eingrenzen, das wenn hash->{FW_detailFn} verwendet wird, die dortige eigendlicht Anzeige nicht mehr erfolgt. :-(

Bei den Devices nennt sich die Zeile wo das Icon dargestellt wird, DeviceOverview.

Zitat Wiki:
_Es stehen für alle Geräte in FHEM folgende Attribute zur Verfügung, die sich teilweise wechselseitig beeinflussen und überlagern..._

Mit dem jetzigen Verhalten ist das ein Wiederspruch!

## Specifications

  - Microcontroller:
  - Version (Firmware):
V 3.3.1-RC-nightly SIGNALduino cc1101 (chip CC1101) - compiled at Feb 3 2019 21:35:11
  - Versionmodul (FHEM Module):
v3.4.0_dev_08.03

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

**Comment by HomeAutoUser** [comment]
Das ganze liegt an dem fehlenden Eintrag

`$hash->{FW_deviceOverview} = 1;`

entweder wir nehmen diesen fest herein oder ggf abschaltbar via Attribut.
Was meint Ihr @sidey79  @Ralf9 ?

**Comment by sidey79** [comment]
Verstehe ich es richtig, dass in der Raumansicht alles passt aber in der Detailansicht fehlt der durch webcmd definierte Eintrag?

**Comment by HomeAutoUser** [comment]
Das rot markierte fehlt wo das webCmd dargestellt wird wenn `$hash->{FW_deviceOverview} = 1;` nicht ergänzt wird.

![Unbenannt](https://user-images.githubusercontent.com/25631927/54232825-e0cd0480-450b-11e9-980f-af09228d9fb3.jpg)

**Comment by sidey79** [comment]
Ja `$hash->{FW_deviceOverview} = 1` blendet in der Detailansicht die Zeile mit DeviceOverview ein. Da Du es schon eingefügt hast, machst Du bestimmt einen PR oder?

**Comment by sidey79** [comment]
Details finden sich in diesem Thread:

https://forum.fhem.de/index.php?topic=71772.0
