### ISSUE TITLE
PERL WARNING - 14_SD_RSL.pm - need fix

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#551]
## Expected Behavior
- fix PERL WARNING - no more WARNING 

## Actual Behavior
`2019.03.18 05:07:39 1: PERL WARNING: "my" variable $iodevice masks earlier declaration in same scope at ./FHEM/14_SD_RSL.pm line 106.`

## Steps to Reproduce the Problem

  1. bei einem Empfang für das Modul
  2.
  3.

## Specifications

  - Microcontroller:
  - Version (Firmware):
V 3.3.1-RC-nightly SIGNALduino cc1101 (chip CC1101) - compiled at Feb 3 2019 21:35:11
  - Versionmodul (FHEM Module):
v3.4.0_dev_16.03

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/156 (PERL WARNING - Sammlung | dev-r33), https://github.com/RFD-FHEM/RFFHEM/issues/272 (PERL WARNING: Use of uninitialized - line 1234), https://github.com/RFD-FHEM/RFFHEM/issues/277 (PERL WARNING: Use of uninitialized - line 2456), https://github.com/RFD-FHEM/RFFHEM/issues/314 (00_SIGNALduino.pm - FHT80 - WARNING after fhem-5.9 install - Data aus SVN), and https://github.com/RFD-FHEM/RFFHEM/issues/381 (00_SIGNALduino.pm MU: matching of start pattern: wrong? clarification/docs needed!!).
