### ISSUE TITLE
SD_WS_33 - Frage an die Perl-Experten

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#552]
Beim Test der Prüfroutine von @cxxcoder in https://github.com/RFD-FHEM/SIGNALDuino/issues/113#issuecomment-474477140 taucht eine Merkwürdigkeit auf: Starte ich FHEM neu, erscheinen laufend CRC-Errors, reloade ich nur das Modul 14_SD_WS.pm, funktioniert alles wie gewollt.
Bei genauerer Betrachtung der Ausgaben, stellte ich fest, das offensichtlich das "reverse" in dieser Zeile nicht verarbeitet wird:
SD_WS_bin2dec(reverse(substr($bitData, 38, 4)))
Ich habe mir dann ein kleines Testscript geschrieben:

#!/usr/bin/perl
use strict;
use warnings;

my $bitData = "0010";

print "################# S T A R T ##################\n";

my $test = SD_WS_bin2dec(reverse(substr($bitData, 0, 4)));
print "Test 1: $test\n";

$test = SD_WS_bin2dec(substr($bitData, 0, 4));
print "Test 2: $test\n";

$test = reverse(substr($bitData, 0, 4));
$test = SD_WS_bin2dec($test);
print "Test 3: $test\n";

sub SD_WS_bin2dec($)
    {
      my $h = shift;
      my $int = unpack("N", pack("B32",substr("0" x 32 . $h, -32))); 
      return sprintf("%d", $int); 
    }

Die Ausgabe davon ist dann folgende:

bbs:/opt/fhem/SignalDuino# ./test9.pm
main::SD_WS_bin2dec() called too early to check prototype at ./test9.pm line 11.
main::SD_WS_bin2dec() called too early to check prototype at ./test9.pm line 14.
main::SD_WS_bin2dec() called too early to check prototype at ./test9.pm line 18.
################# S T A R T ##################
Test 1: 2
Test 2: 2
Test 3: 4

Test 1 und 2 sollte aber nicht das gleiche Ergebnis liefern. Nach Recherchen im Internet bin ich darauf gestossen, das man die sub SD_WS_bin2dec vor die anderen subs packen müsste, oder eine Zeile vor dem restlichen Code einfügen sollte:

sub SD_WS_bin2dec($);

Dann kommt auch das richtige Ergebnis ohne Fehlermeldungen:

bbs:/opt/fhem/SignalDuino# ./test9.pm
################# S T A R T ##################
Test 1: 4
Test 2: 2
Test 3: 4

Welche Variante ist die richtige?

**Comment by sidey79** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @sidey79.

Possibly related issues are https://github.com/RFD-FHEM/RFFHEM/issues/551 (PERL WARNING - 14_SD_RSL.pm - need fix), and https://github.com/RFD-FHEM/RFFHEM/issues/498 (preamble bei Modulen die mehrere Protokolle unterstützen).

**Comment by sidey79** [comment]
Beide sind richtig, keine ist falsch.

Ich würde die Variante mit der Forward Declaration nehmen.

Ansonsten, sollten wir derartige Funktionen auch eher Mal in eine Bibliothek Auslagern.
Die haben wir ja mehrfach ;)

**Comment by elektron-bbs** [comment]
Welche Subs sollten dann vorher deklariert werden? Bisher scheint ja auch alles ohne Fehler funktioniert zu haben. In der SIGNALduino.pm sind nur einige deklariert und in der fhem.pl wahrscheinlich alle.

**Comment by sidey79** [comment]
Tia, einfach alle vorher deklarieren, welche innerhalb des Modules selbst aufgerufen werden. Das ist glaube ich eine einfache Faustregel, die immer zum gewünschten Ergebnis führt.
