### ISSUE TITLE
neues Attribut userprotocol

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#561]
Momentan muß, wenn ein Anwender ein neues Protokoll testen soll, vom Anwender die SD_ProtocolData.pm ersetzt und fhem neu gestartet werden.
Wenn wir ein neues Attribut "userprotocol" einführen, dann muss zum Testen die SD_ProtocolData.pm nicht mehr ersetzt werden.
In das neue Attribut "userprotocol" wird die neue Protokolldefinition als json String eingetragen.
Z.B. bei der ID 95 sieht der json String so aus:
`{"name":"Techmar", "id":"95", "one":[1,-0.6], "zero":[1,-1.2], "start":[1,-1.8], "clockabs":"550", "format":"twostate", "preamble":"P95#", "clientmodule":"SD_UT", "length_min":"50", "length_max":"50"}`

Das erzeugen des json String kann in das 88_SIGNALduino_TOOL.pm eingebaut werden.

Der Code in der "sub SIGNALduino_Attr" sieht ungefähr so aus. Ist noch nicht fertig.

```
	elsif ($aName eq "userProtocol")
	{
		my $decoded = eval { decode_json($aVal) };
		SIGNALduino_Log3 $name, 3, "$name Attr: userProtocol " . Dumper($decoded);	# nur zum Test
		my $id = $decoded->{id};
		foreach my $field (keys %{$decoded}) {
			SIGNALduino_Log3 $name, 3, "$name Attr: userProtocol Field=$field : " . $decoded->{$field};	# nur zum Test
			$ProtocolListSIGNALduino{$id}{$field} = $decoded->{$field};
		}
	}
```

**Comment by sidey79** [comment]
Können wir die Userprotokolle nicht genauso einlesen wie wir es bei den Protocol hash Modul machen?

**Comment by Ralf9** [comment]
Das Userprotokoll sollte ohne eine extra Datei funktionieren.
Wenn in das Attribut "userprotocol"  ein json String mit einer vorhandenen ID eingetragen wird, dann kann eine bereits vorhandene Protokolldefinition geändert werden.

**Comment by sidey79** [comment]
Ich meine auch nicht eine Datei auf dem Dateisystem verwenden, sondern die Methoden zum Einlesen eines Packages

**Comment by HomeAutoUser** [comment]
Ich verfolge das ganze Thema auch und überlege wie anfällig die Variante wohl ist.

1) was passiert wenn der Syntax beim JSON nicht eingehalten wird vom User? Leerzeichen, Zeilenumbrüche, verdeckte Zeichen..

2) wie lange ist das Attribut gültig wenn ich 2 Protokolle auf einmal benötige? Geht das dann auch noch?

3) was passiert wenn ein Protokoll definiert wurde und ein selbiges in der OrginalDatei hinzukommt?

X) was spricht dagegen die Anpassungen wie bisher in der Datei vorzunehmen?

**Comment by sidey79** [comment]
Meine Überlegungen dazu:

1) Das können wir anfangen. Das Protokoll wird dann aber nicht funktionieren!

2) Wenn wir die Syntax aus dem Protokoll Hash nehmen können wir auch mehrere Protokolle verwenden. Bei den IDs sollten wir uns was überlegen dass es nicht zu Doppelungen kommt.

3) Es wird ein Oberweite vorgenommen würde ich sagen.

Gegen eine Anpassung in dem Protokoll Hash spricht, dass individuelle Packages mit der gleichen Version existieren.
Das wird unübersichtlich und ist inkompatibel mit dem Fhem Update.

Anstelle in dem Attribut die Protokolle direkt zu adressieren könnten wir auch ein Package via HTTP nach laden. Der Anwender müsste dann nur eine URL angeben.
Die kann von uns kommen oder er legt sich selbst eine Datei irgendwo an.

**Comment by Ralf9** [comment]
> was passiert wenn der Syntax beim JSON nicht eingehalten wird vom User? Leerzeichen, Zeilenumbrüche, verdeckte Zeichen..

Syntaxfehler werden durch "eval" abgefangen. Der JSON String soll nicht vom user erstellt werden.
Dieser wird durch uns erstellt, der user muß den JSON String nur ins userprotocol Attribut kopieren.

Es wäre dabei hilfreich, wenn vom Modul durch Eingabe der ID, von einer bestehenden Protokolldefinition der JSON String erzeugt und in einem Fenster ausgegeben werden könnte. Z.B. durch einen weiteren Eintrag im Information menu.

Durch Trennung mit einem Komma müssten auch mehrere Protokolle möglich sein.

> Das können wir anfangen. Das Protokoll wird dann aber nicht funktionieren!

Warum sollte das Protokoll nicht funktionieren?

> Bei den IDs sollten wir uns was überlegen dass es nicht zu Doppelungen kommt.

Eine Möglichkeit wäre die Userprotokolle auf einen bestimmten ID Bereich zu begrenzen und den Bereich mit Konstanten zu definieren. Z.B.:
```
SDUINO_USERPROTOCOL_ID_MIN => 900,
SDUINO_USERPROTOCOL_ID_MAX => 909,
```




> Anstelle in dem Attribut die Protokolle direkt zu adressieren könnten wir auch ein Package via HTTP nach laden. Der Anwender müsste dann nur eine URL angeben.

Dies ist nicht so einfach zu realisieren, die Probleme stecken im Detail. Möchtest Du bei jedem Fhem neustart das Package via HTTP nach laden? 
Möchtest Du einzelne Protokolle oder den ganzen Protokollhash nachladen?
Was passiert, wenn beim neustart das Internet nicht verfügbar ist?

**Comment by Ralf9** [comment]
Ich habe es mal so abgeändert, daß im Attribut userProtocol auch mehr als ein Protokoll eingetragen werden kann. Es fehlt noch die Abfrage ob die IDs in zulässigen Bereich sind. 

`[{"clientmodule":"SD_WS","clockabs":"500","format":"twostate","id":"933","length_max":"44","length_min":"42","name":"weather33","one":["1","-8"],"preamble":"W33#","start":["1","-16"],"zero":["1","-4"]}, {"name":"Techmar", "id":"995", "one":[1,-0.6], "zero":[1,-1.2], "start":[1,-1.8], "clockabs":"550", "format":"twostate", "preamble":"P95#", "clientmodule":"SD_UT", "length_min":"50", "length_max":"50"}]`


```
	elsif ($aName eq "userProtocol")
	{
		my $id;
		my @decoded = eval { @{decode_json($aVal)} };
		#SIGNALduino_Log3 $name, 3, "$name Attr: userProtocol " . Dumper(@decoded);
		for my $nr (0 .. $#decoded) {
			$id = $decoded[$nr]->{id};
			$ProtocolListSIGNALduino{$id} = $decoded[$nr];
		}
	}
```

Und mit diesen neuen Eintrag bei get kann eine Protokoll ID als json ausgegeben werden:
```
  elsif ($a[1] eq "protocolIdToJson")
  {
	my $ret;
	$arg = 0 if ($arg eq "");
	if (exists($ProtocolListSIGNALduino{$arg})) {
		my %idHash = %{$ProtocolListSIGNALduino{$arg}};
		$ret = toJSON(\%idHash);
		SIGNALduino_Log3 $name, 3, "$name: get protocolIdToJson: $ret";
	}
	else {
		$ret = "ID=$arg not exists!";
	}
	return "$a[1]: \n\n$ret\n";
  }
```

**Comment by HomeAutoUser** [comment]
@Ralf9
die Ideen sind gut, nur bitte nicht mehrere Dinge in einem Issues verschachteln bitte. So verlieren wir komplett den Durchblick und beim auseinander setzen bzw / argumentieren oder diskutieren vermischt man schnell die Themen.

1) Attribut Protokoll
2) get Befehl

2) was genau gibt der Dir aus?

**Comment by Ralf9** [comment]
Der get Befehl gibt die ausgewählte Protokolldefinition als JSON String aus.
Ich habe es noch erweitert, daß es auch besser lesbar angezeigt wird, ich weiß noch nicht wie ich ein Array anzeige.
![protcolIdToJson](https://user-images.githubusercontent.com/14318704/56091490-e1acd980-5eaf-11e9-941a-2fa4046f7122.png)

**Comment by HomeAutoUser** [comment]
@Ralf9, wenn ich dich richtig verstehe, so zeigst du immer nur die Ausgabe an, welche für den User bestimmt ist und welche wir somit weitergeben? richtig?

> ich weiß noch nicht wie ich ein Array anzeige.

Mit Dumper\... könntest du es mal probieren. Das sollte auf jedenfall gehen.

>Der get Befehl gibt die ausgewählte Protokolldefinition als JSON String aus.

Wie wählst du diese option aus? get Auswahl oder worauf bezieht sich dein get Befehl?

**Comment by Ralf9** [comment]
Es wird die ausgewählte Protokolldefinition als JSON String ausgegeben, damit es keine Probleme mit doppelten IDs geben kann, ist evtl sinnvoll vor der Weitergabe die ID zu ändern, z.B. auf 900.
Das Attribut userProtocol kann auch zum entwickeln verwendet werden, damit können ohne ein modul restart Protokolldefinitionen kopiert und verändert werden 

In das Eingabefeld hinter get wird die gewünschte ID eingegeben.

**Comment by Ralf9** [comment]
Ich habe es inzwischen hinbekommen, daß auch ein Array angezeigt wird;
![protcolIdToJson](https://user-images.githubusercontent.com/14318704/56852222-be0a7a00-6918-11e9-8eb6-5ea06ade5bb0.png)

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
