### ISSUE TITLE
neues Internal - LASTIDdecode or Event

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#565]
Weil wir keine Events mit dem Device auslösen wo man soetwas abgreifen könnte, da kam mir die Idee zu einem Internal welches in dem Empfänger Device die letzte decodierte Protocoll-ID wiedergibt?

Können wir sowas realisieren?

Ein anderer Weg bzw. ne Überlegung wäre, ein Event auszulösen, wenn man ein Modul matched?
In Etwas zu diesem Zeitpunkt

Bps:
`Decoded matched MU Protocol id 80 dmsg E01015B880803008305 length 72`

Realisierbar und was denkt Ihr?
MfG

**Comment by sidey79** [comment]
Ich habe leider noch nicht verstanden was Du erreichen möchtest. Kannst Du das noch erläutern?

**Comment by HomeAutoUser** [comment]
Mir schwebt vor, das die Anzeige der decodieren ID welche in den jeweiligen Device erscheint, das das parallel im Empfänger erscheint.

Nach dem Motto, lastDMSG vom Protokoll „X“ ohne das man alle Devices durchschauen muss.
Man kann somit besser den Zusammenhang herstellen bei Protokollen welche keine „klare preamble“ besitzen wie P96...

Den Nutzen sehe ich somit im Komfort und weil ich damals dachte, die ID vom Protokoll wird zusätzlich auch im Internal des Empfängers widergegeben.

**Comment by sidey79** [comment]
Im SIGNALduino existiert auch ein Internal mit dem Namen LASTDMSG .

Reicht das aus?

**Comment by HomeAutoUser** [comment]
> Im SIGNALduino existiert auch ein Internal mit dem Namen LASTDMSG .
Reicht das aus?

Es geht mir nicht um die LASTDMSG, die dazugehörige ID soll als Ergebnis lesbar dabei herauskommen weil die LASTDMSG bei manchen Protokollen NICHT mit dem Preamble P(Protojollnummer) beginnt. 

Bei LASTDMSG i542abce (Beispiel) weil ich es nicht welches Protokoll es war.

;)

**Comment by sidey79** [comment]
Ja verstehe, könnte man in ein internal schreiben, ob es einem Anwender hilft weiss ich nicht, da es ja mit jedem Empfang aktualisiert wird

**Comment by HomeAutoUser** [comment]
Ich denke, teilweise könnte es helfen.

Zusätzlich hat man so die Möglichkeit ggf von anderen Stellen das Internal abzufragen.
Die stellt eine offene „Schnittstelle“ dann dar.

Mir müsste jemand nur bitte behilflich sein dies einzubinden.

**Comment by HomeAutoUser** [comment]
Es wurde eingebunden, so schließe ich den Faden.
