### ISSUE TITLE
errors in commandref

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#577]
## Expected Behavior

commandref check raises no errors

## Actual Behavior

*** EN FHEM/00_SIGNALduino.pm: Unbalanced li (1, last line ok: 4688)
*** DE FHEM/00_SIGNALduino.pm: negative tagcount for ul, line 5134
*** DE FHEM/00_SIGNALduino.pm: Unbalanced li (1, last line ok: 5108)

## Steps to Reproduce the Problem

  1.  	 run perl /opt/fhem/contrib/commandref_join.pl 

## Specifications

  - Versionmodul (FHEM Module): v3.4.0_dev_16.03

**Comment by HomeAutoUser** [comment]
Diesen Fehler kann ich nicht nachstellen, da das Modul selbst die Fehlermeldung

`Cant open FHEM: No such file or directory`

reproduziert.

Ich denke, das die Angabe in

`my @modDir = ("FHEM");`

bei manchen Systemen da zu dem Fehler führt, da der Pfad nicht gefunden wird.
