### ISSUE TITLE
Better message handling, when performing get actions and better ping handling

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#58]
> Beim Ping, könnte man auf der Fhem Seite entweder den Intervall zurücksetzen, wenn etwas empfangen wurde und dadurch nur Abfragen, wenn längere Zeit nichts vom Arduino kommt oder man lässt den Arduino periodisch etwas senden und wertet in Fhem nur noch aus, ob etwas für einen Zeitraum X empfangen wurde.

Eine Möglichkeit wäre im Arduino nach jeder gesendeten Nachricht ein
lastWriteTime = millis();
auszuführen und dann z.B. in der loop mit der lastWriteTime prüfen ob in den letzen 90 sek was gesendet wurde. Falls nicht, dann z.B. ein "alive" senden.

In der SIGNALduino_Read wird dann bei jeder empfangener Nachricht folgendes ausgeführt:
$hash->{keepalive}{ok}    = 1;
$hash->{keepalive}{retry} = 0;

Dann wird z.B. alle 2 Minuten eine sub SIGNALduino_KeepAlive ausgeführt:
dort wird geprüft ob $hash->{keepalive}{ok} = 0
falls ja, dann wurde in den letzten 2 Minuten nichts empfangen und es wird per  InternalTimer die
sub SIGNALduino_KeepAliveCheck
aufgerufen

In der sub SIGNALduino_KeepAliveCheck wird ein ping gesendet und der retry Zähler erhöht.
Wenn nach 2-3 ping keine Antwort gekommen ist, wird ein disconnect durchgeführt.

Dies ist nur das Prinzip, ich habe es aus den Homematic wired Routinen

>Mich würde vor allem interessieren, wie deine Ansätze aussehen.
Gerade das mit den Get Actions hängt meiner Meinung Nach, ja mit dem Serial Buffer zusammen.
Ich würde erwarten, man kann das Problem sehr einfach lösen, indem man auf Arduino Seite auf ein OK von der Fhem Seite wartet.

Eine einfache Lösungsmöglichkeit wäre in der SIGNALduino_ReadAnswer auf 002 und 003 zu prüfen ob vor der Antwort eine raw-Nachricht empfangen wurde.
Und dann nur die Daten ab der 003 als Antwort verwenden.

Falls keine oder eine falsche Antwort empfangen wurde, würde ich nicht sofort disconnecten sondern erst ein KeepAliveCheck durchführen.

**Comment by Ralf9** [comment]
Nachtrag:
durch die KeepAlive Routinen müsste es auch funktionieren ohne das der Arduino ein "alive" sendet.

**Comment by sidey79** [comment]
Ja, müsste man mal grob überlegen.
Aus meiner Sicht aber besser, man fragt den arduino ab und lässt ihn nicht automatisch was senden.
So ist man flexibel mit dem Intervall etc.

Dass wir nur etwas abfragen, wenn nichts empfangen wurde klingt plausibel. 

In SIGNALduino_ReadAnswer sollte man auf einen Zeilenumbruch reagieren, das könnte ausreichend sein.

**Comment by Ralf9** [comment]
Ich habe die notwendigen Änderungen in der SIGNALduino_ReadAnswer jetzt commited.
Damit funktioniert es bei mir seit 2 Tagen ohne Probleme. Es werden jetzt aus der Antwort vom get-Befehl alle Signal-Nachrichten rausgefiltert.

Es können vor der Antwort vollständige oder eine Signal-Nachricht ohne Anfang empfangen werden:

2016.01.22 03:56:23 3: sduino/RAW (ReadAnswerCut003 74): 5353534353535353535353434353434353435343434343535343535343534;CP=3;SP=0;O;
O

Es können auch nach der Antwort Signal-Nachrichten empfangen werden:

2016.01.22 05:31:24 3: sduino/RAW (ReadAnswerCut002003): OK
MS;P0=-1948;P1=495;P2=-972;P3=-3900;D=13101210121012121210121212121212121010121212121010101010101212101212101010;CP=1;SP=3;O;

**Comment by sidey79** [comment]
OK, ich schau mir das noch mal genauer an.

Ich habe aber womöglich eine Ursache für zusammenhängende Übertragungen gefunden.

Wenn wir mit einem SET Befehl ein Kommando an den Arduino sendet, wird das Kommando quasi als Bestätigung zurück übermittelt.

Es fehlt aber meist ein readanswert, was dazu führt, dass der Befehl in der read routine verarbeitet wird.
Ich bin schon dabei, das an zu passen.

**Comment by Ralf9** [comment]
Das ist mir nicht klar, vermutest Du den Fehler in der 00_SIGNALduino.pm oder in der Firmware im Arduino.
Ich würde in der dev32 Firmware keine große Änderungen mehr vornehmen, sie läuft mittlerweile sehr stabil.

**Comment by sidey79** [comment]
Es ist ein Fehler im Modul.
Die Firmware ist so ganz okay und stabil.

Vielleicht baue ich noch eine config Option ein, aber große Änderungen sind keine geplant

**Comment by Ralf9** [comment]
Die Sache mit der ReadAnswer Routine gefällt mir nicht so richtig.
Eine Möglichkeit wäre, die Antworten in der read Routine rauszufiltern und im hash zu speichern.
In der get Routine müsste dann nach dem senden des Befehls per InternalTimer nach ca 1-3 Sekunden eine Routine aufgerufen werden in der geprüft wird ob die Antwort im hash ist.
Das Problem dabei ist, daß ich keine Möglichkeit gefunden habe, wie man die Antwort in einer Message Box ausgeben kann

**Comment by sidey79** [comment]
ReadAnswer ist die übliche Vorgehensweise. Es ist ja so. Es wird etwas gesendet, darauf kommt auch eine Antwort, aber die Antwort fangen wir nicht ab.

Die Antwort wird ja quasi als Bestätigung gesendet. Darauf kann man mit Readanswer gut prüfen. Ich hab mir deinen Commit angesehen. Ich kommentiere da gleich noch, ich verstehe den Ansatz nicht so ganz.

**Comment by sidey79** [comment]
da readAnswer nicht mehr verwendet wird und die ganze Kommunikation FHEM nicht mehr blockiert, können wir das Thema ja eigentlich schließen oder?

**Comment by Ralf9** [comment]
für das dev-32 dürfte es soweit passen.

Für das dev-33 sehe ich noch optimierungs Potential.
Man könnte z.B. für Antworten einen neuen Nachrichtentyp z.B. "MA" einführen.
Damit müsste sich das parsen der Antworten vereinfachen.
Beim Getupdate sehe ich auch noch Optimierungspotential.

**Comment by sidey79** [comment]
Mittlerweile hast Du ja einiges optimiert. Fehlt noch was für 3.3.0 oder können wir das Thema erst mal als erledigt ansehen?

**Comment by Ralf9** [comment]
es ist mittlerweile alles drin. Für mich ist das Thema erledigt.
