### ISSUE TITLE
RAWMSG no decode (id 3.1) -> after revised code commit cfdabfb

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#582]
## Expected Behavior
Feststellung Message-Test
https://github.com/RFD-FHEM/SIGNALduino_TOOL/issues/2#issuecomment-489708648

## Actual Behavior
- no decode rawmsg 
`MS;P0=-11440;P1=-1121;P2=-416;P5=309;P6=1017;D=150516251515162516251625162516251515151516251625151;CP=5;SP=0;R=66;`

- with revision code 
https://github.com/RFD-FHEM/RFFHEM/commit/cfdabfb2f143112ee30542eae32509197d81ab5e
message not more decode

- on Version @Ralf9 this message decode -> PLEASE search ERROR @sidey79 ;-)

## Steps to Reproduce the Problem

  1. dispatch rawmsg
  2.
  3.

## Specifications

  - Versionmodul (FHEM Module): v3.4.0_dev_16.03

**Comment by sidey79** [comment]
@HomeAutoUser 

Hast Du getestet, ob es vor dem genannten commit funktioniert hat?

**Comment by HomeAutoUser** [comment]
@sidey79

Noch nicht, ich habe es erstmal mit der Aussage von Ralf weitergegeben. Ich kann gern versuchen dies einzugrenzen aber Ralf seine Aussage klang plausibel :)

**Comment by HomeAutoUser** [comment]
@sidey79 ich habe versucht den Commit einzuspielen und zu testen, da gelang mir das decodieren der message auch net.

Kannst du dich der Problematik mal widmen bitte das diese nicht "herunterfällt" weil dies ist ja ein Bug welcher gerade die FW von dir und Ralf unterscheidet.

**Comment by HomeAutoUser** [comment]
@Ralf9 könntest du bitte die Nachricht mal bei dir Dispatchen und dabei auf verbose 5 stellen und das selbige machen wir mit @sidey79 seiner Version um das er vielleicht daran anhand schon Erkenntnisse sieht.

Diese Ausgaben vergleichen wir dann und könnten ja da vielleicht den Abbruch feststellen.

**Comment by Ralf9** [comment]
Hatte ich schon hier mit verbose 5 gepostet
https://github.com/RFD-FHEM/SIGNALduino_TOOL/issues/2#issuecomment-489708648

**Comment by sidey79** [comment]
Wir sollten auch erfassen, mit welcher Firmware eine Nachricht erfasst wurde.

Float war bis 4880711c2cba99735f64bcdb0e799c40540931e1 optional auch wenn es im Protokoll Hash definiert wurde.
Jetzt ist float allerdings nicht mehr optional. Wenn float definiert wurde, dann muss die Sequenz auch in den Daten vorkommen.

Bei den genannten Daten ist dies nicht der Fall und deshalb passt ID 3.1 nicht.

Es gibt drei Optionen

1) Float wieder optional gestalten
2) Eine weitere Protokolldefinition anlegen bei der float nicht enthalten ist (passt dann aber ggf. fürs Senden nicht)
3) Einen Schalter in der Protokolldefinition einbauen, welche steuert ob float vorkommen muss oder optional ist.

**Comment by sidey79** [comment]
Ich habe für Option 1 mal einen Pullrequest erstellt. Dann wäre es so wie früher.

**Comment by HomeAutoUser** [comment]
Das der Fall wieso es nicht geht, zeigt mir, das wir alles immer durchprüfen müssen.

Grund dafür ist ganz einfach, es muss IMMER sichergestellt werden das deine Firmware / Modul mit dem von Ralf kompatible ist. Sollte das nicht der Fall sein, so driften wir von einer gemeinsamen Entwicklung eines Projektes welches mit EINEM Namen und mit mehreren Ständen existiert ab. 

Bei dem einen wo es funktioniert, dieser "ernährt" sich mit neuen Features und Fehler werden dadurch stillschweigend hingenommen, das irgendwann die Differenz zu groß wird und Diskussionen, immer bestehen bleiben für den Enduser.
