### ISSUE TITLE
name - comments changes - Protocol ID's

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#591]
Hallo,

ich möchte hier die Möglichkeit zur Diskussion und Anregung schaffen um vermeintliche Namen / Comments in der Protocol ID's Datei "SD_ProtocolData.pm" zu erfassen um nach Klärung diese besser zu bennen für den Endverbraucher.

Bsp:

```
ID 0 - 0.3 - weather (v1) | temperature / humidity or other sensors
ID 4 - arctech2
ID 26 - 27 - remote
```

... unsw.

Gern würde ich dies Schrittweise "angehen" um nicht die Diskussion über mehrere ID gleichzeitig zu führen.

Wie denkt Ihr darüber?

**Comment by sidey79** [comment]
Die Beschreibung zu verbessern ist gut.
Auch das ganze in kleinere Abschnitte zu unterteilen.

Wenn es konkrete Vorschläge gitb, dann her damit würde ich sagen :)

**Comment by sidey79** [comment]
Können wir das Issue schließen?

**Comment by HomeAutoUser** [comment]
Ich würde diesen Faden mal noch offen lassen um die Meinungen auszutauschen bis wir einmal die Liste "durchgekaut haben".

**Fall weather (vX) Protokolle:**
```
name	=> 'weather (v2)',
comment	=> 'temperature / humidity or other sensors',
```

Was haltet Ihr davon, wenn wir hier einfach den name
`temperature / humidity or other sensors (vx)`
bennnen und bei comment
`den bzw die uns bekannten Sensortypen`
reinschreiben?

**Comment by elektron-bbs** [comment]
Ich würde schon besser bei kurzen Namen bleiben wollen, so das in der Protokollliste möglichst kein Zeilenumbruch erfolgt. Das macht es übersichtlicher.
Die Sensortypen und Hersteller etc. dann in den Kommentar.

**Comment by HomeAutoUser** [comment]
Wie wäre der Vorschlag, wenn man anstatt
`weather (v1)`
dies nimmt?
`Temp/Hum/Rain/Wind Sensors`

und dann comment die dort bekannten Sensornamen wie 
`ABS700 / Mebus / GT_WT_02 / Prologue`
?

**Comment by sidey79** [comment]
Könnte man so machen ja.
