### ISSUE TITLE
Spikes in signal from NC_WS sensors

### ISSUE THREAD

**Issue by Antannah** [RFD-FHEM/RFFHEM#594]
## Expected Behavior
Measured temperature-values give a smooth curve in plot

## Actual Behavior
The measured values have frequent outliers, that reach almost a common level of about 48 deg. They show up as spikes in the diagram.
![Spikes in diagram](https://user-images.githubusercontent.com/8082121/58470554-38116700-8142-11e9-8300-d341a255f090.png)
When outliers appear, thy mostly appear on temperature and humidity at the same time, but obviously not always.

## Steps to Reproduce the Problem

  1. run measurement continuously for some time, my NC_WS give one measurement every 90s 
  2. log to database and plot in fhem

## Specifications
Microcontroller #1: wemos d1 mini
Version:	V 3.3.1-RC-nightly SIGNALESP cc1101 (chip CC1101) - compiled at Feb 3 2019 21:37:16
Microcontroller #2: Arduino nano with superhet receiver and cheap china transmitter
V 3.3.1-RC10 SIGNALduino - compiled at Dec 29 2018 01:43:10

Versionmodul (FHEM Module): v3.4.0_dev_16.03

## Incomming Signals from two Signalduinos
Both receive the Signal:

sduinoESP_DMSG | s5E880E631000
-- | --
sduinoESP_MSGCNT | 1972
sduinoESP_Protocol_ID | 0
sduinoESP_RAWMSG | MS;P0=-1954;P1=495;P2=-3908;P4=-9222;D=14101210121212121012101010121010101010101012121210101212101010121210101012;CP=1;SP=4;R=28;O;m2;
sduinoESP_RSSI | -60
sduinoESP_TIME | 2019-05-28 11:37:28
sduino_DMSG | s5E880E832000
sduino_MSGCNT | 3783
sduino_Protocol_ID | 0
sduino_RAWMSG | MS;P0=-9195;P1=509;P2=-1925;P3=-3889;D=10121312131313131213121212131212121212121213131312131212121212131312121312;CP=1;SP=0;R=0;O;m2;
sduino_RSSI | -74
sduino_TIME | 2019-05-28 12:02:33

## What I already did
I tried setting the attribute `max-deviation-temp` to `10`, which didn'n help although outliers are more than 10 deg greater.
There is no attribute to do the same mechanism for humidity.

We recently discussed the bahavior for the OPUS300 Sensor, so I expected it working here in the same way.

What is the reason for the outliers? Wrong decoding?
Why does the mechanism with the `mac-deviation`attribute not cover the case?
Will the mechanism be added for humidity as well?

Best regards Antannah

**Comment by elektron-bbs** [comment]
Das kann bei diesem Sensor nicht funktionieren. Im Modul 14_CUL_TCM97001.pm wird max-deviation-temp nur bei Nachrichten mit einer Länge von 8 ausgewertet:

  if (length($msg) == 8) {
    # Only tmp TCM device
    #eg. 1000 1111 0100 0011 0110 1000 = 21.8C

Die Prüfung auf max-deviation-hum existiert gar nicht.

Da wir dieses Modul nicht bearbeiten, kannst du nur versuchen, im [FHEM-Forum](https://forum.fhem.de/index.php/board,46.0.html) dieses Problem darzustellen.

**Comment by sidey79** [comment]
Wie wäre es mit dem Prüfen auf zwei gleiche Nachrichten?

doubleMsgCheck_IDs
Dieses Attribut erlaubt es, Protokolle anzugeben, die zwei gleiche Nachrichten enthalten müssen, um diese an die Module zu übergeben. Sie können mehrere IDs mit einem Komma angeben: 0,3,7,12

**Comment by sidey79** [comment]
Ich denke wir können hier nicht mehr tun. Wenn noch was ist einfach wieder öffnen :)
