### ISSUE TITLE
length 0 are dispatch & length_min in ID definition

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#596]
## Expected Behavior
- messages with length 0 are dispatch

## Actual Behavior
WRONG Dispatch
```
Decoded matched MU Protocol id 82 dmsg P82# length 0 dispatch(1/4) RSSI = -64.5
Decoded matched MU Protocol id 82 dmsg P82# length 0 dispatch(3/4) RSSI = -64.5
```

```
"82"	=>	## Fernotron shutters and light switches
....
length_min		=> '100',			# actual 120 bit (12 x 10bit words to decode 6 bytes data), but last 20 are for checksum
length_max		=> '3360',			# 3360 bit (336 x 10bit words to decode 168 bytes data) for full timer message
},
```

## Steps to Reproduce the Problem

  1. ID 82 activated
  2. get DUMMY raw MU;P0=-9812;P1=589;P2=-671;P3=1261;P4=-1320;D=012341412323232341412341412323232323232323;CP=3;R=19;

OR

  2. get DUMMY raw MU;P0=10530;P1=-2908;P2=533;P3=-598;P4=-1733;P5=767;D=0123242323232423242324232324232423242323232324232323242424242324242424232423242424232501232423232324232423242323242324232423232323242323232424242423242424242324232424242325012324232323242324232423232423242324232323232423232324242424232424242423242324242;CP=2;O;

## Specifications
  - Versionmodul (FHEM Module):   v3.4.0_dev_11.05

**Comment by HomeAutoUser** [comment]
@sidey79 damit das debuggen weitergeht ;-)

**Comment by sidey79** [comment]
okay, die 3360 Bits werden wir halt nie in den Puffer bekommen :/

**Comment by HomeAutoUser** [comment]
Bitte den Post richtig lesen ;)
Die oben genannte RAWMSG bringt ein Dispatch mit lengh 0.

Um die 3360 Bits geht es nicht. Die def wurde nur mit aufgeführt weil dort eine minimale Länge drin steht aber dennoch ein Dispatch gemacht wird!

**Comment by sidey79** [comment]
@HomeAutoUser 

Danke. Hatte ich im Blick. Das mit der 3360 war eher als Anmerkung zu verstehen Sorry.
Habe den Fehler schon nachgestellt. Liegt womöglich auch an dispatchBin.

**Comment by HomeAutoUser** [comment]
Nichts zu danken ;)

Wenn du den Fehler nachstellen konntest ist ja der Ansatz gemacht.

**Comment by sidey79** [comment]
glaube mittlerweile sogar dass es eher an der Angabe float liegt... naja ich finde das Problem gleich

**Comment by HomeAutoUser** [comment]
Mir ist der Fehler bei einigen RAWs aufgefallen aber auf die Defs habe ich nicht geschaut ob diese den Syntax float besitzen.

**Comment by elektron-bbs** [comment]
Hat sich das erledigt?

**Comment by sidey79** [comment]
Sollte bereits im SVN sein

**Comment by sidey79** [comment]
Sollte bereits im SVN sein
