### ISSUE TITLE
Mumbi m-FS300

### ISSUE THREAD

**Issue by markus7811** [RFD-FHEM/RFFHEM#60]
Hi,
würde gerne meine Funksteckdosen vom Typ Mumbi m-FS300 schalten. Habe einiges über das Protokoll heraus gefunden. Habe ich alles hier im FHEM-Forum bereits geschrieben, weil ich das eigentlich mit dem CUL schalten wollte. Da ist aber tote Hose.

Hallo,

ich hatte die Frage schon unter Cul-Fans auf Google-Groups/FHEM gestellt, allerdings scheint dort tote Hose zu sein. Daher probiere ich es hier noch einmal...

Mein Problem
Ich will Funksteckdosen mit dem SIGNALDUINO schalten und den Status auch in FHEM sehen. (Also beim Schalten mit der FB auch in FHEM aktualisieren)

Meine Dosen
Non-Affiliate-Amazon-Link Die Steckdosen sind vom Typ Mumbi m-FS300, die Fernbedienung eine AB440R. Die Fernbedienung sendet allerlei verschiedene Codes mit einem Tastendruck - unter anderem auch das IT-Protokoll, allerdings reagieren die Steckdosen nicht auf dieses.

Was weiß ich über das Protokoll
Eigentlich nicht viel - da stocher ich (und viele Andere - siehe forum.arduino.cc, oder wiki.pilight.org) noch im Nebel. Nach einiger Zeit ist es mir dann gelungen, die Dosen mit Pilight zu schalten, indem ich die Schaltbefehle mit pilight-raw mitschneide. 

Um es einfach zu machen, werde ich im weiteren Verlauf immer an der Taste B On meiner Fernbedienung orientieren, bzw. versuchen diese zu senden.

Die Pilight-Raw-Timings dieser Taste sind:
Code: [Auswählen]
         1        1        0       1        1        0       1        0       0       1        0       1        1        0       0       1        0       0       0       1        0       0        0      0       0       1        1        0  
238 4945 243 1033 236 1033 897 379 253 1031 257 1045 875 412 231 1031 914 383 894 382 254 1022 893 384 256 1022 266 1021 904 381 919 365 287 1040 855 389 894 380 905 382 275 1003 905 381 905 373 950 349 912 364 897 387 254 1031 272 1022 904 371 302

visualisiert sieht das dann wie folgt aus:
![](https://picload.org/image/wrilrra/temp.png)

Ein Sync besteht wohl immer aus einem knapp 5.000 us langen LOW
Ein 1-Bit besteht aus ca. 230 us HIGH gefolgt von 1050 us LOW
Ein 0-Bit besteht aus ca. 885 us HIGH gefolgt von   400 us LOW
Ein Schaltbefehl besteht immer aus 28 Bit

(Diese Erkenntnisse habe ich aus all meinen Fernbedienungen extrahiert - nicht nur Taste B On  ;))

Mittels Verbose 4 sieht dann die Taste
B ON: 2016.01.13 20:07:52 4: SIGNALduino/msg READ: MS;P0=229;P1=-1007;P2=918;P3=-371;P4=-4898;D=0401012301012323232323232323230101012301012301012301010123;CP=0;SP=4;
B OFF: 2016.01.13 20:10:51 4: SIGNALduino/msg READ: MS;P0=-520;P2=241;P3=-1008;P4=917;P5=-4895;D=2523234023234040402340404023234040404023404040232340402340;CP=2;SP=5;

Analog dazu kann ich auch mit diesen Befehlen schalten:
set sduino raw SR;;R=3;;P0=4742;;P1=-1554;;P2=286;;P3=-786;;P4=649;;P5=-420;;D=0123234545234545452323232323454523234523454523232345454523232323452345234523452345;;
set sduino raw SR;;R=3;;P0=229;;P1=-1007;;P2=918;;P3=-371;;P4=-4898;;D=0401012301012323232323232323230101012301012301012301010123;;

Das Protokoll an sich verstehe ich noch nicht: Ein Bit-Muster für die Fernbedienung, Taste, ON OFF etc. konnte ich noch nicht ausmachen. Werde aber - sobald Erkennen und Schalten mit FHEM funktioniert da weiter dran arbeiten.

**Comment by sidey79** [comment]
Hast Du zwischenzeitlich mal geprüft, ob das Signal demoduliert wird?

**Comment by markus7811** [comment]
Hi, ja - habe ich! Funktioniert super! Vielen Dank für deine schnelle Reaktion!

**Comment by sidey79** [comment]
Und, lässt sich ein Bitmuster erkennen?

**Comment by wexstorm** [comment]
Hallo zusammen,

auch ich habe (wahrlich) nächtelang an diesem bescheuerten Bitmuster gesessen. Ich habe wirklich EINIGES verstanden, aber was eben noch nicht so ganz klar ist:
Es werden pro Knopf (in einer Art Rolling Code) 4 verschiedene Codes (Bei Knopfdruck der gleiche Code 4 Mal) gesendet. Dabei lässt sich vom AN-Code nicht komplett auf den AUS-Code schließen.
Es gibt in den 28 Bit einige Wiederholungen, und einige Bits sind für verschiedene Fernbedienungen, jedoch die gleichen Knöpfe, gleich. Einige Bits in der Mitte unterliegen aber irgendeinen Algorithmus.
Hier mal alle Codes, die ich aufschnappen konnte schön sortiert in txt-Dateien:
[http://www.bit-storm.de/ul/rf433_codes.zip](ZIP-Datei)
Die ersten 6 und letzten 6 Bits bleiben immer gleich (scheinen also Taste und an/aus zu bestimmen).
Dann kommen die 12 super magischen Bits (Was habe ich per XOR und Ähnlichem rumgetüftelt!) und dann
4 Bits, die lustigerweise in zwei Sets, die ich gleichzeitig bestellt habe, komplett gleich sind.
Kurzer Versuch der Veranschaulichung:
[http://www.bit-storm.de/ul/rf433_a_b.gif](Animiertes Gif)

Ich bin gerne bereit, das Thema wieder aufzunehmen. Der Frust war leider zu groß.

Viele Grüße

**Comment by wexstorm** [comment]
Und hier: Falls ihr die Codes mit einem Arduino auslesen möchtet:
[flamingoswitch_working.zip](http://www.bit-storm.de/ul/flamingoswitch_working.zip)
Empfänger anschließen, dann eine der Tasten so of drücken, bis 4 Zeilen in der Console erscheinen => das sind dann die 4 Codes für die Taste. Arduino neu starten und wieder eine Taste 4 Mal drücken usw.

Damit habe ich all meine Fernbedienungen ausgelesen und kann die dazugehörigen Steckdosen mit einem modifizierten Plugin 00_GenShellSwitch (hier gibts's das Original: [Link](https://www.hempel-online.de/cms/index.php/fhem/articles/intertechno-steckdosen-mit-raspberry-pi-aus-fhem-ansteuern.html)) zum Schalten gebracht. rc-switch muss dafür leider auch noch angepasst werden.

In FHEM kann man ein Device dann so einbinden:
define Lampen_Schrank GenShellSwitch /opt/rc-switch/rcswitch-pi/send 0010011101011111101011111001 0010011010011111010011000101 0010011010011000100010010001 0010011011100001011110011001 0010010001011001000111001101 0010011100110011001111101001 0010010101111001011000011101 0010011101001011101110010101 310

Wobei die Codes so aufgebaut sind:
4* An Code, 4* Aus Code, 1* Pulselength (da habe ich am meisten rumtüfteln müssen - rc-switch muss in high priority mode laufen!!!)

Alles nicht so einfach :(

Wäre aber schön, wenn man diese Dosen auch mit SIGNALduino (vorher z.B. die AUS-Codes händisch auslesen, die AN-Codes könnte man ja per FB an den Arduino senden) schalten könnte. Auch hier: Ich helfe gerne wo ich kann!!!

**Comment by nicozimmermann94** [comment]
Ich weiss nicht ob ich hier richtig bin aber ich habe mir gestern die mumbi FS300 Funksteckdosen gekauft und wollte die per pilight steuern. Leider funktioniert keines der getesteten Protokolle. Wenn ich lausche und auf der Fernbedienung den Anschalter betätige, erhalte ich ca 8 verschiedene Signale. Kann es sein, dass es für diese Steckdosen noch kein Protokoll gibt?

**Comment by sidey79** [comment]
Naja, das kommt darauf an.
Wenn Du es mit dem Signalduino nutzen willst, bist Du hier richtig.

**Comment by HomeAutoUser** [comment]
@elektron-bbs hier ist der alte Faden dazu welcher noch geöffnet ist.
Anbei die Liste [mumbi.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/2705169/mumbi.xlsx) und auch die Diskussion https://github.com/RFD-FHEM/RFFHEM/pull/443#issuecomment-449561459 wovon es ausging.
Der Forumslink ist hier https://forum.fhem.de/index.php?topic=94327.new;topicseen#new

**Comment by elektron-bbs** [comment]
Naja, jetzt geht es ja wohl um Manax MX-RCS250.

**Comment by HomeAutoUser** [comment]
Augenroll ;) die sind ähnlich „Smile“

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
