### ISSUE TITLE
SVN Update (3.4.0)

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#608]
Prepare Pullrequest for merge into master
   * [x]  Pullrequest #611 
   * [x]  Änderungen verarbeiten / Releasenotes anfertigen #609 
https://github.com/RFD-FHEM/RFFHEM/releases/tag/3.4.0
   * [x]  Abhängigkeiten 
  * * [x]  #584

Logical modules which are new in version 3.4.0

 * [ ]  14_SD_Keeloq.pm  
  * * [ ]  Maintainer festlegen
  * * [ ]  Ankündigungsthread erstellen
  * * [ ]  Modul hochladen

 Logical modules which must be modified at svn verion 
 
 * [x]  14_SD_BELL.pm (homeautouser  )
 * [x]  14_SD_RSL.pm (ralf9/sidey)
 * [x]  14_SD_UT.pm	  (homeautouser  )
 * [x]  14_SD_WS.pm  (sidey  )
 * [x]  14_SD_WS07.pm (sidey  )
 * [x]  90_SIGNALduino_un.pm (sidey  )
 * [x]  ~~signalduino_protocols.hash~~ (sidey)
 * [x]  SD_ProtocolData.pm (sidey)
 * [x] SD_Protocols.pm (sidey)
 * [x]  00_SIGNALduino.pm (sidey)

 Not updated modules
 
 * [ ]  14_Hideki.pm (sidey)
  * [ ]  14_FLAMINGO.pm (homeautouser )
 * [ ]  10_FS10.pm	 (elektron-bbs  )
 * [ ]  14_SD_WS_Maverick.pm (sidey  )
 * [ ]  14_SD_WS09.pm (sidey  )
 * [ ]  41_OREGON.pm (sidey  )

**Comment by sidey79** [comment]
So ganz nebenbei, gibt es mittlerweile auch eine Organisation in Github in der sich viele FHEM Dinge ansammeln:
https://github.com/fhem

Dort könnte man unter anderem auch das ein oder andere hin verlagern und aufsplitten.

z.B. logische Module von 00_SIGNALduino trennen.

**Comment by sidey79** [comment]
@HomeAutoUser 
Wie sieht das mit 
 14_SD_BELL.pm (homeautouser )
und
 14_SD_UT.pm	(homeautouser )
aus? Soll ich die im SVN aktualisieren?

**Comment by HomeAutoUser** [comment]
Ahoi von de Küst :)
Wenn du es machen möchtest kannst du es machen.

Ich würde nächste Woche bei Rückkehr den „Rundumschlag“ machen für das SVN.

**Comment by sidey79** [comment]
Einige Module habe ich heute aktualisiert.

Nächste Woche bin ich an der Küste :)

**Comment by HomeAutoUser** [comment]
Geht klar.

Ich habe dich schonmal  angekündigt :) und ab sofort gibt’s Strandkörbe mit WLAN :D

**Comment by HomeAutoUser** [comment]
@elektron-bbs 

ich lese hier mit auf der ToDoList
>Logical modules which are new in version 3.4.0
14_SD_Keeloq.pm

Könntest du bitte schauen ob du den Beitrag zwecks Rechtslage nochmal findest und was zu beachten wäre? Vielleicht sind ja noch Hinweise oder Verweise im Modul notwendig. Wir wollen ja nicht aus dem Raum mit 4 Wänden und ohne PC weiterentwickeln ;-)

**Comment by elektron-bbs** [comment]
Das macht sich ach ganz schlecht ohne Internet und PC :-)
Auf Anhieb finde ich jetzt nur dieses wieder:
https://groups.google.com/forum/?hl=de&fromgroups#!topic/cul-fans/hqwSGCJh6ro

**Comment by sidey79** [comment]
@elektron-bbs  @HomeAutoUser 

Wie machen wir mit dem Keeloq Modul weiter?

**Comment by HomeAutoUser** [comment]
@sidey79  Thema,  Keeloq Modul ist vielleicht eine Sache, wo mal Rudi sich nochmal letztendlich zu Wort melden sollte weil in der Diskussion https://groups.google.com/forum/?hl=de&fromgroups#!topic/cul-fans/hqwSGCJh6ro war das schonmal erörtert wurden.

**Comment by elektron-bbs** [comment]
Leider scheint groups.google den Originalfaden nicht komplett abzubilden. Hier ist der Link zum FHEM-Forum mit diesem Thema:
https://forum.fhem.de/index.php/topic,13596.0.html

**Comment by sidey79** [comment]
Ich habe mir nur eine Seite von den 14 angesehen. Da ging es um patente und geheime Codes.

Was für ein Problem könnte es mit dem Modul geben? Wird ggf. ein Patent verletzt?

Wir könnten das Modul auch in ein eigenes Repository migrieren, dann wären wir unabhängiger.

**Comment by HomeAutoUser** [comment]
>Wir könnten das Modul auch in ein eigenes Repository migrieren, dann wären wir unabhängiger.

Das ist es im Grunde schon. https://github.com/HomeAutoUser/SD_Keeloq__old_Jaro
Ich habe nach der Erweiterung expliziet Jaro immer aktualisiert bei uns. Da es mehrer Devices bei uns mit dem Verfahren gibt, so nehme ich die kleinen Erweiterungen bei uns direkt hinzu.

Da es manche Fixes gibt, so wird die Hauptkommunikation direkt auf dem Repro vorgenommen um nicht die SpamFlood hier zu besitzen.

**Comment by sidey79** [comment]
Was ich meinte ist, dass wir es vielleicht nur in einem eigenen Repo im FHEM kompatiblen Format ablegen.
https://github.com/fhem

ist da sehr interessant. Auch eine Migration dieses Projektes eventuell.

**Comment by HomeAutoUser** [comment]
@sidey79 gibt es Vorteile wenn wir es in dem von dir benannten "FHEM kompatiblen Format" ablegen?

-> https://github.com/fhem

**Comment by sidey79** [comment]
Ja,

Damit ist es möglich mittels Update Befehl direkt aus dem Repository das Modul zu aktualisieren und den Anwendern werden fragwürdige editier und Kopieraufgaben abgenommeb

**Comment by HomeAutoUser** [comment]
Das wusste ich nicht, das es sowas gibt.
1) Wird das dem User bei jedem "normalen Update" bereitgestellt oder muss dort noch was eingestellt werden?
2) Wer kann ein solches RePo erstellen und können wir dies dann einfach auch immer updaten?

Ein solcher Fall ist für mich Neuland aber klingt gut.

**Comment by sidey79** [comment]
Funktioniert genauso wie hier im Repo.

Die Update URL muss der Anwender hinterlegen. 

Da könnte man eventuell auch ein Hilfsmodul anbieten um das zu generalisierten.
Quasi einfaches Einbinden des Git Repos.
Das ist dann aber eine andere Baustelle

**Comment by HomeAutoUser** [comment]
@sidey79 
ich habe soeben die Module

```
14_SD_UT.pm
14_SD_BELL.pm
```

ins SVN aktualisiert.

Da für den vollen Funktionsumfang von SD_BELL ein erneutes SVN Update von 00_SIGNALduino.pm notwendig ist, so habe ich im ersten Post den Haken herausgenommen.

```
14_SD_Keeloq.pm
```

Wir haben diese Diskussion offen weshalb wir es "zurück" lassen weil es ja dort auch um ggf. rechtliche Dinge geht. Fakt ist, viele User Nutzen nun unser Modul und ob es für Rudi "rein" ist wenn wir es in dieser Form online stellen weiß ich nicht. Schlüssel welche notwendig dazu sind, sind nicht fest verankert im Modul, diese muss sich jeder selbst ggf. aus der damaligen Sicherheitslücke zusammensuchen.

**Comment by sidey79** [comment]
@HomeAutoUser 
Das verstehe ich jetzt nicht.

Mit Pull #611 sind doch alle Module zum Stand 19.07.2019 in den Master Branch überführt worden.
Wieso sind die jetzt nicht Kompatibel?

Den haken habe ich ob wieder eingesetzt, da die Version im Master (3.4.0) auch die Version ist, welche im SVN (3.4.0) eingecheckt wurde.


**14_SD_Keeloq.pm**

Rechtlich kann ich nicht einschätzen wie der Code entstanden ist. Ob das jetzt im FHEM SVN Repo liegt oder hier spielt hinsichtlich der Rechte am code eine untergeordnete Rolle. Das Problem bleibt erst mal identisch, wenn es denn überhaupt eines gibt, egal in welchem Repo der Code liegt.

**Comment by HomeAutoUser** [comment]
@sidey79 

hier ist die Zeile aus der Masterversion
https://github.com/RFD-FHEM/RFFHEM/blob/03b63a4c46e8490fee29da74bdaa69d34ff6b941/FHEM/00_SIGNALduino.pm#L187

und hier ist die aktuell "benötigte" wenn man den Stand des SD_Bell Moduls voll nutzen möchte.
https://github.com/RFD-FHEM/RFFHEM/blob/b0b295bcdd9164d691e65ee980b06ff4f9598d39/FHEM/00_SIGNALduino.pm#L188

oder auch die notwendige Anpassung ....
https://github.com/RFD-FHEM/RFFHEM/blob/b0b295bcdd9164d691e65ee980b06ff4f9598d39/FHEM/00_SIGNALduino.pm#L3651

Das meinte ich mit, "die SVN - Version" ist somit updatenotwendig ;-)

>14_SD_Keeloq.pm

.... keine Ahnung wie wir da verfahren. Maintainer kann ich gern ergänzen und einen Vorstellungsfaden benötigen wir ja im Forum erst wenn es ins SVN kommt dachte ich.

**Comment by sidey79** [comment]
Ahh jetzt habe ich das mit de Anpassung verstanden.

Zum Keeloq:

Wie hast Du denn den Entschlüsselungscode erstellt? Ist er dir selbst eingefallen?

**Comment by HomeAutoUser** [comment]
Der Code wurde auf Basis von diesem Projekt erstellt.
http://www.bastelbudenbuben.de/2017/04/25/protokollanalyse-von-jarolift-tdef-motoren/

Die dortigen Dateien habe ich mir angesehen und in Perl umgesetzt :)

**Comment by sidey79** [comment]
https://www.microchip.com/design-centers/embedded-security/downloads/keeloq-encoder-download

Lies dir mal die "Terms and conditions" durch.
Die Implementierung dürfte unter 1g fallen


Ist aber ziemlich viel Text und ich habe noch nicht verstanden für was genau Lizenzgebühren fällig wären.
