### ISSUE TITLE
 Renkforce FT007TP - CH 5 + CH 6 - Please Check

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#617]
## Expected Behavior
User berichtet über no AUTOCREATE.

https://forum.fhem.de/index.php?topic=102667.new;topicseen#new

## Actual Behavior
No Autocreate

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Microcontroller:
  - Version (Firmware):

  - Versionmodul (FHEM Module):

**Comment by elektron-bbs** [comment]
Tja, leider keine Reaktion mehr vom User seit 01.08.2019:
https://forum.fhem.de/index.php?topic=102667.msg963330#msg963330

**Comment by HomeAutoUser** [comment]
Ich habe den User nun mal direkt kontaktiert und wenn sich da ebenso nichts tut, werde ich den Faden dann schließen.

**Comment by elektron-bbs** [comment]
@HomeAutoUser 
Seit nunmehr 5 Monaten keine Reaktion vom User - ich hake das erst mal ab.
