### ISSUE TITLE
 PERL WARNING first reception Hideki

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#624]
## Expected Behavior
Troubleshooting Warning

## Actual Behavior
`2019.08.08 19:05:38 1: PERL WARNING: Use of uninitialized value $hidekihex in concatenation (.) or string at ./FHEM/00_SIGNALduino.pm line 3959.`

## Steps to Reproduce the Problem

  1. load current dev-r34 version
  2. shutdown restart
  3. ONLY first reception of Hideki Sensor

## Specifications

  - Microcontroller: arduino nano
  - Version (Firmware): V 3.3.1-experimental SIGNALduino cc1101 (chip CC1101)

  - Versionmodul (FHEM Module): v3.4.1_dev_19.07

**Comment by sidey79** [comment]
Ich habe versucht diesen Fall nachzustellen. Leider vergeblich.

Probiert habe ich es mit folgenden Daten:
https://github.com/RFD-FHEM/SIGNALduino_TOOL/blob/517bcaf97424f11b583056d498b2fee8e688cd4c/FHEM/lib/SD_Device_ProtocolList.json#L209

**Comment by HomeAutoUser** [comment]
Das ist natürlich sehr komisch.
Ich kann das ganze immer provozieren indem ich FHEM neu starte und warte bis der erste Hideki Empfang kommt. Da kommt auch die Warnung.

**Comment by HomeAutoUser** [comment]
Ich habe nun mal ein wenig getestet und probiert mit Testausgaben an der Stelle:

```
my $hidekihex; #<<<<<----- **FEHLERSTELLE**
my $idx;
		
for ($idx=$message_start; $idx<$message_end; $idx=$idx+9)
{
my $byte = "";
$byte= substr($bitData,$idx,8); ## Ignore every 9th bit
Debug "$name: byte in order $byte " if ($debug);
$byte = scalar reverse $byte;
Debug "$name: byte reversed $byte , as hex: ".sprintf('%X', oct("0b$byte"))."\n" if ($debug);

Log3 $name, 3, "Internal RAWMSG nano_433Mhz: ".$defs{nano_433Mhz}{RAWMSG};
Log3 $name, 3, "Internal RAWMSG radino_433Mhz: ".$defs{radino_433Mhz}{RAWMSG};
$hidekihex=$hidekihex.sprintf('%02X', oct("0b$byte"));
}
```

Das Ganze wird behoben wenn

`my $hidekihex;`

in

`my $hidekihex = "";`

geändert wird.

Die PM durchläuft den Wert beim ersten mal und die Variable soll in der 
Zeile
```$hidekihex=$hidekihex.sprintf('%02X', oct("0b$byte"));```
verarbeitet werden. Da kommt der Fehler, wenn $hidekihex undef ist, daher mit leer definieren und schon ist kein Fehler mehr.

Stimmst du dem kleinen Fix zu @sidey79 mit
`my $hidekihex = "";`
Wenn ja, mache ich einen PR.

**Comment by sidey79** [comment]
Ja ich verstehe, der Fix passt.

Ich wundere mich nur, wieso das bei mir gestern nicht kam.

**Comment by HomeAutoUser** [comment]
Fehler wurde gefixt
