### ISSUE TITLE
Crash bei UI = Einzeilig

### ISSUE THREAD

**Issue by Futty87** [RFD-FHEM/RFFHEM#626]
## Expected Behavior
Attribut UI=Einzeilig

## Actual Behavior
FHEM startet neu

Log:
Undefined subroutine &SD_Keeloq::FmtDateTime called at ./FHEM/14_SD_Keeloq.pm line 223.

Attribut wurde nicht übernommen

## Steps to Reproduce the Problem
Mehrere Devices (min. 2) 14_SD_Keeloq definiert. 
Alle haben Attribut Channels und ChannelFixed gesetzt. 

  1. Model = Jarolift
  2. Channels = 1
  3. ChannelFixed = z.B. 1 & 5
  4. Setze Attribut UI = Einzeilig 

## Specifications

  - Microcontroller: Arduino Nano
  - Version (Firmware): V 3.3.1-experimental SIGNALduino cc1101 (chip CC1101) - compiled at Jun 16 2019 00:08:43
  - Versionmodul (FHEM Module): v3.4.1_dev_11.08

**Comment by HomeAutoUser** [comment]
Danke für die Meldung, ich schaue es mir an.

**Comment by Futty87** [comment]
Falls noch weiter Infos benötigt werden einfach kurz melden. Bin zwar sehr unerfahren in der Thematik, versuche aber bestmöglich zu unterstützen.

**Comment by HomeAutoUser** [comment]
Hallo @Futty87,
ich habe versucht soeben mal das Ganze nachzustellen aber bei mir tritt der benannte Fehler nicht auf.

Bitte mal mal ein list <device> damit ich sehen kann was du alles gesetzt hat und was nicht.
Wenn ich die Attribute so setzte wie von dir beschrieben stürzt nichts ab bzw kann ich auch erst nicht Kanal 5 setzen wenn einer eingestellt ist.

**Comment by Futty87** [comment]
Sehr schön, 

also benötigst du auch keine weiteren Infos / ein list mehr?
Soll ich hier schließen da behoben?
Vielen Dank für die Mühe und die Arbeit

**Comment by HomeAutoUser** [comment]
Bitte testen @Futty87 nachdem du ein Update vollzogen hast.

**Comment by Futty87** [comment]
Funktioniert. Danke!
