### ISSUE TITLE
Lidl Wetterstation

### ISSUE THREAD

**Issue by localhosthack0r** [RFD-FHEM/RFFHEM#63]
Temperatursensor Z31743B-TX
https://www.libble.de/auriol-z31743/p/594324/
Wurde von FHEMduino als Auriol erkannt.

Hier mal Logschnipsel:

2016.01.28 21:50:27 4: sduino/msg READ: MU;P0=-1937;P1=483;P2=-3889;P3=-9072;D=0101010101012121210101012121010121012121010131;CP=1;
2016.01.28 21:50:27 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.01.28 21:50:30 4: sduino/msg READ: MU;P0=-1856;P1=-696;P2=185;P4=-4206;D=012020202024202020202020202420202020202020242;CP=2;

2016.01.28 21:51:01 4: sduino/msg READ: MU;P0=-184;P1=-1824;P2=505;P4=-3888;D=01212121212121242424212124212121212421242420;CP=2;
2016.01.28 21:51:36 4: sduino/msg READ: MU;P0=-3892;P1=-587;P2=154;P4=508;P5=-1933;D=121214145400454045454545404045454045454545454545404040454540454545454045404045454;CP=4;

2016.01.28 21:52:12 4: sduino/msg READ: MU;P0=-1947;P1=480;P2=-3894;P3=-9072;D=01010101012121210101210101010121012121010131;CP=1;

2016.01.28 22:00:22 4: sduino/msg READ: MU;P0=489;P1=-1938;P2=-3890;P3=-9076;D=01010102020201010201010101020102020101030;CP=0;

Würde mich sehr freuen wenn ich den Sensor auch mit Signalduino nutzen könnte.
Vielen Dank!

**Comment by sidey79** [comment]
Hi, 

mit welcher Version der Firmware passiert das?

**Comment by localhosthack0r** [comment]
Sorry, vergessen mit anzugeben:

VERSION   V 3.2.0-b11 SIGNALduino - compiled at Jan 15 2016 22:44:39 


Habe übrigens auch noch einen Logilink WS0002, der wird einwandfrei als MS und dann CUL_TCM97001 NC_WS erkannt.

**Comment by sidey79** [comment]
Das ist ein seltsames verhalten.

Könntest Du mal ein paar mehr zusammenhängende Loheinträge Posten, ich habe das Gefühl zwischendurch fehlen interessante Daten.

**Comment by localhosthack0r** [comment]
So, habe bei dem Sensor jetzt Batterien gewechselt und direkt neben den Signalduino gestellt, jetzt werden MS Nachrichten erkannt! 

Log, diesmal ungekürzt:

2016.01.31 22:33:00 3: sduino: setting Verbose to: 5
2016.01.31 22:34:31 1: PERL WARNING: Use of uninitialized value in string eq at fhem.pl line 4463.
2016.01.31 22:34:31 3: LUXTRONIK2 HEIZUNG: UpdateDone.1034 autoSynchClock triggered (delayDeviceTimeCalc 864 > 60).
2016.01.31 22:34:32 3: LUXTRONIK2 HEIZUNG: UpdateDone.1048 Do not dare to synchronize. Device clock of host 192.168.178.26 differs by 864.0 seconds (max. is 600).
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:39 1: Error:  has no TYPE
2016.01.31 22:34:46 4: sduino: ping ...
2016.01.31 22:34:46 4: sduino/msg get raw: 
2016.01.31 22:35:45 4: sduino/msg READ: MU;P0=-3861;P1=361;P3=-2115;P4=-9424;D=0101010101010131013131313131313131313131313131313131313131313141010101;CP=1;
2016.01.31 22:35:45 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.01.31 22:35:45 4: sduino/msg READ: MS;P1=367;P2=-2077;P4=-9415;P5=-4014;D=141515151515151515121512121212121212121212121212121212121212121212;CP=1;SP=4;O;
2016.01.31 22:35:46 4: sduino/msg READ: MS;P0=378;P1=-2068;P2=-9397;P3=-4008;D=020303030303030303010301010101010101010101010101010101010101010101;CP=0;SP=2;O;
2016.01.31 22:35:46 4: sduino/msg READ: MS;P0=-2080;P1=367;P3=-9392;P4=-4020;D=131414141414141414101410101010101010101010101010101010101010101010;CP=1;SP=3;O;
2016.01.31 22:35:47 4: sduino/msg READ: MS;P0=364;P1=-4052;P2=-2088;P3=-9405;D=030101010101010101020102020202020202020202020202020202020202020202;CP=0;SP=3;O;
2016.01.31 22:35:48 4: sduino/msg READ: MS;P1=377;P2=-2070;P3=-4022;P4=-9391;D=141312121212121213131212121212121213131313121312121212131212131212;CP=1;SP=4;O;
2016.01.31 22:35:48 4: sduino/msg READ: MS;P0=377;P1=-4015;P2=-2066;P3=-9401;D=030102020202020201010202020202020201010101020102020202010202010202;CP=0;SP=3;
2016.01.31 22:36:19 4: sduino/msg READ: MS;P2=408;P3=-2043;P4=-3991;P5=-9364;D=252423232323232324242323232323232324242424242324232324232324232324;CP=2;SP=5;O;
2016.01.31 22:36:19 4: sduino/msg READ: MS;P0=-3998;P1=402;P2=-2045;P3=-9365;D=131012121212121210101212121212121210101010101210121210121210121210;CP=1;SP=3;
2016.01.31 22:36:50 4: sduino/msg READ: MS;P1=-1925;P2=399;P4=-3997;P5=-9346;D=252421212121212124242121212121212124242424242124212124212124212124;CP=2;SP=5;O;
2016.01.31 22:36:50 4: sduino/msg READ: MS;P0=-2037;P1=329;P2=-3998;P3=-9362;D=131210101010101012121010101010101012121212121012101012101012101012;CP=1;SP=3;
2016.01.31 22:37:21 4: sduino/msg READ: MS;P2=409;P3=-2048;P4=-3990;P5=-9355;D=252423232323232324242323232323232324242424232424232424242424242324;CP=2;SP=5;O;
2016.01.31 22:37:21 4: sduino/msg READ: MS;P0=-2038;P1=405;P2=-3987;P3=-9364;D=131210101010101012121010101010101012121212101212101212121212121012;CP=1;SP=3;
2016.01.31 22:37:51 4: sduino/msg READ: MU;P0=-2034;P1=-4133;P2=399;P4=128;P5=-870;D=21454545400211202020202020212120202020202020212121212021212021212121212120212;CP=2;
2016.01.31 22:37:51 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.01.31 22:37:51 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.01.31 22:37:51 5: sduino: Starting demodulation at Position 2
2016.01.31 22:37:52 4: sduino/msg READ: MS;P0=403;P1=-3994;P2=-2050;P3=-9355;D=030102020202020201010202020202020201010101020101020101010101010201;CP=0;SP=3;O;
2016.01.31 22:37:52 4: sduino/msg READ: MS;P0=-2030;P1=333;P2=-3994;P3=-9356;D=131210101010101012121010101010101012121212101212101212121212121012;CP=1;SP=3;
2016.01.31 22:38:23 4: sduino/msg READ: MS;P0=-1696;P1=399;P3=-4000;P4=-9359;D=141310101010101013131010101010101013131313101310131313101310101010;CP=1;SP=4;O;
2016.01.31 22:38:23 4: sduino/msg READ: MS;P0=396;P1=-3990;P2=-2049;P3=-9369;D=030102020202020201010202020202020201010101020102010101020102020202;CP=0;SP=3;
2016.01.31 22:38:54 4: sduino/msg READ: MS;P2=401;P3=-2054;P4=-3995;P5=-9368;D=252423232323232324242323232323232324242424232423242424232423232323;CP=2;SP=5;O;
2016.01.31 22:38:54 4: sduino/msg READ: MS;P0=-2047;P1=399;P2=-4002;P3=-9378;D=131210101010101012121010101010101012121212101210121212101210101010;CP=1;SP=3;
2016.01.31 22:39:24 4: sduino/msg READ: MU;P0=-2044;P1=401;P2=-4630;P3=112;P4=-884;D=1234343434121201010101010121210101010101010121212121010121212101010121012101;CP=1;
2016.01.31 22:39:24 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.01.31 22:39:24 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.01.31 22:39:24 5: sduino: Starting demodulation at Position 2
2016.01.31 22:39:25 4: sduino/msg READ: MS;P0=408;P1=-3990;P2=-2043;P3=-9361;D=030102020202020201010202020202020201010101020201010102020201020102;CP=0;SP=3;O;
2016.01.31 22:39:25 4: sduino/msg READ: MS;P0=-2050;P1=252;P2=-3997;P3=-9364;D=131210101010101012121010101010101012121212101012121210101012101210;CP=1;SP=3;
2016.01.31 22:39:31 1: PERL WARNING: Use of uninitialized value in string eq at fhem.pl line 4463.
2016.01.31 22:39:31 3: LUXTRONIK2 HEIZUNG: UpdateDone.1034 autoSynchClock triggered (delayDeviceTimeCalc 864 > 60).
2016.01.31 22:39:32 3: LUXTRONIK2 HEIZUNG: UpdateDone.1048 Do not dare to synchronize. Device clock of host 192.168.178.26 differs by 863.0 seconds (max. is 600).
2016.01.31 22:39:46 4: sduino: ping ...
2016.01.31 22:39:46 4: sduino/msg get raw: 
2016.01.31 22:39:56 4: sduino/msg READ: MS;P1=396;P2=-2042;P3=-4000;P4=-9371;D=141312121212121213131212121212121213131313121213131312121213121312;CP=1;SP=4;O;
2016.01.31 22:39:56 4: sduino/msg READ: MS;P0=397;P1=-2051;P2=-3999;P3=-9370;D=030201010101010102020101010101010102020202010102020201010102010201;CP=0;SP=3;
2016.01.31 22:40:27 4: sduino/msg READ: MS;P2=399;P3=-2042;P4=-3998;P5=-9366;D=252423232323232324242323232323232324242424232323242324232423232424;CP=2;SP=5;O;
2016.01.31 22:40:27 4: sduino/msg READ: MS;P0=-2037;P1=411;P2=-3991;P3=-9367;D=131210101010101012121010101010101012121212101010121012101210101212;CP=1;SP=3;
2016.01.31 22:40:58 4: sduino/msg READ: MS;P1=-2033;P2=418;P3=-3979;P4=-9351;D=242321212121212123232121212121212123232323212121232123212321212323;CP=2;SP=4;O;
2016.01.31 22:40:58 4: sduino/msg READ: MS;P0=-2046;P1=402;P2=-3990;P3=-9357;D=131210101010101012121010101010101012121212101010121012101210101212;CP=1;SP=3;
2016.01.31 22:41:29 4: sduino/msg READ: MS;P1=396;P2=-4001;P3=-2036;P4=-9360;D=141213131313131312121313131313131312121213121212121312131213131313;CP=1;SP=4;O;
2016.01.31 22:41:29 4: sduino/msg READ: MS;P0=405;P1=-3989;P2=-2045;P3=-9369;D=030102020202020201010202020202020201010102010101010201020102020202;CP=0;SP=3;
2016.01.31 22:42:00 4: sduino/msg READ: MS;P0=-3231;P2=412;P5=-9356;D=252020202020202020202020202020202020202020202020202020202020202020;CP=2;SP=5;O;
2016.01.31 22:42:00 4: sduino/msg READ: MS;P0=-3996;P1=399;P2=-2051;P3=-9361;D=131012121212121210101212121212121210101012101010101210121012121212;CP=1;SP=3;
2016.01.31 22:42:31 4: sduino/msg READ: MS;P1=-3650;P2=403;P3=-2044;P5=-9367;D=252123232323232321212323232323232321212123212121212321232123232323;CP=2;SP=5;O;
2016.01.31 22:42:31 4: sduino/msg READ: MS;P0=-3993;P1=399;P2=-2046;P3=-9377;D=131012121212121210101212121212121210101012101010101210121012121212;CP=1;SP=3;
2016.01.31 22:43:01 4: sduino/msg READ: MU;P0=-2789;P1=-4004;P2=390;P4=100;P5=-296;D=204520020202020202112120202020202020212121202121212120212021202020202;CP=2;
2016.01.31 22:43:01 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.01.31 22:43:01 5: sduino: Starting demodulation at Position 2
2016.01.31 22:43:01 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.01.31 22:43:01 4: sduino: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2016.01.31 22:43:01 5: sduino: Starting demodulation at Position 2
2016.01.31 22:43:01 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.01.31 22:43:01 5: sduino: Starting demodulation at Position 2
2016.01.31 22:43:01 4: sduino: Fingerprint for MU Protocol id 34 -> unknown34 matches, trying to demodulate
2016.01.31 22:43:01 5: sduino: Starting demodulation at Position 2
2016.01.31 22:43:01 4: sduino: Fingerprint for MU Protocol id 37 -> weather37 matches, trying to demodulate
2016.01.31 22:43:01 5: sduino: Starting demodulation at Position 2
2016.01.31 22:43:02 4: sduino/msg READ: MS;P0=393;P1=-4002;P2=-2051;P3=-9366;D=030102020202020201010202020202020201010102010101010201020102020202;CP=0;SP=3;O;
2016.01.31 22:43:02 4: sduino/msg READ: MS;P0=-3995;P1=392;P2=-2046;P3=-9354;D=131012121212121210101212121212121210101012101010101210121012121212;CP=1;SP=3;
2016.01.31 22:43:33 4: sduino/msg READ: MS;P1=404;P2=-2039;P3=-3988;P4=-9355;D=141312121212121213131212121212121213131312131313121312131212131212;CP=1;SP=4;O;
2016.01.31 22:43:33 4: sduino/msg READ: MS;P0=325;P1=-3997;P2=-2039;P3=-9362;D=030102020202020201010202020202020201010102010101020102010202010202;CP=0;SP=3;
2016.01.31 22:44:04 4: sduino/msg READ: MS;P0=-3217;P2=394;P5=-9361;D=252020202020202020202020202020202020202020202020202020202020202020;CP=2;SP=5;O;
2016.01.31 22:44:04 4: sduino/msg READ: MS;P0=-3993;P1=403;P2=-2041;P3=-9364;D=131012121212121210101212121212121210101012101010121012101212101212;CP=1;SP=3;
2016.01.31 22:44:31 1: PERL WARNING: Use of uninitialized value in string eq at fhem.pl line 4463.
2016.01.31 22:44:31 3: LUXTRONIK2 HEIZUNG: UpdateDone.1034 autoSynchClock triggered (delayDeviceTimeCalc 864 > 60).
2016.01.31 22:44:31 3: LUXTRONIK2 HEIZUNG: UpdateDone.1048 Do not dare to synchronize. Device clock of host 192.168.178.26 differs by 863.0 seconds (max. is 600).
2016.01.31 22:44:35 4: sduino/msg READ: MS;P2=411;P3=-2037;P4=-3990;P5=-9363;D=252423232323232324242323232323232324242423242424232423242323242323;CP=2;SP=5;O;
2016.01.31 22:44:35 4: sduino/msg READ: MS;P0=-3996;P1=331;P2=-2037;P3=-9363;D=131012121212121210101212121212121210101012101010121012101212101212;CP=1;SP=3;
2016.01.31 22:44:46 4: sduino: ping ...
2016.01.31 22:44:46 4: sduino/msg get raw: 
2016.01.31 22:45:06 4: sduino/msg READ: MS;P0=405;P1=-2050;P2=-3989;P3=-9366;D=030201010101010102020101010101010102020201020202010201020101020101;CP=0;SP=3;O;
2016.01.31 22:45:06 4: sduino/msg READ: MS;P0=-3992;P1=403;P2=-2036;P3=-9360;D=131012121212121210101212121212121210101012101010121012101212101212;CP=1;SP=3;
2016.01.31 22:45:37 4: sduino/msg READ: MS;P1=-3643;P2=403;P3=-2043;P5=-9364;D=252123232323232321212323232323232321212123212123232321212121212321;CP=2;SP=5;O;
2016.01.31 22:45:37 4: sduino/msg READ: MS;P0=-3986;P1=413;P2=-2036;P3=-9342;D=131012121212121210101212121212121210101012101012121210101010101210;CP=1;SP=3;
2016.01.31 22:46:07 4: sduino/msg READ: MS;P1=401;P2=-3997;P3=-2050;P4=-9360;D=141213131313131312121313131313131312121213121213131312121212121312;CP=1;SP=4;O;
2016.01.31 22:46:08 4: sduino/msg READ: MS;P0=410;P1=-3991;P2=-2038;P3=-9366;D=030102020202020201010202020202020201010102010102020201010101010201;CP=0;SP=3;
2016.01.31 22:46:38 4: sduino/msg READ: MS;P0=-2045;P2=402;P3=-3991;P4=-9371;D=242320202020202023232020202020202023232320232320232320202023202023;CP=2;SP=4;O;
2016.01.31 22:46:39 4: sduino/msg READ: MS;P0=-3999;P1=324;P2=-2042;P3=-9365;D=131012121212121210101212121212121210101012101012101012121210121210;CP=1;SP=3;
2016.01.31 22:47:09 4: sduino/msg READ: MS;P1=398;P2=-2050;P3=-4005;P4=-9365;D=141312121212121213131212121212121213131312131312131312121213121213;CP=1;SP=4;O;
2016.01.31 22:47:10 4: sduino/msg READ: MS;P0=-3997;P1=404;P2=-2041;P3=-9374;D=131012121212121210101212121212121210101012101012101012121210121210;CP=1;SP=3;

**Comment by sidey79** [comment]
Danke,

ohne es jetzt weiter analysiert zu haben, nehme ich an, dass dein Sensor vermutlich dieses Signal sendet:

MS;P1=367;P2=-2077;P4=-9415;P5=-4014;D=141515151515151515121512121212121212121212121212121212121212121212;CP=1;SP=4;O;�
2016.01.31 22:35:46 4: sduino/msg READ: �MS;P0=378;P1=-2068;P2=-9397;P3=-4008;D=020303030303030303010301010101010101010101010101010101010101010101;CP=0;SP=2;O;�

Ich schau mir das die Tage noch an, scheint nach diesen Angaben aber ein anderes Protokoll als NC_WS etc. zu sein.

**Comment by localhosthack0r** [comment]
Ich kopier mal aus 14_FHEMduino_Env.pm:

# AURIOL (Lidl Version: 09/2013)
  #                /--------------------------------- Channel, changes after every battery change      
  #               /        / ------------------------ Battery state 1 == Ok      
  #              /        / /------------------------ Battery changed, Sync startet      
  #             /        / /  ----------------------- Unknown      
  #            /        / / /  /--------------------- neg Temp: if 1 then temp = temp - 4096
  #           /        / / /  /---------------------- 12 Bit Temperature
  #          /        / / /  /            /---------- ??? CRC 
  #         /        / / /  /            /      /---- Trend 10 == rising, 01 == falling
  #         01010101 1 0 00 000100001011 110001 00
  # Bit     0        8 9 10 12           24     30

Leider blicke ich noch nicht ganz durch, wie ich jetzt von den Daten aus dem Signalduino Log auf eine Binärfolge komme.

**Comment by sidey79** [comment]
Das Demodulieren baue ich dir noch ein.... morgen oder so :)

**Comment by localhosthack0r** [comment]
2016.02.07 21:21:26 4: sduino/msg READ: MS;P1=392;P2=-4006;P3=-2057;P4=-9370;D=141213131313131312121313131313131312121212121313131213131213131313;CP=1;SP=4;O;
2016.02.07 21:21:26 4: sduino: Matched MS Protocol id 38 -> weather38
2016.02.07 21:21:26 4: sduino: Decoded MS Protocol id 38 dmsg s8180F89000 length 32
2016.02.07 21:21:26 4: CUL_TCM97001 using longid: 1 model: Mebus


Wird jetzt erkannt, super! Vielen, vielen Dank! :-)

**Comment by sidey79** [comment]
Aber Medbus ist doch falsch?

**Comment by localhosthack0r** [comment]
Am Namen hab ich mich jetzt nicht gestört, die Werte für die Temperaturen haben jetzt auch nicht abwegig ausgesehen.
Ich werds mal weiterhin beobachten.

Oder ist der Mebus vielleicht ein ganz anderer Sensor, aus der Nachbarschaft?

Wären Logs mit speziellen Settings hilfreich?

**Comment by sidey79** [comment]
Hmm, mebus wäre meiner Meinung nach ein anderer Sensor, aber vielleicht nutzen mebus und Auriol das gleiche Format..

Probier doch mal folgenden Patch. Ob es dein Sensor ist, kannst Du auch feststellen in dem Du den Sensor erwärmst.

http://forum.fhem.de/index.php/topic,48813.msg405010.html#msg405010

**Comment by localhosthack0r** [comment]
Hi,
danke für den Patch, damit siehts jetzt so aus:

2016.02.13 09:55:23 4: sduino/msg READ: MS;P0=332;P1=-2043;P2=-3987;P3=-9362;D=030201010101010102020101010101010102020102020102020102020101010102;CP=0;SP=3;
2016.02.13 09:55:23 4: sduino: Matched MS Protocol id 38 -> weather38
2016.02.13 09:55:23 4: sduino: Decoded MS Protocol id 38 dmsg s8180DB6100 length 32
2016.02.13 09:55:23 4: sduino: Dropped (s8180DB6100) due to short time or equal msg
2016.02.13 09:55:23 4: sduino/msg READ: MS;P0=-2142;P1=531;P2=-9248;P5=-3895;D=12101510151010101015151010151010101010101015151;CP=1;SP=2;
2016.02.13 09:55:53 4: sduino/msg READ: MS;P0=402;P1=-3988;P2=-2049;P3=-9359;D=030102020202020201010202020202020201010201010201010201010202020201;CP=0;SP=3;O;
2016.02.13 09:55:53 4: sduino: Matched MS Protocol id 38 -> weather38
2016.02.13 09:55:53 4: sduino: Decoded MS Protocol id 38 dmsg s8180DB6100 length 32
2016.02.13 09:55:53 2: CUL_TCM97001 auriol verify
2016.02.13 09:55:53 2: CUL_TCM97001 auriol 21.9
2016.02.13 09:55:53 4: CUL_TCM97001 using longid: 1 model: AURIOL
2016.02.13 09:55:54 4: sduino/msg READ: MS;P0=-2059;P1=395;P2=-3988;P3=-9357;D=131210101010101012121010101010101012121012121012121012121010101012;CP=1;SP=3;
2016.02.13 09:55:54 4: sduino: Matched MS Protocol id 38 -> weather38
2016.02.13 09:55:54 4: sduino: Decoded MS Protocol id 38 dmsg s8180DB6100 length 32
2016.02.13 09:55:54 4: sduino: Dropped (s8180DB6100) due to short time or equal msg
2016.02.13 09:56:24 4: sduino/msg READ: MS;P1=-3136;P2=400;P5=-9359;D=252121212121212121212121212121212121212121212121212121212121212121;CP=2;SP=5;O;
2016.02.13 09:56:25 4: sduino/msg READ: MS;P0=-4000;P1=319;P2=-2041;P3=-9364;D=131012121212121210101212121212121210101210101210101210101212121210;CP=1;SP=3;
2016.02.13 09:56:55 4: sduino/msg READ: MS;P2=398;P3=-2051;P4=-4000;P5=-9371;D=252423232323232324242323232323232324242324242324242324242323232324;CP=2;SP=5;O;
2016.02.13 09:56:55 4: sduino: Matched MS Protocol id 38 -> weather38
2016.02.13 09:56:55 4: sduino: Decoded MS Protocol id 38 dmsg s8180DB6100 length 32
2016.02.13 09:56:55 2: CUL_TCM97001 auriol verify
2016.02.13 09:56:55 2: CUL_TCM97001 auriol 21.9
2016.02.13 09:56:55 4: CUL_TCM97001 using longid: 1 model: AURIOL
2016.02.13 09:56:56 4: sduino/msg READ: MS;P0=-3999;P1=403;P2=-2040;P3=-9372;D=131012121212121210101212121212121210101210101210101210101212121210;CP=1;SP=3;
2016.02.13 09:56:56 4: sduino: Matched MS Protocol id 38 -> weather38
2016.02.13 09:56:56 4: sduino: Decoded MS Protocol id 38 dmsg s8180DB6100 length 32
2016.02.13 09:56:56 4: sduino: Dropped (s8180DB6100) due to short time or equal msg



Das Device, das per Autocreate vorher als Mebus angelegt wurde wird weiter verwendet, hat jetzt aber noch unter Attributes 

model AURIOL

stehen.


Nochmal vielen Dank für deine Mühe! :-)

**Comment by sidey79** [comment]
Kannst Du deine Erkenntnisse noch in dem verlinkten Post schildern?
