### ISSUE TITLE
SIGNALduino.pm - refresh BrowserView

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#633]
## Expected Behavior
- Aktualisierung nur des aktiven BrowserFenster bzw. Tab wo man sich befindet

## Actual Behavior
-  alle offenen FHEM Fenster werden aktualisiert, was zur Folge hat, das bei der Benutzung mit mehreren Usern auf dem Server zu Kollisionen kommt.
- User werden durch den Refresh vom "Auszuführenden" herausgewurfen von Fensterständen oder Logfilepositionen
(@elektron-bbs und @HomeAutoUser haben dies mehrfach bei der Zusammenarbeit)

--> Übeltäter
`FW_directNotify("#FHEMWEB:$FW_wname", "location.reload('true')", "");`

Im Edge, wird man komplett herausgewurfen auf die "Startseite von FHEM" und beim Firefox wird man von der aktuellen View "zurückgesetzt" an den Anfang der Seite wenn der andere ein Refresh erzeugt via get availableFirmware.

## Steps to Reproduce the Problem

  1. Browser mit mindestens 2 FHEM Fenster öffenen (Devices oder Logfile)
  2. get availableFirmware
  3. Browserfenster beobachten (am besten sieht man dies, wenn das Logfile offen ist)

## Specifications

  - Versionmodul (FHEM Module):
v3.4.1_dev_11.08

**Comment by sidey79** [comment]
Interessant, ich habe verstanden, dass alle Browserfenster den refresh bekommen und nicht nur das, was gerade offen ist?

**Comment by HomeAutoUser** [comment]
@sidey79 genau richtig so ist das Verhalten.

**Comment by sidey79** [comment]
Ich habe es erfolgreich nachgestellt und analysiert.
Eine Lösung dagegen habe ich nicht direkt gefunden und daher im Forum das gewünschte Verhalten geschildert.

**Comment by sidey79** [comment]
Ich habe deinen Beitrag eben erst zugespielt bekommen:

https://forum.fhem.de/index.php?topic=48736.0

Ich halte mich aus der Lösungsfindung dann erst mal raus, da es wenig bringt die Situation doppelt zu klären

**Comment by sidey79** [comment]
Folgenden Beitrag hatte ich zu diesem Problem verfasst:

https://forum.fhem.de/index.php?topic=103368.new;topicseen#new

**Comment by HomeAutoUser** [comment]
Ich schließe den Faden weil die Anpassung erfolgte.
