### ISSUE TITLE
InternalTimers are not removed 14_SD_WS_Maverick

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#637]
## Expected Behavior

Calling `SD_WS_Maverick_Undef` should remove all running internal timers:
Referenz:
https://wiki.fhem.de/wiki/DevelopmentModuleIntro#X_Undef

## Actual Behavior

internals Timers are not removed by `SD_WS_Maverick_Undef`

## Steps to Reproduce the Problem

  1. define maverick device
  2. dispatch message `P47#599599A959996699A969`
  3. undef maverick device
 

## Specifications
https://github.com/RFD-FHEM/RFFHEM/blob/dev-r34/FHEM/14_SD_WS_Maverick.pm#L100-L110

**Comment by git-developer** [comment]
Should be fixed by commit [20a256f](https://github.com/RFD-FHEM/RFFHEM/pull/635/commits/20a256f498865ee1cc07063be3742dbbbceb4e70) of issue #635.

**Comment by sidey79** [comment]
Ja das stimmt. Vielen Dank.
