### ISSUE TITLE
TFA 30.3233.01 support (rain sensor DROP)

### ISSUE THREAD

**Issue by michapr** [RFD-FHEM/RFFHEM#639]
##  Specifications for new sensor  

  - manufacturer: TFA
  - model name: 30.3233.01
  - pictures of the device / the board (very helpful) 
https://www.tfa-dostmann.de/produkt/regensender-30-3233/

  
433MHz rain sensor with better resolution - can it be supported in near future`?

Thanks,
Michael

**Comment by sidey79** [comment]
Hi,

Do you have messages in the logfile from this Sensor

**Comment by michapr** [comment]
Hi,
sorry, I haven't ... :(
It is a request from a customer who is using SIGNALDuino and want now to integrate now this new device...

I'm using still RFXCom and have no SignalDuino at hand ...

Michael

**Comment by sidey79** [comment]
Currently we have no information about the sensor, how it modulates the signal and how the data is encoded.

To implement a sensor, we need the raw messages which are seen at verbose 4 or higher.

If we can find the signal in the logfile, we can try to implement decoding of the sensordata. Die this we need the measured data whithhin the known representation on a working receiver device.

**Comment by HomeAutoUser** [comment]
@michapr 
Hello, is your request still up to date?
If your user is still interested, please contact us or we can close the Issues?

**Comment by elektron-bbs** [comment]
Sollte eigentlich erledigt sein:
https://github.com/RFD-FHEM/RFFHEM/pull/802
https://forum.fhem.de/index.php/topic,107998.msg1032422.html#msg1032422
