### ISSUE TITLE
Call SD_Keeloq_binsplit_JaroLift only if verbose >=5

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#640]
Die Funktion SD_Keeloq_binsplit_JaroLift muss nur aufgerufen, werden, wenn der Verbose Level 5 gesetzt ist.

https://github.com/RFD-FHEM/RFFHEM/blob/710a597818241e775f49b2c25d641b9044a64ed2/FHEM/14_SD_Keeloq.pm#L586

und

https://github.com/RFD-FHEM/RFFHEM/blob/710a597818241e775f49b2c25d641b9044a64ed2/FHEM/14_SD_Keeloq.pm#L777

Da die Daten nur bei Verbose 5 ausgegeben werden.

**Comment by HomeAutoUser** [comment]
Habe ich auf dem Zettel und werde es heute Abend einarbeiten

**Comment by sidey79** [comment]
Cool.
Es eilt nicht. Mir ist es nur aufgefallen und bevor ich es vergesse machte ich das issue als Merker auf.
