### ISSUE TITLE
PERL WARNING - 00_SIGNALduino.pm

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#648]
## Expected Behavior
- fix Warning

## Actual Behavior
`2019.09.09 18:04:40 1: PERL WARNING: Use of uninitialized value $name in hash element at ./FHEM/00_SIGNALduino.pm line 4097.`

--> entspricht der Zeile

https://github.com/RFD-FHEM/RFFHEM/blob/b0b295bcdd9164d691e65ee980b06ff4f9598d39/FHEM/00_SIGNALduino.pm#L4094-L4097

in der **sub SIGNALduino_TestLength**.

## Steps to Reproduce the Problem

  1. update SIGNALduino
  2. fhem restart
  3. view in Logfile

## Specifications

  - Versionmodul (FHEM Module):
v3.4.1_dev_06.09

**Comment by sidey79** [comment]
@HomeAutoUser 
Ich habe es mal mittels Code Permalink eingebaut .
Hmm, ich hatte schon befürchtet, dass es zu Fehlern kommen könnte, wenn ich nicht auf $name prüfe.

Und diesen Fall scheint es auch genau einmal zu geben.
https://github.com/RFD-FHEM/RFFHEM/blob/b0b295bcdd9164d691e65ee980b06ff4f9598d39/FHEM/00_SIGNALduino.pm#L2153

**Comment by sidey79** [comment]
Es gibt zwei arten diesem Problem zu begegnen:

1. Variante:

```
 	my $hash=$defs{$name) if ($logMsg ne ""); 
```

2. Variante
```
 	my $hash=$defs{$name) if (exists($defs{$name}); 
```

**Comment by HomeAutoUser** [comment]
Variante 2  würde ich nehmen.

Soll ich einen PR machen oder wollen wir die Varianten gegenüberstellen was vor / nachteile der Varianten sind? Wenn es welche gibt überhaupt ;-)

**Comment by sidey79** [comment]
Den PR mach ich, kein Problem. Variante 2 passt für mich auch eher. Variante 1 funktioniert ja nur, weil der letzte Parameter "" ist. 
Warum ich da nicht undef genommen hatte... wenn ich es überhaupt war :)
