### ISSUE TITLE
get raw befehle

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#651]
Ich bin mir nicht sicher, ob wir diesen Abschnitt noch brauchen. Ich nehme an, wir brauchen es nicht:

https://github.com/RFD-FHEM/RFFHEM/blob/ee404c6878b6ab2f540d62bc9a3b046ed9bc7ff9/FHEM/00_SIGNALduino.pm#L964-L974

**Comment by HomeAutoUser** [comment]
Lauf der Protokolldatei benötigt es mindestens ein i am Anfang.

`modulematch				=> '^i......',`

Ob dieser "Hack" noch zum tragen kommt, dazu kenne ich die Hintergründe zu wenig.

**Comment by elektron-bbs** [comment]
Wenn ich die 4. Nachricht aus ProtocolData Protokoll 17.1 dispatche, wird ein Device IT_V3_a67e0c0 angelegt.
Ich verstehe jetzt nicht, was dann nicht mehr unterstützt werden sollte.

**Comment by sidey79** [comment]
Dispatch läuft in der Regel nicht über get raw
