### ISSUE TITLE
PERL WARNING - 00_SIGNALduino.pm (isn't numeric in numeric ge) - very sporadic

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#652]
## Expected Behavior
- the circumstances regulate or clarify

## Actual Behavior
`2019.09.11 00:26:37 1: PERL WARNING: Argument "2^BMu" isn't numeric in numeric ge (>=) at ./FHEM/00_SIGNALduino.pm line 2489.

2019.09.12 22:56:29 1: PERL WARNING: Argument "3^BMu" isn't numeric in numeric ge (>=) at ./FHEM/00_SIGNALduino.pm line 2489.
`

root cause --> line:
`$rssi = ($rssi>=128 ? (($rssi-256)/2-74) : ($rssi/2-74)); # todo: passt dies so? habe ich vom 00_cul.pm`

https://github.com/RFD-FHEM/RFFHEM/blob/ee404c6878b6ab2f540d62bc9a3b046ed9bc7ff9/FHEM/00_SIGNALduino.pm#L2041

## Steps to Reproduce the Problem

  1. FHEM with SIGNALduino receive
  2. "wait for unknown event"
  3.

## Specifications

  - Microcontroller: Arduino Nano
  - Version (Firmware):
V 3.3.1-experimental SIGNALduino cc1101 (chip CC1101) - compiled at Jun 16 2019 00:11:55
  - Versionmodul (FHEM Module):
v3.4.1_dev_09.09

**Comment by sidey79** [comment]
Was kommt den vom uC als Rawmessage in diesem Fall?

**Comment by HomeAutoUser** [comment]
Leider haben wir zu dem Zeitpunkt keinen "Mitschnitt" der Rawmessage.

Entweder ich modifiziere mit mal ein Programm, das ich es so lange laufen lassen muss bis der Fehler auftritt oder ich muss nochmal drüber nachdenken wie ich zu diesem "Falle" an die dortigen Zustände gelange.

Problem, der Fall ist sehr schwer reproduzierbar.

**Comment by HomeAutoUser** [comment]
Ich erlaube mir diesen Faden erstmal zu schließen, weil der Fall sehr schlecht zu provozieren ist.
Sollte ich dahinter kommen um es nachzuvollziehen von "extern" so öffne ich dieses ISSUES erneut.

**Comment by HomeAutoUser** [comment]
`2020.01.23 12:55:25 1: PERL WARNING: Argument "4^BMu" isn't numeric in numeric gt (>) at ./FHEM/00_SIGNALduino.pm line 2580.`

Der Fehler ist noch vorhanden und aus diesem Grund ReOpened ich diesen Faden. 
Vielleicht können wir mal die uC Seite eingrenzen zu können.

Bei diesem Fehler vielleicht "Hilfswerte" einsammeln aber welche da sinn machen würde, kann nur @sidey79 überblicken.
