### ISSUE TITLE
get "spezialbefehle"

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#653]
Es gibt hier diverse Spezialbefehle die mich ziemlich beschäftigt haben:

https://github.com/RFD-FHEM/RFFHEM/blob/ee404c6878b6ab2f540d62bc9a3b046ed9bc7ff9/FHEM/00_SIGNALduino.pm#L896-L940

Teilweise bekomme ich die auch nicht zum laufen und der code Abschnitt passt für fast alle get .... Befehle

**Comment by HomeAutoUser** [comment]
Hallo,
inwieweit bekommst du die Befehle nicht zum laufen?
Wobei können wir dir hier helfen? Ich werde aus deinen Worten nicht richtig schlau worin du uns fragst.

**Comment by sidey79** [comment]
Aus der Angabe von file und regexp werde ich nicht schlau.

Ein File habe ich nicht geschafft anzubinden. Ob wir das im Signalduino Modul überhaupt brauchen ist mir auch nicht so klar. Dasfür gibt es doch das SIGNALDuino_Tool schätze ich.

Frage 1)
Wie funktionierts

Frage 2)
Brauchen wir es überhaupt

**Comment by HomeAutoUser** [comment]
Also nach dem ersten beleuchten, sehe ich da bei manchen keinen so richtigen Sinn.
Lass uns es mal nach und nach durchleuchten @sidey79. Bei einSprüchen, bitte @all zu Wort melden :-)

Bei
`if (IsDummy($name) && $a[1] ne "protocolIDs")`

fällt die Abfrage der Version

```
if ($arg =~ m/^version=/) {           # set version 
 		$arg2 = substr($arg,8); 
 		$hash->{version} = "V " . $arg2; 
 	} 
```

weg weil bei einem richtigen Empfänger, steht dort im Hash der Versionsname. Nichts desto trotz, ist $arg leer und kann nicht zu dem Ergebnis kommen. (Vielleicht ein Schreibfehler ?)

`version | V 3.3.1-experimental SIGNALduino cc1101 (chip CC1101) - compiled at Jun 16 2019`

Das denke ich, könnte man herausnehmen.

**Comment by HomeAutoUser** [comment]
@sidey79 ich habe nun erstmal Durchschaut wie es zu den Ergebnissen kommt, wie es standard mäßig drin steht.

Teste mal bitte
`get raw version=344`
oder
`get raw regexp=TEST` ...
...
`get raw ?` 
ergibt

```
dummy get raw

raw message       e.g. MS;P0=-392;P1=...
dispatch message  e.g. P7#6290DCF37
version=x.x.x     sets version. e.g. (version=3.2.0) to get old MC messages
regexp=           set fileRegexp for get raw messages from file. e.g. regexp=^MC
file=             gets raw messages from file in the fhem directory
```
nur so kommt der Code zu einem Ergebnis.

Sinn dahinter ... dern Kennt nur der Erschaffer.

**Comment by sidey79** [comment]
Ich denke nicht, dass wir ein Internal oder Reading anlegen müssen, wenn wir keine Werte abfragen können.

Ich würde auch zunächst eher mal prinzipiell durchgehen was wie funktionieren soll und ob es gebraucht wird, bevor wir was am Code ändern.
Ich hab da schon was angefangen und dabei festgestellt, dass ich die Funktionsweise nicht so recht kenne.

**Comment by sidey79** [comment]
`get raw version=344`
und
`get raw regexp=TEST ...`

beides probiert.

`get raw file=` findet bei mir keine Datei.             

Dateien kann doch das Signalduino Tool laden.
Ich würde das beim Recoden der Get Funktion erst mal ausbauen.


`get dummyDuino version ?` liefert im übrigen das identische wie `get raw ?`
