### ISSUE TITLE
ELV-Wettersensoren-Protokoll

### ISSUE THREAD

**Issue by wherzig** [RFD-FHEM/RFFHEM#66]
Hallo,

ist es aufwändig einen Bit-Decoder für das ELV-Wettersensoren-Protokoll bereitzustellen? Die Module gibt es ja bereits im FHEM. Ich habe einige S555TH-Sensoren, die ich auf 433 Mhz umgebaut haben. Könnte aber auch für diejenigen sinnvoll sein, die einen 868-Mhz-Receiver an SIGNALduino stecken.

Beschrieben ist das Funksignal hier:
http://www.dc3yc.homepage.t-online.de/protocol.htm

Wenn Ihr Logs aus SIGNALduino braucht, müsste ich mal per Notebook und S555th-Sensor in eine Sensorfreiezone fahren.....

Grüße

Willi

**Comment by sidey79** [comment]
Ja, mach das mal. Was die Beschreibung so angibt, sieht es gut aus.
Wenn das alles stimmt, könnte man es auch anhand vom Datenblatt implementieren

**Comment by pejonp** [comment]
schau mal in diese Modul 13_KS300.pm dort wird der KS300 (S555TH)  dekodiert. Auf 868MHz kann dieser mit einem CUL empfangen werden.

**Comment by sidey79** [comment]
Was genau soll ich in diesem Modul nachsehen?

**Comment by pejonp** [comment]
Ich hatte gedacht das Modul kann zur Dekodierung der vom Signalduino übergebenen Nachricht genutzt werden, es müsste kein neues entwickelt werden.

**Comment by sidey79** [comment]
Ja, das sollte gehen.
Leider kennen wir aber das Signal noch nicht...

**Comment by elektron-bbs** [comment]
Das ist genau das Protokoll, an dem ich gerade dran bin - Protokoll für WS7000-20  #136
