### ISSUE TITLE
"Firmware update was succesfull" auch bei fehlgeschlagenem Firmwareupdate

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#661]
## Actual Behavior
"Firmware update was succesfull" auch bei fehlgeschlagenem Firmwareupdate

## Steps to Reproduce the Problem

  1. flash SIGNALduino
  2. show SIGNALduino-Flash.log
  3. Connecting to programmer: .
Found programmer: Id = "Mu;°πλ"; type = 
    Software Version = .M; Hardware Version = u.;
avrdude: error: buffered memory access not supported. Maybe it isn't
a butterfly/AVR109 but a AVR910 device?
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

avrdude: error: programmer did not respond to command: leave prog mode
avrdude: error: programmer did not respond to command: exit bootloader

## Specifications

  - Microcontroller: radinoCC1101
  - Version (Firmware): V 3.3.1-RC10 SIGNALduino cc1101 (433Mhz) - compiled at Dec 29 2018 01:43:31

  - Versionmodul (FHEM Module): v3.4.1_dev_31.08

**Comment by elektron-bbs** [comment]
Es wäre schön, wenn einem das Log von avrdude, wie früher direkt nach dem Flashen angezeigt würde.

**Comment by sidey79** [comment]
Der State wird ,mit PR 662 je nach Ausgang angepasst.
Das Anzeigen des Logs nach dem Flashen wird tricky, da wir den Flashvorgang Asynchron zur Browsersitzung machen.

Das würde vielleicht mit asyncOutput gehen, aber ganz sicher bin ich mir da nicht, da der Browser auf nichts mehr wartet.

**Comment by elektron-bbs** [comment]
So tragisch ist das mit der Anzeige des Logs nicht. Ich fand das halt früher gut, jetzt klickt man halt nochmal auf den Link.
Ich denke, wir können das Thema als erledigt betrachten.
