### ISSUE TITLE
Wetterstation von Lidl AURIOL AHFL 433 B2 IAN 314695 

### ISSUE THREAD

**Issue by Kreidler1221** [RFD-FHEM/RFFHEM#663]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: AURIOL AHFL 433 B2 IAN 314695 
  - model name: AHFL 433 B2 IAN 314695 
  - pictures of the device / the board (very helpful)
https://www.lidl.de/de/auriol-funk-wetterstation/p309089?searchTrackingQuery=Wetterstationen&searchTrackingId=Product.309089&searchTrackingPos=1&searchTrackingOrigPos=1&searchTrackingRelevancy=97.5&searchTrackingPage=1&searchTrackingPageSize=36&searchTrackingOrigPageSize=36

  
## Specifications 

  - Microcontroller:
  - Version (Firmware): arduino nano (signalduino) 
  

  - Versionmodul (FHEM Module): v3.4.1_dev_09.09
  
V3.3.1-RC Signalduino compiled at Dec 29 2018 01:43:10

**Comment by Kreidler1221** [comment]
Hallo Github-Gemeinde,
habe mir die oben beschriebene Funkwetterstation besorgt.
Leider wurden ihr Sendeprotokoll nicht in Fhem erkannt.
Vielleicht können wir zusammen dies ändern und das Protokoll dekodieren.

Anbei der erste Log.
[Auriollog1.log](https://github.com/RFD-FHEM/RFFHEM/files/3693230/Auriollog1.log)

Ich habe anhand der Logdatei ein Teil des Signals bereits dekodiert.
[Auriol dekode1.txt](https://github.com/RFD-FHEM/RFFHEM/files/3693241/Auriol.dekode1.txt)

Hier erkennt man dass vermutlich:
bit 1-8 id
bit 10-11 ?
bit 12-13 Kanal
bit 14-24 Temperatur
bit 25-31 Feuchte
32 - 43 ?

Bitte hilft mir weiter.

**Comment by elektron-bbs** [comment]
Ich habe die Daten aus deinen Logs mit den von dir vermuteten Bedeutungen der Bits in eine Excel-Tabelle gepackt:
[Auriol_IAN-314695.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/3693638/Auriol_IAN-314695.xlsx)
Du müsstest erst einmal prüfen, ob die Berechnungen soweit plausibel sind. Wenn ja, kannst du die Liste ergänzen, in dem du jeweils die DMSG in der Form "W51#0700DF7A4E0" aus deinem Log in die Liste übernimmst.

Zu klären sind dann außerdem noch einige Fragen:
1. random ID: Bit 0-7 oder vieleicht 0-9, ändert sich diese bei Batteriewechsel des Sensors?
2. welches Bit ändert sich bei Betätigen der TX-Taste am Sensor?
3. ändert sich ein Bit bei Betätigen der °C/°F - Taste am Sensor?
4. welches Bit (oder auch mehrere) ändert sich bei zu geringer Batteriespannung des Sensors?
5. stimmt die Auswertung des Kanal-Schalters?

**Comment by Kreidler1221** [comment]
Hallo und Danke für die Hilfe.
Ich habe weitere Meßwerte in die Tabelle eingefügt.
[Auriol_IAN-314695_weitere_Messwerte.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/3694164/Auriol_IAN-314695_weitere_Messwerte.xlsx)


zu 1. ja,
Bit 0-7 ändern sich bei Batt.wechsel

zu 2.
keine Änderung entdeckt?!

zu 3.
Nein keine Änderung bei °C/°F

zu 4. noch offen

zu 5.
Ja, Kanaländerungen sind stimmig

Die negativen Temp.-werte sind noch nicht richtig interpretiert
Habe festgestellt dass man mit:
Tempwert_negativ= [4096-Bitwert(bit14-24)] /10
den negativen Temperaturwert errechnen kann

Was muss ich noch liefern ausser Punkt 4?

**Comment by elektron-bbs** [comment]
zu 1. hast du das mehrmals probiert? Ich möchte sicher gehen, das es wirklich Bit 0 bis 7 ist.
zu 2. bitte nochmal testen. Bei den meisten Sensoren wird dabei ein Bit gesetzt.
zu 3. erledigt
zu 4. dazu bräuchte ich noch Nachrichten oder Ergänzungen in der Excel-Tabelle
zu 5. erledigt

Die Temperaturberechnung habe ich jetzt in der Tabelle ergänzt.
[Auriol_IAN-314695_weitere_Messwerte.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/3694586/Auriol_IAN-314695_weitere_Messwerte.xlsx)

Hier wäre vorab eine Testversion:
[SD_WS_53.zip](https://github.com/RFD-FHEM/RFFHEM/files/3694588/SD_WS_53.zip)
Bitte die beiden Dateien in deinem System ersetzen. Nach einem Neustart von FHEM sollte dir dann ein SD_WS_53_x angelegt werden.

Wir müssten dann noch verifizieren, ob Nibble 8 (Bit 32-35) wirklich immer 0100 sind. Ich könnte das dann noch in eine Prüfung einbauen.
Die letzten 6 Bit (36-41) könnten irgend eine Prüfung sein. Damit habe ich mich aber noch nicht beschäftigt. Vieleicht findest du ja eine Lösung.

Die Firmware deines SIGNALduino solltest du bitte auch noch auf aktuellen Stand bringen und dann ein Log des Sensors posten (Attribut "addvaltrigger" auf "1" gesetzt, damit auch RAWMSG im Log erscheinen).

**Comment by Kreidler1221** [comment]
Habe die SD_WS_53 Daten in Fhem eingebunden.
Super, er legte SD_WS_53_TH3 an.
Inzwischen habe ich auf V3.3.2.1-rc.... geflasht
zu 4: Batteriewechsel-->
Neuer Stand "Auriol_IAN-314695_weitere_Messwerte3" sind von Zeile 50 bis 59 Batteriewechsel mit schwachen Batterien enthalten.
Danach kommt ein Batt.-Wechsel auf volle Batt. und in Zeile77 - 86 weitere Batteriewechsel  Es ist deutlich zu erkennen wie sich Bit 8 ändert.
zu 1 (ID): Die ID bleibt bei Bit 0 -7 
 zu 2 (TX-Taste): Ich sehe weiterhin keine Änderungen der Bits, welche sich auf die TX-Taste beziehen könnten.
[Auriol_IAN-314695_weitere_Messwerte3.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/3697624/Auriol_IAN-314695_weitere_Messwerte3.xlsx)

**Comment by elektron-bbs** [comment]
Zur Firmware, bitte durch die Versionsnummerierung nicht irritieren lassen. Die Version "3.3.1-exp" ist die aktuelle Version hier. Version 3.3.2.1-rc8 stammt aus einem anderen Zweig. Diese kannst du nach Abschluss der Tests hier natürlich auch gern verwenden.

Die Auswertung des Batteriebits habe ich jetzt eingebaut. Ident (Bit 0-7) und TX-Taste können wir dann abhaken. Das Modul prüft jetzt Nibble 8 auf die Bitfolge "0100". Sollte die Prüfung nicht passen, erfolgt eine Log-Ausgabe in dieser Art:
SD_WS_Parse 3E444CC007C protocolid 53 (Auriol IAN 314695) - ERROR prematch
Bitte mal darauf achten.

[14_SD_WS_191007.zip](https://github.com/RFD-FHEM/RFFHEM/files/3699068/14_SD_WS_191007.zip)

Bleibt noch offen: Die letzten 6 Bit (36-41) könnten irgend eine Prüfung sein.

**Comment by Kreidler1221** [comment]
Die Datei habe ich in Fhem eingebunden. Es funktioniert gut.
Bisher gab es noch keine Meldung ...protocolid 53 (Auriol IAN 314695) - ERROR prematch

Ein herzliches Danke für die sehr gute und schnelle Hilfe.

Für die letzten 6 Bits habe ich noch keine Dekodierung gefunden.
Eine Frage beschäftigt ich noch:
Hätte ich beispielsweise 5 von diesen Funksensoren dieser Bauart ( Sensor hat ja nur 3 Kanäle) gleichzeitig in betrieb. Kann man diese 5 Sensoren auch mit Fhem aufzeichnen? und wie ginge das?

**Comment by elektron-bbs** [comment]
Ich denke, ich habe jetzt auch die Checksumme richtig gedeutet.
[Auriol_IAN-314695.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/3721086/Auriol_IAN-314695.xlsx)

Bitte teste nochmal ausführlich mit dieser Datei im Archiv:
[14_SD_WS_191012.zip](https://github.com/RFD-FHEM/RFFHEM/files/3721088/14_SD_WS_191012.zip)
Wenn alles zufriedenstellend funktioniert, werden wir das Protokoll dann erstmal in die Entwicklerversion überführen.

**Comment by Kreidler1221** [comment]
Checksumme sieht gut und richtig aus, Prima!
Die neue Datei ist installiert und arbeitet bisher fehlerfrei.
Muss noch ein paar Tests machen und melde mich dann wieder.

**Comment by elektron-bbs** [comment]
Ich will nicht drängeln, aber wie ist der Stand deiner Tests?

**Comment by Kreidler1221** [comment]
Habe gerade nochmal Tests gemacht.
Batt.-Wechsel,
Kanalwechsel,
Neg. Temp.
(addvaltrigger war 1 und development war 1)
Hat alles funktioniert und korreckt angezeigt.

wie kann ich aber bei solchen Tests verhindern, dass bei großen Werteänderungen egal ob Temperatur oder Humity, nichts mehr angezeigt wird und die Meldung kommt:
2019.11.04 09:30:39 3 : sduino: SD_WS_53_TH_3 ERROR - Hum diff too large (old 77, new 81, diff 4.0)
oder
2019.11.04 09:30:39 3 : sduino: SD_WS_53_TH_3 ERROR - Temp diff too large (old 16, new 21, diff 5.0)

**Comment by sidey79** [comment]
Es gibt dafür zwei Attribute:
https://fhem.de/commandref_DE.html#SD_WS

max-deviation-temp
max-deviation-hum

**Comment by elektron-bbs** [comment]
Dann spricht ja sicher nichts mehr dagegen, das wir das Protokoll in die Entwicklerversion übernehmen?

**Comment by Kreidler1221** [comment]
Danke vielmals für die Hilfe elektron-bbs und sidey79.
JA, Du kannst das Protokoll in der Entwicklerversion aufnehmen.

**Comment by elektron-bbs** [comment]
Das Protokoll wurde jetzt in die Entwicklerversion überführt.
Ich schließe dieses Issue.

**Comment by marco402** [comment]
hello
If you are interested, I have decoded the messages from the 433 tech temperature sensor (your link https://www.gitmemory.com/issue/RFD-FHEM/RFFHEM/547/474374179)
I put a version of rtl_433 on (https://github.com/marco402/rtl_433).
FYI, you had to change 00 to 0 and 10 to 1.

**Comment by marco402** [comment]
For information
I transferred a new version of my project:
https://github.com/marco402/Rtl_433_dll-for-plugin-SdrSharp pour la dll rtl_433
and
https://github.com/marco402/plugin-Rtl433-for-SdrSharp for SdrSharp plugin
