### ISSUE TITLE
Wetterstation WH3080 - Forum#67587

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#664]
##  Specifications for new sensor / switch / or other device ... 

- Forumsbeitrag
https://forum.fhem.de/index.php/topic,67587.msg980092.html#msg980092

 @Ralf9 @pejonp 
Da Ihr beiden hier https://forum.fhem.de/index.php/topic,67587.msg980092.html#msg980092 aktiv seit und eine modifizierte Version der **14_SD_WS09.pm** in den Umlauf bringt, macht Ihr bitte auch hier auf Github den PR dazu um nicht automatisch zu einer ungewollten Differenz zu kommen. Es wäre schade wenn auf diesen Weg vielleicht etwas verloren geht da vielleicht parallel weiterentwickelt wird an einer anderen Stelle des Modules.

MfG

**Comment by Ralf9** [comment]
Ich habe eigentlich nicht vor einen PR auf Github zu machen.
Dies ist nur ein Vorschlag für pejonp. Ob er es so übernimmt oder es modifiziert, möchte ich Ihm überlassen, es ist sein Modul.

**Comment by HomeAutoUser** [comment]
Es wäre schön, wenn wir hier eine Lösung finden, da erneut die Benutzer anfragen.
https://forum.fhem.de/index.php/topic,67587.msg1015862.html#msg1015862
