### ISSUE TITLE
Commandref link is not unique

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#673]
## Expected Behavior

Selecting the module ping shoud open the commandref of module ping

## Actual Behavior

Commandref jumps to signalduino pings description

## Steps to Reproduce the Problem

Load https://fhem.de/commandref_DE.html#ping

## Specifications

  - Versionmodul (FHEM Module): ?

https://forum.fhem.de/index.php?topic=58397.new;topicseen#new

**Comment by sidey79** [comment]
In Branch https://github.com/RFD-FHEM/RFFHEM/tree/dev-r34_commandrefLinks  sind die commandref Links nun eineindeutig. Allerdings findet FHEM die Hinweise so nicht, wenn z.B. ein Attribut ausgewählt wird.

@elektron-bbs 
@HomeAutoUser 

Habt ihr eine Idee ob es da noch eine Lösung geben könnte?

**Comment by HomeAutoUser** [comment]
@sidey79 
ich habe schonmal versucht danach zu schauen aber bin noch am testen. Auf anhieb was schlüssiges habe ich nicht gefunden.

Denkst du nicht, das es generell eigendlich alle Module betrifft welche das nach dem bisherigen Schema nutzen?

**Comment by sidey79** [comment]
Ja ich schätze es betrifft alle Module.
Hätte ja sein können, dass ich was übersehen habe.

**Comment by HomeAutoUser** [comment]
Ich habe mich nochmal belesen und auch erörtert mit @elektron-bbs.
Das ganze macht nur Sinn, wenn Rudi dieses Feature erweitert oder eine Entscheidung / Anweisung herausgibt. Es war damals schon umstritten und ich würde im Forum nochmal den Ball zurückwerfen.

Das Feature <a name> ist schon günstig, aber wenn die Commandref stur alles einliest ohne Modulunterscheidung, so beißt sich das weil Entwickler sich nicht absprechen wie die Werte heißen um es dann als Hilfe darzustellen.

**Comment by sidey79** [comment]
Ja, ich bin auch an dem Punkt angekommen, dass es sich nicht um ein Problem des Moduls handelt, sonder darum, dass FHEM mit gleichbenannten Attributen hinsichtlich Commandref nicht umgehen kann.

**Comment by HomeAutoUser** [comment]
Ich habe hier versucht das Thema nochmal anzustoßen.
https://forum.fhem.de/index.php/topic,90592.0.html
