### ISSUE TITLE
additional PERL WARNING after "last" adaptation

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#687]
## Expected Behavior
- Catching this message
- no Warning

## Actual Behavior
Ich glaube mit diesem https://github.com/RFD-FHEM/RFFHEM/commit/4e7a90c5cd3482701bf70112e1c3853ac5e47f17 ist dies aufgetreten.

`PERL WARNING: Use of uninitialized value $a[1] in concatenation (.) or string at ./FHEM/00_SIGNALduino.pm line 562.`

Grund:
https://github.com/RFD-FHEM/RFFHEM/blob/00c28d83d718338054a4dc2e6a9ef97c488d8fcf/FHEM/00_SIGNALduino.pm#L562

## Steps to Reproduce the Problem

  1. update to current dev version
  2. FHEM restart
  3. click on one SIGNALduino Device
  4. look into Logfile

## Specifications

  - Versionmodul (FHEM Module): v3.4.1_dev_28.10

**Comment by sidey79** [comment]
Ich weiss warum es passiert. Danke für den Hinweis

**Comment by HomeAutoUser** [comment]
keine Thema, dafür sind wir da um es duchzutesten :-)

**Comment by sidey79** [comment]
Könnte wir das Issue schließen?
