### ISSUE TITLE
hasCC1101 falsch gesetzt

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#688]
## Actual Behavior
$hash->{hasCC1101} = 1  if ($ver !~ m/cc1101/);

## Steps to Reproduce the Problem

  1. get cconf missing with CC1101

**Comment by elektron-bbs** [comment]
00_SIGNALduino.pm Zeile 1211 aktuell:
$hash->{hasCC1101} = 1  if ($ver !~ m/cc1101/);

sollte geändert werden in:
$hash->{hasCC1101} = 1  if ($ver =~ m/cc110/);

**Comment by sidey79** [comment]
Das sieht plausibel aus.
Was habe ich da nur zusammen getestet , seltsam .

Danke für den Hinweis

**Comment by sidey79** [comment]
So habe die Zeile angepasst und die Tests erweitert.
Ich glaube und hoffe das war alles was angepasst werden musste :)

**Comment by elektron-bbs** [comment]
Nicht ganz, mein CC1100 wird so sicher nicht richtig gedeutet :-)

**Comment by sidey79** [comment]
Hast Du es getestet? Im Versions String sollte cc1101 enthalten sein

**Comment by elektron-bbs** [comment]
Ja, ich hatte nicht bedacht, das das zweimal erscheint. Getestet habe ich es jetzt auch.

**Comment by sidey79** [comment]
Kein Problem. Lieber 2x geschaut. Geht ja leider schnell mit den Fehler.

Ich hatte das mit dem Dummy sogar noch getestet und war wohl der Meinung, dass es richtig ist, dass die cc1101 Kommandos angezeigt werden :)

**Comment by elektron-bbs** [comment]
Mhmm, beim Dummy sollte ja dann eigentlich keinerlei get-Befehl erscheinen und bei set vieleicht nur raw und sendmsg?

**Comment by sidey79** [comment]
Ja, die Befehle sollten meiner Ansicht nach angenommen werden, aber im dropdown nicht erscheinen.

Ich hatte homeautouser in #423 gefragt ob es das trifft.
Kannst ja dort auch mal deine Meinung kund tun :)
