### ISSUE TITLE
Protokoll für MKT Multi Kon Trade Bewegungsmelder

### ISSUE THREAD

**Issue by vwpeter** [RFD-FHEM/RFFHEM#69]
sduino version => V 3.2.0-b12 SIGNALduino - compiled at Feb 13 2016 21:34:09 

`<2>MU;P0=572;P1=-1574;P2=1497;P3=-558;P4=-15940;D=010101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=572;P1=-1573;P2=1496;P3=-558;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=570;P1=-1572;P2=1498;P3=-557;P4=-15944;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=573;P1=-1572;P2=1495;P3=-557;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=572;P1=-1574;P2=1495;P3=-557;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=573;P1=-1571;P2=1497;P3=-556;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=573;P1=-1571;P2=1497;P3=-558;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=573;P1=-1571;P2=1497;P3=-556;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=571;P1=-1572;P2=1495;P3=-561;P4=-15944;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=572;P1=-1572;P2=1495;P3=-560;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=572;P1=-1572;P2=1492;P3=-560;P4=-15944;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=570;P1=-1571;P2=1494;P3=-558;P4=-15944;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=572;P1=-1573;P2=1497;P3=-558;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=572;P1=-1573;P2=1495;P3=-558;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
<2>MU;P0=573;P1=-1571;P2=1497;P3=-556;P4=-15940;D=0101230123010101232323012301230123012323230101040;CP=0;<3><\n>
`

**Comment by vwpeter** [comment]
Verbaut ist ein CS5211AGP Remote Encoding Chip von Semico.
Vielleicht hilft dieser Link weiter: [https://www.disk91.com/2013/technology/hardware/raspberry-pi-receive-433mhz-radio-signal/](url)

**Comment by sidey79** [comment]
Der Link hat mich erst mal nicht weiter gebracht.
Demodulieren wird aber erst mal nicht das Problem sein.

**Comment by sidey79** [comment]
Kannst Du mit der b18 Firmware bitte noch mal ein paar Logs erzeugen.
Dann auch mal mit 2 Tasten, ich möchte ausschließen, dass im Signal ein Fehler enthalten ist.

**Comment by vwpeter** [comment]
Habe die b12 drauf. Wo bekomme ich die b18 her? Habe auf Github leider 
nichts gefunden ...

Am 26.03.2016 um 23:31 schrieb sidey79:

**Comment by sidey79** [comment]
einfach ein 

update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r32/controls_signalduino.txt

ausführen und dann flashen.

**Comment by vwpeter** [comment]
Hier die Ausgaben für vier Bewegungsmelder. Dazu jeweils die Codes, die 
ein Arduino-Script mit der <RCSwitch.h> ausgibt.

1. <RCSwitch.h>: 1340764

<2>MU;P0=1488;P1=-566;P2=424;P4=-1579;D=24242440124012424240101012401240124012401010124242;CP=2;<3><\n>
<2>MU;P0=-15952;P1=564;P2=-1581;P3=1486;P4=-566;D=0121212341234121212343434123412341234123434341212101;CP=1;<3><\n>
<2>MU;P0=-1579;P1=565;P2=1486;P3=-564;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1579;P1=565;P2=1487;P3=-566;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1579;P1=565;P2=1486;P3=-564;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1579;P1=566;P2=1489;P3=-563;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1579;P1=565;P2=1486;P3=-566;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1576;P1=566;P2=1489;P3=-564;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1577;P1=566;P2=1487;P3=-566;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1578;P1=565;P2=1491;P3=-562;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1578;P1=567;P2=1489;P3=-563;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1580;P1=564;P2=1487;P3=-563;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1578;P1=565;P2=1489;P3=-561;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1578;P1=567;P2=1488;P3=-564;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1578;P1=566;P2=1490;P3=-563;P4=-15952;D=01010231023101010232323102310231023102323231010141;CP=1;<3><\n>
<2>MU;P0=-1816;P2=752;P3=521;P5=-3965;D=33530353030353030303530353530352030303035353;CP=3;<3><\n>


2. <RCSwitch.h>: 12898652
<2>MU;P0=-1591;P1=488;P2=1508;P3=-567;D=10100231010232310231010102310231023232310101;CP=1;<3><\n>
<2>MS;P0=-16121;P1=1578;P2=-510;P3=485;P4=-1594;D=30121234343412343412123412343434123412341212123434;CP=3;SP=0;O;<3><\n>
<2>MS;P0=1584;P1=-502;P2=510;P3=-1594;P4=-16122;D=24010123232301232301012301232323012301230101012323;CP=2;SP=4;O;<3><\n>
<2>MS;P0=-1593;P1=485;P2=1509;P3=-565;P4=-16119;D=14232310101023101023231023101010231023102323231010;CP=1;SP=4;<3><\n>
<2>MU;P0=-570;P1=-1594;P2=1506;P3=457;D=20020313131203131202031203131312031203120202031313;CP=3;<3><\n>
<2>MS;P0=-16117;P1=1577;P2=-510;P3=487;P4=-1594;D=30121234343412343412123412343434123412341212123434;CP=3;SP=0;O;<3><\n>
<2>MS;P0=1585;P1=-502;P2=511;P3=-1592;P4=-16119;D=24010123232301232301012301232323012301230101012323;CP=2;SP=4;O;<3><\n>
<2>MS;P0=-1591;P1=487;P2=1508;P3=-568;P4=-16120;D=14232310101023101023231023101010231023102323231010;CP=1;SP=4;<3><\n>


3. <RCSwitch.h>: 6049116

<2>MU;P0=563;P1=-1569;P2=1478;P3=-563;P4=-15872;D=123012323230101012301012323012301230123232301010040;CP=0;<3><\n>
<2>MU;P0=-1570;P1=1479;P2=-562;P3=562;P4=-15872;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1571;P1=1480;P2=-560;P3=563;P4=-15872;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1573;P1=1479;P2=-563;P3=560;P4=-15872;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1571;P1=1479;P2=-560;P3=562;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1570;P1=1481;P2=-560;P3=564;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1571;P1=1479;P2=-562;P3=563;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1572;P1=1481;P2=-560;P3=563;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1567;P1=1480;P2=-561;P3=565;P4=-15872;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1568;P1=1482;P2=-559;P3=565;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1569;P1=1480;P2=-559;P3=564;P4=-15872;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1567;P1=1481;P2=-559;P3=565;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1568;P1=1480;P2=-561;P3=565;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1570;P1=1482;P2=-560;P3=562;P4=-15868;D=01230121212303030123030121230123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1570;P1=1481;P2=-561;P3=462;P4=-32001;P5=204;D=01230121212303030123030121230123012301212123030345;CP=3;<3><\n>


4. <RCSwitch.h>: 5050716

<2>MU;P0=1499;P1=-563;P2=-1586;P3=-16036;P4=484;P5=-231;D=50114242010142014242420142424201420142010101424243;CP=4;<3><\n>
<2>MU;P0=570;P1=-1582;P2=1500;P3=-564;P4=-16040;D=012301012323012301010123010101230123012323230101040;CP=0;<3><\n>
<2>MU;P0=-1582;P1=1502;P2=-564;P3=570;P4=-16040;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1584;P1=1501;P2=-562;P3=570;P4=-16040;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1583;P1=1500;P2=-564;P3=570;P4=-16040;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1581;P1=1503;P2=-564;P3=570;P4=-16040;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1582;P1=1501;P2=-563;P3=572;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1579;P1=1501;P2=-562;P3=576;P4=-16032;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1586;P1=1501;P2=-562;P3=571;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1583;P1=1502;P2=-561;P3=571;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1582;P1=1501;P2=-563;P3=573;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1583;P1=1503;P2=-561;P3=571;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1585;P1=1502;P2=-561;P3=572;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1582;P1=1500;P2=-564;P3=574;P4=-16036;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>
<2>MU;P0=-1582;P1=1499;P2=-567;P3=570;P4=-16040;D=01230301212301230303012303030123012301212123030343;CP=3;<3><\n>

**Comment by sidey79** [comment]
Ich werde zwar nicht ganz schlau, warum das so wie in den Logs zu sehen empfangen wird, aber ich habe es jetzt mal implementiert.

Bitte mal testen.

**Comment by vwpeter** [comment]
Habe mit der b19 getestet. Bei PIR 1, 3 und 4 wird gar nichts mehr ausgegeben, bei Nummer 2 das hier:

<2>MS;P0=-1590;P1=488;P2=-16110;P3=1738;P4=-497;D=12343410101034101034341034101010341034103434341010;CP=1;SP=2;O;<3><\n><2>MS;P0=522;P1=-1559;P2=1589;P3=-497;P4=-16108;D=04232301010123010123230123010101230123012323230101;CP=0;SP=4;O;<3><\n>

FHEM macht daraus das:

2016-04-10 20:41:36 SIGNALduino sduino UNKNOWNCODE iC4D15C

**Comment by sidey79** [comment]
Eigentlich sollten alle Sensoren so erkannt werden.

Ich habe schon im vorherigen Post gesehen, dass es nicht klappt.
Das finde ich seltsam.

Könntest Du das Signal einmal mit dem Logikanalyse Sketch und dem Python Programm dazu aufzeichnen und abspeichern?
Ich würde das gerne bei mir nachstellen um den Fehler finden zu können.

Grüße Sidey

**Comment by vwpeter** [comment]
Hab den Sketch nicht zum Laufen gebracht, irgendwie kam der mit dem RingBuffer nicht klar. 
Hab mit dem Oszi mal die 4 PIRs und ein 1kHz Vergleichssignal aufgenommen. 1 Messwert / µs.
Hoffe, das hilft und die Auswertung ist kein Problem. Ansonsten kann ich es auch in Excel o.ä. noch etwas aufbereiten.


[Oszi.zip](https://github.com/RFD-FHEM/RFFHEM/files/215886/Oszi.zip)

**Comment by sidey79** [comment]
Hi,

ich weiss noch nicht, wie ich aus den Rohdaten zu einer Auswertung komme.

Wenn ich es richtig verstanden habe, dann ist jede Zeile ein uS?

Um die Dauer eines Zustandes zu messen müsste man also die Anzahl der Zeilen in Abhängigkeit zur gemessenen Spannung Auswerten?

Grüße Sidey

**Comment by vwpeter** [comment]
Der Code ist eine 24-stellige Binärzahl.
1=1,5 ms H + 0,5 ms L
0=0,5 ms L + 1,5 ms H
Abschluss mit 0,5 ms H
Code wird mehrfach gesendet, Pause dazwischen 16 ms.

Das sind die vier Codes meiner Sensoren:
000101000111010101011100
110001001101000101011100
010111000100110101011100
010011010001000101011100

Dabei gibt es gleiche und unterschiedliche Bereiche:
00 0 10 10 0011101 01 0101 1100
11 0 00 10 0110100 01 0101 1100
01 0 11 10 0010011 01 0101 1100
01 0 01 10 1000100 01 0101 1100

Da kann man jetzt nur vermuten, was Seriennummer und was Gerätecode ist.

**Comment by sidey79** [comment]
Woher weisst Du, was zum Start und was zum Ende des Signals gehört?

Der Start des Signals könnte doch auch mit 0,5 mS high und 16ms low als Startzeichen gesendet werden oder? Das würde somit zumindest den gängigen PT2262 und EV1527 Chips entsprechen.

**Comment by vwpeter** [comment]
Das habe ich nur vermutet, da ich mir nur einen Ausschnitt mit 3-4 Übertragungen angesehen habe.
Das was Du schreibst, passt genau so und ist wohl auch plausibler, wenn es bei den anderen Chips auch so ist.

**Comment by sidey79** [comment]
Problem ist nur, das Signal wurde nur bei einem deiner Tasten so erkannt..

Bitte folgendes machen. Den MS Decoder (geht über FHEM) deaktivieren und dann alle Taster im Abstand von 15 Sekunden drücken.

Das Log hier noch mal posten.
Vielleicht finde ich so heraus, wo es.klemmt.

**Comment by sidey79** [comment]
Ich weiss noch immer nicht, wie ich die oszi Daten auswerten bzw. verarbeiten soll... hmm.

**Comment by kabakakao** [comment]
Ich habe hier auch die Alarmanlage.
Probiere mich gerade an der Fernbedienung für die Scharfschaltung.
Ich habe die aktuelle Version von der "r33" installiert (auch die Firmware aktualisiert).
Leider werden "arm" und "disarm" als zwei verschiedene Schalter erkannt:
ARM:
```
2017.04.01 15:31:44 4 : sduino/msg READ: MS;P0=514;P1=-3881;P2=-9181;P3=-1933;D=02030103010301010303030101010303030303030301010303030101010303030103010101;CP=0;SP=2;O;
2017.04.01 15:31:44 4 : sduino: Matched MS Protocol id 0 -> weather1
2017.04.01 15:31:44 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:31:44 4 : sduino: Decoded MS Protocol id 0 dmsg s56380C717000 length 40
2017.04.01 15:31:44 5 : sduino: converted Data to (s56380C717000)
2017.04.01 15:31:44 5 : sduino: dispatch s56380C717000
2017.04.01 15:31:45 4 : sduino/msg READ: MU;P0=493;P1=-3884;P2=-1935;P3=-9056;D=010202020202020201010202020101010202020102010101030;CP=0;
2017.04.01 15:31:45 4 : sduino: Fingerprint for MU Protocol id 13.1 -> FLAMINGO FA21 b matches, trying to demodulate
2017.04.01 15:31:45 5 : sduino: start pattern for MU Protocol id 13.1 -> FLAMINGO FA21 b mismatches, aborting
2017.04.01 15:31:45 5 : sduino: applying filterfunc SIGNALduino_filterSign
2017.04.01 15:31:45 5 : sduino: applying filterfunc SIGNALduino_compPattern
2017.04.01 15:31:45 5 : sduino: applying filterfunc SIGNALduino_filterMC
2017.04.01 15:31:50 4 : sduino/msg READ: MS;P0=-13472;P2=408;P5=-472;P6=1288;P7=-1338;D=20656527276565276565652765276565656565272727272727;CP=2;SP=0;O;
2017.04.01 15:31:50 4 : sduino: Matched MS Protocol id 3 -> itv1
2017.04.01 15:31:50 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:31:50 4 : sduino: Decoded MS Protocol id 3 dmsg iCDD7C0 length 24
2017.04.01 15:31:50 5 : sduino: converted Data to (iCDD7C0)
2017.04.01 15:31:50 5 : sduino: dispatch iCDD7C0
2017.04.01 15:31:50 4 : sduino IT: message "iCDD7C0" (7)
2017.04.01 15:31:50 4 : sduino IT: msgcode "101F1FF11000" (12) bin = 110011011101011111000000
2017.04.01 15:31:50 5 : sduino IT: SBC_FreeTec housecode = 101F1FF1 onoffcode = 1000
2017.04.01 15:31:50 4 : sduino IT: 101F1FF1 not defined (Switch code: 1000)
2017-04-01 15:31:50 Global global UNDEFINED IT_101F1FF1 IT 101F1FF1 0100 1000
2017-04-01 15:31:54 PROPLANTA pr_AU_Wetter durationFetchReadings: 10.00
2017-04-01 15:31:54 PROPLANTA pr_AU_Wetter lastConnection: 281 values captured in 10.00 s
2017.04.01 15:31:58 4 : sduino/msg READ: MC;LL=-2662;LH=3200;SL=-1220;SH=1707;D=5253BFC8;C=1464;L=31;
2017.04.01 15:31:58 4 : sduino: Found manchester Protocol id 18 clock 1464 -> OSV1
2017.04.01 15:31:58 5 : sduino: extracted data 01010010010100111011111111001000 (bin)
2017.04.01 15:31:58 5 : sduino: OSV1 protocol converted to hex: (08ADAC4037) with length (8) bits
2017.04.01 15:31:58 5 : sduino: converted Data to (08ADAC4037)
2017.04.01 15:31:58 5 : sduino: dispatch 08ADAC4037
2017-04-01 15:31:58 SIGNALduino sduino UNKNOWNCODE 08ADAC4037
2017.04.01 15:31:58 3 : sduino: Unknown code 08ADAC4037, help me!
2017.04.01 15:32:15 4 : sduino/msg READ: MS;P1=-471;P3=1290;P4=414;P5=-1328;P6=-13462;D=46313145453131453131314531453131313131454545454545;CP=4;SP=6;
2017.04.01 15:32:15 4 : sduino: Matched MS Protocol id 3 -> itv1
2017.04.01 15:32:15 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:32:15 4 : sduino: Decoded MS Protocol id 3 dmsg iCDD7C0 length 24
2017.04.01 15:32:15 5 : sduino: converted Data to (iCDD7C0)
2017.04.01 15:32:15 5 : sduino: dispatch iCDD7C0
2017.04.01 15:32:15 4 : sduino IT: message "iCDD7C0" (7)
2017.04.01 15:32:15 4 : sduino IT: msgcode "101F1FF11000" (12) bin = 110011011101011111000000
2017.04.01 15:32:15 5 : sduino IT: SBC_FreeTec housecode = 101F1FF1 onoffcode = 1000
2017.04.01 15:32:15 4 : sduino IT: 101F1FF1 not defined (Switch code: 1000)
2017.04.01 15:32:15 2 : autocreate: define IT_101F1FF1 IT 101F1FF1 0100 1000
2017.04.01 15:32:15 2 : autocreate: define FileLog_IT_101F1FF1 FileLog ./log/IT_101F1FF1-%Y.log IT_101F1FF1
2017-04-01 15:32:15 Global global UNDEFINED IT_101F1FF1 IT 101F1FF1 0100 1000
2017-04-01 15:32:15 Global global DEFINED IT_101F1FF1
2017-04-01 15:32:15 Global global DEFINED FileLog_IT_101F1FF1
2017-04-01 15:32:15 Global global SAVE
```

DISARM:
```
2017.04.01 15:32:54 4 : sduino/msg READ: MS;P0=509;P1=-1935;P2=-3888;P3=-9168;D=03010201020102020101010202020101010101010102020101020101010101010201020202;CP=0;SP=3;O;
2017.04.01 15:32:54 4 : sduino: Matched MS Protocol id 0 -> weather1
2017.04.01 15:32:54 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:32:54 4 : sduino: Decoded MS Protocol id 0 dmsg s56380C817000 length 40
2017.04.01 15:32:54 5 : sduino: converted Data to (s56380C817000)
2017.04.01 15:32:54 4 : sduino: Dropped (s56380C817000) due to short time or equal msg
2017.04.01 15:33:00 4 : sduino/msg READ: MU;P0=-1596;P1=-5506;P2=1684;P3=-2705;P4=3149;P5=-1223;P6=97;P7=-752;D=01234345234325434523252543252525252545234345252167606765;CP=2;
2017.04.01 15:33:00 5 : sduino: applying filterfunc SIGNALduino_filterSign
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: start pattern for MU Protocol id 28 -> IC Ledspot mismatches, aborting
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: Starting demodulation at Position 49
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: start pattern for MU Protocol id 36 -> socket36 mismatches, aborting
2017.04.01 15:33:00 5 : sduino: applying filterfunc SIGNALduino_compPattern
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 39 -> X10 Protocol matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: start pattern for MU Protocol id 39 -> X10 Protocol mismatches, aborting
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 50 -> optus_XT300 matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: Starting demodulation at Position 12
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 61 -> FS10 matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: Starting demodulation at Position 48
2017.04.01 15:33:00 5 : sduino: applying filterfunc SIGNALduino_filterMC
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 64 -> WH2 matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: Starting demodulation at Position 7
2017.04.01 15:33:00 4 : sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2017.04.01 15:33:00 5 : sduino: Starting demodulation at Position 12
2017.04.01 15:33:00 4 : sduino/msg READ: MC;LL=-2682;LH=3175;SL=-1220;SH=1701;D=52D3BF28;C=1462;L=31;
2017.04.01 15:33:00 4 : sduino: Found manchester Protocol id 18 clock 1462 -> OSV1
2017.04.01 15:33:00 5 : sduino: extracted data 01010010110100111011111100101000 (bin)
2017.04.01 15:33:00 5 : sduino: OSV1 protocol converted to hex: (08AD2C40D7) with length (8) bits
2017.04.01 15:33:00 5 : sduino: converted Data to (08AD2C40D7)
2017.04.01 15:33:00 5 : sduino: dispatch 08AD2C40D7
2017-04-01 15:33:00 SIGNALduino sduino UNKNOWNCODE 08AD2C40D7
2017.04.01 15:33:00 3 : sduino: Unknown code 08AD2C40D7, help me!
2017.04.01 15:33:07 4 : sduino/msg READ: MU;P0=-926;P1=202;P2=-584;P3=-242;P4=116;P6=450;D=1210131104134343134244343113413131643631;CP=4;
2017.04.01 15:33:07 4 : sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2017.04.01 15:33:07 5 : sduino: start pattern for MU Protocol id 16 -> Dooya shutter mismatches, aborting
2017.04.01 15:33:07 5 : sduino: applying filterfunc SIGNALduino_filterSign
2017.04.01 15:33:07 4 : sduino: Fingerprint for MU Protocol id 20 -> livolo matches, trying to demodulate
2017.04.01 15:33:07 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:33:07 4 : sduino: Fingerprint for MU Protocol id 24 -> visivon remote matches, trying to demodulate
2017.04.01 15:33:07 5 : sduino: start pattern for MU Protocol id 24 -> visivon remote mismatches, aborting
2017.04.01 15:33:07 4 : sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2017.04.01 15:33:07 5 : sduino: start pattern for MU Protocol id 28 -> IC Ledspot mismatches, aborting
2017.04.01 15:33:07 4 : sduino: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2017.04.01 15:33:07 5 : sduino: start pattern for MU Protocol id 29 -> HT12e remote mismatches, aborting
2017.04.01 15:33:07 4 : sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2017.04.01 15:33:07 5 : sduino: start pattern for MU Protocol id 30 -> unitec47031 mismatches, aborting
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 34 -> unknown34 matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: start pattern for MU Protocol id 34 -> unknown34 mismatches, aborting
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 37 -> weather37 matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: start pattern for MU Protocol id 37 -> weather37 mismatches, aborting
2017.04.01 15:33:08 5 : sduino: applying filterfunc SIGNALduino_compPattern
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 45 -> Revolt matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: start pattern for MU Protocol id 45 -> Revolt mismatches, aborting
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 49 -> quigg_gt9000 matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: start pattern for MU Protocol id 49 -> quigg_gt9000 mismatches, aborting
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 56 -> Celexon matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: start pattern for MU Protocol id 56 -> Celexon mismatches, aborting
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 61 -> FS10 matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:33:08 4 : sduino: Fingerprint for MU Protocol id 62 -> Clarus_Switch matches, trying to demodulate
2017.04.01 15:33:08 5 : sduino: start pattern for MU Protocol id 62 -> Clarus_Switch mismatches, aborting
2017.04.01 15:33:08 5 : sduino: applying filterfunc SIGNALduino_filterMC
2017.04.01 15:33:29 4 : sduino/msg READ: MU;P0=7;P1=-392;P3=-1925;P4=-3875;P5=-9161;D=01030403040304040303030404040303030303030304040303040303030303030403040404050304030403040403030304040403030303030303040403030403030303030304030404040503040304030404030303040404030303030303030404030304030303030303040304040405030403040304040303030404040303;CP=0;O;
2017.04.01 15:33:29 5 : sduino: applying filterfunc SIGNALduino_filterSign
2017.04.01 15:33:29 5 : sduino: applying filterfunc SIGNALduino_compPattern
2017.04.01 15:33:29 5 : sduino: applying filterfunc SIGNALduino_filterMC
2017.04.01 15:33:29 4 : sduino/msg READ: MS;P0=502;P1=-1936;P2=-3883;P3=-9175;D=03010201020102020101010202020101010101010102020101020101010101010201020202;CP=0;SP=3;O;
2017.04.01 15:33:29 4 : sduino: Matched MS Protocol id 0 -> weather1
2017.04.01 15:33:29 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:33:29 4 : sduino: Decoded MS Protocol id 0 dmsg s56380C817000 length 40
2017.04.01 15:33:29 5 : sduino: converted Data to (s56380C817000)
2017.04.01 15:33:29 5 : sduino: dispatch s56380C817000
2017.04.01 15:33:29 4 : CUL_TCM97001 using longid: 1 model: NC_WS
2017.04.01 15:33:47 4 : sduino/msg READ: MS;P1=-476;P2=1285;P4=400;P5=-1346;P6=-13465;D=46212145452121452121214521452121214545454521214545;CP=4;SP=6;
2017.04.01 15:33:47 4 : sduino: Matched MS Protocol id 3 -> itv1
2017.04.01 15:33:47 5 : sduino: Starting demodulation at Position 2
2017.04.01 15:33:47 4 : sduino: Decoded MS Protocol id 3 dmsg iCDD70C length 24
2017.04.01 15:33:47 5 : sduino: converted Data to (iCDD70C)
2017.04.01 15:33:47 5 : sduino: dispatch iCDD70C
2017.04.01 15:33:47 4 : sduino IT: message "iCDD70C" (7)
2017.04.01 15:33:47 4 : sduino IT: msgcode "101F1FF10010" (12) bin = 110011011101011100001100
2017.04.01 15:33:47 5 : sduino IT: V1 housecode = 101F1FF100 onoffcode = 10
2017.04.01 15:33:47 4 : sduino IT: 101F1FF100 not defined (Switch code: 10)
2017.04.01 15:33:47 2 : autocreate: define IT_101F1FF100 IT 101F1FF100 0F F0
2017.04.01 15:33:47 2 : autocreate: define FileLog_IT_101F1FF100 FileLog ./log/IT_101F1FF100-%Y.log IT_101F1FF100
2017-04-01 15:33:47 Global global UNDEFINED IT_101F1FF100 IT 101F1FF100 0F F0
2017-04-01 15:33:47 Global global DEFINED IT_101F1FF100
2017-04-01 15:33:47 Global global DEFINED FileLog_IT_101F1FF100
2017-04-01 15:33:47 Global global SAVE
```

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
