### ISSUE TITLE
Dummy - Event Fehlermeldung

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#691]
## Expected Behavior
- keine Fehlermeldung

## Actual Behavior
```
2019-11-11 21:18:16 Global global ATTR sduino_dummy addvaltrigger 0
2019-11-11 21:18:16 SIGNALduino sduino_dummy sduino_dummy 5: Unknown argument ? for sduino_dummy
2019-11-11 21:18:34 SIGNALduino sduino_dummy sduino_dummy 4: sduino_dummy: Calling Getting Attr sub with args: set addvaltrigger = 1
2019-11-11 21:18:34 Global global ATTR sduino_dummy addvaltrigger 1
2019-11-11 21:18:35 SIGNALduino sduino_dummy sduino_dummy 5: Unknown argument ? for sduino_dummy
```
- "Unknown argument ? for " deutet auf einen fehlerhaften return

Auftreten ist nur bei einem DUMMY Device!!!!

## Steps to Reproduce the Problem

  1. define Dummy
  2. open eventmonitor
  3. set attribut addvaltrigger
  4. look at eventmonitor

## Specifications

  - Versionmodul (FHEM Module): v3.4.1_dev_28.10

**Comment by sidey79** [comment]
Welchen Befehl genau setzt Du ab?

Mit
`attr dummyDuino set attribut addvaltrigger`

Bekomme ich das nicht hin

**Comment by HomeAutoUser** [comment]
Vorgehensweise:
- im Web via Auswhalfelder
- Auswahl addvaltrigger
- wechseln ins Eingabefeld und setze Wert
- anschließend auf attr klick

**Comment by sidey79** [comment]
Der Event "Unknown argument ? for dummyDuino" kommt immer wenn ein sduino im webif aufgerufen wird. Egal ob ein Attribut gesetzt wird.

**Comment by HomeAutoUser** [comment]
>Der Event "Unknown argument ? for dummyDuino" kommt immer wenn ein sduino im webif aufgerufen wird. Egal ob ein Attribut gesetzt wird.

Soll das gewollt sein bzw. ist das normal?

**Comment by sidey79** [comment]
Hmm, es liegt daran, dass Fhemweb immer ein ? sendet um die Befehle zu erhalten und für einen unbekannten Befehl wird eine Logmeldung ausgegeben. Wenn eventlogging aktiv ist, dann mit Event:

https://github.com/RFD-FHEM/RFFHEM/blob/1a8242ced9f4d531fb4a0fde76e84d7fb3a6d353/FHEM/00_SIGNALduino.pm#L925-L926

Vermutlich kann man auf das Event hier vollständig verzichten und nur die Log3 Funktion hier aufrufen.

**Comment by HomeAutoUser** [comment]
Das muss ich mal ausprobieren. Das mit dem ? kenne ich, ich hatte dann immer "if cmd ne ?" gewählt.
