### ISSUE TITLE
new Sensor TCM218943

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#692]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer:
  - model name: TCM218943
  - pictures of the device / the board (very helpful)

  
## Specifications 

  - Microcontroller:
  - Version (Firmware): V 3.3.1-dev SIGNALduino cc1101 - compiled at Mar 10 2017 22:54:50
  
  - Versionmodul (FHEM Module):

https://forum.fhem.de/index.php/topic,101425.msg992007.html#msg992007
https://manual.pilight.org/protocols/433.92/weather/tcm.html

**Comment by Ralf9** [comment]
```
20,9, 25
CUL/RAW: /sAEFFE6F2E0F9;  208: 8032
sduino/msg READ: MS;P0=-1072;P2=-8040;P3=211;P4=-2026;D=32303430343030303430303030303030303030303434303034303030303434303430303034;CP=3;SP=2;
sduino Dispatch: u6#5100190D1, test ungleich: disabled


21,0, 25, forced
CUL/RAW: /sAEEFE6F2D0FC;  208: 8032


21,3, 22, bat low, forced
CUL_Parse: nanoCUL433 s6A6FE9F2A0F3;  208: 8064
sduino/msg READ: MS;P0=-580;P2=-962;P5=-7993;P6=271;D=65606262606260626060626260626262626262626062606062626262626060626062606260;CP=6;SP=5;
sduino/msg READ: MS;P0=-972;P1=244;P2=-1986;P3=-8004;D=13121010121012101212101012101010101010101210121210101010101212101210121012;CP=1;SP=3;



27,3, 78, bat low
CUL/RAW: /s6A7FB1EEE007;  224: 8016
sduino/msg READ: MS;P0=216;P1=-1015;P3=-2014;P4=-8066;D=04030101030103010303010101010101010103010103030303010103010303010101030101;CP=0;SP=4;
2019.11.14 19:01:14.602 5: sduino Dispatch: u6#95804F2C4, test ungleich: disabled


21,7, 82, forced
CUL/RAW: /s2DEFADF260FB;  208: 8032
sduino/msg READ: MS;P0=-931;P1=262;P2=-1978;P4=-8000;D=14121210121010121010101012101010101012101210101210101010101212101212101012;CP=1;SP=4;
sduino Dispatch: u6#D210520D9, test ungleich: disabled


21,1, 83, normal
CUL/RAW: /s2DFFADF29018;  208: 8032

20,8, 84, normal
CUL/RAW: /s2DFFABF2F011;  208: 8032

```

**Comment by Ralf9** [comment]
Der TCM218943 wird momentan als ID 6 erkannt, die Daten sind inventiert.
Ich habe bei mir eine neue ID 97 angelegt, damit passt es dann. Ich habe dazu einfach die Werte von der ID 6 genommen und one und zero vertauscht:
```

		"97"	=>	## TCM218943
						# T:22.9, H:24     MS;P0=-970;P1=254;P3=-1983;P4=-8045;D=14101310131010101310101010101010101010101313101010101010101313131010131013;CP=1;SP=4;
						# T:23.0, H:23, tx MS;P0=-2054;P1=236;P2=-1032;P3=-7760;D=13121012101212121012121210121212121212121012101010121212121010101212121010;CP=1;SP=3;
		{
			name			=> 'TCM218943',
			id			=> '97',
			one			=> [1,-5],
			zero			=> [1,-10],
			sync			=> [1,-36],		# This special device has no sync
			clockabs		=> 220,			# -1 = auto
			format 			=> 'twostate',	# tristate can't be migrated from bin into hex!
			preamble		=> 's',			# prepend to converted message	 	
			postamble		=> '00',		# Append to converted message	 	
			clientmodule    => 'CUL_TCM97001',
			#modulematch	=> '^u......',  # not used now
			length_min		=> '24',
			paddingbits     => '8',				 # pad up to 8 bits, default is 4
		}
```

**Comment by elektron-bbs** [comment]
Kommt das dann auch irgendwann in das offizielle TCM-Modul, oder bleibt das bei dir?

Wenn es offiziell wird, könnten wir m.E. auch die ID 6 verwenden. Das Protokoll 6 schlummert seit 2015 halbfertig in der 90_SIGNALduino_un.pm:

## TCM218943
# T:22.9, H:24     MS;P0=-970;P1=254;P3=-1983;P4=-8045;D=14101310131010101310101010101010101010101313101010101010101313131010131013;CP=1;SP=4;
# 2019.11.15 16:55:37 3: SIGNALduino_unknown decoded protocolid: 6  EuroChron, sensor id=51, channel=, temp=22.9, hum=24, bat=ok, sendMode=automatic
# T:23.0, H:23, tx MS;P0=-2054;P1=236;P2=-1032;P3=-7760;D=13121012101212121012121210121212121212121012101010121212121010101212121010;CP=1;SP=3;
# 2019.11.15 16:56:41 3: SIGNALduino_unknown decoded protocolid: 6  EuroChron, sensor id=51, channel=, temp=22.7, hum=23, bat=ok, sendMode=manual

Ansonsten wäre es auch möglich, Protokoll 6 fertig zu stellen und in die 14_SD_WS.pm zu übernehmen.

**Comment by Ralf9** [comment]
> Kommt das dann auch irgendwann in das offizielle TCM-Modul, oder bleibt das bei dir?

Ja, wenn alles im TCM-Modul eingebaut ist, gebe ich nach einer Testphase Bjoern bescheid, daß er es ins SVN bringen kann.

> Wenn es offiziell wird, könnten wir m.E. auch die ID 6 verwenden. 

Ja, dies wäre auch möglich, dazu müsste dann bei der ID 6 one und zero vertauscht werden

**Comment by sidey79** [comment]
Das Protokoll 6 ist als Eurochon bezeichnet.
Von dem denken wir ja zumindest, dass wir wissen was die einzelnen Bits bedeuten.

Vermutlich haben wir nur die Person nie gefunden, die so einen Sensor hat.

Interessant wäre wieso die Modulation vom aculfw als s beginnend interpretiert wird. Da passt die Taktrate eigentlich nicht.
Der aculfw kann ja ja vermutlich ähnlich schlecht zwischem dem unterscheiden, was wir als id6 definiert haben .

In so fern, wäre für mich erst mal die Frage, ob ID6 und  ID97 vielleicht doch identisch sind und die Invertierung nicht eher bei der Auswertung als bei der Demodulation erfolgen müssen.

**Comment by elektron-bbs** [comment]
In der 90_SIGNALduino_un.pm ist bei Protokoll 6 dokumeniert:
# EuroChron / Tchibo
Die Protokollbeschreibung in 90_SIGNALduino_un.pm ist identisch zu der von @Ralf9 verlinkten Beschreibung bei pilight.
Die mit Protokoll 6 dekodierten Werte passen auch zu den Angaben in den von @Ralf9 geposteten Beispielen.

@Ralf9 
Brauchst du die Daten invertiert um zu einem anderen Empfänger kompatibel zu bleiben, oder warum?

**Comment by Ralf9** [comment]
> Brauchst du die Daten invertiert um zu einem anderen Empfänger kompatibel zu bleiben, oder warum?

Ich möchte zum CUL kompatibel bleiben
```
20,9, 25
CUL/RAW: /sAEFFE6F2E0F9;  208: 8032
sduino/msg READ: MS;P0=-1072;P2=-8040;P3=211;P4=-2026;D=32303430343030303430303030303030303030303434303034303030303434303430303034;CP=3;SP=2;
sduino Dispatch: u6#5100190D1

27,3, 78, bat low
CUL/RAW: /s6A7FB1EEE007;  224: 8016
sduino/msg READ: MS;P0=216;P1=-1015;P3=-2014;P4=-8066;D=04030101030103010303010101010101010103010103030303010103010303010101030101;CP=0;SP=4;
sduino Dispatch: u6#95804F2C4
```

**Comment by elektron-bbs** [comment]
OK, dann würde ich vorschlagen, wir passen die ID 6 an und entfernen aus der 90_SIGNALduino_un.pm die Dekodierung.

**Comment by elektron-bbs** [comment]
Ich habe jetzt die vorgeschlagene Definition angepasst:

`	"97"	=>	## TCM 218943, Eurochron
						# T:22.9, H:24     MS;P0=-970;P1=254;P3=-1983;P4=-8045;D=14101310131010101310101010101010101010101313101010101010101313131010131013;CP=1;SP=4;
						# 2019.11.15 16:55:37 3: SIGNALduino_unknown decoded protocolid: 6  EuroChron, sensor id=51, channel=, temp=22.9, hum=24, bat=ok, sendMode=automatic
						# T:22.7, H:23, tx MS;P0=-2054;P1=236;P2=-1032;P3=-7760;D=13121012101212121012121210121212121212121012101010121212121010101212121010;CP=1;SP=3;
						# 2019.11.15 16:56:41 3: SIGNALduino_unknown decoded protocolid: 6  EuroChron, sensor id=51, channel=, temp=22.7, hum=23, bat=ok, sendMode=manual
		{
			name         => 'TCM 218943',
			comment      => 'Weatherstation TCM 218943, Eurochron',
			id           => '97',
			knownFreqs   => '434.92',
			one          => [1,-5],
			zero         => [1,-10],
			sync         => [1,-32],
			clockabs     => 248,
			format       => 'twostate',
			preamble     => 's',  # prepend to converted message	 	
			postamble    => '00', # append to converted message	 	
			clientmodule => 'CUL_TCM97001',
			length_min   => '36', # sync, postamble und paddingbits werden nicht mitgezaehlt
			length_max   => '36', # sync, postamble und paddingbits werden nicht mitgezaehlt
			paddingbits  => '8',  # pad up to 8 bits, default is 4
		}
`
und die Datei 14_CUL_TCM97001.pm von @Ralf9 installiert.

Protokoll 6 und 97 liefern identische Daten.

**Comment by elektron-bbs** [comment]
Wie verfahren wir hier jetzt weiter?

**Comment by sidey79** [comment]
Du stellst einen PR in dem Du deine Anpassung einreichst.

> Protokoll 6 und 97 liefern damit identische Daten

.

**Comment by elektron-bbs** [comment]
OK, geht seinen Gang...

@Ralf9 
bist du mit der Definition einverstanden? Die Timings habe ich bestmöglich mit den von dir geposteten Nachrichten angepasst.
[TCM218943.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/3863340/TCM218943.xlsx)

**Comment by Ralf9** [comment]
ja, müsste so passen

**Comment by elektron-bbs** [comment]
Protokolldefinition wurde in Protokoll #6 realisiert. Ich schließe dieses Issue.
