### ISSUE TITLE
SD_RSL in eigenes Repository

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#695]
Wie auch bereits beim Keeloq Modul andiskutiert würde ich das RSL Modul gerne in ein eigenes Repository verschieben:

https://github.com/fhem

Hintergrund ist, dass es weitgehend unabhängig von den restlichen Modulen in in unserem Repo arbeitet.
Und im aktuellen Fall auch nichts dagegen spricht es im master und SVN zu aktualisieren.

**Comment by sidey79** [comment]
@HomeAutoUser 
@elektron-bbs 
@Ralf9 

Irgendwelche Meinungen dazu?

**Comment by elektron-bbs** [comment]
Welche Vor- und Nachteile hat es für den User oder den Entwickler?
Müssen User und Entwickler sich dann die Module selbst zusammen suchen, oder reicht weiterhin ein Update auf dev-r34 oder master?

**Comment by sidey79** [comment]
Vorteil den ich sehe ist, dass Anpassungen des RSL Modules unabhängiger vom 00_SIGNALduino.pm und den anderen Modulen in den Master kommt.

Die Anpassung der SetExtensions könnte man in einen Master Branch schieben, aber ohne alle anderen Anpassungen geht das hier nicht sauber.

Im RFFHEM Repo würde ich das Modul dann auch entfernen, da man es dann ja auch schneller über den FHEM Update Mechanismus bekommt.

**Comment by HomeAutoUser** [comment]
>Im RFFHEM Repo würde ich das Modul dann auch entfernen, da man es dann ja auch schneller über den FHEM Update Mechanismus bekommt.

Den einzigen Unterschied sehe ich dann dabei, das wir es von hier heraustrennen und der User dann mit einem zusätzlichen updat add "webseite" es normal updaten kann. Sehe ich das richtig so oder habe ich da etwas falsch verstanden?

**Comment by sidey79** [comment]
Er kann es mit einem eigenen update [add] updaten, ja.

Es ist aber auch unabhängiger vom SIGNALDuino Modul was das Thema "master" und svn angeht.

**Comment by sidey79** [comment]
@HomeAutoUser 
Gibts denn etwas was dagegen spricht?  Bis das RSL Modul in diesem Modus nun in einen master branch kommt wird es ja vermutlich noch dauern

**Comment by HomeAutoUser** [comment]
Ich denke es sollte da nichts dagegegn sprechen.
Bei einigen Überlegungen kam ich am ende zum Entschluss das es vielleicht da sogar besser ist wenn man dies separat macht.

Es wäre vielleicht auch dann analog SD_Keeloq und dem SD_GT angepasst, wenn man es so einrichtet. Der einzige Grund als Vorteil sehe ich dabei, das man in dem Projekt wirklich nur das eine Modul hat und es unabhängig updaten kann. Sobald eine "Mischung" vorliegt, so könnte es passieren wenn ein User das Projekt mit update add hinzufügen möchte, FHEM meckert, daas Projekt sei schon eingetragen obwohl es auf einen anderen Branch verweist.

1) Habe ich es richtig vernommen und bei den anderen Projekten abgeschaut, das bestmöglich die FHEM struktur im Github stimmen muss für das "normale Update verfahren"?

2) Wie verläuft die Anpassung der controls Datei welche als Basis genutzt wird, ob eine Änderung am Modul vorgenommen wird?

**Comment by sidey79** [comment]
Zu 1.
Ja die Struktur muss für den Updatebefehl stimmen. Das sollte aber kein großes Problem darstellen.

Zu 2.
Die controls Datei wird wie auch in diesem Repository von einem script, welches auf travis-ci ausgeführt wird, automatisch aktualisiert.

Ich würde das RSL Modul dann mal migrieren

**Comment by HomeAutoUser** [comment]
>Die controls Datei wird wie auch in diesem Repository von einem script, welches auf travis-ci ausgeführt wird, automatisch aktualisiert.
Ich würde das RSL Modul dann mal migrieren

Ist das einfach oder kann ich mir dies irgendwo abschauen? Das würde ich dann auch für das SD_Keeloq mal vornehmen oder Timer Modul, das das automatisch dann passiert ;-)

**Comment by sidey79** [comment]
Einfach ist es immer, wenn man weiss, wie es geht.
Ich schreib mal auf, was gemacht werden muss... so als Vorlage :)

**Comment by elektron-bbs** [comment]
So richtig habe ich das wohl noch nicht verstanden. Angenommen, das SD_GT wird veröffentlicht, dann gehört das doch zum SIGNALduino-Projekt und sollte mit einem Update-Befehl auf den gleichen Stand wie SIGNALduino gehoben werden.
Was passiert mit den ausgelagerten Modulen? Muss dem User dann beigebracht werden, das er mindestens zwei Updates durchführen muss?
Muss ich dann bei Änderungen, die ein Protokoll betreffen, aber z.B. in der SD_ProtocolData.pm und 10_SD_GT.pm Änderungen erforderlich machen an zwei Stellen Pull-Requests durchführen?

**Comment by sidey79** [comment]
Der Einwand von elektron-bbs ist richtig.

Wenn an beiden Modulen etwas geändert werden muss, dann sind zwei PRs und zwei Updates notwendig.

Wie oft kommt das aber vor?
Initial auf jeden Fall und immer, wenn eine neue Protokolldefinition erstellt wird.

Für die Updates könnten wir das ganze lösen, wenn wir die Dateien wieder an einem Ort zusammenführen.

In GitHub releases wird es ein wenig Tricky, da man auf den Tag Namen verweisen muss.
In GitHub Pages könnte man es vermutlich Recht einfach alles zusammen kopieren.


Was das automatische Updaten der Controls und Changes Datei angeht habe ich das gestern Abend noch schnell auf Basis von GitHub Actions zusammengeschraubt.
Das ist deutlich schneller als über Travis CI.

Die Actions kann man noch auslagern und von mehreren Repos gemeinsam verwenden.
Das will ich noch angehen, da es eine nützliche Funktion für so ziemlich jedes FHEM Modul auf GitHub ist.

**Comment by elektron-bbs** [comment]
Ich werde das Gefühl nicht los, das das Ganze dadurch benutzerunfreundlicher wird.

Angenommen, $user kommt mit einer etwas älteren Installation und Raw-Daten eines unbekannten Protokolls. Muss er dann erstmal Firmware, RFD-FHEM, Modul A, Modul B usw. einzelln aktualisieren?
Oder kriegst du es hin, das er mit einem Update-Befehl zumindest alle zu FHEM gehörenden Bestandteile aktualisieren kann?

**Comment by HomeAutoUser** [comment]
Es ist richtig, das das ganze Vor und Nachteile hat. Von @elektron-bbs der Einwand ist natürlich berechtigt.

Ich sehe nur den einzigen Konflikt dabei, das wenn eine solche "Abspaltung" via separaten Branch erfolgt, das man stets achten muss, das der Branch aktuell ist von allen Files.

Zusätzlich muss es auch einschränkungen geben, wenn man dein Project mit 2 verschiedenen Branche via update add in FHEM eintragen möchte, dort der Hinweis kommt, das Project ist schon hinzugefügt. Das müsste man nochmal nachstellen und kontrollieren. Wenn das der Fall sein sollte, so kann nur die Entwicklung innerhalb des Dev Branch integriert bleiben oder man ist gezwungen diesbezüglich es eben auszulagern.

Eine Alternative es "hintenrum" zusammenzuführen ist natürlich auch eine Idee.
Für Benutzerfreundlichkeit bin ich immer zu haben und das wir es nicht schwieriger gestalten üder die unerfahrenen User.

>Einfach ist es immer, wenn man weiss, wie es geht.
Ich schreib mal auf, was gemacht werden muss... so als Vorlage :)

Darauf bin ich gespannt weil in Git Action sehe ich noch nicht durch.

**Comment by elektron-bbs** [comment]
Es geht nicht um separate Branches (SD_GT ist dort erst mal nur zum Test und soll natürlich, wenn es fertig ist, ins normale RFFHEM), sondern, wie der Titel schon sagt, um getrennte Repositorys.

**Comment by HomeAutoUser** [comment]
- um getrennte Repositorys.

Ich habe es schon verstanden :-) Es gibt je unterschiedlicher Zusammenstellung (derzeit Branch, später ggf. Repositorys oder innerhalb Project RFHEM) nur unterschiedliche Einschränkungen.

Ich denke mal, um eine Entscheidung zu setzen mit Punkt, wäre vielleicht die Aussage erstmal sinnvoll, wann die aktuelle DEV ins Master überführt werden soll um das besser zu beleuchten. Bedingung um das Modul zu nutzen ist ja erstmal ein "gewisser DEV" Stand welcher immer vorhanden werden muss. Bevor der Stand nicht im SVN Erreicht ist, so macht ein separtes Repository kein Sinn weil wir dem User etwas anbieten was nicht "kompatibel" ist.

Alle anderen Überlegungen würden glaube ich sich im Kreise drehen ;-)

**Comment by sidey79** [comment]
Man kann es drehen und wenden.

Aktuell ist es so, dass ein Anwender alle Development Versionen laden muss nur um in den Genuss der RSL Erweiterung zu kommen.

Dafür bekommt er alles mit einem Befehl.
Will er nur das eine Modul, dann muss er hand anlegen.

Vom Prinzip ist meine Idee identisch mit dem TCM oder IT Modul. Das liegt in anderen Repos. Muss somit separat aktualisiert werden.

Eigentlich gibt es auch keinen Grund die Protokolldatei nicht anderweitig zu aktualisieren. Der ist es weitgehend egal, welche Modulversion eingesetzt wird.
Vielleicht ist auch das ein Ansatz, dass man bei neuen Modulen die Protokolldatei mit austauscht

**Comment by sidey79** [comment]
Automatisches erstellen der controls Datei habe ich als github action entwickelt:

https://github.com/fhem/fhem-controls-actions

Das lässt sich in jedem github actions workflow einbinden und erstellt die controls Datei.


Das RSL Modul habe ich mal in ein eigenes Repo gelegt und dort einen Worflow hinterlegt der sowohl die controls Datei als auch das CHANGED erstellt. Letzteres taugt aber nicht viel. Da muss man trotzdem von Hand ran.

https://github.com/fhem/mod_RSL/blob/master/.github/workflows/update.yml

**Comment by Ralf9** [comment]
> Das RSL Modul habe ich mal in ein eigenes Repo gelegt

Wenn ich das richtig sehe, hast Du nur 2 commits übernommen:
https://github.com/fhem/mod_RSL/commits/master/FHEM/14_SD_RSL.pm

Mit cherry pick lassen sich die commits
https://github.com/RFD-FHEM/RFFHEM/commits/dev-r34/FHEM/14_SD_RSL.pm
problemlos übernehmen, ist reine Fleissarbeit.
Mit etwas Übung geht es recht zügig.

**Comment by sidey79** [comment]
Genau genommen habe ich keinerlei commits übernommen. :)

Mit einem cherry pick könnten wir die commit message übernehmen.
Der commit ist aber jeweils ein neuer, da es ja ein anderes Repo ist.

Wäre das denn wichtig?

**Comment by Ralf9** [comment]
Es wäre schön, wenn Du einige commits übernehmen könntest.
Ich habe mir die commits mal angeschaut, die letzten beiden wären ausreichend:
 SD_RSL - Support SetExtionsions
 14_SD_RSL - optimize Log set

**Comment by sidey79** [comment]
Ich schau mal, die commit Messages sollten machbar sein.

@HomeAutoUser  @elektron-bbs 

Bezüglich Update von einer Stelle habe ich mir https://github.com/fhem/fhem-mirror/blob/master/fhem/FHEM/98_update.pm angesehen.

Aktuell erwartet das Kommando, dass alle Dateien unter der gleichen URL zu finden sind.

Ich denke, man könnte den Befehl erweitern.
Derzeit wird die Url, von der die einzelnen Dateien geladen werden in Zeile 377 wie folgt zusammengesetzt:
`my $remFile = upd_getUrl("$basePath/$fName");`


$basePath wird dabei von der Url zur controls Datei genommen. z.B.:
`https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r34/`

Wenn wir prüfen ob $fName eine absolute URL darstellt,  könnten wir mit einer kleinen Erweiterung die Datei vom angegebenen Ort laden.
```
my $fileuri;
if ($fname =~ (+^https?:\/\/+) {
  $fileuri = $fname;
  $fname=~ m,(?:.+\/)(.+),;
  $fname=$1; #Extract Filename from Url
} else {
 $fileuri="$basePath/$fName";
}
my $remFile = upd_getUrl("$fileuri");
```

Man müsste nur noch überlegen, wie man es schafft, die Datei an den richtigen Ort zu bekommen.
Eventuell müssten wir da noch einen MOV Befehl in der controls_.txt Datei einbauen.
Mit diesem Syntax landen die Dateien leider nicht in FHEM sondern im "fhem" root Verzeichnis.

**Comment by sidey79** [comment]
@Ralf9 

So die commits habe ich übernommen. Hab dann doch alle gesucht in denen das RSL Modul vorkam.

**Comment by Ralf9** [comment]
Danke, damit ist es perfekt

**Comment by HomeAutoUser** [comment]
>Man müsste nur noch überlegen, wie man es schafft, die Datei an den richtigen Ort zu bekommen.
Eventuell müssten wir da noch einen MOV Befehl in der controls_.txt Datei einbauen.
Mit diesem Syntax landen die Dateien leider nicht in FHEM sondern im "fhem" root Verzeichnis.

Würde denn etwas dagegensprechen wenn man so verfahren würde?

**Comment by sidey79** [comment]
Ich denke es spricht nichts dagegen wenn so verfahren wird.  Die MOV und UPD Befehle müssten wir noch irgendwie in die Controls Datein reinbekommen. 
Vermutlich statisch.

Unter Umständen hilft auch eine Unterteilung in "core" Module und "3rd Party"


Eine Idee die mir gerade kam ist, dass man eine controls_xyz.txt in der controls_signalduino.txt referenziert und nicht die einzelnen Dateien.

Anstelle des UPD Befehls nimmt man einen anderen wie beispielsweise REM für Remote:

```
UPD 2019-11-21_20:14:40 145030  FHEM/lib/SD_ProtocolData.pm
UPD 2019-06-08_09:30:54 5181    FHEM/lib/SD_Protocols.pm
MOV FHEM/firmware/SIGNALduino_nano328.hex unused
REM https://raw.githubusercontent.com/fhem/mod_RSL/master/controls_rsl.txt
```

Für die Einträge mit REM ruft man den Update Befehl einfach erneut auf.
Ist nicht 100% sauber, aber vielleicht noch besser und flexibler, da wir ja sonst die Dateigröße schwer errechnen können.

**Comment by sidey79** [comment]
Ich hab das mit der Anpassung der controls Datei entwickelt.

https://github.com/sidey79/fhem-mirror/pull/1

Könnt es euch ja mal ansehen

**Comment by HomeAutoUser** [comment]
@sidey79 ist Issues hier abgeschlossen mit dem hier https://github.com/fhem/mod_RSL?
Mit SD_Keeloq sind wir "umgezogen" nach https://github.com/fhem/SD_Keeloq.
