### ISSUE TITLE
SD_UT RC_10 Button set all does not work after renaming the device

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#701]
## Expected Behavior
Button set all work after renaming the device

## Actual Behavior
Button set all does not work after renaming the device

## Steps to Reproduce the Problem

  1. create RC_10_7869_all and RC_10_7869_A
  2. rename RC_10_7869_A to RC_WZ
  3. set RC_10_7869_all on or off

## Specifications

  - Microcontroller: no matter
  - Version (Firmware): no matter

  - Versionmodul (FHEM Module): v3.4.1_dev_19.11

**Comment by elektron-bbs** [comment]
@HomeAutoUser 
Mir ist letztens etwas aufgefallen, als ich aus SD_UT etwas in SD_GT verwenden wollte.

		my $device = $model."_".substr($name,6,4);
		if ($name =~ /^$device.all$/) {
			foreach my $d (sort keys %defs) {
				if (defined($defs{$d}) && defined($defs{$d}{NAME}) && $defs{$d}{NAME} =~ /^$device.[ABCD]$/) {
					readingsSingleUpdate($defs{$d}, "state" , $cmd , 1);
					Log3 $name, 4, "$ioname: SD_UT_Set attr_model=$model device $name set ".$defs{$d}{NAME}." to $cmd";
				}
			}
		}

Ich denke, es ist besser, statt $defs{$d}{NAME} dort $defs{$d}{DEF} zu verwenden.
In SD_GT habe ich es dann so umgesetzt:

	if ($hash->{DEF} =~ /_all$/) {	# send button all
		my $systemCode = ReadingsVal($name, "SystemCode", "");
		foreach my $d (keys %defs) {	# sucht angelegte SD_GT mit gleichem Sytemcode 
			if(defined($defs{$d}) && $defs{$d}{TYPE} eq "SD_GT" && $defs{$d}{DEF} =~ /$systemCode/ && $defs{$d}{DEF} =~ /[ABCD]$/ && ReadingsVal($d, "state", "") ne $cmd) {
				readingsSingleUpdate($defs{$d}, "state" , $cmd , 1);
				Log3 $name, 3, "$ioname: SD_GT set $d $cmd";
			}
		}
	}

**Comment by HomeAutoUser** [comment]
Die Anpassung können wir gern vornehmen.
Geht mit deiner Änderung das Rename reibungslos?

@elektron-bbs, SD_UT schein noch ein Bug zu besitzen :-( Mir fiel gestern was auf beim Dispatchen aber dies dann separat in einem PR. Ich möchte damit nur zum Ausdruck bringen, bitte mehrfach und alle "Dummheiten" testen wenn du Bruchteile in SD_GT übernimmt :-)

**Comment by elektron-bbs** [comment]
Du darfst sicher den Abschnitt nicht komplett so aus SD_GT übernehmen, aber das Prinzip funktioniert. Ich hatte es auch kurz im SD_UT getestet - funktioniert damit auch nach Umbenennen des Gerätes.
Wo ich mir nicht sicher war, ist das Parsen beim Empfang. Dort scheint die Lösung in SD_UT aber zu funktionieren.

Wenn ich so etwas nicht doppelt und dreifach testen würde, wäre mir der Fehler sicher nicht aufgefallen :-)

**Comment by HomeAutoUser** [comment]
Ich werde es mir heute Abend oder morgen ansehen.

**Comment by elektron-bbs** [comment]
Ich hätte den Patch jetzt eingebaut, bin mir aber unschlüssig, wo ich den pull request tätige.
Bei dir scheint es keine dev-r34 zu geben.
Eigenartigerweise finde ich die Version, die ich hier habe:
# $Id: 14_SD_UT.pm 20137 2019-09-09 15:58:29Z HomeAuto_User $
auch weder bei dir, noch bei RFD-FHEM. Kann es sein, da die aus dem SVN ist?

**Comment by HomeAutoUser** [comment]
Die Version
`# $Id: 14_SD_UT.pm 20137 2019-09-09 15:58:29Z HomeAuto_User $`
ist die aktuelle SVN Version.

Im normalen SIGNALduino dev-r34 aktuell ist die
`# $Id: 14_SD_UT.pm 19886 2019-08-26 20:21:52Z sidey79 $`

Beide sind identisch bis auf den Zeilenkopf. Diesen hatte ich angepasst im SVN wo es hochgeladen wurde. Du kannst also den Patch auf die Github dev-r34 loslassen.

PS: Sorry, ging unter der Faden.

**Comment by elektron-bbs** [comment]
Ich habe erst mal  nur einen neuen Branch erstellt:
https://github.com/RFD-FHEM/RFFHEM/tree/dev-r34_SD_UT-RC_10

Sieh dir das mal an. Ich habe absichtlich die Zeilen noch nicht eingerückt, damit die Änderungen leichter zu erkennen sind.
Beim Einbau war mir aufgefallen, das my @definition = split(" ", $hash->{DEF}); und if ($cmd ne "?")
if ($cmd ne "?") eigentlich nicht bei jedem Device notwendig wären. Ich habe das zusammengefasst. Deshalb ist die Änderung etwas umfangreicher geworden.

**Comment by elektron-bbs** [comment]
Der Patch ist jetzt in die Entwicklerversion übernommen. Ich schließe das Issue.
