### ISSUE TITLE
neuer ReedKontakt Schalter (Sender 433)  (on/off) evt. Batterie

### ISSUE THREAD

**Issue by RainerPrivat** [RFD-FHEM/RFFHEM#702]
ist es möglich, diesen einzubinden?
Danke.

##  Specifications for new sensor / switch / or other device ... 

  - china:
  - ReedKontakt Sender mit 2 Zuständen. Ggf. auch ein Batterie Signal.
  - blaue LED oben links leuchtet beim senden
[https://www.ebay.de/itm/433MHz-Tür-und-Fensterkontakt-Magnetkontakt-Funk-Sensor-Schalter-Alarm-Sicher/254022908251]
Preis ist gut verhandelbar.

Material: ABS Plastic Color: As Picture ShownOperating Voltage: 1.5VBuild-in Battery: 1 * AAA LR03 AM4 1.5V 800mAh Dry BatteryBattery Life: About 8 monthsStatic Current: ≤10uAOperating Current: ≤15mATransmitting Frequency: 433MHzTransmitting Distance: ≥100m (open area distance)Door Magnet Detecting Distance: 25~35mm / 0..98~1.37inWireless Coding Format: Compatible for PT2262Operating Temperature: -10℃~40℃Humidity: ≤90%rh

  
## Specifications 

  - Microcontroller: cc1101
  - Version (Firmware): 3.3.1 ex
  
  - Versionmodul (FHEM Module):
     3.4.1
```
2019-12-03_16:34:48 SIGNALduino_unknown_5 bitMsg: 010000101101011000001010
2019-12-03_16:34:48 SIGNALduino_unknown_5 bitMsg_invert: 101111010010100111110101
2019-12-03_16:34:48 SIGNALduino_unknown_5 bitCount: 24
2019-12-03_16:34:48 SIGNALduino_unknown_5 hexMsg: 42D60A
2019-12-03_16:34:48 SIGNALduino_unknown_5 hexMsg_invert: BD29F5
2019-12-03_16:34:48 SIGNALduino_unknown_5 hexCount_or_nibble: 6
2019-12-03_16:34:48 SIGNALduino_unknown_5 lastInputDev: cc1101_ip2
2019-12-03_16:34:57 SIGNALduino_unknown_5 UserMSG: **open**
2019-12-03_16:35:00 SIGNALduino_unknown_5 bitMsg: 010000101101011000001110
2019-12-03_16:35:00 SIGNALduino_unknown_5 bitMsg_invert: 101111010010100111110001
2019-12-03_16:35:00 SIGNALduino_unknown_5 bitCount: 24
2019-12-03_16:35:00 SIGNALduino_unknown_5 hexMsg: 42D60E
2019-12-03_16:35:00 SIGNALduino_unknown_5 hexMsg_invert: BD29F1
2019-12-03_16:35:00 SIGNALduino_unknown_5 hexCount_or_nibble: 6
2019-12-03_16:35:00 SIGNALduino_unknown_5 lastInputDev: cc1101_ip2
2019-12-03_16:35:06 SIGNALduino_unknown_5 UserMSG: **close**
```

**Comment by HomeAutoUser** [comment]
Hallo @RainerPrivat,
dieser sollte schon integriert sein.

Schalte mal bitte das Protokoll 3 aktiv und teste erneut.
Ggf, bitte  alle Protokolle aktivieren.

Diesen Kontakt habe ich ebenso und daher gehe ich davon aus, das du ihn nur deaktiviert hast.

Frage? Hast du auf die aktuelle dev Version geupdatet?

versionProtocols | 1.10
versionmodul | v3.4.1_dev_16.11

**Comment by RainerPrivat** [comment]
Hallo HomeAutoUser :-)
das Prot. 3 ist aktiv. erkannt wird ein z.B. 1527x42d60 (A/E)
was mich hier aber stört, das ein cc1101 diesen nicht immer sauber erkennt. Schaltvorgänge gehen verloren.
Dagegen spricht das u5# bei jedem Schaltvorgang sauber an.

Die aktuelle Version ist drauf.

**Comment by HomeAutoUser** [comment]
Ja, das ist weil der Sensor auf der ID 3 trifft, welche als Clockabs auto drin hat. Deswegen geht es mal aber nicht immer. In dem Fall müssen wir vermutlich eine neue Definition schaffen wo wir die Clockabs einstellen fest um es immer "genau" zu treffen.

Mache mal bitte folgendes,
einige Schaltvorgänge ... und sammel mal die RAWMSG.

**Comment by elektron-bbs** [comment]
Die Definition ist bei diesem Schaltkreis (PT2262) schon OK.
Vieleicht wird er auch nicht immer als MS erkannt, sondern als MU.

**Comment by RainerPrivat** [comment]
RAW con der ID3 oder von der u5#?

**Comment by HomeAutoUser** [comment]
>RAW con der ID3 oder von der u5#?

Am besten einfach mal alle Protokolle einschalten und verbose 4. Danach häufiger Schalten um sehen zu können ob es immer eindeutig ein Nachrichtentyp ist oder ob auch mal ein Wechsel zu MS stattfindet.

**Comment by RainerPrivat** [comment]
u5# wechselt nicht, bleibt immer bei MU
ID3 sind durchweg MS Nachrichten.
```
MU;P0=1931;P1=-1364;P2=1343;P3=3193;P4=-1952;P5=458;P6=-466;D=0121345126515151512651262651265126265151515151265126515;CP=5;R=53;
MU;P0=4940;P1=-1346;P2=458;P4=1343;P5=-467;P6=-6503;D=01214521212121452145452145214545212121212145214521260;CP=2;R=47;
MU;P0=1343;P1=-1364;P2=1946;P3=459;P4=-466;D=01213104313131310431040431043104043131313131043104313;CP=3;R=38;
MU;P0=-2950;P1=458;P2=-1363;P3=1353;P4=-466;P6=5038;D=0123412121212341234341234123434121212121234343412106;CP=1;R=41;
MU;P0=-467;P1=459;P2=-1364;P3=1369;P4=-4081;P5=3756;D=0123012121212301230301230123030121212121230123012145;CP=1;R=35;
MU;P0=98;P1=-1363;P2=457;P3=1373;P4=-466;D=012134212121213421343421342134342121212121343434212;CP=2;R=45;
```

**Comment by elektron-bbs** [comment]
Die MS-Nachrichten werden einwandfrei dekodiert. Wahrscheinlich hast du noch nicht die aktuelle Entwicklerversion dev-r34 und evtl. noch ein älteres IT-Modul in Benutzung.

**Comment by RainerPrivat** [comment]
version    V 3.3.1-experimental SIGNALESP cc1101 (chip CC1101) - compiled at Oct  8 2019 16:39:14
   versionProtocols 1.11
   versionmodul v3.4.1_dev_19.11

**Comment by elektron-bbs** [comment]
Schalte mal bitte bei diesem SIGNALESP das Attribut "addvaltrigger" auf 1 und poste noch eininge RAW-MSG, damit wir auch den RSSI sehen.
Was vieleicht auch noch hilfreich wäre, sind die Einstellungen des CC1101 (ccconf).

**Comment by RainerPrivat** [comment]
ja, das die MS Nachrichten einwandfrei decodiert werden, sehe ich auch. doch dies geschieht  nur mit einem sudino ohne cc1101. und das nicht bei jedem Schaltvorgang.
sobald ein cc1101 im Spiel ist, decodiert er nur die u5# Nachrichten als MU

**Comment by RainerPrivat** [comment]
der RSSI ist zwischen -50 bis -53

**Comment by RainerPrivat** [comment]
```

2019.12.03 18:35:44 4 : cc1101_ip2/msg READredu: MU;P0=2814;P1=-774;P2=459;P3=-1363;P4=1344;P5=-466;D=012345232323234523454523452345452323232323452345232;CP=2;R=43;
2019.12.03 18:35:44 4 : cc1101_ip2: Fingerprint for MU Protocol id 5 -> Unitec matches, trying to demodulate
2019.12.03 18:35:44 4 : cc1101_ip2: Decoded matched MU Protocol id 5 dmsg u5#42D60A length 24 dispatch(1/4) RSSI = -52.5
2019.12.03 18:35:44 4 : SIGNALduino_unknown incomming msg: u5#42D60A
2019.12.03 18:35:44 4 : SIGNALduino_unknown rawData: 42D60A
2019.12.03 18:35:44 4 : SIGNALduino_unknown Protocol: 5
2019.12.03 18:35:44 4 : SIGNALduino_unknown converted to bits: 010000101101011000001010

2019.12.03 18:37:18 4 : cc1101_ip2/msg READredu: MU;P0=-4248;P1=458;P2=-1364;P3=1350;P4=-467;D=01234121212123412343412341234341212121212343434121;CP=1;R=44;
2019.12.03 18:37:18 4 : cc1101_ip2: Fingerprint for MU Protocol id 5 -> Unitec matches, trying to demodulate
2019.12.03 18:37:18 4 : cc1101_ip2: Decoded matched MU Protocol id 5 dmsg u5#42D60E length 24 dispatch(1/4) RSSI = -52
2019.12.03 18:37:18 4 : SIGNALduino_unknown incomming msg: u5#42D60E
2019.12.03 18:37:18 4 : SIGNALduino_unknown rawData: 42D60E
2019.12.03 18:37:18 4 : SIGNALduino_unknown Protocol: 5
2019.12.03 18:37:18 4 : SIGNALduino_unknown converted to bits: 010000101101011000001110

19.12.03 18:38:03 4 : cc1101_ip2/msg READredu: MU;P0=1343;P1=-618;P2=459;P3=-1364;P4=-467;P5=-7893;D=0123042323232304230404230423040423232323230423042325;CP=2;R=47;
2019.12.03 18:38:03 4 : cc1101_ip2: Fingerprint for MU Protocol id 5 -> Unitec matches, trying to demodulate
2019.12.03 18:38:03 4 : cc1101_ip2: Decoded matched MU Protocol id 5 dmsg u5#42D60A length 24 dispatch(1/4) RSSI = -50.5
2019.12.03 18:38:03 4 : SIGNALduino_unknown incomming msg: u5#42D60A
2019.12.03 18:38:03 4 : SIGNALduino_unknown rawData: 42D60A
2019.12.03 18:38:03 4 : SIGNALduino_unknown Protocol: 5
2019.12.03 18:38:03 4 : SIGNALduino_unknown converted to bits: 010000101101011000001010

2019.12.03 18:38:38 4 : cc1101_ip2/msg READredu: MU;P0=2828;P1=-1364;P2=457;P3=1378;P4=-466;D=012134212121213421343421342134342121212121343434212;CP=2;R=46;
2019.12.03 18:38:38 4 : cc1101_ip2: Fingerprint for MU Protocol id 5 -> Unitec matches, trying to demodulate
2019.12.03 18:38:38 4 : cc1101_ip2: Decoded matched MU Protocol id 5 dmsg u5#42D60E length 24 dispatch(1/4) RSSI = -51
2019.12.03 18:38:38 4 : SIGNALduino_unknown incomming msg: u5#42D60E
2019.12.03 18:38:38 4 : SIGNALduino_unknown rawData: 42D60E
2019.12.03 18:38:38 4 : SIGNALduino_unknown Protocol: 5
2019.12.03 18:38:38 4 : SIGNALduino_unknown converted to bits: 010000101101011000001110
```

freq:433.920MHz bWidth:464KHz rAmpl:42dB sens:4dB (DataRate:115051.27Baud)

**Comment by elektron-bbs** [comment]
Mhmm, eigenartig, das der SIGNALESP diese nicht als MS erkennt. Die Datenrate sieht komisch aus. Mach mal bitte ein "set raw e" - das sollte den CC1101 auf Standardeinstellngen setzen. Diese müssten dann so aussehen:
freq:433.920MHz bWidth:325KHz rAmpl:38dB sens:8dB (DataRate:5603.79Baud)

**Comment by RainerPrivat** [comment]
done!
MS;P0=-14038;P1=448;P4=-1363;P6=1364;P7=-453;D=10146714141414671467671467146767141414141467146714;CP=1;SP=0;R=41;O;m2;
es war die Datenrate. :-)
danke.
