### ISSUE TITLE
Bereitstellen von Zwischenständen im Forum oder besser auf git

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#704]
@elektron-bbs 

Wieso machst Du im Repo nicht einen neuen Branch auf und bietest den Entwicklungsstand über eine Updatebefehl an?
Die Rechte solltest Du dazu haben meine ich.

Vorteil:

Da muss niemand manuell was kopieren
Der Stand ist wohl dokumentiert
Einspielen der Änderung funktioniert mit bekannten FHEM update Befehl
Wenn der Branch gelöscht wird, setzt niemand auf dann veraltete Stände, weil sie noch irgendwo liegen.

**Comment by elektron-bbs** [comment]
Die Rechte müsste ich haben, zumindest hat es bei SD_GT funktioniert.
Da aber SD_GT auch noch offen ist, bin ich mir nicht sicher, ob wir das dann alles unter einen Hut bringen können, wenn ich eine zweiten Branch anlege.
Es kommt doch so schon immer zu Konflikten, wenn zwischenzeitlich jemand anderes Dateien geändert hat.

**Comment by sidey79** [comment]
Es kann maximal zu den gleichen Konflikten kommen, zu denen es auch kommt, wenn Du es später versucht zusammenzusetzen.

Solange nicht die gleichen Codezeilen verändert werden, kann das System es automatisch zusammensetzen.

Und wenn es zu Konfliken kommt, müssen die doch so oder so manuell gelöst werden oder wie hattest Du das gemeint?

**Comment by elektron-bbs** [comment]
Ich vermeide Konflikte weitestgehend, indem ich pull requests aus einem aktuellen Branch mache.

**Comment by sidey79** [comment]
die Forums Änderung läuft ja jetzt parallel, wenn ich jetzt die Änderungen vom Master in den dev-r34 branch packe, dann haben wir doch den identischen Stand hinsichtlich Änderungen, egal ob die Datei im Forum liegt oder in einem eigenen Branch?

**Comment by elektron-bbs** [comment]
Eher nicht. Was ich im Forum zum Testen bereit gestellt habe, basiert auf v3.4.1_dev_19.11 inklusive SD_GT-Anpassungen.
Ich mag hier auch nicht jeden Tag Updates fahren, wenn ich gerade etwas in Arbeit habe. Da lässt sich so etwas viel schneller und einfacher durch den User testen, wenn ich die geänderten Dateien einzeln bereit stelle.
Wenn es dann fertig ist, aktualisiere ich auf aktuellen Stand, füge meine Änderungen ein und tätige den PR.

**Comment by HomeAutoUser** [comment]
Hallo, ein kurzes Statement von mir.

„ ... wenn ich die geänderten Dateien einzeln bereit stelle.“

Ich glaube es geht @sidey79 nur darum, das du die Dateien in einem separaten Branch der dev-r34 „pflegst“ und nicht jede Datei einzeln in einem Branch.

Er möchte somit denke ich, die Stände / Zwischenstände später nachvollziehbar haben und dem user das einspielen via Updatebefehl ermöglichen.

**Comment by elektron-bbs** [comment]
> Er möchte somit denke ich, die Stände / Zwischenstände später nachvollziehbar haben und dem user das einspielen via Updatebefehl ermöglichen.

Das birgt aber m.E. viel mehr Risiken für den User.
Er bekommt plötzlich alle Module auf einem Rutsch aus dem Entwicklerzweig. Das passt u.U. überhaupt nicht mehr zum SVN.
Da aktualisiere ich doch besser nur das eine Modul.
Nachvollziehbar ist es dann beim endgültigen Update.

**Comment by sidey79** [comment]
@HomeAutoUser 

Prinzipiell richtig. Bereitstellen via update fände ich besser, als einzelne Dateien irgendwo zu hinterlegen.

@elektron-bbs 
Ich verstehe wohl nicht so recht, welche Konflikte es da geben soll. :(
Wenn Du für unterschiedlichen Anpassungen die gleiche Datei und die gleichen Zeilen änderst, dann hast Du die Konflikte doch immer, egal welches System Du verwendest.

Wenn es zwei völlig unabhängig Änderungen sind, dann verstehe ich nicht welche Konflikte es da geben soll.

Vielleicht hast Du da ein Beispiel?

Einzelne Dateien Update geht "update <Dateiname>". Ob das auch von fremden Repos geht habe ich nicht getestet. 
Toll wäre aber in der Tat ein Single File update mit Angabe einer Datei / URL .

Module in eigene Repos auslagern kann da helfen um nicht den Stand aller Module zu überbügeln, das hatte ich ja jetzt beim RSL Modul probiert und wir hatten auch viel diskutiert :)

**Comment by elektron-bbs** [comment]
> Ich verstehe wohl nicht so recht, welche Konflikte es da geben soll. :(
> Wenn Du für unterschiedlichen Anpassungen die gleiche Datei und die gleichen Zeilen änderst, dann hast Du die Konflikte doch immer, egal welches System Du verwendest.
> 
> Wenn es zwei völlig unabhängig Änderungen sind, dann verstehe ich nicht welche Konflikte es da geben soll.
> 
> Vielleicht hast Du da ein Beispiel?

Nein, habe ich nicht, da ich es bisher noch nicht probiert habe. Ich will ja hier auch nicht alles durcheinander bringen.
Ich ging davon aus, das, wenn ich jetzt beispielsweise einen pull reqest von dev-r34_QUIGG-Gt-9000 in 
dev-r34 tätige, es dann zu einer Menge Konflikten kommt, weil es ja z.B. in der Datei 00_SIGNALduino.pm mittlerweile etliche Änderungen gab.
 
> Einzelne Dateien Update geht "update ". Ob das auch von fremden Repos geht habe ich nicht getestet.
> Toll wäre aber in der Tat ein Single File update mit Angabe einer Datei / URL .

Update einzelner Dateien geht - oder geht nicht? 

> Module in eigene Repos auslagern kann da helfen um nicht den Stand aller Module zu überbügeln, das hatte ich ja jetzt beim RSL Modul probiert und wir hatten auch viel diskutiert :)

Das bringt aber auch nichts, wenn Änderungen in 00_SIGNALduino.pm oder SD_ProtocolData.pm und im ausgelagerten Modul erforderlich sind.

**Comment by sidey79** [comment]
Das Zusammenführen der Änderungen erfolgt zeilenweise. Das ist ja gerade der Vorteil von GIT, dass mehrere Änderungen wieder unabhängig entwickelt werden können und wieder zusammen finden.
Da kommt es selten zu Konflikten. Kandidaten sind da in der Regel auch nur CHANGED und die Controls Datei.


Update einzelner Dateien aus dem SVN geht. Ob das auch bei 3rd party repos geht, habe ich nicht getestet.
Wenn es nicht geht, wäre ein Patch interessant denke ich :)

**Comment by elektron-bbs** [comment]
OK, dann werde ich das mit dev-r34_QUIGG-Gt-9000 probieren.

Interessant wäre für uns ja eher, ob ein Update einzelner Dateien von github ginge.

**Comment by sidey79** [comment]
Das Update einzelner Dateien geht.


Ich habe folgendes gemacht:

1.
`update add https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r34/controls_signalduino.txt`


2. `update 00_SIGNALduino.pm`

```
fhem
UPD FHEM/00_SIGNALduino.pm

New entries in the CHANGED file:
 - feature: 30_HUEBridge, 31_HUEDevice: added deCONZ scenes (by shadowghost)
 - feature: 14_SD_RSL.PM: support for setExtensions added
 - change:  59_Weather: delete table options in commandref
 - bugfix:  73_AutoShuttersControl: fix Commandref, skip ExternalTrigger Drive
                      from adv check
 - bugfix:  88_HMCCU: Fixed problems during shutdown / restart
 - bugfix:  70_VIERA: avoid possible interaction GET status/SET command
                     see also Forum #99994
 - change:  33_readingsGroup: don't use events to update cells
 - feature: 98_WeekdayTimer: add support for weekprofile, add nl Forum: #105521
 - bugfix:  98_WeekdayTimer: fix last timer of a day Forum: #104167
 - feature: 98_weekprofile: add support for WeekdayTimer Forum: #105521
 - feature: 98_RandomTimer: Add execNow option
 - change:  93_DbRep: minor internal code chane, commandref revised
 - bugfix:  73_AutoShuttersControl: fix selfdefense bug
 - bugfix:  73_AutoShuttersControl: fix time format problem
 - feature: 73_DoorBird: Videos File Format as Attribute
 - bugfix:  71_COE_Node: decimal for kWh fixed
 - change:  73_AutoShuttersControl: fix 'table with attributes' message then
                          commandref create
 - new:     66_EseraAnalogInOut.pm: new modul
 - new:     66_EseraDigitalInOut.pm: new modul
 - new:     66_EseraMulti.pm: new modul
 - new:     66_EseraTemp.pm: new modul
 - new:     66_EseraCount.pm: new modul
 - new:     66_EseraIButton.pm: new modul
... rest of lines skipped.


signalduino
UPD FHEM/00_SIGNALduino.pm

New entries in the CHANGED file:
06.12.2019
  00_SIGNALduino.pm: 
    logoutput adjusted to standard -> $name: "sub", "Text"
    remove unneeded get commands from webif for dummys
    remove cc1101 get commands if no cc1101 connected
    fixed serval Perlwarning and rare bug that caused fhem to crash
    new Internal hasCC1101 added
    allows flash nano328 and nanoCC1101 with new bootloader optiboot
    allows flash radino with DEF /dev/serial/by-id/
    new internal which provides error messages from flash     
    during flash operation
    add special reset for radinoCC1101
    added specify arduino hardware type (ESP8266,ESP8266cc1101)
    attribute ESP1_M is deleted
    !! Please define new if hardware defined with old typ !!
    fix some logging issues with disabled eventlogging
    Optimze logging if eventlogging is 0 or unset
    get availableFirmware - fix browser refresh
    add support to flash microcontroller on Windows platform
    New protocol TCM 218943, replaced u6 was in development
    add definition for Medion OR28V RF Vista Remote Control
  90_SIGNALduino_un.pm: 
    clean some code
  14_SD_RSL.PM: 
    support for setExtensions added
  14_SD_WS.pm: 
... rest of lines skipped.
Calling /usr/bin/perl ./contrib/commandref_modular.pl, this may take a while

update finished, "shutdown restart" is needed to activate the changes.
```

Die Logausgabe sieht auf den erst Blick merkwürdig aus, aber alles ist in Ordnung.
Zuerst wird ein Update vom "fhem" repository gezogen. Anschließend wird dann ein Update aus dem signalduino repository geladen.

Die Datei weist dann folgende Signatur aus:
`# $Id: 00_SIGNALduino.pm 10488 2019-12-06 12:00:00Z v3.4.1 $`

Somit ist ein Update einzelner Dateien auch aus 3rd Party Repos möglich. Das zuletzt hinzugefügte Repository wird aber wohl zuletzt ausgeführt.
