### ISSUE TITLE
Was ist die aktuelle dev Version? - Syntax SDUINO_VERSION, "dev" failed

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#710]
Hallo,

mir ist soeben aufgefallen, das bei einem Update die Meldung

`2019.12.09 10:43:08 3: nano_433Mhz: getAttrDevelopment, IdList ### Attribute development is in this version ignored ###`

erscheint.

Da das Attribut  `development 1` gesetzt ist, wurde ich stutzig.

Darauf hin habe ich es unter die Lupe genommen. Der Code
```

	if (index(SDUINO_VERSION, "dev") >= 0) {  	# development version
		$develop = AttrVal($name,"development", 0) if (!defined($develop));
		$devFlag = 1 if ($develop eq "1" || (substr($develop,0,1) eq "y" && $develop !~ m/^y\d/));	# Entwicklerversion, y ist nur zur Abwaertskompatibilitaet und kann in einer der naechsten Versionen entfernt werden
	}
	else {
		$develop = "0";
		Log3 $name, 3, "$name: getAttrDevelopment, IdList ### Attribute development is in this version ignored ###";
	}
	return ($develop,$devFlag);
```

wertet es aus.

In der bisherigen dev-r34 ist kein Syntax dev mehr vorhanden und auch in dem neuen Branch dev-r34_3.4.1 ebenso nicht.

dev-r34
https://github.com/RFD-FHEM/RFFHEM/blob/443c9a39649f51a552b2a8d78262bc89a05255a6/FHEM/00_SIGNALduino.pm#L34

dev-r34_3.4.1
https://github.com/RFD-FHEM/RFFHEM/blob/c1fa7e251976731be891cebcfbcbbfd0ced3c71f/FHEM/00_SIGNALduino.pm#L34

ToDo @sidey79 
In der aktuellen DEV-Version sollte der Kürzel "dev" wieder ergänzt werden da ich deine Gedanken nicht kenne, welches der Branchs du noch als DEV siehst. Die Dev Version wird ja "nie" fertig ;-)

**Comment by HomeAutoUser** [comment]
@sidey79 *Handheb* 
in welche Version dürfen weiter pushen und bitte den Kürzel dev nicht vergessen ;-)

**Comment by sidey79** [comment]
Bitte weiter in dev-r34 pushen.

Das Kürzel ist aktuell nicht enthalten, da die Version exakt identisch mit dem master ist.

Ich habe auch einfach nicht daran gedacht, anschließend einen commit zu tätigen, der das ändert.

Der Branch 3.4.1 war nur ein Zwischenschritt um alles zusammenzuführen, den werde ich wieder löschen.

**Comment by sidey79** [comment]
sollte sich erledigt haben oder?

**Comment by HomeAutoUser** [comment]
noch nicht ganz ;-)

https://github.com/RFD-FHEM/RFFHEM/blob/75b5740cf1a9941414d26cf235426f182489689f/FHEM/00_SIGNALduino.pm#L34

hat noch kein dev Kürzel um fortzufahren.
