### ISSUE TITLE
Update SVN to 3.4.1

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#712]
Modified files:
- [x] 14_SD_BELL.PM
- [x] 00_SIGNALDuino.PM
- [ ] 14_SD_Keeloq.pm 
- [x] 14_SD_UT.pm
- [x] 14_SD_WS.pm
- [x] 14_SD_WS_Maverick.pm 
- [x] SD_ProtocolData.pm 
- [x] 90_SIGNALduino_un.pm

**Comment by sidey79** [comment]
Ich werde das heute noch angehen

**Comment by sidey79** [comment]
@HomeAutoUser 

Ich hab soweit fertig. Für die anderen beiden Module bist Du als maintainer hinterlegt :)

**Comment by HomeAutoUser** [comment]
Bei den Modulen  14_SD_BELL.PM & 14_SD_UT.pm hat sich nichts geändert und diese sind in der Version schon im SVN.

14_SD_Keeloq.pm - nur im dev bei uns hier.

**Comment by sidey79** [comment]
Wenns mit Keeloq ein Problem mit Uhrheberrechten gibt, dann trifft uns das hier ebenso wie auf SVN. Den Rest habe ich verstanden und abgehakt :)

**Comment by HomeAutoUser** [comment]
> Wenns mit Keeloq ein Problem mit Uhrheberrechten gibt, dann trifft uns das hier ebenso wie auf SVN. 

lass uns das das nächste mal hochschieben ;-)
