### ISSUE TITLE
Protokoll für xavax Funksteckdosen Set

### ISSUE THREAD

**Issue by codeartisan-de** [RFD-FHEM/RFFHEM#717]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: xavax
  - model name: 00111939
  - pictures of the device / the board (very helpful)

![IMG_20191214_021611](https://user-images.githubusercontent.com/25353216/70841264-59554e80-1e19-11ea-8528-fed96cd318d8.jpg)
![IMG_20191214_021622](https://user-images.githubusercontent.com/25353216/70841266-5d816c00-1e19-11ea-8d23-c6346b640610.jpg)
![IMG_20191214_021630](https://user-images.githubusercontent.com/25353216/70841267-5f4b2f80-1e19-11ea-8502-952b078313b6.jpg)

Uraltes Funksteckdosenset, das ich hier liegen habe. Hab ich bisher auch nicht mit meinem rc-switch Arduino Uno hin bekommen. 

## Specifications 

   - Microcontroller: cc1101 an Arduino Nano an Raspi
  - Version (Firmware): V 3.4.0-dev SIGNALduino cc1101 (chip CC1101) - compiled at Dec 4 2019 22:02:15
  - Versionmodul (FHEM Module): Latest Revision: 20724

File                 Rev   Last Change

fhem.pl              20651 2019-12-03 08:39:54Z rudolfkoenig
98_autocreate.pm     19372 2019-05-11 15:13:59Z rudolfkoenig
14_CUL_TCM97001.pm   19762 2019-07-02 19:21:52Z bjoernh
91_eventTypes.pm     14888 2017-08-13 12:07:12Z rudolfkoenig
01_FHEMWEB.pm        20540 2019-11-19 08:25:23Z rudolfkoenig
92_FileLog.pm        20537 2019-11-18 21:28:30Z rudolfkoenig
98_help.pm           19915 2019-07-29 20:01:16Z betateilchen
91_notify.pm         19374 2019-05-11 17:48:03Z rudolfkoenig
14_SD_Keeloq.pm         32 2019-08-31 12:00:00Z v3.4-dev_02.12.
00_SIGNALduino.pm    19857 2019-07-19 18:00:16Z Sidey
90_SIGNALduino_un.pm 19858 2019-07-19 18:16:55Z Sidey
10_SOMFY.pm          15807 2018-01-06 23:32:41Z viegener
99_SUNRISE_EL.pm     18732 2019-02-25 13:15:34Z rudolfkoenig
98_SVG.pm            20537 2019-11-18 21:28:30Z rudolfkoenig
98_update.pm         20600 2019-11-26 18:07:13Z rudolfkoenig
99_Utils.pm          18920 2019-03-16 09:58:52Z rudolfkoenig
98_version.pm        15140 2017-09-26 09:20:09Z markusbloch

AttrTemplate.pm      20425 2019-10-30 08:33:31Z rudolfkoenig
Blocking.pm          17553 2018-10-17 15:56:35Z rudolfkoenig
DevIo.pm             20174 2019-09-16 18:04:03Z rudolfkoenig
GPUtils.pm           19666 2019-06-20 11:17:29Z CoolTux
HttpUtils.pm         20375 2019-10-17 22:52:43Z rudolfkoenig
RTypes.pm            10476 2016-01-12 21:03:33Z borisneubert
No Id found for SD_ProtocolData.pm
No Id found for SD_Protocols.pm
SetExtensions.pm     19208 2019-04-17 19:27:09Z rudolfkoenig
TcpServerUtils.pm    19138 2019-04-07 10:17:21Z rudolfkoenig

f18.js                     20069 2019-08-27 08:36:02Z rudolfkoenig
fhemweb.js                 20554 2019-11-20 20:53:04Z rudolfkoenig
svg.js                     19667 2019-06-20 13:39:55Z rudolfkoenig

## Logs

Logs für 3 mal kurze Zeit einige der Tasten gedrückt. Taste siehe Dateiname - also 1 bzw. 2 & on bzw. off.

[xavax.1.on.txt](https://github.com/RFD-FHEM/RFFHEM/files/3963277/xavax.1.on.txt)
[xavax.1.off.txt](https://github.com/RFD-FHEM/RFFHEM/files/3963278/xavax.1.off.txt)
[xavax.2.on.txt](https://github.com/RFD-FHEM/RFFHEM/files/3963279/xavax.2.on.txt)
[xavax.2.off.txt](https://github.com/RFD-FHEM/RFFHEM/files/3963280/xavax.2.off.txt)

**Comment by codeartisan-de** [comment]
Hallo.

Ein weiteres Funksteckdosen Set, das ich gerne einsetzen würde.
Ich habe wieder versucht im Ticket das nötigste auf die schnelle anzugehen. Wenn mehr Logs/Bilder/Infos nötig sind schaue ich gerne was ich hin bekommen. Mit rc-switch hab ich das Set noch nicht zum laufen bekommen. Irgendwie blickt ich bei dem Code überhaupt nicht durch.

**Comment by HomeAutoUser** [comment]
Hallo @codeartisan-de,

ich habe wie hier https://github.com/RFD-FHEM/RFFHEM/issues/716#issuecomment-565702165 beschrieben auch dort gleich das Protokoll mal integriert und du solltest da schonmal ein u20 Device erhalten für den ersten Schritt. Der Befehl ist der Gleiche.

**Comment by codeartisan-de** [comment]
Auch hier nach dem Update

```
2019.12.14 13:27:47 4: sduino: Read, msg READredu: MU;P0=3000;P1=-3552;P2=436;P3=-1337;P4=-535;P5=-18264;D=012323242323242324232423242324232324242324242324232423242324232424232424242423232325;CP=2;R=44;
2019.12.14 13:27:47 4: sduino: Parse_MU, Fingerprint for MU Protocol id 20 -> xavax matches, trying to demodulate
2019.12.14 13:27:47 4: sduino: Parse_MU, Decoded matched MU Protocol id 20 dmsg u20#DAAB255487 length 40 dispatch(1/4) RSSI = -52
2019.12.14 13:27:47 4: SIGNALduino_unknown incomming msg: u20#DAAB255487
2019.12.14 13:27:47 4: SIGNALduino_unknown rawData: DAAB255487
2019.12.14 13:27:47 4: SIGNALduino_unknown Protocol: 20
2019.12.14 13:27:47 4: SIGNALduino_unknown converted to bits: 1101101010101011001001010101010010000111
2019.12.14 13:27:47 4: SIGNALduino_unknown sduino Protocol:20 | To help decode or debug, please add u20! (attr sduino development u54,u20)
2019.12.14 13:27:47 4: Unknown, please report
2019.12.14 13:27:47 4: SIGNALduino_unknown incomming msg: u20#DAAB255487
2019.12.14 13:27:47 4: SIGNALduino_unknown rawData: DAAB255487
2019.12.14 13:27:47 4: SIGNALduino_unknown Protocol: 20
2019.12.14 13:27:47 4: SIGNALduino_unknown converted to bits: 1101101010101011001001010101010010000111
2019.12.14 13:27:47 4: SIGNALduino_unknown sduino Protocol:20 | To help decode or debug, please add u20! (attr sduino development u54,u20)
2019.12.14 13:27:47 4: Unknown, please report
2019.12.14 13:27:47 3: sduino: Unknown code u20#DAAB255487, help me!
```

`attr sduino development u54,u20`

```
2019.12.14 13:30:47 4: sduino: Read, msg READredu: MU;P0=-26752;P1=-537;P2=387;P3=3306;P4=-3520;P6=-1358;P7=-20412;D=12134262621262621262126212621262126262121262121262126212621262126212126212121212626262721213426262126262126212621262126212626212126212126212621262126212621212621212121262626202;CP=2;R=52;
2019.12.14 13:30:47 4: sduino: Parse_MU, Fingerprint for MU Protocol id 20 -> xavax matches, trying to demodulate
2019.12.14 13:30:47 4: sduino: Parse_MU, Decoded matched MU Protocol id 20 dmsg u20#DAAB255487 length 40 dispatch(1/4) RSSI = -48
2019.12.14 13:30:47 4: SIGNALduino_unknown incomming msg: u20#DAAB255487
2019.12.14 13:30:47 4: SIGNALduino_unknown rawData: DAAB255487
2019.12.14 13:30:47 4: SIGNALduino_unknown Protocol: 20
2019.12.14 13:30:47 4: SIGNALduino_unknown converted to bits: 1101101010101011001001010101010010000111
2019.12.14 13:30:47 1: sduino: SIGNALduino_unknown UNDEFINED sensor SIGNALduino_unknown_20 detected
2019.12.14 13:30:47 2: autocreate: define SIGNALduino_unknown_20 SIGNALduino_un SIGNALduino_unknown_20
2019.12.14 13:30:47 2: autocreate: define FileLog_SIGNALduino_unknown_20 FileLog ./log/SIGNALduino_unknown_20-%Y.log SIGNALduino_unknown_20
```

Device `SIGNALduino_unknown_20`

**Comment by HomeAutoUser** [comment]
na das sieht schonmal gut aus.
Die weiteren Schritte müssen noch eingebaut und erarbeitet werden.

Du könntest mit diesem Stand sogar schon mittels einem DOIF auf die eingehenen Information reagieren. Senden geht definitiv nicht.

**Comment by codeartisan-de** [comment]
Und noch die Innereien:

![IMG_20191214_133418](https://user-images.githubusercontent.com/25353216/70848786-d5ca4a80-1e76-11ea-94f9-fbb45f6f7554.jpg)
![IMG_20191214_133406](https://user-images.githubusercontent.com/25353216/70848787-d5ca4a80-1e76-11ea-9221-b61939d0162d.jpg)

**Comment by codeartisan-de** [comment]
> na das sieht schonmal gut aus.
> Die weiteren Schritte müssen noch eingebaut und erarbeitet werden.

Prima, wenn ich was testen/liefern kann einfach bescheid geben. 

> Du könntest mit diesem Stand sogar schon mittels einem DOIF auf die eingehenen Information reagieren. Senden geht definitiv nicht.

So könnte ich schonmal eine FB mehr einsetzen als bisher. Aber Senden wäre das wichtigere. Die Dosen sind nämlich eher das was ich gebrauchen kann ;-)

**Comment by codeartisan-de** [comment]
Hallo @elektron-bbs & @HomeAutoUser .

Wie in #716 angefragt hier nochmal ein Log von der xavax mit den aktuellen Einstellungen.
[xavax.log](https://github.com/RFD-FHEM/RFFHEM/files/3980478/xavax.log)

Hab wieder 2 Tastenpaare aufgezeichnet 1&2 ON + OFF. Trennung im Log via
`sduino: Attr, Calling sub with args: set comment = xavax Taste 1 EIN`

Noch ein Hinweis: Ich bin gestern wieder auf den `dev-r34_Mandolyn` Branch gewechselt um mit dem dev20 Protokoll noch rumtesten zu können. Im `dev-r34` ist das offensichtlich nicht drin.

Ich versuche auch gerade mit den neuen Erkenntnissen von hier (z.B. Code >32bit) ein wenig auf dem rc-switch das Protokoll zu verstehen.

**Comment by elektron-bbs** [comment]
Ich habe jetzt einen neuen Branch für diese Fernbedienung erstellt:
https://github.com/RFD-FHEM/RFFHEM/tree/dev-r34_xavax

Der Befehl für das Update auf diesen Branch lautet:
update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r34_xavax/controls_signalduino.txt

Nach einem Neustart wird dir dann ein neues Gerät SIGNALduino_unknown_26 angelegt.

Setze bitte bei deinem SIGNALduino das Attribut "addvaltrigger" auf 1.

Bei dem neuen Gerät gibt es einen set-Befehl "UserInfo". Bitte in das Eingabefeld die Tastenbezeichnung eintragen und anschließend die entsprechende Taste der Fernbedienung betätigen.
Diesen Vorgang bitte für alle Tasten wiederholen.

Im Log des Gerätes sollten sich dann alle Infos finden, die wir noch benötigen.
Die Logdatei dann einfach hier hochladen.

**Comment by codeartisan-de** [comment]
Hallo @elektron-bbs.

Das Update klapt leider nicht:
```
2019.12.20 22:43:15 1: UPD FHEM/00_SIGNALduino.pm
2019.12.20 22:43:15 1: UPD FHEM/10_SD_GT.pm
2019.12.20 22:43:15 1: UPD FHEM/14_SD_UT.pm
2019.12.20 22:43:15 1: UPD FHEM/90_SIGNALduino_un.pm
2019.12.20 22:43:15 1: UPD FHEM/lib/SD_ProtocolData.pm
2019.12.20 22:43:15 1: Got 150061 bytes for FHEM/lib/SD_ProtocolData.pm, expected 148059
2019.12.20 22:43:15 1: aborting.
```

**Comment by sidey79** [comment]
@codeartisan-de 
Danke für den Hinweis. Ich habe den Fehler gefunden, der das Update verhindert hat.
Jetzt funktioniert es.

**Comment by codeartisan-de** [comment]
@sidey79 

danke, update ging jetzt.

@elektron-bbs 

`2019.12.21 14:12:01 4: sduino: Attr, Calling sub with args: set development = u26`
`2019.12.21 14:12:39 4: sduino: Attr, Calling sub with args: set addvaltrigger = 1`

[SIGNALduino_unknown_26-2019.log](https://github.com/RFD-FHEM/RFFHEM/files/3991417/SIGNALduino_unknown_26-2019.log)

Ich hab jede Taste 2 mal gedrück. Also so das zwei Werte im Log erscheinen. Hoffe das war OK.

**Comment by elektron-bbs** [comment]
Ja, sehr gut.
Ich habe das Protokoll jetzt erst mal in den oben genannten Branch integriert. Nach einem Update und Neustart von FHEM sollte es dir dann nach dreimaligen Empfang von deiner Fernbedienung ein neues Gerät xavax_DAAB2554 anlegen.
Bitte ausgiebig testen.

**Comment by codeartisan-de** [comment]
@elektron-bbs 

Nice! Das sieht sehr gut aus. 
Bekomme alles Tasten von der FB gelesen. 
Und konnte die beiden Dosen auch schalten. 

Jetzt versuche ich noch hier auch wieder FB und Dosen zu trennen. Scheint diesemal nicht einfach durch 1 Bit ändern zu gehen.

Das `DAAB2554` ist doch wieder der Hauscode bzw. immer gleiche Teil des Codes, oder?

BTW: Das Gerät für die Mandolyn (aus #716) ist verschwunden. P34 wird noch erkannt aber dann kommt `unknown`. Ich vermute mal das ist in dem xavax branch noch nicht mit drin?

**Comment by elektron-bbs** [comment]
Ja, "DAAB2554" ist der Hauscode. Ich weiß aber nicht, ob darin irgend eine Prüfung auf Gültigkeit enthalten ist. Wenn sich deine Dosen anlernen lassen, wenn du ein beliebiges Nibble davon änderst, sollte das nicht der Fall sein.

Protokoll 34 musste ich nochmal ändern. Da hatten wir den Hauscode zuerst nur zweistellig. Es müssen aber drei Nibble sein.

**Comment by codeartisan-de** [comment]
Hallo @elektron-bbs. Danke für die Rückmeldung.
Habs im Moment gefunden. Ist wirklich ne Prüfung/Checksumme/Muster drauf. Einfach ein Bit/Nibble ändern ging nicht. 

Binär müssen die Codes immer invertiert sein. Ist auch bei den Tasten so 
```
ON: A5 = 1010  0101‬
OFF: 5A  = 0101 1010
```
Im zweiten Nibble sind die 1 und 0 jeweils invitiert.

Beim Hauscode scheint die Paarung zwischen den 4 Nibblen zu bestehen. 
```
‭DAAB 2554
‭1101 1010 1010 1011  0010 0101 0101 0100
1001 1010 1010 1001  0110 0101 0101 0110
‭9AA9 6556‬
```

Kann sein das auch die Wiederholung bei Nibble 2&3 (+6&7) und die Spiegelung bei Nibble 1&4 (+5&8) relevant sind. Hab ich jetzt nicht nochmal versucht.

Damit funktioniert die xavax jetzt aber auch. Super und Danke an euch! Zusammen kann ich die xavax und Mandloyn vermutlich verwenden, wenn beides im normal Dev-Branch ist?

Jetzt spiele ich noch mit meinem SilverCrest 66538 Set rum. Die scheint auf `SD_GT` zu hören. Und das scheint auch noch in Dev zu sein? Da wird das mit dem festen vergeben eines Hauscodes scheinbar nicht so einfach. Aber ich muss das mal noch genauer anschauen.

**Comment by elektron-bbs** [comment]
Bei den Tasten hatte ich das auch schon bemerkt, mir aber den Hauscode noch nicht näher angesehen.
Ich würde den Hauscode dann auf 4 Nibble ändern und eine Prüfung beim Dekodieren einbauen, ob die letzten 4 Nibble invertiert zu den ersten vier sind.

Würdest du bitte noch testen, ob die Spiegelungen/Wiederholungen relevant sind, also z.B. mit einem Hauscode 1234 EDCB oder ähnlich?

Die Mandolyn sollte eigentlich auch mit diesem Branch funktionieren. Diese muss nur neu angelegt werden, da ich den Hauscode nochmal ändern musste.

SD_GT ist noch im dev-r34.

**Comment by codeartisan-de** [comment]
Hi @elektron-bbs 

> Würdest du bitte noch testen, ob die Spiegelungen/Wiederholungen relevant sind

Sind sie wohl nicht. Geht sowohl ohne Spiegelung, ohne Wiederholung und ohne Beides in den ersten 4 Nipples:


```
1101 1011 1010 1001  0010 0100 0101 0110
‭DBA9 2456‬
1101 1010 1010 1101  0010 0101 0101 0010
‭DAAD 2552‬
‭1101 1011 1010 1011  0010 0100 0101 0100
DBAB 2454
```


Nur ohne Invertierung zwischen 1-4 und 5-8 geht es nicht
```
1101 1010 1010 1101  0010 0101 0101 0001‬
‭DAAD 2551‬
```

> Die Mandolyn sollte eigentlich auch mit diesem Branch funktionieren. 
> Diese muss nur neu angelegt werden, da ich den Hauscode nochmal ändern musste.

Okay, deswegen war sie weg. Und jetzt hat er das Gerät auch wieder angelegt. War ich wohl beim ersten Versuch zu ungeduldig.

**Comment by elektron-bbs** [comment]
OK, die Prüfung auf Invertierung 1-4 gegen 5-8 und 9 gegen 10 habe ich schon mal eingebaut.

Ich werde dann wohl noch den Hauscode auf 4 Nibble ändern.

**Comment by elektron-bbs** [comment]
Ich habe jetzt den Hauscode von 8 Nibble auf 4 Nibble geändert.
Um die Invertierung musst du dich dann nicht mehr kümmern. Allerdings wird dir nochmal ein neues Gerät angelegt: xavax_DAAB

**Comment by codeartisan-de** [comment]
Und auch hier wurde das Gerät neu anglegt und schalten geht noch.

Wie läuft das jetzt eigentlich weiter. Soll ich die Anpassungen nochmal testen wenn sie in den Haupt(Dev)Zweig übernommen sind und dann die Tickets schließen? Oder macht ihr die irgendwann selber zu?

**Comment by sidey79** [comment]
Wenn wir es übernommen haben, dann wäre es super wenn Du es testest. Das Ticket kannst Du dann selbst schließen :)

**Comment by elektron-bbs** [comment]
@codeartisan-de 
Hast du es nochmal mit der Entwicklerversion probiert?
Wenn alles zur Zufriedenheit läuft, kannst du dieses Issue schließen.

**Comment by codeartisan-de** [comment]
Hallo @elektron-bbs.

Erstmal ein Gesundes Neues Jahr in die Runde. Bin von Weihnachtsfeiern über Silvester Urlaub erstmal zum Anbinden FHEM an OpenHAB übergegangen. Ging ja ersmal und ich hab garnicht mitbekommen das es schon gemerged wurde.

Update auf Dev mal durchgeführt – hoffentlich richtig via:
```
update force https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r34/controls_signalduino.txt 

2020.01.11 14:04:09 1: RMDIR: ./restoreDir/update/2019-12-21
2020.01.11 14:04:10 1: UPD FHEM/00_SIGNALduino.pm
2020.01.11 14:04:10 1: UPD FHEM/10_FS10.pm
2020.01.11 14:04:10 1: UPD FHEM/10_SD_GT.pm
2020.01.11 14:04:11 1: UPD FHEM/14_BresserTemeo.pm
2020.01.11 14:04:11 1: UPD FHEM/14_FLAMINGO.pm
2020.01.11 14:04:11 1: UPD FHEM/14_Hideki.pm
2020.01.11 14:04:11 1: UPD FHEM/14_SD_AS.pm
2020.01.11 14:04:11 1: UPD FHEM/14_SD_BELL.pm
2020.01.11 14:04:12 1: UPD FHEM/14_SD_Keeloq.pm
2020.01.11 14:04:12 1: UPD FHEM/14_SD_RSL.pm
2020.01.11 14:04:12 1: UPD FHEM/14_SD_UT.pm
2020.01.11 14:04:12 1: UPD FHEM/14_SD_WS.pm
2020.01.11 14:04:13 1: UPD FHEM/14_SD_WS07.pm
2020.01.11 14:04:13 1: UPD FHEM/14_SD_WS09.pm
2020.01.11 14:04:13 1: UPD FHEM/14_SD_WS_Maverick.pm
2020.01.11 14:04:13 1: UPD FHEM/41_OREGON.pm
2020.01.11 14:04:13 1: UPD FHEM/90_SIGNALduino_un.pm
2020.01.11 14:04:14 1: UPD FHEM/lib/SD_ProtocolData.pm
2020.01.11 14:04:14 1: UPD FHEM/lib/SD_Protocols.pm
2020.01.11 14:04:14 1: saving fhem.cfg
2020.01.11 14:04:14 1: saving ./log/fhem.save
2020.01.11 14:04:14 1:
2020.01.11 14:04:14 1: New entries in the CHANGED file:
2020.01.11 14:04:14 1: 2020-01-11 - New sub for get commands from other modules (API) (#774)
2020.01.11 14:04:14 1: Calling /usr/bin/perl ./contrib/commandref_join.pl -noWarnings, this may take a while
2020.01.11 14:04:36 1:
2020.01.11 14:04:36 1: update finished, "shutdown restart" is needed to activate the changes.
```

Sowohl für das Set hier als auch für die anderen Beiden von mir gilt danach:
Alles FBs werden richtig ausgewertet. Und die angeschlossenen Dosen lassen sich auch noch schalten. Passt Also denke ich. 

Danke nochmal!
und zu->
