### ISSUE TITLE
SVN compatibility

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#719]
## Expected Behavior

Files are compatible with SVN checks

## Actual Behavior

`*** trunk/fhem/FHEM/00_SIGNALduino.pm: DE: summary is longer than 80 chars on`

## Steps to Reproduce the Problem

  1. svn commit file (#712)
  2.
  3.

**Comment by elektron-bbs** [comment]
Die Versionsausgabe passt ach nicht so richtig:
![version](https://user-images.githubusercontent.com/26026988/82798718-34a9dc00-9e79-11ea-94cb-c81f3b127cd4.png)

**Comment by HomeAutoUser** [comment]
@elektron-bbs 
schau dir mal den Kopf der Datei an.
Es ist am Ende getan mit der einen Zeile leerKommentare.

**Comment by elektron-bbs** [comment]
Welche der Dateien meinst du?

**Comment by elektron-bbs** [comment]
Vergesst meine Postings zu dem Issue, war ein Irrtum meinerseits.
item summary_DE ist mittlerweile auch angepasst. Das Issue kann demnach m.E. geschlossen werden.
