### ISSUE TITLE
Protokoll für SilverCrest FSS B 20-A Funksteckdosen Set

### ISSUE THREAD

**Issue by codeartisan-de** [RFD-FHEM/RFFHEM#734]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: SilverCrest
  - model name: FSS B 20-A (3726) / 66538
  - pictures of the device / the board (very helpful)

![IMG_20191223_084628](https://user-images.githubusercontent.com/25353216/71345078-9bdb0180-2564-11ea-9cd1-f6313b76fc1a.jpg)
![IMG_20191223_084828](https://user-images.githubusercontent.com/25353216/71345079-9c739800-2564-11ea-8ea7-e45cd17c50ba.jpg)
![IMG_20191223_084814](https://user-images.githubusercontent.com/25353216/71345080-9c739800-2564-11ea-9f82-3c3f869104c2.jpg)
![IMG_20191223_084700](https://user-images.githubusercontent.com/25353216/71345081-9c739800-2564-11ea-9c6d-dca2d607a76b.jpg)
![IMG_20191223_084651](https://user-images.githubusercontent.com/25353216/71345082-9c739800-2564-11ea-9002-9f1f63455661.jpg)

Uraltes Funksteckdosenset, das ich hier liegen hatte und bisher mit einem rc-switch Arduino Uno einsetze.
rc-switch: https://github.com/sui77/rc-switch

## Specifications 

  - Microcontroller: cc1101 an Arduino Nano an Raspi
  - Version (Firmware): V 3.4.0-dev SIGNALduino cc1101 (chip CC1101) - compiled at Dec 4 2019 22:02:15
  - Versionmodul (FHEM Module): Latest Revision: 20724
```
File                 Rev   Last Change

fhem.pl              20651 2019-12-03 08:39:54Z rudolfkoenig
98_autocreate.pm     19372 2019-05-11 15:13:59Z rudolfkoenig
14_CUL_TCM97001.pm   19762 2019-07-02 19:21:52Z bjoernh
91_eventTypes.pm     14888 2017-08-13 12:07:12Z rudolfkoenig
01_FHEMWEB.pm        20540 2019-11-19 08:25:23Z rudolfkoenig
92_FileLog.pm        20537 2019-11-18 21:28:30Z rudolfkoenig
98_help.pm           19915 2019-07-29 20:01:16Z betateilchen
91_notify.pm         19374 2019-05-11 17:48:03Z rudolfkoenig
10_SD_GT.pm              0 2019-12-11 21:00:00Z elektron-bbs
14_SD_Keeloq.pm         32 2019-09-02 09:56:00Z v3.4
14_SD_UT.pm          20137 2019-09-09 15:58:29Z HomeAuto_User
00_SIGNALduino.pm    20746 2019-12-14 22:26:52Z Sidey
# $Id: 90_SIGNALduino_un.pm 15479 2019-11-21 20:14:00 dev-r34 $
10_SOMFY.pm          15807 2018-01-06 23:32:41Z viegener
99_SUNRISE_EL.pm     18732 2019-02-25 13:15:34Z rudolfkoenig
98_SVG.pm            20537 2019-11-18 21:28:30Z rudolfkoenig
99_Utils.pm          18920 2019-03-16 09:58:52Z rudolfkoenig
98_version.pm        15140 2017-09-26 09:20:09Z markusbloch

AttrTemplate.pm      20425 2019-10-30 08:33:31Z rudolfkoenig
Blocking.pm          17553 2018-10-17 15:56:35Z rudolfkoenig
DevIo.pm             20174 2019-09-16 18:04:03Z rudolfkoenig
GPUtils.pm           19666 2019-06-20 11:17:29Z CoolTux
HttpUtils.pm         20375 2019-10-17 22:52:43Z rudolfkoenig
RTypes.pm            10476 2016-01-12 21:03:33Z borisneubert
No Id found for SD_ProtocolData.pm
No Id found for SD_Protocols.pm
SetExtensions.pm     19208 2019-04-17 19:27:09Z rudolfkoenig
TcpServerUtils.pm    19138 2019-04-07 10:17:21Z rudolfkoenig

fhemweb.js                 20554 2019-11-20 20:53:04Z rudolfkoenig
svg.js                     19667 2019-06-20 13:39:55Z rudolfkoenig
```

SIGNALduino auf Branch https://github.com/RFD-FHEM/RFFHEM/tree/dev-r34_xavax 

## Infos

Logs für 3 mal kurze Zeit einige der Tasten gedrückt. Taste siehe 
`sduino: Attr, Calling sub with args: set comment = Silvercrest A ON`

[Silvercrest.log](https://github.com/RFD-FHEM/RFFHEM/files/3994161/Silvercrest.log)

Codes in rc-switch mit Protokoll 5 24bit
```
100010011010000100110000 (iFB_SilverCrest_A, ON));
100011011101101010110000 (iFB_SilverCrest_A, ON));
100011111111100001000000 (iFB_SilverCrest_A, ON));
100001010001100101110000 (iFB_SilverCrest_A, ON));
100000011110010010010000 (iFB_SilverCrest_A, OFF));
100001110000000000000000 (iFB_SilverCrest_A, OFF));
100011100011111100100000 (iFB_SilverCrest_A, OFF));
100001101011101100010000 (iFB_SilverCrest_A, OFF));
100011011101101010110100 (iFB_SilverCrest_B, ON));
100001010001100101110100 (iFB_SilverCrest_B, ON));
100011111111100001000100 (iFB_SilverCrest_B, ON));
100010011010000100110100 (iFB_SilverCrest_B, ON));
100011100011111100100100 (iFB_SilverCrest_B, OFF));
100001110000000010100100 (iFB_SilverCrest_B, OFF));
100000011110010010010100 (iFB_SilverCrest_B, OFF));
100001101011101100010100 (iFB_SilverCrest_B, OFF));
100001010001100101111100 (iFB_SilverCrest_C, ON));
100011011101101010111100 (iFB_SilverCrest_C, ON));
100011111111100001001100 (iFB_SilverCrest_C, ON));
100010011010000100111100 (iFB_SilverCrest_C, ON));
100001110000000010101100 (iFB_SilverCrest_C, OFF));
100000011110010010011100 (iFB_SilverCrest_C, OFF));
100001101011101100011100 (iFB_SilverCrest_C, OFF));
100011100011111100101100 (iFB_SilverCrest_C, OFF));
100000011110010010010010 (iFB_SilverCrest_D, ON));
100001101011101100010010 (iFB_SilverCrest_D, ON));
100001110000000010100010 (iFB_SilverCrest_D, ON));
100011100011111100100010 (iFB_SilverCrest_D, ON));
100001010001100101110010 (iFB_SilverCrest_D, OFF));
100011011101101010110010 (iFB_SilverCrest_D, OFF));
100010011010000100110010 (iFB_SilverCrest_D, OFF));
100011111111100001000010 (iFB_SilverCrest_D, OFF));
100001101011101100011010 (iFB_SilverCrest_Master, ON));
100000011110010010011010 (iFB_SilverCrest_Master, ON));
100001110000000010101010 (iFB_SilverCrest_Master, ON));
100011100011111100101010 (iFB_SilverCrest_Master, ON));
100010011010000100111010 (iFB_SilverCrest_Master, OFF));
100011111111100001001010 (iFB_SilverCrest_Master, OFF));
100001010001100101111010 (iFB_SilverCrest_Master, OFF));
100011011101101010111010 (iFB_SilverCrest_Master, OFF));
```

Im FHEM reagieren auf dem DEV Branch 2 Protokolle. Nicht immer, aber Beide oft. 

P49.1: Erkannt als `SD_GT`. Geräte werden auch angelegt und Codes gelernt (`SD_GT_8070A_A, _B, _C, _D`). Der Master sieht etwas komisch aus (SD_GT_8070A_) und hat kein set - ich kann ihn also nicht senden. Senden der anderen Tasten geht und die Dosen schalten auch.

P19:  `Unknown`. Hier kommen genau die Codes raus wie im rc-switch.
`attr sduino development u19`

Per UserInfo gefülltes Log:
[SIGNALduino_unknown_19-2019.log](https://github.com/RFD-FHEM/RFFHEM/files/3994164/SIGNALduino_unknown_19-2019.log)

## Wunsch

Ich fände es gut wenn man damit das P19 fertig bekommt. Bei SD_GT scheint das mit dem Hauscode nicht (so einfach) zu gehen. Und wenn es mit 19 ein SD_UT wird dann würden sich alle meine Sets gleich verhalten. Das wäre für die Weiterverarbeitung sehr hilfreich.

**Comment by elektron-bbs** [comment]
Wenn ich das richtig sehe, ist SD_GT schon das richtige Modul.
Bei den Tasten A, B, C und D steht bei dir in den Readings sicher "Version 2"?
Bei Protokollversion 2 hatte ich bisher noch keine Codes für die Master-Tasten. Ich muss mal sehen, ob ich die jetzt schon aus deinen Logs heraus bekomme.

Ich habe mich entschieden, das nicht in SD_UT einzubauen, da das Verfahren durch die Verschlüsselung dort nicht so einfach zu integrieren ist.

Den Hauscode selbst zu ändern, wird auch nicht so einfach, weil er mittels Hash verschlüsselt ist.
Warum willst du eigentlich immer den Hauscode ändern?

**Comment by codeartisan-de** [comment]
> steht bei dir in den Readings sicher "Version 2"?

jep.
```
2019.12.23 08:42:19 4: sduino: SD_GT_Parse 8DDAB0, possible codes version 1 80BCA or version 2 8070A
2019.12.23 08:42:19 4: sduino: SD_GT_Parse found SD_GT_8070A_, version 2, systemCode 8070A
2019.12.23 08:42:19 4: sduino: SD_GT_Parse 8DDAB0, found version 2 with systemCode 8070A
```

> mittels Hash verschlüsselt ist

Kommen da deswegen immer 4 verschiedene Codes? 
Beim Senden hab ich aber immer einfach nur einen verwendet. Damit lassen sich die Dosen anlernen und auch schalten. Aber ich meine die Codes für die Dosen hab ich damals aus einem Forum genommen da ich es mit einfach bits ändern nich hin bekommen habe. Das lag dann wohl am Hash.

Da eh jedes Tastenpaar ein Gerät ist bei SD_GT würde es auch helfen wenn ich den Code selber angeben kann der gesendet wird. Wobei, im Prinzip müsste es ja auch gehen wenn ich die Codes die ich habe einfach per SIGNALduino SendMSG sende. Muss ich dann mal testen.

> Warum willst du eigentlich immer den Hauscode ändern?

Weil ich die FB unabhängig von den Dosen nutze. Also wenn ich die FB drücke schaltet keine der Dosen. Die Dosen werden dann - wenn nötig - vom OpenHAB eben mit einem anderen Hauscode angesteuert. Damit kann ich die FBs für alles Mögliche nutzen, ohne das ich drauf achten muss welche Dose jetzt evtl. den Code der Tasten verwendet. Bslp: TV per LAN anmachen oder 3 Dosen aus unterschiedlichen Sets zusammen mit einer Taste der FBs schalten und die gleich Taste der anderen FB schaltet die gleichen 3 unterschiedlichen Dosen. So kommt man ganz billig an brauchbare FBs für's SmartHome ^^

**Comment by elektron-bbs** [comment]
Ich habe die Codes für die Master-Tasten in der 10_SD_GT.pm jetzt erst mal probehalber im Branch xavax ergänzt, damit du nicht hin und her wechseln musst. Bitte mal testen.

Diese Fernbedienungen senden 2 oder 4 verschiedene Codes pro Taste, die über einen Hash verschlüsselt einen Systemcode enthalten. In einer Übertragung werden die Daten auch noch mit 2 verschiedenen Timings übertragen. Deshalb auch 2 bzw. 3 Definitionen für ein Protokoll (49, 49.1 und 49.2). Welches Timing bei welcher Steckdose ausgewertet wird, entzieht sich meiner Kenntnis.

**Comment by codeartisan-de** [comment]
Hallo und ein Frohes Fest. 
Hab heute mal Zeit zum testen gehabt. Hab alle Geräte entsorgt und nochmal neu angelernt. Jetzt wurde auch ein `SD_GT_8070A_all` angelegt, das auch alle Dosen im Test geschaltet hat. Die anderen Geräte gingen auch noch. Besten Dank.

**Comment by elektron-bbs** [comment]
Dieses Protokoll wird im Modul 10_SD_GT.pm ausgewertet.
Ich schließe dieses Issue.
