### ISSUE TITLE
controls_signalduino.txt wird teilweise nicht aktualisiert

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#737]
## Steps to Reproduce the Problem

  1. update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r34/controls_signalduino.txt
  2. 2019.12.26 16:09:52 1 : UPD FHEM/00_SIGNALduino.pm
2019.12.26 16:09:52 1 : Got 211287 bytes for FHEM/00_SIGNALduino.pm, expected 211063
2019.12.26 16:09:52 1 : aborting.

## Specifications

  - Microcontroller: egal
  - Version (Firmware): egal

  - Versionmodul (FHEM Module): egal

**Comment by sidey79** [comment]
@elektron-bbs 

Lass mich raten, dem Problem ging noch ein normaler Merge voraus?

**Comment by elektron-bbs** [comment]
Pull request und merge - das eigenartige ist, das drei andere Dateien, die auch betroffen waren, wurden aktualisiert. Nur 00_SIGNALduino.pm ist auch jetzt noch auf altem Stand:

UPD 2019-12-21_23:09:10 211063 FHEM/00_SIGNALduino.pm
UPD 2019-12-26_14:03:19 19839  FHEM/10_SD_GT.pm
UPD 2019-12-26_14:53:37 120748 FHEM/14_SD_UT.pm
UPD 2019-12-26_14:03:19 150728 FHEM/lib/SD_ProtocolData.pm

**Comment by sidey79** [comment]
Das ist, weill der bot nicht in den branch pushen darf. :(

Und vorher, wird der Stand auch nicht mit dem Zielbranch zusammengeführt.
Das habe ich bisher nie verstanden, warum das nicht erfolgt.

Ich werde versuchen die Sperre mal kurzfristig zu deaktivieren.
Wenn man die Controls Datei nicht immer mit dem eigentlichen Repo ablegen müsste, wäre das deutlich einfacher :)

**Comment by elektron-bbs** [comment]
Ich verstehe nur Bahnhof :-(

**Comment by sidey79** [comment]
Die git Fehlermeldung besagt, dass der Bot nicht in diesen Branch pushen darf.

```
un ad-m/github-push-action@master
  with:
    github_token: ***
    branch: dev-r34
    directory: .
  env:
    CONTROLS_FILENAME: controls_signalduino.txt
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch dev-r34
remote: error: GH006: Protected branch update failed for refs/heads/dev-r34.        
remote: error: Required status check "Travis CI - Pull Request" is expected. At least 1 approving review is required by reviewers with write access.        
To https://github.com/RFD-FHEM/RFFHEM.git
 ! [remote rejected] HEAD -> dev-r34 (protected branch hook declined)
error: failed to push some refs to '***github.com/RFD-FHEM/RFFHEM.git'
```

**Comment by sidey79** [comment]
Ich glaube ich habe den Fehler behoben. 100% sicher bin ich mir nicht und er tritt nur auf, wenn das controls file im dev-r34 Branch neu erstellt werden muss.

**Comment by elektron-bbs** [comment]
Jetzt scheint die Datei gar nicht mehr aktualisiert zu werden :-(

Pull request und merge von "revised old information" durch @HomeAutoUser vor etwa 30 Minuten.

controls_signalduino.txt Update Changed / controls File (#738) 17 hours ago

Update bricht ab:

2019.12.27 16:25:09 1 : UPD FHEM/14_FLAMINGO.pm
2019.12.27 16:25:09 1 : Got 13627 bytes for FHEM/14_FLAMINGO.pm, expected 13616
2019.12.27 16:25:09 1 : aborting.

**Comment by sidey79** [comment]
Kennt ihr das Sprichwort

Never Change a running system

**Comment by HomeAutoUser** [comment]
>Never Change a running system

Zuuu gut ;-)

**Comment by sidey79** [comment]
Ich werde gleich mal schauen, aber ich muss zugeben, nachdem die Diskussion um eine Erweiterung des update Befehls schon im Sande verlaufen ist, dass ich kurz davor bin ein Update Kommando zu entwickeln, dass mit Github releases arbeitet .....
Das ist alles von hinten durch die Brust geschossen :)

**Comment by sidey79** [comment]
Ich denke ich habe den Fehler gefunden und entfernt:

https://github.com/RFD-FHEM/RFFHEM/commit/61b4412f198f8072d82b63fe802fcade726959e8


Zumindest wurde diesmal in den richtigen Branch das Update geschoben
