### ISSUE TITLE
OS Windows - SIGNALduino define & commandref

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#743]
## Expected Behavior
- define SIGNALduino on OS Windows with FHEM
- added commandref

## Actual Behavior
- no doc in commandref
- no example

Aus gegebenen Örtlichkeiten und Umständen habe ich soeben den Test gewagt aber kam nicht zum Erfolg. Es wäre schön, wenn mir jemand helfen könnte.

**Comment by HomeAutoUser** [comment]
eine Erweiterung der commandref muss erfolgen mit

`/COM3@57600`

für OS Windows als Portbezeichnung.

grrrrrrrrrrrrr Dokumentationsmuffel ;-)

**Comment by HomeAutoUser** [comment]
1) Nächster Punkt, der cc1101 wird nicht erkannt obwohl er initialisiert ist und ich auch empfange im Terminal.

2) Das Device hat nur set Befehle aber keine get?

```
Internals:
   Clients    :IT:CUL_TCM97001:SD_RSL:OREGON:CUL_TX:SD_AS:Hideki:SD_WS07:SD_WS09: :SD_WS:RFXX10REC:Dooya:SOMFY:SD_BELL:SD_UT:SD_WS_Maverick:FLAMINGO:CUL_WS:Revolt: :FS10:CUL_FHTTK:Siro:FHT:FS20:CUL_EM:Fernotron:SD_Keeloq:SD_GT:SIGNALduino_un:
   DEF        /COM3@57600
   DMSG       nothing
   DevState   INACTIVE
   DeviceName /COM3@57600
   FUUID      5e078a8b-f33f-08a5-cd7a-b6b97cc89436b813
   IDsNoDispatch 2,72.1,82
   LASTDMSG   nothing
   LASTDMSGID nothing
   NAME       SIGNALduino_nano
   NR         19
   STATE      closed
   TIME       1577555515
   TYPE       SIGNALduino
   initResetFlag 1
   initretry  3
   sendworking 0
   version    
   versionProtocols 1.13
   versionmodul v3.4.1_dev_21.12
   MatchList:
     10:SD_WS07 ^P7#[A-Fa-f0-9]{6}[AFaf][A-Fa-f0-9]{2,3}
     11:SD_WS09 ^P9#F[A-Fa-f0-9]+
     12:SD_WS   ^W\d+x{0,1}#.*
     13:RFXX10REC ^(20|29)[A-Fa-f0-9]+
     14:Dooya   ^P16#[A-Fa-f0-9]+
     15:SOMFY   ^Ys[0-9A-F]+
     16:SD_WS_Maverick ^P47#[A-Fa-f0-9]+
     17:SD_UT   ^P(?:14|20|26|29|30|34|46|68|69|76|81|83|86|90|91|91.1|92|93|95)#.*
     18:FLAMINGO ^P13\.?1?#[A-Fa-f0-9]+
     19:CUL_WS  ^K[A-Fa-f0-9]{5,}
     1:IT       ^i......
     20:Revolt  ^r[A-Fa-f0-9]{22}
     21:FS10    ^P61#[A-F0-9]+
     22:Siro    ^P72#[A-Fa-f0-9]+
     23:FHT     ^81..(04|09|0d)..(0909a001|83098301|c409c401)..
     24:FS20    ^81..(04|0c)..0101a001
     25:CUL_EM  ^E0.................
     26:Fernotron ^P82#.*
     27:SD_BELL ^P(?:15|32|41|42|57|79|96)#.*
     28:SD_Keeloq ^P(?:87|88)#.*
     29:SD_GT   ^P49#[A-Fa-f0-9]+
     2:CUL_TCM97001 ^s[A-Fa-f0-9]+
     3:SD_RSL   ^P1#[A-Fa-f0-9]{8}
     4:OREGON   ^(3[8-9A-F]|[4-6][0-9A-F]|7[0-8]).*
     5:CUL_TX   ^TX..........
     6:SD_AS    ^P2#[A-Fa-f0-9]{7,8}
     7:Hideki   ^P12#75[A-F0-9]+
     9:CUL_FHTTK ^T[A-F0-9]{8}
     X:SIGNALduino_un ^[u]\d+#.*
   QUEUE:
   READINGS:
     2019-12-28 18:57:01   state           closed
     2019-12-28 18:02:06   version         0
   helper:
   mcIdList:
     10
     11
     12
     18
     43
     47
     52
     57
     58
     96
   msIdList:
     0
     0.1
     0.2
     0.3
     0.4
     1
     3
     3.1
     4
     6
     7
     13
     13.2
     14
     15
     17
     20
     23
     25
     33
     33.1
     33.2
     35
     41
     49
     51
     53
     55
     65
     68
     74.1
     87
     88
     90
     91.1
     93
   muIdList:
     8
     9
     13.1
     16
     17.1
     19
     21
     22
     24
     26
     28
     29
     30
     32
     34
     36
     37
     38
     39
     40
     42
     44
     44.1
     45
     46
     48
     49.1
     49.2
     50
     56
     59
     60
     61
     62
     64
     66
     67
     69
     70
     71
     72
     73
     74
     76
     79
     80
     81
     83
     84
     85
     86
     89
     91
     92
     94
     95
Attributes:
   hardware   nanoCC1101
```

**Comment by elektron-bbs** [comment]
`SIGNALduino_nano: Can't open /COM3: No such file or directory
`
Vieleicht ja ohne Slash vor COM3? Ich rate aber nur.

Get-Befehle machen ja eigentlich ach erst Sinn, wenn ein SIGNALduino erkannt wurde.

**Comment by HomeAutoUser** [comment]
Die Schnittstelle muss auf jedenfall mit einem / beginnen. Das habe ich verifiziert. Wenn er diese hat und auch das Gerät dran ist, so öffnet er diese aber später schließt er diese wieder weil keine Antwort vom CC1101 obwohl dieser funktioniert.

**Comment by elektron-bbs** [comment]
Den CC1101 hat der SIGNALdino ja:
```
CCVersion =0x14
CCPartnum =0x0
cc1101 found 
```
Tja, serielle Kommnikation unter Windows ist mehr oder weniger Glückssache, so ist zumindest meine Erfahrung.
Hängt der SIGNALduino an einer "richtigen" RS232 oder an irgend so einem USB-seriell-Wandler?

**Comment by sidey79** [comment]
Das mit dem / unter Windows gibt es nicht.  COM3 wäre dann schon eher eine Windows übliche Bezeichnung.

Ich frage mal vorsichtig, wieso Du es nativ unter Windows laufen lassen willst?
In Zeiten des Linux Subsystems für Windows.

**Comment by HomeAutoUser** [comment]
Windows?
Orginalsystem ist eine Etage höher. Pc zum Testen unten & Treppen steigen ist tabu derzeit.

Der Signalduino hängt an einer richtigen.

Es handelt sich um einen testaufbau von der Couch um testen/Erkenntnisse gesammelt werden können.

**Comment by sidey79** [comment]
> Windows?
Hatte ich so verstanden, dass Du FHEM unter Windows zum laufen bringen möchtest?

> Orginalsystem ist eine Etage höher. Pc zum Testen unten & Treppen steigen ist tabu derzeit.
Ui, dann mal gute Besserung.
 
> Es handelt sich um einen testaufbau von der Couch um testen/Erkenntnisse gesammelt werden können.
Läuft da Win10? Dann installier dir das Linux Subsystem. So mache ich das auch und muss mich nicht mit Perl / Windows / FHEM Thematik rumärgern.

**Comment by HomeAutoUser** [comment]
> Hatte ich so verstanden, dass Du FHEM unter Windows zum laufen bringen möchtest?

Richtig, es läuft ja schon. Ging ja simple zu einrichten.

> Ui, dann mal gute Besserung.

Danke, so bleibt mehr Zeit zum Ideen sammeln oder Testen 🗡 

> Läuft da Win10? Dann installier dir das Linux Subsystem. So mache ich das auch und muss mich nicht mit Perl / Windows / FHEM Thematik rumärgern.

Ja Win10.
Linux Subsystem, klingt neu für mich. Muss ich mal lesen und am Ende lerne ich noch hinzu.

**Comment by HomeAutoUser** [comment]
Abschließend würde ich ergänzen, der Hinweis mit dem Subsystem ist Top. Ich habe mir es eingerichtet und somit habe ich auf dem Tablett die Möglichkeit nun FHEM zu testen und mir den Testaufbau für den FSK weiter anzugehen.

Frage, wollen wir einen Hinweis in der Commandref diesbezüglich hinterlassen?
