### ISSUE TITLE
Uninitalized device can't be flashed via module

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#746]
## Expected Behavior

If a device is not initalized it can be flashed via fhem module.
The get command to receive available firmware is not displayed on inactive devices.

## Actual Behavior
![image](https://user-images.githubusercontent.com/7968127/71563383-df66cb80-2a8e-11ea-8c34-6ecdd585083d.png)

No get commands are available

## Steps to Reproduce the Problem

  1. Disconnect uC
  2. Wait for fhem to detect that the uC is not longer initalized
  3. Try to get available firmware via FHEMWEB

## Specifications

  - Versionmodul (FHEM Module): v3.4.2_dev_28.12

**Comment by HomeAutoUser** [comment]
Nun sehe ich erstmal das "Elend". Get Befehle gehen auch nicht.

**Comment by elektron-bbs** [comment]
Das Flashen funktioniert aber nicht nur bei "uninitalized" device nicht, sondern auch bei "opened". Da führt es sogar zum Neustart von FHEM. Getestet habe ich auf 2 Systemen mit diesen Versionen:

```
version    V 3.4.0-dev SIGNALduino cc1101 (433 Mhz ) - compiled at Dec  4 2019 21:59:32
versionProtocols 1.13
versionmodul v3.4.2_dev_28.12
```
```
hardware: radinoCC1101
2019.12.30 15:38:10 1: sduinoACM: found availableFirmware for ESP8266,ESP8266cc1101,ESP32,nano328,nanoCC1101,miniculCC1101,promini,radinoCC1101
2019.12.30 15:38:10 1: PERL WARNING: Use of uninitialized value $index in array element at ./FHEM/00_SIGNALduino.pm line 670.

2019.12.30 15:38:43 1: PERL WARNING: Reference found where even-sized list expected at ./FHEM/00_SIGNALduino.pm line 691.
2019.12.30 15:38:43 3: sduinoACM: Set, flash 3.4.0-dev_041219 try to fetch github assets for tag 3.4.0-dev_041219
2019.12.30 15:38:43 3: sduinoACM: Set, flash 3.4.0-dev_041219 try to fetch release https://api.github.com/repos/RFD-FHEM/SIGNALDuino/releases/tags/3.4.0-dev_041219
2019.12.30 15:38:43 1: PERL WARNING: Use of uninitialized value $d in hash element at fhem.pl line 4534.
2019.12.30 15:38:43 1: PERL WARNING: Use of uninitialized value $name in concatenation (.) or string at ./FHEM/00_SIGNALduino.pm line 4437.
Can't use an undefined value as a subroutine reference at ./FHEM/00_SIGNALduino.pm line 4437.
2019.12.30 15:38:45 1: Including fhem.cfg
2019.12.30 15:38:45 3: WEB: port 8083 opened
```
```
hardware nano328
2019.12.30 09:32:54.654 1: sduino_USB0: found availableFirmware for ESP8266,ESP8266cc1101,ESP32,nano328,nanoCC1101,miniculCC1101,promini,radinoCC1101
2019.12.30 09:32:55.065 1: PERL WARNING: Use of uninitialized value $index in array element at ./FHEM/00_SIGNALduino.pm line 670.

2019.12.30 09:33:40.308 3: sduino_USB0: Set, flash 3.4.0-dev_041219 try to fetch github assets for tag 3.4.0-dev_041219
2019.12.30 09:33:40.308 3: sduino_USB0: Set, flash 3.4.0-dev_041219 try to fetch release https://api.github.com/repos/RFD-FHEM/SIGNALDuino/releases/tags/3.4.0-dev_041219
2019.12.30 09:33:40.901 1: PERL WARNING: Use of uninitialized value $d in hash element at fhem.pl line 4534.
2019.12.30 09:33:40.901 1: PERL WARNING: Use of uninitialized value $name in concatenation (.) or string at ./FHEM/00_SIGNALduino.pm line 4437.
Can't use an undefined value as a subroutine reference at ./FHEM/00_SIGNALduino.pm line 4437.
2019.12.30 09:33:41.420 1: Including fhem.cfg
2019.12.30 09:33:41.525 3: WEB: port 8083 opened
```
```
hardware ESP8266cc1101
2019.12.30 09:40:11.974 1: sduino_IP: found availableFirmware for ESP8266,ESP8266cc1101,ESP32,nano328,nanoCC1101,miniculCC1101,promini,radinoCC1101
2019.12.30 09:40:12.445 1: PERL WARNING: Use of uninitialized value $index in array element at ./FHEM/00_SIGNALduino.pm line 670.

2019.12.30 09:41:56.704 1: PERL WARNING: Reference found where even-sized list expected at ./FHEM/00_SIGNALduino.pm line 691.
2019.12.30 09:41:56.704 3: sduino_IP: Set, flash 3.4.0-dev try to fetch github assets for tag 3.4.0-dev
2019.12.30 09:41:56.704 3: sduino_IP: Set, flash 3.4.0-dev try to fetch release https://api.github.com/repos/RFD-FHEM/SIGNALDuino/releases/tags/3.4.0-dev
2019.12.30 09:41:57.014 1: PERL WARNING: Use of uninitialized value $d in hash element at fhem.pl line 4534.
2019.12.30 09:41:57.014 1: PERL WARNING: Use of uninitialized value $name in concatenation (.) or string at ./FHEM/00_SIGNALduino.pm line 4437.
Can't use an undefined value as a subroutine reference at ./FHEM/00_SIGNALduino.pm line 4437.
2019.12.30 09:41:57.421 1: Including fhem.cfg
2019.12.30 09:41:57.526 3: WEB: port 8083 opened
```
Gestern mit diesen Versionen hat es noch funktioniert:
```
version    V 3.4.0-dev SIGNALduino cc1101 (433 Mhz ) - compiled at Dec  4 2019 21:59:32
versionProtocols 1.14
versionmodul v3.4.1_dev_21.12
```

**Comment by HomeAutoUser** [comment]
>Da führt es sogar zum Neustart von FHEM. Getestet habe ich auf 2 Systemen mit diesen Versionen:

kann ich bestätigen!

Bin schon nebenher auf der Suche von allen Fehlern, aber @sidey79 war ja wieder mal sparsam mit Hilfsausgaben ;-)

**Comment by HomeAutoUser** [comment]
Ich habe mich nun mit deiner Set Routine mal beschäftigt. Die muss umgestellt werden und so wie du es dir dachtest geht es nicht. Es laufen Prozesse schneller als was gesetzt wird und der nächste Durchlauf kommt. Mit

```
sub SIGNALduino_Set($$@) {
	my ($hash,$name, @a) = @_;
  
 	 return "\"set SIGNALduino\" needs at least one parameter" if(@a < 1);

	if (!InternalVal($name,"hasCC1101",0) && $a[0] =~ /^cc1101/) {
		return "This command is only available with a cc1101 receiver";
	}
	if (!exists($sets{$a[0]})) {
		return "Unknown argument $a[0], choose one of supported commands"; 	
	}

	my $rcode = "";
	if ( $hash->{DevState} eq "initialized" && ($a[0] eq "?" || $a[0] eq 'reset'|| $a[0] eq 'flash') && ref @{$sets{$a[0]}}[1] eq "CODE") {
   	$rcode = @{$sets{$a[0]}}[1]->($hash,@a);
	} else {
		$rcode = @{$sets{$a[0]}}[1]->($hash,@a);
		
		if ($rcode && $rcode ne "") {
			$rcode =~ s/flash:textFieldNL/raw:/g;
			$rcode =~ s/flash:.*raw:/raw:/g;
		}

		if ($hash->{DevState} eq "closed" && $a[0] ne "?" && $a[0] ne "reset" && $a[0] ne "flash") {
			return "$name is not active, may firmware is not supported, please flash or reset";
		}
		return "" if !($rcode);
	}

	return $rcode; # We will exit here, and give an output only, $rcode has some value
}
```

wäre das Verhalten so, das du Befehle nicht ausführen kannst wenn das Device nicht initialized ist bis auf flash und reset. Es hat nur den kleinen "Fehler" derzeit noch, wenn du das provozierst via close, dann kommt die Ausgabe sofort. Wenn du relaod machst und dann clos, ist es ja richtig.

**Comment by HomeAutoUser** [comment]
Manchmal kommen die Eingebungen wenn man drauf schaut :-) Ich habe den Code im oberen Post überarbeitet und schau ob es so deinen Bedürfnissen entspricht.

1) Set Befehle sind nur machbar wenn initializised
2) flash nur möglich wenn initialized
3) wenn geschlossen, so kein flash und bei Aufruf der Befehle kommt not aktive

```
sub SIGNALduino_Set($$@) {
	my ($hash,$name, @a) = @_;
  
 	 return "\"set SIGNALduino\" needs at least one parameter" if(@a < 1);

	if (!InternalVal($name,"hasCC1101",0) && $a[0] =~ /^cc1101/) {
		return "This command is only available with a cc1101 receiver";
	}
	if (!exists($sets{$a[0]})) {
		return "Unknown argument $a[0], choose one of supported commands"; 	
	}

	my $rcode = "";
	if ( $hash->{DevState} eq "initialized" && ($a[0] eq "?" || $a[0] eq 'reset'|| $a[0] eq 'flash') && ref @{$sets{$a[0]}}[1] eq "CODE") {
   	$rcode = @{$sets{$a[0]}}[1]->($hash,@a);
	} else {
		return "$name is not active, please reset" if ($hash->{DevState} eq "closed" && $a[0] ne "?" && $a[0] eq "close");
		$rcode = @{$sets{$a[0]}}[1]->($hash,@a);
		
		if ($rcode && $rcode ne "") {
			$rcode =~ s/flash:textFieldNL/raw:/g;
			$rcode =~ s/flash:.*raw:/raw:/g;
		}

		if ($hash->{DevState} eq "closed" && $a[0] ne "?" && $a[0] ne "reset" && $a[0] ne "flash" && $a[0] ne "close") {
			return "$name is not active, may firmware is not supported, please flash or reset";
		}
		return "" if !($rcode);
	}

	return $rcode; # We will exit here, and give an output only, $rcode has some value
}
```

**Comment by sidey79** [comment]
Wieso muss denn in `$rcode` der Text durch 'raw' ersetzt werden?

**Comment by HomeAutoUser** [comment]
> 
> 
> Wieso muss denn in `$rcode` der Text durch 'raw' ersetzt werden?

Weil dort die komplette Setlist drin ist als String. Wenn du flash raus haben willst, so habe ich mir den Punkt flash bis raw genommen und ersetze diesen mit raw ;-)

**Comment by sidey79** [comment]
> > Wieso muss denn in `$rcode` der Text durch 'raw' ersetzt werden?
> 
> Weil dort die komplette Setlist drin ist als String. Wenn du flash raus haben willst, so habe ich mir den Punkt flash bis raw genommen und ersetze diesen mit raw ;-)

Die möglichen Kommandos werden in SIGNALduino_Set_FhemWebList generiert. Aber flash zu entfernen trifft nicht das Problem. Es macht es ja eher größer:

> If a device is not initalized it can be flashed via fhem module.
> The get command to receive available firmware is not displayed on inactive devices.

Dass der Flash Befehl angeboten ist, ist ja schon mal gut, aber man kann keine Firmware abrufen, da das get Kommando fehlt. Das sollte aber zumindest bei einem Arduino möglich sein, wenn der erstmalig angesteckt wird

**Comment by HomeAutoUser** [comment]
>Die möglichen Kommandos werden in SIGNALduino_Set_FhemWebList generiert. Aber flash zu entfernen trifft nicht das Problem. Es macht es ja eher größer:

Ich bin der Meinung die Kommandos sind schon vorhanden wenn die Setschleife durchgealufen ist.
Alles was danach kommt, beeiflusst diese nicht.

>Dass der Flash Befehl angeboten ist, ist ja schon mal gut, aber man kann keine Firmware abrufen, da das get Kommando fehlt. 

Dann haben wir mehrer Faktoren die einwirken und nicht mit diesem ISSUES genau übereinstimmen denke ich. somit kommen Missverständnisse auf.

**Comment by HomeAutoUser** [comment]
@sidey79 
du könntest auch Recht haben mit der Setlist, aber da tanzt du wieder aus der Reihe mit der Umsetzung und erschlägst uns mit Neuigkeiten *grins* Ich nehme ja immer die Dev Wiki als vorlage und schaue.

```
2019.12.30 20:31:00 1: PERL WARNING: Subroutine getProtocolList redefined at ./FHEM/lib/SD_ProtocolData.pm line 2497.
2019.12.30 20:31:01 3: nano_433Mhz: Set_FhemWebList running
2019.12.30 20:31:01 3: nano_433Mhz: SETLIST fertig
2019.12.30 20:31:01 3: nano_433Mhz: Set_FhemWebList running
2019.12.30 20:31:01 3: nano_433Mhz: SETLIST fertig
2019.12.30 20:31:02 3: nano_433Mhz: Set_FhemWebList running
2019.12.30 20:31:02 3: nano_433Mhz: SETLIST fertig
2019.12.30 20:31:02 3: nano_433Mhz: Set_FhemWebList running
2019.12.30 20:31:02 3: nano_433Mhz: SETLIST fertig

```

**Comment by sidey79** [comment]
> Ich bin der Meinung die Kommandos sind schon vorhanden wenn die Setschleife durchgealufen ist.
> Alles was danach kommt, beeiflusst diese nicht.

Was meinst Du damit? Ich verstehe nicht ganz befürchte ich.
SIGNALduino_Set ruft SIGNALduino_Set_FhemWebList auf, wenn ein ? als Parameter übergeben wird.

> > Dass der Flash Befehl angeboten ist, ist ja schon mal gut, aber man kann keine Firmware abrufen, da das get Kommando fehlt.
> 
> Dann haben wir mehrer Faktoren die einwirken und nicht mit diesem ISSUES genau übereinstimmen denke ich. somit kommen Missverständnisse auf.

Okay, was genau hast Du denn noch für ein Verhalten festgestellt, dass nicht passt?

**Comment by HomeAutoUser** [comment]
Setlist Stimmt deine Variante.

Das Verhalten was nicht richtig ist, werde ich morgen nachstellen sonst gibts Ärger hier :-)
Ich vermute, die "Vermischung" von Kleinigkeiten an anderer Stelle fielen da mit ein.

**Comment by HomeAutoUser** [comment]
Wie ist der Stand hier?

**Comment by sidey79** [comment]
Ich glaube flash geht mittlerweile auch für nicht initialisierte Geräte

**Comment by HomeAutoUser** [comment]
WEnn das so ist, dann könnten wir dies als erledigt betrachten.

**Comment by HomeAutoUser** [comment]
Kann dieser Faden geschlossen werden?
