### ISSUE TITLE
Internal cc1101_frequency vs  attribute cc1101_frequency 

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#747]
## Expected Behavior
Clear usage of internal or attribute cc1101_frequency 

## Actual Behavior
The internal cc1101_frequency is used in some places 

## Specifications

  - Versionmodul (FHEM Module): v3.4.2_dev_28.12

**Comment by HomeAutoUser** [comment]
Verstehe ich dich richtig,
du möchtest dich von einem von beiden „trennen“? Entweder internal oder das Attribut ?

**Comment by sidey79** [comment]
Ja, ich bin nicht sicher, ob es Absicht oder ein Fehler ist.
Das Internal wird aber glaube ich nicht gesetzt, dennoch aber angefragt.

**Comment by sidey79** [comment]
Wenn das Attribut cc1101_frequency gesetzt wird:
https://github.com/RFD-FHEM/RFFHEM/blob/a493614dff5e4b71a9ff7945daeb56c7234c73e4/FHEM/00_SIGNALduino.pm#L2700-L2709

Rückantwort der Abfrage der patable:
https://github.com/RFD-FHEM/RFFHEM/blob/a493614dff5e4b71a9ff7945daeb56c7234c73e4/FHEM/00_SIGNALduino.pm#L983-L984

Bei set cc1101_freq:
https://github.com/RFD-FHEM/RFFHEM/blob/a493614dff5e4b71a9ff7945daeb56c7234c73e4/FHEM/00_SIGNALduino.pm#L4481-L4487

**Comment by elektron-bbs** [comment]
Ich bin da auch schon mehrmals über diese Ausgabe im Log gestolpert:

`2019.12.30 15:36:59 3: sduinoIP: Attr, delete cc1101_frequency
`

Da das Attribut aber anschließend immer noch gesetzt ist, habe ich mich nicht weiter darum gekümmert.
Das Attribut finde ich sinnvoller, da der User hier auch eine evtl. abweichende Frequenz hinterlegen kann.

**Comment by HomeAutoUser** [comment]
>Da das Attribut aber anschließend immer noch gesetzt ist, habe ich mich nicht weiter darum gekümmert.
Das Attribut finde ich sinnvoller, da der User hier auch eine evtl. abweichende Frequenz hinterlegen kann.

Zusätzlich hat das Attribut die Möglichkeit, dies zu verarbeiten. Ich habe da ggf im Hinterkopf, wenn der User ein raw e macht kommt standard erstmal 433Mhz als ergebnis und man muss zusätzlich nochmal die Frequenz setzen. Dieses Verhalten tat sich auf wo ich hier mit den verschiedenen Bändern experimentiere.

**Comment by elektron-bbs** [comment]
Wenn ich das richtig sehe, existiert mittlerweile nur noch das Attribut "cc1101_frequency".
Ich schließe diese Issue.
