### ISSUE TITLE
oregon pir client module wrong

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#779]
## Expected Behavior

The specified client module is correct for Oregon PIR (52)

## Actual Behavior

Oregon PIR is noted with OREGON as client module, but u52 seems not to be dispatched to the OREGON module

## Steps to Reproduce the Problem

  1. look at the protoco definition
https://github.com/RFD-FHEM/RFFHEM/blob/dev-r34/FHEM/lib/SD_ProtocolData.pm#L1474
 
 - Versio SD Protocol Data :1.15

**Comment by HomeAutoUser** [comment]
Sollte es wirklich Oregon sein, so kommen wir mit der Preamble
`preamble				=> 'u52#',`
nicht weiter.

Das Modul Oregon reagiert auf 
`  $hash->{Match}     = "^(3[8-9A-F]|[4-6][0-9A-F]|7[0-8]).*", #38-78`.

Ich bin der Meinung, gelesen zu haben, das das Protokoll 52 noch unklar wäre zu einigen Punkten.

**Comment by HomeAutoUser** [comment]
Es könnte sein, das hier https://github.com/letscontrolit/RFLinkSmall/blob/master/Plugins/Plugin_063.c das Ganze hilfreich ist. Da ist auf jedenfall von PIR die rede.

Leider kann ich den Code nicht richtig interprätieren.

**Comment by sidey79** [comment]
Ich fasse noch mal zusammen.

Das Protokoll 52 sendet keine Daten an das Oregon Modul.
Das Oregon Modul könnte auch nichts mit diesen Daten anfangen. Es ist meiner Ansicht nach ein Dokumentationsfehler.

**Comment by HomeAutoUser** [comment]
Das würde ich auch vermuten.
Der genannte PIR welchen ich über das Forum ausfündig machte, ist auch nicht mehr bei dem User in Benutzung weil er keinen Sduino mehr in Verwendung hat. Er stellt nur die PIR´s noch zur Verfügung für einen kleinen Taler.
