### ISSUE TITLE
CC1101 - after CheckVersionResp, enable receiver (XE) - ccconf query

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#786]
## Expected Behavior
- after CheckVersionResp, enable receiver (XE) one query for configuration
- query fill Internals cc1101_config & cc1101_config_ext

## Actual Behavior
- user must manualy `get ccconf`

## Specifications

  - Versionmodul (FHEM Module): v3.4.2_dev_20.01

**Comment by HomeAutoUser** [comment]
Hallo, ich hoffe die Intension sollte aus dem ersten Post hervor gehen.

Der Ansatz bzw. Vorschlag wäre, das wir in der Sub
`sub SIGNALduino_CheckVersionResp`

folgendes abändern und dort einbauen
```
InternalTimer(gettimeofday() + SDUINO_KEEPALIVE_TIMEOUT, "SIGNALduino_KeepAlive", $hash, 0);
if ($hash->{version} =~ m/cc1101/) {
  $hash->{cc1101_available} = 1;
  SIGNALduino_SendFromQueue($hash, "C0DnF");  # Submitted request direct
  ... weitere Verarbeitung
};
$msg = $hash->{version};
```

Wiedenkt Ihr darüber?

**Comment by sidey79** [comment]
Ich tendiere eher zu Variante 2, aber ich glaube die müssten wir durch einen internal Timer verzögern, da sonst uCcmd überschrieben wird

**Comment by HomeAutoUser** [comment]
Dann verwenden wir die Variante 2. Diese finde ich auch „verständlicher“ gegenüber der normalen Benutzervariante im FhemWeb.

Der Timer sollte nicht das Problem sein. Ich hadere nur noch, wie wir das verzögerte RETURN erhalten.

**Comment by sidey79** [comment]
Hmm, das Internal wird nicht über longpoll aktualisiert, da hilft nur ein manueller Browser Refresh :)

**Comment by HomeAutoUser** [comment]
Wie wollen wir hier fortsetzen?

**Comment by sidey79** [comment]
Ich würde da nichts weiter unternehmen. Muss man halt einen browser refresh machen

**Comment by HomeAutoUser** [comment]
Ja das sehe ich auch so :)
Eher meinte ich mit der Erarbeitung des Codes „grins“

**Comment by sidey79** [comment]
Wie üblich, mittels Pull requests.

Ich bin aktuell ein bisschen schlapp. Daher nicht ganz so auf Zack.

**Comment by HomeAutoUser** [comment]
Wie denkst du @sidey79 bzw. @elektron-bbs hierüber?
Somit wird nach einem Shutdown restart und nach einem enable receiver (XE) die Abfrage abgesetzt und somit werden die Internals gefüllt.

**Comment by HomeAutoUser** [comment]
Es gibt hier https://github.com/HomeAutoUser/RFFHEM/commit/35224b1d6a7c927242abb88d63883141089063fd eine angepasste Version weil ich zusätzlich gleich noch die ccpatable Abfrage mit eingebunden habe.

Bitte testen und Meinungen zur Umsetzung @elektron-bbs & @sidey79.

**Comment by HomeAutoUser** [comment]
Sobald der https://github.com/RFD-FHEM/RFFHEM/pull/791 erledigt ist, hätte ich einen Vorschlag zu liefern für die automatische Konfigabfrage. Die Schublade ist gefüllt ;-)

**Comment by HomeAutoUser** [comment]
Mit https://github.com/RFD-FHEM/RFFHEM/pull/800 erledigt
