### ISSUE TITLE
uniform information - einheitliche Angaben - flash version´s

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#797]
Die Bilder sollten für sich sprechen

![a](https://user-images.githubusercontent.com/25631927/74385009-cf167000-4df2-11ea-8d06-ed38f3ae5d6f.jpg)
![b](https://user-images.githubusercontent.com/25631927/74385011-cfaf0680-4df2-11ea-9fa3-31cef9fc48f3.jpg)

Meine Vorschläge:
1) (Versionsnummer)_(Datum vom kompilieren)
2) (Datum vom kompilieren)
3) (Datum vom kompilieren)_(Dev)

Dazu würde ich das Datumsformat YYMMDD favorisieren weil somit die Sortierung automatisch aufsteigend stattfindet.
Bsp:
1)
`3.4.0-dev_200212`
2) 
```
200212
191204
```
3)
```
200212_dev
191204 (als Beispiel für master wenn kein _dev dahinter geschrieben wurde)
```

**Comment by sidey79** [comment]
Für Zwischenstände finde ich 
(Versionsnummer)(_dev)_(Datum vom kompilieren)
passend.

Für Releases (Versionsnummer) ohne Datum und ohne (_dev)

**Comment by HomeAutoUser** [comment]
**mit Versionsnummer**

Es ist eine Möglichkeit.
- Zwischenstände, (Versionsnummer)(dev)(Datum vom kompilieren)
- Releases, (Versionsnummer) ohne Datum und ohne (_dev)

Aussagekräftiger wäre vielleicht auch
- Zwischenstände, (Versionsnummer)(dev)_(Datum vom kompilieren)
- Releases, (Versionsnummer)_(Datum vom kompilieren)
das hat den Vorteil, das man auf einen Blick sieht, wann das Release erschien ohne groß in Github o.ä. nachzusehen.

**ohne Versionsnummer**
- Zwischenstände, (Datum vom kompilieren)_(dev)
- Releases, (Datum vom kompilieren)

**Comment by sidey79** [comment]
Zwischenstände sind ja bereits als prerelease getaggt und werden nur im Dropdown angezeigt, wenn updateChannel auf Testing gesetzt ist

**Comment by HomeAutoUser** [comment]
> Zwischenstände sind ja bereits als prerelease getaggt und werden nur im Dropdown angezeigt, wenn updateChannel auf Testing gesetzt ist

Das mag sein. Es soll ja selbst wenn updateChannel auf Testing steht, eine Sortierung für den Benutzer vorhanden sein und keine gemischte Struktur.

So würde ich es für aussagekräftig halten.

```
3.4dev_200511
3.3_191103
3.2dev_190124
3.1_180516
```

Für was plädierst du @elektron-bbs?

**Comment by elektron-bbs** [comment]
So ähnlich:

```
3.4_200511_dev
3.3_191103_rel
3.2_190228_dev
3.2_190124_dev
3.1_180516_rel
```

dürfte es die beste Sortierung ergeben und es bleibt übersichlich.

**Comment by sidey79** [comment]
Wir könnten bei testing die stabilen releases ausblenden.

Ansonsten würde ich gern kompatibel zu:
https://semver.org/lang/de/
halten.

**Comment by elektron-bbs** [comment]
Dann würde ja

```
3.4.0
3.3.0
3.2.1
3.2.0
3.1.0

```
auch reichen. Die Hauptsache ist doch, das nicht mal 3.3.1, dann 200105 und zu guter letzt 110220 erscheint, wie es jetzt der Fall ist. Also einfach mal ein einheitliches Schema beibehalten.

**Comment by sidey79** [comment]
So wie ich Semantic Versioning verstehe hat ein "Release"
`3.4.0`

Eine Zwischenversion hat
`3.4.0-fixVersion`

Eine Zwischenversion mit "Build" hat
`3.4.0-fixVersion+c8fe` oder `3.4.0-fixVersion+20200213`

**Comment by elektron-bbs** [comment]
Eigentlich sollte doch bei jedem Compilieren Z hochgezählt werden.

**Comment by sidey79** [comment]
Das hängt davon, ab was unter Veröffentlichen verstanden wird.
Für jeden commit die Patch Version zu erhöhen halte ich nicht für praktikabel.

**Comment by HomeAutoUser** [comment]
Also

```
3.4
3.3_dev_2
3.3_dev_1
3.1
```

so in etwa wäre die Einigung wobei _1 bzw _2 ein Zähler oder Datum sein könnte.

**Comment by sidey79** [comment]
Der letzte teil sollte die commitid oder halt datum würde ich sagen, mit nur einer Zahl kann man sonst nichts anfangen.

**Comment by HomeAutoUser** [comment]
Anstatt der Commitbezeichnung finde ich das Datum besser.

**Comment by elektron-bbs** [comment]
Die "Semantic Versioning Spezifikation" geht doch eindeutig vom Format X.Y.Z aus.
Der BASCOM-Compiler (ich muss mich jetzt mal outen :-) zählt z.B. bei jedem Compilieren Z selbst hoch. Wenn ich das jetzt veröffentlichen würde, käme dann eben so etwas heraus:

```
3.4.0
3.3.0
3.2.27
3.2.12
3.2.1
3.2.0
3.1.0
```

**Comment by sidey79** [comment]
Wenn man etwas veröffentlich ja. Aber nicht jeder compile Vorgang wird ja veröffentlicht.

Meine Interpretation wäre, dass "releases" = veröffentlicht
"pre releases" = nicht veröffentlicht.

**Comment by elektron-bbs** [comment]
Veröffentlicht heist für mich, das ist in dem Fall bei Github als bin-File hinterlegt.
pre-release sieht keiner außer dir.

**Comment by sidey79** [comment]
wieso sieht prerelease keiner?

release ist doch veröffentlichen auf deutsch.

pre-release ist vorabversion

**Comment by elektron-bbs** [comment]
Ich denke, das sieht jetzt gut aus:

![flash](https://user-images.githubusercontent.com/26026988/211871427-8e2e3e13-ea0d-42ff-823f-9da1ff1fb464.png)
