### ISSUE TITLE
Teilweise falsche Werte WH5300 Sensor als WH1080 Device

### ISSUE THREAD

**Issue by johol** [RFD-FHEM/RFFHEM#810]
## Expected Behavior
Korrekte Werte

## Actual Behavior
Falsche Werte für  windDirection, windDirectionDegree, windDirectionText, battery und batteryState.
Die Werte ändern sich nicht, sondern haben konstant folgende Werte

battery         low
batteryState    low
windDirection   10
windDirectionDegree 225
windDirectionText SW

## Steps to Reproduce the Problem
list WH1080
   CODE       WH1080
   DEF        WH1080
   FUUID      5d62fe17-f33f-9f25-abad-4e811dc5e3082150
   LASTInputDev sduino
   MODEL      WH1080
   MSGCNT     10
   NAME       WH1080
   NR         1194
   STATE      T: 2  H: 82  Ws:0.7  Wg:1.0 m/s Wd: SW  R: 690 D: -0.8
   TYPE       SD_WS09
   bitMSG     
   lastMSG    FFA861A452020308FC8AD0
   lastReceive 1585494346.63362
   sduino_DMSG P9#FEA1869148080C23F22B40
   sduino_MSGCNT 10
   sduino_Protocol_ID 9
   sduino_RAWMSG MU;P0=15152;P1=-977;P2=481;P3=1466;P4=-31032;D=01212121212121213121312131313131212131313131212131213131213131312131213131213131313131313121313131313131312121313131312131313121212121212131312131313121312131212131213131313421212121212121213121312131313131212131313131212131213131213131312131213131213131;CP=2;R=44;O;
   sduino_RSSI -52
   sduino_TIME 2020-03-29 17:05:46
   READINGS:
     2020-03-29 17:05:46   battery         low
     2020-03-29 17:05:46   batteryState    low
     2020-03-29 17:05:46   dewpoint        -0.8
     2020-03-29 17:05:46   humidity        82
     2020-03-29 17:05:46   id              134
     2020-03-29 17:05:46   rain            690
     2020-03-29 17:05:46   rain_calc_all   cH: 0.0 lH: 690.0 cD: 0.0 lD: 690.0 IR: 1 Rnow: 0.0 Rdif: 0
     2020-03-29 17:05:46   rain_calc_d_curr 0.0
     2020-03-29 16:58:34   rain_calc_d_last 690.0
     2020-03-29 16:58:34   rain_calc_d_start 690.0
     2020-03-29 16:58:34   rain_calc_d_trig_tsecs 1585546200
     2020-03-29 17:05:46   rain_calc_h_curr 0.0
     2020-03-29 16:58:34   rain_calc_h_last 690.0
     2020-03-29 16:58:34   rain_calc_h_start 690.0
     2020-03-29 16:58:34   rain_calc_h_trig_tsecs 1585495800
     2020-03-29 17:05:46   rain_calc_now_diff 0
     2020-03-29 17:05:46   rain_calc_now_rate 0.0
     2020-03-29 17:05:46   rain_calc_now_value 690.0
     2020-03-29 17:05:46   rain_calc_tsecs 1585494346.63432
     2020-03-29 17:05:46   rain_total      690
     2020-03-29 17:05:46   state           T: 2  H: 82  Ws:0.7  Wg:1.0 m/s Wd: SW  R: 690
     2020-03-29 17:05:46   temperature     2
     2020-03-29 17:05:46   windDirection   10
     2020-03-29 17:05:46   windDirectionAverage 0
     2020-03-29 17:05:46   windDirectionDegree 225
     2020-03-29 17:05:46   windDirectionText SW
     2020-03-29 17:05:46   windGust        1.0
     2020-03-29 17:05:46   windGust_fts    3.3
     2020-03-29 17:05:46   windGust_kmh    3.6
     2020-03-29 17:05:46   windGust_kn     1.9
     2020-03-29 17:05:46   windGust_mph    2.2
     2020-03-29 17:05:46   windSpeed       0.7
     2020-03-29 17:05:46   windSpeed_fts   2.3
     2020-03-29 17:05:46   windSpeed_kmh   2.5
     2020-03-29 17:05:46   windSpeed_kn    1.4
     2020-03-29 17:05:46   windSpeed_mph   1.6

## Specifications

  - Microcontroller:
 SIGNALDuino
  - Version (Firmware):
 3.4.0-dev SIGNALduino cc1101 (chip CC1101) - compiled at Dec  4 2019 22:02:15
  - Versionmodul (FHEM Module):
 v3.4.2_dev_24.03

**Comment by HomeAutoUser** [comment]
Hallo @johol,
hast du die Möglichkeit die Werte welche herauskommen sollten, an einer Station abzulesen?

**Comment by johol** [comment]
Hallo,
ich könnte auf den Sensor schauen und die Richtung schätzen in die die Fahne zeigt.

**Comment by johol** [comment]
Ich habe die Vermutung, dass die Temperaturwerte nur 8 bit lang sind. Die lagen immer viel niedriger als die von einem 10 Meter entfernten Thermometer. Die anderen 4 bit könnten die Windrichtung sein. Mit dem patch passt das auf die aktuellen Wind und Temperature Verhältnisse.

`
--- 14_SD_WS09.pm.20200329.bak  2020-03-29 18:11:16.941027903 +0200
+++ 14_SD_WS09.pm       2020-03-29 19:22:25.739841847 +0200
@@ -230,9 +230,11 @@
                        $model = "WH1080";
                        $id = SD_WS09_bin2dec(substr($sensdata,4,8));
                        $bat = (SD_WS09_bin2dec((substr($sensdata,64,4))) == 0) ? 'ok':'low' ; # decode battery = 0 --> ok
-                       $temp = (SD_WS09_bin2dec(substr($sensdata,12,12)) - 400)/10;
+#                      $temp = (SD_WS09_bin2dec(substr($sensdata,12,12)) - 400)/10;
+                       $temp = (SD_WS09_bin2dec(substr($sensdata,12,8)))/5;
                        $hum = SD_WS09_bin2dec(substr($sensdata,24,8));
-                       $windDirection = SD_WS09_bin2dec(substr($sensdata,68,4));  
+#                      $windDirection = SD_WS09_bin2dec(substr($sensdata,68,4));
+                       $windDirection = SD_WS09_bin2dec(substr($sensdata,20,4));    
                        $windDirectionText = $winddir_name[$windDirection];
                        $windDirectionDegree = $windDirection * 360 / 16;
                        $windSpeed =  round((SD_WS09_bin2dec(substr($sensdata,32,8))* 34)/100,01);`

**Comment by HomeAutoUser** [comment]
Hallo @johol,
kannst du bitte 2 oder 3 RAWMSG (verbose 4 - Signalduino) Posten mit den dazu gehörigen richtigen Werte (abgelesen Station) welche als Ergebnis in den Readings herauskommen sollten. Die RAWMSG benötigen wir zum testen sowohl zur Dokumentation.

Wenn die Verarbeitung deiner WH5300 anders erfolgt wie bei der WH1080, so muss ein zusätzliches Model zur Auswahl ergänzt werden.

**Comment by elektron-bbs** [comment]
@johol 
Nur 8 bit für Temperaturwerte mit Nachkommastelle reichen nicht. In den Sourcen hier:
https://github.com/merbanan/rtl_433/blob/master/src/devices/fineoffset_wh1080.c
ist die Rede von 10 bit:

```
int temp_raw      = ((br[2] & 0x03) << 8) | br[3]; // only 10 bits, discard top bits 
float temperature = (temp_raw - 400) * 0.1; 

```

**Comment by HomeAutoUser** [comment]
Hier gibt es auch nochmal Infos zum Sensor.

https://forum.arduino.cc/index.php?topic=255227.15
https://github.com/bhaap/WH5300-weatherstation-ESP8266-MQTT-json/blob/master/WH5300-weatherstation-ESP8266-MQTT-json.ino

**Comment by HomeAutoUser** [comment]
@johol,
kamst du nochmal zum testen bzw zum sammeln von Informationen in Form von RAWMSGs und dem "gewünschten Wert" abgelesen?

**Comment by johol** [comment]
Sorry, dass ich mich jetzt erst wieder melde. Hier die letzten raw messages

2020.04.01 20:46:35 4: sduino: SD_WS09_Parse0 msg=FF50C3AE66000011FD15D8 Bin=1111111101010000110000111010111001100110000000000000000000010001111111010001010111011000 syncp=1 length:88
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse CRC_AUS:0 
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_SHIFT_1 NOK raw:FF50C3AE66000011FD15D8 crc:230 -> shift
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_SHIFT_2 OK raw:FFA861D733000008FE8AEC msg:P9#FFA861D733000008FE8AEC crc:0
2020.04.01 20:46:35 5: sduino: SD_WS09_Parse_0 whid=1010
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_1 msg=10101000011000011101011100110011000000000000000000001000111111101000101011101100 length:80
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_2 WH1080 id:134, Windspeed bit: 00000000 Dec: 0.0
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_3 WH1080 id:134, Windguest bit: 00000000 Dec: 0.0
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_4 WH1080 id:134, Rain bit: 100011111110 Dec: 690.6
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_5 WH1080 id:134, bat:low, temp=7.1, hum=51, winddir=10:SW wS=0.0, wG=0.0, rain=690.6
2020.04.01 20:46:35 4: sduino: SD_WS09_Parse_19 WH1080 id:134 :10101000011000011101011100110011000000000000000000001000111111101000101011101100 
2020.04.01 20:46:35 4: SD_WS09_Parse_20: WH1080 (FFA861D733000008FE8AEC)
2020.04.01 20:46:35 4: SD_WS09_Parse_rain_offset WH1080 rain:690.6 raintotal:690.6 rainoffset:0 
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse0 msg=FEA1875CCC000023FA2BB0 Bin=1111111010100001100001110101110011001100000000000000000000100011111110100010101110110000 syncp=0 length:88
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse CRC_AUS:0 
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_SHIFT_1 NOK raw:FEA1875CCC000023FA2BB0 crc:253 -> shift
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_SHIFT_3 NOK raw:FF50C3AE66000011FD15D8 crc:230 -> shift
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_SHIFT_4 OK raw:FFA861D733000008FE8AEC msg:P9#FFA861D733000008FE8AEC crc:0
2020.04.01 20:47:23 5: sduino: SD_WS09_Parse_0 whid=1010
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_1 msg=10101000011000011101011100110011000000000000000000001000111111101000101011101100 length:80
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_2 WH1080 id:134, Windspeed bit: 00000000 Dec: 0.0
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_3 WH1080 id:134, Windguest bit: 00000000 Dec: 0.0
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_4 WH1080 id:134, Rain bit: 100011111110 Dec: 690.6
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_5 WH1080 id:134, bat:low, temp=7.1, hum=51, winddir=10:SW wS=0.0, wG=0.0, rain=690.6
2020.04.01 20:47:23 4: sduino: SD_WS09_Parse_19 WH1080 id:134 :10101000011000011101011100110011000000000000000000001000111111101000101011101100 
2020.04.01 20:47:23 4: SD_WS09_Parse_20: WH1080 (FFA861D733000008FE8AEC)
2020.04.01 20:47:23 4: SD_WS09_Parse_rain_offset WH1080 rain:690.6 raintotal:690.6 rainoffset:0 
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse0 msg=FF50C3AC66000011FD140A Bin=1111111101010000110000111010110001100110000000000000000000010001111111010001010000001010 syncp=1 length:88
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse CRC_AUS:0 
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_SHIFT_1 NOK raw:FF50C3AC66000011FD140A crc:230 -> shift
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_SHIFT_2 OK raw:FFA861D633000008FE8A05 msg:P9#FFA861D633000008FE8A05 crc:0
2020.04.01 20:48:59 5: sduino: SD_WS09_Parse_0 whid=1010
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_1 msg=10101000011000011101011000110011000000000000000000001000111111101000101000000101 length:80
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_2 WH1080 id:134, Windspeed bit: 00000000 Dec: 0.0
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_3 WH1080 id:134, Windguest bit: 00000000 Dec: 0.0
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_4 WH1080 id:134, Rain bit: 100011111110 Dec: 690.6
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_5 WH1080 id:134, bat:low, temp=7, hum=51, winddir=10:SW wS=0.0, wG=0.0, rain=690.6
2020.04.01 20:48:59 4: sduino: SD_WS09_Parse_19 WH1080 id:134 :10101000011000011101011000110011000000000000000000001000111111101000101000000101 
2020.04.01 20:48:59 4: SD_WS09_Parse_20: WH1080 (FFA861D633000008FE8A05)
2020.04.01 20:48:59 4: SD_WS09_Parse_rain_offset WH1080 rain:690.6 raintotal:690.6 rainoffset:0 

Die letzte Windrichtung ist Nord Nord West und die Batterie ist voll.

**Comment by johol** [comment]
Das mit den 10 bit Temperatur Werten war einfach schlecht geraten ;-)

**Comment by elektron-bbs** [comment]
Du kannst jetzt eigentlich nur mal Daten sammeln. Ich habe eine Excel-Liste erstellt. Eventuell passt ja die Auswertung des Batterie-Status (N18) und der Windrichtung (N19) nicht zur WH1080. Alle anderen Werte scheinen ja zu passen.
In die Liste müsstest du die Nachrichten übernehmen, die nach erfolgreicher CRC-Prüfung ausgegeben werden, wie z.B.:

`SD_WS09_Parse_SHIFT_2 OK raw:FFA861D733000008FE8AEC msg:P9#FFA861D733000008FE8AEC crc:0
`

[SD_WS09.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/4417180/SD_WS09.xlsx)

**Comment by HomeAutoUser** [comment]
Hallo @elektron-bbs & @johol,
ich bin durch Zufall gerade hierauf https://github.com/merbanan/rtl_433/commit/9a20cb11b61e9889255db1f28b1d9c1ec90f0c0c gestoßen. Da ist auch die Rede von 10 bit bei der WHx080.

**Comment by elektron-bbs** [comment]
Ob 10 oder 12 Bit für die Temperatur verwendet werden, dürfte egal sein. 10 Bit reichen für eine Temperatur bis maximal 62,3 °C. Ich glaube kaum, das die oberen 2 Bit noch für etwas anderes verwendet werden. Aber das kann nur @johol herausfinden.

**Comment by johol** [comment]
[SD_WS09-WH5300.xlsx](https://github.com/RFD-FHEM/RFFHEM/files/4431649/SD_WS09-WH5300.xlsx)
Hier das sheet mit den raw Daten des WH5300 Sensor. Ich rate mal wieder. Die Temperatur Daten sind nur 8 bit lan wobei das high bit für plus oder minus steht. Die anderen 4 bits sind dann Batterie und Windrichtung.

**Comment by elektron-bbs** [comment]
Du sollst aber nicht raten :-)
Trag einfach die von der Wetterstation abgelesenen Werte zu den Daten von FHEM in die Liste ein. Ich habe dafür eine Spalte "Userinfo" vorgesehen.

Laut Dokumentation https://www.froggit.de/media/products/WH5300SE%20Bedienungsanleitung%20(conform).pdf hat der Aussensensor folgende Daten:

Temperatur Messbereich: -40˚C - 65˚C
Genauigkeit: + / - 1 °C
Auflösung:  0.1˚C  

Für diese Auflösung benötigen wir also 1050 verschiedene Werte. Mit 8 Bit lassen sich aber nur 256 darstellen. Der Messbereich bis -40 °C passt eigentlich auch sehr gut zur Berechnung im Code.

**Comment by mibenten** [comment]
Guten Tag die Damen, 
ich habe ebenfalls eine WH5300SE und versucht die Daten mit rtl_433 auszulesen, leider bislang ohne Erfolg. Der Decoder für die FO1080 passt wohl allein von der Telegrammlänge nicht.Dort sind Telegramme von 63,64,87,88 Bytes beschrieben, die aber bei mir nicht vorkommen. Ich habe bislang nur 68 Byte Telegramme, bin mir aber auch nicht mit den Decoder Parametern sicher. Gibt es bei Euch inzwischen eine Erkenntnis wie man korrekte Ergebnisse erzielt?

**Comment by igraf767** [comment]
I have a proove of concept for WH5300SE Sender Data Signal on Testpad T2:

  Idle: 0V
  Square Signals:
  dVin 2.96V
  dVout 3.2V
  3.3V CMOS logic levels ok

Problem: Signal suppressed when connecting Weatherman.
--> Solution adding a logic ic (74HC365 Buffer/LineDriver)

Problem: at Transmission Start: fast noise / digital signal for about 14.3ms
--> Solution: mostly suppressed by adding a RC low pass 19kOhm and 10nF before logic ic

HW Schematic::

  WH5300SE_T2_Data --> R19kOhm
  R19kOHM --> C10nF+
  C10nF+ --> 74HC365_1A_pin2
  74HC365_1Y_pin3 --> Weatherman_Data
  
  Weatherman_GND --> C10nF-
  Weatherman_GND --> WH5300SE_GND
  Weatherman_GND --> 74HC365_NOE1_pin1
  Weatherman_GND --> 74HC365_NOE2_pin15
  Weatherman_GND --> 74HC365_GND_pin8
  Weatherman_3V --> WH5300SE_3V
  Weatherman_3V --> 74HC365_VCC_pin16

Observed Pulse Pause Coding:
1Bit true 1.47mS sum, 0.47mS high, 1ms low (4Bit true : 5.88mS)
1Bit false 2.43mS sum, 1.43mS high, 1ms low (4Bit false : 9.73mS)
MSB first

Data Start on high > 0.2ms and < 1.8ms follwed by low > 0.7ms and < 1.3ms
Data Cancel  on high < 0.2ms or > 1.8ms or low < 0.7ms or > 1.3ms
Data End on low after 88 high
Data Valid if
  valid preamble 0xFF
  and type 0xA
  and valid CRC

Example:
FF    8  Bit    Preamble (0xFF)
A     4  Bit    type   (0xA = Weather message)
3F    8  Bit    id
282  12  Bit    temp   (*0.1 - 40 °C)
38    8  Bit    hum    (%)
00    8  Bit    wSpeed (/3.6 m/s)
00    8  Bit    wGust  (/3.6 m/s)
00    4  Bit    unk
00   12  Bit    rAcum  (/300 * 25.4 mm)
00    4  Bit    status (1Bat, 3Chan?)
06    4  Bit    wdir   (*22.5 °)
                (index to {"N";"NNE";"NE";"ENE";"E";"ESE";"SE";"SSE";"S";"SSW";"SW";"WSW";"W";"WNW";"NW";"NNW"})
DE    8  Bit    CRC

References (incl. CRC calc)
https://github.com/bhaap/WH5300-weatherstation-ESP8266-MQTT-json/blob/master/WH5300-weatherstation-ESP8266-MQTT-json.ino

http://www.sunshine2k.de/coding/javascript/crc/crc_js.html
CRC-8, Input not reflected, Result not reflected, Poly 0x31, Init 0, Final Xor 0
Without Preamble, starting with typ till wdir, without CRC
Example CRC Input Data Bytes:  A3F282380000000006
ResultsCRC value 0xDE

[ArduinoCOMLog_sketch_jun20a_wh5300se_ino.txt](https://github.com/RFD-FHEM/RFFHEM/files/4808654/ArduinoCOMLog_sketch_jun20a_wh5300se_ino.txt)

[ArduinoCOMLog_HWFilterBuffer_withoutStart.txt](https://github.com/RFD-FHEM/RFFHEM/files/4808660/ArduinoCOMLog_HWFilterBuffer_withoutStart.txt)

Thanks for the Hints found here.

**Comment by elektron-bbs** [comment]
Danke für die Bestätigung.
Das passt dann also bis auf die 4 Bit status (1Bat, 3Chan?) genau zum Model "WH1080" im Modul 14_SD_WS09.pm.
Ich denke, wir können das Issue schließen.
