### ISSUE TITLE
xFSK - extension module

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#814]
Nach Absprache und Klärung nach Vorgehensweise mit @sidey79 nun hier das Issues.
Issues https://github.com/RFD-FHEM/RFFHEM/issues/726 wird dadurch geschlossen. @Ralf9 steht uns für Rückfragen zur Verfügung. Die Firmware wird separat in dem dazugehörigen Issues behandelt. (Link https://github.com/RFD-FHEM/SIGNALDuino/issues/124)

Alle dazu notwendigen 
a) Modulanpassungen werden im Branch 
https://github.com/RFD-FHEM/RFFHEM/tree/dev-r35_xFSK
b) Firmwareanpassungen werden im Branch 
https://github.com/RFD-FHEM/SIGNALDuino/tree/dev-r3.5_plattformIO_xFSK
integriert.

##  Specifications for xFSK sensor / switch / or other device ... 

- For receiving and evaluating xFSK signals
- Develops Ralf - startetd with Ralf9@6fd89e1

#############################################################################

Anpassung im weiteren Schritt - bisher offen:
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR67
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR69-R70 (ccmode Auswahl wird benötigt)
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR74
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR703-R709
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR880
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR890-R893
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1085-R1089
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1421-R1423
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1605-R1607
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1642

vermute "individuell"
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1092
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1136-R1140
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR1144-R1168

Anpassung übernommen:
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR86
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR156-R157
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR191-R193
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR254
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR406-R412
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR958
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR2852-R2897
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR2948-R2951
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3326
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3423-R3427
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3448
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR3460
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4556-R4670
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4872
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4933-R4936
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR4994-R5004

Anpassung nicht notwendig:
https://github.com/Ralf9/RFFHEM/commit/6fd89e12c3ab00302ae8f2cc1324496db5f522f6#diff-ffd75143a13a45dd2a5a1184d993cbfdR120-R123

!! Das SIGNALduino_TOOL wurde auf den neuen zusätzlichen Nachrichtentyp erweitert !!

1) Wir werden im ersten Schritt das Modul anpassen und somit kann man die neuen Protokolle ebenso dispatchen.
2) Danach werden wir die Firmware anpassen und die noch benötigten Anpassungen im Modul bei Benötigung anpassen.

Dieser Faden dient zur direkten Kommunikation / Austauch und Hinterfragung zu dieser Erweiterung.

**Comment by HomeAutoUser** [comment]
Das war nötig um die Tests zu verifizieren https://github.com/RFD-FHEM/RFFHEM/commit/145c823f187ed899e71736666baf28f22b331aa6

**Comment by HomeAutoUser** [comment]
@sidey79, ich habe mir mal soeben in der Sonne einiges überlegt.
Wir sollten vielleicht sofort von Beginn an, die Dinge richtig implementieren.
Wie denkst du darüber?

1) Der Setbefehl (für Lacrosse Sensoren) https://github.com/RFD-FHEM/RFFHEM/commit/056cd80c2651d96e81eb58b1cc691d1b6ff05de1#diff-ffd75143a13a45dd2a5a1184d993cbfdR131-R132 wäre nur notwendig wenn
a) der cc1101 erkannt wurde
b) im Reading cc1101_config_ext die Modulation 2-FSK gesetzt ist

Kannst du bitte die 

https://github.com/RFD-FHEM/RFFHEM/blob/145c823f187ed899e71736666baf28f22b331aa6/FHEM/00_SIGNALduino.pm#L651-L666

anpassen. Mir gelingt die Abfrage nicht :-(

2) auf 1. basierend müssen wir den Test `test_sub_SIGNALduino_Set-definition.txt` anpassen und dann bei 
a) `Test SIGNALduino without dummy attrib` keinen ...like LaCrossePairForSec zulassen weil dort das Internal {cc1101_available} gelöscht ist `delete($targetHash->{cc1101_available})`

**Comment by sidey79** [comment]
Gleich richtig machen klingt gut :)
Ob das für uns beide aber das gleiche bedeutet? Hmm

Ich würde ja erst den Test achreiben und danach erst die Abfrage anpassen.

Wieso muss eigentlich das IODev gepairt werden? Muss das nicht eher mit einem logischen Gerät erfolgen?

**Comment by Ralf9** [comment]
hier ist das commandref 
```
    <li>LaCrossePairForSec &lt;sec&gt; [ignore_battery]<br>
       enable autocreate of new LaCrosse sensors for &lt;sec&gt; seconds. If ignore_battery is not given only sensors
       sending the 'new battery' flag will be created.
    </li><br>
```

**Comment by HomeAutoUser** [comment]
>Ob das für uns beide aber das gleiche bedeutet? Hmm

Wir werden uns schon einig :-)

>Ich würde ja erst den Test achreiben und danach erst die Abfrage anpassen.

@sidey79, du kannst auch erst den Test schreiben und dann die Abfrage. Das Ergebnis muss stimmen zum Schluss.

@Ralf9 danke für den Hinweis mit der Commandref. Wir müssen den Set Befehl auch noch ergänzen.

**Comment by HomeAutoUser** [comment]
@Ralf9, kann es sein, das 
`return "Usage: set $name LaCrossePairForSec <seconds_active> [ignore_battery]" if(!$arg || $a[0] !~ m/^\d+$/ || ($a[1] && $a[1] ne "ignore_battery") );`
angepasst werden muss?

https://github.com/Ralf9/RFFHEM/blob/06c8f176c53dbe05e9431bf94564ca7ce188c3d9/FHEM/00_SIGNALduino.pm#L760

`$a[0] !~ m/^\d+$/` ist doch jeweils nicht dezimal oder habe ich einen Denkfehler?

**Comment by sidey79** [comment]
Wieso regelt das nicht einfach das normale autocreate?

**Comment by HomeAutoUser** [comment]
>Wieso regelt das nicht einfach das normale autocreate?

Weil das Module 36_LaCrosse dies nicht vorsieht.
Parse:

```
    Log3 $name, $loglevel, "LaCrosse: Unknown device $rname, please define it";
    Log3 $name, $loglevel, "LaCrosse: check commandref on usage of LaCrossePairForSec" if( !$hash->{LaCrossePair} && !defined($modules{LaCrosse}{defptr}) );

    return "" if( !$hash->{LaCrossePair} );

    return "UNDEFINED LaCrosse_$rname LaCrosse $raddr" if( $battery_new || $hash->{LaCrossePair} == 2 );
    return "";
```

**Comment by sidey79** [comment]
Puuh, hat schon jemand HCS gefragt ob er es nicht an den Standard anpassen möchte?

**Comment by Ralf9** [comment]
Dies ist der Standard von LaCrosse, dies ist recht praktisch und macht den Batteriewechsel recht komfortabel.
Ein neuer LaCrosse Sensor z.B. von einem Nachbarn wird nicht automatisch angelegt.
Mit "set replaceBatteryForSec" beim Sensor Device ist ein Batteriewechsel komfortabel.
```
replaceBatteryForSec <sec> [ignore_battery]
sets the device for <sec> seconds into replace battery mode. the first unknown address that is received will replace the current device address. this can be partly automated with a readings group configured to show the battery state of all LaCrosse devices and a link/command to set replaceBatteryForSec on klick. 
```

**Comment by Ralf9** [comment]
> $a[0] !~ m/^\d+$/ ist doch jeweils nicht dezimal oder habe ich einen Denkfehler?

Sekunden müssen eine Zahl sein und das wird hier geprüft

**Comment by sidey79** [comment]
Ich meine den FHEM Standard, dass das Anlegen neuer Definitionen über die autocreate Definition gesteuert wird.

Ich wusste aktuell nicht, wieso ein replaceBattery Kommando nicht auch mit Autocreate funktionieren soll.

Ich vermute mal, die Antwort auf meine Frage lautet somit eher nein.

**Comment by sidey79** [comment]
@HomeAutoUser 
Wenn ich mir den Code von 36_LaCrosse richtig interpretiert habe, dann verwendet das Modul die Autocreate Funktion, sobald hash->{LaCrossePair} irgend einen Wert aufweist.

Es wäre möglich "hash->{LaCrossePair" im SIGNALduino auf 1 zu setzen. Dann sollte autocreate steuern ob eine Defintion angelegt wird oder eben nicht.

**Comment by HomeAutoUser** [comment]
> Es wäre möglich "hash->{LaCrossePair" im SIGNALduino auf 1 zu setzen. Dann sollte autocreate steuern ob eine Defintion angelegt wird oder eben nicht.

Das kann man testen, indem wir eine Nachricht dispatchen nach der Anpassung. So teste ich ja auch soeben die Integration.

**Comment by sidey79** [comment]
Ich hoffe wir haben zunächst mal alles notwendige Implementiert.

Den Punkt mit der replaceBattery Funktion müsste man noch mal etwas globaler angehen, aber das hat auch erst einmal nichts generell mit FSK zu tun.

**Comment by HomeAutoUser** [comment]
@sidey79 bitte schau schon mal einen Blick darüber ob dir hier etwas nicht "gefällt" oder ob du damit einverstanden wärest.
https://github.com/HomeAutoUser/RFFHEM/commit/c6e60810a72ffda434d8172abd3107b4ae214a13

Den Hash `my %modes` würde ich alternativ noch an den Anfang der SIGNaLduino Datei verschieben.

Das wäre die Realisierung um aus FHEM eine Umschaltung vorzunehmen. Das Attribut wurde namensgleich wie beim CUL gewählt und auch die Bezeichnungen sind identisch.

**Comment by sidey79** [comment]
Was genau wird dort umgestellt?
Wenn Code vom CUL dupliziert wurde, deutet es daraufhin, dass der Teil in ein eigenes Package gehört, damit er nicht dupliziert werden muss.


Da es den Namen nach Hersteller spezifische Konfigurationen sind, passt es meiner Meinung nach nicht in 00_Signalduino.

**Comment by HomeAutoUser** [comment]
Was wird umgestellt? Es sind die Register im cc1101 welcher angeschlossen ist. Es werden nur die Register gesetzt welche aus den bisherigen Erkenntnissen unterschiedlich sind.

Der Code wurde nicht dupliziert. Es werden unsere Routinen genommen um die Register zu setzen.

Wo möchtest du solche Werte speichern, welche nur Herstellerspezifisch den cc1101 konfigurieren? Vorschläge??

**Comment by sidey79** [comment]
Ich bin da nicht so drinnen wie Du, es sieht augenscheinlich so aus, als ob es Sensor oder Produkt spezifische Register sind.

Wenn es um cc1101 Funktionen geht, wäre vielleicht ein cc1101 Package passend, aber es scheint basierend auf den Namen z.B. Kopp oder PCA301 eher nicht um cc1101 Funktionen zu gehen, sondern um Register für ein bestimmtes Produkt.

Ist denn der Array 1:1 identisch zum CUL?
Andere Register, die wir Protokollspezifisch setzen, haben wir in SD_ProtocolData hinterlegt.
Vielleicht passt es ja zum jeweiligen Protokolleintrag?

**Comment by elektron-bbs** [comment]
Es wurden nur 3 Bezeichnungen vom CUL übernommen, wie z.B:
Attribut: rfmode
Value: SlowRF oder KOPP_FC

**Comment by HomeAutoUser** [comment]
Ja, es sind nur cc1101 Register, welche angepasst werden um auf den Hersteller zu reagieren.

Array identisch zum CUL?
Wir schreiben NUR die Werte, welche sich unterscheiden. —> demzufolge ist es nur ein Bruchteil vom kompletten Register. Grund war dafür, ich muss nicht werte schreiben, welche gleich bleiben.

> Andere Register, die wir Protokollspezifisch setzen, haben wir in SD_ProtocolData hinterlegt.

In der Datei haben wir keine Registerwerte hinterlegt. Dort sind Informationen und die Bereiche Modulation / Sync unsw. Müssten dann auseinander genommen werden und die passende Adresse gesucht werden. Da ist der Code unnötig vielfältig aufgebläht.

Ein Kompromiss wäre, in der Datei kann man die Register hinterlegen. (Das Hash mit den arrays, welches in der 00_Signalduino.pm ist)

**Comment by HomeAutoUser** [comment]
>Wenn es um cc1101 Funktionen geht, wäre vielleicht ein cc1101 Package passend, aber es scheint basierend auf den Namen z.B. Kopp oder PCA301 eher nicht um cc1101 Funktionen zu gehen, sondern um Register für ein bestimmtes Produkt.

Manchmal kommen Nachts die Ideen.

https://github.com/HomeAutoUser/RFFHEM/blob/dev-r35_xFSK_TEST/FHEM/00_SIGNALduino.pm#L2925-L2943
https://github.com/HomeAutoUser/RFFHEM/blob/dev-r35_xFSK_TEST/FHEM/00_SIGNALduino.pm#L3850-L3867

>Vielleicht passt es ja zum jeweiligen Protokolleintrag?

Da müssten alle Werte Bsp: https://github.com/HomeAutoUser/RFFHEM/blob/dev-r35_xFSK_TEST/FHEM/00_SIGNALduino.pm#L3863 unter der Protkolldefinition hinterlegt werden. Wenn wir die Werte wie Datenrate Bsp. https://github.com/HomeAutoUser/RFFHEM/blob/dev-r35_xFSK_TEST/FHEM/lib/SD_ProtocolData.pm#L2701 erst umrechnen müssen dann ist das Unnötig viel Code. Somit haben wir das Register und schieben es hinein und fertig.

Vorteil auch daran, wenn die Protokolldatei vom Benutzer nicht lesbar oder vorhanden ist, so läuft das Modul und er kann auch das Attribut nutzen | verstellen... Eine noch weitere Auslagerung würde noch mehr Pflegearbeit herbeiführen. Somit sind packages vom cc1101 und die Herstellerspezifischen Registereinstellungen untereinader in der SIGNALduino.pm Datei.

**Comment by HomeAutoUser** [comment]
Zwischenstand.

Mit diesem https://github.com/RFD-FHEM/RFFHEM/pull/866 PR ist der Branch in voller Modulfunktionalität fertig.
-->Modul mit xFSK support -->Branch "dev-r35_xFSK"

Dieser Schritt https://github.com/RFD-FHEM/RFFHEM/pull/862 ist noch offen und erfolgt nach Entscheidung.

**Comment by HomeAutoUser** [comment]
Die softwäremäßige Einbindung ist somit im Modul abgeschlossen. Die Firmwareanpassung folgt nun als PR.
