### ISSUE TITLE
Attribut IODev bei Sensoren

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#815]
## Actual Behavior
Zitat aus https://forum.fhem.de/index.php/topic,109822.0.html:
Bei allen meinen SD_WS Typ 33 Devices werden bei aktivem Autocreate immer wieder die beiden Attribute:
event-min-interval und event-on-change-reading mit den Defaultwerten überschrieben.

## Steps to Reproduce the Problem

  1. set Attribute IODev
  2. wait
  3. Show Log - autocreate ohne Ende

## Specifications

  - Microcontroller: egal
  - Version (Firmware): egal

  - Versionmodul (FHEM Module): v3.4.2_dev_30.03

**Comment by elektron-bbs** [comment]
Eigentlich brauchen wir ein Attribut IODev bei Sensoren ja nicht, da es nur beim Senden benötigt wird.

Das Problem habe ich mittlerweile auch bei Hideki nachvollziehen können. Bei gesetztem Attribut "IODev" passiert folgendes:

```
2020.04.04 13:33:47 2: autocreate: define FileLog_Hideki_31_1 FileLog ./log/Hideki_31_1-%Y-%m.log Hideki_31_1
2020.04.04 13:33:47 2: autocreate: define SVG_Hideki_31_1 SVG FileLog_Hideki_31_1:temp4hum4:CURRENT
2020.04.04 13:34:30 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC46B503BFA30B03
2020.04.04 13:35:04 3: sduinoUSB0: FS10_Parse P61#02D284210A60 - ERROR message too short or too long (42 bit) 
2020.04.04 13:35:56 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC463503BF237307
2020.04.04 13:35:56 2: autocreate: define FileLog_Hideki_31_1 FileLog ./log/Hideki_31_1-%Y-%m.log Hideki_31_1
2020.04.04 13:35:56 2: autocreate: define SVG_Hideki_31_1 SVG FileLog_Hideki_31_1:temp4hum4:CURRENT
2020.04.04 13:35:56 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC46B503BFA30B07
2020.04.04 13:37:22 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC467503BF6337
2020.04.04 13:37:22 2: autocreate: define FileLog_Hideki_31_1 FileLog ./log/Hideki_31_1-%Y-%m.log Hideki_31_1
2020.04.04 13:37:22 2: autocreate: define SVG_Hideki_31_1 SVG FileLog_Hideki_31_1:temp4hum4:CURRENT
2020.04.04 13:38:05 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC463502BF2232
2020.04.04 13:38:05 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC467502BF627607
2020.04.04 13:38:05 2: autocreate: define FileLog_Hideki_31_1 FileLog ./log/Hideki_31_1-%Y-%m.log Hideki_31_1
2020.04.04 13:38:05 2: autocreate: define SVG_Hideki_31_1 SVG FileLog_Hideki_31_1:temp4hum4:CURRENT
2020.04.04 13:38:05 1: sduinoACM Hideki: UNDEFINED sensor Hideki_31_1 detected, code P12#75EC46B502BFA24A07
```

Das Problem besteht wahrscheinlich in fast allen Modulen von uns:

![IODev](https://user-images.githubusercontent.com/26026988/78450256-b05b8980-767d-11ea-9d86-23c81072c811.png)

Ich schätze, da wurde anfangs einfach bei allen der Code aus der 14_SD_WS.pm übernommen:

```
sub SD_WS09_Attr(@) {
	my @a = @_;
	# Make possible to use the same code for different logical devices when they
	# are received through different physical devices.
	return  if($a[0] ne "set" || $a[2] ne "IODev");
	my $hash = $defs{$a[1]};
	my $iohash = $defs{$a[3]};
	my $cde = $hash->{CODE};
	delete($modules{SD_WS09}{defptr}{$cde});
	$modules{SD_WS09}{defptr}{$iohash->{NAME} . "." . $cde} = $hash;
	return undef;
}
```

Das war bei diesen Sensoren ein "Hack" um Sensoren mit gleicher Adresse, aber verschiedenen Empfangsfrequenzen unterscheiden zu können.

Ich habe bei mir diese Sub komplett und auch das Attribut IODev aus der Liste entfernt.

**Comment by sidey79** [comment]
Gut analysiert. Hatte schon so etwas vermutet.

Hast Du ein Beispiel, welcher Sensortyp die gleiche Definition auf verschiedenen Frequenzen benötigt?

So als Idee:
Könnte man in den defptr nicht anstelle des iodevs auch einfach die Frequenz einbauen, sofern wir die herausbekommen / unterscheiden können.

**Comment by elektron-bbs** [comment]
Mir fällt eigentlich kein Sensortyp ein. Das was ich bisher so verarbeitet habe, lässt sich durch die long-ID unterscheiden.
Mir war das schon vor Jahren bei meinen alten WS2000-Sensoren aufgefallen und hatte mir die 14_CUL_WS.pm angepasst. Das es auch andere Module betrifft, war mir nicht bewusst.

Die Empfangsfrequenz wissen wir im Modul nicht. Dazu müssten wir erst mittels LASTInputDev die Frequenz vom Empfänger holen. Das ginge dann aber auch nur beim CC1101.

**Comment by sidey79** [comment]
Ich denke wir sollten das überall ausbauen.

**Comment by elektron-bbs** [comment]
Machst du, oder soll ich?
dev-r34 oder dev-r35?

**Comment by sidey79** [comment]
Könnten wir einersetz für das SD_WS Modul noch in 3.4 einbringen denke ich.

Dadurch ähndert sich der defptr, wenn ein IODev hinterlegt ist.
Führt das zu einem Problem?
Vermutlich nicht, weil der defptr beim starten von FHEM neu gesetzt wird und der alte keine Rolle mehr spielt (hoffentlich).

Andererseits gibt es aber vielleicht doch noch unbekannte Gründe das IODev mit zu verarbeiten?

Die 3.4.2 müssen wir meiner Einschätzung nach nicht aufhalten.
Papalöwe könnte einen Dev Branch testen und uns Rückmeldung zu unserer Anpassung geben
Eine 3.4.3 wäre dann Recht schnell denkbar, es handelt sich ja ohnehin ausschließlich um eine Anpassung im SD_WS Modul im allerersten Schritt

**Comment by elektron-bbs** [comment]
Ich habe das bisher nur getestet mit dem SD_WS- und dem Hideki-Modul und keine Probleme feststellen können.

**Comment by sidey79** [comment]
@elektron-bbs 

Ich denke ich weiss wieso das IODev Attribut zur Verfügung steht, bzw. für welches Szenario das gedacht ist.
Mir ist es aufgefallen, als ich den Text sehr genau gelesen habe
"Make possible to use the same code for different logical devices when they are received through different physical devices"

Bedeutet:
 a) unterschiedliche Sensoren
 b) von unterschiedlichen phyischen Empfängern

Also z.B. man hat zwei Sensoren und diese bieten keine ZufallsID und auch keinen Kanal. 
Wenn man jeden der Sensoren dann nur mit einem einigen Gerät empfängt, dafür ist das Attribut gedacht.

**Comment by elektron-bbs** [comment]
Genau so ist es. In der commandref steht dazu:

```
CUL_WS
Attribute
    IODev (!) Achtung: mit diesem Attribut ist es möglich mehrere 8-er Sets an S300-er in FHEM zu definieren.
		Wichtige Voraussetzung allerdings ist, dass nur das spezifizierte CUL das S300 empfangen kann,
		z.Bsp. durch Frequenztrennung (433MHz vs. 868MHz). 	
```

Ich habe mir jetzt sämtliche Module, in der meine Suche die Textpassage gefunden hatte, vorgenommen.

Bei diesen 4 Modulen
1. 14_SD_WS.pm
2. 14_Hideki.pm
3. 14_SD_WS07.pm
4. 14_SD_WS_Maverick.pm

konnte ich den Bug mittels vorhandener Testnachrichten nachvollziehen und habe ihn im Branch dev-r34_IODev korrigiert.

Für das Modul 14_SD_AS.pm liegen keine Testnachrichten vor und außerdem ist das ein Eigenbau, wo sicher auch verschiedene Frequenzen verwendet werden könnten.

Für das Modul 14_SD_RSL.pm liegen keine Testnachrichten vor.

Beim Modul 14_SD_WS09.pm kommt der Fehler nicht zum Tragen, weil der Sensor als "WH1080" oder "CTW600" definiert wird, aber für autocreate "SD_WS09.*" eingetragen ist.
`$hash->{AutoCreate} =	{ "SD_WS09.*" => { ATTR => "event-min-interval:.*:300 event-on-change-reading:.* windKorrektur:.*:0 verbose:5" , FILTER => "%NAME", GPLOT => "WH1080wind4:windSpeed/windGust,",  autocreateThreshold => "2:180"} };
`
Das GPLOT existiert übrigens nicht.

Das Modul 14_BresserTemeo.pm kann entfernt werden, da die Protokolle 44 und 44.1 jetzt im Modul  14_SD_WS.pm verarbeitet werden.

**Comment by sidey79** [comment]
14_SD_AS.pm verwende ich selbst auch nicht mehr, aber auch da wird die Unterscheidung via IODev nicht beötigt, da genügend Kanäle vorhanden sind.

**Comment by elektron-bbs** [comment]
14_SD_AS.pm habe ich jetzt auch geändert.

**Comment by HomeAutoUser** [comment]
Das sollte erledigt sein mit https://github.com/RFD-FHEM/RFFHEM/commit/3c0a754d9a65bba24d836732b222751d10197b4c.

Es wird ebenso im Master mit https://github.com/RFD-FHEM/RFFHEM/pull/825 korrigiert.
