### ISSUE TITLE
10_SD_GT.pm:

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#816]
@homeautouser

Hier muss noch der / die Maintainer hinterlegt werden und dann upload im SVN

**Comment by HomeAutoUser** [comment]
@elektron-bbs das ist dein Part :-)

**Comment by elektron-bbs** [comment]
Da gibt es zwei Möglichkeiten:

1. wie bei FS 10 - FHEM/10_FS10.pm              sidey/elektron-bbs   SlowRF
2. nicht ins SVN

**Comment by sidey79** [comment]
Ja können wir so machen wie bei FS10 :)

**Comment by sidey79** [comment]
@elektron-bbs 

In welchem Forum soll der Support erfolgen ?

**Comment by sidey79** [comment]
Ankündigung erstellt: https://forum.fhem.de/index.php?topic=112796.new#new

Ich werde es jetzt hochladen

**Comment by elektron-bbs** [comment]
OK

**Comment by sidey79** [comment]
https://forum.fhem.de/index.php/topic,112797.0.html
