### ISSUE TITLE
Parameterübergabe SIGNALduino_Parse_MN

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#818]
Die Parameterübergabe SIGNALduino_Parse_MN basiert auf den gleichen "Fehlern" wie die anderen Parse Routinen.

Es ist aber nicht nötig, einen Parameter mehrfach zu übergeben.
Das könnten wir zumindest bei der neuen Funktion direkt vermeiden 2x den $hash vom io zu übergeben :)

**Comment by sidey79** [comment]
```
sub SIGNALduino_Parse_MN($$$$@) {
	my ($hash, $iohash, $name, $rmsg,%msg_parts) = @_;
```

Wird aufgerufen durch:
`$dispatched=  SIGNALduino_Parse_MN($hash, $iohash, $name, $rmsg,%signal_parts);`


Aber hier übergeben wir 2x $hash, also den identischen Parameter :)
`return SIGNALduino_Parse($hash, $hash, $hash->{NAME}, $a[1]);`

**Comment by HomeAutoUser** [comment]
Wir können das gern anpassen um nicht 2x das gleiche zu übergeben.
Das ist mit Sicherheit durch C&P entstanden.

ABER, wenn wir es dort korrigieren, haben wir eine korrigierte Stelle und 2 weitere Stellen wo es "falsch" ist. Für mich würden nur 2 Varianten in Betracht kommen
- entweder an allen Stellen richtig stellen
- einheitlich "unnötig doppelt" belassen

**Comment by sidey79** [comment]
Es ist durch C&P entstanden. Meiner Meinung nach, muss man den C&P Fehler ja bei einer neuen sub nicht wiederholen.

Das Anpassen der restlichen Parameter sollten wir mal separat angehen. Da könnte man generell mal etwas "aufräumen" aber das hat wieder ein wir verzetteln uns Potential :)
