### ISSUE TITLE
Wiederspruch Wiki - Funktionsweise (Modul im Master SVN + DEV)

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#820]
## Expected Behavior
Quelle : https://wiki.fhem.de/wiki/SIGNALduino

**Fehlerbehandlung**
1) Der SIGNALduino kann mit folgendem Befehl auf Werkseinstellungen zurückgesetzt werden:
`get raw e`

als Antwort kommt dann "ccFactoryReset done". Ob ein solcher Reset nötig ist, erkennt man an der Antwort auf den Befehl "get config", auf den dann die Meldung "config: MS=1;MU=1;MC=1" folgen sollte.

- gefixt via https://github.com/RFD-FHEM/RFFHEM/commit/6216164da4639bf272fa41e19e8f0b66cf1e0655

2) In der Firmware sind die folgenden Befehle eingebaut
`get raw C<reg>`

<reg> is a (two digit) hex number: return the value of the cc1101 register. <reg>=99 dumps the first 48 registers. Example: C35 -> C35 = 0D 

- Klärung offen !
3) Die Sendeleistung lässt sich mit
`get sduino ccreg 3E`

prüfen, wobei die Rückmeldung wie folgt zu lesen ist: 

- Klärung offen !

## Actual Behavior
- keine Reaktion

## Steps to Reproduce the Problem

- Befehle ausführen laut Wiki

## Specifications

  - Version (Modul): v3.4.2_dev_30.03

**Comment by sidey79** [comment]
Die Commandref passt dann aber wohl auch nicht

![image](https://user-images.githubusercontent.com/7968127/78987165-84cd1900-7b2d-11ea-964c-adb64881d471.png)

**Comment by HomeAutoUser** [comment]
@sidey79, bitte AUFPASSEN

>Die Commandref passt dann aber wohl auch nicht

Die Commandref zeigt dir den SET Auszug an weil dieser als erstes kommt.
Das ist das alte CommanrefProblem wenn 2 Befehle den selben Namen aufweisen.

**Comment by sidey79** [comment]
Ja, das lässt sich lösen, wenn wir den Get Befehl raw umbenennen in get "test" oder irgendwas brauchbares.

Wiki ist aktualisiert. Das akute Problem sollte mit dem PR behoben sein.

**Comment by HomeAutoUser** [comment]
Ich verstehe deine Denkweise ...
dann ABER sollten wir das WiKI umgehend anpassen und die Änderung nach Vollendung ins Master schieben.

> get "test"

da muss ein anderer Name her.

**Comment by elektron-bbs** [comment]
Wie wäre es mit "testMSG" oder "dispatchMSG"?

**Comment by sidey79** [comment]
Lässt und erst Mal raw belassen und in v 3.5 können wir ja auch den Namen ändern :)

**Comment by HomeAutoUser** [comment]
Wir winken den PR durch und eröffnen einen vor 3.5.1 mit dem Namen dispatchRAWMSG oder dispatchMSG. Vorschlag von @elektron-bbs “DaumenHoch“

**Comment by HomeAutoUser** [comment]
@sidey79, bitte Punkt 2 & 3 noch in Angriff nehmen. 
Wir verzetteln uns sonst.

**Comment by sidey79** [comment]
@HomeAutoUser 

Punkt 2 habe ich nun noch mal etwas angepasst:

![image](https://user-images.githubusercontent.com/7968127/79019544-dd74d400-7b76-11ea-9817-1dda8eb40113.png)


Punkt 3 habe ich schon vor einigen Minuten angepasst :)
![image](https://user-images.githubusercontent.com/7968127/79019584-fb423900-7b76-11ea-9d98-dd051dbb91b5.png)

**Comment by HomeAutoUser** [comment]
@sidey79, Punkt 2 stimmt noch nicht.

1. wieso C<reg> <reg>? Meintest du nicht get ccreg <reg>
2. set raw 35 im example... das geht nicht

**Comment by sidey79** [comment]
Ich weiss nicht, wer den Abschnitt im Wiki erstellt hat, aber es werden Firmware Befehle aufgeführt.

ccreg ist ein Modul Kommando und kein Firmware Kommando.
Vielleicht interessant, wenn jemand direkt auf den uC zugreift.

**Comment by HomeAutoUser** [comment]
Fakt ist ja, dieser Abschnitt muss korrigiert werden weil es so nicht geht und auch der Benutzer beim nachlesen eine falsche Vorgabe / Hinweis erhält welcher dann nicht funktionieren kann.

**Comment by sidey79** [comment]
Hab den C35 Befehl korrigiert. Das C hatte sich irgendwo versteckt, also habe ich ein neues spendiert :)

**Comment by HomeAutoUser** [comment]
Bitte erläutere mir, wie bei Dir folgender Befehl geht.
> Example: set raw C35 führt zu einer Logausgabe folgender Art Read, msg: C35 = 0D

Set raw C35 hat kein return und geht im ersten Blick ins leere.

```
2020.04.10 23:12:42 5: radino_433Mhz: SimpleWrite, C35
2020.04.10 23:12:42 4: radino_433Mhz: Read, msg: C35 = 0D
2020.04.10 23:12:42 5: radino_433Mhz: Parse, noMsg: C35 = 0D
2020.04.10 23:12:42 4: radino_433Mhz: HandleWriteQueue, called
2020.04.10 23:12:42 4: radino_433Mhz: HandleWriteQueue, nothing to send, stopping
```

Ist das so gewollt oder Absicht?
Die Logausgabe im Text muss besser erläutert werden, da es erst ab verbose 4 passiert.

**Comment by sidey79** [comment]
Ich hab den Text im  Wiki noch mal abgeändert. Du darfst auch gerne ändern wenn Du andere Vorstellungen hast :)

Der set raw Befehl liefert nie eine Rückmeldung im FhemWeb, das ist so gewollt.
Wer die Firmwarebefehle im wiki hinterlegt hat, weiss ich nicht. Ist auch egal. Ich denke, es soll halt erläutern, wie man direkt auf den UC ohne Modulfunktionen zugreifen kann um Werte abzurufen.

**Comment by HomeAutoUser** [comment]
Gelesen und ich denke da können wir nun einen Haken setzen :)
