### ISSUE TITLE
Multiple set commands are not processed

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#823]
## Expected Behavior
If multiple send requests are executed, they are processed one afther the previous

## Actual Behavior
https://forum.fhem.de/index.php?topic=110026.new;topicseen#new

Only the first set command is received properly from the receiver, the second one isn't received correctly

## Steps to Reproduce the Problem

  1. set PC.Rollo,SZ.Rollo  (send multiiple commands)

## Specifications

  - Microcontroller: nanocc1101
  - Version (Firmware): v3.4.3_dev_08.04

  - Versionmodul (FHEM Module): 3.4.2 stable

**Comment by HomeAutoUser** [comment]
@sidey79, ist das hier, vielleicht der selbe Fall? https://forum.fhem.de/index.php?topic=110035.0

**Comment by sidey79** [comment]
@HomeAutoUser 
Ja ist vermutlich das identische Problem. Ich hab das versucht mit zwei Signalduinos nachstellen zu können, klappt aber nicht sonderlich gut :(

**Comment by sidey79** [comment]
Ich hab gestern noch ein bisschen analysierte und den Fehler eingrenzen können.

Festzustellen ist, dass der 2. Befehl zu früh an den uC übergeben wird und es dadurch zu dem Sendeproblem kommt.

Ob die Ursache im Modul oder in der Firmware steckt habe ich noch nicht so ganz herausbekommen. Nachstellen lässt sich das Verhalten weitgehend, wenn man der Read Funktion ein SR; gefolgt von einem Zeilenumbruch in den InputBuffer vom IO Device legt.

Wo dieser Zeilenumbruch nun herkommt ist die Frage.

**Comment by HomeAutoUser** [comment]
Wenn etwas auf einmal zu schnell sendet oder nun eine Differenz gibt, so können es ja nur diese Dinge sein:

- das damalige einbinden des Sendekommando war falsch
- das Modul hat nun ein anderes Timing bei der Verarbeitung
- ein Steuerzeichen hat sich eingeschlichen was nun eine Verzögerung Veränderung führt
- ...

Wenn der Grund gefunden ist, so zeigt es, das wir diesen Fall abdecken müssen für die Zukunft um nicht wieder einen Fehler einzufangen.

**Comment by sidey79** [comment]
Ich hatte die Verarbeitung in der aktuellen Stable Version angepasst, wir hatten vorher eine feste Zeitspanne zwischen den Sendekommandos unabhängig einer Rückmeldung vom uC.
Das hat oft aber auch nicht immer funktioniert. :(

Jetzt wird auf die Rückmeldung vom uC reagiert. Die Idee ist, sende das Nächste Kommando, sobald eine Rückmeldung vom vorherigen vorliegt.

Im uC wird das SR; direkt nach der Auswertung wieder ausgegeben. Das habe ich gemacht, um möglichst früh schon mit der Antwort zu beginnen. Grundsätzlich sollte dort kein Zeilenumbruch enthalten sein, da mittels MSG_PRINT die Ausgabe erfolgt.

Auf der Modulseite wird das ganze aber als einzelnes Kommando gewertet. Das klappt nur, wenn ein Zeilenumbruch eingefügt wird.

Ob das irgendwo im seriellen Portobjekt verbaut ist?

Ein schneller Workaround wäre, diese feste Pause wieder einzubauen und den Bug dadurch entschärfen.

**Comment by HomeAutoUser** [comment]
Wenn ich darüber nachdenke, so sollte das im prinzip richtig sein.

>Jetzt wird auf die Rückmeldung vom uC reagiert. Die Idee ist, sende das Nächste Kommando, sobald eine Rückmeldung vom vorherigen vorliegt.

Von einer festen Pause würde ich ggf absehen. Wenn ein Nachrichtensiginal mit mehreren Wiederholungen zustande kommt, so bestimmt ja der Hersteller die Pausen bzw. Zeiten der Puls Pause Zusammenstellung.

Ich denke die Umsetzung bzw. die Interpretation im Modul 
>Auf der Modulseite wird das ganze aber als einzelnes Kommando gewertet. Das klappt nur, wenn ein Zeilenumbruch eingefügt wird.

ist dort gefragt. Entweder man kann anstatt einem Zeilenumbruch vielleicht ein Leerzeichen nutzen?

> Ein schneller Workaround wäre, diese feste Pause wieder einzubauen und den Bug dadurch entschärfen.

Ja, aber wann widmet man sich der Sache wieder? Jetzt sich dem Bug zu widmen ist schon richtig denke ich.

Oder denkt Ihr anders darüber? @all

**Comment by sidey79** [comment]
Naja ich denke,
Auf die schnelle kann man die Sendepause wieder einfügen, damit wenigstens die Funktionsweise wieder weitgehend gegeben ist und die Anwender sich nicht unnötig einen Fehler suchen müssen.

Grundsätzlich ist die Ursache zu analysieren. Das könnte halt ein bisschen Zeit benötigen, was für eine Umgehungslösung aus meiner Sicht spricht.

**Comment by HomeAutoUser** [comment]
>Auf die schnelle kann man die Sendepause wieder einfügen, damit wenigstens die Funktionsweise wieder weitgehend gegeben ist und die Anwender sich nicht unnötig einen Fehler suchen müssen.

Dann löse es erstmal so und es DARF nicht in Vergessenheit geraten.

>Grundsätzlich ist die Ursache zu analysieren. Das könnte halt ein bisschen Zeit benötigen, was für eine Umgehungslösung aus meiner Sicht spricht.

**Comment by sidey79** [comment]
Ich werde nicht schlau aus dem Fehlerbild. :(

Ich habe mir den uC genauer angesehen. 
Wenn ich den Sendebefehl per Terminal übergebe, dann kommt auch 1:1 das Kommando wieder zurück. Das passt also auch soweit alles gut.
Die Erkennung von Befehlsende ist Optimierungswürdig, aber das tut für dieses Problem nichts zur Sache.


Übergebe ich den Sendebefehl vom Modul via set raw aus, dann kommt Murks zurück. Soweit ich das aus dem Log deuten kann, kommt
SR;<Zeilenumbruch>
F<Zeilenumbruch>
R=6;P=x...
Der Teil mit D= kommt nicht.

Sehr seltsam :(

**Comment by HomeAutoUser** [comment]
Hatten wir nicht schonmal Probleme mit Zeilenumbrüche ode Codierung wenn du Kommandos via Fonted und Set raw übergibst?

**Comment by sidey79** [comment]
Ich bin der Ansicht, es liegt an der Firmware.

**Comment by HomeAutoUser** [comment]
Soweit überblicke es nicht.
Ich kann mir dann nicht erklären, wieso mit Tausch des Modules der Zustand sich ändert Obwohl die FW gleich bleibt.

**Comment by sidey79** [comment]
Vor der Modulversion 3.4.2 haben wir eine kurze Pause gehabt, nachdem vom uC ein SR; empfangen wurde.

In 3.4.2 habe ich das geändert.

Die fehlerhafte Ausgabe vom uC kam dadurch nicht zum Tragen. Zumindest meistens.

**Comment by HomeAutoUser** [comment]
Na Hauptsache du kannst die Stelle lokalisieren wo man ansetzen muss.

Kann man anstatt der Pause im uC nicht etwas „anderes eindeutiges“ setzen oder markieren?

**Comment by sidey79** [comment]
Das Zeilenende war sozusagen die Erkennung, dass das Senden beendet wurde.

Ich habe die Stelle schon korrigiert.
Müsste mal schauen, ob es da noch mehr so Stellen gibt. Könnte ich mir vorstellen :)

**Comment by HomeAutoUser** [comment]
Nur noch mal zum Verständnis, der #824 hat nichts mit der Fehler / Änderung der FW zu tun ?

**Comment by sidey79** [comment]
Diesen Fehler in der Firmware behoben mit folgendem commit:
https://github.com/RFD-FHEM/SIGNALDuino/commit/749cc9159dcb03281f714d8ca330bd104e4ae9b3

Jetzt stellt sich die Frage, wie wir mit dem Modul umgehen. Sobald ich den Workaround wieder entferne, klappt es mit alten Firmwareversionen ja nicht und die 3.4.0 ist ja noch "development"

**Comment by HomeAutoUser** [comment]
>Jetzt stellt sich die Frage, wie wir mit dem Modul umgehen. Sobald ich den Workaround wieder entferne, klappt es mit alten Firmwareversionen ja nicht und die 3.4.0 ist ja noch "development"

Wir wäre es mit einer Versionsabfrage / kompatiblitätscheck im Modul?

**Comment by sidey79** [comment]
An eine Versionsabfrage habe ich auch kurz gedacht, aber das ist schon irgendwie naja. sagen wir mal so, blöd.
Vielleicht fällt uns da etwas eleganteres ein.

Wenn wir nicht nur auf SR; sondern noch etwas Zusäztlich die Regex bauen, vielleicht
`^SR;.*D=.*;`  (Das  müsste ja immer so enthalten sein), dann würde man ja herausfinden, ob die Firmware den Fix hat. Für den Fall, dass die Rückmeldung nicht kommt, könnte man ja quasi nach einem Timeout die folgenden Sendebefehle absetzen.

Firmware mit bug, wartet dann bis zum timeout und die Firmware ohne bug sendet etwas früher

**Comment by HomeAutoUser** [comment]
Welche Konstellation vom Fehler gibt es?

- Alte FW / altes Modul
- neue FW / neues Modul
- alte FW / neues Modul

Was wäre, wenn man im jetzigen Master FW dies korrigiert? Beim auftreten könnte ggf der Benutzer noch einmal die aktuellere Master FW flashen.

**Comment by sidey79** [comment]
@HomeAutoUser 

Ja, den Workaround würde ich mit #825 in master und auch SVN bringen.

Dann kann man sich der Lösung ja noch widmen :)

**Comment by HomeAutoUser** [comment]
Ich komme irgendwie durcheinander.
Der Workaround ist nur für das Master weil in der Dev Version Modul es angepasst wurde und in der DEV Firmware. Ist das richtig?

Somit ist doch 
> Dann kann man sich der Lösung ja noch widmen :)

Hinfällig in der Dev Version.

**Comment by sidey79** [comment]
@HomeAutoUser 

Naja, ich würds in der v3.4 erst mal mit dem delay belassen, da auch noch keine Firmware compiliert wurde und ich noch weitere Untersuchungen durchführen möchte, ob das an anderer Stelle nicht auch nocht geschehen kann

**Comment by HomeAutoUser** [comment]
@sidey79 hier haben wir auch noch ein Issues schlummern mit dem Label "fixed" & "bug".
Wie ist hier der Sachstand?
