### ISSUE TITLE
Can't use string ("SIGNALduino_Connect")...

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#832]
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Microcontroller:
  - Version (Firmware):

  - Versionmodul (FHEM Module):

**Comment by elektron-bbs** [comment]
Den "Vorspann" habe ich mir jetzt mal gespart.
Ich bin mir nicht sicher, ob hier noch Handlungsbedarf besteht.

Nach dem Update heute Morgen kam FHEM nicht mehr "hoch" - ständige Neustarts mit folgender Fehlermeldung:

```
2020.04.14 09:22:26.638 3: sduino_USB1 device opened
Can't use string ("SIGNALduino_Connect") as a subroutine ref while "strict refs" in use at ./FHEM/DevIo.pm line 237.
```

Der Fehler wurde auch im Forum gemeldet: https://forum.fhem.de/index.php/topic,110179.0.html

Dann wurde wohl ein Patch veröffentlicht und jetzt lief das Update wieder ohne Probleme.

**Comment by sidey79** [comment]
@elektron-bbs 

Danke.
Ja das ist echt klasse.  Der unittest hätte den Fehler auch gefunden, wenn das FHEM package aktualisiert gewesen wäre :)
