### ISSUE TITLE
VASNER VFTB Funk Raumthermostat Sender für Infrarotheizungen / Baugleich Funk-Thermostat Set BT710 Sender mit BT001 Unterputz Empfänger

### ISSUE THREAD

**Issue by DavidKing123456** [RFD-FHEM/RFFHEM#834]
Hallo ich habe ein VASNER VFTB Funk Raumthermostat mit passendem Empfänger.

www.vasner.com/de/produkte/vasner-vftb-x-digitales-funk-raumthermostat-set/

Temp. und Luftfeuchtigkeit bekomme ich ausgelesen. 

**Aber wie kann ich den Funkempfänger schalten? Das ist die Herausforderung**  

FHEM empfängt Ihn 

**als SD_WS_51_TH_1**
```
CFGFN |  -- | --
CODE | SD_WS_51_TH_1
DEF | SD_WS_51_TH_1 
FUUID | 5e971283-f33f-6e19-1e1f-5136b93aa2ee0f0e
LASTInputDev | SIGNALduino433
MSGCNT | 44
NAME | SD_WS_51_TH_1
NR | 243
SIGNALduino433_DMSG | W51#8CF0623281
SIGNALduino433_MSGCNT | 68
SIGNALduino433_Protocol_ID | 51
SIGNALduino433_RAWMSG | MS;P4=617;P5=-8906;P6=-4039;P7=-1841;D=4546474747464647474646464647474747474646474747464747474646474746474647474747474746;CP=4;SP=5;R=238;
SIGNALduino433_RSSI | -83
SIGNALduino433_TIME | 2020-04-15 16:52:39
STATE | T: 19.5 H: 28
TYPE | SD_WS
bitMSG | 1000110011110000011000100011001010000001
lastMSG | 8CF0623281
lastReceive | 1586962359

```
**Readings**
Reading| value | timestamp
-- | -- | --
batteryState | ok | 2020-04-15 16:52:39
channel | 1 | 2020-04-15 16:52:39
humidity | 28 | 2020-04-15 16:52:39
sendmode | auto | 2020-04-15 16:52:39
state | T: 19.5 H: 28 | 2020-04-15 16:52:39
temperature | 19.5 | 2020-04-15 16:52:39
trend | consistent | 2020-04-15 16:52:39
type | Auriol IAN 275901, IAN 114324, IAN 60107 | 2020-04-15 16:52:39

**Comment by HomeAutoUser** [comment]
Hallo,
1) welche Werte von den beiden Devices sind richtig?
2) Kannst du die Werte ablesen und kontrollieren?
3) die Steuerung wird nicht so einfach fürs erste, da die bei dir angelegte Devices nur Sender sind.

Mfg

**Comment by elektron-bbs** [comment]
Ich schätze, beide Werte sind richtig. Ich habe schon länger den Verdacht, das die Module TCM97 und SD_WS teilweise die gleichen Protokolle verarbeiten. Beide Nachrichten enthalten die gleiche long-ID: 0x8C.
Vielleicht haben wir ja Glück und das Ein- und Ausschalten erfolgt auch mit diesem Protokoll. Es sind ja bisher noch 3 Bit unklar.

**Comment by DavidKing123456** [comment]
Ja mein Fehler habe gerade die Batterien aus dem Vasner genommen und der Device **CUL_TCM97001_140** sendet fleißig weiter.... Sorry.  Ich werde erstmal nochmal genau schauen was gesendet wird wenn ich die Batterien wieder einlege.

**Comment by HomeAutoUser** [comment]
@elektron-bbs 
kurz auf deinen Verdacht zu kommen.
Wir müssten uns mal die Arbeit machen und mitloggen / schreiben welche RAWmsg doppelt ausgewertet werden. Zusätzlich ggf mal sämtliche RAWMSG zusammentragen die von den Modulen gesammelt wurden. So kann man ggf das Ganze verifizieren und vielleicht „anpassen“.

**Comment by DavidKing123456** [comment]
So nachdem ich die Batterien eingelegt habe wurde auf dem 
**Event Monitor folgendes ausgegeben:**

2020-04-15 18:53:24 Global global UNDEFINED SD_WS_51_TH_1 SD_WS SD_WS_51_TH_1
2020-04-15 18:53:24 Global global DEFINED SD_WS_51_TH_1
2020-04-15 18:53:24 Global global DEFINED FileLog_SD_WS_51_TH_1
2020-04-15 18:53:24 Global global ATTR SD_WS_51_TH_1 event-min-interval .*:300
2020-04-15 18:53:24 Global global ATTR SD_WS_51_TH_1 event-on-change-reading .*
2020-04-15 18:53:24 Global global DEFINED SVG_SD_WS_51_TH_1
2020-04-15 18:53:24 Global global SAVE
2020-04-15 18:53:25 SD_WS SD_WS_51_TH_1 T: 19.3 H: 28
2020-04-15 18:53:25 SD_WS SD_WS_51_TH_1 temperature: 19.3
2020-04-15 18:53:25 SD_WS SD_WS_51_TH_1 humidity: 28
2020-04-15 18:53:25 SD_WS SD_WS_51_TH_1 batteryState: ok
2020-04-15 18:53:25 SD_WS SD_WS_51_TH_1 trend: consistent
2020-04-15 18:53:25 SD_WS SD_WS_51_TH_1 sendmode: auto


So wenn ich die Daten mit dem Display von Vasner vergleiche steht in FHEM eine Temp. von 19.3 auf dem Display Temp. 22.4 

**Als ich die Heizung ausstellte kam im Log folgender Eintrag:**

2020.04.15 19:24:27 4: SIGNALduino433: Read, msg READredu: MU;P0=-4033;P1=594;P2=-1851;P3=-116;P4=96;P5=-15976;P6=1000;P7=-1018;D=01212121010121212101012121212121210101212134212101012101212121012101212121212121015676767671;CP=1;R=241;
2020.04.15 19:24:27 1: DEBUG>SIGNALduino433: incoming message: (MU;P0=-4033;P1=594;P2=-1851;P3=-116;P4=96;P5=-15976;P6=1000;P7=-1018;D=01212121010121212101012121212121210101212134212101012101212121012101212121212121015676767671;CP=1;R=241;)

Oder welche Daten wären Interessant?

**Comment by DavidKing123456** [comment]
@elektron-bbs Vielleicht bin ich mit den beiden Temperatur Device auch auf dem Holzweg und die gehören garnicht dazu. Mich wundert es halt das die beiden immer Parallel  die selben Daten zeigen und nicht die Daten die auf dem display sind. Wie kann ich das denn verifizieren? Ideen Tips werden gerne angenommen, da ich da noch keine Erfahrung damit habe.

**Comment by elektron-bbs** [comment]
Das SD_WS SD_WS_51_TH_1 hat also auch nichts mit dem Thermostat zu tun.

Der Hersteller schreibt ja, das die Teile bidirektional arbeiten, d.h. wenn vom Thermostat ein Schaltbefehl kommt, muss dieser Befehl vom Aktor bestätigt werden. Es müssten also innerhalb kurzer Zeit mindestens 2 Funktelegramme zu sehen sein.

Du kannst nur versuchen, Thermostat, Aktor und SIGNALduino irgendwie von anderen Funksignalen abzuschirmen und dann die Signale zu loggen. Falls du einen SIGNALduino mit CC1101 hast, kannst du dessen Empfindlichkeit herabsetzen, in dem du cc1101_rAmpl auf 24 setzt. Dann mit den Teilen in eine Blechkiste, oder ab in den Keller... Unter Umständen sendet das Thermostat wirklich nur, wenn ein Ein- oder Ausschaltbefehl erforderlich. Eine erste Möglichkeit wäre auch noch das Pairen zu loggen.

**Comment by elektron-bbs** [comment]
@HomeAutoUser 
Mir fällt immer wieder auf, das TCM97-Geräte mit den typischen Timings von ca. 500, 1000, 4000 und 8000 angelegt werden, die auch SD_WS_33 und 51 verwenden. Hier war es jetzt offensichtlich der Fall.

**Comment by DavidKing123456** [comment]
Ok ,nun dann werde ich mal eine Laborbedingung schaffen wenn ich etwas neues habe melde ich mich wieder.

**Comment by HomeAutoUser** [comment]
Hallo @DavidKing123456 ,
gibt es neue Erkenntnisse?

**Comment by HomeAutoUser** [comment]
@DavidKing123456 
hast du dich deiner Thematik noch einmal beschäftigt?

**Comment by HomeAutoUser** [comment]
@DavidKing123456 

> 
> Ok ,nun dann werde ich mal eine Laborbedingung schaffen wenn ich etwas neues habe melde ich mich wieder.

kamst du zwischenzeitlich noch einmal dazu dies zu testen?

**Comment by HomeAutoUser** [comment]
@DavidKing123456 ist dein Anliegen noch offen oder hast du bereits einen Haken dahinter gemacht ?

**Comment by elektron-bbs** [comment]
Über ein Jahr keine Reaktion, ich schließe das Thema.
