### ISSUE TITLE
Wrong operator for eq 00_SIGNALduino

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#835]
https://github.com/RFD-FHEM/RFFHEM/blob/a848db7df5c6de374fcacacb09027416fabadbd2/FHEM/00_SIGNALduino.pm#L3893

https://perldoc.perl.org/perlop.html#Equality-Operators
Binary "eq" returns true if the left argument is stringwise equal to the right argument.

Todo:

- [ ] Test erstellen
- [ ] Fehler beheben

**Comment by HomeAutoUser** [comment]
Für was möchtest du da einen Test erstellen? Ein Test für diese Zeile ist überflüssig. Es würde nur Sinn machen, wenn ein Test sämtliche „ eq number“ aufdecken würde.

Korrigieren ja.

**Comment by sidey79** [comment]
Naja erstellen trifft es vielleicht nicht, aber den Test für diese Sub SIGNALduino_OSV2 ansehen und entscheiden ob dieser Fehler testbar ist.

**Comment by sidey79** [comment]
Hab auch noch Kandidaten für Nummern gefunden
https://github.com/RFD-FHEM/RFFHEM/blob/a848db7df5c6de374fcacacb09027416fabadbd2/FHEM/00_SIGNALduino.pm#L4005-L4010

**Comment by HomeAutoUser** [comment]
Bitte testen @sidey79 was Perl interpretiert.

Channel == 00 könnte als Channel == 0 gedeutet werden.
Nicht das Channel eq ´00´ gemeint ist. (Doppelte 0). Verstehst du mein Ansinnen?

**Comment by HomeAutoUser** [comment]
Im Falle von https://github.com/RFD-FHEM/RFFHEM/issues/835#issuecomment-614253532 wäre es ‚eq‘ weil die Prüfung auf einen String mit der Länge 2 stattfindet.

**Comment by sidey79** [comment]
@HomeAutoUser 

Perl überrascht mich. Alle Varianten, auch die, welche nicht korrekt sind, liefern ein korrektes Ergebnis:

https://rextester.com/live/ALCOOC96500

**Comment by sidey79** [comment]
Damit hat sich das Thema 'Test anpassen" irgendwie erledigt

**Comment by HomeAutoUser** [comment]
:) ja, irgendwie ist es nur eine Ansichtssache wie man persönlich argumentiert.

**Comment by sidey79** [comment]
Laut Perdoc ist die aktuell verwendete Variante defintitv falsch oder seht ihr das anders?

**Comment by HomeAutoUser** [comment]
Laut Erläuterungen sind
1)  Strings im Vergleich mit Bsp. eq zu vergleichen
2)  Nummerische Werte mit Bsp. == zu vergleichen.

Hier https://github.com/RFD-FHEM/RFFHEM/issues/835#issuecomment-614253532 wäre es ein Misch aus beiden.

**Comment by sidey79** [comment]
Hier sind ein paar ganz gute Beispiele wie ich finde:
https://perlmaven.com/comparing-scalars-in-perl

**Comment by sidey79** [comment]
wir haben noch etliche mehr solcher Stelle in unseren Modulen :(

**Comment by HomeAutoUser** [comment]
Stellen sammeln / notieren und ändern. Sowas bleibt nicht aus bei Übernahme / Erweiterung / C&P Zeiten ...

**Comment by sidey79** [comment]
Hab jetzt alle die ich mittels grep finden konnte korrigiert:

https://github.com/RFD-FHEM/RFFHEM/tree/dev-r34_operatorFixes
