### ISSUE TITLE
Wrong operator eq for number

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#836]
https://github.com/RFD-FHEM/RFFHEM/blob/a848db7df5c6de374fcacacb09027416fabadbd2/FHEM/10_SD_GT.pm#L289

- [ ] Prüfen ob ein Test erweitert werden kann
- [ ] Fehler beheben

**Comment by HomeAutoUser** [comment]
Das Thema ist doch abgehakt oder?

**Comment by sidey79** [comment]
Es ist noch nicht gemerged

**Comment by HomeAutoUser** [comment]
Bitte aber nochmal kontrollieren.

Derzeit ist die Zeile eigendlich wie es sein sollte laut Faden https://github.com/RFD-FHEM/RFFHEM/commit/d3719d04901f2586c8d070490073d7aacdafb4d1

https://github.com/RFD-FHEM/RFFHEM/blob/5fdcf47d4cf360bde7a1b9d0cfeb353fb6bcee0e/FHEM/10_SD_GT.pm#L289

Am besten @elektron-bbs hat dann das letzte Worte ;-)

**Comment by elektron-bbs** [comment]
Es gab hier
https://github.com/RFD-FHEM/RFFHEM/commit/4351e39109873bab27eefe703ee8f7b4d79e2786
dann nochmal eine Änderung, die eigentlich passen müsste. Getestet habe ich diese und die weiteren Änderungen in diesem Branch allerdings noch nicht.

Außerdem hatte @sidey79 bei dem Issue noch angemerkt:

> Prüfen ob ein Test erweitert werden kann

**Comment by sidey79** [comment]
@elektron-bbs 

Ja, aber meine Versuche etwas zu vergleichen haben ergeben, dass wir das mit einem Test nicht abfangen können.... leider

**Comment by elektron-bbs** [comment]
Dann kann das Issue m.E. geschlossen werden.
