### ISSUE TITLE
Signalduino_CalculateCRC16 durch Digest::CRC Ersetzen

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#838]
```
		use Digest::CRC;
		my $ctx = Digest::CRC->new(width=>16, poly=>0x8005, init=>0x0000, refin=>0, refout=>0, xorout=>0x0000);
		
		$dmsg = '010503B7A101AAAAAAAA';
		$chk16 = SIGNALduino_CalculateCRC16($dmsg,$poly,$crc16);
		$ctx->add(pack 'H*', $dmsg);
		is($ctx->digest,$chk16,"check return Digest::CRC dmsg $dmsg");
```

**Comment by HomeAutoUser** [comment]
Verstehe ich das richtig, du möchtest nur den Test durch die fertige Routine ersetzen?

**Comment by sidey79** [comment]
Nein, die komplette Sub, Der test war nur zum verifizieren, dass das gleiche Ergebnis dabei herauskommt und wir keine eigene sub benötigen :)

**Comment by HomeAutoUser** [comment]
Denkst du nicht, das man sich mit solch einer kompletten Umstellung abhängig macht? Der User benötigt das zusätzliche Paket. In wie weit es Plattformübergreifend vorhanden ist, kann ich nicht einschätzen.

Ich selbst habe BSp. ein Testsystem auf einer Synology und da sind solche Pakete rar. Dies würde heißen, ich kann dort dies nicht nutzen.

Im Test ist es okay zum verifizieren.

**Comment by sidey79** [comment]
Da es ein "Spezial CRC" ist, sollten wir hierfür einen besseren Namen finden und das ganze auch in ein package verschieben in das es gehört. Da eh nur die ersten 8 nibble hier verwendet werden, würde ich ja eher anpassen, dass genau ein dezimal Parameter übergeben wird.

`irgendeinCrc(subst($dmsg,0,8))`   oder meinetwegen auch eine Dezimalzahl, aber dann muss in der sub noch mehr angepasst werden.

**Comment by sidey79** [comment]
Da Perl CRC Modul ist  über cpan erhältlich ist, sollte es keine wirkliche Herausforderung darstellen.
Wo kein cpan geht, geht ohnehin zu ziemlich wenig.

Wir verwenden das Modul auch schon in anderen unserer Module und in Fhem ist es durchaus verbreitet.
` grep -rP 'Digest::CRC' /opt/fhem/FHEM/ | grep .pm`  

Würde also sagen, lieber ein Standardmodul verwenden, als code zu duplizieren.

**Comment by HomeAutoUser** [comment]
Ich höre dabei raus, du du Kompromissbereit wärest wenn wir die Sub anpassen und in ein Package verfrachten.

Hast du einen Namensvorschlag wo wir solche Subs hinein bringen?

Den Subname könnte vielleicht sowas sein
- CRC16_first8N ?

**Comment by sidey79** [comment]
Ich komme durcheinander:
SIGNALduino_CalculateCRC  -> Ist was super spezielles und hier werden nur die ersten 8 "Zeichen" für eine crc Berechnung verwendet.  
Ich finde es unlogisch mehr Daten zu übergeben, als ausgewertet werden, also sollte man das anpassen und umbenennen.


SIGNALduino_CalculateCRC16
Können wir meines Erachtens streichen und durch Digest::CRC ersetzen.

**Comment by HomeAutoUser** [comment]
> SIGNALduino_CalculateCRC16
Können wir meines Erachtens streichen und durch Digest::CRC ersetzen.

Können wir gern machen.

> Ich komme durcheinander:
SIGNALduino_CalculateCRC -> Ist was super spezielles und hier werden nur die ersten 8 "Zeichen" für eine crc Berechnung verwendet.

Hier siehst du die Quelle und vermutlich den Ursprung.
https://github.com/heliflieger/a-culfw/blob/master/culfw/clib/lacrosse.c

**Comment by HomeAutoUser** [comment]
Was hälst du von der Variante?

```
################################################
########## Section & functions for CRC #########
package CalculateCRC;

############################# package CalculateCRC
sub order16($) {
  my $dmsg = shift;
  my $ctx = Digest::CRC->new(width=>16, poly=>0x8005, init=>0x0000, refin=>0, refout=>0, xorout=>0x0000);
  $ctx->add(pack 'H*', $dmsg);
  return $ctx;
}
```

Aufruf
`	my $chk16 = CalculateCRC::order16($dmsg);`

Dies lässt Freiraum, das man diese weiter nutzen kann oder wenn es zu einem anderem Poly oder Init kommen sollte, eine weitere Sub in dem Package Abschnitt ergänzt werden kann. (Bsp: andere Digest::CRC 32)

Den Test `test_sub_SIGNALduino_CalculateCRC16-definition.txt` kann man dann löschen und stattdessen einen `test_sub_SIGNALduino_PCA301-definition.txt` erstellen wo die CRC geprüft wird.

**Comment by sidey79** [comment]
Wieso überhaupt eine Sub machen, wenn es doch schon eine im Digest::CRC gibt?

**Comment by HomeAutoUser** [comment]
Die Frage ist berechtigt.
Ich sehe den Vorteil maximal darin, wenn man innerhalb des Modules noch einmal dden Code nutzen möchte oder in Zukunft diesen nochmal nutzen kann.

Entweder immer 3 Zeilen im code zusätzlich oder einmal eine Sub wo die Parameter durchgejagt werden.

**Comment by HomeAutoUser** [comment]
@sidey79 

ich würde das wie folgt denken:

```
sub SIGNALduino_PCA301($$$) {
	my ($name,$rmsg,$id) = @_;
	my $hash = $defs{$name};

	my $checksum = substr($rmsg,20,4);
	my $dmsg = substr($rmsg,0,20);

	if ($missingModulSIGNALduino =~ m/Digest::CRC/ ) {
		$hash->{logMethod}->($hash->{NAME}, 1, "$hash->{NAME}: PCA301_convert failed. Please install Perl module Digest::CRC. Example: sudo apt-get install libdigest-crc-perl");
		return (-1,"PCA301_convert: Digest::CRC failed");
	}

	my $ctx = Digest::CRC->new(width=>16, poly=>0x8005, init=>0x0000, refin=>0, refout=>0, xorout=>0x0000);
	$ctx->add(pack 'H*', $dmsg);

	$hash->{logMethod}->($name, 5, "$name: PCA301, checksumCalc=".$ctx->digest." checksum=" . hex($checksum));

	if ($ctx->digest == hex($checksum)) {
		my $channel = hex(substr($rmsg,0,2));
		my $command = hex(substr($rmsg,2,2));
		my $addr1 = hex(substr($rmsg,4,2));
		my $addr2 = hex(substr($rmsg,6,2));
		my $addr3 = hex(substr($rmsg,8,2));
		my $plugstate = substr($rmsg,11,1);
		my $power1 = hex(substr($rmsg,12,2));
		my $power2 = hex(substr($rmsg,14,2));
		my $consumption1 = hex(substr($rmsg,16,2));
		my $consumption2 = hex(substr($rmsg,18,2));
		$dmsg = "OK 24 $channel $command $addr1 $addr2 $addr3 $plugstate $power1 $power2 $consumption1 $consumption2 $checksum";
		$hash->{logMethod}->($name, 4, "$name: PCA301, translated native RF telegram PCA301 $dmsg");
	} else {
		#Log3 $name, 4, "$name PCA301_convert: wrong checksum $checksum";
		return (-1,"PCA301_convert: wrong checksum $checksum");
	}
	return (1,$dmsg);
}
```

dannn muss der Test test_sub_SIGNALduino_PCA301 angepasst werden.
In etwa so

```
	subtest 'Test rcode -1 , Digest::CRC failed' => sub {
		plan(2);
		my $dmsg="0405019E8700AAAAAAAA0F13AA16ACC0540AAA49C814473A2774D208AC0B0167";
		my $id=101;
		my ($rcode,$dmsgMod) = SIGNALduino_PCA301($target,$dmsg,$id);

		is($rcode,-1,"check rcode for PCA301");
		is($dmsgMod,"PCA301_convert: Digest::CRC failed","check Digest::CRC failed");
	};
```

leider gelingt mit das nicht richtig zu integrieren weil wir ja dem Test sagen müssen, einmal 
1) Digest::CRC failed nicht laden (oder noch nicht geladen)
2) lade Digest::CRC -> subtest 'Test rcode 1' => sub { und subtest 'Test rcode -1' => sub {

**Comment by elektron-bbs** [comment]
> Ich komme durcheinander:
> SIGNALduino_CalculateCRC  -> Ist was super spezielles und hier werden nur die ersten 8 "Zeichen" für eine crc Berechnung verwendet.

Dieses "super spezielle" ist m.E. aber auch nur CRC-8 (siehe auch http://fredboboss.free.fr/articles/tx29.php/) und lässt sich mittels Digest::CRC ersetzen. Dieses Testmodul kommt zumindest zu den gleichen Ergebnissen:

[crc.pm.txt](https://github.com/RFD-FHEM/RFFHEM/files/4493697/crc.pm.txt)

Allerdings wollte @Ralf9 wohl Digest::CRC nicht verwenden (siehe https://forum.fhem.de/index.php/topic,106594.msg1009251.html#msg1009251), warum auch immer.

**Comment by elektron-bbs** [comment]
Mir fiel eben auch noch auf, das das Nachrichtenformat in der sub SIGNALduino_LaCrosse($$$) identisch ist zu Protokoll 64 (WH2) in der 14_SD_WS.pm, nur das dort noch ein Byte 0xFF am Beginn ist.

**Comment by sidey79** [comment]
Wir haben das CRC Modul ja bereits bei anderen Modulen im Einsatz.

Ich habe die Objektorientierte Variante für das Beispiel gewählt, weil die benannten Parameter selbige besser erklärt.

**Comment by HomeAutoUser** [comment]
Ich habe nichts dagegen wenn wir die andere Sub ggf ebenso anpassen.

@sidey79 
https://github.com/RFD-FHEM/RFFHEM/issues/838#issuecomment-615204898 Was sagst du dazu?

**Comment by sidey79** [comment]
Hier ein paar CRC Nutzungsbeispiele

```
FHEM/14_SD_WS09.pm:     my $crcmein1 = Digest::CRC->new(width => 8, poly => 0x31);
FHEM/14_SD_WS09.pm:     my $rr3 = $crcmein1->add($datacheck1)->hexdigest;
```

```
FHEM/14_SD_WS.pm:       my $crcmein1 = Digest::CRC->new(width => 8, poly => 0x31);
FHEM/14_SD_WS.pm:       my $rr3 = $crcmein1->add($datacheck1)->hexdigest;
```

Die Variante
```
$crc = crc($input,$width,$init,$xorout,$refout,$poly,$refin,$cont);
```
Geht auch, aber das würde ich nicht anfangen, da die named params Variante schon in Verwendung ist.

**Comment by HomeAutoUser** [comment]
@sidey79 

es geht um den Vorschlag https://github.com/RFD-FHEM/RFFHEM/issues/838#issuecomment-615204898

Nicht um den Vorschlag von $crc = crc($input,$width,$init,$xorout,$refout,$poly,$refin,$cont);

**Comment by sidey79** [comment]
> sub SIGNALduino_PCA301($$$) {

`	if ($ctx->digest == hex($checksum)) {`

würde ich in

`	if ($ctx->hexdigest == $checksum) {`

Ändern. Sollte auch zum gleichen Ergebnis führen.

Zum anderen, Fallen uns hier die Fehler der Anfänge auf die Füße.
Damit ist der Name und die Lokation der Sub gemeint.

`SIGNALduino_PCA301`

Ich weiss, ich habe damit selbst angefangen :) Wir müssen damit aber nicht weitermachen :)

Hier wird die Sub ja quasi verlinkt:
https://github.com/RFD-FHEM/RFFHEM/blob/ee89daf85eb265e1089137a292d003072a26a0a1/FHEM/lib/SD_ProtocolData.pm#L2648

Als wir die Protokolldaten in package lib::SD_ProtocolData verschoben haben, da war das quasi so die schnelle Lösung, weil die Subs halt in main lagen.

Meiner Ansicht nach, sollten wir das aber nicht fortführen.
Klingt jetzt etwas übertrieben, aber ich habe da Gefühl es wäre viel einfacher für die Zukunft weitere Packages anzulegen:

package lib::SD_ProtocolData::PCA301 oder lib::SD_ProtocolData::101

Ich weiss nicht ob  Nummern als Name erlaubt sind. Zumindest wird dann klar, wohin dieser Code gehört (würde ich mal so meinen)
Ob das jetzt so 100% zu Protokolldata gehört bin ich auch nicht so sicher. Die Sub macht doch nichts weiter, außer eine Checksummenprüfung (sollte man dann auch so benennen)

> Digest::CRC failed nicht laden (oder noch nicht geladen)
> lade Digest::CRC -> subtest 'Test rcode 1' => sub { und subtest 'Test rcode -1' => sub {

Zunächst mal wird das Modul immer installiert. Kann also von den tests auch immer geladen werden.
Den rcode -1 können wir nur hinbekommen, wenn das Modul nicht geladen werden kann.
Mir fällt da keine Lösung ein, wie wir das "einfach" hinbekommen. Bei den anderen Modulen ist es auch nicht realisiert. Würde ich in diesem Fall auch ausser Acht lassen und für den Test "$missingModulSIGNALduino " mit dem passenden Wert belegen. Wobei man das noch mal generell überdenken sollte, wenn wir es in ein eigenes Modul wandeln

**Comment by HomeAutoUser** [comment]
Das sind ja wieder Fakten an Mass ;)
Lese ich richtig heraus, du möchtest du Subs welche derzeit im Package Main lagern, auslagern wenn diese für die reine RAWMSG „Aufbereitung“ bzw Checksummenprüfung da sind?

**Comment by sidey79** [comment]
Hab schon ein schlechtes Gewissen.

Ich würde das jetzt auch nicht für alle bestehenden anwenden, sonder mal auf die neuen.
Vielleicht ist das auch zu viel da für jedes Protokoll ein Packages zu machen und diese Umwandlungen passen vielleicht auch in eines der vorhandenen Packages. 

Aufrufe von FHEM Funktionen sollten wir nach Möglichkeit (Log3) aus den Subs herauslassen, dann ließen sich die viel einfacher mit Bordmitteln verifizieren

**Comment by HomeAutoUser** [comment]
Ich verstehe deine Überlegung.

Leider sehe ich bei der Speicherung an 2 Stellen (alte Position und neue Position) nur mehr Durcheinander auf uns zukommen.

Reicht es nicht, wenn man innerhalb der .pm einen neuen Package Abschnitt eröffnet wo wir dann alle Subs von Modulen „hin transferieren“.

**Comment by sidey79** [comment]
Nein, das ist Murks mehrere Packages in einer Datei.
Ja ich weiss, hab ich für cc1101 mal so angefangen... holt einen alles wieder ein :(

jedes Package = eine eigen Datei, dadurch kann es auch zu einem echten Perl Modul werden.
Der Umstand mit den FHEM Modulen ist schon echt haarstäubend und Zeitaufwendig das im Griff zu halten.

Es gibt sogar schon einen Präzedenzfall habe ich gerade gesehen

sub MCRAW liegt in lib::SD_Protocols

Da würde ich die neuen auch hinpacken wollen.

**Comment by HomeAutoUser** [comment]
Wenn wir es auf 
`sub MCRAW liegt in lib::SD_Protocols`
umstellen, so würde ich wenn alle dann darein nehmen.

1) alles an einem Fleck
2) in der Signalduino pm ist dann nur der Code fürs Modul

Nur die neuen, so verlagern wir das Problem. Somit stellen wir einheitlich um, passen ggf Tests an aber haben es abgehakt. Es bringt nichts, einen Teil zu machen und somit noch mehr Verwirrung stiften.

**Comment by sidey79** [comment]
ja alle geht auch, ich wollte es halt nicht gleich übertreiben :)

**Comment by HomeAutoUser** [comment]
Moin, ich sehe es nicht als übertreiben.

Der Passus Ordnung und keine Verwirrung steht da im Vordergrund denke ich. Bin nicht unbedingt dafür, das wir einen Flickenteppich generieren :)

**Comment by sidey79** [comment]
Ich bin auch nicht für einen Flickenteppich.
Wollte hier jetzt nur keine Arbeit abladen, die mit FSK nichts zu tun hat :)

**Comment by HomeAutoUser** [comment]
Lass uns es mit bewältigen.
Sie es so, wir sehen Arbeit und erledigen diese ohne zu verlagern und „fahren“ weiter im Text.

Ich schaue es mir mal an nachher.

**Comment by HomeAutoUser** [comment]
@sidey79,
wie komme ich in `SD_Protocols.pm` an die globale FHEM Variable `$defs` ran?
Wie ziehen aus ihr heraus den hash `$hash = $defs{$name}`.

**Comment by sidey79** [comment]
Wenn wir Fhem Variablen und Funktionen in dem Modul verwenden, dann können wir nicht Kapseln.

Können wir nicht einfach mit Rückgabewerten arbeiten und die Logausgabe im Hauptprogramm machen?

**Comment by HomeAutoUser** [comment]
> Können wir nicht einfach mit Rückgabewerten arbeiten und die Logausgabe im Hauptprogramm machen?

Das stelle ich mir bisher schwierig vor.
Die Rückgabewerten müssten dann vorher vermutlich aber fest definiert werden.

Ich stelle mir das so vor, die Parse läuft durch und -1 kommt zurück, was Bsp. Fehler CRC bedeutet.
Kommt -2 zurück, dann Fehler CRC Modul. Das sollte dann aber deckend über alles sein.

Mir fehlt gerade die Idee, das sowas strukturiert abläuft ohne 2 Subs zu pflegen aber das der Endbenutzer auch die Hilfsausgaben, Debugausgaben... erhält.

Bsp: FHT
1) $hash->{logMethod}->($name, 3, "$name: FHT80, ERROR message all bit are zeros");
2) $hash->{logMethod}->($name, 5, "$name: FHT80, Detection aborted, checksum matches FS20 code");
3) $hash->{logMethod}->($name, 3, "$name: FHT80, ERROR - Parity not even");
4) $hash->{logMethod}->($name, 3, "$name: FHT80, ERROR - byte 3 bit 5 not 1");
5) $hash->{logMethod}->($name, 4, "$name: FHT80, roomthermostat post demodulation $dmsg");
6) $hash->{logMethod}->($name, 4, "$name: FHT80, ERROR - wrong checksum");

**Comment by HomeAutoUser** [comment]
@elektron-bbs 

> Dieses "super spezielle" ist m.E. aber auch nur CRC-8 (siehe auch http://fredboboss.free.fr/articles/tx29.php/) und lässt sich mittels Digest::CRC ersetzen. Dieses Testmodul kommt zumindest zu den gleichen Ergebnissen:
> 
> [crc.pm.txt](https://github.com/RFD-FHEM/RFFHEM/files/4493697/crc.pm.txt)

da müsste man die Sub anpassen und somit könnte es auf diesem Wege genutzt werden. Da sparen wir schon wieder eine Sub ein.

Hast du dich schonmal oder weiter damit befasst wenn du alles auf die Diggest Variante umstellen würdest?

```
my $datacheck1 = pack( 'H*', substr($dmsg,0,length($dmsg)-2) );
my $crcmein1 = Digest::CRC->new(width => 8, poly => 0x31);
my $rr3 = $crcmein1->add($datacheck1)->hexdigest;
$rr3 = sprintf("%d", hex($rr3));
```
Ist ja nur die Hälfte ($crc) von 
`my ($calccrc,$crc) = SIGNALduino_CalculateCRC($dmsg,4);`
Wenn wir $calccrc ohne die SIGNALduino_CalculateCRC errechnen, somit ist die Auflösung kein Problem.

**Comment by sidey79** [comment]
Nunja, ich habe mir das ganz einfach vorgestellt, vielleicht zu einfach :)

Wenn wir beispielsweise eine Lib wie CRC verwenden, dann schreibt diese Lib ja auch keine FHEM Meldungen raus.
Meist ruft man etwas auf und bekommt eine Rückmeldung.  So würde ich das hier auch machen, dann läuft die Lib auch ohne FHEM.

Konkret ging es ja beispielweise um folgendes:

Ich habe es so verstanden, dass diese Funktion die Daten Konvertiert, damit ein bestehendes Modul damit arbeiten kann.

```
use Data::Dumper;
use Digest::CRC;

sub Convert_ID100_2_Lacross {
	my ($rmsg) = @_;
	
	return (-10,'message to short') if (length($rmsg) < 24);  

	my $checksum = substr($rmsg,20,4);
	my $dmsg = substr($rmsg,0,20);

        my $ctx = Digest::CRC->new(width=>16, poly=>0x8005, init=>0x0000, refin=>0, refout=>0, xorout=>0x0000);
	$ctx->add(pack 'H*', $dmsg);

	return (-1,'checksumCalc=".$ctx->digest." != checksum=" . hex($checksum)') if ($ctx->digest != hex($checksum)) ;

	my $channel = hex(substr($rmsg,0,2));
	my $command = hex(substr($rmsg,2,2));
	my $addr1 = hex(substr($rmsg,4,2));
	my $addr2 = hex(substr($rmsg,6,2));
	my $addr3 = hex(substr($rmsg,8,2));
	my $plugstate = substr($rmsg,11,1);
	my $power1 = hex(substr($rmsg,12,2));
	my $power2 = hex(substr($rmsg,14,2));
	my $consumption1 = hex(substr($rmsg,16,2));
	my $consumption2 = hex(substr($rmsg,18,2));
	
       return (1,"OK 24 $channel $command $addr1 $addr2 $addr3 $plugstate $power1 $power2 $consumption1 $consumption2 $checksum");
}


print(Dumper(Convert_ID100_2_Lacross('34343534543'))); # To short
print(Dumper(Convert_ID100_2_Lacross('AABBCCDDEEFFGG112233445566'))); # Checksum error```
```

Ist jetzt mal freihand ohne Prüfung etc. Ok ich sehe gerade dein letzte Post hat sich mit meinem Entwurf überschnitten.

**Comment by HomeAutoUser** [comment]
Im Prinzip verstehe ich dein Vorgehen.

Die sub Convert_ID100_2_Lacross soll in die SD_Protocol Datei.

Wie rufen wir die dann auf um die Returns auch für das log zu erhalten?

Das geht sicherlich nur, wenn wir den Aufruf der Sub in der 00_Signalduino belassen, dort in die SD_Protocol springen und dann den Return in die 00_Signalduino zurück geben.

**Comment by sidey79** [comment]
Ja, nach ca 2 Stunden nachdenken würde ich sogar den Rückhabext ehrt komplett entfernen und dann eher Werte übergeben.
Den Text darum kann das SIGNALduino Modul machen, denn dieses benötigt es ja auch nur.

**Comment by HomeAutoUser** [comment]
Wenn wir nur Werte übergeben, wie wollen wir dann die Werte, den richtigen Zustand zuordnen?

**Comment by elektron-bbs** [comment]
Eigentlich sollte die CRC-8 genau so funktionieren, wie es @sidey79 vorhin in seinem Beispiel für CRC-16 gebracht hat. Es werden halt statt 10 Byte nur 4 Byte an die CRC-Routine übergeben und dann mit dem 5. Byte verglichen.

**Comment by sidey79** [comment]
> Wenn wir nur Werte übergeben, wie wollen wir dann die Werte, den richtigen Zustand zuordnen?

Naja, mehr als einen Wert übergeben so vielleicht


`return ($returncode, $calcCRC, $refCRC);`
Die Herausforderung haben wir ja bei all diesen Subs.

Die variante über einen Hash hat aber auch etwas, weil wir uns nicht auf die Menge an Werten schon im Vornherein festlegen müsse und das variable Zum Rückgabewert entscheiden können:

Variante mit Fehler  (zu kurz, keine weiteren Angaben nötig):
`return ('error" => RETURN_CODE_TO_SHORT);`

Variante mit Fehler code 2 (crc passt nicht)
`return ('error" => RETURN_CODE_CRC_MISMATCH, 'calcCRC' => $calcCRC, 'refCRC' => $refCRC);`

Variante ohne Fehler:
`return ('error" => RETURN_CODE_OK, 'convMSG' => "OK 24 $channel $command $addr1 $addr2 $addr3 $plugstate $power1 $power2 $consumption1 $consumption2 $checksum");`


Die RETURN_CODES müssen dann aber über alle Subs einheitlich vergeben werden.

Ansonsten könnte man auch ein Standard Perl Vorgehen anwenden und wirft eine execption sobald ein Fehler aufgetreten ist.
Den kann man sich ja wie bei jeder andere Perl Funktion abholen, sollte man es wollen. Vorteil, der Code bricht dann in der Sub auch an dieser Stelle ab.

Die vielen Warnings die wir in FHEM heute sehen, sehen wir ja meist deshalb, weil die Verararbeitung in der sub nicht abgebochen wird, sobald ein Fehler gefunden wurde.

**Comment by HomeAutoUser** [comment]
>Die Herausforderung haben wir ja bei all diesen Subs.

Das ist richtig, deswegen sollte die Zielsetzung sein, eine Variante wo wir die Subs alle abdecken.

1) Ich habe mich mal mit dem Vorgehen Returncode beschäftigt auf die schnelle.
Wenn man es so zurück geben würde `retrurn(-1,"TEST TEST TEST 1");`
könnten wir dann folgendes erzielen:
```
2020.04.18 19:37:42 4: sduino_dummy: Parse_MN, Found 2-FSK Protocol id 100 -> Lacrosse mode 1 with match (?^:^9)
2020.04.18 19:37:42 4: sduino_dummy: Parse_MN, Error! method TEST TEST TEST 1
```

Sobald man nun einen Standard festlegt, das der Return nach der Struktur: rcode, Subname, Fehlermessage erfolgt, könnte man den Fehler in die Parse_Sub zurück bringen.

Bsp.:
```
2020.04.18 19:37:42 4: sduino_dummy: Parse_MN, Error! LaCrosse, CRC failed dmsg=ABC
```
2)
>Die RETURN_CODES müssen dann aber über alle Subs einheitlich vergeben werden.

Ich finde, das ist schwierig festzulegen weil man später vielleicht andere Meldungen mal ausgeben möchte.

3)
> Ansonsten könnte man auch ein Standard Perl Vorgehen anwenden und wirft eine execption sobald ein Fehler aufgetreten ist.

Der Begriff sagt mir auf die Schnelle nichts ;-) Klingt aber plausibel.

**Comment by sidey79** [comment]
Ich habe heute die Idee mal commited:
8ca0b451a3713c6d671e4cdfb5b86929ff15a45d

Fehler werden mit croak zurück gegeben.
Da es noch kein Fehlerhandling gibt wird der Programmcode an dieser Stelle abgebrochen.

Wenn ich das weitgehend nichtig bestanden habe, wird durch croak das aufgerufene Script beendet (FHEM in unserem Fall).
Da wäre für Nachricht zu kurz vielleicht carp angebrachter, das beendet das Script nicht.

Auf Seiten des Aufrufs müssten wir noch auf die Fehler reagieren. (Der Test läuft hier auch noch nicht durch!) :(

**Comment by HomeAutoUser** [comment]
Ich habe mir mal https://github.com/RFD-FHEM/RFFHEM/commit/8ca0b451a3713c6d671e4cdfb5b86929ff15a45d angesehen. Das ist das selbige, das ich heute ohne croak umgesetzt hätte.

Ich würde als return immer den Code und dahinter den Test zurück geben. Somit kommt dieser in die Parse Ausgabe.

Was ist der Vorteil von croak? Wir müssen nicht unbedingt dort bei einem Fehler abbrechen, weil ja auch andere ID´s in der Schleife, welche danach folgen, zutreffen und richtig sein könnten. (Wenn ich das Verfahren auf alle Subs beziehe)

**Comment by sidey79** [comment]
Vorteil von croak / carp ist, dass es Standard Perl Verhalten sind.
Wenns ein Fehler vom Entwickler ist, eine sub mit zu wenigen Parameter aufzurufen ist corak schon okay. Das ist ja bei anderen Perl Befehlen ähnlich.

Das mit den Returncodes naja, müsste man nachhalten. Ich bin da auch unschlüssig. carp wirft eine Warning und bricht die Aktion aber nicht ab.
Ich hab mal richard-CZ gefragt ob er da eine gute Idee hat, wie man das zukunftssicher gestalten kann.

**Comment by HomeAutoUser** [comment]
Prinzipiell können wir den Faden schließen oder ist noch was unter gegangen?

Die Änderung wurde vollzogen in Digest.

**Comment by sidey79** [comment]
Schließen. Wenn mir noch mal etwas auffällt können wir ja wieder öffnen :)
