### ISSUE TITLE
dev-r32: negieren der Nachricht für Protokoll 43 (Somfy RTS)

### ISSUE THREAD

**Issue by habeIchVergessen** [RFD-FHEM/RFFHEM#85]
if ($protocol == 43) {
	$data =~ tr/0123456789ABCDEF/FED**BC**A9876543210/;
}

richtig ist
	$data =~ tr/0123456789ABCDEF/FED**CB**A9876543210/;

**Comment by sidey79** [comment]
Erledigt, was für Änderungen an den Daten brauchen wir noch?

**Comment by habeIchVergessen** [comment]
Sehen denn die [npy-Daten](https://forum.fhem.de/index.php/topic,38831.msg450385.html#msg450385) gut aus, die SIGNALduino sendet?
Sonst habe ich erstmal keine Änderungswünsche (warte noch auf Hardware).

**Comment by sidey79** [comment]
die sehen nicht so gut aus finde ich.

Bin auch gerade am nachsehen ob da noch ein Fehler vorliegt.
