### ISSUE TITLE
FHEM crash master / dev_r34 / dev_r35

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#853]
## Expected Behavior
- NO crash FHEM

## Actual Behavior
- crash FHEM

## Steps to Reproduce the Problem

  1. update from dev_r34 or dev_r35
  2. restart FHEM
  3.

## Specifications

```
SDUINO_VERSION            => "v3.4.4_dev+14042020",
Can't use an undefined value as a subroutine reference at ./FHEM/00_SIGNALduino.pm line 3077.
```
--------------
```
SDUINO_VERSION            => "v3.5_dev_06.04",
Can't use an undefined value as a subroutine reference at ./FHEM/00_SIGNALduino.pm line 3055.
```

Es kommt aus bestimmten Umständen zu diesem Crash und ich konnte noch nicht nachvollziehen wieso die "alte" dev_r34 ebenso betroffen ist. Derzeit startet keine von beiden Versionen durch :-(

**Comment by HomeAutoUser** [comment]
@sidey79 & @elektron-bbs 
irgendetwas mit
`$hash->{logMethod}->( )`
knallt durch aber ich bin langsam mit meinem Latein am Ende.

**Comment by elektron-bbs** [comment]
Kann ich zumindest mit v3.4.4_dev+14042020 auf 2 Systemen nicht nachvollziehen. Die anderen Versionen habe ich nicht probiert.

**Comment by HomeAutoUser** [comment]
Das Ganze ist mehr als Merkwürdig.
Ich habe es nun soweit eingrenzen können, das Empfängerdefinitionen vermutlich den Crash bringen was ich mir nicht erklären kann.

**Comment by HomeAutoUser** [comment]
Ich bin an einer Spur.
Bisher funktionierte Jahrelang solche eine Definition

`define nano_433Mhz SIGNALduino /dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-port0@57600`

Sobald diese in der cfg definiert ist, so kommt es zu dem Crash mit der o.g. Fehlermeldung.
Wenn ich diese entferne, startet das System durch.

**Es scheint mir, das sich innerhalb Debian sich etwas verändert hat.** ???

**Comment by HomeAutoUser** [comment]
Von wo kommt die Ausgabe
`/dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-port0: malformed or unsupported URL` wenn ich die DEF ändere. Im Modul finde ich nicht die Bruchteile 'malformed or unsupported URL'.

Das ist der größte MIST das das nicht mehr geht. Sobald ich restarte FHEM ändert sich auf einmal die Schnittstelle und die Devices springen dann.

**Comment by sidey79** [comment]
Das Problem ist, die Angabe wird so als url erkannt :(

**Comment by HomeAutoUser** [comment]
Ich habe auch den BALL zu DIR gelesen
https://forum.fhem.de/index.php/topic,111832.msg1061157.html#msg1061157

:-(

**Comment by HomeAutoUser** [comment]
@sidey79 
https://forum.fhem.de/index.php/topic,109910.msg1061245.html#msg1061245

Wenn man die aktuelle Version von ioDev.pm manuell aus dem SVN kopiert geht es erstmal wieder.
Diese wird vermutlich morgen erst via update Befehl verteilt.

**Comment by sidey79** [comment]
Was ich verstehe:

1. `$hash->{logMethod} = \&main::Log3;` wird gesetzt.
2. `InternalTimer(gettimeofday(), 'SIGNALduino_IdList',"sduino_IdList:$name",0);` wird verzögert aufgerufen
3. `    $ret = DevIo_OpenDev($hash, 0, "SIGNALduino_DoInit", 'SIGNALduino_Connect');`  wird mit dem Pfad aufgerufen und 
4. `SIGNALduino_Connect` wird aus `DevIo_OpenDev` als Callback mit dem Fehler aufgerufen.

Wieso findet der in 2. Referenzierte Aufruf `sduino_IdList` unter `$hash->{logMethod}` keine coderef mehr?

**Comment by sidey79** [comment]
Ok ich denke ich habs gefunden:

https://svn.fhem.de/trac/browser/trunk/fhem/fhem.pl?rev=22120#L2091

Löscht den Hash aber nicht die Timer :(

**Comment by HomeAutoUser** [comment]
Auf jedenfall ist es schön, den Fehler nicht allein zu haben und zu wissen, das man nicht herumsponn :-D

**Comment by HomeAutoUser** [comment]
Da das Verhalten und der Fehler nicht zwangläufig aus dem Modul resultieren aber die Fehler erkannt wurden welche wir verbessern müssen
- https://github.com/RFD-FHEM/RFFHEM/issues/856 (Alle Callbacks, die im Modul verwendet werden robuster gestalten)
- https://github.com/RFD-FHEM/RFFHEM/issues/855 (SIGNALduino_Undef entfernt nicht alle durch internalTimer generierten timer)

so schließe ich den Faden.

Sollte der Fehler auftreten, so kann man Ihn mit der Version
`# $Id: DevIo.pm 22120 2020-06-05 11:52:07Z rudolfkoenig $`
vorerst beheben.
