### ISSUE TITLE
SIGNALduino_Undef  entfernt nicht alle durch internalTimer generierten timer

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#855]
## Expected Behavior

SIGNALduino_Undef   muss alle internalTimer entfernen, die vom Modul gestartet werden

## Actual Behavior

SIGNALduino_Undef   entfernt nur die Timer welche mit dem Argument $hash eröffnet wurden

## Steps to Reproduce the Problem

    
  1.  Timer erzeugen: InternalTimer(gettimeofday(), 'SIGNALduino_IdList',"sduino_IdList:$name",0);       # verzoegern bis alle Attribute eingelesen sind
  2. SIGNALduino_Undef   Aufrufen
  

## Specifications

  - Versionmodul (FHEM Module): 3.4.3

**Comment by HomeAutoUser** [comment]
Hast du schon eine Idee dies zu lösen?

Hilft uns vielleicht dieser Ansatz weiter?
`RemoveInternalTimer($arg, $functionName);`
Wir müssen schauen im Modul welche Funktionsnamen aufgerufen werden und wir müssten dann alle im Undef einmal in einer Schleife durchlaufen lassen?

**Comment by sidey79** [comment]
Ja wir müssten alle Varianten aufrufen die wir mit internalTimer aufgerufen.

**Comment by HomeAutoUser** [comment]
Mir stellt sich soeben die Frage welchen Weg wir da am besten einschlagen.

- wir schreiben alle Einträge aus dem Modul in eine Schleife Bsp: 
```
for my $functionName ( qw(f1 f2 xyz) ) {
	RemoveInternalTimer($arg, $functionName);
}
```
- man überlegt ob man eine Sub schreibt, wo der functionName automatisch in ein Array gefüllt wird und wir zum Schluss in der Undef nur das Array ablaufen lassen müssen

Es ist nur ein Gedanke wie man vielleicht bei einer Erweiterung nicht vergisst die Argumente im Undef zu ergänzen wenn ein Timer hinzukommen sollte. Nur als Anregung.

**Comment by sidey79** [comment]
Ich bin mir da auch nicht so ganz sicher :(

Eigentlich will ich doch nicht daran denken müssen und die FHEM ApI nimmt es mir nicht ab.

Ich denke auch gerade daran, wie teste ich ob wir an alle Timer gedacht haben:

- Wir kopieren vor einem Test das Array für die Timer (hab den Namen gerade nicht parat)
- führen wir nach jedem Test ein Undef aus? Hier bin ich unschlüssig ob das der richtige Weg ist.
- Dann prüfen wir, dass die Timer nicht mehr enthalten sind. Tia, welche ist dann individuell.

Das Zeigt, dass man wieder an alles selbst denken müsste.

Die Arbeit wollen wir aber nicht haben denke ich. Also muss eine Hilfsroutine her.
Vielleicht sogar eine globale:

Anstelle von internalTimer rufen wir eine Hilfsfunktion auf.
Die müsste sich merken, welche Timer Argumente so alles aufgerufen werden.
Im Gerätehash kann man das nicht speichern, denn der könnte ja weg sein.
Hier bietet sich ggf. der %modules Hash an.
Dort hinterlegt man zu jedem Aufruf internalTimer die Argumente, welche für removeInternalTimer nötig sind.
In Undef müsste man die Liste (bezogen auf die zu löschende Definition) abarbeiten.

Diesen Teil könnte man dann in einem gezielten Test verifizieren.

Bis auf den Punkt nicht zu viel löschen erscheint mir das leicht machbar. :)

**Comment by HomeAutoUser** [comment]
Im Prinzip denken wir beide da soeben gleich.
Immer dran denken geht nicht auf Dauer gut und das im Hintergrund uns das Denken abgenommen wird mittels Hilfsfunktion ist sicherer.

Im Forum habe ich die Denkweisen von anderen auch gelesen. Der Konsens daraus bleibt, der MAINTAINER muss denken / handeln.

Was das Testen angeht, so kann ich mir kein Urteil bilden.

Wie denken @elektron-bbs oder @Ralf9 darüber?

**Comment by sidey79** [comment]
Ich habe eine Bibliothek erstellt. Ca. 30 Zeilen Code.

Sie hat zwei Funktionen:

addTimer und removeTimer

Die Bibliothek merkt sich anhand des Namens der Definition was erstellt wurde.
Die muss somit immer mit übergeben werden.
Die Merkliste ist derzeit ein Array.

Tests habe ich angefangen, aber ich hatte noch Schwierigkeiten zu verifizieren, ob ein Timer gelöscht wurde oder eben nicht.


RemoveTimer akzeptiert bis ein bis drei Parameter, welche die Suchparameter auf defName, FuncName und Arg spezifizieren.

Dadurch ist es möglich alle Timer eines Namens zu entfernen oder halt einen spezifischen Aufruf.

Jetzt kommt aber das große aber:

addTimer ruft internalTimer auf und übergibt die Callback direkt.
Wenn der Timer also ausgeführt wurde, bekommt diese Hilfsbibliothek nichts davon mit.

Das ist unschön, weil die Merkliste (Array) dadurch immer nur Einträge dazu bekommt.
Ich könnte jede callback wieder durch die lib schleusen oder die Merkliste als Hash aufbauen.

Die Frage ist jetzt:
Müssen in der Merkliste nur die noch nicht ausgeführten internalTimer stehen oder reicht es aus, wenn je Aufrufkombination ein Eintrag existiert.

**Comment by sidey79** [comment]
@HomeAutoUser 

Hier mal der aktuelle Zwischenstand, der laut Test auch funktioniert wie ich es mir gedacht habe:
https://github.com/fhem/lib_timer

Die Version hat aber noch das Problem, dass die Liste immer nur größer wird

**Comment by HomeAutoUser** [comment]
>Die Frage ist jetzt:
Müssen in der Merkliste nur die noch nicht ausgeführten internalTimer stehen oder reicht es aus, wenn je Aufrufkombination ein Eintrag existiert.

Ich formuliere es mal so, in der Liste müssten die Timer vorhanden sein, welche gerade gestartet wurden. Es macht keinen Sinn, dort Timer mit aufzunehmen welche nicht im Hintergrund laufen.

Wenn wir von einer intelligenten Lösung ausgehen, dann müssen die Timer gelöscht werden welche gerade laufen um nicht unnötig alle Timervarianten im Löschprozess ablaufen zu lassen.

**Comment by sidey79** [comment]
@HomeAutoUser 

Naja, bin nicht ganz zu 100% deiner Meinung.

Mal angenommen, wir machen die Variante, der Entwickler muss mitdenken, dann macht der Entwickler vermutlich in Undef einen Rundumschlag für alle Timer die jemals gestartet werden:

https://github.com/RFD-FHEM/RFFHEM/issues/855#issuecomment-640009671

Da er ja nicht weiss, ob ein Timer läuft, versucht er also auch Timer zu löschen die nicht laufen. Das macht nichts, ist einfach nur ein bisschen ineffizient. Dafür muss er sich das halt nicht merken.

In der simplen Variante, macht die Hilfsroutine jetzt genau das gleiche. Jeder Timer der einmal angelegt wurde, wird beim Aufruf von removeTimer  entfernt.

Habe ich 10 verschiedene Timeraufrufe in meinem Modul wären das dann 10 Aufrufe von RemoveInternalTimer, egal ob der Timer läuft oder nicht.

Wenn wir jetzt nur Timer entfernen wollen die auch noch nicht ausgeführt wurden, dann brauchen wir Hilfsmittel.

Ich bin nicht abgeneigt diese Hilfsmittel zu entwickeln, nur welche Variante ist hier zu wählen?
Bei jeder Callback einen zusätzlichen Aufruf um die Merkliste (array) zu bereinigen?

Oder beim Hinzufügen abgelaufene löschen oder halt einfach am Ende ein paar versuche  zu löschen die nicht mehr existieren.

Man könnte natürlich auch einen internalTimer aufsetzen der z.B. alle 300 Sekunden die Liste auf verwaiste Elemente absucht :)

**Comment by HomeAutoUser** [comment]
1)
Ich habe heute noch einmal überlegt oder wir haben ein Brainstorming abgehalten. Kannst du den Fall erläutern wieso es zu dem Crash kam. Welche Rolle spielt der Timer im Modul bei uns?

Es sollte doch einfach sein, das erst ein Timer bei uns im Modul gestartet wird wenn das ok von ioDEV kam. Irgendwie versuche ich gedanklich dort das Ganze 100% nachzuvollziehen.

2) 
>In der simplen Variante, macht die Hilfsroutine jetzt genau das gleiche. Jeder Timer der einmal angelegt wurde, wird beim Aufruf von removeTimer entfernt.

>Habe ich 10 verschiedene Timeraufrufe in meinem Modul wären das dann 10 Aufrufe von RemoveInternalTimer, egal ob der Timer läuft oder nicht.

Ich denke das sollte eigentlich ausreichen.

**Comment by sidey79** [comment]
Zu 1.
Define wurde aufgerufen und hat einen Timer für die Funktion SIGNALduino_IdList  gestartet.
DevIo_OpenDev hat eine Fehlermeldung zurück gegeben, und SIGNALduino_Define hat diese Fehlermeldung an fhem core zurück geliefert.
Der Code hat die Zuordung in %defs{<NAME>} gelöscht.

Fhem core hat nach Ablauf von 1 Sekunde (Timer) die Funktion SIGNALduino_IdList  aufgerufen. Die hat versucht den $hash über $defs{$name} zu bekommen. Hier wurde undef geliefert und der Aufruf $hash->{logMethod} führe dann zu dem crash.


Daraus habe ich nun gelernt

1) trau nie darauf, dass dir nicht jemand was an Variablen weglöscht
2) lösche alle Timer wenn undef aufgerufen wird,

**Comment by HomeAutoUser** [comment]
Wieso werden die Timer nicht erst gestartet wenn die Rückmeldung von DevIo_OpenDev eintrifft?
Wenn diese fehl schlägt müsste doch auch kein Timer angelegt werden welcher einen Fehler erzeugen kann. Oder sehe ich das falsch?

**Comment by sidey79** [comment]
DevIo_OpenDev sollte keinen Fehler zurück liefern.
Wir schweifen auch etwas von diesem issue ab :)

Der Timer wird übrigens gestartet, weil es für die Abarbeitung nicht von Belang ist, ob eine Verbindung zum physischen Gerät aufgebaut wurde oder nicht.

**Comment by HomeAutoUser** [comment]
>Wir schweifen auch etwas von diesem issue ab :)

Es ging mir nur um das Verständnis und daher hinterfragte ich das Ganze.
