### ISSUE TITLE
Protokoll Oregon für THGR122N THGRN132N

### ISSUE THREAD

**Issue by frank242** [RFD-FHEM/RFFHEM#86]
Hallo zusammen,

für die Oregon Sensoren wird leider kein Eintrag erzeugt.

Danke vorab
Frank

Arduino nano mit CC1101

Oregon Thermo/HydroSenoren THGR122N   THGRN132N

sduino: Firmwareversion: V 3.2.0-b24 SIGNALduino - compiled at May 14 2016 00:06:40

2016.05.19 10:56:28 4: sduino/msg READ: MC;LL=-1016;LH=1007;SL=-489;SH=450;D=AAAAAAAACCB0;C=485;L=45;
2016.05.19 10:56:28 4: sduino/msg READ: MC;LL=-958;LH=1014;SL=-504;SH=468;D=A99A9A9A56699;C=493;L=52;
2016.05.19 10:57:11 4: sduino/msg READ: MU;P0=454;P3=11664;P4=-1058;P5=916;P7=-553;D=3454545454545454545454545454545457040757040;CP=5;
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.05.19 10:57:11 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.05.19 10:57:36 4: sduino/msg READ: MC;LL=-1137;LH=857;SL=-577;SH=383;D=55A6AA569A9AAAAA4;C=413;L=66;
2016.05.19 10:57:36 4: sduino: Found manchester Protocol id 10 clock 413 -> OSV2o3
2016.05.19 10:57:36 4: sduino: Found manchester Protocol id 11 clock 413 -> AS
2016.05.19 10:57:54 4: sduino/msg READ: MU;P0=-604;P1=472;P3=-436;P4=973;P6=-1033;D=4464646464646464646464646464646464016134;CP=4;
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 34 -> unknown34 matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.05.19 10:57:54 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2016.05.19 10:58:14 4: sduino/msg READ: MC;LL=-1071;LH=937;SL=-556;SH=397;D=55555555996A659AAA4;C=444;L=74;
2016.05.19 10:58:14 4: sduino: Found manchester Protocol id 10 clock 444 -> OSV2o3
2016.05.19 10:58:14 4: sduino: OSV2 protocol detected: preamble_pos = 32
2016.05.19 10:58:14 4: sduino: Found manchester Protocol id 12 clock 444 -> Hideki protocol
2016.05.19 10:58:53 4: sduino/msg READ: MU;P0=931;P1=382;P3=-1054;P5=-538;D=130303030303030303031505131505130303150513150;CP=1;
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 16 -> Dooya shutter matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.05.19 10:58:53 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate

**Comment by sidey79** [comment]
Wie hast Du einen cc1101 mit dem Signalduino zum Laufen gebracht?

**Comment by frank242** [comment]
Hallo zurück,

ich hoffe aus dem Flash.log wird ersichtlich wie ich den Signaldino geflasht habe.
Das ganze habe ich über die Fhem Oberfläche gemacht und sonst keine weiteren Anpassungen vorgenommen.

Gruß
Frank
 
`root@musik:/opt/fhem/log# nano SIGNALduino-Flash.log 

  GNU nano 2.2.6                      File: SIGNALduino-Flash.log                                                   

           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom        65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
           flash         65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           lock           0     0     0    0 no          1    0      0  4500  4500 0x00 0x00
           calibration    0     0     0    0 no          1    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : Arduino
         Description     : Arduino
         Hardware Version: 2
         Firmware Version: 1.16
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us
avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "./FHEM/firmware/SIGNALduino_nano328.hex"
avrdude: input file ./FHEM/firmware/SIGNALduino_nano328.hex auto detected as Intel Hex
avrdude: writing flash (19198 bytes):

Writing | ################################################## | 100% 5.25s

avrdude: 19198 bytes of flash written
avrdude: verifying flash memory against ./FHEM/firmware/SIGNALduino_nano328.hex:
avrdude: load data flash data from input file ./FHEM/firmware/SIGNALduino_nano328.hex:
avrdude: input file ./FHEM/firmware/SIGNALduino_nano328.hex auto detected as Intel Hex
avrdude: input file ./FHEM/firmware/SIGNALduino_nano328.hex contains 19198 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 3.90s

avrdude: verifying ...
avrdude: 19198 bytes of flash verified

avrdude done.  Thank you.

**Comment by sidey79** [comment]
Ich meinte eher, wie Du den cc1101 Empfänger angebunden hast.
Kann doch ohne Modifikationen an der Firmware nicht funktionieren.

**Comment by frank242** [comment]
Nene, an der Firmware habe ich garantiert nichts geändert.
Habe den CUL wie im Wiki
http://www.fhemwiki.de/wiki/Selbstbau_CUL
zusammengebaut .
Danach in FHEM von der Standardfirmware zu SIGNLduino geflasht - dachte ich jedenfalls.
Gruß
Frank

**Comment by Ralf9** [comment]
Wie sidey schon geschrieben hat, kann der cc1101 Empfänger nicht ohne Modifikationen an der Firmware am SIGNALduino funktionieren
Für den SIGNALduino wird ein Superheterodyne Empfänger benötigt.
z.B.:
http://www.ebay.de/itm/433Mhz-Superheterodyne-Wireless-Receiver-Module-for-Arduino-ARM-AVR-/401047720475?hash=item5d604e921b:g:9wsAAOSwF0NXLVDA
oder
https://www.pilight.org/shop/#sender

Gruß Ralf

**Comment by frank242** [comment]
@sidey79 
@Ralf9 
Danke für die Hilfe.

Werde dann mal beim Chinamann anrufen ;-)

Gruß
Frank

**Comment by frank242** [comment]
Kurzer Nachtrag:
Nachdem der  Superheterodyne Empfänger angeschlossen war funktioniert es auch mit den Oregon Sensoren;-)

Gruß
Frank
