### ISSUE TITLE
Protokoll für Technoline WS9180

### ISSUE THREAD

**Issue by wexstorm** [RFD-FHEM/RFFHEM#87]
Hallo,

ist es möglich für den Technoline Temperatursender (TX 104) ebenfalls ein Modul anzubieten. Bin gerne bereit Daten zu loggen und auszuwerten. Komme nur irgendwie gerade nicht weiter.
Es heisst zwar, dass diese Teile mit den Lacrosse Geräten technisch baugleich sind - das kann ich aber anhand der Frequenzen (915 / 433) nicht bestätigen.

Wäre echt super!

**Comment by sidey79** [comment]
Was empfängt der Signalduino denn?

**Comment by wexstorm** [comment]
Hi,

absolut garnichts! Meine Funksteckdosen-Fernbedienungen werden alle als
UNKNOWN geführt (also es tut zumindest da irgendwas) - das Technoline Gerät
taucht überhaupt nicht auf.
Ich hatte Erfolg mit einem Arduino-Script (sollte eigentlich für Tchibo
sein), also zumindest kamen minütlich die selben Bitfolgen.

Vielen Dank!

-- 
Björn Plutka
Sent with Airmail

Am 2. Juni 2016 um 20:46:45, sidey79 (notifications@github.com) schrieb:

Was empfängt der Signalduino denn?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RFD-FHEM/RFFHEM/issues/87#issuecomment-223385286>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAne17ZKwn8CGIofvA0a8sf3Q-P6KLRNks5qHyUUgaJpZM4IszwW>
.

**Comment by wexstorm** [comment]
Ach ja: hier der Code, der irgendwas zurückzugeben scheint:
https://ccblog.de/2012/04/01/garagentoroffner-mit-dem-arduino/ (weiter
unten: Liest dieses komische Tchibo-Wetterdingens per 433MhZ aus.).

Viele Grüße

-- 
Björn Plutka
Sent with Airmail

Am 2. Juni 2016 um 20:56:05, Björn Plutka (wexstorm@googlemail.com) schrieb:

Hi,

absolut garnichts! Meine Funksteckdosen-Fernbedienungen werden alle als
UNKNOWN geführt (also es tut zumindest da irgendwas) - das Technoline Gerät
taucht überhaupt nicht auf.
Ich hatte Erfolg mit einem Arduino-Script (sollte eigentlich für Tchibo
sein), also zumindest kamen minütlich die selben Bitfolgen.

Vielen Dank!

-- 
Björn Plutka
Sent with Airmail

Am 2. Juni 2016 um 20:46:45, sidey79 (notifications@github.com) schrieb:

Was empfängt der Signalduino denn?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RFD-FHEM/RFFHEM/issues/87#issuecomment-223385286>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAne17ZKwn8CGIofvA0a8sf3Q-P6KLRNks5qHyUUgaJpZM4IszwW>
.

**Comment by wexstorm** [comment]
Genau,

verbose 4
und die Standardfirmware die dabei war: V 3.2.0-b24 SIGNALduino - compiled
at May 14 2016 00:06:40

Viele Grüße

P.S.: Hier mal ein paar Codes die ich gerade mit dem „Tchibo-Tool“
ausgelesen habe (ich nehme an, es fehlen ein paar Bit - ich schau da grad
nach):
23.8
00101110 10000000 11111110 1100

25.5
00101110 10000000 111111110011

25.4
00101110 10000000 111111101100

25.3
00101110 10000000 111111011110

25.2
00101110 10000000 111111000001

25.1
00101110 10000000 111110111011

25.0
00101110 10000000 111110100100

-- 
Björn Plutka
Sent with Airmail

Am 2. Juni 2016 um 21:09:00, sidey79 (notifications@github.com) schrieb:

Hast du mit Verbose 4 am sduino geloggt und es kommt nichts rein, wenn der
Sensor etwas sendet?

Mit welcher Firmware hast Du es probiert?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RFD-FHEM/RFFHEM/issues/87#issuecomment-223391506>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAne14-Shu6HF3VYCRx283uyi_6p9IJ4ks5qHypLgaJpZM4IszwW>
.

**Comment by wexstorm** [comment]
So, hier nochmal die 32-Bit-Folgen:
24.7
00101110 10000000 1111011100000110

24.5
00101110 10000000 1111010000101011

24.2
00101110 10000000 1110101011000010

23.9
00101110 10000000 1110111101011111

23.8
00101110 10000000 1110111010101011

23.7
00101110 10000000 1110110110000110

-- 
Björn Plutka
Sent with Airmail

Am 2. Juni 2016 um 21:15:39, Björn Plutka (wexstorm@googlemail.com) schrieb:

Genau,

verbose 4
und die Standardfirmware die dabei war: V 3.2.0-b24 SIGNALduino - compiled
at May 14 2016 00:06:40

Viele Grüße

P.S.: Hier mal ein paar Codes die ich gerade mit dem „Tchibo-Tool“
ausgelesen habe (ich nehme an, es fehlen ein paar Bit - ich schau da grad
nach):
23.8
00101110 10000000 11111110 1100

25.5
00101110 10000000 111111110011

25.4
00101110 10000000 111111101100

25.3
00101110 10000000 111111011110

25.2
00101110 10000000 111111000001

25.1
00101110 10000000 111110111011

25.0
00101110 10000000 111110100100

-- 
Björn Plutka
Sent with Airmail

Am 2. Juni 2016 um 21:09:00, sidey79 (notifications@github.com) schrieb:

Hast du mit Verbose 4 am sduino geloggt und es kommt nichts rein, wenn der
Sensor etwas sendet?

Mit welcher Firmware hast Du es probiert?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RFD-FHEM/RFFHEM/issues/87#issuecomment-223391506>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAne14-Shu6HF3VYCRx283uyi_6p9IJ4ks5qHypLgaJpZM4IszwW>
.

**Comment by wexstorm** [comment]
Dumm von mir:

habedie Codierung doch noch selbst rausgefunden:
Beispiel:
23.7
00101110 10000000 11101101 10000110

00101110 Hauscode?
10000000 Gerätecode?
11101101 Temperatur * 10 (hier: 237)
10000110 Evtl. Feuchtesensor/Checksum?

Wäre es möglich das in Signalduino umzusetzen? Wenn Du mir kurz sagst wie und wo würde ich das auch wohl übernehmen. (evtl. passt ja schon ein anderer Algorithmus und muss nur etwas angepasst werden?!)

**Comment by sidey79** [comment]
Solange wir kein Signal empfangen, lässt sich nichts mit dem Protokoll umsetzen.

**Comment by wexstorm** [comment]
Kann ich denn noch irgendwas tun? Würde den Sender gerne in meine Hausautomatisierung einbauen. Und basteln tu ich auch gerne.

**Comment by sidey79** [comment]
Tia, das wundert mich, dass der Signalduino kein Signal erkennt, aber ein anderer Sketch kann es.

Im verlinkten Beitrag habe ich leider nichts gefunden, wie das Signal aufgebaut ist.


Von daher würde ich gerne besser verstehen, was genau hast du gemacht und was taucht in den Logs auf?

Angefangen bitte beim Hardware Setup. Hast Du in beiden Fällen den gleichen Arduino und Empfänger genutzt.

Empfängt der Signalduino überhaupt was.
Vielleicht empfängt er das Signal auch, aber Du konntest es nicht zuweisen? ...

**Comment by wexstorm** [comment]
Hi mal wieder, 
ich habe mir in der Zwischenzeit einen anderen Sensor besorgt, da der technoline nur och Müll gemessen hat :(
Ich möchte aber, wenn Du Interesse an dem Sensor hast, dennoch einiges beisteuern (Werte auslesen usw.).

Hier der Link zum anderen Sensor mit Codierung ([Link](https://github.com/RFD-FHEM/RFFHEM/issues/88))

**Comment by wexstorm** [comment]
Ich muss alles zurücknehmen... das Gerät wurde heute beim Testen als AURIOL_250 gefunden und angelegt. Dennoch ist die Qualität des Sensors unterirdisch.
