### ISSUE TITLE
RGB LED Controller

### ISSUE THREAD

**Issue by copystring** [RFD-FHEM/RFFHEM#871]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: Not sure. Bought this from https://www.otto.de/ The controller says furnika
  - model name: RGB LED Controller
  - pictures of the device / the board (very helpful)
https://imgur.com/a/LD7xDse

  
## Specifications 

  - Microcontroller:
  - Version (Firmware): version: V 3.4.0-dev SIGNALduino cc1101 (chip CC1101) - compiled at Feb 15 2020 23:23:10
  - Versionmodul (FHEM Module): 3.4.3

Log: https://pastebin.com/m0JPa534

This remote for the couch has 10 buttons.
On/off, mode+, mode-, speed+, speed-, demo, color+,color-,brightness+,brightness-

**Comment by HomeAutoUser** [comment]
Hello,
thanks for this log.

Can you push all buttons and wait some seconds or a minutes to switch the other button.
We need all messages from all buttons to compare it.

If you switch to other button please mark what for button you push.

Thanks :)

**Comment by copystring** [comment]
Sure.
Pressed every button twice for about 1 second.
[rgb_sofa_mode-.log](https://github.com/RFD-FHEM/RFFHEM/files/4933572/rgb_sofa_mode-.log)
[rgb_sofa_mode+.log](https://github.com/RFD-FHEM/RFFHEM/files/4933573/rgb_sofa_mode%2B.log)
[rgb_sofa_on_off.log](https://github.com/RFD-FHEM/RFFHEM/files/4933574/rgb_sofa_on_off.log)
[rgb_sofa_speed-.log](https://github.com/RFD-FHEM/RFFHEM/files/4933575/rgb_sofa_speed-.log)
[rgb_sofa_speed+.log](https://github.com/RFD-FHEM/RFFHEM/files/4933576/rgb_sofa_speed%2B.log)
[rgb_sofa_brightness-.log](https://github.com/RFD-FHEM/RFFHEM/files/4933577/rgb_sofa_brightness-.log)
[rgb_sofa_brightness+.log](https://github.com/RFD-FHEM/RFFHEM/files/4933578/rgb_sofa_brightness%2B.log)
[rgb_sofa_color-.log](https://github.com/RFD-FHEM/RFFHEM/files/4933579/rgb_sofa_color-.log)
[rgb_sofa_color+.log](https://github.com/RFD-FHEM/RFFHEM/files/4933580/rgb_sofa_color%2B.log)
[rgb_sofa_demo.log](https://github.com/RFD-FHEM/RFFHEM/files/4933581/rgb_sofa_demo.log)

**Comment by elektron-bbs** [comment]
Die Logs sehen schon mal gut aus. Das sollte kein Problem darstellen, diese Fernbedienung einzubinden.

Hat die Fernbedienung irgend eine Bezeichnung?
Wir können sie ja schlecht "LED-Sofa-Controller" nennen :-)

**Comment by copystring** [comment]
Das freut mich.

Das ist die Fernbedienung.: https://fccid.io/2ATDY-AC-P901/Internal-Photos/INT-PHO-4303820
Oder zumindest das PCB dazu. Meine sieht außen etwas anders aber das PCB sieht gleich aus. Das Modell ist anscheinend eine AC-P901
Das ist meine dort ist aber keine Bezeichnung vorhanden.: 
![image](https://user-images.githubusercontent.com/1298861/87814075-5f098b80-c863-11ea-89fb-297e7f9e4457.png)

**Comment by elektron-bbs** [comment]
Ich habe mir die Logs jetzt mal etwas genauer angesehen.

Sämtliche Nachrichten werden mit MS protocol id 3 zuverlässig dekodiert und an das Modul 10_IT.pm übergeben. Dort werden sie allerdings nicht weiter verarbeitet (Code 1001 not supported by IT_1527x98240).

Ich bin mir jetzt nicht sicher, ob wir das bei uns einbauen wollen, oder ob es nicht besser in das Modul 10_IT.pm gehört.
@sidey79 @HomeAutoUser  - Was meint ihr dazu?

Maintainer wären dancer0705/bjoernh und das passende Forum https://forum.fhem.de/index.php/board,24.0.html. In letzter Zeit hatte sich auch mal @Ralf9 darum gekümmert.

**Comment by sidey79** [comment]
Das Problem mit dem 10_IT Modul dürften die Befehle sein. Das bietet nur on/Off und DIM.

Ich würde aber mal abwarten, was der Modulautor dazu sagt.

**Comment by HomeAutoUser** [comment]
Man könnte dem Modulautor einen Vorschlag machen. Eine doppelte Einarbeitung, das bei IT es dispatched und ggf im SD_UT Modul wäre nicht günstig denke ich.

Ich werde mal den Maintainer kontaktieren. Damals gab es ja schon als Angebot das Modul zu übernehmen.

**Comment by Ralf9** [comment]
Warum so umständlich? Dafür gibts doch das Attribut "userV1setCodes"
https://fhem.de/commandref_DE.html#userV1setCodes
Das kann in der commandref wahrscheinlich besser beschrieben werden, da darf jeder gerne Vorschläge machen.

`attr IT_1527x98240 userV1setCodes modeMinus:1011 modePlus:0101 on_off:0001 speedMinus:0111`
Die restlichen Tasten müssen noch ergänzt werden.

Die entspechenden 4 Bit Codes stehen im log

> Code **0111** not supported by IT_1527x98240.

**Comment by elektron-bbs** [comment]
Danke, so müsste es funktionieren. Ich habe das mal noch ergänzt:

```
attr IT_1527x98240 userV1setCodes Brightness_Minus:1111 Brightness_Plus:1100 Color_Minus:1101 Color_Plus:1010 Demo:1000 Mode_Minus:1011 Mode_Plus:0101 On_Off:0001 Speed_Minus:0111 Speed_Plus:1001
attr IT_1527x98240 ITclock 400
```

**Comment by copystring** [comment]
Das habe ich bei mir so eingetragen. Wenn ich die knöpfe an der Fernbedienung drücke erkennt das fhem sauber und zeigt an welchen Knopf ich gedrückt habe.
Wenn ich versuche die Befehle über fhem auszulösen werden diese genau so angezeigt aber die Farben am Sofa ändern sich nicht. Keine der Funktionen funktioniert.

**Comment by elektron-bbs** [comment]
Hast du auch das Attribut "ITclock " gesetzt?

**Comment by copystring** [comment]
Ja. auf 400.

**Comment by elektron-bbs** [comment]
Tja, du könntest noch folgendes versuchen:

1. beim SIGNALduino die Sendeleistung erhöhen (cc1101_patable)
2. bei IT_1527x98240 die Anzahl der Wiederholungen erhöhen (ITrepetition)
3. Abstand zwichen SIGNALduino und LED-Controller verringern

**Comment by copystring** [comment]
1. habe ich auf 10 dbm gesetzt und 2. auf 10. Ohne erfolg.
3. wird schwer. Das Sofa kann ich nicht mal eben neben dem server im Heizungsraum stellen und den server nicht mal eben neben das Sofa (meine Frau tötet mich xD)
Vielleicht kann ich bei gelegenheit einen rpi mit fhem und signalduino neben dem sofa zum testen parken.

**Comment by elektron-bbs** [comment]
Mhmm, muss ich mir das so vorstellen, das zwischen Server und LED-Controller ein oder mehr Decken möglichst noch aus Stahlbeton sind?
Kommen denn die Signale der Fernbedienung vom Sofa aus gesendet am Server an?

Evtl. reicht ja auch ein SIGNAL-ESP im Wohnzimmer, der die Signale per WLAN in das Netzwerk bringt.

**Comment by copystring** [comment]
Ja. da ist eine Decke aus Stahlbeton plus mehrere Wände.
Trotzdem kommen die Signale von der Fernbedienung oben an. Auch dann, wenn ich diese direkt beim Sofa benutze. Ist also genau so weit weg wie das Sofa mit LED-Controller selbst.

**Comment by elektron-bbs** [comment]
Du könntest uns bitte mal noch RAW-MSG im MU-Format hochladen, indem du bei deinem SIGNALduino "syncedMS" mit folgendem Befehl ausschaltest:

`set SIGNALduino disableMessagetype syncedMS`

Die Ausgabe von:

`get SIGNALduino config`

sollte dann so aussehen:

`config: MS=0;MU=1;MC=1;Mred=1`

Es reicht dann ein Log einer Taste der Fernbedienung. Die RAW-MSG müssen dann mit "MU" beginnen, etwa wie diese:

`MU;P0=17703;P1=-423;P2=819;P3=356;P4=-885;D=0121212121212121212134342121213421212121342121342134342121343434212121343421342134342121213434213421342121343434343421343
`

**Comment by copystring** [comment]
Aaaaalso. Ich hatte zufälligerweise noch einen fertig gelöteten cc1101 auf einem esp8266 hier liegen.
Geflashed und eingebunden. Neben dem Sofa angeschlossen und es funktioniert nun. Cool!

Die Befehle nun zu modifizieren ginge aber nicht oder? Um z.B. nicht zwischen den Farben zu wechseln sondern eine Farbe direkt einzustellen.


Sind die RAW-MSG im MU-Format jetzt noch relevant? Kann ich gerne zusätzlich hochladen.

**Comment by elektron-bbs** [comment]
Die Nachrichten im RAW-Format sind dann nicht mehr notwendig, da das Senden ja prinzipiell funktioniert.
Ob der LED-Controller noch andere Befehle versteht, die die Fernbedienung nicht unterstützt, kannst nur du herausfinden.

**Comment by elektron-bbs** [comment]
Ich schließe dieses Issue. Falls es doch noch einer Diskussion bedarf, bitte wieder öffnen.
