### ISSUE TITLE
SVN Aktualisieren:

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#875]
- [x] 00_SIGNALDuino.pm 
- [x] 10_FS10.pm
- [x] 14_SD_BELL.pm
- [x] 14_SD_UT.pm
- [x] 14_SD_WS.pm
- [x] 14_SD_WS09.pm
- [x] 90_SIGNALduino_un.pm
- [x] lib/SD_ProtocolData.pm

@homeautouser:
Ich wäre für meinen Teil durch. Machst Du noch deine beiden?

**Comment by HomeAutoUser** [comment]
Jop, werde ich machen und hier Vollzug melden ;)

**Comment by HomeAutoUser** [comment]
Wir haben fertig :-)
