### ISSUE TITLE
Verweise / Hinweise bezüglich Thematiken im Forum

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#885]
Dieses Issues dient dem direkten Hinweis an alle oder einzelne Personen wenn im Forum etwas verwiesen wird.
Manchmal werden
- Fehler
- Meinungen
- Äußerungen 
- ....

im Forum geschrieben, welche manchmal aufgrund der Antworten oder vielen Thematiken unter gehen.

Dies soll helfen, direkt darauf zu verweisen.

**Comment by HomeAutoUser** [comment]
@sidey79 
bitte vielleicht mal hierauf schauen und bewerten
https://forum.fhem.de/index.php/topic,113268.msg1076170.html#msg1076170

Ja, es gab da mal einen Workaraound.

**Comment by sidey79** [comment]
Gehört zu #823

**Comment by sidey79** [comment]
@HomeAutoUser 
Den können wir h schließen oder?

**Comment by HomeAutoUser** [comment]
Wenn du Ordnung schaffen möchtest ja. Sollte ein spezieller Fall sein, so machen wir ein separates Issues auf.
