### ISSUE TITLE
Eurochron Zusatzsensor für EFS-3110A

### ISSUE THREAD

**Issue by alipu-001** [RFD-FHEM/RFFHEM#889]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: Eurochron (verkauft von Conrad)
  - model name: EFS-3110A
  - pictures of the device / the board (very helpful)

  
## Specifications 

  - Microcontroller: Signalduino
  - Version (Firmware): V 3.4.0-dev_20200707 SIGNALduino cc1101 (chip CC1101) - compiled at Jul 10 2020 23:26:18
  

  - Versionmodul (FHEM Module): v3.4.4_dev+14042020
  

Habe eine Eurochron Wetterstation von Conrad, die mit 3  EFTH-800 Sensoren geliefert wurde. Diese werden vom Signalduino erkannt und die entsprechenden Devices und Logs werden angelegt. Da alles so gut lief, habe ich weitere Sensoren gekauft. Diese sahen äußerlich genauso aus wie die alten und ließen sich problemlos mit der Basisstation verbinden. Der Signalduina hat auch das entsprechende Device angelegt, aber leider nichts in den Log geschrieben. Nach Reset (neue ID am Sensor) gab es dann einen Eintrag im Log, dann war wieder Schluss. 

Im Log findet man dann immer die folgenden Einträge 

>SD_WS_Parse 3F94519855C7 protocolid 27 (EFTH-800) - ERROR prematch
Dispatch, W27#3F94519855C7, Dropped due to short time or equal msg

(Der Code der Message variiert natürlich)

Daraufhin habe ich mit den Sensor genauer angesehen und ihn mit dem EFTH-800 verglichen. Folgende Unterschiede
- Der Name ist jetzt EFS-3110A
- Es ist eine Funkuhr mit eingebaut. Laut Anleitung soll zusätzlich die Zeit an die Basistation übermittelt werden.

Ich denke das letzte bereitet die Probleme.

Hier der Log:
>2020.08.22 14:45:08 4: sduino: Read, msg READredu: MU;P0=-237;P1=505;P3=269;P4=-464;P5=-4864;P6=729;P7=-728;D=010101010101034341034103434341034103434341034101034343434343410341010343434103410343410343435676767673434101010101010103434103410343434103410343434103410103434343434341034101034343410341034341034343;CP=3;R=253;
2020.08.22 14:45:08 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:45:08 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94516058A4 length 48 dispatch(1/4) RSSI = -75.5
2020.08.22 14:45:08 4: sduino: SD_WS_Parse protocol 27, rawData 3F94516058A4
2020.08.22 14:45:08 4: sduino: SD_WS_27 Parse msg 3F94516058A4, CRC a4
2020.08.22 14:45:08 4: sduino: SD_WS_Parse decoded protocol-id 27 (EFTH-800), sensor-id F94
2020.08.22 14:45:17 4: sduino: Read, msg READredu: MU;P0=-22480;P1=497;P2=-1030;P3=1463;D=012121212121212123212323212123232323212123232321232323232123212123232121232323232123212123212123;CP=1;R=245;
2020.08.22 14:45:51 4: sduino: Read, msg READredu: MU;P0=-21488;P1=1336;P2=-984;P3=557;P4=-27912;D=01212121232123212121212121212323212323232123232321232123232121232123232321232123212321234121212123212321212121212121232321232323212323232123212323212123212323232123212321232123;CP=3;R=63;
2020.08.22 14:45:52 4: sduino: Read, msg READredu: MU;P0=-13316;P1=1345;P2=-978;P3=562;P4=-27704;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=62;
2020.08.22 14:46:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:46:05 4: sduino: Read, msg READredu: MU;P0=-6640;P1=487;P2=-1040;P3=1457;D=012121212121212123212323212123232323212123232321232323232123212323232121232323232321232323232123;CP=1;R=245;
2020.08.22 14:46:07 4: sduino: Read, msg READredu: MU;P0=-229;P1=517;P2=257;P3=-471;P4=-4860;P5=762;P6=-708;D=010101010101023231023102323231023102323231023101023232323232310231010232323102310232310232324565656562323101010101010102323102310232323102310232323102310102323232323231023101023232310231023231023232;CP=2;R=15;
2020.08.22 14:46:07 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:46:07 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94516058A4 length 48 dispatch(1/4) RSSI = -66.5
2020.08.22 14:46:07 4: sduino: SD_WS_Parse protocol 27, rawData 3F94516058A4
2020.08.22 14:46:07 4: sduino: SD_WS_27 Parse msg 3F94516058A4, CRC a4
2020.08.22 14:46:07 4: sduino: SD_WS_Parse decoded protocol-id 27 (EFTH-800), sensor-id F94
2020.08.22 14:46:48 4: sduino: Read, msg READredu: MU;P0=-20484;P1=1338;P2=-982;P3=559;P4=-28004;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123234121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:46:49 4: sduino: Read, msg READredu: MU;P0=-13328;P1=1336;P2=-991;P3=549;P4=-27712;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=63;
2020.08.22 14:46:52 4: sduino: Read, msg READredu: MU;P0=-32001;P1=17540;P2=-1448;P3=473;P4=-1057;P5=1455;D=01234343434343434345434545434345454545434345454543454545454345434545454343454545454543454545454345;CP=3;R=246;
2020.08.22 14:47:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:47:06 4: sduino: Read, msg READredu: MU;P0=-211;P1=524;P2=279;P3=-454;P4=-4856;P5=754;P6=-705;D=010101010101023231023102323231023102323231023101023232323232310231010232323102310232310232324565656562323101010101010102323102310232323102310232323102310102323232323231023101023232310231023231023232;CP=2;R=26;
2020.08.22 14:47:06 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:47:06 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94516058A4 length 48 dispatch(1/4) RSSI = -61
2020.08.22 14:47:06 4: sduino: SD_WS_Parse protocol 27, rawData 3F94516058A4
2020.08.22 14:47:06 4: sduino: SD_WS_27 Parse msg 3F94516058A4, CRC a4
2020.08.22 14:47:06 4: sduino: SD_WS_Parse decoded protocol-id 27 (EFTH-800), sensor-id F94
2020.08.22 14:47:18 4: sduino: Read, msg READredu: MU;P0=112;P1=-2003;P2=433;P3=-4070;P4=-92;D=0121212123212121212121212321212121212121212304;CP=2;R=218;
2020.08.22 14:47:18 4: sduino: Read, msg READredu: MU;P0=208;P1=-4077;P2=459;P3=309;P4=-1947;P5=-1020;D=01213421212424243421243424242424242134242424242425;CP=2;R=211;
2020.08.22 14:47:41 4: sduino: Read, msg READredu: MU;P0=-24380;P1=465;P2=-1045;P3=1466;D=012121212121212123212323212123232323212123232321232323232123212323232121232323232321232323232123;CP=1;R=243;
2020.08.22 14:47:45 4: sduino: Read, msg READredu: MU;P0=-7036;P1=1327;P2=-996;P3=546;P4=-28004;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123234121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:47:46 4: sduino: Read, msg READredu: MU;P0=-21396;P1=1334;P2=-983;P3=550;P4=-27700;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=63;
2020.08.22 14:48:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:48:04 4: sduino: Read, msg READredu: MU;P0=280;P1=-451;P2=529;P4=-4839;P5=755;P6=-710;P7=-200;D=70127272727272727010127012701270101270127272701012727270101010101010101012701270101270127010127012727012701010127272727270101270456565656010127272727272727010127012701010127012701010127270101272701010101270127012701272727010101272727045656565627012727272;CP=0;R=26;O;
2020.08.22 14:48:04 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:48:04 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94519855C7 length 48 dispatch(1/4) RSSI = -61
2020.08.22 14:48:04 4: sduino: SD_WS_Parse protocol 27, rawData 3F94519855C7
2020.08.22 14:48:04 4: sduino: SD_WS_Parse 3F94519855C7 protocolid 27 (EFTH-800) - ERROR prematch
2020.08.22 14:48:05 4: sduino: Read, msg READredu: MU;P0=-220;P1=273;P2=-447;P3=515;P4=-4840;P5=762;P6=-697;D=01230121212303030303012123012303030121230303012121212121212121230123012123012301212301230301230121212303030303012123014565656561212303030303030301212301230121212301230121212303012123030121212123012301230123030301212123030301;CP=1;R=22;
2020.08.22 14:48:05 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:48:05 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94519855C7 length 48 dispatch(1/4) RSSI = -63
2020.08.22 14:48:05 4: sduino: Dispatch, W27#3F94519855C7, Dropped due to short time or equal msg
2020.08.22 14:48:28 4: sduino: Read, msg READredu: MU;P0=-9508;P1=492;P2=-1046;P3=1442;D=012121212121212123212323212123232323212123232321232323232123212123232121232323232123212123212123;CP=1;R=244;
2020.08.22 14:48:42 4: sduino: Read, msg READredu: MU;P0=-15556;P1=1342;P2=-988;P3=546;P4=-28000;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123234121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:48:43 4: sduino: Read, msg READredu: MU;P0=-13340;P1=1330;P2=-988;P3=556;P4=-27704;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=63;
2020.08.22 14:49:03 4: sduino: Read, msg READredu: MU;P0=-455;P1=504;P4=747;P5=-722;P6=-221;P7=275;D=45454545167016161616161616707016701670167070167016161670701616167070701670707070701670707070167016707016701616701670707070701670701670707;CP=7;R=25;
2020.08.22 14:49:03 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:49:03 4: sduino: Read, msg READredu: MS;P0=-4858;P1=765;P2=-696;P3=273;P4=-462;P5=506;P6=-223;D=301212121256345656565656565634345634563456343456345656563434565656343434563434343434563434343456345634345634565634563434343434563434563434;CP=3;SP=0;R=25;O;
2020.08.22 14:49:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:49:04 4: sduino: Read, msg READredu: MU;P0=-457;P1=266;P2=518;P3=-217;D=010232323232323231010231023101010231023101010232310102323101010102310231023101023232323102323101;CP=1;R=24;
2020.08.22 14:49:17 4: sduino: Read, msg READredu: MU;P0=-18480;P1=478;P2=-1043;P3=1459;P4=-24760;D=0121212121212121232123232121232323232121232323212323232321232121232321212323232321232121232121234;CP=1;R=245;
2020.08.22 14:49:39 4: sduino: Read, msg READredu: MU;P0=-26868;P1=1327;P2=-994;P3=548;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123230121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:49:40 4: sduino: Read, msg READredu: MU;P0=-13340;P1=1343;P2=-977;P3=559;P4=-27712;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=63;
2020.08.22 14:49:49 4: sduino: Read, msg READredu: MU;P0=-13476;P1=443;P2=-8996;P3=-4067;P4=-2050;P6=212;D=0121313141313141313141414141413141464146;CP=1;R=63;
2020.08.22 14:49:49 4: sduino: Read, msg READredu: MU;P0=-132;P1=246;P2=-2020;P3=428;P4=-4052;P6=112;P7=-240;D=01232323214323232323232343232323232323267;CP=3;R=217;
2020.08.22 14:50:02 4: sduino: Read, msg READredu: MU;P0=259;P1=-460;P2=522;P4=-4851;P5=768;P6=-704;P7=-214;D=70127272727272727010127012701270101270127272701012727270101270101010101010127270101270127010127012727012701010101270127270127270456565656010127272727272727010127012701010127012701010127270101272701010101270127012701012727272701272701045656565627012727272;CP=0;R=25;O;
2020.08.22 14:50:02 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:50:02 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94519854F6 length 48 dispatch(1/4) RSSI = -61.5
2020.08.22 14:50:02 4: sduino: SD_WS_Parse protocol 27, rawData 3F94519854F6
2020.08.22 14:50:02 4: sduino: SD_WS_Parse 3F94519854F6 protocolid 27 (EFTH-800) - ERROR prematch
2020.08.22 14:50:03 4: sduino: Read, msg READredu: MU;P0=-224;P1=275;P2=-455;P3=507;P4=-4856;P5=768;P6=-696;D=01230121212123012303012303012303030121230303012123012121212121212303012123012301212301230301230121212123012303012303014565656561212303030303030301212301230121212301230121212303012123030121212123012301230121230303030123030121;CP=1;R=21;
2020.08.22 14:50:03 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:50:03 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F94519854F6 length 48 dispatch(1/4) RSSI = -63.5
2020.08.22 14:50:03 4: sduino: Dispatch, W27#3F94519854F6, Dropped due to short time or equal msg
2020.08.22 14:50:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:50:05 4: sduino: Read, msg READredu: MU;P0=-24640;P1=482;P2=-1045;P3=1455;D=012121212121212123212323212123232323212123232321232323232123212123232121232323232123212123212123;CP=1;R=244;
2020.08.22 14:50:35 4: sduino: Read, msg READredu: MU;P0=-3360;P1=1341;P2=-992;P3=546;P4=-28008;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123234121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:50:36 4: sduino: Read, msg READredu: MU;P0=-11604;P1=1340;P2=-985;P3=546;P4=-27688;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=62;
2020.08.22 14:50:53 4: sduino: Read, msg READredu: MU;P0=-27716;P1=484;P2=-1043;P3=1453;D=012121212121212123212323212123232323212123232321232323232123212123232121232323232123212123212123;CP=1;R=241;
2020.08.22 14:51:01 4: sduino: Read, msg READredu: MU;P0=277;P1=-460;P2=523;P4=-4846;P5=767;P6=-703;P7=-207;D=70127272727272727010127012701270101270127272701012727270101272701010101010127010101270127010127012727012701010127010101012727010456565656010127272727272727010127012701010127012701010127270101012701010101270127012701012701012727010101045656565627012727272;CP=0;R=25;O;
2020.08.22 14:51:01 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:51:01 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F9451885498 length 48 dispatch(1/4) RSSI = -61.5
2020.08.22 14:51:01 4: sduino: SD_WS_Parse protocol 27, rawData 3F9451885498
2020.08.22 14:51:01 4: sduino: SD_WS_Parse 3F9451885498 protocolid 27 (EFTH-800) - ERROR prematch
2020.08.22 14:51:02 4: sduino: Read, msg READredu: MU;P0=-234;P1=261;P2=-470;P3=504;P4=-4864;P5=744;P6=-724;D=01230121212301212121230301212303030121230303012123030121212121212301212123012301212301230301230121212301212121230301214565656561212303030303030301212301230121212301230121212303012121230121212123012301230121230121230301212121;CP=1;R=25;
2020.08.22 14:51:02 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:51:02 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F9451885498 length 48 dispatch(1/4) RSSI = -61.5
2020.08.22 14:51:02 4: sduino: Dispatch, W27#3F9451885498, Dropped due to short time or equal msg
2020.08.22 14:51:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:51:32 4: sduino: Read, msg READredu: MU;P0=-27588;P1=1329;P2=-992;P3=544;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123230121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:51:33 4: sduino: Read, msg READredu: MU;P0=-14680;P1=1332;P2=-994;P3=545;P4=-27704;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=63;
2020.08.22 14:51:41 4: sduino: Read, msg READredu: MU;P0=-15924;P1=473;P2=-1054;P3=1454;D=012121212121212123212323212123232323212123232321232323232123212123232121232323232123212123212123;CP=1;R=243;
2020.08.22 14:52:00 4: sduino: Read, msg READredu: MU;P0=273;P1=-464;P2=506;P4=-4854;P5=754;P6=-707;P7=-223;D=70127272727272727010127012701270101270127272701012727270127010101010101010101270101270127010127012727012701010127270127272727010456565656010127272727272727010127012701010127012701010127270101012701010101270127012701012701012727010101045656565627012727272;CP=0;R=25;O;
2020.08.22 14:52:00 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:52:00 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F9451885498 length 48 dispatch(1/4) RSSI = -61.5
2020.08.22 14:52:00 4: sduino: SD_WS_Parse protocol 27, rawData 3F9451885498
2020.08.22 14:52:00 4: sduino: SD_WS_Parse 3F9451885498 protocolid 27 (EFTH-800) - ERROR prematch
2020.08.22 14:52:01 4: sduino: Read, msg READredu: MU;P0=-235;P1=267;P2=-461;P3=497;P4=-4848;P5=759;P6=-708;D=01230121212303012303030301212303030121230303012301212121212121212123012123012301212301230301230121212303012303030301214565656561212303030303030301212301230121212301230121212303012121230121212123012301230121230121230301212121;CP=1;R=22;
2020.08.22 14:52:01 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:52:01 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F9451885498 length 48 dispatch(1/4) RSSI = -63
2020.08.22 14:52:01 4: sduino: Dispatch, W27#3F9451885498, Dropped due to short time or equal msg
2020.08.22 14:52:04 4: sduino: KeepAlive, ok, retry = 0
2020.08.22 14:52:20 4: sduino: Read, msg READredu: MU;P0=170;P1=-4069;P2=442;P3=-1989;P4=317;P5=-8936;D=012321212321212323232321212323234323232123232323232323232121232123212125212123212123414123232323212123232343232321232323232323230;CP=2;R=204;
2020.08.22 14:52:20 4: sduino: Read, msg READredu: MU;P0=232;P1=-4049;P2=467;P3=-1988;P4=-8956;P5=300;P6=-832;D=0123212124212123212123212123532323212123232323232321232326;CP=2;R=217;
2020.08.22 14:52:21 4: sduino: Read, msg READredu: MS;P1=454;P2=-1985;P3=-4066;P5=-8939;D=15131312131312131312121212131312121212121213121212121212121213131213121313;CP=1;SP=5;R=218;O;m2;
2020.08.22 14:52:21 4: sduino: Read, msg READredu: MS;P1=443;P2=-1989;P3=-4059;P5=-8939;D=15131312131312131312121212131312121212121213121212121212121213131213121313;CP=1;SP=5;R=218;m1;
2020.08.22 14:52:29 4: sduino: Read, msg READredu: MU;P0=-8392;P1=490;P2=-1027;P3=1473;D=012121212121212123212323212123232323212123232321232323232123212123232121232323232123212123212123;CP=1;R=246;
2020.08.22 14:52:31 4: sduino: Read, msg READredu: MU;P0=-16880;P1=1331;P2=-990;P3=544;P4=-28004;D=01212121232123212121212121212323212323212123232321232123232121212123232321232123212123234121212123212321212121212121232321232321212323232123212323212121212323232123212321212323;CP=3;R=63;
2020.08.22 14:52:33 4: sduino: Read, msg READredu: MU;P0=-3920;P1=1340;P2=-985;P3=547;P4=-27688;D=01212121232123212323232121212323212323232123232123212121212121212123232123212121232323214121212123212321232323212121232321232323212323212321212121212121212323212321212123232321;CP=3;R=63;
2020.08.22 14:52:59 4: sduino: Read, msg READredu: MU;P0=271;P1=-460;P2=519;P4=-4856;P5=766;P6=-700;P7=-211;D=70127272727272727010127012701270101270127272701012727270127012701010101010101010101270127010127012727012701010101010101010127270456565656010127272727272727010127012701010127012701010127012727012701010101270127010127270127272727010127045656565627012727272;CP=0;R=25;O;
2020.08.22 14:52:59 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:52:59 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F9451685379 length 48 dispatch(1/4) RSSI = -61.5
2020.08.22 14:52:59 4: sduino: SD_WS_Parse protocol 27, rawData 3F9451685379
2020.08.22 14:52:59 4: sduino: SD_WS_Parse 3F9451685379 protocolid 27 (EFTH-800) - ERROR prematch
2020.08.22 14:53:00 4: sduino: Read, msg READredu: MU;P0=-221;P1=272;P2=-456;P3=512;P4=-4852;P5=751;P6=-708;D=01230121212121212121212303012303030121230303012301230121212121212121212123012301212301230301230121212121212121212303014565656561212303030303030301212301230121212301230121212301230301230121212123012301212303012303030301212301;CP=1;R=25;
2020.08.22 14:53:00 4: sduino: Parse_MU, Fingerprint for MU protocol id 27 -> EFTH-800 matches, trying to demodulate
2020.08.22 14:53:00 4: sduino: Parse_MU, Decoded matched MU protocol id 27 dmsg W27#3F9451685379 length 48 dispatch(1/4) RSSI = -61.5
2020.08.22 14:53:00 4: sduino: Dispatch, W27#3F9451685379, Dropped due to short time or equal msg
2020.08.22 14:53:04 4: sduino: KeepAlive, ok, retry = 0

Hoffe das reicht zunächst. Ansonsten bin ich gerne bereit weitere Informationen zu geben.

Danke für euer Interesse.

**Comment by elektron-bbs** [comment]
Ich habe einen neuen Branch für diesen Sensor erstellt. Ein Update darauf erfolgt mit folgendem Befehl:

`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/master_SD_WS_EFS-3110A/controls_signalduino.txt
`

Bitte mal testen. In den von dir geposteten Nachrichten wurde nur Temperatur und Feuchte übertragen.
Interessant wäre, wie die Übertragung der Uhrzeit erfolgt. Die Doku sagt dazu:

> Die Synchronisierung mit der DCF-Zeit wird durch den Sensor täglich automatisch durchgeführt um 2:00 Uhr sowie um 17:00 Uhr durchgeführt.

**Comment by alipu-001** [comment]
Nach dem Update werden füllen sich alle Devices mit Daten. EFTH-800 und EFS-3110A sind gleichwertig. 

Auch um 17:00 erscheinen in keinem der Logs der EFS-3110A Sensoren irgendwelche Uhrzeiten. Würde dir der FHEM-Log mit Verbose 4 helfen, um eventuell doch die Uhrzeit herauszulesen?

Ich bin mit dem derzeitigen Zustand voll zufrieden. 

In jedem Fall herzlichen Dank für die schnelle Reaktion und Hilfe.

**Comment by elektron-bbs** [comment]
Du könntest ja bitte mal noch prüfen, ob nach Betätigung der Taste "RCC" am Sensor irgend welche ungewöhnlichen Nachrichten in den Logs auftauchen.

**Comment by alipu-001** [comment]
Habe es probiert, es tut sich nichts.

**Comment by elektron-bbs** [comment]
Dann können wir nur abwarten, ob dir noch  irgend welche ungewöhnlichen Nachrichten in den Logs auffallen.

**Comment by alipu-001** [comment]
Alles klar, werde in nächster Zeit mal immer wieder draufschauen.

**Comment by elektron-bbs** [comment]
Wie ist der aktuelle Stand? Können wir das Update so übernehmen, oder gibt es noch Probleme?

**Comment by alipu-001** [comment]
Funktioniert alles bestens. Denke man kann es übernehmen.

**Comment by elektron-bbs** [comment]
Die Protokollerweiterung wurde in den Master-Branch übernommen.
Ich schließe dieses Issue.
