### ISSUE TITLE
Eurochron WS5500S Außensensor 868MHz Protokoll 50%

### ISSUE THREAD

**Issue by EugenIII** [RFD-FHEM/RFFHEM#891]
Hallo FHEM-Freunde,

Ich benötige etwas Hilfe beim Decodieren von Eurochron-Außensensor Protokolls. Einiges habe ich schon geschafft, bin mir aber nicht so sicher ob ich auf dem richtigem Weg bin oder es ein mega Zufall ist, dass die Werte zusammenpassen.

Mein Projekt:
Im Rahmen meiner Studienarbeit habe ich vorgesehen ein Eurochron WS5500S Außensensor zu verwenden. Die Wetterdaten sollen von einer Prototyp-Wetterstation empfangen werden. Die Prototyp-Wetterstation verwendet ESP32-Controller, welcher dann die Daten, sowohl der eigenen Sensoren als auch die des Eurochrons Sesors,  als ROS-Node (Robot Operating System) an den Laptop publisht (=veröffentlicht, sendet). Als Empfänger habe ich einen CC1101 -Modul vorgesehen.
Wetterstation:
1. ESP32 + NodeMcu Base Ver.1.0  
2. Nextion LCD NX3224k028_011
3. Varta 13000mAh Powerbank
4. Sensoren: Adafruit TSL2501, Adafruit Si7021, JoyIT BMP280, JoyIT DS18B20.
5. CC1101 868MHz
Die Verwendung mehrerer Sensoren war für das Decodieren des Protokolls des Eurochrons-Außensensors vorgesehen.

Reverse Engineering:
Mit Hilfe einiger Datenblätter und Bedienungsanleitungen habe ich folgendes über Eurochron WS5500S herausgefunden:

1. Freuquenzband 868,33-868,37 MHz
2. Messwiederholung 16 sec
3.  Darstellung der Wetterdaten bei der Basisstation EFWS2900 (siehe Bilder)
4. Allgemein: Messbereiche, Genauigkeiten und Auflösug der Sensoren des Außensensors
5. Transmitter RFM117 (OOK) oder RFM119S (GFSK, FSK, OOK) 
           [Später kam RFM117 nicht in Betracht da, das empfangene Signal Frequenzmodulierung aufweiste]
6. Receiver RFM219SW (wurde im Datenblatt von RFM119S ausdrücklich empfohlen, bat einige wichtige Infos):
    6.1 Standardeinstellungen (siehe Bilder)
    6.2 Protokollaufbau 
    6.3 Datencodierung (Manchester, NRZ)

Signalauswertung:
Mit Hilfe einer RTL-SDR-Sticks (nooelec NESDR Mini 2+ R820T2 SDR & DVB-T) und URH-Software:
1. Trägerfrequenz 868.345 MHz
2. Frequenzhub 35 kHz
3. NRZ / Baudrate 17.241 kbps (Ein bit = 58 * 10^⁻6)
4. Windrichtung: Nibble 21-22, aber nur bis 255 °. Danach signalisiert Nibble 23 dass ein Überlauf stattgefunden hat. Somit folgt bei Überlauf folgendes: DEC( Nibble 21-22)  + 255 = Windrichtung
5. Windgeschwindigkeit. Nibble 31-32 in m/s
6. Niederschlag: Nibble 33-36
7. Temperatur: DEC(Nibble 24-25) - 15 + DEC(Nibble 26) / 10 = Temperatur [Bin mir  nicht sicher]
8. Beleuchtungsstärke vermutlich bei Nibble 37-42 

Kann mir jemand bitte bei folgenden Größen ein Tipp geben um an die Daten zu kommen: Temperatur, Beleuchtungsstärke und Luftfeuchtigkeit.

Hier kommen Bilder aus den Datenbättern und URH-Programm die mich auf die oben genannten Erkentnissen geführt haben:

![EFWS2900_WS5500S_Eigenschaften](https://user-images.githubusercontent.com/70649216/94336017-0fbca580-ffe0-11ea-977e-211b7870c4e4.jpg)
![Transmitter_ReverseEngineering](https://user-images.githubusercontent.com/70649216/94336053-57dbc800-ffe0-11ea-8194-46eebc8a30f4.jpg)
![RFM119_Datasheet](https://user-images.githubusercontent.com/70649216/94336044-47c3e880-ffe0-11ea-9277-d8feaa0e4259.jpg)
![RFM219SW_Receiver_Datasheet](https://user-images.githubusercontent.com/70649216/94336058-5f02d600-ffe0-11ea-9f5a-617f1438420f.png)
![RFM219SW_RF-SettingsParameter_ConfigGuide](https://user-images.githubusercontent.com/70649216/94336066-7772f080-ffe0-11ea-984c-c50f1c0a984f.png)
![RFM219SW_(G)FSK-SettingsParameter_ConfigGuide](https://user-images.githubusercontent.com/70649216/94336078-878ad000-ffe0-11ea-8bba-942670e8f5d1.png)
![RFM219SW_PacketType_Dtatasheet](https://user-images.githubusercontent.com/70649216/94336080-8fe30b00-ffe0-11ea-864b-5eac8c1d3267.png)
![RFM219SW_Leitungskodierung_CommunicationExample](https://user-images.githubusercontent.com/70649216/94336082-93769200-ffe0-11ea-81a8-05847492a34f.png)
![RFMTranceiver_Example_CommunicationExample](https://user-images.githubusercontent.com/70649216/94336083-96718280-ffe0-11ea-95a2-3165ca628e8a.png)
![SHT30_TEMP-HUM_ReverseEngineering](https://user-images.githubusercontent.com/70649216/94336085-9a050980-ffe0-11ea-874d-0803df06efcd.jpg)
![SHT30_TEMP-HUM-Berechnung_datasheet](https://user-images.githubusercontent.com/70649216/94336086-9c676380-ffe0-11ea-9bf6-174e4fc94151.png)

URH-Analyse:

![Spektrum_Analyzer_01](https://user-images.githubusercontent.com/70649216/94336092-a38e7180-ffe0-11ea-925e-1e4f1bb8418e.PNG)
![Spektrum_Analyzer_02](https://user-images.githubusercontent.com/70649216/94336095-ab4e1600-ffe0-11ea-9870-819a1bc72083.PNG)
![Spektrum_Analyzer_03](https://user-images.githubusercontent.com/70649216/94336097-adb07000-ffe0-11ea-8cb3-be08a308cb3b.PNG)
![URH_analog-demoduliert_Messwiederholung](https://user-images.githubusercontent.com/70649216/94192840-c8cf9280-feaf-11ea-82ff-a92fa6ef5b35.png)
In dem mittlerem Abschnitt des Bildes sind genau 10 Samples ausgewählt.
![URH_TEMP-Messung](https://user-images.githubusercontent.com/70649216/94192852-ccfbb000-feaf-11ea-9399-3e24edd6eb79.png)
Jede Messung beinhaltet 2 Nachrichten (02_[gemessene Werte] - Messung  => 1 & 2 Nachricht im rechtem Fenster ). Die Temperatur wurde mit Hilfe eines Proxxon-Föhns erhöht und mit Prototyp-Wetterstation gemessen.

Anhänge:
[Eurochron_Datenblätter.zip](https://github.com/RFD-FHEM/RFFHEM/files/5286375/Eurochron_Datenblatter.zip)

**Comment by HomeAutoUser** [comment]
Hallo, ich muss nun mal Zwischenfragen bei dem vielen Input. Du möchtest den Sensor dekodieren mit Hilfe des Signalduino‘s? 

Wenn ja, da müssen wir die Registerwerte setzen um die Datenrate und Modulation ... zu konfigurieren. Besitzt du einen Signalduino?

**Comment by EugenIII** [comment]
Verzeiht mir bitte der großen Menge der Information,  ich wollte mehr oder weniger detaliert beschreiben wie ich auf die Ergebnisse gekommen bin.
Ich möchte die Wetterdaten mit ESP32 + CC1101(in binären/hexadezimalen Format) vom Eurochron-Sensor empfangen und per 2.4 GHz -Verbindung an Laptop weiterschicken. Zur Konfiguration der Register des CC1101-Moduls werde ich die SmartRC-CC1101-Driver-Lib verwenden. Derzeit bin ich dabei den Rest des Protokolls zu dekodieren mit URH-Software und den Empfang der Daten mit CC1101 einzurichten.
Ich benötige etwas Hilfe beim herausfinden wo sich Temperatur, Luftfeuchtigkeit und Beleuchtungsstärke  in der Nachricht vestecken, die mit Hilfe URH und SDR-STL-Sticks empfangen werden.
....
Ich bin mir bewusst, dass dies ein FHEM-Forum ist, der sich ausschließlich sich mit Signalduino und Homeautomatisierung befasst, fand aber leider keinen passenden Forum für mein Problem.

**Comment by elektron-bbs** [comment]
Dann poste doch mal bitte einige Nachrichten im Hex- oder Binaerformat mit den zugehörigen Werten, die dabei übermittelt wurden.

**Comment by EugenIII** [comment]
Hier sind die Daten einmal in txt-Dateien und als URH-Projekt: 

[Wetterdaten_BIN.txt](https://github.com/RFD-FHEM/RFFHEM/files/5285367/Wetterdaten_BIN.txt)
[Wetterdaten_NEX.txt](https://github.com/RFD-FHEM/RFFHEM/files/5285369/Wetterdaten_NEX.txt)
[URH_TEMP-HUM-Messungen.zip](https://github.com/RFD-FHEM/RFFHEM/files/5285370/URH_TEMP-HUM-Messungen.zip)

**Comment by elektron-bbs** [comment]
Ich habe mir die Daten mal angesehen, kann aber auf Anhieb die fehlenden Werte nicht erkennen. Man bräuchte dafür mehr Datenreihen mit sich stetig ändernden Werten. Die Temperatur ist in den Logs ohne Dezimalstelle notiert, der Sensor überträgt diese aber sicher.
