### ISSUE TITLE
GT-TMBBQ-01e(Aldi/Globaltronics) Grillthermometer

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#892]
Siehe hier
https://forum.fhem.de/index.php/topic,114437.0.html

und die Anleitung
http://docplayer.org/26655435-Bedienungsanleitung-funk-grillthermometer-anwenderfreundliche-anleitung-id-05006.html

Laut Anleitung:
Messbarer Temperaturber.: 0 °C–148 °C
In der Anleitung steht aber auch
"Das Grillthermometer wurde für das Messen der Kerntemperatur des Bratguts bis 200 °C entwickelt"

Ich denke das Modul 14_SD_WS.pm ist dafür passender als das 14_CUL_TCM97001

Es ist dafür eine neue ProtocolId notwendig, die nächste freie ist die 106
ungefähr so:
```
		"106"	=>	## BBQ temperature sensor GT-bbqt01e
							# MS;P1=-9134;P2=482;P3=-4097;P4=-2095;D=2123232423232323232424232324232424242324242424;CP=2;SP=1;R=53;
			{
				name            => 'BBQ temperature',
				comment         => 'temperature sensor',
				id              => '106',
				one             => [1,-8.5],
				zero            => [1,-4.4],
				sync            => [1,-19],
				clockabs        => 480,
				format          => 'twostate',
				preamble        => 'W106#',					# prepend to converted message
				clientmodule    => 'SD_WS',
				#modulematch    => '',
				length_min      => '22',
				length_max      => '26',
			}
```

und das 14_SD_WS.pm Modul
```
		106 => {
				sensortype => 'GT-TMBBQ-01',
				model      => 'SD_WS_106_T',
				prematch   => sub { return 1; },		#  no precheck known
				id         => sub { return 0;},
				temp       => sub {my (undef,$bitData) = @_; return ( round(((hex(substr($rawData,2,4)) / 4) -2500) / 35,0)); },
				crcok      => sub {return 1;},		# crc test method is so far unknown
		} ,
```

dies passt für diesen Sensor nicht
```
		if ($temp < -30 || $temp > 70) {
			Log3 $iohash, 3, "$ioname: SD_WS_Parse $deviceCode - ERROR temperature $temp";
			return "";  
		}
```

> Messbereich 0°C-130°C(Anzeigeeinheit ohne Nachkommastellen; mit einem Feuerzeug bin ich in FHEM bis 312° gekommen;Minusgrade gehen vermutlich auch)

**Comment by elektron-bbs** [comment]
Das Protokoll ist jetzt im Branch "Master".
Die Installation in FHEM erfolgt mit folgendem Befehl:

`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/master/controls_signalduino.txt`

Ich schließe dieses Issue.
