### ISSUE TITLE
Protokoll für 3-T Motor (Markise & Rollo)

### ISSUE THREAD

**Issue by MBj1703** [RFD-FHEM/RFFHEM#90]
Hallo Zusammen,

bin gerade ein bisschen am Spielen und versuche, meinen 3-T Motor der Markise in fhem zu bekommen.
Er geht per Funk auf 433 MHz.

Habe den SIGNALduino auf verbose 5 gestellt und ein paar mal die FB gedrückt.

Folgender Log kam raus:

> 2016.07.06 13:30:23.429 4: SIGNALduino_unknown converted to bits: 0100000010100111
> 2016.07.06 13:30:23.429 4: SIGNALduino_unknown Protocol: 40
> 2016.07.06 13:30:23.428 4: SIGNALduino_unknown rawData: 40A7
> 2016.07.06 13:30:23.428 4: SIGNALduino_unknown incomming msg: u40#40A7
> 2016.07.06 13:30:23.427 5: SIGNALduino433 dispatch u40#40A7
> 2016.07.06 13:30:23.427 5: SIGNALduino433: converted Data to (u40#40A7)
> 2016.07.06 13:30:23.427 4: SIGNALduino433: decoded matched MU Protocol id 40 dmsg u40#40A7 length 16
> 2016.07.06 13:30:23.426 5: SIGNALduino433: dispatching bits: 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1
> 2016.07.06 13:30:23.426 4: SIGNALduino_unknown converted to bits: 010000001010011111000100001001100110
> 2016.07.06 13:30:23.426 4: SIGNALduino_unknown Protocol: 40
> 2016.07.06 13:30:23.426 4: SIGNALduino_unknown rawData: 40A7C4266
> 2016.07.06 13:30:23.425 4: SIGNALduino_unknown incomming msg: u40#40A7C4266
> 2016.07.06 13:30:23.424 5: SIGNALduino433 dispatch u40#40A7C4266
> 2016.07.06 13:30:23.424 5: SIGNALduino433: converted Data to (u40#40A7C4266)
> 2016.07.06 13:30:23.424 4: SIGNALduino433: decoded matched MU Protocol id 40 dmsg u40#40A7C4266 length 36
> 2016.07.06 13:30:23.423 5: SIGNALduino433: dispatching bits: 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0
> 
> 2016.07.06 13:27:49.963 4: SIGNALduino_unknown converted to bits: 01000000101001111000
> 2016.07.06 13:27:49.963 4: SIGNALduino_unknown Protocol: 40
> 2016.07.06 13:27:49.963 4: SIGNALduino_unknown rawData: 40A78
> 2016.07.06 13:27:49.963 4: SIGNALduino_unknown incomming msg: u40#40A78
> 2016.07.06 13:27:49.962 5: SIGNALduino433 dispatch u40#40A78
> 2016.07.06 13:27:49.961 5: SIGNALduino433: converted Data to (u40#40A78)
> 2016.07.06 13:27:49.961 4: SIGNALduino433: decoded matched MU Protocol id 40 dmsg u40#40A78 length 20
> 2016.07.06 13:27:49.961 5: SIGNALduino433: dispatching bits: 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 0 0 0
> 2016.07.06 13:27:49.960 4: SIGNALduino_unknown converted to bits: 010000001010011111000100001001100100
> 2016.07.06 13:27:49.960 4: SIGNALduino_unknown Protocol: 40
> 2016.07.06 13:27:49.960 4: SIGNALduino_unknown rawData: 40A7C4264
> 2016.07.06 13:27:49.960 4: SIGNALduino_unknown incomming msg: u40#40A7C4264
> 2016.07.06 13:27:49.959 5: SIGNALduino433 dispatch u40#40A7C4264
> 2016.07.06 13:27:49.959 5: SIGNALduino433: converted Data to (u40#40A7C4264)
> 2016.07.06 13:27:49.958 4: SIGNALduino433: decoded matched MU Protocol id 40 dmsg u40#40A7C4264 length 36
> 2016.07.06 13:27:49.958 5: SIGNALduino433: dispatching bits: 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 0
> 2016.07.06 13:27:49.957 4: SIGNALduino_unknown converted to bits: 010000001010011111000100001001100110
> 2016.07.06 13:27:49.957 4: SIGNALduino_unknown Protocol: 40
> 2016.07.06 13:27:49.957 4: SIGNALduino_unknown rawData: 40A7C4266
> 2016.07.06 13:27:49.957 4: SIGNALduino_unknown incomming msg: u40#40A7C4266
> 2016.07.06 13:27:49.956 5: SIGNALduino433 dispatch u40#40A7C4266
> 2016.07.06 13:27:49.955 5: SIGNALduino433: converted Data to (u40#40A7C4266)
> 2016.07.06 13:27:49.955 4: SIGNALduino433: decoded matched MU Protocol id 40 dmsg u40#40A7C4266 length 36
> 2016.07.06 13:27:49.955 5: SIGNALduino433: dispatching bits: 0 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0
> 2016.07.06 13:27:49.954 4: SIGNALduino_unknown converted to bits: 0010000100110010
> 2016.07.06 13:27:49.954 4: SIGNALduino_unknown Protocol: 40
> 2016.07.06 13:27:49.954 4: SIGNALduino_unknown rawData: 2132
> 2016.07.06 13:27:49.954 4: SIGNALduino_unknown incomming msg: u40#2132
> 2016.07.06 13:27:49.953 5: SIGNALduino433 dispatch u40#2132
> 2016.07.06 13:27:49.952 5: SIGNALduino433: converted Data to (u40#2132)
> 2016.07.06 13:27:49.952 4: SIGNALduino433: decoded matched MU Protocol id 40 dmsg u40#2132 length 16
> 2016.07.06 13:27:49.952 5: SIGNALduino433: dispatching bits: 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0
> 2016.07.06 13:27:49.952 5: SIGNALduino433: Starting demodulation at Position 11`

Hier noch das Reading aus dem SIGNALduino Device:

> `2016-07-06_13:54:45 SIGNALduino433 UNKNOWNCODE u#441D2FE4B1E2D01B4E76
> 2016-07-06_13:53:43 SIGNALduino433 UNKNOWNCODE u#441D2FE4ADE2D01B52AE
> 2016-07-06_13:52:44 SIGNALduino433 UNKNOWNCODE u#448E97F255F1680DAA66
> 2016-07-06_13:51:45 SIGNALduino433 UNKNOWNCODE u#44E97F254F1680DAB77

und aus dem Event Monitor:

> 2016-07-06 13:55:40-MC;LL=-1040;LH=915;SL=-572;SH=406;D=C28312B8EE7D77138;C=440;L=67;#2016-07-06 13:55:40-MC;LL=-1030;LH=918;SL=-555;SH=433;D=0A0C4AD3B9F5DA720;C=450;L=65;#2016-07-06 13:55:43-MU;P0=-780;P1=108;P2=455;P4=-489;P5=304;P7=212;D=012124242421212121212121512121242421242121212421212121242121212121212170211;CP=1;#2016-07-06 13:55:43-MU;P0=136;P1=459;P2=-598;P7=316;D=012121212121212121212121212121212121212121212127212121212120;CP=1;#2016-07-06 13:55:43-MU;P0=263;P1=96;P2=455;P4=-607;D=0121042121242421012101242124212124010121211;CP=1;#2016-07-06 13:55:48-MU;P0=217;P1=491;P2=-491;P3=-244;P5=-5096;D=50505051212121213020313020313021203130212121212121212121212031212130212121212121203121213020312121212130212121203130203130212120;CP=1;#2016-07-06 13:56:09-MS;P0=-379;P1=327;P2=-746;P3=689;P4=-7985;P5=4779;P6=-1536;D=1456303030123012301212121212123012301212303030303012121230121212123012121230303030;CP=1;SP=4;O;#2016-07-06 13:56:13-MU;P0=-690;P1=302;P4=196;P6=120;P7=-132;D=0101010101010104010101010101010101010101067;CP=1;#2016-07-06 13:56:13-MU;P0=190;P1=92;P2=-797;P4=287;D=0120242424242424242424202124242424242424242424242024202020202;CP=4;#2016-07-06 13:56:13-MU;P0=-794;P2=298;P4=-1792;P6=120;P7=220;D=00002020242000607020200020000020000000000020202000002000006;CP=2;#2016-07-06 13:56:13-MU;P0=-774;P1=275;P3=186;P6=126;P7=96;D=01010103010301010101010101010101010101010101010101010101010101010101010106070101010106;CP=1;#2016-07-06 13:56:14-MU;P0=241;P1=338;P2=-690;D=012121212120212120212121202121212121212020212121202121212121202021202020212121212121212121212121212121212020202;CP=1;#2016-07-06 13:56:14-MU;P0=-679;P1=291;P7=108;D=0101010101010101010101010101010101010107;CP=1;#2016-07-06 13:56:21-MC;LL=-1021;LH=933;SL=-544;SH=426;D=E7B9895AB73EBC858;C=452;L=68;#2016-07-06 13:56:21-MU;P0=-455;P1=429;P2=-112;P3=-933;P5=911;D=00123105010101350101310501300105310535350135353501350101310501010101353501010131053101010535013101;CP=1;#2016-07-06 13:56:21-MC;LL=-1048;LH=909;SL=-609;SH=422;D=7B9895AB73EBC858;C=443;L=64;#2016-07-06 13:56:21-MU;P0=-754;P1=240;P4=355;D=10101040101010101010101040101010404010101010;CP=1;#2016-07-06 13:56:22-MU;P0=-332;P1=295;P2=-696;P6=148;D=01212121212126212121212121212121212121212121212;CP=1;#2016-07-06 13:56:23-MC;LL=-1082;LH=877;SL=-597;SH=381;D=5C28312B0EE7D761B0;C=419;L=70;#2016-07-06 13:56:23-MC;LL=-1035;LH=920;SL=-572;SH=406;D=C28312B8EE7D77138;C=441;L=67;#2016-07-06 13:56:23-MC;LL=-1035;LH=920;SL=-539;SH=436;D=0A0C4AD3B9F5DA720;C=451;L=65;#2016-07-06 13:56:24-MC;LL=-490;LH=490;SL=-224;SH=234;D=9A6AAAAA56AAA56556A99A8;C=241;L=90;#2016-07-06 13:56:29-MC;LL=-1010;LH=940;SL=-501;SH=459;D=B9AE625605CFA73640;C=466;L=70;#2016-07-06 13:56:30-MC;LL=-1032;LH=926;SL=-545;SH=431;D=5CD7312B42E7D39358;C=452;L=71;#2016-07-06 13:56:30-MS;P0=-4351;P3=442;P4=313;P5=-2012;P6=-9150;D=364530303535303035353535303535353035353535303030303030303535353035;CP=3;SP=6;

**Comment by sidey79** [comment]
Auf Anhieb kann ich das Signal leider nicht zuordnen.

Es gibt durchaus mehrere Signale, die erkannt werden.
Leider sind die augenscheinlich nicht identisch.

Hast Du vielleicht noch mehr Informationen zu dem Sender / Empfänger?

**Comment by MBj1703** [comment]
Viel weiß bzw. habe ich nicht.

Das ist der Motor: https://www.3t-motors.de/3T-Markisenmotore-3T/Funk-Markisenmotore/3T-Funk-Markisenmotor-30Nm-inkl-Adaptersatz-Handsender-HS1.html

Das ist die FB: https://www.3t-motors.de/3T-Funk-Handsender/3T-Funk-Handsender-1-Kanal-HS1.html

Gefunkt wird auf 433,92 MHz ± 100KHz.
Ich habe wohl mal gelesen, dass das mit RollingCode funktioniert. Deswegen vermutlich die verschiedenen Signale.

Was kann ich noch liefern?

**Comment by sidey79** [comment]
Also, wenn da ein rolling code enthalten ist, wird das Interpretieren der Nachricht schwer.

Das Signal selbst, moduliert üblicherweise immer nach einem festen Schema.
Kannst Du noch mal so loggen, das alle Daten (Verbose 4) im Logfile landen.

Am besten die FB tasten 5x im Abstand von 10 Sekunden drücken. Dann ist es einfacher, das Signal im Log zuzuordnen.

**Comment by sidey79** [comment]
Die commits gehören nicht zu diesem Issue.

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.
