### ISSUE TITLE
Network connected Signalduino does not connect

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#901]
## Expected Behavior

Connect to network connected signalduino should be possible. Currently there seems to be some bug 

## Actual Behavior

```
2020.10.25 16:19:46 1: stacktrace:
2020.10.25 16:19:46 1: PERL WARNING: Use of uninitialized value in string eq at ./FHEM/00_SIGNALduino.pm line 969.
2020.10.25 16:19:46 1: sduino: Can't connect to fhem-pi:45020\: http://fhem-pi:45020\: malformed or unsupported URL
2020.10.25 16:19:46 5: HttpUtils url=http://fhem-pi:45020\
2020.10.25 16:19:46 3: Opening sduino device fhem-pi:45020\
2020.10.25 16:19:46 3: sduino: ResetDevice, nano328
2020.10.25 16:19:42 1:     main::CallFn                        called by fhem.pl (763)
2020.10.25 16:19:42 1:     main::FW_Read                       called by fhem.pl (3817)
2020.10.25 16:19:42 1:     main::FW_answerCall                 called by ./FHEM/01_FHEMWEB.pm (592)
2020.10.25 16:19:42 1:     main::FW_doDetail                   called by ./FHEM/01_FHEMWEB.pm (1161)
2020.10.25 16:19:42 1:     main::getAllGets                    called by ./FHEM/01_FHEMWEB.pm (1526)
2020.10.25 16:19:42 1:     main::CommandGet                    called by fhem.pl (2757)
2020.10.25 16:19:42 1:     main::CallFn                        called by fhem.pl (1988)
2020.10.25 16:19:42 1:     main::SIGNALduino_Get               called by fhem.pl (3817)
2020.10.25 16:19:42 1:     main::__ANON__                      called by ./FHEM/00_SIGNALduino.pm (967)
2020.10.25 16:19:42 1: stacktrace:
2020.10.25 16:19:42 1: PERL WARNING: Use of uninitialized value in string eq at ./FHEM/00_SIGNALduino.pm line 969.
2020.10.25 16:19:42 3: sduino: Attr, setting Verbose to: 5

```

## Steps to Reproduce the Problem

  1. define sduino `def=fhem-pi:45020`
  2. reset sduino
  3.  sduino is not connected

## Specifications

  - Microcontroller: nano328 attatched via ser2net
  - Version (Firmware):   V 3.4.0 SIGNALduino - compiled at Jul 16 2020 20:52:03
  - Versionmodul (FHEM Module): 3.5.0

Connection works with module Version 3.4.4.

**Comment by elektron-bbs** [comment]
Der Fehler dürfte an dieser Zeile in der Datei 00_SIGNALduino.pm liegen:

```
  $dev .= '\@57600' if ($dev ne 'none' && $dev =~ m/[a-zA-Z]/xms && $dev !~ m/\@/);   # bei einer IP wird kein \@57600 angehaengt
```

Ich habe diese auskommentiert, dann funktioniert es auch mit Hostnamen. So richtig sehe ich keinen Sinn im Anhängen der Baudrate (der führende Backslash dürfte sowieso falsch sein).

Es müsste nur die Doku geändert werden:

`Sie können auch eine Baudrate angeben, wenn der Gerätename das @ enthält, Beispiel: /dev/ttyACM0@57600`

in 

`Sie müssen auch die Baudrate angeben, Beispiel: /dev/ttyACM0@57600`

Oder du passt halt das Regex an.

**Comment by sidey79** [comment]
@elektron-bbs 

Super vielen Dank.
Ich hatte noch nicht so genau nachgesehen wo der Fehler herkam. Mir war zunächst wichtig ihn zu dokumentieren.
Ich werde mal schauen was wir da geändert haben.  Die Baudrate würde ich nicht als Parameter entfernen wollen.

**Comment by elektron-bbs** [comment]
Dann vieleicht so:
```
  $dev .= '@57600' if ($dev ne 'none' && $dev =~ m/[a-zA-Z]/xms && $dev !~ m/\@/ && $dev !~ m/:/);   # bei einer IP oder Hostname wird kein @57600 angehaengt
```

**Comment by sidey79** [comment]
Es liegt an dem xms modifier.
Ohne den ging es.

Ich schreibe gerade einen Test der die verschiedenen Namensgebebungen durchtestet

Mir fällt ein
`/dev/serial/by-id/something4@115200`
`/dev/serial/by-id/something4@57600`
`/dev/serial/by-id/something4`

`192.168.122.56:44323`
`192.168.122.56`
`192.168.122:44323`


`sernetgw:44323`
`sernetgw.local.host:44323`
`sernetgw.local.host`

Hab ich was wesentliches vergessen?

**Comment by elektron-bbs** [comment]
Mir fällt jetzt keine weitere Variante ein.
Eine IP mit nur 24 Bit sollte eigentlich nicht akzeptiert werden, ebenso IP oder Hostname ohne Port.

**Comment by HomeAutoUser** [comment]
>Hab ich was wesentliches vergessen?

Genau genommen darf auch sowas nicht funktionieren
`Hostname:65536`
`192:168:122:56:45476`

Gültige Einträge sind bsp. auch:

`/dev/serial/by-path/platform-3f980000.usb-usb-0:1.1.3:1.0-port0@57600`
`/dev/ttyACM1@57600`

**Comment by sidey79** [comment]
Ich bau die alle mal ein. Kann ja nicht schaden.
Das Grundgerüst habe ich. Nur an Details hängt es. Vielleicht sind es aber auch Fehler die gerade aufdecke, dass die Baudtate 115200 nicht übernommen wird

**Comment by sidey79** [comment]
@elektron-bbs 
@HomeAutoUser 

So ich habe ein umfangreiches Testset erstellt.
Naja vielleicht hätte ich es doch gleich mit einer Schleife machen solle :-)

Sind ein paar Fälle die jetzt nicht so implementiert sind, wie wie es funktionieren sollte

**Comment by sidey79** [comment]
Bis auf den Hostnamen mit Port (ohne FQDN) habe ich den Fix fertig.
Für den Hostnamen ohne Domäne muss ich mir noch was einfallen lassen :)

**Comment by HomeAutoUser** [comment]
>So ich habe ein umfangreiches Testset erstellt.
Naja vielleicht hätte ich es doch gleich mit einer Schleife machen solle :-)
>
> Sind ein paar Fälle die jetzt nicht so implementiert, wie es funktionieren sollte

Da hoffe ich mal, das du alle Fälle bedacht hast. Deine neues Hobby ;-)

**Comment by sidey79** [comment]
Naja,
Alle Fälle hab ich nicht bedacht vermute ich.
Allerdings deutlich mehr als vorher bedacht waren. :)
