### ISSUE TITLE
receive TPS signals

### ISSUE THREAD

**Issue by SuperMesna** [RFD-FHEM/RFFHEM#903]
Hi 

I am using a SignalDuino on a RasPi4, running Raspian with FHEM. Everything seems to be working just fine.
is there a way to see if a TirePressure Sensor is working? At least if it is sending anything whatsoever? 
I know the sensors I bought are sending on 433MHz. Just wanted to make sure the batteries haven't died yet...

**Comment by HomeAutoUser** [comment]
Hello,
you can set your SIGNALduino to verbose 4 and see whether messages appear in the log file.
If that is not the case, then you have to find out the modulation of your hardware.
What is the name or model of your TirePressure sensor?

**Comment by SuperMesna** [comment]
the model is S180052050C
I couldnt find any specification about that very model. But I got to read somewhere that the car (Volvo V50) is using 433MHz sensors...

**Comment by HomeAutoUser** [comment]
Hello,
you can only test it by having a sensor send.
Either you remove a sensor or drive the car next to the receiver ;-)

**Comment by elektron-bbs** [comment]
Es könnte auch sein, das die Teile erst ab einer bestimmten Geschwindigkeit senden:

> The tire pressure monitoring system1 uses sensors mounted in the tire valves to check inflation pressure levels. When the vehicle is moving at a speed of approximately 20 mph (30 km/h) or faster, these sensors transmit inflation pressure data to a receiver located in the vehicle.

Quelle: http://www.volvedia.com/inf-2014.html

**Comment by HomeAutoUser** [comment]
Hello @SuperMesna,
is your concern still up to date or can the issues be resolved?

**Comment by HomeAutoUser** [comment]
@SuperMesna, since there was no response, we close the thread.
You can open it again if there is still a need.
