### ISSUE TITLE
Alphavision Slender Line Plus motor canvas

### ISSUE THREAD

**Issue by TheChatty** [RFD-FHEM/RFFHEM#906]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: AlphaVision * HomeCinema
  - model name: Slender Line Plus (mine is 300x169 M228E)
  - pictures of the device / the board (very helpful) [see here](https://www.ebay.de/sch/i.html?_nkw=%22Slender+Line+Plus%22+%22300+x+169%22)

  
## Specifications 

  - Microcontroller: unknown
  - Version (Firmware): unknown
  

  - version | V 3.4.0 SIGNALESP cc1101 (chip CC1101) - compiled at Jul 16 2020 20:53:39
  - versionProtocols | 1.21
  - versionmodul | v3.4.4

The highest RSSI with most narrow bandwidth can be achieved at 433.88 MHz.

The remote has five buttons where "left" and "right" do not make the SignalDuino blink. Pressing the other buttons creates the following messages (every time with each button press, tried it multiple times):

- **center** (stop the motor at any position) --> **2** transmissions
```
  Read, msg READredu: MU;P0=-2341;P1=5206;P2=-571;P3=591;P4=-211;P5=207;D=0123452345252...
  --> Decoded matched MU protocol id 56 dmsg u56#A3479696010023978 length 68
  --> Decoded matched MU protocol id 56 dmsg u56#A34796960100238 length 60
  Read, msg READredu: MU;P0=-189;P1=204;P2=-584;P3=585;P4=5169;D=0123030303042...
  --> Decoded matched MU protocol id 24 dmsg u24#A3479696010020 length 56
  --> Decoded matched MU protocol id 56 dmsg u56#A3479696010023978 length 68
```

- **up** (roll in canvas or stop if moving down) --> **6** transmissions
```
  Read, msg READredu: MU;P0=-16412;P1=5195;P2=-598;P3=585;P4=-208;P5=192;D=0123452345252...
  --> Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68
  --> Decoded matched MU protocol id 56 dmsg u56#A347969601000B6 length 60
  Read, msg READredu: MU;P0=-207;P1=571;P2=5159;P3=-597;P4=191;D=0101010101023...
  --> Decoded matched MU protocol id 24 dmsg u24#A3479696010008 length 56
  --> Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68
  Read, msg READredu: MU;P0=-209;P1=580;P2=198;P3=-599;P4=-15720;P5=5166;D=010231010101010...
  --> Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68
  Read, msg READredu: MU;P0=-588;P1=576;P2=-206;P3=204;P4=5164;D=01230301230301230...
  --> Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68
  --> Decoded matched MU protocol id 61 dmsg P61#5CB86969FEF length 44
  Read, msg READredu: MU;P0=-591;P1=195;P2=575;P3=-203;P4=5166;D=010101010102...
  --> Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68
  --> Decoded matched MU protocol id 61 dmsg P61#5CB86969FE length 40
  Read, msg READredu: MU;P0=-200;P1=191;P2=-597;P4=582;D=01212121212121212121240121240121240121240401212124;CP=1;R=235;
  --> no protocol matched but RSSI twice as high --> maybe the control unit answered?
```

- **down** (roll out canvas or stop if moving up) --> **6** transmissions
```
Read, msg READredu: MU;P0=-18697;P1=5185;P2=-578;P3=598;P4=-210;P5=202;D=012345234...
--> Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68
--> Decoded matched MU protocol id 56 dmsg u56#A3479696010043A length 60
Read, msg READredu: MU;P0=-207;P1=203;P2=-582;P3=591;P4=5173;D=0123030303042301230...
--> Decoded matched MU protocol id 24 dmsg u24#A3479696010040 length 56 dispatch(1/4) RSSI = -21
--> Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68
Read, msg READredu: MU;P0=-191;P1=596;P2=212;P3=-578;P4=-15720;P5=5189;D=010102310...
--> Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68
Read, msg READredu: MU;P0=-579;P1=592;P2=-198;P3=200;P4=5176;D=0123030123030123030...
--> Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68
Read, msg READredu: MU;P0=-585;P1=204;P2=590;P3=-205;P4=5175;D=0101010101023101023...
--> Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68
Read, msg READredu: MU;P0=-189;P1=208;P2=-573;P3=602;D=01212121212121212121230121230121230121230301212123;CP=1;R=231;
  --> no protocol matched but RSSI twice as high --> maybe the control unit answered?
```

Verbose 5 logs:
[presslogs.zip](https://github.com/RFD-FHEM/RFFHEM/files/5575490/presslogs.zip)

Up/Down have similar messages thus I guess the following messages are important:
- `u56#A3479696010043B78` for **up**
- `u56#A3479696010023978` for **stop**
- `u56#A347969601000B7F8` for **down**

But trying to send those message like thise has no effect:
`set sduino sendMsg u56#A3479696010023978`

**Comment by elektron-bbs** [comment]
Ich denke, die Codes passen.
Die Fernbedienung scheint die gleichen Codes zu senden wie "Celexon Motorleinwand" im Beitrag https://forum.fhem.de/index.php/topic,52025.0.html im FHEM-Forum.

Noch nicht ganz sicher bin ich mir, ob Protokoll 24 "visivon remote with PT4450 OOK/ASK #39" dann entfallen kann.

Einige Fragen bleiben noch:
Gibt es weitere evtl. versteckte Tasten?
Ändern sich die Codes nach Batteriewechsel?
Ändern sich die Codes bei schwachen Batterien?

Bilder von der Fernbedienung wären brauchbar, möglichst auch von den "Innereien", wenn sie zerstörungsfrei zu öffnen ist. Schaltkreisbezeichnungen helfen oft bei der Bestimmung des verwendeten Protokolls.

**Comment by TheChatty** [comment]
Auf der Rückseite der Fernbedienung steht AC114-01B, RF-Transmitter, Frequency: 433.92MHz. Es gibt ein Loch, vermutlich mit einem Taster darunter. Ein Batteriewechsel hat keinen Code-Wechsel zur Folge - anbei ein frischer Log (hoch, stop, runter, stop):
[press-after-battery-replace.log](https://github.com/RFD-FHEM/RFFHEM/files/5578244/press-after-battery-replace.log)

Eine Web-Suche nach AC114 brachte [dieses Projekt](https://github.com/sui77/rc-switch/issues/163) hervor (samt Bild von innen und dem Taster). Nochmal hier von außen und innen:
![image](https://user-images.githubusercontent.com/4789510/99885901-866ccc80-2c38-11eb-9aab-97a81f6455ff.png)
![image](https://user-images.githubusercontent.com/4789510/99885920-c2079680-2c38-11eb-84d1-9b8a8c77bea3.png)

**Comment by elektron-bbs** [comment]
>Es gibt ein Loch, vermutlich mit einem Taster darunter.

Das müsstest du bitte noch genauer untersuchen. Ich habe noch Zweifel, ob die Ident der Fernbedienung "fest eingebrannt" ist, oder sie sich ändert.
Ansonsten geht es mit der Einbindung gut voran.

**Comment by TheChatty** [comment]
Ich habe beim Leinwand-Verkäufer eine Anleitung zum Anlernen von Fernbedienungen angefordert. Bis dahin würde ich nur ungern die Kopplung zwischen Sender und Empfänger auflösen.

**Comment by elektron-bbs** [comment]
OK, verstehe ich.

Die Fernbedienung scheint bei zweimaliger Bedienung der Tasten UP/DOWN jeweils bei der zweiten Betätigung einen anderen Code zu senden. Die zweite Betätigung löst doch ein STOP aus - sehe ich das richtig?
Ich habe hier:
https://github.com/akirjavainen/A-OK
einen Quellcode mit folgender Beschreibung gefunden:

```
* COMMAND BITS:
* 49 bits for a unique remote ID
* 7 bits for command (UP = 0001011, DOWN = 1000011, STOP = 0100011, PROGRAM = 1010011, AFTER UP/DOWN = 0100100)
* 5 bits are unknown (maybe some kind of checksum?)
* 4 bits at the end are always 0111, except for the AFTER UP/DOWN commands 1001
* 
* = 65 bits in total
```

Ich drösele das aber anders auf:
```
32 Bit ID
16 Bit unklar (könnten z.B. Kanäle sein, die FB gibt es mit bis zu 16 Kanälen)
 8 Bit Button
 8 Bit Checksumme
 1 Bit EOT
 3 Bit werden aufgefüllt, um Nibble zu übergeben
```
Bitte zeichne mal noch folgende Vorgänge auf:
Taste UP - 3 Sekunden warten - Taste UP
und dann noch mal dasselbe mit Taste DOWN.

**Comment by TheChatty** [comment]
Ich habe versucht, auf die wichtigen Meldungen (READredu -> Tastendruck, Decoded -> eine Interpretationsmöglichkeit) zu filtern:
```
14:16:20 READredu: MU;P0=-2635;P1=5196;P2=-568;P3=594;P4=-200;P5=198;D=012345234
14:16:20 Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68 
14:16:20 Decoded matched MU protocol id 56 dmsg u56#A3479696010043A length 60 di
14:16:20 READredu: MU;P0=-189;P1=203;P2=-591;P3=593;P4=-252;P5=5182;P6=-15724;D=
14:16:20 Decoded matched MU protocol id 24 dmsg u24#A3479696010024 length 56 dis
14:16:20 Decoded matched MU protocol id 56 dmsg u56#A3479696010043B7 length 64 d
14:16:20 READredu: MU;P0=-588;P1=195;P2=594;P3=-198;P4=5176;D=010231010232310101
14:16:20 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:20 READredu: MU;P0=-566;P1=587;P2=-204;P3=216;P4=5184;D=012303012303012303
14:16:20 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:21 READredu: MU;P0=-582;P1=207;P2=582;P3=-205;P4=5149;D=010101010102310102
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A347969601002498 length 64 d
14:16:21 READredu: MU;P0=-1070;P1=5194;P2=-570;P3=597;P4=-196;P5=200;D=012345234
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68 
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A3479696010043A length 60 di
14:16:21 READredu: MU;P0=-192;P1=204;P2=-585;P3=593;P4=5170;D=012303030304230123
14:16:21 Decoded matched MU protocol id 24 dmsg u24#A3479696010040 length 56 dis
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68 
14:16:21 READredu: MU;P0=-211;P1=586;P2=199;P3=-582;P4=-15715;P5=5203;D=01010231
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:21 READredu: MU;P0=-571;P1=592;P2=-196;P3=203;P4=5163;P5=-259;D=0123030123
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A347969601002498 length 64 d
14:16:21 READredu: MU;P0=-577;P1=212;P2=579;P3=-198;P4=5181;D=010101010102310102
14:16:21 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:21 Decoded matched MU protocol id 61 dmsg P61#5CB86969FE length 40 dispatc
14:16:23 READredu: MU;P0=-199;P1=205;P2=-586;P3=585;D=01212121212121212121230121
14:16:25 READredu: MU;P0=-28842;P1=5195;P2=-567;P3=598;P4=-194;P5=216;D=01234523
14:16:25 Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68 
14:16:25 Decoded matched MU protocol id 56 dmsg u56#A3479696010043A length 60 di
14:16:25 READredu: MU;P0=-196;P1=205;P2=-578;P3=588;P4=5175;D=012303030304230123
14:16:25 Decoded matched MU protocol id 24 dmsg u24#A3479696010040 length 56 dis
14:16:25 Decoded matched MU protocol id 56 dmsg u56#A3479696010043B78 length 68 
14:16:25 READredu: MU;P0=-199;P1=595;P2=214;P3=-580;P4=-15712;P5=5191;D=01010231
14:16:25 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:25 READredu: MU;P0=-582;P1=596;P2=-197;P3=208;P4=5186;D=012303012303012303
14:16:25 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:25 READredu: MU;P0=-577;P1=213;P2=591;P3=-203;P4=5184;D=010101010102310102
14:16:25 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:25 Decoded matched MU protocol id 61 dmsg P61#5CB86969FE length 40 dispatc
14:16:27 READredu: MU;P0=-197;P1=201;P2=-582;P3=596;D=01212121212121212121230121
14:16:34 READredu: MU;P0=-6807;P1=5196;P2=-589;P3=590;P4=-194;P5=190;D=012345234
14:16:34 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68 
14:16:34 Decoded matched MU protocol id 56 dmsg u56#A347969601000B6 length 60 di
14:16:35 READredu: MU;P0=-208;P1=596;P2=5187;P3=-582;P4=199;D=010101010102310431
14:16:35 Decoded matched MU protocol id 24 dmsg u24#A3479696010008 length 56 dis
14:16:35 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68 
14:16:35 READredu: MU;P0=-199;P1=590;P2=206;P3=-576;P4=5181;P5=-15726;D=01023101
14:16:35 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F length 64 d
14:16:35 READredu: MU;P0=-576;P1=594;P2=-193;P3=215;P4=5181;D=012303012303012303
14:16:35 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:35 READredu: MU;P0=-571;P1=216;P2=594;P3=-210;P4=5169;D=010101010102310102
14:16:35 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:36 READredu: MU;P0=-195;P1=201;P2=-584;P3=600;P4=5154;D=012121212121212121
14:16:36 Decoded matched MU protocol id 56 dmsg u56#A347969601002498 length 64 d
14:16:37 READredu: MU;P0=-18811;P1=5195;P2=-581;P3=598;P4=-192;P5=210;D=01234523
14:16:37 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68 
14:16:37 Decoded matched MU protocol id 56 dmsg u56#A347969601000B6 length 60 di
14:16:37 READredu: MU;P0=-207;P1=586;P2=5152;P3=-593;P4=194;D=010101010102310431
14:16:37 Decoded matched MU protocol id 24 dmsg u24#A3479696010008 length 56 dis
14:16:37 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68 
14:16:37 READredu: MU;P0=-196;P1=583;P2=203;P3=-579;P4=-15727;P5=5180;D=01023101
14:16:37 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:37 READredu: MU;P0=-583;P1=592;P2=-185;P3=211;P4=5178;D=012303012303012303
14:16:37 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:37 Decoded matched MU protocol id 61 dmsg P61#5CB86969FEF length 44 dispat
14:16:37 READredu: MU;P0=-580;P1=210;P2=598;P3=-191;P4=5167;D=010101010102310102
14:16:37 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:37 Decoded matched MU protocol id 61 dmsg P61#5CB86969FE length 40 dispatc
14:16:39 READredu: MU;P0=-199;P1=213;P2=-570;P3=588;D=01212121212121212121230121
14:16:42 READredu: MU;P0=-15846;P1=5195;P2=-570;P3=592;P4=-206;P5=208;D=01234523
14:16:42 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68 
14:16:42 Decoded matched MU protocol id 56 dmsg u56#A347969601000B6 length 60 di
14:16:42 READredu: MU;P0=-207;P1=590;P3=5170;P4=-580;P5=202;D=010101010103410541
14:16:42 Decoded matched MU protocol id 24 dmsg u24#A3479696010008 length 56 dis
14:16:42 Decoded matched MU protocol id 56 dmsg u56#A347969601000B7F8 length 68 
14:16:42 READredu: MU;P0=-195;P1=597;P2=209;P3=-580;P4=-15723;P5=5178;D=01023101
14:16:42 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:42 READredu: MU;P0=-582;P1=579;P2=-199;P3=209;P4=5187;D=012303012303012303
14:16:42 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:42 Decoded matched MU protocol id 61 dmsg P61#5CB86969FEF length 44 dispat
14:16:42 READredu: MU;P0=-581;P1=209;P2=577;P3=-203;P4=5180;D=010101010102310102
14:16:42 Decoded matched MU protocol id 56 dmsg u56#A3479696010024988 length 68 
14:16:42 Decoded matched MU protocol id 61 dmsg P61#5CB86969FE length 40 dispatc
14:16:43 READredu: MU;P0=-190;P1=200;P2=-590;P3=586;D=01212121212121212121230121
```
Ich halte alle Nachrichten, die nicht u56 mit Länge 64|68 sind, für Fehlinterpretationen. Dann ergibt gibt sich auch nur eine Interpretation je Tastendruck, womit sich weiter reduzieren lässt auf
```
<Taste nach unten, Leinwand fährt herunter>
14:16:20 u56#A3479696010043B78 length 68 dispatch(1/4) RSSI = -39.5
14:16:20 u56#A3479696010043B7 length 64 dispatch(1/4) RSSI = -38.5
14:16:20 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -38.5
14:16:20 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -38.5
14:16:21 u56#A347969601002498 length 64 dispatch(1/4) RSSI = -38.5
<Taste nach unten, Leinwand fährt weiter runter>
14:16:21 u56#A3479696010043B78 length 68 dispatch(1/4) RSSI = -39.5
14:16:21 u56#A3479696010043B78 length 68 dispatch(1/4) RSSI = -37.5
14:16:21 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -37.5
14:16:21 u56#A347969601002498 length 64 dispatch(1/4) RSSI = -37.5
14:16:21 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -38
14:16:23 unknown
<Taste nach unten, Leinwand fährt weiter runter>
14:16:25 u56#A3479696010043B78 length 68 dispatch(1/4) RSSI = -38.5
14:16:25 u56#A3479696010043B78 length 68 dispatch(1/4) RSSI = -38.5
14:16:25 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39.5
14:16:25 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39.5
14:16:25 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -40.5
14:16:27 unknown

<Taste nach oben, Leinwand stoppt nur>
14:16:34 u56#A347969601000B7F8 length 68 dispatch(1/4) RSSI = -39
14:16:35 u56#A347969601000B7F8 length 68 dispatch(1/4) RSSI = -39.5
14:16:35 u56#A347969601000B7F length 64 dispatch(1/4) RSSI = -39.5
14:16:35 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -40.5
14:16:35 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -40.5
14:16:36 unknown
<Taste nach oben, Leinwand fährt hoch>
14:16:36 u56#A347969601002498 length 64 dispatch(1/4) RSSI = -40.5
14:16:37 u56#A347969601000B7F8 length 68 dispatch(1/4) RSSI = -39
14:16:37 u56#A347969601000B7F8 length 68 dispatch(1/4) RSSI = -39
14:16:37 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39.5
14:16:37 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -40
14:16:37 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39.5
14:16:39 unknown
<Taste nach oben, Leinwand fährt weiter hoch>
14:16:42 u56#A347969601000B7F8 length 68 dispatch(1/4) RSSI = -38.5
14:16:42 u56#A347969601000B7F8 length 68 dispatch(1/4) RSSI = -38.5
14:16:42 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39.5
14:16:42 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39
14:16:42 u56#A3479696010024988 length 68 dispatch(1/4) RSSI = -39.5
14:16:43 unknown
```
Die unbekannte Nachricht, die mit ca. 1 Sekunde Verspätung gesendet wird, kommt manchmal nicht - oder wird nicht gehört. Die 64-Zeichen-Nachrichten sind vermutlich auch nur falsch verstanden.
Der Tastendruck scheint jedenfalls immer den gleichen Code zur Folge zu haben, aber die Interpretation (Stop-bei-Entgegengesetzt oder Bewegung) erfolgt in der Steuereinheit.

Die vollständige Log-Datei:
[buttons.log](https://github.com/RFD-FHEM/RFFHEM/files/5579590/buttons.log)

**Comment by elektron-bbs** [comment]
Ich gehe davon aus, das die Nachrichten 65 Bit lang sein müssen, weil im letzten Byte (vor der 8) eine Checksumme ist. Die restlichen 3 Bit werden aufgefüllt, damit Nibble übergeben werden können.
Hast du wirklich jeweils nur einmal die Taste betätigt? Es werden ja in jedem Abschnitt zwei verschiedene Nachrichten übertragen.

**Comment by TheChatty** [comment]
Die zweite Nachricht kommt ja sowohl bei hoch als auch bei runter. Für das letzte Logfile drückte ich 3x runter, 3x hoch.

**Comment by elektron-bbs** [comment]
Ja, scheint so, als ob bei jedem Tastendruck zuerst mehrmals der eigentliche Befehl gesendet wird nd anschließend mehrmals ein "AFTER_UPDOWN".
Das nachzubilden könnte schwierig werden, weil dann das Sendekommando zu lang für den SIGNALduino wird.

Kommen bei STOP auch zwei verschiedene Nachrichten?

**Comment by TheChatty** [comment]
Bei Stopp kommt immer nur u56#A3479696010023978. Gibt es keine Möglichkeit das frisch geloggte Signal zu senden bevor du das Protokoll ordentlich aufgenommen hast?

**Comment by elektron-bbs** [comment]
Das Senden müsste eigentlich beispielsweise mit "set sduino sendMsg P29#0xF7E#R4" funktionieren:

Aus der Doku:
Beispiel 0xhexdata: set sduino sendMsg P29#0xF7E#R4
Wird eine sende Kommando fuer die Hexfolge F7E anhand der protocol id 29 erzeugen. Die Nachricht soll 4x gesendet werden.

**Comment by TheChatty** [comment]
Wieso P29? Und 0xF7E? Bewirkt jedenfalls nichts. Ich hatte ja schon sendMsg wie oben in der issue description (siehe letzter Satz) genutzt, aber das funktioniert auch nicht.

**Comment by elektron-bbs** [comment]
Das war nur ein Beispiel, was ich vorhin auf die Schnelle aus der Doku kopiert habe.
Das, was du probiert hattest, konnte nicht funktionieren, da fehlt ein "0x", da es sich um Hex-Daten handelt. Probiere mal:

`set sduino sendMsg u56#0xA3479696010023978#R5`

Kann aber sein, das es auch nicht funktioniert, weil 3 Bit zu viel gesendet werden. Dann müsste Hex in Binär gewandelt werden, die 3 letzten Nullen entfernen, so das 65 Bit übrig bleiben. Der Sendebefehl ist dann (Achtung auch wieder nur ein Beispiel!):

Aus der Doku:
Beispiel binarydata: set sduino sendMsg P0#0101#R3
Wird eine sende Kommando fuer die Bitfolge 0101 anhand der protocol id 0 erzeugen.

Wenn auch das nicht funktioniert erwartet der Empfänger vielleicht tatsächlich die zweite Nachricht hinterher.

**Comment by TheChatty** [comment]
Oh man, weder das FHEM-Modul noch der ESP-Code bemängeln Dezimalzahlen mit Buchstaben... hier wäre eine Ausgabe wie "wrong decimal, **did you mean 0x**....?" wünschenswert. Und die Debugausgabe des Moduls sollte auch "Decoded matched MU protocol id 56 dmsg u56#**0x**...." ausgeben.
Ich hatte vorher schon mit "....#R1|2|3" und "...#C210|250|300" usw probiert, aber das 0x übersehen.

Am besten hätten wir von Anfang an über das Wiederholen der Signale mit SignalDuino reden sollen.

Langer Rede kurzer Sinn: Ich muss mindestens R3 verwenden, darunter passiert nichts. Aber ab R3 klappt es bisher jedes Mal:

- hoch: `set sduino sendMsg u56#0xA347969601000B7F8#R3`
- stopp: `set sduino sendMsg u56#0xA3479696010023978#R3`
- runter: `set sduino sendMsg u56#0xA3479696010043B78#R3`

Vielen Dank bis hierhin. Wenn ich noch helfen kann, sag bescheid.

**Comment by elektron-bbs** [comment]
Das ist doch schon mal ein Fortschritt!!!
Da muss ich mir hoffentlich beim Senden keine Gedanken mehr über die zweite Nachricht machen.

Ich habe zwischenzeitlich einen neuen Branch für die ersten Tests erstellt. Ein Update darauf kannst du mit folgendem Befehl durchführen:

`update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/master_feature_AC114-xxB/controls_signalduino.txt`

Es sollte dir nach einem Neustart dann nach drei empfangenen Nachrichten der Fernbedienung ein neues Device "AC114_01B_479696" angelegt werden.

Den Befehl "after_updown" muss ich dann sicher noch irgendwie unterdrücken.

**Comment by TheChatty** [comment]
Es dauerte etwas, weil der Restart nun nach Digest::CRC verlangte, das portable Perl-CPAN aber nicht mit Umlauten im Pfad klarkommt. Nach manueller Installation des CRC-Moduls gings aber weiter.
Was soll ich sagen, nach dreimaligem Drücken der Stop-Taste erschien besagtes Device. `set AC114_01B_479696 up` fuhr gerade meine Leinwand hoch. Nochmals danke.

**Comment by elektron-bbs** [comment]
Ist der Befehl "after_updown" zu irgend etwas zu gebrauchen, oder kann er tatsächlich weg?

**Comment by TheChatty** [comment]
Bei meiner Leinwand macht "after_updown" nichts - weder während sie fährt, noch wenn sie steht.

Der Hersteller hat mir geantwortet, wie man eine neue Fernbedienung anlernt (sowohl beim Sender als auch Empfänger Stopp gedrückt halten), aber das ändert nichts an den Codes.

Der Reset-Knopf im Empfänger ist für mich leider unzugänglich, da an die Decke geklebt und der Kleber sicherlich nicht stärker ist als die Gehäuse-Haltenasen (ich hätte beim Versuch, das Ding zu öffnen, also das ganze Gehäuse in der Hand).

**Comment by elektron-bbs** [comment]
Ich habe den Befehl "after_updown" jetzt aus der Setlist entfernt und beim Empfang wird er nicht ausgewertet. Ich habe keine Vorstellung, wozu der eigentlich gedacht ist.

Einen Code für "program" habe ich in https://github.com/akirjavainen/A-OK gefunden. Hoffe mal, das der stimmt.

Bitte mach nochmal ein Update, wie gestern und probiere dann ausgiebig.

**Comment by elektron-bbs** [comment]
Ich würde das Protokoll jetzt gerne in den Master-Branch überführen.
Wie sind deine Erfahrungen, gibt es noch irgendwelche Probleme oder Änderungswünsche?

**Comment by TheChatty** [comment]
Läuft perfekt.

**Comment by elektron-bbs** [comment]
Das Protokoll ist jetzt im Master-Branch. Ich schließe dieses Issue.

**Comment by TheChatty** [comment]
@elektron-bbs Ich würde unheimlich gern OpenMQTTGateway in Verbindung mit HomeAssistant einsetzen. OMG setzt auf rtl_433_ESP, jedoch [ohne flex decoder](https://github.com/NorthernMan54/rtl_433_ESP/issues/45#issuecomment-1454064799). Gibt es [dort ein Protokoll](https://github.com/NorthernMan54/rtl_433_ESP/tree/master/src/rtl_433/devices), welches ähnlich zu dem AC114-01B oder BeSmart von SignalDuino ist? Ich würde dann (gern mit deiner Unterstützung) beide Protokolle hinzufügen, damit OMG dieses empfangen und senden kann.

**Comment by elektron-bbs** [comment]
Ob es dort etwas ähnliches gibt, kann ich nicht beantworten. Im Prinzip müsste ja jede Fernbedienung als Beispiel herhalten können (ich finde dort auf Anhieb aber nur drei Stück). FS20 (https://github.com/NorthernMan54/rtl_433_ESP/blob/master/src/rtl_433/devices/fs20.c) erscheint mir z.B. am einfachsten anpassbar.

**Comment by TheChatty** [comment]
Mit der Hilfe von @zuckschwerdt habe ich [generic_motion](https://github.com/merbanan/rtl_433/blob/master/src/devices/generic_motion.c) als Grundlage genommen. Mit dem RTL2832U [funktioniert es](https://github.com/merbanan/rtl_433/issues/2242#issuecomment-1484099024) auch. Mit dem ESP und OpenMQTTGateway (also rtl_433_ESP) noch nicht zuverlässig. SignalDuino ist aber der Beweis, dass es nicht am ESP liegt.
Trotzdem danke für deine Suche nach einer passenden Vorlage.
