### ISSUE TITLE
Protokoll für Berner Garagentorantrieb GA401

### ISSUE THREAD

**Issue by anphiga** [RFD-FHEM/RFFHEM#91]
Hallo,
- Arduino Nano V 3.2.0-b12 SIGNALduino 
- 433Mhz China Sender+Empfänger (FS1000A+RV-5A)

Diesen Handsender:
[http://www.handsender-express.com/handsender+TEDSEN+:+SKX1MD](url)

Dieser Funkempfänger ist verbaut:
[http://www.hand-sender.de/Empfaenger/Tedsen/Empfaengerplatine-EKX1BE::79.html](url)

Signalduino liefert folgendes:

**Tor fährt zu**
MU;P0=-15829;P1=-3580;P2=1962;P3=-330;P4=245;P5=-2051;D=1234523232345234523232323234523234540023452323234523452323232323452323454023452323234523452323232323452323454023452323234523452323232323452323454023452323234523452323232323452323454023452323234523452323;CP=2;

**Tor fährt auf**
MU;P0=-1943;P1=1966;P2=-327;P3=247;P5=-15810;D=01230121212301230121212121230121230351230121212301230121212121230121230351230121212301230121212121230121230351230121212301230121212121230121230351230121212301230121212121230121230351230;CP=1;

**Dazwischen diese Einträge:**
2016.07.17 14:59:56 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.07.17 14:59:56 4: sduino: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2016.07.17 14:59:56 5: sduino: Starting demodulation at Position 2
2016.07.17 14:59:56 4: sduino: Fingerprint for MU Protocol id 34 -> unknown34 matches, trying to demodulate
2016.07.17 14:59:56 5: sduino: Starting demodulation at Position 2
2016.07.17 14:59:56 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.07.17 14:59:56 5: sduino: Starting demodulation at Position 2
2016.07.17 14:59:56 4: sduino: Fingerprint for MU Protocol id 37 -> weather37 matches, trying to demodulate
2016.07.17 14:59:56 5: sduino: Starting demodulation at Position 2
2016.07.17 14:59:56 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.07.17 14:59:56 4: sduino: Fingerprint for MU Protocol id 39 -> X10 Protocol matches, trying to demodulate
2016.07.17 14:59:56 5: sduino: Starting demodulation at Position 2
2016.07.17 14:59:56 4: sduino: Fingerprint for MU Protocol id 5 -> unitec6899 matches, trying to demodulate
2016.07.17 14:59:56 5: sduino: Starting demodulation at Position 1
2016.07.17 15:03:15 4: sduino: ping ...
2016.07.17 15:03:15 5: sduino: command for gets: P 
2016.07.17 15:03:15 5: sduino SW: P
2016.07.17 15:03:15 5: sduino/RAW (ReadAnswer): OK

Danke schön :-)

**Comment by sidey79** [comment]
23   2000,-330  8,-1      zero
45   250,-2000  1,-8      one
40   250,-15900 1,-63,6   end
17 Bit
clock 250

**Comment by sidey79** [comment]
Bitte mal Update auf die dev-r32 Version machen.
Die Demodulation habe ich anhand der Daten eingebaut. Seltsamer weise, kommt das gleiche Demodulationsergebnis für hoch und runter. Einfach mal testen.

**Comment by anphiga** [comment]
Hallo sidey,
vielen Dank erst mal für deine Mühe :-)) 
Getestet mit dem Update auf die dev-r32 Version:
```
2016.07.21 22:09:57 4: sduino/msg READ: ? Use one of V i R t X F S P C G 
2016.07.21 22:10:11 4: sduino/msg READ: MU;P0=-292;P1=359;P3=-15888;P5=-2023;P6=2014;P7=-204;D=156760601560156060606060156060151360156060601560156060606060156060151360156060601560;CP=6;
2016.07.21 22:10:11 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 20 -> livolo matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 2
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 2
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 2
2016.07.21 22:10:11 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 42 -> MKT motionsensor matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 34
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 44 -> Bresser7009995 matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 1
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 46 -> EKX1BE matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 0
2016.07.21 22:10:11 4: sduino: Fingerprint for MU Protocol id 5 -> unitec6899 matches, trying to demodulate
2016.07.21 22:10:11 5: sduino: Starting demodulation at Position 0
2016.07.21 22:10:53 4: sduino/msg READ: MU;P0=302;P1=-2041;P2=2000;P3=-309;P5=-15899;D=01230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301;CP=2;O;
2016.07.21 22:10:53 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.07.21 22:10:53 4: sduino: Fingerprint for MU Protocol id 29 -> HT12e remote matches, trying to demodulate
2016.07.21 22:10:53 5: sduino: Starting demodulation at Position 2
2016.07.21 22:10:53 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.07.21 22:10:53 5: sduino: Starting demodulation at Position 2
2016.07.21 22:10:53 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.07.21 22:10:53 4: sduino: Fingerprint for MU Protocol id 42 -> MKT motionsensor matches, trying to demodulate
2016.07.21 22:10:53 5: sduino: Starting demodulation at Position 26
2016.07.21 22:10:53 4: sduino: Fingerprint for MU Protocol id 44 -> Bresser7009995 matches, trying to demodulate
2016.07.21 22:10:53 5: sduino: Starting demodulation at Position 1
2016.07.21 22:10:53 4: sduino: Fingerprint for MU Protocol id 46 -> EKX1BE matches, trying to demodulate
2016.07.21 22:10:53 5: sduino: Starting demodulation at Position 0
2016.07.21 22:10:53 5: sduino: dispatching bits: 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1
2016.07.21 22:10:53 4: sduino: decoded matched MU Protocol id 46 dmsg u#468A09 length 16
2016.07.21 22:10:53 5: sduino: converted Data to (u#468A09)
2016.07.21 22:10:53 5: sduino dispatch u#468A09
2016.07.21 22:10:53 3: sduino: Unknown code u#468A09, help me!
2016.07.21 22:10:53 5: sduino: dispatching bits: 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1
2016.07.21 22:10:53 4: sduino: decoded matched MU Protocol id 46 dmsg u#468A09 length 16
2016.07.21 22:10:53 5: sduino: converted Data to (u#468A09)
2016.07.21 22:10:53 4: sduino: Dropped (u#468A09) due to short time or equal msg
2016.07.21 22:10:53 5: sduino: dispatching bits: 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1
2016.07.21 22:10:53 4: sduino: decoded matched MU Protocol id 46 dmsg u#468A09 length 16
2016.07.21 22:10:53 5: sduino: converted Data to (u#468A09)
2016.07.21 22:10:53 4: sduino: Dropped (u#468A09) due to short time or equal msg
2016.07.21 22:10:53 5: sduino: dispatching bits: 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1
2016.07.21 22:10:53 4: sduino: decoded matched MU Protocol id 46 dmsg u#468A09 length 16
2016.07.21 22:10:53 5: sduino: converted Data to (u#468A09)
2016.07.21 22:10:53 4: sduino: Dropped (u#468A09) due to short time or equal msg
2016.07.21 22:10:53 5: sduino: dispatching bits: 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1
2016.07.21 22:10:53 4: sduino: decoded matched MU Protocol id 46 dmsg u#468A09 length 16
2016.07.21 22:10:53 5: sduino: converted Data to (u#468A09)
2016.07.21 22:10:53 4: sduino: Dropped (u#468A09) due to short time or equal msg
2016.07.21 22:10:53 5: sduino: dispatching bits: 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1
2016.07.21 22:10:53 4: sduino: decoded matched MU Protocol id 46 dmsg u#468A09 length 16
2016.07.21 22:10:53 5: sduino: converted Data to (u#468A09)
2016.07.21 22:10:53 4: sduino: Dropped (u#468A09) due to short time or equal msg
2016.07.21 22:14:56 5: sduino/GetUpdate: ping was not reported in time, disconnecting device
2016.07.21 22:14:56 1: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0 disconnected, waiting to reappear (sduino)
2016.07.21 22:15:06 3: Setting sduino serial parameters to 57600,8,N,1
2016.07.21 22:15:06 1: define: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0
2016.07.21 22:15:06 1: init: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0
2016.07.21 22:15:06 5: sduino SW: XQ
2016.07.21 22:15:06 5: sduino SW: V
2016.07.21 22:15:09 5: sduino SW: V
2016.07.21 22:15:09 5: sduino/RAW (ReadAnswer): V 3.2.0-b24 SIGNALduino - compiled at May 14 2016 00:06:
2016.07.21 22:15:09 5: sduino/RAW (ReadAnswer): 40

2016.07.21 22:15:09 5: sduino: command for gets: ? 
2016.07.21 22:15:09 5: sduino SW: XE
2016.07.21 22:15:09 1: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0 reappeared (sduino)
2016.07.21 22:15:09 5: sduino SW: ?
2016.07.21 22:15:09 4: sduino/msg READ: ? Use one of V i R t X F S P C G 
2016.07.21 22:15:09 5: sduino/HandleWriteQueue: nothing to send, stopping timer
```

????????

Das erste msg/Read hat das Tor geschlossen und das zweite wieder geöffnet. 

`Internals: 
   Clients    :IT:CUL_TCM97001:SIGNALduino_RSL:OREGON:CUL_TX:SD_AS:Hideki:SD_WS07:SD_WS09:SD_WS:RFXX10REC:Dooya:SOMFYSIGNALduino_un: 
   DEF        /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0 
   DMSG       u#468A09 
   DeviceName /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A50285BI-if00-port0@57600 
   FD         9 
   Interval   300 
   MSGCNT     1 
   NAME       sduino 
   NR         63 
   PARTIAL 
   RAWMSG     MU;P0=302;P1=-2041;P2=2000;P3=-309;P5=-15899;D=01230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301230123232323230123230105230123232301;CP=2;O; 
   STATE      opened 
   TIME       1469131853 
   TYPE       SIGNALduino 
   unknownmessages 2016-07-21 22:10:11-MU;P0=-292;P1=359;P3=-15888;P5=-2023;P6=2014;P7=-204;D=156760601560156060606060156060151360156060601560156060606060156060151360156060601560;CP=6; 
   Matchlist: 
     10:SD_WS07 ^P7#[A-Fa-f0-9]{6}F[A-Fa-f0-9]{2} 
     11:SD_WS09 ^P9#[A-Fa-f0-9]+ 
     12:SD_WS   ^W\d+#.* 
     13:RFXX10REC ^(20|29)[A-Fa-f0-9]+ 
     14:Dooya   ^P16#[A-Fa-f0-9]+ 
     15:SOMFY   ^YsA[0-9A-F]+ 
     1:IT       ^i...... 
     2:CUL_TCM97001 ^s[A-Fa-f0-9]+ 
     3:SIGNALduino_RSL ^r[A-Fa-f0-9]+ 
     4:OREGON   ^(3[8-9A-F]|[4-6][0-9A-F]|7[0-8]).* 
     5:CUL_TX   ^TX.......... 
     6:SD_AS    ^P2#[A-Fa-f0-9]{7,8} 
     7:Hideki   ^P12#75[A-F0-9]+ 
     X:SIGNALduino_un ^[uP]\d+#.* 
   QUEUE: 
   Readings: 
     2016-07-17 17:15:21   Version         V 3.2.0-b12 SIGNALduino - compiled at Feb 13 2016 21:34:09 
     2016-07-21 22:15:09   cmds            ?UseoneofViRtXFSPCG 
     2016-07-16 01:24:46   config          MS=1;MU=1;MC=1 
     2016-07-21 18:42:20   ping            No answer 
     2016-07-21 22:15:09   state           opened 
     2016-07-21 22:15:09   version         V 3.2.0-b24 SIGNALduino - compiled at May 14 2016 00:06:40
 `
Ich steig da nicht mehr durch :-((

Viele Grüße

**Comment by anphiga** [comment]
Seit heute habe ich das Geetech 433MhZ Superhetordyne 3400RF Set am Arduino angeschlossen..
[http://www.ebay.de/itm/381199588108?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT](url)

**Comment by anphiga** [comment]
Kann ich hier noch behilflich sein? Wäre Klasse, wenn das funktionieren würde :-)

**Comment by HomeAutoUser** [comment]
Hallo @anphiga,

lang ist her dein Post.
Wie ist der aktuelle Stand? Besteht noch Bedarf?

**Comment by elektron-bbs** [comment]
Dieses Protokoll ist seit kurzem in der Entwicklerversion implementiert.
Protokoll 46
Tedsen Fernbedienungen u.a. für Berner Garagentorantrieb GA401 und Geiger Antriebstechnik Rolladensteuerung
Ich schließe dieses Issue.
