### ISSUE TITLE
"get raw" vs "set raw"

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#924]
Bevor ich mich jetzt damit plage, die Tests zum Laufen zu bringen (https://github.com/RFD-FHEM/RFFHEM/tree/master_feature_get-raw), frage ich lieber erst mal an, ob die Änderung überhaupt gewünscht ist.

Schon seit längerem stört es mich, das bei den Befehlen "set sduino raw" und "get sduino raw" die gleiche Hilfe unter dem Befehl angezeigt wird. Das ist extrem irreführend.

Nun wollte ich "get sduino raw" in "get sduino rawmsg" ändern, um dieses Problem zu umgehen. In der sub SIGNALduino_Get_Raw wird ja sowieso nur noch das dispatchen von RAW-MSG unterstützt.

Lokal bringt diese Änderung den gewünschten Erfolg - nur die Tests machen mal wieder einen Strich durch die Rechnung :-(

**Comment by sidey79** [comment]
Die Idee finde ich gut.
Von mir aus kann der Befehl auch ganz raus 👍 

Oder man benennt ihn testMsg oder sowas, aber eigentlich kann man den auch rauslassen denke ich. Naja vielleicht benutzt das ja jemand mal... ich halt nicht mehr

**Comment by HomeAutoUser** [comment]
Einer Umbenennung stehe ich offen gegenüber und das es dann in der Commandref dann richtig angezeigt wird 👍 

Die derzeitige Situation der gleichen Namen in der commandref ist auch bekannt als Problematik im Forum. Es war mal im Gespräch, das der Zusammenbau der Commandref überarbeitet werden sollte mit der Zielsetzung, set / raw Parameter mit zu verarbeiten um gleichnamige Befehle in set / raw unterscheiden zu können.

Eine komplette Entfernung würde ich nicht vornehmen. Der Vorschlag „get sduino rawmsg“ ist sehr gut 👍

**Comment by HomeAutoUser** [comment]
Einer Umbenennung stehe ich offen gegenüber und das es dann in der Commandref dann richtig angezeigt wird 👍 

Die derzeitige Situation der gleichen Namen in der commandref ist auch bekannt als Problematik im Forum. Es war mal im Gespräch, das der Zusammenbau der Commandref überarbeitet werden sollte mit der Zielsetzung, set / raw Parameter mit zu verarbeiten um gleichnamige Befehle in set / raw unterscheiden zu können.

Eine komplette Entfernung würde ich nicht vornehmen. Der Vorschlag „get sduino rawmsg“ ist sehr gut 👍

**Comment by HomeAutoUser** [comment]
Ich glaube @elektron-bbs hat hier ein wenig "geschlampt" *grins*
Bitte auch bei solchen Änderung die Logausgaben jeweils mit anpassen.

```
sub SIGNALduino_Get_RawMsg {
....
    $hash->{logMethod}->( $hash->{NAME}, 4, "$hash->{NAME}: msg get raw: $a[1]");
```

Die Ausgabe müsste noch angepasst werden um nicht Verwirrungen aufkommen zu lassen.
