### ISSUE TITLE
00_SIGNALduino ist deaktivated if Digest::CRC is missing

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#927]
## Expected Behavior

Module ist in some standby mode but not fully deactivated!

## Actual Behavior

Module ist completly deactivated if DIGEST::CRC is missing.

```
 Can't locate Digest/CRC.pm in @INC (you may need to install the Digest::CRC module) (@INC contains: ./lib ./FHEM . /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/arm-linux-gnueabihf/perl5/5.24 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base ./FHEM/lib) at ./FHEM/00_SIGNALduino.pm line 27, <$fh> line 1033.
BEGIN failed--compilation aborted at ./FHEM/00_SIGNALduino.pm line 27, <$fh> line 1033.

2021.01.09 18:59:40 0: Can't locate Digest/CRC.pm in @INC (you may need to install the Digest::CRC module) (@INC contains: ./lib ./FHEM . /etc/perl /usr/local/lib/arm-linux-gnueabihf/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/arm-linux-gnueabihf/perl5/5.24 /usr/share/perl5 /usr/lib/arm-linux-gnueabihf/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/arm-linux-gnueabihf/perl-base ./FHEM/lib) at ./FHEM/00_SIGNALduino.pm line 27, <$fh> line 1033.
BEGIN failed--compilation aborted at ./FHEM/00_SIGNALduino.pm line 27, <$fh> line 1033.

2021.01.09 18:59:40 1: reload: Error:Modul 00_SIGNALduino deactivated:
```

## Steps to Reproduce the Problem

  1. Prepare System without DIGEST::CRC
  2. start fhem
  3. Module is deactivated

## Specifications

  - Versionmodul (FHEM Module): 3.5.1+05012021

**Comment by elektron-bbs** [comment]
Da  Digest::CRC in der 00_SIGNALduino.pm m.E. sowieso noch nicht benötigt wird, würde ich es dort noch nicht laden, sondern erst in den Modulen die es benötigen prüfen, ob es installiert ist.
In den Modulen 14_SD_WS.pm und 14_SD_AS.pm hatte ich es dementsprechend eingebaut.

**Comment by sidey79** [comment]
Ja, ich bin dran.
Es wird in SD_Protocols benötigt, das Modul funktioniert auch erst mal ohne, aber ich möchte eine brauchbare Meldung ausgeben und das Modul in einen Error state versetzen.

Ist ziemlich blöd, wenn das nach einem FHEM Update dann nicht mehr geht, aber wie soll man dem Benutzer das mitteilen, so dass er es nach dem Update Befehl sieht?

**Comment by elektron-bbs** [comment]
Das komplette Modul würde ich nicht außer Gefecht setzen. CRC wird dort im Moment nur von 2 Protokollen genutzt. Da die CRC-Prüfung eigentlich nur ein zusätzliches Feature ist, sollte eine Log-Meldung mit verbose 1 reichen, wenn es fehlt.

Im Modul 14_SD_AS.pm habe ich es so gelöst:
```
    my $rc = eval {
      require Digest::CRC;
      Digest::CRC->import();
      1;
    };
    if ($rc) {
      my $ctx = Digest::CRC->new( width => 8, poly => 0x31 );
      my $calcCrc = $ctx->add( pack 'H*', substr( $rawData, 0, 8 ) )->digest;
      my $checksum = sprintf( "%d", hex( substr( $rawData, 8, 2 ) ) );
      if ($calcCrc != $checksum) {
        Log3 $iohash, 3, "$name: SD_AS ERROR - Calculated CRC ($calcCrc) not match received ($checksum) in msg $rawData";
        return q{};
      }
    } else {
      Log3 $name, 1, "$name: SD_AS ERROR - CRC not load, please install modul Digest::CRC";
      # return q{};
    }
```

**Comment by sidey79** [comment]
Hatte ich auch kurz überlegt, aber da Digest::CRC nicht in ein oder zwei Funktionen eingebunden wird, sondern global wird es auch als globaler Fehler betrachtet.
Da ohnehin ein Objekt geliefert wird, erscheint mfr das ja ein wenig gebastel ein Objekt zu haben, bei dem nicht alle Methoden funktionieren.

Ich bin jetzt ohnehin erst mal im 00_SIGNALduino Modul daran, einen Fehler in den mittels use eingebundenen Modulen ordentlich zu berücksichtigen. Da habe ich wohl mal etwas verschlimmbessert :/

PS: Require würde ich nicht einsetzen, und bei use bleiben.

**Comment by sidey79** [comment]
@elektron-bbs 
Ich habe das nun mal lauffähig hingebogen und am Beispiel Digest::CRC ausgetüftelt wie es in etwa gehen könnte, wenn ein benötigtes Modul nicht geladen werden kann.

SD_Protocols meldet einen Fehler, wenn das Einbinden von z.B. Digest::CRC nicht klappt.

00_SIGNALduino.pm bindet die SD_Protocols in einem eval ein, welches FHEM nicht daran hindert das Modul zu laden, wenn ein Fehler auftritt.
Die Fehlermeldung wird gespeichert und sobald _Define aufgerufen wird, wird auch die besagte Fehlermeldung berücksichtigt.

Sieht dann so aus in FHEMWeb
![image](https://user-images.githubusercontent.com/7968127/104134310-08e85180-5389-11eb-9946-78c4ce89eab3.png)

Und so im Logfile:
```
2021.01.10 21:11:16.467 1: sduino_dummy: Define, device is none, commands will be echoed only
2021.01.10 21:11:16.467 2: sduino_dummy: modules with error: lib::SD_Protocols 
2021.01.10 21:11:16.467 1: sduino_dummy: Error loading Protocol Hash. Module is in inoperable mode. Error messages:(You need to install the Digest::CRC module at (eval 95) line 1.
Compilation failed in require at (eval 95) line 1, <$fh> line 48.
BEGIN failed--compilation aborted at (eval 95) line 1, <$fh> line 48.
 to be able to load module lib::SD_Protocols  and get operational mode)
```

Es ist natürlich blöde, dass das Modul nach einem Update auf einmal einfach nicht mehr läuft. Ich wüsste aber auf Anhieb nicht, wie wir herausfinden könnten, dass CRC für Protokoll 101 und 103 verwendet wird und diese deaktivieren könnten.
Dazu wäre ja eine art "Selbsttest" notwendig :)

**Comment by elektron-bbs** [comment]
Nach meinem Vorschlag würden die Protokolle weiterhin funktionieren, halt ohne CRC-Prüfung. Irgendwann wird der User schon mal ins Log sehen...

**Comment by sidey79** [comment]
Das müsste dann in den beiden SD_Protocols Methoden eingebunden werden oder was meinst Du?

**Comment by elektron-bbs** [comment]
Genau so meine ich das.

**Comment by sidey79** [comment]
Vielleicht lohnt sich da eine kleine Lib, das müsste dann ja nur 1* programmiert werden

**Comment by elektron-bbs** [comment]
Tja, ich weiß nicht, ob sich das wegen den 3 Zeilen Code rentiert. Außerdem sind dann wieder mehrere Module von einem abhängig. Wenn dort etwas geändert wird, funktionieren u.U. alle anderen wieder nicht mehr.

**Comment by HomeAutoUser** [comment]
>Wenn dort etwas geändert wird, funktionieren u.U. alle anderen wieder nicht mehr.

Gibt es Beispiele wo die Module auch ohne dem Signalduino Modul laufen?
Sollte es dies geben, so wäre es nicht sinnvoll diese abhängig von der Lib zu machen denke ich.

**Comment by sidey79** [comment]
Die Idee die ich hatte war eher, dass man den Code für alle FHEM Entwickler 1x bereitstellt und dann Module die optional sind darüber eingebunden werden können.
Das dürften dann auch mehr als nur drei Zeilen code werden, wenn man dazu noch ein bisschen was dazupackt wie Meldungen zurückgeben und Fehlerbehandlung.

Riesen groß wird die Sache natürlich nicht, andererseits habe ich schon dinge gesehen, wo sich manch einer abgebrochen hat nur um am ende irgendein JSON Modul zu laden und sich durch zu hangeln, welches denn gerade verfügbar ist.

Bestimmt gibt es da auch was auf cpan, aber das bekommen wir in FHEM nicht einfach rein.
Was das mit dem funktionieren angeht, ist es bei zentralen Funktionen richtig, dass es Abhängigkeiten gibt. Andererseits, muss man den Code dann auch nur 1x testen und weiss, dass er wirklich funktioniert. Hier haben wir ja heute schon mehrere Implementierungsarten die etwas unterschiedlich arbeiten und auch funktionieren.

**Comment by elektron-bbs** [comment]
Ich hole das Thema mal wieder nach oben: https://github.com/RFD-FHEM/RFFHEM/issues/992#issuecomment-879988978

**Comment by sidey79** [comment]
Ich habe hinsichtlich meiner Idee nichts unternehmen können.

Im groben hatte ich an etwas in dieser Art gedacht:
https://metacpan.org/pod/Module::Installed::Tiny

Aber genauer durchdachte ist das nicht, an welcher Stelle dann diese Prüfung erfolgt

**Comment by elektron-bbs** [comment]
Das Modul ist aber m.E. auch nicht von Haus aus installiert.
Das einfachste wäre, wie auch auf der verlinkten Seite vorgeschlagen:
```
if (eval { require Foo::Bar; 1 }) {
    # Foo::Bar is available
}
```

So ähnlich hatte ich es auch schon hier https://github.com/RFD-FHEM/RFFHEM/issues/927#issuecomment-757492236 erwähnt.

**Comment by sidey79** [comment]
Das stimmt, ich meinte auch eher eine Funktionalität wie in besagtem Modul.
Quasi ohne es zu laden zu testen ob es vorhanden ist.

**Comment by elektron-bbs** [comment]
Das müsste doch erledigt sein?
Wenn doch nicht, bitte wieder öffnen.

**Comment by sidey79** [comment]
Ja ist so
