### ISSUE TITLE
Todos und Wünsche für das r3.3.0

### ISSUE THREAD

**Issue by Ralf9** [RFD-FHEM/RFFHEM#94]
Hallo Sidey,

könntest Du mir bitte eine Firmware 3.3.0-b35 bauen?
Ich würde gerne in der "sub SIGNALduino_Read" das herausfiltern der cmdResponse vereinfachen.
Ich würde das mit einem neuen Nachrichtentyp "MR" oder "MA" machen.
Damit würde auch dies einfacher:
`if ( $rmsg && !SIGNALduino_Parse($hash, $hash, $name, $rmsg) && $hash->{getcmd} )`

In der Firmware könnte dies z.B. so aussehen:
```

preamble = "";
postamble = ";";
preamble.concat(MSG_START);
preamble.concat("MR;");

postamble.concat(MSG_END);
postamble.concat('\n');

Serial.print(preamble);
Serial.print("V " PROGVERS " SIGNALduino - compiled at " __DATE__ " " __TIME__);
Serial.print(postamble);

Serial.print(preamble);
Serial.print(freeRam());
Serial.print(postamble);
```

Gruß Ralf

**Comment by sidey79** [comment]
Kann ich machen, dann wäre die Firmware aber definitiv nicht mehr kompatibel mit dem FHEM Modul 3.2

Wofür steht denn MR oder MA und wieso können wir die Nachricht nicht mit einer Regex auf ^V  herausfiltern?

**Comment by Ralf9** [comment]
MR = response
MA = answer
Ich finde damit können die cmdResponses einfacher und sauberer herausgefiltert werden.

**Comment by Ralf9** [comment]
Ich habe es mir nochmals genau angeschaut und mir Gedanken darüber gemacht.
Du hast Recht, so wies Du es programmiert hast, wird die cmdResponse auch gut erkannt.
Damit wir zur 3.2 Firmware kompatibel bleiben, müsste die Firmwareversion auch in den hash geschrieben werden und könnte dann bei der SIGNALduino_Parse_MC abgefragt werden damit bei der 3.2 nicht invertiert wird

**Comment by sidey79** [comment]
Naja, ich meinte mit Kompatibel nicht zwingend, dass wir für jede Änderung abfangen.

Ungünstig wäre aus meiner Sicht nur, wenn der uC nach einem Update der Module überhaupt nicht mehr initialisiert werden kann.

Aber alle Veränderungen sollten wir nicht abhängig von der Firmware realisieren.
Die Notwendigkeit eine alte Firmware einzusetzen ist doch eher gering.

**Comment by Ralf9** [comment]
Da sich der Aufwand in Grenzen hält, damit bei der Firmware 32 auch das MC funktioniert, halte ich es für sinnvoll bei der Invertierung die Abfrage einzubauen.

Ich habe damit angefangen bei der  00_SIGNALduino.pm  das DevIo_OpenDev und die Initialisierung auf nonBlocking umzustellen. Ich habe die 00_HMUARTLGW.pm als Vorlage genommen.
Es muß noch etwas ergänzt und optimiert werden.
Wenn es ok ist, mache ich mal ein commit.

**Comment by Ralf9** [comment]
Ich bin jetzt mit dem Init und dem Keepalive soweit fertig. Es müsste jetzt komplett blockierungs frei sein.

Die Version 3.3 wäre evtl auch eine Gelegenheit im Forum ein neue Thema aufzumachen z.B.
" Signalduino Entwicklung Version 3.3"
Dies hätte u.a. den Vorteil, daß die erste Nachricht Dir gehört.
Was hältst Du davon?

Hier sind noch ein paar Todos für die r3.3.0:
- [ ] Firmware 3.3.0-... bauen
- [ ] sub SIGNALduino_DoInit:   # Todo:  $hash->{QUEUE} loeschen
- [ ] sub SIGNALduino_parseResponse:  #  Todo ?UseoneofViRtXFSPCG  frueher sah es so aus: V i R t X F S P C G

**Comment by sidey79** [comment]
Ja, der Foren Thread ist mir ein Problem.
Das sind zu viele Beiträge und auch zu viele Themen rund um das Einbinden neuer Sensoren.

**Comment by sidey79** [comment]
Firmware 3.3.0 ist compiliert und im Branch eingecheckt.

**Comment by sidey79** [comment]
Folgende Module kommen in R 3.3.0.

QS Prüfung (POD Summary ok?)
- [ ] 00_SIGNALduino
- [ ] 14_Hideki
- [ ] 14_SD_WS
- [ ] 14_SD_WS_Maverick
- [ ] 14_SD_WS07
- [ ] 14_SD_WS09
- [ ] 14_SIGNALduino_RSL
- [ ] 90_SIGNALduino_un
- [ ] 98_Dooya

Kein Bestandteil von Release 3.3.0
- [ ] 41_Orgon   (Modul hat einen anderen Besitzer)
- [ ] 14_SD_AS   (Spezielles Modul)
- [ ] 14_SD_UT   (Unbekannter Status, keine Doku, kein podmarker)
- [ ] 14_BresserTemeo   (Soll nach SD_WS konvertiert werden. Release 3.3.1)

**Comment by Ralf9** [comment]
offene Todos 00_SIGNALduino:

 todo:  $hash->{QUEUE} loeschen

whitelistIDs in der device help nach englisch übersetzen

**Comment by sidey79** [comment]
fertig
