### ISSUE TITLE
Remotecontrol RC-120 for ESMART / Motorleinwand

### ISSUE THREAD

**Issue by betrev** [RFD-FHEM/RFFHEM#942]
##  Specifications for new sensor / switch / or other device ... 

  - manufacturer: **ESMART Professional MIMOTO** (Fernbedienung für motorbetriebene Leinwand) / https://www.amazon.de/gp/product/B01MQ222IA/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
  - model name: **RC-120**
  - pictures of the device / the board (very helpful)
![20210211_162508](https://user-images.githubusercontent.com/36778900/107658085-16457400-6c86-11eb-9a5b-29e7c51a0633.jpg)
![20210211_162515](https://user-images.githubusercontent.com/36778900/107658108-1a719180-6c86-11eb-8a1c-e3e5ed8ab2ae.jpg)
![20210211_162525](https://user-images.githubusercontent.com/36778900/107658114-1ba2be80-6c86-11eb-955a-d20b499363ba.jpg)

  
## Specifications 

  - Microcontroller: ?
  - Version (Firmware): ?
  

  - Versionmodul (FHEM Module): V 3.4.0 SIGNALduino cc1101 (433 Mhz ) - compiled at Jul 16 2020 20:52:35
  

v3.4.4
[RC-120.txt](https://github.com/RFD-FHEM/RFFHEM/files/5966442/RC-120.txt)

Code 0010 (Fernbedienung "UP") und 1000 (Fernbedienung "STOP") werden nicht erkannt, 3. Code (Fernbedienung "DOWN") wird bei automatisch angelegten IT Device in FHEM als "ON" erkannt. sieht Verbose 4 Log-Auszug.

**Comment by elektron-bbs** [comment]
Das hätte zwar besser ins FHEM-Forum https://forum.fhem.de/index.php/board,24.0.html gepasst, da das IT-Modul nicht von uns ist.
Da ich aber eine ähnliche Fernbedienung habe kann ich vielleicht helfen. Ich habe die Nachrichten von dir mal dispatcht und dann die Attribute ergänzt:

```
define IT_1527x69e49 IT 1527x69e49 0100 0000
setuuid IT_1527x69e49 60255b7b-f33f-b27f-befe-20f330d6923ba8e9
attr IT_1527x69e49 IODev sduinoUSB0
attr IT_1527x69e49 protocol V1
attr IT_1527x69e49 room Test
attr IT_1527x69e49 userV1setCodes DOWN:0100 UP:0010 STOP:1000
attr IT_1527x69e49 webCmd UP:STOP:DOWN
```
Den Gerätenamen und IODev musst du natürlich noch an deine Gegebenheiten anpassen.

**Comment by betrev** [comment]
Vielen Dank. Das scheint zu funktionieren.

 

LG

 

Marc

 

 

Von: Udo <notifications@github.com> 
Gesendet: Donnerstag, 11. Februar 2021 18:10
An: RFD-FHEM/RFFHEM <RFFHEM@noreply.github.com>
Cc: betrev <md4791@yahoo.de>; Author <author@noreply.github.com>
Betreff: Re: [RFD-FHEM/RFFHEM] Remotecontrol RC-120 for ESMART / Motorleinwand (#942)

 

Das hätte zwar besser ins FHEM-Forum https://forum.fhem.de/index.php/board,24.0.html gepasst, da das IT-Modul nicht von uns ist.
Da ich aber eine ähnliche Fernbedienung habe kann ich vielleicht helfen. Ich habe die Nachrichten von dir mal dispatcht und dann die Attribute ergänzt:

define IT_1527x69e49 IT 1527x69e49 0100 0000
 
setuuid IT_1527x69e49 60255b7b-f33f-b27f-befe-20f330d6923ba8e9
 
attr IT_1527x69e49 IODev sduinoUSB0
 
attr IT_1527x69e49 protocol V1
 
attr IT_1527x69e49 room Test
 
attr IT_1527x69e49 userV1setCodes DOWN:0100 UP:0010 STOP:1000
 
attr IT_1527x69e49 webCmd UP:STOP:DOWN
 

Den Gerätenamen und IODev musst du natürlich noch an deine Gegebenheiten anpassen.

**Comment by elektron-bbs** [comment]
Sehr schön, dann schließe ich das Issue.
