### ISSUE TITLE
PERL WARNING

### ISSUE THREAD

**Issue by elektron-bbs** [RFD-FHEM/RFFHEM#949]
## Expected Behavior
no Warnings

## Actual Behavior
```
2021.03.14 09:10:05 1: PERL WARNING: Subroutine Utils_Initialize redefined at FHEM/99_Utils.pm line 10.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine time_str2num redefined at FHEM/99_Utils.pm line 16.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine min redefined at FHEM/99_Utils.pm line 26.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine max redefined at FHEM/99_Utils.pm line 36.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine minNum redefined at FHEM/99_Utils.pm line 46.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine maxNum redefined at FHEM/99_Utils.pm line 56.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine abstime2rel redefined at FHEM/99_Utils.pm line 67.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine defInfo redefined at FHEM/99_Utils.pm line 83.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine SVG_time_to_sec redefined at FHEM/99_Utils.pm line 99.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine trim redefined at FHEM/99_Utils.pm line 125.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine ltrim redefined at FHEM/99_Utils.pm line 138.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine rtrim redefined at FHEM/99_Utils.pm line 150.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine UntoggleDirect redefined at FHEM/99_Utils.pm line 162.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine UntoggleIndirect redefined at FHEM/99_Utils.pm line 185.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine IsInt redefined at FHEM/99_Utils.pm line 212.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine fhemNc redefined at FHEM/99_Utils.pm line 219.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine round redefined at FHEM/99_Utils.pm line 238.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine sortTopicNum redefined at FHEM/99_Utils.pm line 245.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine Svn_GetFile redefined at FHEM/99_Utils.pm line 265.
2021.03.14 09:10:05 1: PERL WARNING: Subroutine WriteFile redefined at FHEM/99_Utils.pm line 295.
```

## Steps to Reproduce the Problem

  1. shutdown restart 
  2. view log

## Specifications

  - Microcontroller: various
  - Version (Firmware): various
  - Versionmodul (FHEM Module): 3.5.1+20210228

**Comment by elektron-bbs** [comment]
Wozu braucht es require "99_Utils.pm"; in der 00_SIGNALduino.pm?
Wenn ich das auskommentiere kann ich keine Unterschiede feststellen, aber die Warnungen kommen nicht mehr.

**Comment by sidey79** [comment]
Das require ist dafür da, dass diese Perl Datei, ich will es nicht Modul nennen, geladen wird.
Andernfalls würden wir uns darauf verlassen, dass irgendwas dafür sorgt, diese Datei zu laden.

Ich habe festgestellt, wenn FHEM mit milnimalisten Definitionen im Testmodus läuft, dass es dieses Modul nicht eigenständig lädt.
Da wir aber Funktionen aus dieser Datei laden, habe ich es mit require eingebunden.

Hmm, war ja klar dass es hier mal wieder einen Konflikt gibt, weil fhem ja nicht über require lädt

**Comment by elektron-bbs** [comment]
Mit "Testmodus" meinst du wahrscheinlich deine Tests?
Im laufenden Betrieb sollte es nicht erforderlich zu sein, das Modul extra zu laden.
Zitat aus https://wiki.fhem.de/wiki/DevelopmentModuleIntro:

"Die Schlüsselnummer 99 hat hierbei eine besondere Bedeutung, da alle Module mit dieser Schlüsselnummer beim Start von FHEM automatisch geladen werden, selbst, wenn sie in der Konfiguration nicht verwendet werden."

Da wir z.B. "round" an vielen Stellen verwenden und das auch ohne require "99_Utils.pm" bisher funktionierte und auch jetzt noch funktioniert, gehe ich davon aus, das dieser Satz auch aktuell noch gültig ist.

**Comment by sidey79** [comment]
Hmm, das Laden hängt vom modpath ab und wenn der nicht definiert ist, dann wird relativ zum cwd versucht was zu laden.
Das liegt aber nicht unbedingt im cwd sondern relativ von fhem.pl.

Mit require ließ sich das lösen, da require relativ vom Programm arbeitet.

Blöde Situation, aber ich wüsste nicht, wie ich diesen Zustand umschiffen kann.
Das liegt ja ursächlich daran, dass fhem quasi core Bestandteile als fhem Modul lädt.

Ich kann natürlich ein Patch machen und 99 utils in ein Perl Modul konvertierten.
Das könnte das Problem lösen, aber ich bezweifle, dass der ohne weiteres akzeptiert wird

**Comment by HomeAutoUser** [comment]
@sidey79 i be back :-P

Vielleicht findest du hier https://forum.fhem.de/index.php?topic=19195.0 einen Hinweis.
Den Ansatz finde ich am besten, erst schauen ob es geladen wurde und wenn NICHT, dann den Bestandteil laden. Damit deckst du beide Fälle ab. (wenn bereits geladen + nicht geladen)

Ein ständiges laden finde ich auch überflüssig (mit den dazugehörigen Logeinträgen).
