### ISSUE TITLE
Add Flamenco module

### ISSUE THREAD

**Issue by sidey79** [RFD-FHEM/RFFHEM#95]
Demodulation wurde mit #21 implementiert.  Es wird noch ein logisches Modul benötigt um die Rauchmelder komfortabel in FHEM einzubinden.

**Comment by Ralf9** [comment]
anscheinend passt es noch nicht so richtig:
https://forum.fhem.de/index.php/topic,57735.msg525474.html#msg525474

vielleicht hilft das hier ein wenig weiter
https://github.com/pimatic/rfcontroljs/blob/master/lib/protocols/alarm1.js
https://github.com/pimatic/rfcontroljs/blob/master/lib/protocols/alarm2.js

**Comment by Ralf9** [comment]
Die ID 13.1 passt noch nicht so richtig
https://forum.fhem.de/index.php/topic,83356.0.html
Ich habe es bei mir angepasst:
https://github.com/Ralf9/RFFHEM/commit/0b48efce16fbd9caaab7a40eb488d2dac73fd3ef
