### ISSUE TITLE
README.md links to outdated thread on forum.fhem.de

### ISSUE THREAD

**Issue by gernot-h** [RFD-FHEM/RFFHEM#957]
## Expected Behavior

README.md should refer to some place in forum.fhem.de where the current development version can be discussed - if there is any?

## Actual Behavior

README.md here links to http://forum.fhem.de/index.php/topic,38831.0.html where there are explicit statements that this thread shall not be used any longer.

I would've created a PR if I would've found a better thread - or is forum.fhem.de not the preferred place to discuss r35 any more?

**Comment by sidey79** [comment]
I think best is the maintained section in the board:

https://forum.fhem.de/index.php?board=29.0
