### ISSUE TITLE
rfmode - from SD_ProtocolData.pm

### ISSUE THREAD

**Issue by HomeAutoUser** [RFD-FHEM/RFFHEM#980]
@sidey79, wie denkst du darüber?

https://github.com/RFD-FHEM/RFFHEM/blob/b0d916f668f430ae4a55e9d096145a5805b90b18/FHEM/00_SIGNALduino.pm#L273

Diese Zeile könnte man sicherlich auch sofort aus der `SD_ProtocolData.pm` generieren.
Indem man die Einträge wie 
https://github.com/RFD-FHEM/RFFHEM/blob/b0d916f668f430ae4a55e9d096145a5805b90b18/FHEM/lib/SD_ProtocolData.pm#L2771
https://github.com/RFD-FHEM/RFFHEM/blob/b0d916f668f430ae4a55e9d096145a5805b90b18/FHEM/lib/SD_ProtocolData.pm#L2858
zusammen in ein Array bringt.

Es hätte den Vorteil, das man nicht an 2 Stellen den Code pflegen muss immer.

**Comment by sidey79** [comment]
Ich denke da ebenso wie Du.

Kann auch sein dass ich das bei einem PR schon angemerkt hatte :)

Wir könnten eine Funktion in der SD_Protocols erstellen die den Key von allen Protokollen in einem Array übergibt.

`@List = getAllProps($self,$property);`

Für andere Fälle bräuchten wir aber noch die protocol ID zu dem Eintrag, da wäre dann ein Hash passender. Hmm.

**Comment by HomeAutoUser** [comment]
Wieder eine Funktion?
Was spricht dagegen wenn man bei dem vorhandenen Datensatz
https://github.com/RFD-FHEM/RFFHEM/blob/b0d916f668f430ae4a55e9d096145a5805b90b18/FHEM/00_SIGNALduino.pm#L410
direkt durchläuft. 
Alles was kein rfmode besitzt überspringen und zum Schluss einmal SlowRF hinzufügen.

**Comment by HomeAutoUser** [comment]
@sidey79 offene Frage https://github.com/RFD-FHEM/RFFHEM/issues/980#issuecomment-857027715
Könntest du dir das so vorstellen wie ich mir damals dachte?

**Comment by sidey79** [comment]
> 

Funktionen lassen sich gut testen und wenn ich es richtig deute, dann wollen wir Daten aus dem Objekt mit den Protokollen und nicht selbst darin rumsuchen müssen.
Zumindest theoretisch könnte dann auch mal ein anderes Modul die Daten verwenden, keine Ahnung ob es dafür einen Anwendungsfall geben wird.
So wäre es halt gekapselt.

**Comment by HomeAutoUser** [comment]
> Funktionen lassen sich gut testen und wenn ich es richtig deute, dann wollen wir Daten aus dem Objekt mit den Protokollen und nicht selbst darin rumsuchen müssen.
Zumindest theoretisch könnte dann auch mal ein anderes Modul die Daten verwenden, keine Ahnung ob es dafür einen Anwendungsfall geben wird.
So wäre es halt gekapselt.

Wir wollen die Datei `SD_ProtocolData.pm` durchlaufen lassen in einer Schleife und überall wo der Eintrag `rfmode          => '.....',` vorhanden ist erfassen. Somit erhalten wir eine Liste, welche weiterverarbeitet werden kann. Das bringt den Vorteil, das bei einer Protokollerweiterung nicht an 3 Stellen das gleiche eingetragen werden muss.

**Comment by sidey79** [comment]
Genau so habe ich das auch verstanden.

**Comment by elektron-bbs** [comment]
@sidey79 
Wir hatten uns eigentlich dadurch eine Vereinfachung der Programmierung gedacht.
Jetzt muss ich anstelle der 00_SIGNALduino.pm den Test anpassen :-(

00_SIGNALduino_initialize.t

```
    is(\@rfmodes,array {
            item 'rfmode:Avantek';
            item 'Bresser_5in1';
            item 'Bresser_6in1';
            item 'Fine_Offset_WH51_434';
            item 'Fine_Offset_WH51_868';
            item 'KOPP_FC';
            item 'Lacrosse_mode1';
```

Da hätten wir uns die Änderung auch sparen können :-(

Kannst du nicht im Test das Array dynamisch erstellen lassen?

**Comment by sidey79** [comment]
Hast Du eine Idee von wo wir die RFModes als Referenz bekommen?

**Comment by elektron-bbs** [comment]
Aus der SD_ProtocolData.pm?

**Comment by sidey79** [comment]
Hmm, die Extraktion verifizieren wir ja gerade.
Wir könnten den Test ändern, dass er nur die heute bekannten in einer undefierten Reihenfolge verifiziert.

Dann müsste es nicht angepasst werden. Die Sortierung testen wir dann halt nicht mit.

An dieser Stelle eine andere Protokolldatei (die sich nicht ändert) laden ginge auch, aber das ist etwas aufwändiger.

**Comment by elektron-bbs** [comment]
Meine Überlegung war eigentlich, das Array im Test auch dynamisch aus der SD_ProtocolData.pm erstellen zu lassen. Wenn beide Arrays dann identisch sind, sollte das auch reichen.

**Comment by sidey79** [comment]
@elektron-bbs 

Wie willst Du das machen? Wenn wir in beiden Fällen die gleiche Vorgehensweise verwenden, dann sind die doch auch identisch, wenn die Vorgehensweise fehlerhaft wäre.

**Comment by elektron-bbs** [comment]
Ich ging davon aus, das du prüfen willst, ob jemand in der 00_SIGNALduino.pm den Code geändert hat und dort dann etwas anderes heraus kommt.

**Comment by sidey79** [comment]
> 00_SIGNALduino_initialize

Also das wesentliche Ergebnis der sub ist, dass Variablen vorbereitet werden. Unter anderem, dass rfmode (eine globale Variable im Modul) Werte erhält und das AttributListe für rfmode in sortierter Reihenfolge erweitert wird.

Der Test prüft, ob die Werte dem erwarteten entsprechen. Die Herausforderung ist halt die Sortierung, solange nicht zwischendrin ein neuer RFMode erscheint, braucht es auch keine Anpassung am Test.

**Comment by elektron-bbs** [comment]
Dann lass halt Prüfung der Sortierung weg. Es sollte ja reichen, das geprüft wird, das noch mindestens die im Test vorhandenen rfmodes enthalten sind.
